### ISSUE TITLE
webpack-subresource-integrity plugin support

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#1126]
support object config，like https://modernjs.dev/builder/en/api/config-security.html#security-sri

**Comment by chenjiahan** [comment]
@bvanjoi Rsbuild needs to use this plugin, can you help to support it?

**Comment by bvanjoi** [comment]
Could you provide a basic example of how you intend to use this plugin? I'm uncertain about the specific features you require.

**Comment by chenjiahan** [comment]
bump

**Comment by sowtame** [comment]
bump

**Comment by chenjiahan** [comment]
duplicated with https://github.com/web-infra-dev/rspack/issues/4381
