### ISSUE TITLE
style-loader and css-loader compatibility

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#1245]

**Comment by ahabhgk** [comment]
@h-a-n-a Have we support style-loader and css-loader? Could you add some examples once we support, thanks!

**Comment by h-a-n-a** [comment]
> @h-a-n-a Have we support style-loader and css-loader? Could you add some examples once we support, thanks!

@ahabhgk There are some glitches with HMR. Example will be added once it resolved.

**Comment by h-a-n-a** [comment]
Closed in https://github.com/web-infra-dev/rspack/pull/2925.HMR glitch will be tracked in a new issue.
