### ISSUE TITLE
tracking community webpack plugin support

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1343]
our internal projects use lots of commnunity webpack plugins, it will be very unreal to implement these plugins all by ourself
* copy-webpack-plugin
* clean-webpack-plugin

**Comment by mysteryven** [comment]
Do you mean those plugins need to implement in Rust too ? If so, I am interested to implement someone.

**Comment by hardfist** [comment]
no, we're tracking the compatibility of community plugins
