### ISSUE TITLE
support cacheGroups[key].name function

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#1653]
needed in splitByModule strategy

https://github.com/web-infra-dev/modern.js/blob/v2.24.0/packages/builder/builder/src/plugins/splitChunks.ts#L169

**Comment by hyf0** [comment]
This blocks

- https://github.com/web-infra-dev/rspack/blob/aa9d7409a4dc6a28180cec04777b8d505f3dabdf/webpack-test/configCases/split-chunks-common/library

**Comment by hardfist** [comment]
> needed in splitByModule strategy
> 
> [modern-js-dev/modern.js@`main`/packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts#L142](https://github.com/modern-js-dev/modern.js/blob/main/packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts?rgh-link-date=2023-01-17T02%3A52%3A59Z#L142)

link is 404

**Comment by 9aoy** [comment]
https://github.com/web-infra-dev/modern.js/blob/v2.24.0/packages/builder/builder/src/plugins/splitChunks.ts#L169 
updated

**Comment by xc2** [comment]
`cacheGroups[key].name` function token:

- rspack: `(module: Module) => string`
- webpack: `<T>(module: T extends Module, selectedChunks: Chunk[], cacheGroupKey: string) => string`

related issues:

- [ ] #4953 `module.context`
- [ ] #4843 `module.size`, `module.context`

**Comment by chenjiahan** [comment]
This was supported by Rspack.

https://www.rspack.dev/plugins/webpack/split-chunks-plugin.html#splitchunksname
