### ISSUE TITLE
[Bug Report]: sass-embedded panic when force exit by ^C

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1741]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 276.14 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Yarn: 1.10.1 - ~/Library/Application Support/fnm/node-versions/v16.17.1/installation/bin/yarn
    npm: 8.15.0 - ~/Library/Application Support/fnm/node-versions/v16.17.1/installation/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 109.0
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.0.0-6530ad08f-20230202102742 => 0.0.0-6530ad08f-20230202102742 

### Details

![image](https://user-images.githubusercontent.com/8898718/216497157-91c1a366-50c4-42cf-a6f0-63ad56b4a0c5.png)

### Reproduce Steps

1. npm run dev
2. ctrl+c force exit devServer

**Comment by hyf0** [comment]
I guess this was solved. Create a new one if not.
