### ISSUE TITLE
[Bug Report]: missing runtime module when change file in devlopment

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1746]
### System Info

 System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.94 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/58961_1675443777679/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/58961_1675443777679/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 110.0
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: workspace:* => 0.0.21 
    @rspack/plugin-html: workspace:* => 0.0.21 

### Reproduce Steps

1. npm run dev
2. modify src/index.ts
3. visit localhost:port
see the following error
![image](https://user-images.githubusercontent.com/8898718/216664141-0fc14442-2112-47d2-9235-643c344e671b.png)

This is caused by missing runtime module definition in main.js chunk

**Comment by hyf0** [comment]
I guess this was solved. Create a new one if not.
