### ISSUE TITLE
[Feature Request]: Bridge rust fs with nodejs fs

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1758]
### What problem does this feature solve?

webpack-dev-server rely on outputFileSystem to access the build assets of rspack but for performance reason we wan't to keep build assets in rust side to avoid write | binding cost  in devServer  so use the normal nodejs filesystem as outputFileSystem won't work since we don't write assets to disk.
so we could proxy all the rust fs to nodejs fs and vice versa.

**Comment by h-a-n-a** [comment]
Closed as finished, leaving input file system to another one.
