### ISSUE TITLE
Rspack 0.1 Iteration Plan

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1769]
This document outlines our focused tasks for Rspack 0.1.  It minimally indicates intent to investigate tasks or contribute to an implementation. Nothing is set in stone, but we will strive to complete these tasks in a reasonable timeframe.

## Core Features
* Language Support: Support JavaScript、TypeScript、JSX|TSX、css、css modules、sass、image asset、json out of box
* Sourcemap : css、sass、javascript sourcemap support
* Tree Shaking:align tree shaking algorithm with webpack  https://github.com/modern-js-dev/rspack/issues/903
* Code Splitting & Bundle Splitting :  https://github.com/modern-js-dev/rspack/issues/1401
* DevServer : ailgn devServer logic with webpack
* Hot Module Replacement: 
## Compat
* Config Compat
* Plugin Compat
* Loader Compat
* Compilar API Compat
* Compilation API Compat
## Performance Optimization
* Incremental HMR Support
## Stability
* panic report 
## Infrastructure
* benchmarks
  *  build benchmark
  *  hmr benchmark
* stats diff like https://github.com/vercel/next.js/pull/45619#issuecomment-1419370027
## Website
* https://github.com/modern-js-dev/rspack-website/issues/2
## Ecosystem
* Showcase
* modern.js support 
* solid support
* nx support

**Comment by harrytran998** [comment]
In the future, should we make rspack can integrate with vite plugin? Bcs Vite has a large ecosystem, a lot of users use it.

**Comment by hardfist** [comment]
> In the future, should we make rspack can integrate with vite plugin? Bcs Vite has a large ecosystem, a lot of users use it.

you can use vite plugin by unplugin

**Comment by h-a-n-a** [comment]
Closed as finished
