### ISSUE TITLE
Iteration plan for April - June

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2048]
This issue serves as an Epic to provide transparency for our community and collaborators, internal and external, informed about our current goals and timelines.

We will be actively working on the tasks listed below, which have been aligned with our goals for the next three months (April - June 2023).

If you see something that is not in this list but is strongly needed. Please write a detailed requirement in this issue if you feel the need for feature prioritization. Also remember this is not a complete list so please search for relevant issues beforehand.

For broader collaboration, you can also find us on [discord](https://discord.com/invite/79ZZ66GH9E) if you need a quick chat.

## Loaders and Plugins

We are dedicated to investing significant time and resources into collaborating with the open source community on loaders and plugins. Pull requests are greatly welcomed and encouraged in this regard.

Unordered list:
```[tasklist]
- [ ] #2350
- [ ] #2591
- [ ] #2394
- [ ] #1749
- [ ] https://github.com/web-infra-dev/rspack/issues/2373
```

## APIs

Some of the loaders and plugins require additional APIs, they are tracked separately.

```[tasklist]
- [ ] #2385
- [ ] #2388 
- [ ] #2422
```

## Performance

To pave the road for caching abilities, we will start small and improve our HMR time first. This is driven by some of the mega projects internally.

```[tasklist]
- [ ] #2361
```

## Engineering

Our current top priority is to improve build and test infrastructure to offer better stability, so the core can be improved over time without breaking.

```[tasklist]
- [ ] #2410 
- [ ] #2581
- [ ] #2472
- [ ] #2485 
- [ ] #2413
- [ ] #2496 
- [ ] #2484
```

## Website
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack-website/issues/257
```
## Milestones

The iteration plan for tri-month divides into multiple milestones.

### Release 0.2.0 

Date | Event
-- | --
April 6th | Rspack 0.2.0 Roadmap Release
May 16th | Rspack 0.2.0 Release

**Features**

```[tasklist]
- [ ] #2350 
- [ ] #1749
- [ ] #2394 
```

**Comment by yufengwang** [comment]
6

**Comment by ityuany** [comment]
Can snapshots be continuously released, for example:

I noticed that inline-loader has already been merged, and I want to try it out directly, but there is no version available for me to try.

**Comment by hardfist** [comment]
> Can snapshots be continuously released, for example:
> 
> I noticed that inline-loader has already been merged, and I want to try it out directly, but there is no version available for me to try.

you can always use nightly version to test nightly build, just try `@rspack/cli@nightly`

**Comment by ityuany** [comment]
Is there an rspack feedback group?

**Comment by zackarychapple** [comment]
@hardfist should we add the second Angular tracking issue to this list?
