### ISSUE TITLE
[Feature Request]: Angular support

### ISSUE THREAD

**Issue by alfaproject** [web-infra-dev/rspack#2099]
### What problem does this feature solve?

Angular is working on an esbuild target to speed up Angular apps bundling but I was wondering if a similar work could be done using Rspack, perhaps with the help of the NX team

### What does the proposed API of configuration look like?

Drop in replacement for an Angular CLI or NX executor

**Comment by hardfist** [comment]
tracked in https://github.com/web-infra-dev/rspack/issues/3158
