### ISSUE TITLE
[Bug Report]: Postcss-loader with Tailwindcss HMR not work

### ISSUE THREAD

**Issue by skywalker512** [web-infra-dev/rspack#2103]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 319.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: 110.0.1587.69
    Safari: 16.3

### Details

Rspack did not trigger the update of src/styles/main.css (tailwind registered dependencies through postcss loader)

### Reproduce link

https://github.com/skywalker512/rspacksse-lite

### Reproduce Steps

pnpm i
pnpm dev
change tailwind css

**Comment by IWANABETHATGUY** [comment]
Thanks for reporting, but since this issue is duplicated with https://github.com/web-infra-dev/rspack/issues/2177, closed
