### ISSUE TITLE
[Bug Report]: Error accessing using the 'output' configuration in the documentation / rspack.config.js  

### ISSUE THREAD

**Issue by gxlself** [web-infra-dev/rspack#2109]
### System Info

output: {
   // filename: '[contenthash].bundle.js',
   publicPath: '/assets/',
    chunkFilename: '[id].chunk.js',
    assetModuleFilename: '[name][ext]',
  },

![image](https://user-images.githubusercontent.com/32733844/224210050-755fd2bb-9087-4aed-996e-69fb3dc86281.png)

### Details

Use the config and error in page

![image](https://user-images.githubusercontent.com/32733844/224210050-755fd2bb-9087-4aed-996e-69fb3dc86281.png)

![image](https://user-images.githubusercontent.com/32733844/224210166-99f1a1f7-dcc7-4f70-87fd-bf5f6ff9fd37.png)

### Reproduce Steps

```js
const path = require('path')
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	context: __dirname,
	output: {
		// filename: '[contenthash].bundle.js',
		publicPath: '/assets/',
    chunkFilename: '[id].chunk.js',
    assetModuleFilename: '[name][ext]',
  },
	entry: {
		main: "./src/main.jsx"
	},
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		]
	},
	module: {
		rules: [
			{
				test: /\.svg$/,
				type: "asset"
			}
		]
	},
	resolve: {
		alias: {
			"@": path.resolve(__dirname, './src')
		}
	}
};


```

```bash
yarn dev
```

**Comment by ahabhgk** [comment]
It is expected, webpack and webpack-dev-server does the same, when `output.publicPath` is set to `'/assets/'`, you need to access `http://{host}/assets/` in browser to get the request.

**Comment by ahabhgk** [comment]
Feel free to reopen if you have any further question.
