### ISSUE TITLE
[Bug Report]: when used tailwindcss, HMR randomly（Hot updates randomly updating）

### ISSUE THREAD

**Issue by gxlself** [web-infra-dev/rspack#2113]
### System Info

Mac
Rspack
tailwindcss
postcss
HMR

### Details

![image](https://user-images.githubusercontent.com/32733844/224216044-e468a97f-ffc1-4ed4-bc18-2d2d2c0718f2.png)

when i always change css name, HMR is not always update in page

### Reproduce Steps

```
yarn dev
```

**Comment by gxlself** [comment]
[https://github.com/web-infra-dev/rspack/issues/2103](#2103)
OK
find a repeat issue

**Comment by IWANABETHATGUY** [comment]
Thanks for reporting, Closed because it is duplicated with [https://github.com/web-infra-dev/rspack/issues/2103](https://github.com/web-infra-dev/rspack/issues/2113#2103)
