### ISSUE TITLE
[Feature Request]:  咨询下rspack和 webpack 版本 API 对齐，有没有接入计划 todolist 之类

### ISSUE THREAD

**Issue by jiangtao** [web-infra-dev/rspack#2114]
### What problem does this feature solve?

- [ ] webpack 版本 API 对齐
- [ ] 有没有接入计划 todolist 之类

### What does the proposed API of configuration look like?

如上.

**Comment by skywalker512** [comment]
https://github.com/KyrieLii/webpack-to-rspack

**Comment by h-a-n-a** [comment]
可以参考我们的文档：https://www.rspack.dev/zh/guide/config-diff.html

**Comment by jiangtao** [comment]
> 可以参考我们的文档：https://www.rspack.dev/zh/guide/config-diff.html

收到 源妹
