### ISSUE TITLE
想问一下，如何参与这个开源项目当中

### ISSUE THREAD

**Issue by Raywh** [web-infra-dev/rspack#2123]
前端（vue方向）开发四年，也在关注rust，奈何没有实践机会

**Comment by ycjcl868** [comment]
https://github.com/web-infra-dev/rspack/blob/main/CONTRIBUTING.md

**Comment by Raywh** [comment]
> https://github.com/web-infra-dev/rspack/blob/main/CONTRIBUTING.md

Thank you very much.

**Comment by h-a-n-a** [comment]
Closed. Feel free to open a discussion this if you have any further questions.
