### ISSUE TITLE
[Feature Request]: How to configure the generation of .d.ts files?

### ISSUE THREAD

**Issue by luojinghui** [web-infra-dev/rspack#2135]
### What problem does this feature solve?

When building typescirpt files, how to generate .d.ts type files through rspack？

### What does the proposed API of configuration look like?

N/A

**Comment by h-a-n-a** [comment]
Currently, we don't have any plan for generating .d.ts files natively, as it leverages some features from the TypeScript compiler.

**Comment by luojinghui** [comment]
The temp solution is compiled by TSC, and the correct way should be to open the configuration of ts-loader under rspack
