### ISSUE TITLE
[Bug Report]: Error: Failed to convert JavaScript value `Boolean true ` into rust type `String`

### ISSUE THREAD

**Issue by shunyue1320** [web-infra-dev/rspack#2145]
### System Info

windows 11

### Details

![image](https://user-images.githubusercontent.com/47295879/224295530-8abd4728-dc03-4f65-a01a-335b529cfa92.png)

### Reproduce link

no

### Reproduce Steps

run `rspack serve`

**Comment by IWANABETHATGUY** [comment]
Would you mind pasting the `rspack.config.js` or giving us a minimum reproduce demo?

**Comment by shunyue1320** [comment]
```js
builtins: {
  html: [
    {
      template: "./src/main.html",
      filename: "main.html",
      inject: true,   //  It is caused by inject: true
    },
  ],
}
```

**Comment by lxfxy** [comment]
```ts
inject?: "head" | "body"
```
