### ISSUE TITLE
Offensive project name

### ISSUE THREAD

**Issue by ghost** [web-infra-dev/rspack#2157]
Please consider renaming this project. The term "spack" (from the etymology "spastic" -> "spacker") is a highly offensive term for someone with cerebral palsy, in British English. 

Naming your project "r spack" is far too close to this insulting term for such differently able people, and puts your project in breach of its own code of conduct.

Thank you for your consideration on this matter.

**Comment by hardfist** [comment]
you can treat it as rs-pack

**Comment by hardfist** [comment]
We took your tip very seriously, consulted with a number of relevant linguists, and investigated the situation of similarly named open source projects. We don't think it's necessary to change the project name at this time.
