### ISSUE TITLE
[Feature Request]: Native WebAssembly Support

### ISSUE THREAD

**Issue by ulivz** [web-infra-dev/rspack#2158]
### What problem does this feature solve?

Currently Rspack doesn't support load `*.wasm` file:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/23133919/224460973-ea2f4123-9ab6-4af7-a97e-5e75f0b32cf8.png">

I just created a reproduction here: https://github.com/ulivz/rusty-react, reproduction steps are as follows:

```
git clone git@github.com:joshfinnie/rusty-react.git
cd rusty-react
pnpm i
pnpm run dev
```

Refs:

- Rspack: https://github.com/web-infra-dev/rspack/blob/b4f206819061e0d6efd19b33886aad9430478f49/crates/node_binding/src/js_values/source.rs#L69-L72
- Webpack: https://github.com/webpack/webpack/blob/main/lib/wasm-sync/WebAssemblyParser.js

### What does the proposed API of configuration look like?

1. Introduce native WebAssembly support like [Webpack](https://webpack.js.org/concepts/modules/#supported-module-types).
2. Introduce [experiments.asyncWebAssembly](https://webpack.js.org/configuration/experiments/#experiments) support.

**Comment by tuchg** [comment]
@hardfist  hi,guys  I'm very interested in this feature, can you assign it to me?
