### ISSUE TITLE
[Bug Report]: Unbelievable memory usage, even 16+8GB swap is not enough.

### ISSUE THREAD

**Issue by tuchg** [web-infra-dev/rspack#2163]
### System Info

  System:
    OS: Linux 6.0 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 4800U
    Memory: 12.68 GB / 15.00 GB
    Container: Yes
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  npmPackages:
    @rspack/cli: workspace:* => 0.1.0

### Details

After cloning the repository, I tried to run the rspack test and my vscode crashed. Upon checking `htop`， I found that the memory was overloaded. Afterwards, I tried adding an 8GB swap file, but it still couldn't meet the requirements of rspack.

### Reproduce Steps

to exec `cargo test` in rspack repo

**Comment by Boshen** [comment]
Running `cargo test` in a terminal only uses a small amount of memory, I can't really tell what's happening with VSCode in this case. Is the `cargo test` process taking a lot of memory or is it some other process?

**Comment by tuchg** [comment]
> Running `cargo test` in a terminal only uses a small amount of memory, I can't really tell what's happening with VSCode in this case. Is the `cargo test` process taking a lot of memory or is it some other process?

maybe it's an issue with my system's kernel, not due to VSCode. 
When I run `cargo test` on my system, it encounters OOM during the Cargo Building phase, but `cargo build` is ok.

I have briefly checked the system logs. 
output: `Killed process 15803 (ld) total-vm:1417440kB, anon-rss:956624kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:2812kB oom_score_adj:200`
