### ISSUE TITLE
[Bug Report]: useRoutes() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by LironHazan** [web-infra-dev/rspack#2166]
### System Info

  System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 534.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v16.10.0/bin/npm

  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 68.0
    Firefox Nightly: 110.0a1
    Safari: 15.4

  npmPackages:
    @rspack/core: 0.1.0 => 0.1.0 
    @rspack/dev-server: 0.1.0 => 0.1.0 
    @rspack/plugin-minify: 0.1.0 => 0.1.0 

### Details

Hey thanks for this great project! looks promising!

In my [nx monorepo](https://github.com/LironHazan/g_api/tree/rspack-gapi) I've installed the `@nrwl/rspack` plugin 
and created a [new app ](https://github.com/LironHazan/g_api/tree/rspack-gapi/apps/rspack-gapi),
Since my modules are completely decoupled (NX is awesome...), I created the App component similar to the [webpack app ](https://github.com/LironHazan/g_api/tree/rspack-gapi/apps/gapi) one - both points to the same lib (run nx graph to easily visualize it), 
But when running the rspack app the following error appears:

```
Uncaught Error: useRoutes() may be used only in the context of a <Router> component.
    at invariant (router.js:270:11)
    at useRoutes (index.js:474:76)
    at Routes (index.js:1161:10)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

You can run the webpack app as well to see that it plays well,
Both App components are identical :)

I hope I'm not miss-using it, feel free to play with my project, 
Let me know if I can help / contribute as well! ❤️ 

### Reproduce link

https://github.com/LironHazan/g_api/tree/rspack-gapi

### Reproduce Steps

1. Install monorepo deps (`npm i`)
2. Start rspack app: `npm run start:rspack-gapi`
3. Browse to the app, open the devtools to see console errors

**Comment by LironHazan** [comment]
BTW I tested it with a newer node version as well so it's not related to that
```
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
```

**Comment by bvanjoi** [comment]
This should not be a Rspack build issue, you can add a `<BrowserRouter>xxxx</BrowserRouter>` to [apps/rspack-gapi/src/main.tsx](https://github.com/LironHazan/g_api/blob/rspack-gapi/apps/rspack-gapi/src/main.tsx#L12-L14), as you did in [apps/gapi/src/main.tsx](https://github.com/LironHazan/g_api/blob/rspack-gapi/apps/gapi/src/main.tsx#L26-L30), and maybe that will solve your problem.

**Comment by LironHazan** [comment]
Thanks I missed that..!
