### ISSUE TITLE
[Bug Report]:  HMR module log circular printing

### ISSUE THREAD

**Issue by xiaochuan1719** [web-infra-dev/rspack#2169]
### System Info

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.67 GB / 15.88 GB
  Binaries:
    Node: 18.13.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.3 - D:\Programs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.69)
  npmPackages:
    @rspack/cli: latest => 0.1.0

### Details

pnpm v7.29.1

The browser found that the HMR module has been printing logs in a loop.

When the component code is edited and saved, a hot update is triggered, and then the HMR module appears in the console to keep printing logs.
![GIF 2023-03-11 21-45-04](https://user-images.githubusercontent.com/38381164/224488744-b38bb818-e41c-46f5-b5a3-ade792358c67.gif)

### Reproduce Steps

1、 `pnpm create rspack`
2、`pnpm dev`
3、Create a Button component
4、Import Button component into App.jsx
5、Save component code file
6、Observe the browser console

**Comment by bvanjoi** [comment]
I couldn't reproduce the problem the way you did, maybe it's a problem with my computer system or maybe it's missing some steps. Can you post a repository where you can reproduce the problem.
