### ISSUE TITLE
about the name in readme

### ISSUE THREAD

**Issue by liuyib** [web-infra-dev/rspack#2175]
Refer: https://www.rspack.dev/misc/branding.html#the-name

<img width="838" alt="image" src="https://user-images.githubusercontent.com/38221479/224503847-7e86382b-9043-495a-9bbd-23d3ec66dab5.png">

It should be `Rspack`  :)

**Comment by h-a-n-a** [comment]
Nice catch! We will take a look into this.

**Comment by liuyib** [comment]
done, now closed
