### ISSUE TITLE
[Bug Report]: Tailwindcss can't hmr when use postcss-loader 

### ISSUE THREAD

**Issue by zhoushaw** [web-infra-dev/rspack#2177]
### System Info

System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 205.58 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/94375_1678589443898/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/94375_1678589443898/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/94375_1678589443898/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.1
  npmPackages:
    @rspack/cli: latest => 0.0.24

### Details

When I use the CDN approach (https://tailwindcss.com/docs/installation/play-cdn) to use Tailwindcss, HMR works. 
However, when I use the `postcss-loader`(https://www.rspack.dev/guide/language-support.html#tailwind-css) approach to ensure that only the required CSS content is imported, the Tailwindcss class does not load correctly when I update my content's className. I have to restart the dev server to get it to work correctly.

> config 

```javascript
// rspack.config.js
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	context: __dirname,
	entry: {
		main: "./src/main.jsx"
	},
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		]
	},
	module: {
		rules: [
			{
				test: /\.svg$/,
				type: "asset"
			},
			{
				test: /\.css$/,
				use: [
				  {
					loader: 'postcss-loader',
					options: {
					  postcssOptions: {
						plugins: {
						  tailwindcss: {},
						},
					  },
					},
				  },
				],
				type: 'css',
			  },
		]
	}
};

```

> package.json

```json
{
  "name": "rspack-react-starter",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "rspack serve",
    "build": "rspack build"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@rspack/cli": "latest",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.8",
    "postcss": "^8.4.21",
    "postcss-loader": "^7.0.2",
    "tailwindcss": "^3.2.7"
  }
}
```

> tailwind.config.js

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {},
    },
    plugins: [],
}
```

### Reproduce link

https://github.com/zhoushaw/tailwind-hmr-problem

### Reproduce Steps

1. pnpm install
2. pnpm run dev
3. add new Tailwindcss  className to App Component
4. HMR can't take effect
5. restart server will see take effect
![image](https://user-images.githubusercontent.com/27547179/224523888-2d90e9df-52df-4c09-b871-9532b743c68f.png)

**Comment by bvanjoi** [comment]
I can't reproduce this problem:

https://user-images.githubusercontent.com/30187863/224528564-17fc4222-4bfb-48fe-8845-7e5e19fd8d4a.mov

**Comment by zhoushaw** [comment]
Maybe you could add more className to repeat the question

**Comment by bvanjoi** [comment]
I have reproduced other similar problems, but this should not be due to Tailwind, even normal css can have problems, I will try to fix it later

**Comment by zhoushaw** [comment]
You need to start the development server and then modify the className. I think the postcss-loader is invalid in HMR.

**Comment by bvanjoi** [comment]
This is an issue in the incremental update logic, a temporary solution:

```js
// rspack.config.js
module.exports = {
    // xxxxxx
    experiments: {
        incrementalRebuild: false
     }
}
```

**Comment by zhoushaw** [comment]
Repeat issue: #2103

**Comment by skywalker512** [comment]
I still have a problem. Please help me take a look here. I downloaded the corresponding [node file](https://github.com/web-infra-dev/rspack/suites/11520194665/artifacts/595825479) from this [Github action Artifacts](https://github.com/web-infra-dev/rspack/actions/runs/4404036702) and modified the @rspack/binding to apply your changes. However, when I modify the tailwind atomic CSS, tailwindcss still does not generate the corresponding CSS.

https://github.com/skywalker512/rspack-tailwind-hmr-problem

DEBUG=1 pnpm dev

only first time tailwindcss will Create context

<img width="697" alt="image" src="https://user-images.githubusercontent.com/12960906/224762625-04c531b8-74c3-4544-9456-30cb07e4e381.png">

I'm familiar with webpack and rust, tailwindcss. I don't know why I have such a problem.

**Comment by ckken** [comment]
same here
