### ISSUE TITLE
[Bug Report]: HMR very slow when using rspack postcss loader

### ISSUE THREAD

**Issue by fz6m** [web-infra-dev/rspack#2180]
### System Info

  System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 4.21 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/Library/Caches/fnm_multishells/34472_1678607522204/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/34472_1678607522204/bin/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.2
  npmPackages:
    @rspack/cli: latest => 0.1.0 
    @rspack/postcss-loader: latest => 0.1.0

### Details

When using rspack postcss loader, if you import `antd/dist/antd.min.css` :

```ts
import "antd/dist/antd.min.css";
```

Start project, HMR need 26 seconds + 

But, if you import `antd/dist/antd.css` : 

```ts
import 'antd/dist/antd.css'
```

It works well

### Reproduce link

https://github.com/MoeYc/rspack-bug-hmr-very-slow

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by bvanjoi** [comment]
I will check it now

**Comment by bvanjoi** [comment]
> This issue was not fixed in `0.1.1`

For more information on how long your hmr takes?

**Comment by fz6m** [comment]
Each cold start and hmr takes 25s+ , just a minimal demo :

<img src='https://user-images.githubusercontent.com/59400654/225674960-2b752b7c-a115-40ab-b121-cdbdbeab57bd.png' width='50%' />

I found that a lot of time was spent in `processing assets` :

<img src='https://user-images.githubusercontent.com/59400654/225673679-1243892a-272a-4a81-92d8-8ebf9eb8b84a.png' width='50%' />

**Comment by bvanjoi** [comment]
Really sad news, there should be a lot of room for optimisation in this piece.

You can get around this by temporarily making `devtool: false`.

**Comment by fz6m** [comment]
Set `devtool: false` , it works 👍🏻

Expect to see this issue resolved
