### ISSUE TITLE
[Bug Report]: package.json scripts don't run 

### ISSUE THREAD

**Issue by asrvd** [web-infra-dev/rspack#2185]
### System Info

 System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 480.56 MB / 7.73 GB
  Binaries:
    Node: 16.16.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    npm: 8.11.0 - ~\scoop\apps\nodejs-lts\current\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.22621.1

### Details

The `pnpm format:js` or `pnpm lint:js` commands and all the scripts that use the pattern `./x ......` don't run, here's the error that I get, it's also preventing me from committing my changes as pre-commit hooks have format cmds.

![image](https://user-images.githubusercontent.com/68690233/224537727-a28d57bf-8b5f-4160-8f8f-17b695573f45.png)

![image](https://user-images.githubusercontent.com/68690233/224537704-9ba27113-a31e-4b73-a7a4-f89b052fa8b0.png)

### Reproduce Steps

1. Clone the repo, setup everything locally
2. Run the command `pnpm format:js` or `pnpm format:rs`

**Comment by hardfist** [comment]
seems windows compat problem, you can run `node ./x format js` to bypass this problem, we're gonna fix windows problems later.

**Comment by asrvd** [comment]
> node ./x format js

the thing is, pre-commit hooks are not letting me commit my changes, how am i supposed to make a pr?
