### ISSUE TITLE
[Feature Request]: Write rspack config in typescript

### ISSUE THREAD

**Issue by marco2216** [web-infra-dev/rspack#2188]
### What problem does this feature solve?

Webpack config can be written [in a ts file](https://webpack.js.org/configuration/configuration-languages/) (webpack.config.ts). It would be very helpful to be able to do this for rspack as well, since we get type and ESM syntax support, and it makes it much easier to migrate existing configs to rspack. (existing webpack config may also have dependencies on other TS files, so it's not good to have to convert those to JS as well.)

### What does the proposed API of configuration look like?

rspack.config.ts - follow webpack.

**Comment by hardfist** [comment]
you can use ts-node/register to handle ts config support right now, we will support ts config out of box in the future
* rspack.config.js
```js
require('ts-node/register');
your config here
```

**Comment by HerringtonDarkholme** [comment]
Hi rspack team, I found webpack uses [rechoir](https://www.npmjs.com/package/rechoir) and [interpret](https://github.com/gulpjs/interpret) to load JS variants. Is it the desirable way to do it? Or do you prefer using minimal dependencies?

**Comment by hardfist** [comment]
we prefer minimal

**Comment by leimonio** [comment]
What is the performance of using `.js` vs `.ts` rspack configuration files?

**Comment by leimonio** [comment]
Also might be  bit early, but any idea how the [NodeJS experimental Typescript Support](https://github.com/nodejs/loaders/issues/217) will change the current approach?
