### ISSUE TITLE
[Bug Report]: arco-pro example not working

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#2189]
### System Info

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 243.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 14.1.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.0 
    @rspack/plugin-html: workspace:* => 0.1.0 

### Details

`examples/arco-pro`  cannot be run with the following error
![image](https://user-images.githubusercontent.com/7599351/224546061-c8913664-d53d-41ba-9d08-59aee96a2846.png)

### Reproduce Steps

cd `examples/arco-pro`
pnpm  dev

**Comment by IWANABETHATGUY** [comment]
I can't reproduce this error.

**Comment by xierenyuan** [comment]
> I can't reproduce this error.
my other examples are working, I'm not sure if my computer is the only one with this problem I'll copy this demo out and try it later

**Comment by IWANABETHATGUY** [comment]
I can reproduce this now
![image](https://user-images.githubusercontent.com/17974631/225221255-3b4ca821-473c-48e6-94bf-2f60acb0c9d4.png)

**Comment by IWANABETHATGUY** [comment]
Please try to use `pnpm --filter @rspack/binding build:release` to compile your binding before run `pnpm dev` .
It seems that swc has some issues compiling big file in debug mode.

**Comment by IWANABETHATGUY** [comment]
Since this issue could only be reproduced in debug mode, closed. Feel free to reopen if you have any further questions.
