### ISSUE TITLE
[Debugging Report]: `#![feature int_roundings]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by ycjcl868** [web-infra-dev/rspack#2192]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 198.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/Library/Caches/fnm_multishells/3220_1678612243488/bin/node
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/3220_1678612243488/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @rspack/cli: workspace:* => 0.1.0 

### Details

`cargo build` throw error:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/13595509/224552787-2adc9846-017c-4c4d-818e-63daf88ca4f5.png">

`rustup toolchain list` show:

```bash
❯ rustup toolchain list
stable-aarch64-apple-darwin
nightly-2022-12-15-aarch64-apple-darwin (default) (override)
nightly-aarch64-apple-darwin
```

### Reproduce Steps

1. run `cargo clean && cargo build`

**Comment by hardfist** [comment]
we don't use stable channel please check your `rustup show` result to see whether you use the right nightly version
![image](https://user-images.githubusercontent.com/8898718/224557270-d414edb1-9a14-4227-8e9d-b42b0154595b.png)

**Comment by ycjcl868** [comment]
> we don't use stable channel please check your `rustup show` result to see whether you use the right nightly version ![image](https://user-images.githubusercontent.com/8898718/224557270-d414edb1-9a14-4227-8e9d-b42b0154595b.png) we configure the rust version in https://github.com/web-infra-dev/rspack/blob/main/rust-toolchain.toml, if your active toolchain is not `nightly-2022-12-15` you toolchain version may be override by other global configuration

```bash
❯ rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/jcl/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-12-15-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

active toolchain
----------------

nightly-2022-12-15-aarch64-apple-darwin (overridden by '/Users/jcl/github/web-infra-dev/rspack/rust-toolchain.toml')
rustc 1.68.0-nightly (b70baa4f9 2022-12-14)
```

**Comment by Boshen** [comment]
@ycjcl868 can you check if you have `RUSTC_WRAPPER` env set to a stable rustc?

**Comment by ycjcl868** [comment]
> 

Fixed by `brew uninstall rust`, because there is a conflict between the `brew install rust`and `rustup` install.
