### ISSUE TITLE
webpack-manifest-plugin support

### ISSUE THREAD

**Issue by minoritea** [web-infra-dev/rspack#2196]
We are using [webpack-manifest-plugin](https://github.com/shellscape/webpack-manifest-plugin) to generate manifest.json, but this plugin causes a runtime error with rspack.

> Error: napi error: GenericFailure - Error: processAssets hook uses custom stage number is not supported.

We are using manifest.json only to get the mapping of file names with fingerprints and original file names.

Do you have any plans to support this plugin? I'm fine with any other workaround if there is one.

**Comment by hardfist** [comment]
i investigate the implementation and find it relyes on lots of api we dont support yet, we are gonna provide workaround for it

**Comment by hardfist** [comment]
you can use rspack-manifest-plugin in rspack@nightly now, see example here https://github.com/web-infra-dev/rspack/blob/main/examples/plugin-compat/rspack.config.js#L65

**Comment by hardfist** [comment]
@minoritea can you help check whether rspack-manifest-plugin works for you

**Comment by hardfist** [comment]
closing as has workaround, if anyone met problem again feel free to reopen it

**Comment by minoritea** [comment]
I'm sorry, I didn't notice the mention and the reply was late.
I'm very happy that the plugin has been implemented!
I'll check later if it works as expected in our application.

**Comment by piotrpalek** [comment]
I have explored rspack and this does not work for our app, the build crashes with a SIGFAULT in our case
