### ISSUE TITLE
[Feature Request]: Set custom environment variables

### ISSUE THREAD

**Issue by szkj-web-he** [web-infra-dev/rspack#2206]
### What problem does this feature solve?

How to set?

new webpack.DefinePlugin({
             'process.env': {
                NODE_ENV: 'a',
                BASENAME: 'b',
            },
        }),

### What does the proposed API of configuration look like?

...

**Comment by IWANABETHATGUY** [comment]
please refer to https://www.rspack.dev/config/builtins.html#builtinsdefine

**Comment by IWANABETHATGUY** [comment]
feel free to reopen this issue if you have any future question
