### ISSUE TITLE
[Feature Request]: 支持 dotenv

### ISSUE THREAD

**Issue by xezzon** [web-infra-dev/rspack#2208]
### What problem does this feature solve?

构建时可以从以下环境中读取环境变量（优先级从低到高）：

- .env
- .env.local
- .env.[mode]
- .env.[mode].local

将结果作为 [Rspack 配置函数](https://www.rspack.dev/config.html#exporting-a-configuration-function) 的 env 参数（以上文件的优先级低于命令行的 env 参数）。并且自动将其设置到 `process.env` 中。

以 create-rspack 生成的项目，应该在 `.gitignore` 中包含 `*.local` ，以保证其只在本地生效，而不被 Git 追踪。

### What does the proposed API of configuration look like?

参考 [Vite 环境变量与模式](https://vitejs.dev/guide/env-and-mode.html)。

**Comment by IWANABETHATGUY** [comment]
I will try if a plugin could solve it.

**Comment by IWANABETHATGUY** [comment]
rspack-cli 目前的定位更偏向于 `webpack-cli` 不像 `cra` 或者 `vite` 所以我们可能会更加偏向使用 plugin 来支持

**Comment by IWANABETHATGUY** [comment]
https://github.com/IWANABETHATGUY/rspack-plugin-dotenv
可以试试 安装这个包，你如果有更多定制化的需求，可以fork 一份自己修改，目前我们目标是兼容 webpack 生态，为了让 webpack 用户平滑迁移，可能不会让这个 plugin 变得和 vite一样。
你可以自己修改并且适配，修改方法非常简单，https://github.com/IWANABETHATGUY/rspack-plugin-dotenv/commit/b982ad2c38172d69f8276d349ee03494fa0d8cd6#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R53-R59

**Comment by xezzon** [comment]
OK，有劳了。
