### ISSUE TITLE
[Feature Request]: 原生css 支持 css loader的更多配置

### ISSUE THREAD

**Issue by crazyxhz** [web-infra-dev/rspack#2223]
### What problem does this feature solve?

原生css的支持只有css module 的3个参数；

css loader本身的很多能力不知道是否支持配置?

https://webpack.js.org/loaders/css-loader/#options

### What does the proposed API of configuration look like?

支持css 的更多配置

**Comment by h-a-n-a** [comment]
除了文档中的参数目前还没有其他支持的计划，不妨可以说说你用到的配置项，我们根据优先级进行支持。

**Comment by wangtao0101** [comment]
@crazyxhz getLocalIdent 参数能否支持

**Comment by hardfist** [comment]
我们这部分和webpack的experiments.css功能进行对齐，如果需要一些定制功能，可以尝试给webpack侧提对应需求
