### ISSUE TITLE
[Feature Request]: 支持inline loader

### ISSUE THREAD

**Issue by baozouai** [web-infra-dev/rspack#2225]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/33510001/224724803-e4ea273a-7e48-4535-a410-2d7dd3ae1e0e.png)
项目中用到了inline loader来处理lesss，但是启动的时候报错，看文档好像没有处理inline loader相关的？请问是否还不支持？

### What does the proposed API of configuration look like?

像webpack一样支持

**Comment by h-a-n-a** [comment]
It does not supported at the moment. This is already on our roadmap and will be supported in the near future. So stay tuned!

**Comment by h-a-n-a** [comment]
Closed and in favor of https://github.com/web-infra-dev/rspack/issues/1749
