### ISSUE TITLE
[Bug Report]: create-rspack command error 

### ISSUE THREAD

**Issue by PengBoUESTC** [web-infra-dev/rspack#2241]
### System Info

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 169.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Browsers:
    Edge: 97.0.1072.62

### Details

yargs 生成的命令行，默认命令handler 为异步时，help 不好使

### Reproduce Steps

cd packages/create-rspack

node ./index.js help

https://github.com/yargs/yargs/issues/2312

**Comment by hardfist** [comment]
fixed in #2244
