### ISSUE TITLE
[Feature Request]: Supports magic comment `webpackChunkName`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2245]
### What problem does this feature solve?

To give chunk a readable name.

### What does the proposed API of configuration look like?

![img_v2_8fd31df2-84d3-4c23-a17f-92a061deeb1g](https://user-images.githubusercontent.com/49502170/224940905-a69e72a1-4a8f-4ebc-8033-4c3c029f619e.jpg)

**Comment by wsz7777** [comment]
when i can use this feature ?

**Comment by hyf0** [comment]
> when i can use this feature ?

Just a quick note to let you know that I am planning to finish this task on Friday, unless something else comes up unexpectedly.

**Comment by hyf0** [comment]
Duplicate to https://github.com/web-infra-dev/rspack/issues/2385
