### ISSUE TITLE
[Bug Report]: ReactComponent as SomeSvg/Scss modules

### ISSUE THREAD

**Issue by aslanalyiev** [web-infra-dev/rspack#2256]
### System Info

 System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 181.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @rspack/cli: ^0.1.0 => 0.1.0
    @rspack/plugin-node-polyfill: ^0.1.0 => 0.1.0

### Details

Trying to migrate from craco to your package, using TS(baseURL/target-2020), svg, scss modules, and common scss and getting these errors(a lot of them): 

<img width="808" alt="image" src="https://user-images.githubusercontent.com/99654428/225125300-57eed059-a92d-42b1-ad1e-3de57a56a4d1.png">
<img width="822" alt="image" src="https://user-images.githubusercontent.com/99654428/225126184-157f72b3-6562-4a13-ac02-b1304a944ada.png">

here is my setup:

```
const CopyPlugin = require('copy-webpack-plugin');
const NodePolyfill = require('@rspack/plugin-node-polyfill');
/*
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  entry: {
    main: './src/index.tsx', // Configure the project entry file
  },
  builtins: {
    html: [
      {
        template: './public/index.html', // Align CRA to generate index.html
      },
    ],
  },
  plugins: [
    new CopyPlugin([
      {
        from: 'public',
        to: '.',
      },
    ]),
    new NodePolyfill()
  ], // Copy the files from the public directory to the dist directory, aligning the behavior of the CRA
  rules: [
    {
        test: /\.ts$/,
        type: 'tsx',
      },
{
  test: /\.s[ac]ss$/i,
  use: [
    {
      loader: "sass-loader",
      options: {
        implementation: require("sass"),
      }
    }
  ],
  type: 'css'
},
      {
        test: /\.png$/,
        type: 'asset',
      },
      {
        test: /\.svg$/i,
        use: ['@svgr/webpack', 'url-loader'],
      },
  ],
  resolve: {
    modules: ["node_modules", "./src"],
    tsConfigPath: "./tsconfig.json"
  }
};
```

### Reproduce Steps

run rspack serve with ts(baseUrl)/scss modules/svg imported like this:

`import { ReactComponent as SomeSvg } from "assets/images/icons/some.svg";`

**Comment by ahabhgk** [comment]
`rules` field is not valid, it should be `module: { rules: [...] }`

**Comment by ahabhgk** [comment]
Feel free to reopen if you have any further questions.
