### ISSUE TITLE
[Feature Request]: Support extensionAlias field

### ISSUE THREAD

**Issue by patricklafrance** [web-infra-dev/rspack#2257]
### What problem does this feature solve?

As mentionned in the following [discussion](https://github.com/webpack/webpack/discussions/16083) and [issue](https://github.com/webpack/webpack/issues/13252), to use Wepack (now rspack) with an ESM + TypeScript setup, the bundlers should support file extensions aliases to enable the following syntax:

```js
// Importing from button.tsx but using the ".js" file extension to satisfy TypeScript.

import type { ButtonProps } from "./button.js"
```

As ESM is getting quite popular it would be great to have support for [extensionAlias](https://webpack.js.org/configuration/resolve/#resolveextensionalias) sooner than later 🙏🏻 

TypeScript 5.0 comes with a ["bundler mode" module resolution](https://webpack.js.org/configuration/resolve/#resolveextensionalias) which should fix the issue but it would still be useful for organization which cannot move to TS 5.0.

Thank you

### What does the proposed API of configuration look like?

Same as Webpack https://webpack.js.org/configuration/resolve/#resolveextensionalias

**Comment by jraoult** [comment]
@patricklafrance I just found this issue while trying to migrate from Webpack. Has it been really implemented and released? My configuration gets rejected with the following:
```bash
 configuration.resolve has an unknown property 'extensionAlias'
```

**Comment by patricklafrance** [comment]
@jraoult it has not been implementend. I closed the issue because it’s not necessary anymore with TS 5 offering the allowImportingTsExtensions configuration field.

**Comment by jraoult** [comment]
@patricklafrance thx for your reply. In my case, `allowImportingTsExtensions ` doesn't provide the same benefits as `extensionAlias`. I'm sharing modules between Node and the browser. It's essential to be able to write `import {...} from "./myModule.js"` so it can be resolved once transpiled for the Node side (cf. https://www.typescriptlang.org/docs/handbook/esm-node.html). Neither `import {...} from "./myModule.ts"` nor `import {...} from "./myModule"` would work when using ESM resolution. So my solution was always to write the full import path with the `.js` extension and then get Webpack to try the `.ts` and `.tsx` when the `.js` doesn't resolve to an existing file. 

Would you reconsider the decision not to implement it?

**Comment by patricklafrance** [comment]
Hey @jraoult 

I initally created an issue but I thought it was required to support ESM+TS+Webpack but I am not a maintainer nor contributor of `rspack`, there I have no say in that :)

Since this one is close and your use case is different, I would recommend creating a new issue.

**Comment by jraoult** [comment]
@patricklafrance, my bad. Somehow I assumed you were one of the maintainers 😀. I'll create a new request then.
