### ISSUE TITLE
Refactor: unify task script

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2261]
we're using makefile、js scritps、shell、xtask to manual tasks and it's kind of messy and cause confusions for outside contributors, so we should unify all the task scripts.
there are some requirements for task scripts:

* cross platform compatible
* easy to maintain
* easy to debug

there are some options now:
* https://github.com/google/zx
* npm scripts
* js scripts
* shell

**Comment by Boshen** [comment]
Rome uses https://github.com/casey/just.

This looks kind of nice: https://github.com/rome/tools/blob/main/justfile

**Comment by zakuru** [comment]
Hi,

For the calls to './x' would it make sense to replace them by 'node x' or it causes trouble ?
I can open a PR for it if it makes sense to you

**Comment by hyf0** [comment]
> Hi,
> 
> For the calls to './x' would it make sense to replace them by 'node x' or it causes trouble ? I can open a PR for it if it makes sense to you

We are going to remove `./x` soon/next week, which causes many cross-platform problems and so on. We would switch to `npm scripts` + `zx` to have consistent experiences for any platform.

**Comment by zakuru** [comment]
> > Hi,
> > 
> > For the calls to './x' would it make sense to replace them by 'node x' or it causes trouble ? I can open a PR for it if it makes sense to you
> 
> Thanks for bringing this up. We are going to remove `./x` soon/next week, which causes many cross-platform problems and so on. We would switch to `npm scripts` + `zx` to have consistent experiences for any platform.

Super 👌 
Thanks

**Comment by hyf0** [comment]
Sync up:

The Rspack team has met many problems with the current workflows.

After some discussions, the team had to decide to use `zx` and npm scripts to unity current scripts(runner).

**Comment by hyf0** [comment]
Closed by
- https://github.com/web-infra-dev/rspack/pull/2754
- https://github.com/web-infra-dev/rspack/pull/2840
- https://github.com/web-infra-dev/rspack/pull/2756
