### ISSUE TITLE
[Feature Request]: `builtins.css.modules` support `auto` config

### ISSUE THREAD

**Issue by hzura** [web-infra-dev/rspack#2273]
### What problem does this feature solve?

Currently, if you need to support both .less and .module.less files in the project, you need to configure their types separately like below. (plz forgive me if I have used them incorrectly)
```
{
  test: /\.less$/,
  use: [{
	  loader: 'less-loader',
  }],
  type: 'css/module',
},
{
  test: /^(.(?!\.module))+\.less$/,
  use: [{
	  loader: 'less-loader',
  },],
  type: 'css',
},
``` 
I hope that `builtins.css.modules` config can support option `auto` like css-loader, allowing automatic differentiation using regular expressions (as the cost of using a function may be high at the moment)
preference: https://webpack.js.org/loaders/css-loader/#modules

### What does the proposed API of configuration look like?

```
type BuiltinsCssModules = {
  localsConvention?:
    | 'asIs'
    | 'camelCase'
    | 'camelCaseOnly'
    | 'dashes'
    | 'dashesOnly';
  localIdentName?: string;
  exportsOnly?: boolean;
  auto?: boolean | RegExp;
};
```

**Comment by hardfist** [comment]
waiting for https://github.com/webpack/webpack/issues/16572 resolved

**Comment by evertzz** [comment]
I wonder how to support module.less, the configuration above does't work

**Comment by hardfist** [comment]
since https://github.com/webpack/webpack/pull/16577 landed, we can continue supporting it now
