### ISSUE TITLE
[Feature Request]: externals support function or Regexp type

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#2277]
### What problem does this feature solve?

In Project, some external module has similar name, like `@/someA` `@/someB`

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/externals/#externals 
```
external: ( name ) => { return /@.*/.test(name) }
```

**Comment by Songkeys** [comment]
This would be significant for server side applications which uses `webpack-node-externals` in most cases.

**Comment by hardfist** [comment]
external is already supported

**Comment by underfin** [comment]
close at #2866. The function arguments which include `contextInfo` & `getResolve` & `contextInfo` is not supported at now, please track here https://github.com/web-infra-dev/rspack/issues/2877
