### ISSUE TITLE
how to use the swc plugin with Rspack

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#2287]
rt
I want to use a third party swc plugin in rspack How to configure

**Comment by hardfist** [comment]
not supported yet, we may consider support it in the future

**Comment by h-a-n-a** [comment]
A swc-loader with native plugin may be used as a current workaround.

**Comment by hyf0** [comment]
swc wasm plugin is quite experimental. We have no plan for it now.
