### ISSUE TITLE
[Bug Report]: arco-pro demo open cache hot update error

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#2289]
### System Info

 System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: 110.0.1587.69
    Safari: 14.1.1
  npmPackages:
    @rspack/cli: * => 0.1.0 
    @rspack/plugin-html: * => 0.1.0 

### Details

![image](https://user-images.githubusercontent.com/7599351/225498607-20002b9e-e0c8-4378-8c1a-24e973b2c72b.png)

### Reproduce Steps

- cd arco-pro
- pnpm dev
- example update
- page not refreshing
- forced refresh 
- error

**Comment by hardfist** [comment]
@xierenyuan does it still exist?

**Comment by hardfist** [comment]
feel free to reopen is it's not solved
