### ISSUE TITLE
[Bug Report]: cargo build got an error

### ISSUE THREAD

**Issue by ryanxiang7** [web-infra-dev/rspack#2304]
### System Info

system：wsl2/ubuntu 20.24.6 LTS
cargo version：1.68.0-nightly
node version：v18.15.0

### Details

I get an error when running 'cargo build'。Error occurs in `crates/rspack_plugin_javascript/src/visitors/plugin_import.rs`

Just don't know how to fix this.😥

### Reproduce Steps

1. run `cargo build`
2. error[E0277]: the trait bound `impl swc_ecma_visit::Fold + '_: swc_core::ecma::visit::Fold` is not satisfied

```zsh
error[E0277]: the trait bound `impl swc_ecma_visit::Fold + '_: swc_core::ecma::visit::Fold` is not satisfied
 --> crates/rspack_plugin_javascript/src/visitors/plugin_import.rs:5:67
  |
5 | pub fn plugin_import(config: Option<&Vec<PluginImportConfig>>) -> impl Fold + '_ {
  |                                                                   ^^^^^^^^^^^^^^ the trait `swc_core::ecma::visit::Fold` is not implemented for `impl swc_ecma_visit::Fold + '_`
  |
  = help: the following other types implement trait `swc_core::ecma::visit::Fold`:
            &'a mut V
            AndThen<A, B>
            Box<V>
            Either<A, B>
            EmotionTransformer<C>
            ReactHmrFolder
            format::RspackModuleFinalizer<'a>
            swc_core::common::pass::Optional<V>
          and 2 others
  = note: required for `Either<impl swc_ecma_visit::Fold + '_, impl swc_core::ecma::visit::Fold>` to implement `swc_core::ecma::visit::Fold`

```

**Comment by IWANABETHATGUY** [comment]
could you try pulling the latest main branch, and `cargo clean`, then run `cargo build` ?

**Comment by ryanxiang7** [comment]
> could you try pulling the latest main branch, and `cargo clean`, then run `cargo build` ?

That works! Thanks a lot!🫡🫡🫡
