### ISSUE TITLE
[Bug Report]: As the input size increases, the difference in build output size between webpack widens.

### ISSUE THREAD

**Issue by suguanYang** [web-infra-dev/rspack#2309]
### System Info

 System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (6) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.97 GB / 11.70 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  npmPackages:
    @rspack/cli: ^0.1.1 => 0.1.1
    @rspack/plugin-minify: ^0.1.1 => 0.1.1
    webpack: 5.76.2 => 5.76.2

### Details

I was trying to bundle on this entry
```
export * as React from "react";
export * as ReactDOM from "react-dom";
export * as Redux from "redux";
export * as ReactRedux from "react-redux";
export * as ReactRouterDOM from "react-router-dom";
export * as ReactRouter from "react-router";
export * as classnames from "classnames";
export * as ReactDnd from "react-dnd";
export * as ReactBeautifulDnd from "react-beautiful-dnd";
export * as ReactDraggable from "react-draggable";
export * as ReactDndHtml5Backend from "react-dnd-html5-backend";
export * as ReactRnd from "react-rnd";
export * as Dayjs from "dayjs";
export * as Lodash from "lodash";
export * as Recoil from "recoil";
```

The output size between webpack and rspack get bigger when I export more from these libs, even they use same minfier plugin, literally, use this same config:
```
const path = require("path");
const minifyPlugin = require("@rspack/plugin-minify");

module.exports = {
  target: ["web", "es5"],
  externals: {},
  mode: "production",
  entry: {
    vendor: path.join(process.cwd(), "./index.js"),
  },
  output: {
    path: path.join(process.cwd(), "./dist"),
    filename: "[name].js",
    libraryTarget: "umd",
  },
  devtool: false,
  optimization: {
    minimizer: [new minifyPlugin({ minifier: "terser" })],
  },
};
```
the output size of webpack:  605 KiB
the output size of rspack:  650 KiB

almost 10% bigger, and it will continue to increase if we export more libs

I have checked the input and output of terser, for rspack, it call terser with smaller sourcefile, but results bigger, why? is webpack optimized for this scenario?

### Reproduce link

https://github.com/suguanYang/rspack-webpack-terser

### Reproduce Steps

go clone https://github.com/suguanYang/rspack-webpack-terser
run
```
yarn // npm i

yarn build:webpack

yarn build:rspack
```

**Comment by IWANABETHATGUY** [comment]
sorry for the late reply, I dig a little bit. Her is some reason: 
1. We don't implement `concatenateModule` and `mangleExports`, these two options would reduce some output size.
2. We don't have a custom runtime yet, the format phase is taken over by `swc` which would introduce some extra code. e.g.
```js
Object.defineProperty(exports, "__esModule", {
    value: true
});
```

**Comment by suguanYang** [comment]
Thank you for your response. Do you have any plans to optimize on these? as the size of the bundle will be a critical performance factor

**Comment by IWANABETHATGUY** [comment]
Yeah, of course, I will open issue to track these

**Comment by shawnmcknight** [comment]
> Yeah, of course, I will open some issues to track these problem

@IWANABETHATGUY Out of curiosity, did tracking issues get logged for these?  I've been trialing Rspack and comparing to webpack.  Build performance is significantly faster (as expected), but our bundle size has increased by ~22%.  If issues have been logged, I'd like to subscribe to them to follow, but I wasn't able to find anything.

Thanks!

**Comment by IWANABETHATGUY** [comment]
> > Yeah, of course, I will open some issues to track these problem
> 
> @IWANABETHATGUY Out of curiosity, did tracking issues get logged for these? I've been trialing Rspack and comparing to webpack. Build performance is significantly faster (as expected), but our bundle size has increased by ~22%. If issues have been logged, I'd like to subscribe to them to follow, but I wasn't able to find anything.
> 
> Thanks!
Would you mind providing your repo link?

**Comment by IWANABETHATGUY** [comment]
tracked here https://github.com/web-infra-dev/rspack/issues/2853

**Comment by shawnmcknight** [comment]
> Would you mind providing your repo link?

Unfortunately, I cannot, as its in a large private monorepo.  Is there anyrthing else I can provide to help?  Possibly the two different output bundles or the bundle analyzer `stats.json` files?  I have no idea if that helps at all, so I'm just suggesting some possibilities.

**Comment by IWANABETHATGUY** [comment]
> 


Oh, I know that, maybe you could try again after we address these bundle optimization issues

**Comment by IWANABETHATGUY** [comment]
https://github.com/web-infra-dev/rspack/pull/2871 this pr would optimize tree shaking swc/helpers maybe you could try the next nightly version of `rspack`, but I don't expect this would bring too much improvement

**Comment by shawnmcknight** [comment]
> #2871 this pr would optimize tree shaking swc/helpers maybe you could try the next nightly version of `rspack`, but I don't expect this would bring too much improvement

I tested out the latest nightly.  There was an improvement, but as you expected it wasn't substantial.  It looks like bundle is about 10kb smaller than it was previously.  So it moved from a 22.1% size increase over the equivalent webpack build to a 21.7% increase over the equivalent webpack build.

**Comment by IWANABETHATGUY** [comment]
> it

Thanks for your work, we will continue to optimize the bundle size.

**Comment by suguanYang** [comment]
@IWANABETHATGUY Any updates on progress? We're eager to move away from Webpack, but this is currently impeding us.

**Comment by hardfist** [comment]
@suguanYang can you file a separate issue, it maybe not the same problem

**Comment by IWANABETHATGUY** [comment]
try this https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking in the latest 0.4.2, or the latest nightly, your feedback is highly appreciated.

**Comment by IWANABETHATGUY** [comment]
With latest commit and `newTreeshaking` enabled
```js
const path = require("path");
const minifyPlugin = require("@rspack/plugin-minify");

/**@type {import("@rspack/cli").Configuration}*/
module.exports = {
	target: ["web", "es5"],
	mode: "production",
	experiments: {
		rspackFuture: {
			newTreeshaking: true,
      disableTransformByDefault: true,
		},
	},
	entry: {
		vendor: path.join(__dirname, "./index.js"),
	},
	devtool: false,
	optimization: {
		concatenateModules: false, // disable this option because we don't implement this feature yet. tracked #2853
		minimizer: [new minifyPlugin({ minifier: "terser" })],
	},
};

```
**webpack** 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/27c33982-46f1-4552-9ad1-868d71753dea)
**rspack** 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/ca72c6f4-8bb4-47a9-b47b-c1a6d7b777e7)
Closed this, and tracked rest issues https://github.com/web-infra-dev/rspack/issues/2853
