### ISSUE TITLE
[Feature Request]: Do we need to make `resolve.tsConfigPath` support relative paths?

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#2312]
### What problem does this feature solve?

Currently, `resolve.tsConfigPath` only supports absolute paths, otherwise it reports an error, should we make it support relative paths as well in the future? Just like `entry`.

### What does the proposed API of configuration look like?

```js
// rspack.config.js
module.exports = {
  resolve: {
     tsConfigPath: './tsconfig' // it should be relatieve `context`
  }
}
```

**Comment by hardfist** [comment]
relativePath makes sense which is relative to config.context

**Comment by hardfist** [comment]
@bvanjoi @Boshen can you help confirm whether this problem still exist or this issue should be closed?
