### ISSUE TITLE
[Feature Request]: Mention more clearly that the RSPack package name is `@rspack/cli` on the website.

### ISSUE THREAD

**Issue by iclanton** [web-infra-dev/rspack#2319]
### What problem does this feature solve?

It's not immediately obvious that on https://www.rspack.dev/ that the package a user is meant to install is [`@rspack/cli`](https://www.npmjs.com/package/@rspack/cli) and not [`rspack`](https://www.npmjs.com/package/@rspack/cli) without drilling down.

It'd be useful if this detail was on the homepage.

### What does the proposed API of configuration look like?

N/A

**Comment by octogonz** [comment]
The [rspack](https://www.npmjs.com/package/rspack) package seems to be defunct but owned by @hardfist. Maybe also it's README.md could have a deprecation notice. And also its `install` script could print a `console.log()` message recommending to install the other package (we did this with `@microsoft/node-core-library` for eaxmple).

**Comment by hardfist** [comment]
yes this is a good point, we will fix it later

**Comment by hardfist** [comment]
I add deprecated and redirect notice about rspack package in  https://www.npmjs.com/package/rspack

**Comment by hardfist** [comment]
I'm not sure whether we should add detail to homepage, I look at vite|rollup|babel|webpack, it seems none of these tools put package name on homepage but on quickstart page, which we already did. @octogonz may have better ideas

**Comment by hyf0** [comment]
> I add deprecated and redirect notice about rspack package in https://www.npmjs.com/package/rspack

Close the issue due to this.
