### ISSUE TITLE
[Feature Request]:old mac 2015  error:rspack.darwin-x64.node 

### ISSUE THREAD

**Issue by changchuncun** [web-infra-dev/rspack#2321]
### What problem does this feature solve?

old mac 2015  error:rspack.darwin-x64.node 

### What does the proposed API of configuration look like?

old mac 2015  error:rspack.darwin-x64.node

**Comment by h-a-n-a** [comment]
It seems you're using a wrong template, so you may have to fill it again with **bug report**. I have to close this.

**Comment by changchuncun** [comment]
Error: dlopen(/Users/wpf/projects/dcoin/rspack_test/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node, 1): no suitable image found.  Did find:
	/Users/wpf/projects/dcoin/rspack_test/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)

**Comment by changchuncun** [comment]
Error: dlopen(/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node, 1): no suitable image found.  Did find:
	/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)
