### ISSUE TITLE
[Bug Report]: Error: dlopen(/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node, 1): no suitable image found

### ISSUE THREAD

**Issue by changchuncun** [web-infra-dev/rspack#2324]
### System Info

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 327.22 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 12.1.2
  npmPackages:
    @rspack/cli: ^0.1.0 => 0.1.1
### Details

Error: dlopen(/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node, 1): no suitable image found.  Did find:
	/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)
	/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/@rspack/binding/binding.js:106:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

### Reproduce link

npm create rspack@latest

### Reproduce Steps

yarn dev

**Comment by h-a-n-a** [comment]
Please stick to the template and provide more clearer systeminfo: `npx envinfo --system --npmPackages '@rspack/*' --binaries --browsers`

**Comment by changchuncun** [comment]
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 327.22 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 12.1.2
  npmPackages:
    @rspack/cli: ^0.1.0 => 0.1.1

**Comment by zuolung** [comment]
i got the same problem

**Comment by zuolung** [comment]
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 13.1.2
  npmPackages:
    @rspack/cli: ^0.1.1 => 0.1.1 '

**Comment by zuolung** [comment]
wait wait @h-a-n-a

**Comment by hardfist** [comment]
@zuolung  please help check in latest version whether this problem still exists

**Comment by zuolung** [comment]
version: 0.1.11 has got the same problem
```text
Error: dlopen(/Users/apple/Desktop/Dian/sariel/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node, 1): no suitable image found.  Did find:
        /Users/apple/Desktop/Dian/sariel/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)
        /Users/apple/Desktop/Dian/sariel/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node: cannot load 'rspack.darwin-x64.node' (load command 0x80000034 is unknown)
```

**Comment by hardfist** [comment]
seems related to https://github.com/hashicorp/vagrant/issues/13131, we will take down protobuf and see whether it works, cc @ahabhgk

**Comment by hardfist** [comment]
@zuolung please help check in latest version whether this problem still exists

**Comment by hardfist** [comment]
close issue for long time inactivity, feel free to reopen if you have more question.
