### ISSUE TITLE
[Bug Report]: resolve error when 3rd-packages use node internal module

### ISSUE THREAD

**Issue by AuglyXu** [web-infra-dev/rspack#2332]
### System Info

System: Windows11

### Details

当第三方包依赖了node的内置模块，如http、https
target为'node'时正常构建，target为'web'时报如下错误
![image](https://user-images.githubusercontent.com/42527305/225878375-6b51e5e8-42f9-4bbe-9560-48c2a60bf9eb.png)

### Reproduce Steps

1. yarn install
2. rspack serve -c internal/rspack/rspack.dev.config.js

**Comment by h-a-n-a** [comment]
不建议在 web 场景下引入 node std 的内容，如果避免不了可以用 https://www.npmjs.com/package/@rspack/plugin-node-polyfill
