### ISSUE TITLE
[Feature Request]: Add support for `webpackInclude` and `webpackExclude` magic comments

### ISSUE THREAD

**Issue by zakuru** [web-infra-dev/rspack#2335]
### What problem does this feature solve?

Hi, 
Webpack supports `webpackExclude` and `webpackInclude` magic comments as shown here : https://webpack.js.org/api/module-methods/#magic-comments
Is there some plan in progress to have it supported by rspack ?

### What does the proposed API of configuration look like?

https://webpack.js.org/api/module-methods/#magic-comments
https://github.com/webpack/webpack/pull/5809

```
// Single target
import(
  /* webpackChunkName: "my-chunk-name" */
  /* webpackMode: "lazy" */
  /* webpackExports: ["default", "named"] */
  'module'
);

// Multiple possible targets
import(
  /* webpackInclude: /\.json$/ */
  /* webpackExclude: /\.noimport\.json$/ */
  /* webpackChunkName: "my-chunk-name" */
  /* webpackMode: "lazy" */
  /* webpackPrefetch: true */
  /* webpackPreload: true */
  `./locale/${language}`
);
```
Thank you

**Comment by zackarychapple** [comment]
@IWANABETHATGUY should this be closed since #2367 is merged?

**Comment by zakuru** [comment]
Thank a lot @IWANABETHATGUY 🙏

**Comment by IWANABETHATGUY** [comment]
No, that pr is just a prerequisite of this feature.

**Comment by zakuru** [comment]
HI @IWANABETHATGUY 
Seems that this one can be closed or there is work left to do ?
Thanks

**Comment by IWANABETHATGUY** [comment]
@hyf0 , can we close this?

**Comment by ywang1724** [comment]
Not supported yet? Rspack@0.3.4

**Comment by LingyuCoder** [comment]
not sure why this issue was closed, support by https://github.com/web-infra-dev/rspack/pull/7055
