### ISSUE TITLE
[Bug Report]: Parses all JS files in strict mode

### ISSUE THREAD

**Issue by andersk** [web-infra-dev/rspack#2339]
### System Info

```
  System:
    OS: Linux 6.2 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 8.50 GB / 15.27 GB
    Container: Yes
    Shell: 5.2.15 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.14.2 - ~/.nix-profile/bin/node
    Yarn: 1.22.19 - ~/.nix-profile/bin/yarn
    npm: 9.5.0 - ~/.nix-profile/bin/npm
  Browsers:
    Chromium: 111.0.5563.64
    Firefox: 111.0b8
  npmPackages:
    @rspack/cli: ^0.1.1 => 0.1.1 
```

### Details

rspack has inherited SWC’s default of parsing all JS files as modules, and therefore cannot parse code that only compiles in non-strict mode, such as

```js
delete a;
```

or as a real-world example, the [sorttable](https://www.npmjs.com/package/sorttable) library.

SWC provides the `isModule` configuration option for this; I think we want to set it based on the file extension (`.cjs`, `.mjs`, `.cts`, `.mts`) or the [`type` field](https://nodejs.org/api/packages.html#type) in the nearest `package.json` (`.js`, `.ts`).

See for example

- swc-project/swc#1810

Probably related:

- #2178

### Reproduce Steps

From an empty directory:

```console
$ mkdir src
$ echo 'delete a;' > src/index.js
$ rspack
Hash: eb46cf29de5a8584
PublicPath: auto
  Asset       Size  Chunks             Chunk Names
main.js  248 bytes    main  [emitted]  main
Entrypoint main = main.js
[887] ./src/index.js 10 bytes {main}

error[javascript]: JavaScript parsing error
  ┌─ src/index.js:1:8
  │
1 │ delete a;
  │        ^ 'delete' cannot be called on an identifier in strict mode


build: 29.688ms
```

**Comment by JSerFeng** [comment]
This can be solved when SWC parses non-module correctly, you can check the progress on #2406.
