### ISSUE TITLE
[Bug Report]: devServer.invalidate() 调用报错

### ISSUE THREAD

**Issue by crazyxhz** [web-infra-dev/rspack#2341]
### System Info

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 91.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.0

### Details

devServer.invalidate() 调用报错
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/6551888/226145033-12cf37ba-6d18-421b-a28b-cd120c02fee6.png">

### Reproduce Steps

1. pnpm create rspack@latest
2. `rspack.config.js` 添加配置 
```
devServer:{
    setupMiddlewares: (mid, server) => {
      server.app.get('/reload', (_, response) => {
        server.invalidate();
        response.send('reloaded');
      });
      return mid
    }
  },
```
3. pm dev 后， curl localhost:8080/reload 报错

需求，配置变更之后想调用invalid 重读配置

**Comment by jerrykingxyz** [comment]
The compiler rebuild will update module graph with `modifiedFiles` and `deleteFiles`. Empty for both means that the module graph has not changed, and naturally the final assets has not changed. Maybe we should skip incremental rebuild in make phase when both `modifiedFiles` and `deleteFiles` are empty.(Of course this will be slower). cc @hardfist @hyf0 @Boshen
