### ISSUE TITLE
[Feature Request]: Support WebpackManifestPlugin and ModuleFederationPlugin

### ISSUE THREAD

**Issue by crazyxhz** [web-infra-dev/rspack#2347]
### What problem does this feature solve?

这两个plugin是业务中很常用的插件，很多业务依赖
希望能支持一下

### What does the proposed API of configuration look like?

like webpack

**Comment by hardfist** [comment]
it is on the roadmap

**Comment by IWANABETHATGUY** [comment]
feel free to reopen this issue if you have any further questions.
