### ISSUE TITLE
[Feature Request]: how to use eslint-loader in rspack

### ISSUE THREAD

**Issue by AuglyXu** [web-infra-dev/rspack#2353]
### What problem does this feature solve?

I want to use eslint-loader to warning in terminal, how can i use it?

### What does the proposed API of configuration look like?

{
    test: /.jsx/i
    loader: 'eslint-loader'
}

**Comment by Boshen** [comment]
It is not recommended to run eslint inside webpack / rspack anymore. Run it in another build step, and also in lint-staged.

**Comment by hardfist** [comment]
we will check whether we could make eslint-loader work now

**Comment by ScriptedAlchemy** [comment]
be warned that transferring this much data between rust and js will be expensive and likely have an impact on build speed. 
Echoing @Boshen - rather run `yarn lint` after the build process. 
Anything that involves parsing in JS land will create bottlenecks. 

If there were a rust based linter this would not be such a bottleneck. 
If we used a packet buffer to push payloads from rust to a workerpool, this might preserve the parallelism of rust - however starting workers is not fast
