### ISSUE TITLE
[Bug Report]: 同样的publicPath，在webpack中可以正确加载，rspack中并没有加载资源

### ISSUE THREAD

**Issue by AuglyXu** [web-infra-dev/rspack#2359]
### System Info

System: windows11

### Details

下面的配置没有加载js文件
截图entry配置有误，已修复依旧如此
![image](https://user-images.githubusercontent.com/42527305/226255017-df701fa7-92e0-4714-9ef4-a0fbf335995a.png)
![image](https://user-images.githubusercontent.com/42527305/226255036-35ea0de3-cc0d-4d81-8342-6acb00964727.png)
![image](https://user-images.githubusercontent.com/42527305/226255165-d7863e4d-6266-4a14-8d58-e2dda4b43831.png)

将publicPath改成 '/' 之后，加载了js文件，但是报了如下错误
![image](https://user-images.githubusercontent.com/42527305/226255390-616b8135-0bb5-446c-a5be-212eea1ab552.png)
![image](https://user-images.githubusercontent.com/42527305/226255430-7b035169-751b-4252-b51f-2baff47e3d16.png)
![image](https://user-images.githubusercontent.com/42527305/226260759-7d13c5c6-8982-45c0-a70a-62b058ff1a69.png)

期望结果：
publicPath在第一种情况下也能正确加载js文件，并没有报第二种情况的错误

### Reproduce Steps

1. yarn install
2. yarn start

**Comment by IWANABETHATGUY** [comment]
可以给一个最小的复现demo吗？

**Comment by IWANABETHATGUY** [comment]
may related to https://github.com/web-infra-dev/rspack/issues/2178

**Comment by AuglyXu** [comment]
> 可以给一个最小的复现demo吗？

publicPath问题复现仓库：
https://github.com/AuglyXu/lerna-test

执行 yarn install; yarn run start:web

启动域名'www.company.ui.cn', 需要通过whistle解析到127.0.0.1下，或者通过修改本机host文件解析

项目为monorepo，非monorepo项目没有问题

**Comment by AuglyXu** [comment]
> may relate to #2178

和2178不太一样，我也提供在复现的demo下，将publicPath设置为'/'即可

**Comment by IWANABETHATGUY** [comment]
> > may relate to #2178
> 
> 图二的问题和图一应该不是同一个问题，也和2178不太一样，我也提供在复现的demo下，将publicPath设置为'/'即可

好的我们看一下

**Comment by ahabhgk** [comment]
rspack 配置和 webpack 配置不一致导致的，webpack devServer 配了 `static.publicPath: ['/insight/webui']` 和 `devMiddleware.publicPath: '/insight/webui'`，rspack 也配置上就好了

另外 Octal escape 的报错是因为把 png 内容 inline 到 js 里了，`module.rules` 里将 png rule 的 type 改成 `asset` 或 `asset/resource` 就行
