### ISSUE TITLE
[Bug Report]: 文件夹不能有中文字符？

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#2363]
### System Info

System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 10.66 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

### Details

在 builtins.html.template 中使用绝对路径时，如果路径包含中文字符，就会报错
![image](https://user-images.githubusercontent.com/69964024/226281444-78a01963-a8ef-4608-96b8-76d82b6634e3.png)

### Reproduce Steps

1. npx rspack serve

**Comment by dingff** [comment]
相对路径是没问题的

**Comment by JSerFeng** [comment]
我马上修复一下哈～
