### ISSUE TITLE
[Bug Report]: Documentation is wrong

### ISSUE THREAD

**Issue by Lantianyou** [web-infra-dev/rspack#2364]
### System Info

no need

### Details

Docs: https://www.rspack.dev/zh/guide/migrate-from-cra.html
 ![image](https://user-images.githubusercontent.com/37259750/226304849-3b861efd-9f55-4851-98b8-6e0a885ecfaf.png)

Solution: 
![image](https://user-images.githubusercontent.com/37259750/226304928-72ed952b-fed4-45b2-a13a-a6454d7ec7fb.png)

### Reproduce Steps

Just click the link to see the problem and solution

**Comment by hardfist** [comment]
the copyWebpackPlugin version  in the document is v5 which is not the same api as copyWebpackPlugin@10

**Comment by Lantianyou** [comment]
I found about it too. So I suppose stressing install `copyWebpackPlugin@5` would give good guide in the migration doc, would not you say?

**Comment by hardfist** [comment]
feel free to send a PR to documentation

**Comment by Lantianyou** [comment]
Would you mind showing the repo link for docs, I cannot find it :)

**Comment by spencerHT** [comment]
Here is the repo link of [Rspack Website](https://github.com/web-infra-dev/rspack-website).

**Comment by Lantianyou** [comment]
[PR](https://github.com/web-infra-dev/rspack-website/pull/248) submitted, thanks in advance for reviewing it

**Comment by Lantianyou** [comment]
The preview page is here https://deploy-preview-248--rspack.netlify.app/guide/migrate-from-cra.html

**Comment by JSerFeng** [comment]
Thanks !
