### ISSUE TITLE
[Tracking issue] Angular support

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2373]
```[tasklist]
- [ ] https://github.com/web-infra-dev/rspack/issues/2377
- [ ] #2374
- [ ] #2375
- [ ] #2376
- [ ] https://github.com/web-infra-dev/rspack/issues/2601
```

**Comment by zackarychapple** [comment]
Should we add `compilation.rebuildModule` as its own task on this issue as well?

**Comment by kbrilla** [comment]
shouldn't #2385 also be included for Angular support for `namedChunks` option?

**Comment by IWANABETHATGUY** [comment]
closed in favor of https://github.com/web-infra-dev/rspack/pull/3009
