### ISSUE TITLE
[Feature Request]:  preview cli

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#2379]
### What problem does this feature solve?

Locally preview production build.If users are not familiar with rspack, they may not know how to implement it.

### What does the proposed API of configuration look like?
add a cli command `preview` like [vite](https://vitejs.dev/guide/cli.html#vite-preview)
or add some description about how to preview production build locally, like preview script in `acro design` example: `cd build & serve -s`
<img width="315" alt="image" src="https://user-images.githubusercontent.com/87003751/226410698-4c07838e-2676-4df0-b0ed-0f8e647ed0c8.png">

**Comment by sidverma32** [comment]
@hardfist  can i take this issue?

**Comment by faga295** [comment]
@hardfist I am very interested in this issue and have already started working on it. Can you assign this issue to me?

**Comment by hardfist** [comment]
go ahead!
