### ISSUE TITLE
[Feature Request]: Improve Terminal Output message formatting. 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [web-infra-dev/rspack#2381]
### What problem does this feature solve?

When a compile fails, for example - trying to bundle modules that cannot be resolved, the terminal will emit a large section of code followed by a big section of empty space and at the end an error message. 

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/25274700/226493642-fd9c41c1-fc30-44e2-bee0-20c64009d9b2.png">

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/25274700/226493669-6660caa4-de8f-4daf-a928-1b980864972f.png">

Error message formatting functions could be used to reduce verbosity 

### What does the proposed API of configuration look like?

I believe webpack can also throw an error that includes large code payloads, however its usually uncommon.

I dont think this requires adjustments to the bundler internal apis (perhaps the bindings back to JS) to ensure that less verbose output is returned to end users. The current output can be hard to navigate and locate all error messages or can exceed the terminals buffer if too long.

**Comment by IWANABETHATGUY** [comment]
Would you mind providing a minimum reproduction repo?

**Comment by ScriptedAlchemy** [comment]
You can use this repo listed here. It should cause the large terminal dump if you run build-server. 

https://github.com/web-infra-dev/rspack/issues/2382

**Comment by h-a-n-a** [comment]
Should be resolved. Please try again with the latest version ;-)
