### ISSUE TITLE
[Feature Request]: support webpackChunkName

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2385]
### What problem does this feature solve?

support specify name for the chunk use webpackChunkName comment

### What does the proposed API of configuration look like?

just like webpack: https://webpack.js.org/api/module-methods/#magic-comments

**Comment by HerringtonDarkholme** [comment]
This is my favorite webpack feature. Can I take a grab on this? But please give me several days to investigate how it is implemented in webpack and how to integrate to Rspack. 

I will give a summary after the initial investigation.

**Comment by hyf0** [comment]
> This is my favorite webpack feature. Can I take a grab on this? But please give me several days to investigate how it is implemented in webpack and how to integrate to Rspack.
> 
> I will give a summary after the initial investigation.

The feature is requested eagerly, I'm working on it and plan to finish it this Friday.

**Comment by hyf0** [comment]
Note: I investigate the feature and there are some problems the team needs to discuss. Once we come up with some conclusions, I will remove the `on hold` tag.

**Comment by leereichardt** [comment]
Did this ever get implemented?

**Comment by birtles** [comment]
Yes, I think it was first added in [0.1.7](https://github.com/web-infra-dev/rspack/releases/tag/v0.1.7) and then subsequent releases further fixed the allowed syntax, allowed it in workers etc.
