### ISSUE TITLE
[Feature Request]: support output.chunkLoadingGlobal

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2388]
### What problem does this feature solve?

In micro front-end scenarios, it's necessary to use a unique name instead of webpackChunkwebpack, to avoid multiple rspack runtimes conflict.

### What does the proposed API of configuration look like?

Maybe we not need to specical  output.chunkLoadingGlobal, just use output.uniqueName as output.chunkLoadingGlobal default value.

https://webpack.js.org/configuration/output/#outputchunkloadingglobal

https://webpack.js.org/configuration/output/#outputuniquename

<img width="801" alt="image" src="https://user-images.githubusercontent.com/22373761/226512315-7c4b18bf-7550-4467-b0b3-2d964fede7a5.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/22373761/226512444-184365a4-3082-4fd9-8a38-f952a1f0b418.png">

<img width="940" alt="image" src="https://user-images.githubusercontent.com/22373761/226512490-123d26b5-15ab-4748-b974-0605158afd43.png">

**Comment by ScriptedAlchemy** [comment]
Output.uniqueName would be the more thorough option to cover uniqueness of several runtime aspects

**Comment by KyrieLii** [comment]
I also expect this. 🫣
