### ISSUE TITLE
[Bug Report]: cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2392]
### System Info

 System:
 - OS: macOS 12.5.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 212.05 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
 
Binaries:
- Node: 16.19.1 - /usr/local/bin/node
- Yarn: 1.22.19 - /usr/local/bin/yarn
- npm: 8.19.3 - /usr/local/bin/npm

 Browsers:
 - Chrome: 111.0.5563.64
 - Safari: 15.6.1
 
 npmPackages:
  - @rspack/cli: latest => 0.1.1 

### Details

runtime error when use some esm libs which have some `import.meta` syntax, like [zustand](https://github.com/pmndrs/zustand)

<img width="648" alt="image" src="https://user-images.githubusercontent.com/22373761/226515483-095b7d22-401c-4012-a3aa-1edc7f83f7ee.png">

![image](https://user-images.githubusercontent.com/22373761/226514262-ea2fd5ec-7978-4455-bc48-5e581e3defa7.png)

![image](https://user-images.githubusercontent.com/22373761/226516202-9ef3826c-b53f-4742-8913-9eab9a3011b6.png)

### Reproduce link

https://github.com/9aoy/rspack-issue-reproduce/tree/main/import-esm

### Reproduce Steps

1. pnpm install 
2. pnpm dev
3. open the browser

**Comment by underfin** [comment]
Related https://github.com/webpack/webpack/issues/15833, it should get more feedback with webpack community.

Here is wrokaround for this.
``` ts
// rspack.config.js

{
        builtins: {
		define: {
			'import.meta.env && import.meta.env.MODE': "'development'"
		}
	},
}

```
