### ISSUE TITLE
[Feature Request]: Support optimizations.chunkIds deterministic

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2393]
### What problem does this feature solve?

<img width="711" alt="image" src="https://user-images.githubusercontent.com/22373761/226515902-df88c82e-5abe-448e-b21a-847584598ab9.png">

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/optimization/#optimizationchunkids

**Comment by hyf0** [comment]
> I can work on this if it sounds good to you

That would be very good.

If you need any guidance, feel free to ping me anytime on GitHub or Discord.

**Comment by hardfist** [comment]
bump
