### ISSUE TITLE
[Feature Request]: pitching loader support

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2394]
https://webpack.js.org/api/loaders/#pitching-loader

**Comment by ScriptedAlchemy** [comment]
Pitching loader support is a biggie! I almost exclusively use pitch loaders for augmenting applications. 

Will pitch loaders support this.loadModule or this.importModule?

**Comment by ahabhgk** [comment]
Pitching loader is needed for vue-loader, if there are any common uses loader relying on loadModule or importModule, we will also support these two API
