### ISSUE TITLE
[Bug Report]: react-streaming/server is not exported in /xxxxx/exports-issue/node_modules/react-streaming/package.json

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2398]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 372.73 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish

### Details
![image](https://user-images.githubusercontent.com/17974631/226541301-fffd0975-7a04-4c17-9281-9c0c1a4682e9.png)

### Reproduce link

https://github.com/IWANABETHATGUY/rspack-package-json-exports-fields-issue

### Reproduce Steps

1. pnpm install
2. pnpm build

**Comment by IWANABETHATGUY** [comment]
@bvanjoi, would you mind having a look?

**Comment by bvanjoi** [comment]
There has two ways to solve that:
1. add corresponding `conditionNames` in your config.
2. add `default` field in `react-streaming`, maybe https://github.com/brillout/react-streaming/pull/17 can solve this problem.

**Comment by IWANABETHATGUY** [comment]
> There has two ways to solve that:
> 
> 1. add corresponding `conditionNames` in your config.
> 2. add `default` field in `react-streaming`, maybe [feat: add `default` in exports field brillout/react-streaming#17](https://github.com/brillout/react-streaming/pull/17) can solve this problem.
Thanks for the quick reply!
Yes, I found that webpack will yield the same error, so closed.

**Comment by brillout** [comment]
Fix released at `react-streaming@0.3.6`.

**Comment by IWANABETHATGUY** [comment]
> Fix

Thanks

**Comment by brillout** [comment]
The fix was bogus. It's fixed. Use `react-streaming@0.3.7` instead.
