### ISSUE TITLE
[Bug Report]: 修改样式无法触发页面更新？

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#2399]
### System Info

System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.76 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

### Details

使用sass和cssModules，修改样式后，页面没有更新

### Reproduce Steps

npx rspack serve

**Comment by dingff** [comment]
手动刷新页面后样式是正常的

**Comment by hardfist** [comment]
能提供最小复现demo吗

**Comment by dingff** [comment]
npm start

**Comment by jerrykingxyz** [comment]
可以暂时先通过移除 `output.filename` 中的 `[contenthash]` 来规避，相关问题在修复中
``` js
const isDev = process.env.NODE_ENV === "development";
module.exports = {
  output: {
    filename: isDev ? '[name].js' : '[name].[contenthash].js'
  }
}
```

**Comment by underfin** [comment]
Related https://github.com/webpack/webpack-dev-server/issues/3227
