### ISSUE TITLE
 find a way to disable `HookMap` hook, when it is unused.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2400]
https://github.com/web-infra-dev/rspack/pull/2356#discussion_r1143028300

**Comment by hardfist** [comment]
@IWANABETHATGUY is this still valid?

**Comment by IWANABETHATGUY** [comment]
Yeah, currently we can't apply `disableHooks` on `HookMap`

**Comment by h-a-n-a** [comment]
bump

**Comment by IWANABETHATGUY** [comment]
looks like it is fixed by #5202
