### ISSUE TITLE
[Feature Request]: non_webpack_require

### ISSUE THREAD

**Issue by ScriptedAlchemy** [web-infra-dev/rspack#2408]
### What problem does this feature solve?

This allows me to skip bundling a specific require call. `__non_webpack_require__` is converted back into `require` and is often used inside libraries as a way to escape the containers closure.

This is the same concept as webpack magic comments for webpackIgnore on a import(), which tells webpack to use native import() spec to load that specific file. For require or sync imports - non_webpack_require does the same kind of thing

### What does the proposed API of configuration look like?

this is syntax sugar, no outward facing api. 

I believe this would be a parser update or require factory alteration to match how webpack does it currently.

**Comment by hardfist** [comment]
we should support it but you can workaround it by `eval('require')(id)`

**Comment by ScriptedAlchemy** [comment]
Just to note for users reading, libraries may have issues till this is patched if they depend on breaking out of webpack with non require.

**Comment by Ttou** [comment]
> we should support it but you can workaround it by `eval('require')(id)`

how to do？use rspack to start nestjs project，output error

![image](https://github.com/web-infra-dev/rspack/assets/4298437/c890856a-4b1d-4732-a790-20bc8496a493)

**Comment by hardfist** [comment]
so you use some third-party module which use `__no_webpack_require__` api?

**Comment by Ttou** [comment]
yes

**Comment by hardfist** [comment]
you either wait for rspack __no_webpack_require__ implementation or use patch-package to modify third party mode code

**Comment by NexxLuo** [comment]
when i use __non_webpack_require__   , an error occurs ：`require is not defined`
