### ISSUE TITLE
[Bug Report]: compiler.hooks.compile not called

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2412]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 150.22 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 15.6.1

### Details

I want use compiler.hooks.compile hook in plugin，but never called.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/22373761/226796177-2fdb8097-af7c-4580-9629-61d8bf6defe0.png">

### Reproduce Steps

It seems like not implemented in the code.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/22373761/226796761-a0162dd5-2e75-4343-885e-452fc4574ecb.png">

**Comment by IWANABETHATGUY** [comment]
@KarthusLorin

**Comment by hyf0** [comment]
Please re-open this issue if it's not stale.
