### ISSUE TITLE
[Bug Report]: undefined factory error when nothing export

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2414]
### System Info

System:

OS: macOS 12.5.1
CPU: (10) arm64 Apple M1 Pro
Memory: 212.05 MB / 32.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:

Node: 16.19.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 8.19.3 - /usr/local/bin/npm
Browsers:

Chrome: 111.0.5563.64
Safari: 15.6.1
npmPackages:

@rspack/cli: latest => 0.1.1

### Details

runtime error when nothing export.

I know this(nothing export) should not occur in a real scenario, but it does exist in some lib packages. :joy

<img width="662" alt="image" src="https://user-images.githubusercontent.com/22373761/226814251-9ab1dd36-ec57-4c22-b98b-5966754402cb.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/22373761/226814145-d69ca73e-32f0-4b0f-8b83-700a460148c8.png">

### Reproduce link

https://github.com/9aoy/rspack-issue-reproduce/tree/main/export-empty

### Reproduce Steps

1. pnpm install
2. pnpm dev
3. open the browser

**Comment by underfin** [comment]
closed at #2421
