### ISSUE TITLE
[Bug Report]: require.context regex not working correctly

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#2417]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 133.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.1 => 0.1.1

### Details

Dir like  this : 

```sh
.
├── a.yaml
├── b.yaml
├── c.yml
├── d.yml.abcdefg
└── index.ts
```

index.ts :

```ts
// @ts-ignore
const context = require.context(".", false, /\.ya?ml$/);

export default context;
```

I think `d.yml.abcdefg` can't be matched，but: 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/16858738/226827061-a2b658f1-9e6c-4775-8a66-b52aed56cc45.png">

Webpack will ignore the file,  so I think something is wrong with the regex.

Tks guys 👀 

### Reproduce link

https://github.com/KyrieLii/rspack-webpack-demo/tree/require-context

### Reproduce Steps

See readme.

**Comment by underfin** [comment]
closed at #2509
