### ISSUE TITLE
Question: Can you output ESM?

### ISSUE THREAD

**Issue by jacob-ebey** [web-infra-dev/rspack#2418]
Haven't dove deep but spun up a quick test with the following input and the output contains an IIFE and does not contain ESM exports.

app/entry.browser.ts:
```ts
export const message = "Hello, World!";
console.log(message as string);
```

repack.config.js:
```js
const path = require("node:path");

module.exports = {
	entry: {
		"entry.browser": "./app/entry.browser.ts",
	},
	output: {
		filename: "[name].js",
		path: path.resolve(__dirname, "public/build"),
		enabledLibraryTypes: ["module"],
		library: {
			type: "module",
		},
	},
	optimization: { minimize: false },
};
```

**Comment by hardfist** [comment]
fixed in #2803

**Comment by zackarychapple** [comment]
@hardfist this fixes support for ESM in the same way that webpack supports ESM which is a big win.  However after talking with @valorkin and @ScriptedAlchemy, we would like to see a way to output an ESM target for library authoring similar to how Rollup preserveModules works. That would allow us to do things like [this](https://unpkg.com/browse/@angular/cdk@16.0.0-rc.0/esm2022/menu/menu-item.mjs) for Angular.

**Comment by hardfist** [comment]
support `preserveModules` is another feature request that needs to be discussed, I think this feature request is solved right now.

**Comment by hyf0** [comment]
Close for having https://github.com/web-infra-dev/rspack/pull/2803
