### ISSUE TITLE
[Feature Request]: Support DataURL import

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#2422]
### What problem does this feature solve?

See: https://nodejs.org/api/esm.html#data-imports

### What does the proposed API of configuration look like?

```js
import 'data:text/javascript,console.log("hello!");';
```

**Comment by ScriptedAlchemy** [comment]
DataURL support would be very useful, ive used it a few times for generation of virtual entrypoints as well as in pitching loaders

**Comment by h-a-n-a** [comment]
> DataURL support would be very useful, ive used it a few times for generation of virtual entrypoints as well as in pitching loaders

@ScriptedAlchemy Exactly! We have some internal project rely on this to get virtual module working.
