### ISSUE TITLE
[Feature Request]: support compilation.hooks.optimizeModules

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#2423]
### What problem does this feature solve?

We need `compilation.hooks.optimizeModules` to be compatible with [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin)

### What does the proposed API of configuration look like?

``` js
compilation.hooks.optimizeModules.tap("PluginName", (modules) => {})
```

**Comment by KyrieLii** [comment]
+1
