### ISSUE TITLE
[Bug Report]: exclude 配置无效

### ISSUE THREAD

**Issue by congxiaobai** [web-infra-dev/rspack#2427]
### System Info

node :14.13.0
"@rspack/cli": "0.1.0",
  @rspack/dev-server": "0.1.0",

### Details

配置modules如下:
![image](https://user-images.githubusercontent.com/20089891/226875249-3b4b6207-a6e0-4741-a7fb-5da8a175705c.png)
![image](https://user-images.githubusercontent.com/20089891/226875325-c4e99cea-5cf1-4631-a352-c376bbb4aff0.png)

### Reproduce Steps

1. run dev
2.
![image](https://user-images.githubusercontent.com/20089891/226875488-6902e515-2b9c-41f4-83b4-ed5e5d6b9435.png)
![image](https://user-images.githubusercontent.com/20089891/226875973-3b7cf8f4-4e13-4f27-b9cc-875d7e92e12f.png)

3. 问题：
     a, 可以看到./../node_modules/.pnpm被解析了
     b, svg解析失败

**Comment by hardfist** [comment]
minimal demo please

**Comment by ahabhgk** [comment]
1. There is no `module.rule[]` in the configuration above useable for `.eot`/`.woff2` file, so these file will hit `module.defaultRules` and be treated as javascript module, there is no `exclude` in `module.defaultRules`, so this explains errors in first picture, you need at least one rule to process `.eot`/`.woff2` file.
2. The test condition is wrong for matching `.svg` file, so `.svg` file also be treated as javascript.

**Comment by ahabhgk** [comment]
Feel free to reopen if you have any further question.
