### ISSUE TITLE
[Feature Request]: webpack-merge like utility

### ISSUE THREAD

**Issue by arananegra** [web-infra-dev/rspack#2428]
### What problem does this feature solve?

Having multiple config files without having to replicate the same config or use environment variables all the time. 

### What does the proposed API of configuration look like?

You can import the common base config like this:

```
const { merge } = require('rspack-merge');
const common = require('./base.rspack.config');
```

Then, for example in the production config file like `pro.rspack.config.js` you can use it like this:

```
module.exports = merge(common, {
  mode: 'production',
  ....

```

I've searched the docs, the issues and discussions and haven't found if it already exists something like this (sorry if it does)

**Comment by ScriptedAlchemy** [comment]
Agreed, webpack merge should work without issue

**Comment by arananegra** [comment]
Thank you! Seems to be working!
