### ISSUE TITLE
[Bug Report]: A Large Config Array Uses All System Resources

### ISSUE THREAD

**Issue by beeequeue** [web-infra-dev/rspack#2431]
### System Info

```
  System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 15.62 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.local/share/rtx/installs/nodejs/16.19.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/rtx/installs/nodejs/16.19.1/bin/yarn
    npm: 8.19.3 - ~/.local/share/rtx/installs/nodejs/16.19.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @rspack/cli: latest => 0.1.2
```

### Details

At some point when using an array of configurations (7 when I first encountered it, 10 in the repro repo) the build slows to a crawl, making the build take 10x as long.

Here is how the repro repo build looks on my M1 Mac 64GB:
```
Building 1 configs...
build: 288.429ms
Building 2 configs...
build: 297.402ms
Building 3 configs...
build: 395.663ms
Building 4 configs...
build: 317.321ms
Building 5 configs...
build: 339.679ms
Building 6 configs...
build: 414.946ms
Building 7 configs...
build: 586.755ms
Building 8 configs...
build: 564.843ms
Building 9 configs...
build: 831.296ms
Building 10 configs...
build: 9.221s          <-- Right here!
Building 11 configs...
build: 10.404s
Building 12 configs...
build: 7.152s
```

### Reproduce link

https://github.com/BeeeQueue/repro-rspack-config-array

### Reproduce Steps

1. Install deps - `pnpm install`
1. Run build - `pnpm build`
1. See in logs how at some point the build slows to a crawl

**Comment by BeeeQueue** [comment]
It would make sense, in the project I initially encountered it the entire computer freezes intermittently while at 100% CPU usage

**Comment by ScriptedAlchemy** [comment]
Not saying this is 100% the case, but in webpack i accidentally ran a parallel build task over module-federation-examples which issues 179 webpack builds at once. My computer froze up and was not able to even exit terminal.

Blind guess is that there may need to be a "management" thread for Rust to communicate with JS bindings over. If the CPU is choked it might put some resource limits on Rust-JS transfer as JS, even with multiple processes seems to have a few global limits. 

Defiantly worth looking into a little deeper, because i can see a NX monorepo trying to build in parallel and we don't want to impact those common use cases.

**Comment by Boshen** [comment]
@BeeeQueue I found a workaround and I need your assistance to verify if this works.

Inside `node_modules/@rspack/core/dist/multiCompiler.js`,
add `options.parallelism = 1;` below line 29:

```
class MultiCompiler {
    constructor(compilers, options) {
        options.parallelism = 1;
```

And comment out line 444

```
                if (result) {
                    node.result = undefined;
                    // stats.push(result);
                }
```

There are two problems at hand:
* Running the multi compiler in parallel will cause Rspack to go haywire on the Rust side
* Sending a huge stats array through napi will cause it to crash

**Comment by Boshen** [comment]
This should be fixed by the referenced issues and PRs, feel free to reopen if this is still happening.

**Comment by BeeeQueue** [comment]
From my quick testing it has not fixed it.

**Comment by Boshen** [comment]
> From my quick testing it has not fixed it.

Do you mind updating your repro so I can take a quick look?

**Comment by BeeeQueue** [comment]
It had already been updated but I updated it to the latest version again and there's still no difference.

Running it locally:

<details>
<summary>Details</summary>

```
repro-rspack-config-array main |  v18.16.0  took 23s
❯ nr build

> rspack-react-starter@0.0.0 build /Users/ahaglund/projects/repro-rspack-config-array
> for i in {1..12}; do AMOUNT="$i" rspack build; done

Building 1 configs...
Time: 135ms
Building 2 configs...
Time: 157ms

Time: 151ms
Building 3 configs...
Time: 143ms

Time: 134ms

Time: 138ms
Building 4 configs...
Time: 172ms

Time: 170ms

Time: 169ms

Time: 160ms
Building 5 configs...
Time: 171ms

Time: 161ms

Time: 157ms

Time: 164ms

Time: 163ms
Building 6 configs...
Time: 204ms

Time: 209ms

Time: 219ms

Time: 190ms

Time: 201ms

Time: 213ms
Building 7 configs...
Time: 273ms

Time: 279ms

Time: 231ms

Time: 224ms

Time: 331ms

Time: 224ms

Time: 280ms
Building 8 configs...
Time: 374ms

Time: 305ms

Time: 397ms

Time: 353ms

Time: 335ms

Time: 385ms

Time: 364ms

Time: 347ms
Building 9 configs...
Time: 822ms

Time: 768ms

Time: 842ms

Time: 797ms

Time: 760ms

Time: 799ms

Time: 783ms

Time: 788ms

Time: 794ms
Building 10 configs...
Time: 6569ms

Time: 6812ms

Time: 6812ms

Time: 6837ms

Time: 6788ms

Time: 6763ms

Time: 6763ms

Time: 6834ms

Time: 6754ms

Time: 6843ms
Building 11 configs...
Time: 4480ms

Time: 5780ms

Time: 5686ms

Time: 5812ms

Time: 5784ms

Time: 5730ms

Time: 5555ms

Time: 5787ms

Time: 5647ms

Time: 5728ms

Time: 5731ms
Building 12 configs...
Time: 12812ms

Time: 14080ms

Time: 14280ms

Time: 14315ms

Time: 14165ms

Time: 14290ms

Time: 14225ms

Time: 14350ms

Time: 14283ms

Time: 14200ms

Time: 14341ms

Time: 14345ms
```

</details>

**Comment by BeeeQueue** [comment]
The workaround/fix from before still works as well
https://github.com/BeeeQueue/repro-rspack-config-array/pull/1

**Comment by BeeeQueue** [comment]
Bump

**Comment by h-a-n-a** [comment]
This is related to the parallelism to the related tasks of the module graph creations. webpack's limit is `100` by default. We should support this as well.

**Comment by t0dorakis** [comment]
Hi there! Is a there a known workaround for this, so some kind of limit?
Our build peaks at a usage of more then 30gb (8gb in webpack).
We are using an array of 11 configs 🗡️

**Comment by beeequeue** [comment]
In my repro repo it seems that the issue has [been resolved](https://github.com/beeequeue/repro-rspack-config-array/actions/runs/9797253851/job/27053478625).
The build times increase in a logical manner the more builds you have going on at once.

**Comment by hardfist** [comment]
seems we can close this issue now
