### ISSUE TITLE
[Bug Report]:  TypeError: _definePropertyMjs is not a function when enable `builtins.presetEnv`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2433]
### System Info

 System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 570.06 MB / 32.00 GB
    
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/95486_1679541766094/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/95486_1679541766094/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/95486_1679541766094/bin/npm
    
    Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.6.1

### Details

TBD

### Reproduce link
https://github.com/IWANABETHATGUY/rspack-issue-2433
### Reproduce Steps

1. pnpm i 
2. pnpm dev

**Comment by KyrieLii** [comment]
Same here.

**Comment by lzsheng** [comment]
Same here.
