### ISSUE TITLE
[Bug Report]:  command line entry option's priority is not higher than config

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#2438]
### System Info

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 70.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.1
    @rspack/plugin-html: workspace:* => 0.1.1

### Details
![image](https://user-images.githubusercontent.com/87003751/227134564-75428a2c-ccfe-41ed-8bea-fb6d95587367.png)
This entry actually is not exist.

It can still build with entry in the config file.
![image](https://user-images.githubusercontent.com/87003751/227135453-3db50c1a-50de-4f9b-90c3-99743cb70a4d.png)
This is the main problem code. It will only process the entry in the command line when it cannot find a configuration file.

If this is indeed a problem, then I am willing to solve it.

### Reproduce Steps

cd examples/acro-pro
rspack --entry ./src/fasfsa.js // not exist actually

**Comment by ahabhgk** [comment]
If `--entry` has higher priorty than config file in `webpack-cli`, then it's a bug, feel free to make a PR if you willing to solve it 😃.

**Comment by faga295** [comment]
> The --entry-reset option is required to replace the existing [entry](https://webpack.js.org/configuration/entry-context/#entry) option, without it the --entry option will add another entry to the existing entries.
I noticed this in the webpack documentation. It’s not about priority. But the current behavior still differs from webpack.

**Comment by faga295** [comment]
but somtimes user don't want to write config file, specify entry through cli is more convenient.

**Comment by ahabhgk** [comment]
Then what the behavior should be when `--entry` and entry in config file exists at the same time? I don't want to introduce `--entry-reset` into `repack-cli` because it adds more complexity, and `rspack-cli` never meant to be the `webpack-cli` of `rspack`, it should be more out-of-box, like `parcel` or `CRA` but running `rspack` under the hood, for `webpack-cli` of `rspack`, it would be better to compatibility the APIs that `webpack-cli` is using by `rspack`, or a community project which behave like `webpack-cli`.

Thought? @hardfist

**Comment by faga295** [comment]
I agree with `rspack-cli` never meant to be the `webpack-cli` of `rspack`, and there is nothing wrong with the present behavior. I just noticed the behavior is not same as webpack, which could be confusing users, maybe we can state in the document.

**Comment by hardfist** [comment]
@faga295  command line `--entry` options has priority sounds good to me, I'm ok to accept PR to solve this and we don't want to introduce `--reset-entry` which seems too complex for cli options. I will add a PR to clarify the difference between `rspack-cli` and `webpack-cli`

**Comment by hardfist** [comment]
@faga295 we add documentation about the rspack-cli and webpack-cli difference, do you still want to work on this ?

**Comment by faga295** [comment]
Sure, I’m enthusiastic about it.

**Comment by faga295** [comment]
#2723  does rspack want remove entry option?

**Comment by hardfist** [comment]
we think webpack-cli's way of dealing with entry is too complex( config.entry --entry flags, --resetEntry and entry args), we want to simplify this, so we're considering only support entry flag and config.entry. the #2723 removes entry args(not entry flags).

**Comment by hardfist** [comment]
fixed in #2902
