### ISSUE TITLE
[Bug Report]: `relay: true` option shows "require is not defined" error 

### ISSUE THREAD

**Issue by Godsenal** [web-infra-dev/rspack#2440]
### System Info

  System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 439.22 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.08.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.4
  npmPackages:
    @rspack/cli: latest => 0.1.2 

### Details

Hi.
I'm trying to move my project's bundler to rspack. But encountered `"require is not defined"` error when using rspack with relay.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/21077928/227160477-ebbe5c7e-6d76-498c-ad27-d78f2bdc0e4e.png">

In main.js, it looks like rspack didn't transpile relay related syntax at all. (maybe ordering issue?)
```
// ...
globalThis.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
// here, relay related code
const Query = require("/Users/lth/rspack-project/src/__generated__/AppQuery.graphql.ts");
function App() {
    return (0, _jsxDevRuntimeJs.jsxDEV)("div", {
        className: "App",
        children: "Test"
    }, void 0, false, {
        fileName: "</Users/lth/rspack-project/src/App.tsx>",
        lineNumber: 14,
        columnNumber: 10
    }, this);
}
_c = App;
var _default = App;
// ...
```

 
here is reproduce repo and codesandbox
- [repo](https://github.com/Godsenal/rspack-relay-repor)
- [codesandbox](https://codesandbox.io/p/github/Godsenal/rspack-relay-repor/master?file=%2Frspack.config.js&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A21%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A21%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clfkwhst20000g6fo5del2scy%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Frspack.config.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfkwhw2l000e3b6n41zvls1t%2522%253A%257B%2522key%2522%253A%2522clfkwhw2l000e3b6n41zvls1t%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfkwqx1201dc3b6nx1sw8geu%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8080%252C%2522key%2522%253A%2522clfkwqx0401by3b6n8fafj23x%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfkwhw2l000e3b6n41zvls1t%2522%252C%2522spacesOrder%2522%253A%255B%2522clfkwhw2l000e3b6n41zvls1t%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

### Reproduce link

https://github.com/Godsenal/rspack-relay-repor

### Reproduce Steps

1. run "yarn dev"
2. open browser developer console

**Comment by JSerFeng** [comment]
Thank you for reporting this issue with minimum repro, I'll fix this soon
