### ISSUE TITLE
[Bug Report]: AMD build artifacts bugs

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#2443]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 140.73 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.2 => 0.1.2

## 1. Missing return of IIFE

In my demo , the output of webpack look like: 

<img width="803" alt="image" src="https://user-images.githubusercontent.com/16858738/227186614-8cf94a95-a3c5-41d8-a145-7552429a343e.png">

But rspack's product code not retrun IIFE :

<img width="821" alt="image" src="https://user-images.githubusercontent.com/16858738/227186461-f691ed52-a1bb-49c8-9186-1b80a3256b5f.png">

 Maybe something error here:  
https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_library/src/amd_library_plugin.rs#L71

### Reproduce link

https://github.com/KyrieLii/rspack-webpack-demo/tree/library-amd

### Reproduce Steps

See readme

**Comment by underfin** [comment]
closed at #2453
