### ISSUE TITLE
[Bug Report]: ERR_UNSUPPORTED_ESM_URL_SCHEME since version 0.1.2 on Windows OS

### ISSUE THREAD

**Issue by zakuru** [web-infra-dev/rspack#2449]
### System Info

 System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.61 GB / 7.85 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.2

### Details

Running the `yarn build` or `yarn dev` command on the react example will fail on windows OS starting version 0.1.2 of @rspack/cli
```
PS D:\github\rspack\examples\react> yarn build
yarn run v1.22.19
$ rspack build
rspack build [entry..]

run the rspack build

Positionals:
  entry  entry                                             [array] [default: []]

Options:
      --help        Show help                                          [boolean]
      --version     Show version number                                [boolean]
  -c, --config      config file                                         [string]
      --mode        mode                                                [string]
      --watch       watch                             [boolean] [default: false]
      --env         env passed to config function                        [array]
      --node-env    sets process.env.NODE_ENV to be specified value     [string]
      --devtool     devtool                           [boolean] [default: false]
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1056:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)    at requireWithAdditionalExtension (D:\github\rspack\examples\react\node_modules\@rspack\cli\src\utils\loadConfig.ts:87:3)
    at loadRspackConfig (D:\github\rspack\examples\react\node_modules\@rspack\cli\src\utils\loadConfig.ts:35:25)
    at RspackCLI.loadConfig (D:\github\rspack\examples\react\node_modules\@rspack\cli\src\rspack-cli.ts:189:44) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Error Seems to come from this line: https://github.com/web-infra-dev/rspack/compare/v0.1.1...v0.1.2#diff-d6c292e1bdc6c0e6bc53290c34f11de3cfa95e3438f501b03326492793ea7790R87

### Reproduce Steps

Go into the react example folder for instance at `rspack\examples\react`
Run:
1 - yarn install
2 - yarn dev / build

The error will show

**Comment by hardfist** [comment]
can you help try it in node@16 and see whether this problem still exists?

**Comment by hardfist** [comment]
!canary

**Comment by zakuru** [comment]
> can you help try it in node@16 and see whether this problem still exists?

I tried 14, 16 , 18 and get the same issue - so not related to node - the PR is ready just waiting for the test pipeline to finish and will tag you

**Comment by IWANABETHATGUY** [comment]
@zakuru Could we close this issue since https://github.com/web-infra-dev/rspack/pull/2450 has been merged?

**Comment by zakuru** [comment]
> @zakuru Could we close this issue since #2450 has been merged?

@IWANABETHATGUY Hello, yes we can close it as now the build works. But it uncovered another issue related to the dev server configuration I will post a new issue and description about it soon
