### ISSUE TITLE
[Bug Report]: 安装并run dev 报错

### ISSUE THREAD

**Issue by LiMao00** [web-infra-dev/rspack#2462]
### System Info

win

### Details

![image](https://user-images.githubusercontent.com/99939885/227646026-e39d94c0-eee4-401e-b607-885d363200c8.png)
这就尴尬了，直接pnpm create rspack@latest，pnpm install，pnpm run dev 就报错了，想试试都不行

### Reproduce Steps

pnpm create rspack@latest，pnpm install，pnpm run dev

**Comment by AntonyFagundez** [comment]
I have the same problem, I tried to recreate a basic migration in cra, following the documentation, and make a Example, with a github action running on windows (fails in start, and build):

https://github.com/AntonyFagundez/cra-rspack-migration/actions/runs/4516443380/jobs/7954779931


Here is the basic example: https://github.com/AntonyFagundez/cra-rspack-migration

**Comment by hardfist** [comment]
please retry again, this is caused by windows&node14 compatible problem which should be resolved in #2449,  you may solve this by upgrade node to node@16 or high version or use @rspack/cli@0.1.1 version

**Comment by AntonyFagundez** [comment]
Hi @hardfist thanks for the quick reply, in my case the test was on `windows`, `node lts` y `rspack/cli@0.1.2`. 

And working fine on `ubuntu-latest` but no in `windows-latest`.

https://github.com/AntonyFagundez/cra-rspack-migration/actions/runs/4516443380

**Comment by hardfist** [comment]
it seems you're using node@18 and it still has problem so https://github.com/web-infra-dev/rspack/issues/2449 may fix this issue, you can use `rspack@cli@0.1.1` to workaround it right now.

**Comment by AntonyFagundez** [comment]
It seems its not related to the node version,

https://github.com/AntonyFagundez/cra-rspack-migration/actions/runs/4516932936/jobs/7955735659

but yes with the version of cli

https://github.com/AntonyFagundez/cra-rspack-migration/actions/runs/4516971609


It seems I need to wait #2449. It's ok for me, if you need some help with this issue or PR, please let me now for help! I don't know rust lang but javascript it's ok for me.

**Comment by LiMao00** [comment]
![image](https://user-images.githubusercontent.com/99939885/227712150-c892bcbf-3f16-4f84-835c-b0ceaf344de9.png)
well
