### ISSUE TITLE
[Bug Report]: Calls to './x' will fail on Windows

### ISSUE THREAD

**Issue by zakuru** [web-infra-dev/rspack#2467]
### System Info

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.22 GB / 7.85 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.51)
    Internet Explorer: 11.0.22621.1

### Details

Hi,

Not really a bug but more about developer experience.
Any call to './x' from the various package.json files will fail on Windows OS
I was wondering if there was a specific reason to not replace them by 'node x'
If it is fine to do so I am willing to open a PR for it, just checking with you beforehand
Thanks 

### Reproduce Steps

on a windows os run:
yarn build:js of instance

you will then get this error `'.\x' is not recognized as an internal or external command,`

**Comment by hardfist** [comment]
related to #2261

**Comment by zakuru** [comment]
> related to #2261 

Ok let me know if a PR for this specific part would make sense

**Comment by hardfist** [comment]
we have not decided to which task script to use but welcome to discuss in #2261

**Comment by zakuru** [comment]
> we have not decided to which task script to use but welcome to discuss in #2261 

Ok noted thanks 👌

**Comment by hardfist** [comment]
is this fixed now? @hyf0

**Comment by zakuru** [comment]
> is this fixed now? @hyf0

Hi @hardfist 
Just tested and it works perfectly 
Thanks a lot 
Will close the ticket
