### ISSUE TITLE
[Bug Report]: 路径包含中文字符，启动报错

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#2477]
### System Info

  System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.73 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.3

### Details

启动项目时，如果项目路径包含中文字符，就会报错
![image](https://user-images.githubusercontent.com/69964024/227850954-c9ede2a2-73a8-4719-94ce-3a5e97fa49c7.png)

### Reproduce link

https://github.com/dingff/rspack-demo

### Reproduce Steps
1. Rename the folder using Chinese characters 
2. npx rspack serve

**Comment by dingff** [comment]
I have removed them, but could you please show me the error they are throwing? They look fine on my computer.

**Comment by hyf0** [comment]
Duplicate with https://github.com/web-infra-dev/rspack/issues/2546.
