### ISSUE TITLE
[Feature Request]:  Rspack should validate the version of nodejs

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2486]
### What problem does this feature solve?

Rspack doesn’t support nodejs lower than 12(include 12).

To provide a better experience, Rspack should validate the version of nodejs where Rspack is running.

### What does the proposed API of configuration look like?

nope.

**Comment by hyf0** [comment]
This is a good first issue!

You could add the following code

```jsx
const semver = require('semver');
const requiredVersion = '>=14.0.0';

if (!semver.satisfies(process.version, requiredVersion)) {
  throw new Error(`Node.js version must be ${requiredVersion}, but found ${process.version}.`)
}
```

 before this line

https://github.com/web-infra-dev/rspack/blob/28b9757460a57998e78474f4c448dadc7e1faf21/packages/rspack-cli/src/bootstrap.ts#L4

to solve this issue.

**Comment by hyf0** [comment]
> also need add notice to website

I think it could be done in a separate PR. I would also create an issue in https://github.com/web-infra-dev/rspack-website.

**Comment by ycjcl868** [comment]
```js
if (semver.lt(semver.clean(process.version), '14.0.0')) {
   // throw error
}
```

**Comment by amanx123** [comment]
Please assign me I would like to make this contribution real quick.

**Comment by hyf0** [comment]
> Please assign me I would like to make this contribution real quick.
> 
> 

Done. Thank you in advance.

**Comment by hyf0** [comment]
@amanx123 Hi, a friendly ping. Do you still work on this?
