### ISSUE TITLE
[Bug Report]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: PermissionDenied, error: "failed to invoke protoc (hint: https://docs.rs/prost-build /#sourcing-protoc): (path: \"F:\\\\.protoc\\\\bin\"): Access denied. (os error 5)" }' on Windows OS

### ISSUE THREAD

**Issue by yzydeveloper** [web-infra-dev/rspack#2490]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 2.82 GB / 7.89 GB
  Binaries:
    Node: 18.15.0 - F:\.node\node.EXE
    npm: 9.5.0 - F:\.node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: workspace:* => 0.1.2

### Details

error: failed to run custom build command for `sass-embedded v0.6.2`

Caused by:
  process didn't exit successfully: `E:\_github\rspack\crates\node_binding\target\release\build\sass-embedded-7b373f2e9a1a8692\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=ext/sass/sass-embedded.proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: PermissionDenied, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): (path: \"F:\\\\.protoc\\\\bin\"): 拒绝访问。 (os error 5)" }', F:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\sass-embedded-0.6.2\build.rs:12:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at BuildCommand.<anonymous> (E:\_github\rspack\node_modules\@napi-rs\cli\scripts\index.js:13018:30)
    at Generator.next (<anonymous>)
    at E:\_github\rspack\node_modules\@napi-rs\cli\scripts\index.js:3484:71
    at new Promise (<anonymous>)
    at __awaiter$1 (E:\_github\rspack\node_modules\@napi-rs\cli\scripts\index.js:3480:12)
    at BuildCommand.execute (E:\_github\rspack\node_modules\@napi-rs\cli\scripts\index.js:12839:16)
    at BuildCommand.validateAndExecute (E:\_github\rspack\node_modules\@napi-rs\cli\scripts\index.js:2010:37)

### Reproduce Steps

e.g. 
`pnpm run build:binding:release` or `cargo build`

**Comment by ahabhgk** [comment]
duplicate with:
- https://github.com/tokio-rs/prost/issues/830
- https://github.com/ahabhgk/sass-embedded-host-rust/issues/44

Rspack is a downstream project which using sass-embedded-host-rust, and sass-embedded-host-rust is using prost, you should keep following up [issue in prost](https://github.com/tokio-rs/prost/issues/830).
