### ISSUE TITLE
[Bug Report]: hot reload is not working when using custom memo function in React

### ISSUE THREAD

**Issue by Shad02w** [web-infra-dev/rspack#2498]
### System Info

 System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 78.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/Library/Caches/fnm_multishells/41915_1679985898031/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/41915_1679985898031/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/41915_1679985898031/bin/npm
  Browsers:
    Safari: 16.3

### Details

React hot reload failed when i wrapped a component with custom memo function
```javascript
function memo(displayName, functionComponent) {
    return React.memo(Object.assign(functionComponent, { displayName }))
}

const UnwrappedApp = memo('App', () => {
    const [count, setCount] = React.useState(0)

    return (
        <div className="App">
            <div>
                <a href="https://reactjs.org" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>
            <h1>Rspack + React</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
                <p>
                    Edit <code>src/App.jsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">Click on the Rspack and React logos to learn more</p>
        </div>
    )
})


export const App = memo('App', UnwrappedApp)
```
when i update text in component, rspack did a full reload instead of hot reload. Hot reload works as expected when export `App` with `React.memo`. It does not seem to be a issue on webpack or vite.

![Snipaste_2023-03-28_15-13-38](https://user-images.githubusercontent.com/6605655/228159242-3eca76e6-51cd-440e-ba06-987c5fbd1921.png)

### Reproduce link

https://github.com/Shad02w/rspack-hmr-repro

### Reproduce Steps

1. create project `pnpm create rspack@latest`
2. start dev server
3. update text in `App`
4. page get full reload

**Comment by underfin** [comment]
@Shad02w It already fixed after aligin to `react-refresh-webpack-plugin`, you can have a try with latest version.I will close this issue, feel free to open a new issue if you have any new issues.
