### ISSUE TITLE
[Bug Report]: TypeError: Cannot read properties of undefined (reading 'createElement') when enable builtins.presetEnv 

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2501]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 212.36 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 15.6.1

### Details

<img width="749" alt="image" src="https://user-images.githubusercontent.com/22373761/228160087-34d6c3a3-7d20-49b7-b85e-40c9293eb721.png">

### Reproduce link

https://github.com/web-infra-dev/modern.js/tree/test/rspack-3-28

### Reproduce Steps

1. pnpm install
2. cd tests/integration/webpack-builder
3. DEBUG=builder pnpm dev:rspack
4. open the browser

Everything works fine when disable presetEnv:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/22373761/228162036-6d6c18e4-a83f-484e-87d8-a345cff417c1.png">
tests/integration/webpack-builder/scripts/shared.ts

**Comment by underfin** [comment]
colsed at #2503
