### ISSUE TITLE
test modernjs before release

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2502]
we should make sure all modernjs ci pass before release stable version otherwise we will need to fix and release again, this may evolves like https://github.com/vitejs/vite-ecosystem-ci in the future

**Comment by Boshen** [comment]
I want to change ecosystem ci to nightly, and also trigger it from the github ui instead of a issue comment (This reduces noise from the github actions page).

**Comment by Boshen** [comment]
Automating this takes some time so I decided to do this manually. I have added this process to our internal release document.
