### ISSUE TITLE
[Bug Report]:  WASM runtime code in Rspack should target es5

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2504]
### System Info

None

### Details

Becasue rspack insert runtime need keep es5, avoid break old broswers

### Reproduce Steps

See https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_wasm/src/runtime/async-wasm-loading.js 
https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_runtime/src/runtime_module/runtime/async_module.js

**Comment by hyf0** [comment]
Closed due to not being sure if it's a bug.
