### ISSUE TITLE
[Bug Report]: Unexpected warning from export variables

### ISSUE THREAD

**Issue by Lantianyou** [web-infra-dev/rspack#2521]
### System Info

  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 39.11 GB / 62.26 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 102.0
  npmPackages:
    @rspack/cli: latest => 0.1.1 
    @rspack/core: ^0.1.3 => 0.1.3 
    @rspack/dev-server: ^0.1.3 => 0.1.3 

### Details

![image](https://user-images.githubusercontent.com/37259750/228435218-01d32c1c-e81e-4dca-9035-5ca678e410a8.png)

### Reproduce Steps

Seems like the there will be warning in the following, however, the build is successful
```
const bar = { foo: () => {} }
export const {foo} = bar
```

**Comment by Lantianyou** [comment]
As far as I understand, there should be a fixtures cover the above code , like this https://github.com/web-infra-dev/rspack/commit/edd66e02e33c5c1dd72ad26a7e0c96ff051f64bb

**Comment by Lantianyou** [comment]
I believe the above code is a correct, as they are used extensivily in `@reduxjs/toolkit` https://redux-toolkit.js.org/tutorials/typescript

**Comment by HerringtonDarkholme** [comment]
I'm interested. Can I take a try?

**Comment by IWANABETHATGUY** [comment]
> I'm interested. Can I take a try?

sure

**Comment by HerringtonDarkholme** [comment]
Looks like the problem locates in crates/rspack_core/src/tree_shaking/visitor.rs, where we didn't handle destructring.

**Comment by IWANABETHATGUY** [comment]
> Looks like the problem locates in crates/rspack_core/src/tree_shaking/visitor.rs, where we didn't handle destructring.

yeah

**Comment by Lantianyou** [comment]
Fantastic work. Thank you @IWANABETHATGUY @HerringtonDarkholme
