### ISSUE TITLE
[Bug Report]: ReferenceError: xxx is not defined when enable builtins.presetEnv

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2523]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 120.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.3 => 0.1.3 

### Details

<img width="925" alt="image" src="https://user-images.githubusercontent.com/22373761/228441747-c2ee35ac-6a6c-4663-a3df-2a087058a813.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/22373761/228441896-300d1a27-77ad-494d-bbc3-2b45521fef76.png">

### Reproduce link

https://github.com/9aoy/rspack-issue-reproduce/tree/main/rspack-_int-error

### Reproduce Steps

1. npm install
2. npm run dev
3. open the browser

**Comment by underfin** [comment]
The `int` is es3 reserved words in js, so you want it works need exclude this transfrom, but rsapck isn't export it. So here need export more config of swc preset env, at here https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs#L16. After this you can add `presetEnv.exclude: ['transform-reserved-words']` to disable this transform.

playground: https://play.swc.rs/?version=1.3.40&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP18jMK9HkAgCb7Xa9EQAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSwrCMBCGryID7lKpC1104Q08gbgI6bRE8igzSW0pubtJqHQ38z8%2B%2Fg0%2BrKDbYJLESOXi1QW5QAeorGRFegogcixLgSImAUHSiKEk%2BJYt4z0jdIM0jAKsdnpYC0h5OxEyH5Z0o%2FknUwZZ38cibBDWCSvwDulg7D3Nzz1YBghAN9dOnZHx8Di1l%2FZ6hkosnMhyxPziokwsygsCSceDJ9vkTUgz9s3XU8%2FwTukHpOT4cgYBAAA%3D

**Comment by underfin** [comment]
Compare with babel https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzsAdvAvnAZlCI4DkAdAPQCGRAVgM4EBQdAxhCtRADYCmR7EA5gApUMAJRA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.21.3&externalPlugins=%40babel%2Fplugin-transform-reserved-words%407.18.6&assumptions=%7B%7D. it is a swc bug.

**Comment by underfin** [comment]
opened a issue at swc. https://github.com/swc-project/swc/issues/7164
