### ISSUE TITLE
[Feature Request]: export more preset env config from swc

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2530]
### What problem does this feature solve?

export more preset env config from swc 

### What does the proposed API of configuration look like?

 here https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/swc_visitor/compat.rs#L16

**Comment by hyf0** [comment]
Close for stale. Please re-open it if you think the issue is solved.
