### ISSUE TITLE
[Bug Report]: The DCD-DATA project throw error while importing picture via https in less file 

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2551]
### System Info

.

### Details

![image](https://user-images.githubusercontent.com/49502170/228749835-2deede2c-0111-45ee-95c6-93479a4835c2.png)

### Reproduce Steps

![image](https://user-images.githubusercontent.com/49502170/228749949-253f76cb-f5b6-4d5e-8962-754c2ead60b6.png)

**Comment by ahabhgk** [comment]
@hyf0 What's the version are you using, this should be fixed in https://github.com/web-infra-dev/rspack/pull/2404
