### ISSUE TITLE
[Bug Report]: MultiCompiler crashes with parallelism = infinity

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#2566]
### System Info

All

### Details

The MultiCompiler currently sets `parallelism` to `INFINITY`, which makes the Rspack Compiler go into an inconsistent state and spawns threads until it run of threads and crashes.

We can set `parallelism = 1` to fix this.

Relates to
* https://github.com/web-infra-dev/rspack/issues/2448
* https://github.com/web-infra-dev/rspack/issues/2431

### Reproduce link

https://github.com/tbranyen/rspack-webpack-example/commit/22b741f5080a3a64da044cb58b7f4642fbfd5b58

### Reproduce Steps

See repro in https://github.com/web-infra-dev/rspack/issues/2448

**Comment by hardfist** [comment]
we should separate this to two tasks:
* workaround multi-compiler problems by set parallelism @Boshen 
* investigate multi compiler instance coexist problem @h-a-n-a
