### ISSUE TITLE
[Bug Report]: output.filename [id] not work 

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#2570]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 132.39 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.4 => 0.1.4 

### Details

ref: https://www.rspack.dev/config/output.html#outputfilename  

rspack.config.js:
```
// ...
output: {
   filename: `[id].bundle.js`,
},
```
output: 

<img width="241" alt="image" src="https://user-images.githubusercontent.com/16858738/229052882-08b6d2b8-4d8e-48f0-a922-696419ffa992.png">

And you can see with same config that webpack has successfully replaced [id] .

Thks guys.

### Reproduce link

https://github.com/KyrieLii/rspack-webpack-demo/tree/chunk-id

### Reproduce Steps

Please see README

**Comment by hyf0** [comment]
Rspack already supports this feature. 

The difference between Rspack and Webpack is Rspack currently doesn't support the `numberic` id in the production build.

`main` in `main.bundle.js` is the id, which is the result after Rsapck doing replacements.
