### ISSUE TITLE
[Feature Request]:  Storybook support

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#2591]
### What problem does this feature solve?

Use rspack as storybook builder, this issue is for tracking some issues related to it

https://github.com/storybookjs/storybook/issues/21561

### What does the proposed API of configuration look like?

@storybook/builder-rspack

**Comment by hardfist** [comment]
supported https://www.rspack.dev/guide/migrate-storybook.html

**Comment by stanfortonski** [comment]
Waiting for supporing version Storybook 8

**Comment by the-simian** [comment]
The link @hardfist posted moved here: https://www.rspack.dev/guide/migration/storybook
