### ISSUE TITLE
[Bug Report]: Stats module reasons compared to webpack (userRequest and other fields missing)

### ISSUE THREAD

**Issue by lalexdotcom** [web-infra-dev/rspack#2593]
### System Info

devcontainer
```
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (5) arm64 unknown
    Memory: 15.93 GB / 23.45 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @rspack/cli: ^0.1.5 => 0.1.5 
```

### Details

Thanks to #2573 workaround, I could have the reason property on modules' compilation stats.
But some fields are missing in RSPack reasons (JsStatsModuleReason) compared to webpack (StatsModuleReason type)
(I'm showing TS types which should be clearer for reporting)

RSPack
```typescript
export interface JsStatsModuleReason {
  moduleIdentifier?: string
  moduleName?: string
  moduleId?: string
}
```
Webpack
```typescript
declare interface KnownStatsModuleReason {
	moduleIdentifier?: string;
	module?: string;
	moduleName?: string;
	resolvedModuleIdentifier?: string;
	resolvedModule?: string;
	type?: string;
	active: boolean;
	explanation?: string;
	userRequest?: string;
	loc?: string;
	moduleId?: string | number;
	resolvedModuleId?: string | number;
}
```
I'm mainly after the `userRequest` property, but others may be used...

~~By the way, the `module` field is now `moduleId`, shouldn't it be ISO with webpack for better interoperability?~~ (my bad, moduleId is there 😅)

### Reproduce link

https://github.com/lalexdotcom/rspack-bug-report rspack-module-reason-type

### Reproduce Steps

**!! Be sure to be on rspack-module-reason-type branch !!**

1. run `npm install`
2. RSPack output: run `npm run rspack-stats-output`
```
Reasons found fields [ 'moduleIdentifier', 'moduleName', 'moduleId' ]
```
3. Webpack output: run `npm run webpack-stats-output`
```
Reasons found fields [
  'moduleIdentifier',
  'module',
  'moduleName',
  'resolvedModuleIdentifier',
  'resolvedModule',
  'type',
  'active',
  'explanation',
  'userRequest',
  'loc',
  'moduleId',
  'resolvedModuleId'
]
```

**Comment by ScriptedAlchemy** [comment]
Nice to have, especially helpful for tools like medusa which do consume alot of info about module reasons
