### ISSUE TITLE
[Bug Report]: Why is there an extra space after the hash value？

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#2594]
### System Info

System:
    OS: macOS 13.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.17 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - /usr/local/bin/npm

### Details

After I set `builtins.css.modules.localIdentName` to `'[local]--[hash:6]'`, I noticed there was a weird space after the hash.
![image](https://user-images.githubusercontent.com/69964024/229471088-79c3d82c-a1cd-43fb-990e-4dc441d1b4d1.png)

### Reproduce link

https://github.com/dingff/rspack-template

### Reproduce Steps

1. yarn dev

**Comment by ScriptedAlchemy** [comment]
Good catch. Ive seen this in webpack before but dont think the cause is mutually exclusive.
