### ISSUE TITLE
ForkTSCheckerWebpackPlugin support

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2602]
[fork-ts-checker-webpack-plugin](https://www.npmjs.com/package/fork-ts-checker-webpack-plugin) is widely used, we need to support it

**Comment by hyf0** [comment]
I'm not quite familiar with `ForkTSCheckerWebpackPlugin`.

So, my thoughts may be subjective. IMO, `ForkTSCheckerWebpackPlugin` is complicated, but the goal is actually quite simple: invoking type-check during compiling.

To achieve this goal, I'm more in favor of how https://github.com/fi3ework/vite-plugin-checker is used.

I'm talking to @fi3ework to see how we could use https://github.com/fi3ework/vite-plugin-checker in Rspack and Webpack.

**Comment by ycjcl868** [comment]
watching

**Comment by hardfist** [comment]
port https://github.com/fi3ework/vite-plugin-checker to rspack is feasible

**Comment by acnebs** [comment]
When using `fork-ts-checker-webpack-plugin` with rspack, I get frequent errors (about 50% of the time it seems) related to process communication.

```
Error: write EPIPE
    at target._send (node:internal/child_process:872:20)
    at target.send (node:internal/child_process:745:19)
    at /[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

Whether or not it works is incredibly random. I will try to start the dev server and it will fail, and then (with no code changes) I will try again and it will work. It seems to be slightly *less* likely to fail after repeated attempts, and most likely to fail if I haven't built in a while.

**Comment by hardfist** [comment]
> When using `fork-ts-checker-webpack-plugin` with rspack, I get frequent errors (about 50% of the time it seems) related to process communication.
> 
> ```
> Error: write EPIPE
>     at target._send (node:internal/child_process:872:20)
>     at target.send (node:internal/child_process:745:19)
>     at /[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
>     at new Promise (<anonymous>)
>     at sendMessage (/[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
>     at /[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
>     at Generator.next (<anonymous>)
>     at fulfilled (/[PATH]/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errno: -32,
>   code: 'EPIPE',
>   syscall: 'write'
> }
> ```
> 
> Whether or not it works is incredibly random. I will try to start the dev server and it will fail, and then (with no code changes) I will try again and it will work. It seems to be slightly _less_ likely to fail after repeated attempts, and most likely to fail if I haven't built in a while.

can you file a separate issue for this

**Comment by guillaume-docquier-vention** [comment]
For future readers, it's documented on the rspack compatibility page: https://rspack.dev/guide/compatibility/plugin
`fork-ts-checker-webpack-plugin` has an alternative with [`ts-checker-rspack-plugin`](https://github.com/rspack-contrib/ts-checker-rspack-plugin)

I found that `fork-ts-checker-webpack-plugin` worked fine most of the time, but rarely I got the following error: `Error: Unable to access compilation with id = CompilationId(1) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(114)`

**Comment by shirakaba** [comment]
I still get those EPIPE issues with [ts-checker-rspack-plugin](https://github.com/rspack-contrib/ts-checker-rspack-plugin) :/

```
Error: write EPIPE
    at target._send (node:internal/child_process:878:20)
    at target.send (node:internal/child_process:751:19)
    at /Users/jamie/Documents/git/banana_native/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:18:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/jamie/Documents/git/banana_native/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:10:38)
    at process.handleMessage (/Users/jamie/Documents/git/banana_native/node_modules/ts-checker-rspack-plugin/lib/rpc/expose-rpc.js:51:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by 1714080902120** [comment]
@shirakaba Hi, can you provide a demo and create a separate issue? I'm also having this issue on a Linux arm64 cloud server, but I can't reproduce the bug in docker. And I'm using rspack, rspack 1.3.2 is fine, but I've had this issue since 1.3.3.
