### ISSUE TITLE
ecosystem-ci

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2609]
reference:

- vite: https://github.com/vitejs/vite-ecosystem-ci
- vue: https://github.com/vuejs/ecosystem-ci

our ecosystem for now:

- rspack-plugins: https://github.com/rspack-contrib/rspack-plugins
- modern.js: https://github.com/web-infra-dev/modern.js
- nx: https://github.com/nrwl/nx-labs/tree/main/packages/rspack

**Comment by hardfist** [comment]
add nx to the list

**Comment by hardfist** [comment]
add `npm create rspack@latest` test to test our scaffold

**Comment by hyf0** [comment]
Close by for we have implemented the ecosystem-ci
