### ISSUE TITLE
[Feature Request]: Support __webpack_chunk_load__

### ISSUE THREAD

**Issue by GiveMe-A-Name** [web-infra-dev/rspack#2613]
### What problem does this feature solve?

In Modern.js, when the user navigate the route, we will load the required resources and data in parallel according to the route to avoid the problem of request serialization, currently the way to load is through APIs provided by tools, such as webpack_chunk_load of Webpack, or preloadRemote of Vmok, here we hope Rspack can provide a similar API to load the required static resources based on chunk id.

Currently chunk ids are obtained from webpack stats, so we also relies on support for stats.namedChunkGroups.

### What does the proposed API of configuration look like?

Align webpack [__webpack_chunk_load__](https://webpack.js.org/api/module-variables/#__webpack_chunk_load__-webpack-specific) api

**Comment by hyf0** [comment]
Move tracking to https://github.com/web-infra-dev/rspack/issues/3070. A contributor would like to take on this work :).
