### ISSUE TITLE
[Feature Request]: add normalModuleFactory.hooks.afterResolve

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#2619]
### What problem does this feature solve?

Adding to #2446 and in order to use the `DedupeModuleResolvePlugin` from [Angular](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts#L53) we need to add the afterResolve hook on Normal Module Factory.  Currently trying to add this plugin throws the below error. 

```bash
[rspack-cli] [Error: napi error: GenericFailure - TypeError: Cannot destructure property 'normalModuleFactory' of 'undefined' as it is undefined.
    at /Users/packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts:52:23
```

### What does the proposed API of configuration look like?

This should work as expected: `plugins: [new DedupeModuleResolvePlugin()]`

**Comment by edusperoni** [comment]
The actual error is:

```
[rspack-cli] [Error: napi error: GenericFailure - TypeError: Cannot read properties of undefined (reading 'tap')
    at /Users/eduardosperoni/projects/packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts:53:48
```

The first error is fixed by exposing `normalModuleFactory` in the `compilation` hook (https://github.com/zackarychapple/rspack/commit/8c430de49177ff841eaa8f373112f342b1fbad2e). As expected, the error is due to the missing `normalModuleFactory.hooks.afterResolve` hook
