### ISSUE TITLE
[Feature Request]: A bot to lock closed issues

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2631]
### What problem does this feature solve?

Open-source projects often have a bot to lock closed issues as a way to prevent further comments or updates on issues that have already been resolved or closed. 

This is done to keep the issue tracker organized and prevent clutter. By locking closed issues, the project maintainers can ensure that the focus remains on open issues and new feature requests, rather than on issues that have already been addressed. 

Additionally, locking closed issues can help prevent spam or inappropriate comments from being posted on these issues.

### What does the proposed API of configuration look like?

.

**Comment by ahabhgk** [comment]
ecosystem-ci also needs a bot to comment ci result in PR.

**Comment by Boshen** [comment]
I find it pretty annoying to see bot comments in my notifications. I think issue locking should only be used for abnormal behaviours instead of abusing it for shutting people off.

**Comment by hyf0** [comment]
> I find it pretty annoying to see bot comments in my notifications. I think issue locking should only be used for abnormal behaviours instead of abusing it for shutting people off.

I'm not sure I understand you correctly.

The [reason](https://github.com/web-infra-dev/rspack/issues/2631#issue-1656611645) for having a stale bot is quite clear. Could you point out what's the abusing part you may think of?

**Comment by Boshen** [comment]
You premise is to keep the issue tracker organized and prevent clutter, my premise is that issue locking should be used for violating code of conducts, as stated in https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations

I just find it annoying to see notifications coming from bots. I don't see people commenting on closed issues and PRs as clutter if the conversation is meaningful and we actually want to reopen the issue for tracking context.

**Comment by hyf0** [comment]
> I just find it annoying to see notifications coming from bots.

I also find it annoying to see a closed issue from one years ago and say "You didn't fix the problem".

>  I don't see people commenting on closed issues and PRs as clutter if the conversation is meaningful

I see people commenting on closed issues and PRs as clutter if the conversation is spam

> We actually want to reopen the issue for tracking context.

I believe a link to the original issue would be enough. Also, IMO, a closed issue locked due to outdated shows its completeness of itself.

---

The intention is to lock closed/solved outdated issues such as two/three months before. And encourage people to file a new one.

I also find that encouraging to create a new issue is more fits with our workflow per week.

Let's hear some suggestions from @hardfist.

**Comment by hardfist** [comment]
I also think issue closed by bot is kind of impolite for user who file the issue, maybe we could send the alert message to teams, and let team member closes issue manually if the issue is not useful anymore or update issue state if it's just ignored by ourself.

**Comment by hyf0** [comment]
Sync up:

The issue is on hold for not sure whether we would fall into the spam situation.

**Comment by Boshen** [comment]
See 
* https://github.com/web-infra-dev/rspack/pull/3065
