### ISSUE TITLE
[Feature Request]: Redesign builtins.noEmitAssets

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2639]
we introduce builtins.noEmitAssets to solve performance problems in internal projects, which could reduce lots communication cost of passing assets from rust to js side, but it causes several problems
* it's not working well with webpack-dev-server middleware(historyapiFallback, compress and so on)
* it's misleading, it actually can't control whether emitAsset to Disk

**Comment by hyf0** [comment]
Related discussion: https://github.com/web-infra-dev/rspack/discussions/2742

**Comment by hyf0** [comment]
We currently have no manpower for it.
