### ISSUE TITLE
[Bug Report]: builtins.css.modules covered custom modules rules by postcss-loader

### ISSUE THREAD

**Issue by MatrixAge** [web-infra-dev/rspack#2652]
### System Info

  System:
    OS: macOS 13.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 398.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Browsers:
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.1.6 => 0.1.6 

### Details

builtins.css.modules covered custom modules rules by postcss-loader, config like this:

### config
```js
      builtins: {
		sourceMap: false,
		decorator: {},
		css: {
			modules: {
				exportsOnly: true
			}
		}
	},
	module: {
		rules: [
			{
				test: /\.module\.less$/i,
				use: [
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {
								modules: true,
								extract: false,
								plugins: [PostCssImport(), PostCssNested()]
							}
						}
					}
				],
				type: 'css/module'
			}
		]
	}
```

### output:
![image](https://user-images.githubusercontent.com/25472851/230467209-621fb442-6ae8-405b-b6c2-f5e15cd5f519.png)

### source
![image](https://user-images.githubusercontent.com/25472851/230467421-77a226ad-bebb-4bd4-bbd3-75423c8cd555.png)

### question
![image](https://user-images.githubusercontent.com/25472851/230467588-056ff794-f1c9-4fa2-b51e-cb0ac1865357.png)

builtins.css.modules & postcssOptions.extract, which one is right? and how to inject inline css correctly?

### rollup output
this is rollup output with same config for postcss
![image](https://user-images.githubusercontent.com/25472851/230468087-4747e927-36a8-41f0-8b02-7b87f5df0569.png)

![image](https://user-images.githubusercontent.com/25472851/230468229-58005cb4-eb21-4ca1-be22-af812d87b315.png)

I guess something error when builtins.css.modules & postcssOptions.extract all be set.

by the way, rspack is faster then rollup, 700ms >>> 4.5s.

### Reproduce Steps

see details.

**Comment by hyf0** [comment]
@ahabhgk. Would you mind taking a look at this?

**Comment by ahabhgk** [comment]
`modules` and `extract` is not exists in postcss-loader's [`postcssOptions`](https://github.com/webpack-contrib/postcss-loader#postcssOptions), webpack is using `css-loader` or `experiment.css` to process css modules.

**Comment by MatrixAge** [comment]
> `modules` and `extract` is not exists in postcss-loader's [`postcssOptions`](https://github.com/webpack-contrib/postcss-loader#postcssOptions), webpack is using `css-loader` or `experiment.css` to process css modules.

so how to inject inline style by exportsonly？likely it did not work in my case.

**Comment by ahabhgk** [comment]
You mean inline style in javascript like `style-loader` dose? We haven't support that yet.

**Comment by MatrixAge** [comment]
> You mean inline style in javascript like `style-loader` dose? We haven't support that yet.

The "builtins.css.modules.exportsOnly" seems to be of little use, as the documentation suggests it is meant for SSR scenarios, yet it does not inject any styles, only classes. It appears to be quite futile.

**Comment by hyf0** [comment]
Close for stale. Please re-open it if you think the issue is not solved.
