### ISSUE TITLE
[Feature Request]: support public path per entrypoint

### ISSUE THREAD

**Issue by kiliancs** [web-infra-dev/rspack#2653]
### What problem does this feature solve?

Support `publicPath` per `EntryDescription`, like webpack, as per the docs: https://webpack.js.org/concepts/entry-points/#entrydescription-object. Note other docs are outdated and don't reflect this property.

I believe this is necessary for some of the mini-css-extract-plugin codepaths during the build (where `__webpack_public_path__` doesn't apply).

See https://github.com/webpack/webpack/pull/13137 as well.

### What does the proposed API of configuration look like?

`EntryDescription` gains a `publicPath` property of the same time as `output.publicPath`.

**Comment by hyf0** [comment]
> ### What problem does this feature solve?
> Support `importPath` per `EntryDescription`, like webpack, as per the docs: https://webpack.js.org/concepts/entry-points/#entrydescription-object. Note other docs are outdated and don't reflect this property.

```js
module.exports = {
  entry: {
    a2: 'dependingfile.js',
    b2: {
      dependOn: 'a2',
      import: './src/app.js',
    },
  },
};
```

For `importPath`, did you mean the `import` property in the above config?

**Comment by kiliancs** [comment]
Errr... no, sorry. This is why I shouldn't try to do more than one thing at once. I meant `publicPath` (I had it wrong in the title and in one key location in the description, sorry).

**Comment by hyf0** [comment]
Good. Thanks for clarifying. I would mark this issue as planned to solve.
