### ISSUE TITLE
[Bug Report]: The compile time printed is NaN

### ISSUE THREAD

**Issue by nieyuyao** [web-infra-dev/rspack#2654]
### System Info

 System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 88.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 15.4
  npmPackages:
    @rspack/cli: workspace:* => 0.1.6 

### Details

The compile time becomes `NaN` on the latest code.

### Reproduce Steps

Steps as follows:
1. `git checkout main`
2. `pnpm build:cli:debug`
3. `cd examples/basic`
4.  `pnpm dev`

The `Time` becomes `NaN`.
```
Rspack ████████████████████████████████████████ 100% done
Time: NaNms
```

**Comment by hyf0** [comment]
I marked this issue as planned to solve. In the meanwhile, welcome anyone who wants to take a look at this.

**Comment by HerringtonDarkholme** [comment]
Fix in bound!
![image](https://user-images.githubusercontent.com/2883231/230542730-74da8b44-e437-4e50-b5a5-2e3d9ab6bbbb.png)
