### ISSUE TITLE
[Bug Report]: Polyfill & Swc Helpers & tslib module should skip compat transform

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2664]
### System Info

-

### Details

![image](https://user-images.githubusercontent.com/14008915/230578943-bdad3125-b377-4e9f-883e-ccd7b8878c65.png)

### Reproduce Steps

Use config.js add 

``` .js
module.exports = {
    "target": [
	"web",
	"es5"
    ],
}
```

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
should be fixed in builtin:swc-loader
