### ISSUE TITLE
[Feature Request]: Support esm exports for config files

### ISSUE THREAD

**Issue by RobinClowers** [web-infra-dev/rspack#2668]
### What problem does this feature solve?

Typescript and node support esm, and it's confusing that the config file requires using a commonjs export.

### What does the proposed API of configuration look like?

Rspack should look for a default export first, and fall back to using the named exports if it doesn't find the default export.

**Comment by hardfist** [comment]
rspack supports esm config https://github.com/web-infra-dev/rspack/blob/main/packages/rspack-cli/tests/build/basic/entry.config.mjs

**Comment by RobinClowers** [comment]
Oh cool, I will try that out! Seems like it needs to be added to the docs, unless I missed it?

**Comment by hyf0** [comment]
Closed for having https://github.com/web-infra-dev/rspack-website/issues/267.
