### ISSUE TITLE
[Bug Report]: Empty scss or css file is referenced by bundle but bundle is removed

### ISSUE THREAD

**Issue by th3fallen** [web-infra-dev/rspack#2670]
### System Info

  System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 43.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Firefox Developer Edition: 110.0
    Safari: 16.4
  npmPackages:
    @rspack/cli: latest => 0.1.6
    @rspack/plugin-html: latest => 0.1.6

### Details

When building a react project if you have any component import a css or scss file that happens to be empty the resulting bundle will crash because it's trying to import a bundle that is never output as a file.

### Reproduce Steps

in any react example component import a css or scss file that is empty
watch the fireworks.

**Comment by th3fallen** [comment]
even happens with 
```
optimization: {
      removeEmptyChunks: false,
    },
```

**Comment by th3fallen** [comment]
luckily the easy solution is the obvious one.... delete the empty files and import references to them...

**Comment by hyf0** [comment]
Would you mind providing a minimal reproduction repo?

**Comment by th3fallen** [comment]
> 

sure, https://github.com/th3fallen/rspack-bug-sass-include-paths just run yarn dev and you'll see it

**Comment by hyf0** [comment]
Thank you. We'll fix it soon.

**Comment by th3fallen** [comment]
👍 thank you
