### ISSUE TITLE
[Bug Report]:  HMR update too many times 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2674]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 293.05 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Yarn: 3.2.2 - ~/Library/Application Support/fnm/node-versions/v16.17.1/installation/bin/yarn
    npm: 8.15.0 - ~/Library/Application Support/fnm/node-versions/v16.17.1/installation/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox Developer Edition: 111.0
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.6 => 0.1.6 

### Details

https://user-images.githubusercontent.com/8898718/230747115-af2b89f4-5f4d-4f63-9397-9b47587b15cf.mov

### Reproduce Steps

https://github.com/sapphi-red/performance-compare/tree/81e8bd2bb1192566ff18f284fd78691d2d417c0d
upgrade rspack to 0.1.6 and run start:rspack

**Comment by hardfist** [comment]
it works fine on 0.1.5 and maybe related to https://github.com/web-infra-dev/rspack/pull/2576? cc @bvanjoi

**Comment by bvanjoi** [comment]
I can't reproduce this problem, can you give me the specific steps to reproduce it?

relative: https://github.com/web-infra-dev/rspack/issues/2169
