### ISSUE TITLE
[Bug Report]: Usage Polyfill issue

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2680]
### System Info

-

### Details

enable`builtins.presetEnv`, but core-js has some issue.

``` js
// entry code
console.log(new Set())
```

``` js
// rspack.config.js
module.exports = {
       builtins: presetEnv: {
        targets: [
          '> 0.01%',
          'not dead',
          'not op_mini all'
        ],
        mode: 'usage',
        coreJs: '3.26'
    }
}
```

### Reproduce Steps

-

**Comment by suxin2017** [comment]
"mode": "usage",

**Comment by suxin2017** [comment]
Maybe you can take a look at this hope to help you
https://babeljs.io/docs/babel-preset-env#usebuiltins-entry

**Comment by underfin** [comment]
I have a try with `mode: 'usage'`, found some issue with usage polyfill.

1. need users install `core-js`
2. need users alias `core-js`, config is 
``` js
resolve: {
    alias: {
	    "core-js": require('path').dirname(require.resolve("core-js"))
    }
}
```
3. same issue with https://github.com/web-infra-dev/rspack/issues/2664

**Comment by hardfist** [comment]
I prefer let user to do the alias work because polyfill solution is very subjective, and different framework choose different polyfill solution.  see also https://github.com/vercel/next.js/discussions/36601, so when use set usage to entry or usage, they should set right config to make polyfill working for themselves.

**Comment by hardfist** [comment]
we need add document about how to use `presetEnv.mode`

**Comment by chenjiahan** [comment]
Agreed, the alias of core-js should not be a default behaviour. 


The latest version of core-js is 3.x, but some legacy packages still depend on core-js 2.x. And the subpath of core-js 2.x and core-3.x is different. If Rspack aliases all core-js imports to the same path, it will break these legacy packages. So we should let users decide whether to add the core-js alias config.

**Comment by underfin** [comment]
closed at https://github.com/web-infra-dev/rspack-website/pull/293
