### ISSUE TITLE
[Feature Request]: Introduce `corepack` in Rspack workflow

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2693]
### What problem does this feature solve?

See contexts in https://github.com/web-infra-dev/rspack/pull/2678#discussion_r1162250931

### What does the proposed API of configuration look like?

.

**Comment by hyf0** [comment]
Sync up:

We have discussed this and going to introduce `corepack` in the Rspack repo. After this, The affection of updating the version of Pnpm would be reduced a lot.

We are also going to write a `setup` script to help contributors finish all setup work before running `pnpm install`.

**Comment by Boshen** [comment]
`corepack` is being used in CI build now

https://github.com/web-infra-dev/rspack/blob/fdc5fd9d8243be41ef6cbdf7cad45b513463826b/.github/actions/docker-test/action.yml#L41

**Comment by hyf0** [comment]
Closed by #2754
