### ISSUE TITLE
[Bug Report]: Tree shaking has bug with bump swc.

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2699]
### System Info

-

### Details

![image](https://user-images.githubusercontent.com/14008915/231068335-6ebde002-01b4-4df3-ba91-84724566420f.png)

The `_instanceof` is lost import.

### Reproduce Steps

see https://github.com/web-infra-dev/rspack/pull/2657/files#diff-7778d5149babbc138f4afc0e9aaf627ebed05f11856a32c6fd4c118890fa893c

**Comment by IWANABETHATGUY** [comment]
Noticed that this issue appear after we bump swc.

**Comment by IWANABETHATGUY** [comment]
https://github.com/web-infra-dev/rspack/pull/2657 The issue is worked around for now, caused by the swc latest `@swc/helpers` breaking change, It works fine when you install `@swc/helpers`.  I will recover that test case next week.
