### ISSUE TITLE
Rspack has different behaviors with Webpack for importing `moment`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2702]
The behavior is inconsistent with webpack, where the type under webpack is a function while rspack is an object.

![image](https://user-images.githubusercontent.com/49502170/231080014-efca365e-afa5-4998-bf4f-993425ba511d.png)

**Comment by underfin** [comment]
Look like it is a special case, we can't resolve at now, need custom runtime

**Comment by underfin** [comment]
It is a namespace interop issue. 

``` ts
import *  as moment from './moment'

moment()
```

**Comment by hardfist** [comment]
@underfin  please  confirm whether this is solved

**Comment by underfin** [comment]
It already fixed at 0.2.5.
