### ISSUE TITLE
[Bug Report]: import commonjs module from esmodule throw `Failed to resolve` error in 0.1.7 version.

### ISSUE THREAD

**Issue by Godsenal** [web-infra-dev/rspack#2705]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 173.41 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.3
  npmPackages:
    @rspack/cli: 0.1.7 => 0.1.7 

### Details

Hello.
I'd like to report an issue that has occurred since version 0.1.7.

When a module in the esmodule format imports a commonjs format module, a Failed to resolve A in B error occurs.

The module with the issue was [axios-retry](https://www.npmjs.com/package/axios-retry), which imports a cjs format module called [is-retry-allowed](https://www.npmjs.com/package/is-retry-allowed).

I'm not sure if this is a major issue, but since it didn't occur in version 0.1.6, I wanted to report it.

### Reproduce link

https://github.com/Godsenal/rspack-relay-repor

### Reproduce Steps

1. run `yarn dev`

(Please ignore the repository name. I used it #2440 )

**Comment by ahabhgk** [comment]
It's not a bug, [Webpack does the same](https://webpack.js.org/configuration/module/#resolvefullyspecified), you can disable this behavior by:

```js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.m?js$/,
        resolve: {
          fullySpecified: false, // disable the behaviour
        },
      },
    ],
  },
};
```

**Comment by Godsenal** [comment]
@ahabhgk
Aha! It seems that the feature that was previously in webpack has been added in version 0.1.7 Thank you.

I'll close the issue!
