### ISSUE TITLE
[Feature Request]: Provide builtin.html hooks

### ISSUE THREAD

**Issue by my-lalex** [web-infra-dev/rspack#2711]
### What problem does this feature solve?

When you want to control HTML plugin output, you have to use the undocumented `HtmlRspackPlugin` instead of builtin.html options... would be nice to be able to handle HTML output hooks

### What does the proposed API of configuration look like?

I'm not sure where we could put this...

Ideally,  HtmlRspackPlugin static method `getHook` give access to the instance used by builtin: this would allow to use the HtmlRsPackPlugin instance or builtins.html? This would allow the plugin's plugins to be easily portable...

A dedicated hook in compilation?

**Comment by my-lalex** [comment]
No special issue here, but the HtmlRspackPlugin has no documentation or any mention in the doc, so it seemed to me that the "official" way is `builtin.html`
> Rspack has built-in support for HTML. This means you can use builtins.html instead of html-webpack-plugin:

**Comment by hardfist** [comment]
we will add documentation for htmrspackplugin
