### ISSUE TITLE
[Bug Report]: get arguments in arrow function incorrect when set builtins.presetEnv

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#2733]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 115.89 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: latest => 0.1.7 

### Details

When I don't set `builtins.presetEnv`, everything works fine. But when I set `builtins.presetEnv`, the `arguments` in the arrow function is incorrect.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/22373761/231407618-780390a1-d349-4b37-b5e4-4685742f3b22.png">

code: 
```js
export const a = function () {
    console.log(this, arguments);  //  { b: 1 }, [1, 2, 3]

    //  Expected: { b: 1 }, [1, 2, 3]
    //  Received: { b: 1 }, []
    const b = () => console.log('aaa', this, arguments);   
    b();
};

a.apply({ b: 1 }, [1,2,3]); 
```

rspack.config.js: 
```
  builtins: {
    presetEnv: {
      targets: ["> 0.01%", "not dead", "not op_mini all"],
    },
  },
```

output: 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/22373761/231402018-76085f7e-208b-4385-b4ba-31476e1583d9.png">

### Reproduce link

https://github.com/9aoy/rspack-issue-reproduce/tree/main/test-arguments

### Reproduce Steps

1. npm install
2. npm run dev

**Comment by underfin** [comment]
Here is transformed code.

``` .js
var a = function a() {
    var _this = this;
    console.log(this, arguments);
    var b = function() {
        return console.log('aaa', _this, arguments);
    };
    b();
};
```

**Comment by 9aoy** [comment]
The expected behavior is: 
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/22373761/232759855-d946e267-b9a5-4d58-af0f-3f7f9ea1aa98.png">
