### ISSUE TITLE
Interoperable CSS (ICSS) modules are not supported

### ISSUE THREAD

**Issue by dmathisen** [web-infra-dev/rspack#2738]
### System Info

  System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 78.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 16.1
  npmPackages:
    @rspack/cli: ^0.1.5 => 0.1.5

### Details

[ICSS](https://github.com/css-modules/icss) modules, which allows us to use `:export {...}` in our CSS, does not seem to be supported.

If I create `styles.module.css` with a simple class, importing it via `import myStyles from './styles.module.css` works fine.
`styles.module.css` example: 
```
.my-class {
  background-color: #000;
}
```
The output of `myStyles` is `{ my-class: 'src-styles-module-css__my-class }'`, as expected.

However, if I use `:export {...}` (icss) in my CSS file, the import produces an empty object.
`styles.module.css` example: 
```
:export {
  black: #000;
}
```
`import myStyles from './styles.module.css`
`myStyles` comes out being an empty object `{}`

Using **webpack** and **css-loader**, the solution was to set the `mode` to `icss`. Details available [here](https://github.com/webpack-contrib/css-loader#mode).

```
{
  loader: 'css-loader',
  options: {
    modules: {
      mode: 'icss'
    }
  }
}
```

I don't see any way to set the CSS module mode to support "icss".

### Reproduce Steps

1. Start a new rspack project
2. Add a `styles.module.css` file
3. Add an `:export {...}` directive to the css file
4. Import the css file
5. The import produces an empty object

**Comment by ahabhgk** [comment]
This can be achieved by adding support for style-loader and css-loader compatibility, which we have already started doing it.

**Comment by dmathisen** [comment]
Thank you, @ahabhgk 
Do you know when style-loader and css-loader are going to be supported? Is there a issue/pipeline I can watch for updates?

**Comment by hardfist** [comment]
style-loader and css-loader is supported now, please try it in 0.1.12 version

**Comment by dmathisen** [comment]
@hardfist @ahabhgk @hyf0
I've confirmed that this works with `css-loader`. I'm all good here and as far as I'm concerned, the issue can be closed. Thank you!

**Comment by hardfist** [comment]
lets leave it open until we support it in native css

**Comment by hardfist** [comment]
we will wait until webpack experiments.css support it, so close now
