### ISSUE TITLE
Add webpack's extractLicenses option to rspack's project configuration

### ISSUE THREAD

**Issue by dgmachado** [web-infra-dev/rspack#2739]
### What problem does this feature solve?

The extractLicenses option can be configured in project.json file and consumed by the Webpack.  It's desirable that this option is supported by Rspack.

**extractLicenses**
Extract all licenses in a separate file, in the case of production builds only.

### What does the proposed API of configuration look like?

```json
         "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/demo-api/src/environments/environment.ts",
              "with": "apps/demo-api/src/environments/environment.prod.ts"
            }
          ]
          "mode": "production",
          "sourceMap": false,
         }
```

**Comment by zackarychapple** [comment]
While this is part of the Nx config, it is still beneficial to have in Rspack as it is something performed by webpack IIRC.

**Comment by hardfist** [comment]
we may need to add `extractComments` functionality like [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin#extractcomments) to support this feature

**Comment by IWANABETHATGUY** [comment]
basically addressed  by https://github.com/web-infra-dev/rspack/pull/2882, you could try next nightly release, 
```js
module.exports = {
  builtins: {
    extractComments: true | false | /@licence|@something else /
  }
}
```

**Comment by IWANABETHATGUY** [comment]
@dgmachado , we have landed this feature via `builtins.minfyOptions.extractComments`, for more details you could refer https://github.com/web-infra-dev/rspack/releases. I am gonna close this issue, feel free to reopen it if you have any further questions.
