### ISSUE TITLE
Add webpack's fileReplacements option to rspack's project configuration

### ISSUE THREAD

**Issue by dgmachado** [web-infra-dev/rspack#2740]
### What problem does this feature solve?

The fileReplacements option can be configured in project.json file and consumed by the Webpack.  It's desirable that this option is supported by Rspack.

**fileReplacements**
Replace files with other files in the build.

### What does the proposed API of configuration look like?

```json
         "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/demo-api/src/environments/environment.ts",
              "with": "apps/demo-api/src/environments/environment.prod.ts"
            }
          ]
          "mode": "production",
          "sourceMap": false,
         }
```

**Comment by hardfist** [comment]
this seems not a webpack option?

**Comment by zackarychapple** [comment]
@dgmachado I believe this issue should be filed under [the Nx rspack repo](https://github.com/nrwl/nx-labs), as it is part of the Nx config.

**Comment by hardfist** [comment]
since it's not related to rspack, I'm gonna close it and feel free to file another one if you find it's related to rspack.
