### ISSUE TITLE
ExportsInfo support

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2752]
### What problem does this feature solve?

Some features need this.
- The module output used `exportsInfo.orderedExports` （p2）
- The `__webpack_exports_info__ ` API

### What does the proposed API of configuration look like?

Port https://github.com/webpack/webpack/blob/main/lib/ExportsInfo.js

**Comment by faga295** [comment]
@IWANABETHATGUY Have you started, if not and if you have other tasks to solve, can you assign this issue to me, because I have already done part of it.

**Comment by IWANABETHATGUY** [comment]
I am almost finished with it, you should probably choose another task to address.

**Comment by IWANABETHATGUY** [comment]
One more suggestion, you could ask for an assignment before you start. This may reduce conflict like the current scenario.

**Comment by faga295** [comment]
Thanks for your suggestion, I found that this question was not assigned, so I started without asking for an assignment. Hope to learn from your code.
