### ISSUE TITLE
support extractComments in minifyOptions 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2772]
### What problem does this feature solve?

fixes https://github.com/web-infra-dev/rspack/issues/2739 

### What does the proposed API of configuration look like?

https://github.com/webpack-contrib/terser-webpack-plugin#extractcomments
```
{
  builtins: {
    minify: { 
      extractComments: true | false | Regex // we can support license first
   }
 }
}
```

**Comment by lippzhang** [comment]
api是不是将 minifyOptions 错写成了minify？应该是下面这样子吧？
```js
{
  builtins: {
    minifyOptions: { 
      extractComments: true | false | Regex // we can support license first
   }
 }
}
```

**Comment by faga295** [comment]
Can you assign this to me?

**Comment by hardfist** [comment]
thanks in advance

**Comment by faga295** [comment]
What's the default value, if the `extractComments` is `undefined`?
