### ISSUE TITLE
Production build results in mangling of class `extends`

### ISSUE THREAD

**Issue by jasperlin451** [web-infra-dev/rspack#2774]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.97 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.4

### Details

Input code:
```typescript
import { WrappedIotsType } from '../WrappedIotsType';

export class StringEncodedObject extends WrappedIotsType {
  constructor(
  ) {
   ...
  }
}
```

Production build result:
```javascript
__webpack_require__(\"902067\");\nclass StringEncodedObject extends WrappedIotsType { ...
```

I know the required module number is correct (in other parts of the bundle I see code like `new _902067.WrappedIotsType`). It seems like in this specific case, there is no variable assignment of the require. Ie I would expect

```javascript
var _902067 = __webpack_require__(\"902067\");\nclass StringEncodedObject extends _902067.WrappedIotsType { ...
```

This seems to work fine in `development` mode.
```javascript
var _wrappedIotsTypeTs = __webpack_require__(\"../common_types/src/defs/WrappedIotsType.ts\"); class StringEncodedObject extends _wrappedIotsTypeTs.WrappedIotsType {
```

### Reproduce Steps

Extend a class in production mode.

**Comment by hyf0** [comment]
Would you like to provide a reproduction using https://github.com/web-infra-dev/rspack-repro?

**Comment by jasperlin451** [comment]
I was able to fix the issue by setting `sideEffects: false` in the package.json.

**Comment by IWANABETHATGUY** [comment]
Would you mind providing more info about this bug, although you have worked around it, but if you give us more info about this issue like providing a reproduce repo link, we could fix it.
