### ISSUE TITLE
Compatibility of umd/amd output.

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#2787]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 15.74 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: latest => 0.1.7 

### Details

Some packages output files like this:
https://github.com/aui/art-template/blob/3.1.0/dist/template-debug.js#L728   

Another example is lodash (but i don't find souce code):
<img width="753" alt="image" src="https://user-images.githubusercontent.com/16858738/232481010-d78b036b-a7e1-4289-980a-22a1a8319dc4.png">

To reproduce this issue, I have written a simple demo.

```js

...
const mmm = {a: 'a'};

if (typeof define === "function") {
  define(function () {
    return mmm;
  });
} else if (typeof exports !== "undefined") {
  module.exports = mmm;
} else {
  this.mmm = mmm;
}
```

You can see the difference of outputs between rspack and webpack .

rspack: 

<img width="624" alt="image" src="https://user-images.githubusercontent.com/16858738/232478703-00592e24-5f61-46f2-b735-9806fcc2bda5.png">

webpack: 

<img width="907" alt="image" src="https://user-images.githubusercontent.com/16858738/232478784-a9b2bdd0-e4d8-48fb-9e0d-6cd8c0d2f85c.png">

These differences will lead to some errors  .

Tks!

### Reproduce link

https://github.com/KyrieLii/rspack-webpack-demo/tree/amd-0.1.7

### Reproduce Steps

Pls see README.

**Comment by underfin** [comment]
Look like need scan amd module syntax, it is a hard work at now.

**Comment by daief** [comment]
Resolved <https://rspack.rs/config/other-options#amd>.

<details> 

### System Info

```bash
npx envinfo --system --npmPackages '@rspack/*' --binaries --browsers

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 8.33 GB / 31.87 GB
  Binaries:
    Node: 20.19.1 - ~\AppData\Local\mise\installs\node\20.19.1\node.EXE
    Yarn: 1.22.22 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.8.2 - ~\AppData\Local\mise\installs\node\20.19.1\npm.CMD
    bun: 1.3.3 - ~\AppData\Local\mise\installs\bun\1.3.3\bin\bun.EXE
  Browsers:
    Edge: Chromium (140.0.3485.54)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rspack/cli: ^1.7.0 => 1.7.2
    @rspack/core: ^1.7.0 => 1.7.2
```

### Details

Although rspack currently supports modules in amd/umd format, the compilation result retains `typeof define == 'function'`, which is inconsistent with webpack.

I have a host application that integrates rollup on the browser side, causing the `define` variable to be mounted in the global environment. When subcomponents run within this host environment, their internally referenced amd module dependencies are incorrectly taken over by the global `define`, preventing access to content inside the module.

### Reproduce link

<https://github.com/daief/rspack-issues/blob/master/issues/amd-format/>

- [amd-format/test-amd-pkg](https://github.com/daief/rspack-issues/tree/master/issues/amd-format/test-amd-pkg): mock a amd module
- [amd-format/config.js](https://github.com/daief/rspack-issues/tree/master/issues/amd-format/config.js): rspack/webpack config

### Reproduce Steps

- clone `https://github.com/daief/rspack-issues`
- run `yarn`
- run `cd issues/amd-format`
- run `yarn build`, then see `dist-rspack/test-amd-pkg.js` and `dist-webpack/test-amd-pkg.js`

difference:

- rspack: https://github.com/daief/rspack-issues/blob/master/issues/amd-format/dist-rspack/test-amd-pkg.js#L33
- webpack: https://github.com/daief/rspack-issues/blob/master/issues/amd-format/dist-webpack/test-amd-pkg.js#L36

Webpack result(ok):

<img width="361" height="104" alt="Image" src="https://github.com/user-attachments/assets/da3f145a-3c5e-4607-8d68-8113d1d1b9bb" />

Rspack result(wrong):

<img width="384" height="106" alt="Image" src="https://github.com/user-attachments/assets/6a6b0106-9930-4897-b825-4dab1313cb67" />

### Excepted

Consistent output with webpack, eliminating runtime code related to `define`.
</details>
