### ISSUE TITLE
[Bug] 1.0.7 resolution issues?

### ISSUE THREAD

**Issue by th3fallen** [web-infra-dev/rspack#2790]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 351.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - /opt/homebrew/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Firefox Developer Edition: 110.0
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.1.7 => 0.1.7
    @rspack/core: ^0.1.7 => 0.1.7
    @rspack/dev-server: ^0.1.7 => 0.1.7

### Details

After the 1.0.7 release updating ONLY rspack packages i now get resolution issues with @babel/runtime packages from other npm packages.

Sorry i dont have more details but im pretty flabbergasted 

### Reproduce link

https://github.com/th3fallen/rspack-bug-sass-include-paths

### Reproduce Steps

1. `yarn install`
2. `yarn start`

**Comment by ahabhgk** [comment]
Can you provide a **minimal** reproduction? With this link above I can't `yarn` at first, it contains some internal net packages, after I remove those packages and `yarn` successfully, `yarn start` works fine.

**Comment by th3fallen** [comment]
absolutely, i'll get right on that
