### ISSUE TITLE
Rspack cannot resolve alias with query

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2800]
### System Info

.

### Details

Webpack builds successfully.

Rspack builds failed.

### Reproduce link

https://github.com/hyf0/issue-rspack-webpack-resolve-alias-20230418

config: https://github.com/hyf0/issue-rspack-webpack-resolve-alias-20230418/blob/main/config.mjs

### Reproduce Steps

See repro.

**Comment by Boshen** [comment]
@bvanjoi For the target `path.resolve(__dirname, "./node_modules/moment/moment.js?raw")` ending with `?raw`, 

What should be done with the `?raw` part in alias plugin? https://github.com/web-infra-dev/nodejs_resolver/blob/main/src/plugin/alias.rs#L37-L41

```
                            let normalized_target = inner_target.replacen(from, to, 1);
                            dbg!(&normalized_target); // /path/to/file?raw
                            let alias_info = info
                                .clone()
                                .with_request(info.request().clone())
                                .with_target(&normalized_target);
```
