### ISSUE TITLE
跟随官网「手动安装指南」创建demo，实际输出与示例不一致。

### ISSUE THREAD

**Issue by JustForLucky** [web-infra-dev/rspack#2801]
### System Info

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 96.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Safari: 16.3
  npmPackages:
    @rspack/cli: ^0.1.7 => 0.1.7

### Details

真实输出
![rspack build output](https://user-images.githubusercontent.com/12389643/232691790-8db9ed29-c1c2-4623-9a47-99c60ce74782.png)
示例输出
![期待output](https://user-images.githubusercontent.com/12389643/232693836-d11e5f04-3514-4bad-a177-e7e9f156ed9c.png)

### Reproduce Steps

完全按照官网示例执行命令

**Comment by hyf0** [comment]
感谢报告，与文档行为不一致对我们来说是严重 Bug， 我们会马上安排人着手修复。
