### ISSUE TITLE
Support inline css assets

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#2802]
### What problem does this feature solve?

In local test some library, i need only import js assets

### What does the proposed API of configuration look like?

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.sass$/,
        use: [
          {
            loader: 'sass-loader',
            options: {
              // ...
            },
          },
        ],
        type: 'css',
       // new option
        inline: true
      },
    ],
  },
};
```

**Comment by ahabhgk** [comment]
This can be achieved by adding support for style-loader and css-loader compatibility, which we have already started doing it.

**Comment by h-a-n-a** [comment]
You can refer to [exportType](https://github.com/webpack-contrib/css-loader#exporttype) of css-loader to see if it suits your use case. Feel free to reopen the issue if you have any further issues.
