### ISSUE TITLE
Improve analyzing of magical comment `import(/* webpackChunkName: "d" */ "./d")`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2806]
### What problem does this feature solve?

Expected improvements:

- sub folders (cannot got up as only one dot is allowed at start).
- ensure that last character is not a slash
- ensure that opening and closing quotes are the same
- allow `-` and `_` in folder/file name

Thanks to @lalexdotcom, who proposes these improvements.

# Guidance

You should improve the regexp in

https://github.com/web-infra-dev/rspack/blob/99bec3fec54dbea969c157a8236938235ad1b8c2/crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs#L101-L103

https://jex.im/regulex should be very helpful for writing the regexp.

Read https://github.com/web-infra-dev/rspack/issues/2688 for more details.

### What does the proposed API of configuration look like?

.

**Comment by suxin2017** [comment]
Can you assign this to me?

**Comment by hyf0** [comment]
> Can you assign this to me?

Thank you in advance.
