### ISSUE TITLE
Use postcss-loader crash message Napi Error: GenericFailure - TypeError: css.walkRules is not a function

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#2815]
### System Info

System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 649.57 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: ^0.1.8 => 0.1.8 
    @rspack/core: ^0.1.8 => 0.1.8 
    @rspack/dev-server: ^0.1.8 => 0.1.8

### Details

Fail `css.walkRules is not a function`
```
formatted: 'Napi Error: GenericFailure - TypeError: css.walkRules is not a function\n' +
        '    at /project/home/shaodahong/workspace/node_modules/.pnpm/postcss-px-to-viewport@1.1.1/node_modules/postcss-px-to-viewport/index.js:34:9\n' +
        '    at LazyResult.runOnRoot (/project/home/shaodahong/workspace/node_modules/.pnpm/postcss@8.4.22/node_modules/postcss/lib/lazy-result.js:339:16)\n' +
        '    at LazyResult.runAsync (/project/home/shaodahong/workspace/node_modules/.pnpm/postcss@8.4.22/node_modules/postcss/lib/lazy-result.js:393:26)\n' +
        '    at LazyResult.async (/project/home/shaodahong/workspace/node_modules/.pnpm/postcss@8.4.22/node_modules/postcss/lib/lazy-result.js:221:30)\n' +
        '    at LazyResult.then (/project/home/shaodahong/workspace/node_modules/.pnpm/postcss@8.4.22/node_modules/postcss/lib/lazy-result.js:206:17)\n' +
        '   0: <unknown>\n' +
        '   1: <unknown>\n' +
        '   2: _ZN6v8impl12_GLOBAL__N_118ThreadSafeFunction7AsyncCbEP10uv_async_s\n' +
        '   3: uv__async_io\n' +
        '             at /home/iojs/build/ws/out/../deps/uv/src/unix/async.c:163:5\n' +
        '   4: uv__io_poll\n' +
        '             at /home/iojs/build/ws/out/../deps/uv/src/unix/epoll.c:374:11\n' +
        '   5: uv_run\n' +
        '             at /home/iojs/build/ws/out/../deps/uv/src/unix/core.c:389:5\n' +
        '   6: _ZN4node13SpinEventLoopEPNS_11EnvironmentE\n' +
        '   7: _ZN4node16NodeMainInstance3RunEv\n' +
        '   8: _ZN4node5StartEiPPc\n' +
        '   9: __libc_start_main\n' +
        '  10: <unknown>\n' +
        '\n',
```

### Reproduce link

https://codesandbox.io/p/sandbox/competent-lumiere-zkswpl?file=%2Fbuild.js&selection=%5B%7B%22endColumn%22%3A28%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A14%2C%22startLineNumber%22%3A9%7D%5D

### Reproduce Steps

1. pnpm i
2. node build.js

**Comment by ahabhgk** [comment]
postcss-px-to-viewport is using postcss@5, and lack of maintenance for a long time, postcss-loader needs postcss's version "^7.0.0 || ^8.0.1", IMO you should use [a fork version of postcss-px-to-viewport](https://www.npmjs.com/package/postcss-px-to-viewport-8-plugin) which upgrade postcss to the latest
