### ISSUE TITLE
Refactor: remove `impl Module for Box<dyn Module>` in codebase

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2820]
## Details

See context at https://github.com/web-infra-dev/rspack/discussions/2762

## Guidance

1. Remove following code

https://github.com/web-infra-dev/rspack/blob/2c4c1daf81d388cd4fc0b54049d9e2a762e34418/crates/rspack_core/src/module.rs#L149-L193

2. Fix all errors

PS:

Take this code as an example

https://github.com/web-infra-dev/rspack/blob/2c4c1daf81d388cd4fc0b54049d9e2a762e34418/crates/rspack_core/src/module_graph/mod.rs#L162-L165

There's no need for returning `Box<&dyn Module>` due to no use cases(so far) caring about the `Box` in `Box<&dyn Module>`. Returning `Option<&dyn Module>` would be enough.

The argument also applies to using `&BoxModule` in function parameters. So, we just need to replace all `&BoxModule` with `&dyn Module`, which would also achieve the goal: reduce boilerplate code for deref `Box` and avoid the traps mentioned above.

### What does the proposed API of configuration look like?

.

**Comment by sladyn98** [comment]
Opened a PR for this https://github.com/web-infra-dev/rspack/pull/2831
