### ISSUE TITLE
CI unexpected segmentfault

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2828]
### System Info

see the log file

### Details

https://gist.github.com/IWANABETHATGUY/742c5a7db4ad26f5fd91a748790e151b

### Reproduce link

https://gist.github.com/IWANABETHATGUY/742c5a7db4ad26f5fd91a748790e151b

### Reproduce Steps

hard to reproduce

**Comment by Boshen** [comment]
Seems fixed.
