### ISSUE TITLE
Product inconsistency when webpackChunkName: "user/[id]/page" 

### ISSUE THREAD

**Issue by GiveMe-A-Name** [web-infra-dev/rspack#2829]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 258.70 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/node
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Safari: 16.3

### Details

if I use webpackChunkName like this:
```js
import(/* webpackChunkName: "user/[id]/page" */ "./Hello1").then((module) => {
  module.default();
});
import(/* webpackChunkName: "redirect/page" */ "./Hello2").then((module) => {
  module.default();
});
```
we can watch the product is different between `webpack` and `rspack`.
### webpack 
![image](https://user-images.githubusercontent.com/58852732/233038156-19d91807-ec58-4952-ad7f-1b6be41c1561.png)

### rspack 
![image](https://user-images.githubusercontent.com/58852732/233043378-b8149c17-2042-4406-87fa-2d59cf7b986d.png)

### Reproduce link

https://github.com/GiveMe-A-Name/rspack-chunkname-demo/tree/feat/test1

### Reproduce Steps

1. pnpm install 
2. pnpm run build 
3. pnpm run build:webpack

**Comment by faga295** [comment]
Can you assign this issue to me?I'm interested about it. @hyf0

**Comment by hyf0** [comment]
> Can you assign this issue to me?I'm interested about it. @hyf0 

Thank you in advance.

**Comment by GiveMe-A-Name** [comment]
sorry, I not found it was already assigned.
It block my work in modern.js, so I am fixing it just now.

**Comment by hyf0** [comment]
> Sorry, I not found it was already assigned.
> 
> It block my work in modern.js, so I am fixing it just now.

@faga295 Sorry for that. I didn't expect this problem to become so hot😅. Thank you anyway.
