### ISSUE TITLE
Browserslist erroring when using "extends" syntax

### ISSUE THREAD

**Issue by shawnmcknight** [web-infra-dev/rspack#2832]
### System Info

System:                                                        
  OS: Windows 10 10.0.19045                                    
  CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz 
  Memory: 16.54 GB / 31.73 GB                                  
Binaries:                                                      
  Node: 18.15.0 - C:\Program Files\nodejs\node.EXE             
  npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD                 
Browsers:                                                      
  Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)    
  Internet Explorer: 11.0.19041.1566                           

### Details

Browserslist allows [shareable configs](https://github.com/browserslist/browserslist#shareable-configs) via an `extends` keyword in the context's browserlist configuration.  For instance, if there is a `.browserslistrc` file in the context folder which contains `extends @scope/browserslist-config`, then that configuration will be resolved and used as the configuration.

However, when using `builtins.presetEnv` and allowing it to find the browserslist configuration, I am receiving the following error:
```
[rspack-cli] [Error: error[internal]: failed to parse targets: failed to convert target query to version data

Caused by:
    0: failed to execute query
    1: failed to resolve browserslist query: ["extends @storis/browserslist-config"]
    2: failed to parse the rest of input: ...''.
Raw: panicked at 'failed to parse targets: failed to convert target query to version data

Caused by:
    0: failed to execute query
    1: failed to resolve browserslist query: ["extends @storis/browserslist-config"]
    2: failed to parse the rest of input: ...''', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_preset_env-0.193.4\src\lib.rs:49:60
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
```

An existing example configuration could be [github's configuration](https://www.npmjs.com/package/@github/browserslist-config).

### Reproduce link

https://github.com/shawnmcknight/rspack-repro-browserslist-extends

### Reproduce Steps

1. `npm install -D @github/browserslist-config`
2. Create a `.browserslistrc` file in the context folder containing `extends @github/browserslist-config`
3. In rspack configuration, set `builtIns.presetEnv = {}`
4. Run `rspack` to build

Error above will be presented.

**Comment by shawnmcknight** [comment]
Reproduction available at https://github.com/shawnmcknight/rspack-repro-browserslist-extends

**Comment by hyf0** [comment]
Well, it was kind of expected. The `browserlist-rs` SWC used doesn't support "extends" syntax.

You could see the limitation here: https://github.com/browserslist/browserslist-rs#limitations

Thanks for reporting. I think we need to improve the document to show the limitations😢.

**Comment by hyf0** [comment]
Closed for having https://github.com/web-infra-dev/rspack-website/issues/288.
