### ISSUE TITLE
support ContextReplacementPlugin

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#2841]
### What problem does this feature solve?

Provide a plugin or builtin field to support the features of ContextReplacementPlugin
https://webpack.js.org/plugins/context-replacement-plugin

**Comment by hyf0** [comment]
@underfin I remember we have supported something like
```js
import(`./locale/${name}.json`)
```
Does it have any relationships with `ContextReplacementPlugin`?

**Comment by hyf0** [comment]
Close for stale.
