### ISSUE TITLE
Better memory allocation in `member_expr_to_string::collect_member_expr`

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#2842]
This function seems pretty hot

<img width="2484" alt="image" src="https://user-images.githubusercontent.com/1430279/233313137-9cadf6b7-8e42-45c5-afed-4e4d479134ed.png">

https://github.com/web-infra-dev/rspack/blob/cb8cfeb670f2bd32b242c79d17cbcfa09d410b1e/crates/rspack_plugin_javascript/src/visitors/dependency/util.rs#L110-L135

<img width="2437" alt="image" src="https://user-images.githubusercontent.com/1430279/233314821-f383e209-49cc-4542-8240-45aa78b31b9e.png">

**Comment by hyf0** [comment]
I'm interested in this.
