### ISSUE TITLE
Bundle Optimizations are significantly slower than expected

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#2850]
### System Info

Rspack 1.7

### Details

 When testing NestJS support for Rspack with @mandarini and @dgmachado discovered that enabling bundle optimization had some odd behavior around build times with little to no bundle size improvements. 

This is the results for a NestJS application with 13 Controllers, 18 Services, 16 Modules, 125 TypeScript files, and 13960 lines of code. 

<table>
<tr>
<td align="center" colspan="2"><strong>Development</strong></td> 
<td align="center" colspan="3"><strong>Production</strong></td> 
</tr>
</th>
<tr>
<td>Webpack</td>
<td>Rspack</td>
<td>Webpack</td>
<td>Rspack + Optimizations off (Bundle 9.5mb)</td>
<td>Rspack + Optimizations on (Bundle 9.4mb)</td>
</tr>
<tr>
<td>50.52s</td>
<td>6.68s</td>
<td>44.74s</td>
<td>7.90s</td>
<td>33.71s</td>
</tr>
</table>

### Reproduce Steps

Run build with optimizations turned on vs off

**Comment by IWANABETHATGUY** [comment]
Would you mind providing the repo link, so we could better investigate?

**Comment by IWANABETHATGUY** [comment]
Also, would you mind providing the bundle time when webpack disables optimization?

**Comment by hyf0** [comment]
Close for stale. Please re-open it if you think the issue is not solved.

**Comment by zackarychapple** [comment]
@dgmachado can we go ahead and keep this closed? I tried to replicate and could not with either of the two below versions. 

## Rspack 0.1.11
Hyperfine benchmarks with 2 warmups
### Optimizations on
```bash
Benchmark 1: nx build nest-api --production
  Time (mean ± σ):      1.348 s ±  0.057 s    [User: 1.350 s, System: 1.049 s]
  Range (min … max):    1.273 s …  1.441 s    10 runs
```
### Optimizations off 
```bash
Benchmark 1: nx build nest-api --production
  Time (mean ± σ):      1.372 s ±  0.080 s    [User: 1.355 s, System: 0.970 s]
  Range (min … max):    1.292 s …  1.497 s    10 runs
```

## Rspack 0.2.4
Hyperfine benchmarks with 2 warmups
### Optimizations on
```bash
Benchmark 1: nx build nest-api --production
  Time (mean ± σ):      1.332 s ±  0.033 s    [User: 1.356 s, System: 1.007 s]
  Range (min … max):    1.280 s …  1.396 s    10 runs
```
### Optimizations off 
```bash
Benchmark 1: nx build nest-api --production
  Time (mean ± σ):      1.310 s ±  0.029 s    [User: 1.348 s, System: 1.035 s]
  Range (min … max):    1.279 s …  1.378 s    10 runs
```
