### ISSUE TITLE
@rspack/plugin-html has direct dependency on @rspack/core -- should it be peer?

### ISSUE THREAD

**Issue by shawnmcknight** [web-infra-dev/rspack#2852]
### System Info

System:                                                         
  OS: Windows 10 10.0.19045                                     
  CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz  
  Memory: 16.37 GB / 31.73 GB                                   
Binaries:                                                       
  Node: 18.15.0 - C:\Program Files\nodejs\node.EXE              
  npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD                  
Browsers:                                                       
  Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)     
  Internet Explorer: 11.0.19041.1566                            

### Details

Originally reported in #2795 but splitting into separate issue.

`@rspack/plugin-html` has a direct dependency on `@rspack/core`.  It seems like this would be preferable as a peer dependency since I would think you can have different versions of  `@rspack/plugin-html` and `@rspack/core` as dependencies.  With `@rspack/plugin-html` having a direct dependency, that can lead to multiple versions of `@rspack/core` being installed if the versions are not in sync with each other.

I ran into this problem when testing use of `@rspack/plugin-html@0.1.8` while I was using `@rspack/cli@nightly` (and transitively `@rspack/core@nightly`.  Because there were multiple versions of `@rspack/core` available, I was getting type errors as the plugin's type was incompatible with `@rspack/core`.  When I switched everything to `@nightly` the type errors went away because everything was in sync.  However, it seems like you should be able to move `@rspack/plugin-html`'s version independently of `@rspack/core`'s version.

### Reproduce Steps

N/A

**Comment by hyf0** [comment]
@hardfist cc

**Comment by hardfist** [comment]
@shawnmcknight  peerdep seems better，are you willing to fix it
