### ISSUE TITLE
module code generate doesn't include comments

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#2868]
### System Info

 System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 56.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.1
  npmPackages:
    @rspack/cli: 0.1.7 => 0.1.7

### Details

webpack:
![image](https://user-images.githubusercontent.com/87003751/233772696-e0928e62-d5e4-42cb-a926-cc3583b4e017.png)
rspack:
![image](https://user-images.githubusercontent.com/87003751/233772712-f99021c5-43de-4cfb-8966-99633cb8f13e.png)
when `optimization.minimize` is false, webpack retains all comments from the original files, but rspack removes them 

### Reproduce link

https://github.com/faga295/rspack-reproduce/tree/module_generate_include_comments

### Reproduce Steps

1. pnpm i
2. pnpm build:rspack
3. pnpm build:webpack
4. check the difference between webpack-dist and rspack-dist

**Comment by faga295** [comment]
Can I fix it by the way in #2882?

**Comment by IWANABETHATGUY** [comment]
We prefer one pr focus on one thing.
