### ISSUE TITLE
Uncaught ReferenceError: $RefreshSig$ is not defined

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2873]
### System Info

.

### Details

Cause: https://github.com/hyf0/rspack-issue-react-refresh-20230423/blob/db6facbe1d541b4146f9784d2e880d3be8b9a6f2/rspack.config.mjs#L29-L32

![image](https://user-images.githubusercontent.com/49502170/233820061-095a352d-aa4a-44c0-b6cf-400fa9ab6f16.png)

### Reproduce link

https://github.com/hyf0/rspack-issue-react-refresh-20230423

### Reproduce Steps

`pnpm dev`

**Comment by th3fallen** [comment]
@hyf0 im actually still seeing this on 0.1.9

**Comment by hyf0** [comment]
> @hyf0 im actually still seeing this on 0.1.9

It should be different causes, even though the error is the same :).

Could you create a new issue with the code that throws this error? The error you met could be just fixed at https://github.com/web-infra-dev/rspack/pull/2939.

Maybe you could try the nightly version of tomorrow.
