### ISSUE TITLE
[Tracking]: add more bundlers to benchmark page

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2881]
### What subject does this issue tracking?

# Background
we only benchmark against webpack before but more and more users want to benchmark rspack with rollup | esbuild | vite, and even we don't want to start a benchmark game with other bundlers, but it did help users make choice about which bundler to choose. and there are already lots benchmark against rspack right now, some of them may not be familiar with rspack and use the wrong way to benchmark against rspack which made a bad reputation about rspack.
there are lots of things to consider to do a fair benchmark(You can't do benchmark right the first time).

## bundler choices
* webpack
* vite
* turbopack
* rspack
* parcel
* rollup 
* esbuild
## benchmark criteria
* cold start time
* hot start time
* cold build time
* hot build time
* rebuild time
* HMR time
* build size 
* FCP time of build assets
## benchmark machine
we should always benchmark in ci machine because local machin is very subjective and can't be reviewed, but bundler may have different performance on different machine(for example, since rspack|turbopack heavily relys on multi thread, it performance well on machines which have more threads)
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by chenjiahan** [comment]
Is it possible for different bundler teams to maintain a shared benchmark?

**Comment by hardfist** [comment]
> Is it possible for different bundler teams to maintain a shared benchmark?

yes, a neutral benchmark is more fair than benchmark owned by some bundler teams.

**Comment by hyf0** [comment]
https://github.com/web-infra-dev/performance-compare
