### ISSUE TITLE
`require.context` not update when file change

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#2901]
### System Info

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.55 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.1

### Details

In webpack `require.context` will update if file changes, for example, require.context() gets 3 modules in the first time: a, b, c, then if I delete c in filesystem, it's fine and it updates, but rspack will panic.

### Reproduce link

https://codesandbox.io/p/sandbox/cool-panka-k90mx1

### Reproduce Steps

run `npm run start:rspack`
then delete mod1 or mod2, then you can see the error message in the terminal.

redo delete

run `npm run start:webpack`
then delete mod1 or mod2, it's fine for webpack

**Comment by nieyuyao** [comment]
I had the same issue. The relevant code seems to be here.

https://github.com/web-infra-dev/rspack/blob/f78eb67de4ebe071fd934cc9e13432f86a83a1e4/crates/rspack_core/src/compiler/hmr.rs#L214-L220

Whether the removed files should not be forced to build ?
