### ISSUE TITLE
feat: add debugging

### ISSUE THREAD

**Issue by Phinome** [web-infra-dev/rspack#2905]
### What problem does this feature solve?

When contributing to the core repo, writing a loader/plugin, or even working on a complex project, debugging tools can be central to your workflow.

### What does the proposed API of configuration look like?

node --inspect node_modules/.bin/rspack build

**Comment by hyf0** [comment]
Would this be helpful to you? https://web-infra-dev.github.io/rspack-dev-guide/debugging/intro.html

**Comment by Phinome** [comment]
@hyf0 i try by following this docs, but got warning: `npm/darwin-arm64                         |  WARN  Unsupported platform: wanted: {"cpu":["arm64"],"os":["darwin"],"libc":["any"]} (current: {"os":"darwin","cpu":"x64","libc":"unknown"})`
.
i got error: `rspack/crates/node_binding/node_modules/@rspack/binding-darwin-x64/rspack.darwin-x64.node` when running `debug-rspack`.
so, what libs that i need to install ?
thanks

**Comment by dgmachado** [comment]
@Phinome I'm getting the same issue. Could you move forward?

**Comment by dgmachado** [comment]
@Phinome I was having the same issue and it was missing protobuf. 

```
brew install protobuf
```

**Comment by wood3n** [comment]
I still have this problem after `install protobuf` 😢 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/31716713/236421381-3c72d362-c058-435b-80c7-1536bd87b455.png">

**Comment by Boshen** [comment]
`protobuf` is no longer required.

I followed the instructions at https://web-infra-dev.github.io/rspack-dev-guide/debugging/intro.html and managed to run the debugger.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1430279/236777208-9d7d4d32-76b6-439d-90e2-c5030ea9cb55.png">

May I get a double confirmation that this actually works?

**Comment by Boshen** [comment]
I'll close this as fixed, feel free to reopen if this is not the case.
