### ISSUE TITLE
Rspack incompatible with license-webpack-plugin

### ISSUE THREAD

**Issue by dgmachado** [web-infra-dev/rspack#2913]
### System Info

System:
OS: macOS 13.1
CPU: (10) arm64 Apple M1 Pro
Memory 32GB
Shell: /bin/zsh

Binaries: 
node: 16.13.2
npm: 9.5.0
yarn: 1.22.19

Browsers:
Chrome: 111.0.5563.146

npmPackages:
@nrwl/rspack: 15.9.5
@rspack/core: ~0.1.0
@rspack/dev-server: ~0.1.0
@rspack/plugin-minify: ~0.1.0

### Details

Rspack seems to be incompatible with the [license-webpack-plugin](https://www.npmjs.com/package/license-webpack-plugin) package.

It's happening a fatal error:
```
Error: napi error: GenericFailure - TypeError: compilation.compiler.isChild is not a function
...
:28)
   0: _napi_register_module_v1
   1: <unknown>
   2: <unknown>
```

### Reproduce Steps

1. Create an rspack project
2. Install the license-webpack-plugin package: npm i -D license-webpack-plugin
3. Add the plugin into the rspack.config.js file:

```
const LicenseWebpackPlugin = require('license-webpack-plugin').LicenseWebpackPlugin;

module.exports = {
  plugins: [
    new LicenseWebpackPlugin()
  ]
};
```

### What does the proposed API of configuration look like?

-

**Comment by dgmachado** [comment]
Ticket related to https://github.com/web-infra-dev/rspack/issues/2739

**Comment by hyf0** [comment]
Not sure they are the same, but https://github.com/web-infra-dev/rspack/pull/2882 is ongoing.

Could it meet your need?

**Comment by dgmachado** [comment]
@hyf0 we may need to add extractComments functionality like [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin#extractcomments) to support this feature but it isn't the same.

**Comment by dgmachado** [comment]
Furthermore, the support to this license-webpack-plugin may have relation with https://github.com/web-infra-dev/rspack/issues/2739.

**Comment by IWANABETHATGUY** [comment]
I think this issue may have a workaround now, for more details you could refer to https://github.com/web-infra-dev/rspack/issues/2739

**Comment by dgmachado** [comment]
@hyf0  
> Not sure they are the same, but #2882 is ongoing.
> 
> Could it meet your need?

It's a good workaround, however not sure if it meets our needs because comparing the license-webpack-plugin output and the extract comments the plugin output has much more licenses. 

It seems the **builtins.minfyOptions.extractComments** is extracting licenses from almost all first-level included dependencies (not all) but nothing for all second-level and the following. 

That's why I've created this [PR](https://github.com/web-infra-dev/rspack/pull/3010) adding support to this plugin. Testing this integration on Rspack the plugin output has much more licenses than the **builtins.minfyOptions.extractComments**.

**Comment by hyf0** [comment]
Thanks for the feedback. So appreciated that you create https://github.com/web-infra-dev/rspack/pull/3010 but the implementation of it has some issues. I already comment on it in the PR. 

If you could change the implementation, I will continue following up with the PR and merge it to the main.

**Comment by IWANABETHATGUY** [comment]
Your implementation looks to have some performance penalty. If I understand correctly, it at least has a time complexity of `O(mn^2)`, m is the length of chunk, n is the number of module of each chunk

**Comment by dgmachado** [comment]
Thank you @IWANABETHATGUY and @hyf0 for all your help.
