### ISSUE TITLE
CLI for development

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#2915]
### What problem does this feature solve?

Developing Rspack is harder than normal Node.js applications due to needing to have both Node.js and Rust installed and run.

It is tedious to look for commands related to both Node.js or Rust, it doesn't make sense to look for commands in either package.json scripts or cargo .cargo/config.toml or other documentation places.

In order to provide better developer experience, a development cli is needed to wrap all commands and provide useful help information.

We will unify all development workflow, GitHub workflows and documentation to this CLI. 

Previously we had `./x` script but it didn't work on windows. This time we will bring it back, but change the underlying mechanism to use `zx`.

The CLI will use the `commander` library to provide the interface.

### What does the proposed API of configuration look like?

After this is done, we should be able to run 

```bash
./x --help
```

and it will display something like 

```
subcommands:
* test
* build
```

subcommand `./x test --help` will display

```
* test rust
* test e2e
* test unit
* test example
```

**Comment by hardfist** [comment]
a bad DX of using ./x before is that we need to go back to project root to execute this command, it would be better it could be executed in any package directory.

**Comment by hyf0** [comment]
> a bad DX of using ./x before is that we need to go back to project root to execute this command, it would be better it could be executed in any package directory.

Could we achieve this by making `cli` a node package and linking to the root `package.json`.

After `pnpm install` the CLI is installed to `node_modules/.bin` and we could use `pnpm x`.

**Comment by Boshen** [comment]
> a bad DX of using ./x before is that we need to go back to project root to execute this command, it would be better it could be executed in any package directory.

It is also bad DX if you need to CD into directories for development.

**Comment by hardfist** [comment]
> > using ./x before is that we need to go back to project root to execute this command, it would be better it could be executed in any package directory.
that's inevitable，I may need to debug some example so I need to cd to example directory

**Comment by hardfist** [comment]
> After `pnpm install` the CLI is installed to `node_modules/.bin` and we could use `pnpm x`.

we could just add the cli bin path to $PATH just like other cli does

**Comment by Boshen** [comment]
> > > using ./x before is that we need to go back to project root to execute this command, it would be better it could be executed in any package directory.
> 
> that's inevitable，I may need to debug some example so I need to cd to example directory

The examples are isolated packages, better to call their own package.json scripts?

**Comment by Boshen** [comment]
The script is done. We can just add commands as we go.
