### ISSUE TITLE
Do not compile all of swc (try again)

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#2916]
### What problem does this feature solve?

Back in 
* https://github.com/web-infra-dev/rspack/pull/2552

I tried to untangle swc but failed due to pulling in `swc::config` 

### What does the proposed API of configuration look like?

This time I suggest to directly copy `swc::config` into Rspack so we can remove the problem of "swc pulling in everything".

See https://github.com/swc-project/swc/blob/main/crates/swc/src/config/mod.rs

---

## Current `cargo build --timings`

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1430279/234780483-6074eedd-15bf-4b27-97cb-7834989cb03e.png">
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/1430279/234780575-dcb14f69-7319-4ea9-87a3-f60f2938977f.png">

**Comment by Boshen** [comment]
https://github.com/swc-project/swc/blob/main/crates/swc/src/config/mod.rs

**Comment by Boshen** [comment]
After: 201s -> 172s (=29s), 15% improvement

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1430279/234809554-a48b7011-1bf4-4be4-b525-2b2ec4870ad0.png">
<img width="1807" alt="image" src="https://user-images.githubusercontent.com/1430279/234809646-16d48fa7-6573-4975-9bbb-389d5e96542b.png">

**Comment by Boshen** [comment]
@suxin2017 Can you take a look at this, 

https://github.com/web-infra-dev/rspack/blob/ed6411c6d693ab2e313404f01647fb378bbce0e5/crates/rspack_loader_swc/Cargo.toml#L22

Is is possible to remove the base import for avoiding compiling all of swc.

**Comment by Boshen** [comment]
We still have these two:

```
error[E0433]: failed to resolve: could not find `base` in `swc_core`
 --> crates/rspack_plugin_javascript/src/visitors/mod.rs:6:15
  |
6 | use swc_core::base::config::ModuleConfig;
  |               ^^^^ could not find `base` in `swc_core`

error[E0433]: failed to resolve: could not find `base` in `swc_core`
 --> crates/rspack_plugin_javascript/src/visitors/swc_visitor/build_module.rs:3:15
  |
3 | use swc_core::base::config::ModuleConfig;
  |               ^^^^ could not find `base` in `swc_core`
```

**Comment by suxin2017** [comment]
> @suxin2017你能看看这个吗
> 
> https://github.com/web-infra-dev/rspack/blob/ed6411c6d693ab2e313404f01647fb378bbce0e5/crates/rspack_loader_swc/Cargo.toml#L22
> 
> 可以删除基本导入以避免编译所有 swc。



> @suxin2017 Can you take a look at this,
> 
> https://github.com/web-infra-dev/rspack/blob/ed6411c6d693ab2e313404f01647fb378bbce0e5/crates/rspack_loader_swc/Cargo.toml#L22
> 
> Is is possible to remove the base import for avoiding compiling all of swc.

This can be tricky, because the swc documentation is so sketchy that it takes a little bit of looking at the code to separate out the logic
