### ISSUE TITLE
Cannot read properties of undefined (reading 'noEmitAssets') 

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#2929]
### System Info

codesandbox

### Details

```
/project/home/shaodahong/workspace/node_modules/.pnpm/@rspack+dev-server@0.1.9_2pphuzght2cmkis7ijav2ajsne/node_modules/@rspack/dev-server/dist/server.js:51
                if (compiler.options.builtins.noEmitAssets) {
                                              ^

TypeError: Cannot read properties of undefined (reading 'noEmitAssets')
```

maybe cause by https://github.com/web-infra-dev/rspack/pull/2907

### Reproduce link

https://codesandbox.io/p/sandbox/blissful-tess-ttden9?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A25%7D%5D

### Reproduce Steps

1. pnpm i
2. node build.js

**Comment by hyf0** [comment]
Closed by 2942.
