### ISSUE TITLE
support plugin api `ensureHook`

### ISSUE THREAD

**Issue by KyrieLii** [web-infra-dev/rspack#2931]
### What problem does this feature solve?

For example , [enhanced-resolve](https://www.npmjs.com/package/enhanced-resolve) provide plugin boilerplate: 

```js
class MyResolverPlugin {
	constructor(source, target) {
		this.source = source;
		this.target = target;
	}

	apply(resolver) {
		const target = resolver.ensureHook(this.target);
		resolver
			.getHook(this.source)
			.tapAsync("MyResolverPlugin", (request, resolveContext, callback) => {
				// Any logic you need to create a new `request` can go here
				resolver.doResolve(target, request, null, resolveContext, callback);
			});
	}
}
```
But it not work in rspack , because the error : `resolver.ensureHook is not a function`.

### What does the proposed API of configuration look like?

Support `ensureHook` like webpack. 🫡

**Comment by hyf0** [comment]
Close for stale. Please re-open it if you think the issue is not solved.
