### ISSUE TITLE
Can not extract all styles into a single chunk 

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#2936]
### System Info

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 176.75 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/13750_1682415852840/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/13750_1682415852840/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/13750_1682415852840/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.1.9 => 0.1.9

### Details

I'm trying to extract all styles into a single chunk, but the following splitsChunks config is not work as expected:

```ts
const config = {
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: "styles",
          test: /\.css$/,
          chunks: "all",
          priority: 99,
        },
      },
    },
  },
};
```

### Reproduce link

https://github.com/chenjiahan/rspack-css-split-chunk-issue

### Reproduce Steps

```bash
pnpm i
pnpm build
```

Then we can find two css files in the dist folder: `styles.css` and `src_foo_js.css`.

**Comment by hyf0** [comment]
workaround: use `newSplitChunks: true`. See https://github.com/web-infra-dev/rspack/pull/2996/files#diff-289abfac267fac9924115451312d09aab9a25a4fc382fb5122c20639e5c38486R15-R27 for details

**Comment by chenjiahan** [comment]
Bumped to Rspack v0.4.2 and still has this issue.

Repro updated: https://github.com/chenjiahan/rspack-css-split-chunk-issue

**Comment by bvanjoi** [comment]
@chenjiahan What output are you expecting? Webpack also emits two files:

![image](https://github.com/web-infra-dev/rspack/assets/30187863/258be4f4-331f-4582-b886-5c941e6a1867)

**Comment by chenjiahan** [comment]
@bvanjoi sorry I forgot to add `minSize: 1`, after adding it, the outputs are correct.

Maybe we should document the default minSize in https://www.rspack.dev/config/optimization-split-chunks.html#splitchunksminsize

![image](https://github.com/web-infra-dev/rspack/assets/7237365/fab913f5-b22e-4207-8c6e-b69ad60e2195)

https://webpack.js.org/plugins/split-chunks-plugin/#splitchunksminsize

**Comment by bvanjoi** [comment]
same as webpack
