### ISSUE TITLE
output.sourceMapFilename

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2938]
### What problem does this feature solve?

Manage the output path of source map files

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/output/#outputsourcemapfilename

**Comment by lippzhang** [comment]
can you assig to me?

**Comment by hardfist** [comment]
sure

**Comment by suxin2017** [comment]
> can you assig to me?

下手如此之快
![image](https://user-images.githubusercontent.com/28481035/234508400-5c6b6b40-4e55-408d-875e-81cb4547a5b2.png)

**Comment by IWANABETHATGUY** [comment]
Since the related pr has been merged, can we close this issue?

**Comment by ahabhgk** [comment]
Of course
