### ISSUE TITLE
CI: `check-changeset.yml` sometimes hang for no reasons

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#2969]
### System Info

.

### Details

After I cancel the CI, I got this

![c8ffc4f9-3f1b-4c5f-bfb7-b3ea155c7f3d](https://user-images.githubusercontent.com/49502170/235046067-b3e9941e-c61b-4ec9-aa73-e34ae82feac9.jpeg)

### Reproduce Steps

There are no stable reproduce steps.

**Comment by chenjiahan** [comment]
The CI stops at the `changeset version` command, perhaps some internal logic of changeset is broken, such as DependencyGraph.

![image](https://user-images.githubusercontent.com/7237365/236617361-b8984fad-f6cb-4ada-8f31-b4e50e1140bb.png)

**Comment by Boshen** [comment]
I vote for removing changeset:

It
* Duplicates GH releases
* creates noise from CI
* creates burden on the contributor

**Comment by hardfist** [comment]
related to https://github.com/changesets/changesets/issues/571

**Comment by hyf0** [comment]
Closed for we have disabled the `check-changeset.yml` action
