### ISSUE TITLE
`ignoreWarnings` for filter warnings

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2979]
### What problem does this feature solve?

Tells Rspack to ignore specific warnings.

Support regex type and function type can be easily implemented with some work on js side, supporting object type can be separated to another issue/PR, which will need more refactor work on rust side.

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/other-options/#ignorewarnings

**Comment by hardfist** [comment]
it's not urgent and most of the work is on js side and most of the work is porting this plugin https://github.com/webpack/webpack/blob/1f59cbec16c5b49c01e332d9e29373d096b69c49/lib/IgnoreWarningsPlugin.js#LL11C1-L11C1

**Comment by nagy-nabil** [comment]
> it's not urgent and most of the work is on js side and most of the work is porting this plugin [webpack/webpack@`1f59cbe`/lib/IgnoreWarningsPlugin.js#LL11C1-L11C1](https://github.com/webpack/webpack/blob/1f59cbec16c5b49c01e332d9e29373d096b69c49/lib/IgnoreWarningsPlugin.js#LL11C1-L11C1)

i started working on it yesterday
I added `ignoreWarnings` option to rspack options schema
I might do PR for you guys to see my progress
