### ISSUE TITLE
support `compilation.mainTemplate.hooks.localVars` hook

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#2982]
### What problem does this feature solve?

- https://github.com/webpack/webpack/blob/main/lib/runtime/CompatRuntimeModule.js

### What does the proposed API of configuration look like?

- support the user add runtime code to runtime module.

**Comment by hardfist** [comment]
hi @alexander-akait, I see the comment in https://github.com/webpack/webpack/blob/main/lib/MainTemplate.js#L40, and want to know whether MainTemplate will be removed in webpack6 and are all the hooks in mainTemplate will be gone, if MainTemplate will be removed what's alternative to put all these hooks, because if it will be removed in webpack@6 then we don't think it's necessary to implement it in rspack.

**Comment by alexander-akait** [comment]
It will be removed without replacement, we have good messages about deprecations - https://github.com/webpack/webpack/blob/main/lib/MainTemplate.js#L301, therefore, we should not implement it

**Comment by hardfist** [comment]
> It will be removed without replacement, we have good messages about deprecations - [webpack/webpack@`main`/lib/MainTemplate.js#L301](https://github.com/webpack/webpack/blob/main/lib/MainTemplate.js?rgh-link-date=2023-05-24T13%3A50%3A21Z#L301), therefore, we should not implement it

so there's no alternative for `compilation.mainTemplate.hooks.localVars`?, it seems some frameworks and plugins relys on this hook

**Comment by alexander-akait** [comment]
Based on logic you can rewrite it using `compilation.hooks.additionalTreeRuntimeRequirements` hook - https://github.com/webpack/webpack/blob/main/lib/RuntimePlugin.js#L442, we already do it :smile:

**Comment by alexander-akait** [comment]
https://github.com/nuxt/nuxt/blob/a672cd7a4291eb812d76b9841ec516cd8609c680/packages/webpack/src/plugins/chunk.ts#L22 can be rewritten on using `compilation.hooks.additionalTreeRuntimeRequirements` without any problems

**Comment by hardfist** [comment]
it seems all the hooks(which is useful) in the Template will be replaced with some hook in compilation?

**Comment by alexander-akait** [comment]
@hardfist Yeah, we done a lot of refactor around runtime and now runtime contains modules, like other modules, so now it is possible to write custom plugins with runtime without hacking like `replace`/`regexp`/etc

**Comment by hardfist** [comment]
low priority now we can reopen if we do need it
