### ISSUE TITLE
tracing logging for better debug

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#2989]
### What problem does this feature solve?

better dx

### What does the proposed API of configuration look like?

reference: 
https://rustc-dev-guide.rust-lang.org/tracing.html#using-tracing-to-debug-the-compiler

**Comment by IWANABETHATGUY** [comment]
@bvanjoi Did this pull request fits your need? https://github.com/web-infra-dev/rspack/pull/3002

**Comment by Boshen** [comment]
Closed due to stale and unclear feature request.
