### ISSUE TITLE
context module regex can't match properly

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#2990]
### System Info

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 56.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.9

### Details

webpack's regex is different to rspack, so the `map` will be different
![image](https://user-images.githubusercontent.com/87003751/235358157-e7c41944-4b2f-45c9-9b60-f9bece717936.png)

I found that the `relative_path` is always start with `./`
https://github.com/web-infra-dev/rspack/blob/71a6275769ed9acc8e11f7f68c1d2b201af0aaad/crates/rspack_core/src/context_module.rs#L407-L418
so I suggest changing this reg to `^\\.\\/{prefix}.*{inner_reg}{postfix_raw}$`
https://github.com/web-infra-dev/rspack/blob/71a6275769ed9acc8e11f7f68c1d2b201af0aaad/crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs#L502

### Reproduce link

https://github.com/faga295/rspack-reproduce/tree/context_module_regex

### Reproduce Steps

1. run 'pnpm build'
2. check the difference between `webpack-dist` and `rspack-dist`

**Comment by IWANABETHATGUY** [comment]
It seems that this is not a bug on Windows platform

**Comment by suxin2017** [comment]
#2960

**Comment by underfin** [comment]
Duplicated of #2960
