### ISSUE TITLE
process is not define when i start the project

### ISSUE THREAD

**Issue by AuglyXu** [web-infra-dev/rspack#2994]
### System Info

System：mac

### Details

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/42527305/235880681-1d348bc4-3007-4f82-a87e-d116088da08b.png">

启动项目后发生的问题，不知道问题具体出现在哪里

### Reproduce Steps

yarn install 
yarn start

**Comment by hardfist** [comment]
It seems you may forget to define some `process.env.xxx` which cause you access process on the browser(which not exits), you can check out the error stack and see how do you use `process` in your code

**Comment by AuglyXu** [comment]
> 

I will check tomorrow.Today I took a rough look at my project, but I didn’t find undefined process.env.xxx.If the error still exist,I will try to reproduce in demo project

**Comment by yxzh614** [comment]
i have this problem too. 
![image](https://user-images.githubusercontent.com/25242391/236402315-346abd12-f77f-414b-bb36-617884328eec.png)


        "@rspack/cli": "^0.1.9",
        "@rspack/plugin-node-polyfill": "^0.1.9",

**Comment by yxzh614** [comment]
@hardfist  demo is here https://github.com/yxzh614/demo_rspack_error

problem is these deps

    "@rspack/plugin-node-polyfill": "^0.1.9",
    "jmuxer": "^2.0.5",

**Comment by hardfist** [comment]
you forget to config define, so process.env.NODE_DEBUG is not transformed
```js
builtins: {
    define: {
      'process.env.NODE_DEBUG': JSON.stringify(false),
    },
    html: [
      {
        template: './index.html',
      },
    ],
  },
```

**Comment by AuglyXu** [comment]
@hardfist demo is here 
https://github.com/AuglyXu/lerna-test
problem is the deps "insight-iclient-leaflet"

how can i cover all the process.env.xxx in 3rd party library

**Comment by hardfist** [comment]
> @hardfist demo is here [AuglyXu/lerna-test](https://github.com/AuglyXu/lerna-test) problem is the deps "insight-iclient-leaflet"
> 
> how can i cover all the process.env.xxx in 3rd party library

if you find third party ship process.env.xxx, it's normally a bug of the library or the library should document this behavior

**Comment by AuglyXu** [comment]
> > @hardfist demo is here [AuglyXu/lerna-test](https://github.com/AuglyXu/lerna-test) problem is the deps "insight-iclient-leaflet"
> > how can i cover all the process.env.xxx in 3rd party library
> 
> if you find third party ship process.env.xxx, it's normally a bug of the library or the library should document this behavior, bundler can't automatic fix this for you

The dep is forked from @supermap/iclient-leaflet. It is a frequently used library and I can start successfully on webpack.Please can you help me locate what caused the problem in demo and how can  i fixed the error?Thanks.

**Comment by AuglyXu** [comment]
> 

I define the environment and use the demo from @yxzh614 , it occurs another unexpected error and my demo occured too.These errors depend on the third-party library used and are not predictable.

**Comment by hardfist** [comment]
> > 
> 
> I define the environment and use the demo from @yxzh614 , it occurs another unexpected error and my demo occured too.These errors depend on the third-party library used and are not predictable.

your demo is not a minimal demo and it seems your application use libraries which use node api, so you need to provide node-polyfill to make it work

**Comment by mirageN1349** [comment]
If you are using rsbuild then install https://v0.rsbuild.dev/plugins/list/plugin-node-polyfill
It solve problem for me
