### ISSUE TITLE
HMR has problem when enable treeShaking

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#3022]
### System Info

system unrelated.

### Details

use rspack **examples/react-refresh/**, change `rspack.config.js` to: 
```js
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	mode: "development",
	entry: { main: "./src/index.tsx" },
	builtins: {
		html: [{ template: "./index.html" }],
		define: {
			"process.env.NODE_ENV": "'development'"
		},
		treeShaking: true
	},
	optimization: {
		sideEffects: false
	}

};

```

### Reproduce link

nope

### Reproduce Steps

1. pnpm dev
2. change any file and trigger a hmr
3. you will find the hmr is not working as expected (maybe you should try more than once to reproduce this issue.)
4. and refresh the browser.

![image](https://user-images.githubusercontent.com/17974631/236415320-620e9151-7644-4c5b-80b6-9d2453ea6c2d.png)

**Comment by suxin2017** [comment]
Please assign it to me

**Comment by suxin2017** [comment]
The reason I found this problem is because the make section removes all the ast
```  
// remove prev build ast in modules
    fast_drop(
      self
        .module_graph
        .modules_mut()
        .values_mut()
        .map(|module| {
          if let Some(m) = module.as_normal_module_mut() {
            let is_ast_unbuild = matches!(m.ast_or_source(), NormalModuleAstOrSource::Unbuild);
            if !is_ast_unbuild {
              return Some(std::mem::replace(
                m.ast_or_source_mut(),
                NormalModuleAstOrSource::Unbuild,
              ));
            }
          }
          None
        })
        .collect::<Vec<Option<NormalModuleAstOrSource>>>(),
    );
```

**Comment by IWANABETHATGUY** [comment]
Thanks for investigating, I have already drafted a pull request to solve this issue. https://github.com/web-infra-dev/rspack/pull/3034
