### ISSUE TITLE
tsconfig.json paths not working

### ISSUE THREAD

**Issue by edusperoni** [web-infra-dev/rspack#3028]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.0.0-canary-e4a4943-20230505164427 => 0.0.0-canary-e4a4943-20230505164427 

### Details

When adding `paths` to `tsconfig.json`, rspack is unable to resolve them:

```
    "paths": {
      "my-alias/*": ["./src/*"]
    },
```

`src/main.ts`:
```ts
import { someValue } from "my-alias/otherfile";
```

Error:
```
error[internal]: Resolve error
  ┌─ src/main.ts:2:1
  │
2 │ import { someValue } from "my-alias/otherfile";
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Failed to resolve my-alias/otherfile in /path/to/src/main.ts
```

### Reproduce link

https://github.com/edusperoni/rspack-tsconfig-paths-issue

### Reproduce Steps

1. npm i
2. npx rspack

**Comment by hardfist** [comment]
do you config https://www.rspack.dev/config/resolve.html#resolve-tsconfigpath  this?

**Comment by hyf0** [comment]
I guess we need to make it more clear: Rspack doesn't read `tsconfig.json`.

I remember esbuild will read `tsconfig.json`, not sure which way it's better. But a good choice for improving DX is more checking by `@rspack/cli`.

A best-effort checking:

1. If the `tsconfig.json` exists with `paths` filed.
2. If the `resolve-tsconfigpath` is not configured.

Add a warning or else in the terminal when running `@rspack/cli`.

**Comment by edusperoni** [comment]
Maybe I'm doing something wrong? I've updated the example with:
```
resolve: {
    tsConfigPath: "./tsconfig.json",
  }
```

and it still doesn't work

**Comment by hardfist** [comment]
you should both set tsconfigPath as absolute path and set baseUrl as '.' to make tsconfig alias work right now, I thinks this should be improved
* rspack.config.js
```js
const path = require('path');
/**
 * @type {import('@rspack/core').Configuration}
 */
module.exports = {
  entry: './src/main.ts',
  resolve: {
    tsConfigPath: path.resolve(__dirname, './tsconfig.json'),
  },
};
```
* tsconfig.json
```json
{
  "compilerOptions": {
    "rootDir": "./src",
    "module": "commonjs",
    "paths": {
      "my-alias/*": ["./src/*"]
    },
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

**Comment by bvanjoi** [comment]
related: https://github.com/web-infra-dev/rspack/issues/2312
