### ISSUE TITLE
iconv cannot be bundled because of native bindings

### ISSUE THREAD

**Issue by antoinepairet** [web-infra-dev/rspack#3039]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 39.84 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 8.19.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Edge: 113.0.1774.35
    Safari: 16.4
  npmPackages:
    @rspack/core: ^0.0.0-canary-e4a4943-20230505164427 => 0.0.0-canary-e4a4943-20230505164427
    @rspack/dev-server: ~0.1.0 => 0.1.9
    @rspack/plugin-minify: ~0.1.0 => 0.1.9

### Details

In the context of a node app, we want to bundle all dependencies inside the deployed package. The goal is to avoid installing dependencies inside Docker because it is time-consuming and bloats the image size.

`iconv`, which is a native module, does not work. `rspack` crashes because it cannot deal with the compiled native code:

````
let bindings;
try {
  bindings = require('./build/Release/iconv.node');
}
catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  bindings = require('./build/Debug/iconv.node');
}
````
<img width="1533" alt="Screenshot 2023-05-06 at 12 21 52" src="https://user-images.githubusercontent.com/5238592/236618461-81798f01-a918-473f-b62c-1f1ca334f667.png">

I would expect `rspack` to behave the same way `webpack` (or `ncc`) does: copy the binary file in the output folder:

````
- main.js
- ./build/Release/iconv.node
````

### Reproduce Steps

Try to bundle any node program requiring `iconv`.

````ts
import { Iconv } from 'iconv';
const iconv = new Iconv('CP1252', 'UTF-8');
````

Relevant part of the `rspack` config: 
`config.externals = []`

**Comment by hyf0** [comment]
Have you tried https://github.com/webpack-contrib/node-loader?

**Comment by antoinepairet** [comment]
> Have you tried https://github.com/webpack-contrib/node-loader?

Thank you for the prompt feedback 🙌🏻 

I am using `rspack` in combination with `Nx`, the full config is: 

````js
const { composePlugins, withNx } = require('@nrwl/rspack');

module.exports = composePlugins(withNx(), (config) => {
  config.module.rules = config.module.rules || [];
  config.module.rules.push({
    test: /\.node$/,
    loader: 'node-loader',
  });
  config.externals = [];
  return config;
});
````

**Comment by hardfist** [comment]
@antoinepairet  https://github.com/web-infra-dev/rspack/pull/3030/files#diff-a6348f62d70aeaf4e122d5da1500710e64c3120004d7184103645d1f1e541f1cR13 I make a example for bundle iconv here

**Comment by antoinepairet** [comment]
@hyf0 

To make it work, 2 changes are needed:
1. Update the `rspack` config
2. Modify the way `iconv` loads binding 

Regarding the `rspack` config, I got it working:

````
{
  test: /\.node$/,
  loader: 'node-loader' // does not work and has typing issue
}
````


This does work
````
{
    test: /\.node$/,
    use: [
      {
        loader: 'node-loader',
      },
    ],
  }
````
<img width="326" alt="Screenshot 2023-05-06 at 14 26 30" src="https://user-images.githubusercontent.com/5238592/236623956-8806e2c0-c718-46fb-92b7-a5305c305917.png">

However, `iconv` refers to two `.node` files but only one is provided
````
let bindings;
try {
  bindings = require('./build/Release/iconv.node'); // <--- this file is provided
}
catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  bindings = require('./build/Debug/iconv.node');  // <--- this file DOES NOT exist
}
````

Modifying the `iconv` code to:
````
let bindings = require('./build/Release/iconv.node');
````

<img width="884" alt="Screenshot 2023-05-06 at 14 16 16" src="https://user-images.githubusercontent.com/5238592/236623866-3e174038-31a9-4ca0-9b5c-e5c6bbf96bf2.png">

Full config:
````js
const { composePlugins, withNx } = require('@nrwl/rspack');

module.exports = composePlugins(withNx(), (config) => {
  config.devtool = false;
  config.module = config.module || {};
  config.module.rules = config.module.rules || [];
  config.module.rules.push({
    test: /\.node$/,
    use: [
      {
        loader: 'node-loader',
      },
    ],
  });
  config.externals = [];

  console.log(JSON.stringify(config, null, 2));
  return config;
});
````

**Comment by antoinepairet** [comment]
> @antoinepairet https://github.com/web-infra-dev/rspack/pull/3030/files#diff-a6348f62d70aeaf4e122d5da1500710e64c3120004d7184103645d1f1e541f1cR13 I make a example for bundle iconv here

Thank you for the follow-up and the addition to the docs 💪🏻 🙌🏻 

I still cannot get `iconv` working because of the missing Debug binary:
<img width="1222" alt="Screenshot 2023-05-06 at 14 34 46" src="https://user-images.githubusercontent.com/5238592/236624539-f8cf6bab-9b3d-4ed2-9492-bf8f20e13dd2.png">

What would be the best way to solve this?
I tried to use the `null-loader` but it did not help
````js
  config.module.rules.push(
    {
      test: /Debug\/iconv.node$/,
      use: [
        {
          loader: 'null-loader',
        },
      ],
    },
    {
      test: /\.node$/,
      use: [
        {
          loader: 'node-loader',
          options: {
            name: '[path][name].[ext]',
          },
        },
      ],
    }
  );
````

**Comment by hardfist** [comment]
you just need to external Debug/iconv.node like I did here https://github.com/web-infra-dev/rspack/pull/3030/files#diff-2844befaec6ec4b247186e3b773e6846ff0df61d646099eaead593665f474462R9

**Comment by antoinepairet** [comment]
`/Debug\/iconv.node$/`

> you just need to external Debug/iconv.node like I did here https://github.com/web-infra-dev/rspack/pull/3030/files#diff-2844befaec6ec4b247186e3b773e6846ff0df61d646099eaead593665f474462R9

Thanks. I overlooked that part initially.
By the way, I tried with the `ignore-loader` but it did not work.

Tested with your example. It works like a charm. Huge thanks!
