### ISSUE TITLE
flag commonjs dependency in try block as optional 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3042]
### What problem does this feature solve?

when we bundle binding library which has many optional dependency, which always use try { requrie('xxx')} to do platform fallback logic.
but when rspack met this require will report resolve error which make bundle binding library hard.
webpack do an optimization to make require in try block as optional we should implement this feature too.
related to https://github.com/webpack/webpack/pull/11646
related to https://github.com/web-infra-dev/rspack/issues/3039

### What does the proposed API of configuration look like?

no api needed

**Comment by suxin2017** [comment]
Please assign this to me

**Comment by hardfist** [comment]
also need to deal with require.resolve
```js
try {
  let t = require.resolve('xxx');
}catch(err){
}
```
should transformed to 
```
try {
  let t = /*require.resolve*/(Object(function webpackMissingModule() { var e = new Error("Cannot find module 'xxx'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
  console.log('t:', t);
} catch (err) {}

/******/ })()
;
```

**Comment by antoinepairet** [comment]
@hardfist 

What about this one? Should it be transformed too?

https://github.com/ngonzalvez/rest-facade/blob/0f84023ace1709f3d8c0c82cf7190a32b10a239a/src/Client.js#L7

````js
  if (this.options.proxy) {
    // Add proxy support to the request library.
    require('superagent-proxy')(request);
  }
````

**Comment by hardfist** [comment]
it only handles require in try block
