### ISSUE TITLE
React for echarts fail to load

### ISSUE THREAD

**Issue by crazyxhz** [web-infra-dev/rspack#3046]
### System Info

 System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 172.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Safari: 16.0
  npmPackages:
    @rspack/cli: latest => 0.1.9

### Details

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6551888/236634648-d3ad170d-8944-460a-ac2e-a89f494c8288.png">

https://github.com/crazyxhz/echarts

### Reproduce link

https://github.com/crazyxhz/echarts

### Reproduce Steps

clone the repo
npm i && npm run dev

**Comment by suxin2017** [comment]
```
  const option = {
    series: [
      {
        type: 'pie',
        radius: ['40%', '60%'],
        label: {
          normal: {
            position: 'center'
          }
        },
        data: [{
          name:'Apples',
          value:60,
        },{
          name:'Oranges',
          value:40,
        }]
      },
      {
        type: 'pie',
        radius: ['0%', '40%'],
        data: [{
          name:'Bananas',
          value:100,
        }]
      }
    ]
  };
```
I tried to change the configuration to make this work and echart version 5.x
@crazyxhz

**Comment by suxin2017** [comment]
> 

哈哈哈，一本正经瞎生成
