### ISSUE TITLE
rspack sets optional properties of a class to `undefined`

### ISSUE THREAD

**Issue by antoinepairet** [web-infra-dev/rspack#3054]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 8.19.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Edge: 113.0.1774.35
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.0.0-canary-e4a4943-20230505164427 => 0.0.0-canary-e4a4943-20230505164427 
    @rspack/core: 0.0.0-canary-e4a4943-20230505164427 => 0.0.0-canary-e4a4943-20230505164427 
    @rspack/dev-server: ~0.1.0 => 0.1.9 
    @rspack/plugin-minify: ~0.1.0 => 0.1.9 

# Update 2023-05-08 19:32 GMT+2
All previous updates can be discarded.

`rspack` and `webpack (tsc)` give a different output with the following example:

Define a class with an optional property.

````ts
class MyClass {
  color?: string;
}
const withoutColor = new MyClass();

console.log(withoutColor);
````

### Webpack
````js
/******/ (() => { // webpackBootstrap
var __webpack_exports__ = {};
class MyClass {
}
const withoutColor = new MyClass();
console.log(withoutColor);
//The rest of the file is redacted
````

### Rspack
````js
(function() {
var __webpack_modules__ = {
"821": function (module, exports, __webpack_require__) {
class MyClass {
    color;
}
const withoutColor = new MyClass();
console.log(withoutColor);
},
//The rest of the file is redacted
````

`rspack` sets the color property to `undefined`. This leads to unexpected behavior at runtime. 

# ==== Below are past updates and the original bug report ====

## [Outdated] Update 2023-05-08 - simpler reproduction examples
Webpack and Rspack behave differently in the following cases:
1. When the typing and the decorators are not aligned, and the property is set - See Example 1
2. When `IsOptional()` is used, but the property is not set - See Example 2

The summary boils down to:
1. `@IsOptional()` is required to make the validation work
2. Adding `@IsOptional()` leads to properties being set to `undefined`, changing the behavior of the app (in our case, it makes the app crash)

### Example 1 - validation fails

````ts
import { ValidatorOptions, validate } from 'class-validator';

class MyClass {
  color?: string;
}
const withoutColor = new MyClass();

const opts: ValidatorOptions = {
  whitelist: true,
  forbidNonWhitelisted: true,
};

async function test() {
  const errorWithoutColor = await validate(withoutColor, opts);
  console.log(errorWithoutColor);
}

test();

````
Will log:
````
[
  ValidationError {
    target: MyClass { color: undefined },
    value: undefined,
    property: undefined,
    children: [],
    constraints: {
      unknownValue: 'an unknown value was passed to the validate function'
    }
  }
]
````

### Example 2 - `undefined`
````ts
import { IsOptional } from 'class-validator';

class MyClass {
  @IsOptional()
  color?: string;
}

const withColor = new MyClass();
withColor.color = 'blue';

const withoutColor = new MyClass();

console.log(withColor); // { color: 'blue' }
console.log(withoutColor); // { color: undefined }. <--- `undefined` is not expected
````

At runtime, the behavior will be different depending on the tool that is used to compile:
- with rspack:  `{ color: undefined }`
- with webpack: ` { }`

### Context
Webpack

## [Outdated] Original report

The package [class-validator](https://github.com/typestack/class-validator) behaves differently at runtime when compiled using `rspack` or `webpack`. A full reproduction is available below.

````ts
import { Type } from 'class-transformer';
import { IsArray, IsNumber, IsString, ValidateNested } from 'class-validator';

class userDataPostDto {
  @ValidateNested({ each: true })
  @IsArray()
  @Type(() => subData)
  public userSubData: subData[];

  @ValidateNested()
  @Type(() => subObject)
  public userSubObject: subObject;

  // webpack and rspack behave differently when the property is optional but the annotation @IsOptional() is not present
  // With the following payload:
  // {
  //   "userSubData": [
  //     { "subString": "hello", "subNumber": 3 },
  //     { "subNumber": 5, "subString": "there" }
  //   ]
  // }
  // 
  // webpack returns 200
  // rspack returns a 400, BadRequest
  //
  // When @IsOptional() is added, both behave the same way and accept the payload

  public iAmOptional?: string;
}
````

Similar issues exist with `Reflect.has()` when combined with `class-validator` and optional properties.
(for this one, I still need to produce a minimal reproduction scenario).
````ts
import has = Reflect.has;
has(myObj, 'myOptionalProperty') // will return `true` even though `myObj.myOptionalProperty` is not set.
````

Happy to provide any additional details or to pair to help investigate.

### Reproduce link

https://github.com/rosahealth/nestjs-rspack

### Reproduce Steps

Clone `https://github.com/rosahealth/nestjs-rspack`
Install dependencies `npm ci`

# Rspack
- Serve the app using `rspack` with `npx nx run bundle-all-deps:rspack-serve`
- Use cURL or Postman to send requests to the app

````
curl --location --request POST 'http://localhost:3000/api' \
--header 'Content-Type: application/json' \
--data-raw '{"userSubData": [{"subString": "hello", "subNumber": 3}, {"subNumber": 5, "subString": "there" }]}'
````

returns

````
{
    "statusCode": 400,
    "message": [
        "property iAmOptional should not exist"
    ],
    "error": "Bad Request"
}
````

# Webpack
- Serve the app using `rspack` with `npx nx run bundle-all-deps:serve`

Webpack correctly responds:
````
{
    "message": "Never reached with rspack"
}
````

**Comment by edusperoni** [comment]
Can you share your `tsconfig.json`? I believe this is related to https://github.com/web-infra-dev/rspack/issues/3028

It seems rspack is outputting es2022 and isn't honoring the options in `tsconfig.json`.

To emit this:
```
class MyClass {
}
```
under `es2022` you need to define `"useDefineForClassFields": false`

The new "correct" way of declaring optional values is:
```
class MyClass {
  declare color?: string;
}
```

Example:
https://www.typescriptlang.org/play?strict=false&useDefineForClassFields=true&target=99&noLib=true#code/MYGwhgzhAEAqCmEAu0DeAoaXoBN6jACd5oIB7AW3gDUwQBXeAfgC5SlCBLAOwHMBuTNjJIAFvEK0GzNsi59BAXyA

**Comment by antoinepairet** [comment]
@edusperoni That is correct. Thanks for the tip.

The issue or confusion comes from the fact that `rspack` does not read `tsconfig.json` as specified in https://github.com/web-infra-dev/rspack/issues/3028#issuecomment-1537031620

To have it working, one needs both:
- https://www.rspack.dev/config/target.html#target
- `output.chunkFormat` (which seems undocumented)

````
  config.target = 'es2015';
  config.output = {
    ...config.output,
    chunkFormat: 'commonjs',
  };
````

**Comment by hardfist** [comment]
@antoinepairet  thank you for your detail investigation, currently rspack only respect tsconfig.json's paths and baseUrl when set resolve.tsconfigPaths, so we need to expose https://swc.rs/docs/configuration/compilation#jsctransformusedefineforclassfields to builtins.transform so user can custom swc transform logic, in the long term we'll expose swc-transform as a loader so user can config swc transform logic directly in config options

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
you can disable internal transformation and use builtin:swc-loader to control decorator transformation now https://www.rspack.dev/guide/loader.html#builtinswc-loader
