### ISSUE TITLE
example angular bundle size is a lot bigger than webpack

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#3062]
### System Info

mac os 

### Details

bundle  generated by `rspack` is about 200KB bigger than `webpack`

### Reproduce Steps

1. cd examples/angular
2. pnpm build 
3. pnpm build:rspack
4. compare bundle size

**Comment by junshengL** [comment]
The following error was reported when starting the build locally

![image](https://github.com/web-infra-dev/rspack/assets/128459865/6ea92e44-22d1-4546-8577-89bed0597dfb)

**Comment by Boshen** [comment]
![img_v2_7fbd5fcc-56d9-4420-957b-a2e5a5f05feg](https://github.com/web-infra-dev/rspack/assets/1430279/50993298-9782-4df6-b3d1-614bf8fa3e1d)
![img_v2_a1c2817b-345a-48a4-bf97-2b34bc5e8b4g](https://github.com/web-infra-dev/rspack/assets/1430279/816a53d7-d5c4-496c-a48d-6bef081578be)

**Comment by IWANABETHATGUY** [comment]
closed in favor of https://github.com/web-infra-dev/rspack/pull/3514
