### ISSUE TITLE
support builtin:swc-loader with custom swc options

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3067]
### What problem does this feature solve?

users need more and more swc custom options now (see https://github.com/web-infra-dev/rspack/issues/3054) , and it's not ideal to put more and more swc options to builtins which will bloat builtins, so it would be better to put all these custom swc options to loader, once we support builtin-swc-loader, we may deprecate type: 'ts' and the default transformation of javascript module in the future, which makes rspack more compatible with webpack

> The builtin:swc-loader is much faster than the js version of https://swc.rs/docs/usage/swc-loader because it can run parallel in rust side and it avoids the rust js communication

### What does the proposed API of configuration look like?
```js
module.exports = {
  module: {
   rules: [{
      test: /\.js/,
      use: {
           loader: 'builtin:swc-loader',
           options: {

                        parser: {
                            syntax: "typescript"
                        },
                        transformer: {
                            useDefineForClassFields: true
                       }
                }
      }
   }]
 }
}
```

**Comment by hardfist** [comment]
we may need a option to disable default transformation of javascript | typescript module, since it will cause the module is transformed by swc twice once people use swc-loader, but the default transformation behavior is friendly to user than manually configure loader especially for new user.
one solution is we introduce a concept called preset(which I remember @TheLarkInn mentioned before), which controlled whether rspack will transform these modules by default
```js
{
  presets: 'default'  | 'transform' // default means don't do any transformation by default and 'transform' means transform ts and js using swc by default
}
```
@TheLarkInn @alexander-akait what's the plan of the `preset` concept and any suggestions?

**Comment by alexander-akait** [comment]
@hardfist we are still considering this concept (and I don't think preset will sove this problem fully), but there are already two solutions:
1. pass AST from swc-loader, so rspack can avoid double parsing, webpack supports it, but only for `estree` compatibility parsers
2. redefine `defaultRules` and use `swc-loader` by default

I think the valid usage is the first, because you can't neven know which options will be used, but if you have AST, you don't need to parse everything twicy, the same can be used for CSS and HTML, unfortunately, no `estree` analog for CSS and HTML, but I for HTML it is not a problem, because `swc-html` uses the browser logic and create DOM, so it can be used as a `standard`, for CSS it is tricky, anyway right now I have dicussion in stylleint about full features parser and analog for CSS, so it will allow to reuse CSS AST across different parsers.

Here https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js#L3897 usage of AST
Anyway we use this approach even for custom parsers, for example https://github.com/webpack-contrib/postcss-loader/blob/master/src/index.js#L228, we pass AST from postcss-loader to css-loader and avoid multiple parsing

**Comment by hardfist** [comment]
> So do you want to implement presets to hide implementations from users, right? Because developer can setup swc-loader using rules now.

I think defaultRules is good enough to handle compatibility now, so I don't think introduce `preset` before webpack does is a good idea, and in the long run we consider deprecate the whole `builtins` options and replace it with `swc-loader` with swcOptions and [mock plugin](https://github.com/web-infra-dev/rspack/discussions/3252) this makes rspack more compatible with wepback.
but I'm still not sure should we keep things like  `type: ts`, because although it's nog compatible with webpack but it's user friendly for normal user but it's hard to work with swc-loader, I tend to deprecate it for compatibility

**Comment by hardfist** [comment]
> Here [webpack/webpack@main/lib/javascript/JavascriptParser.js#L3897](https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js?rgh-link-date=2023-06-07T11%3A02%3A14Z#L3897) usage of AST
Anyway we use this approach even for custom parsers, for example [webpack-contrib/postcss-loader@master/src/index.js#L228](https://github.com/webpack-contrib/postcss-loader/blob/master/src/index.js?rgh-link-date=2023-06-07T11%3A02%3A14Z#L228), we pass AST from postcss-loader to css-loader and avoid multiple parsing
so this only works for style-loader or you need to do right span calculation in this postcss-loader?

**Comment by hardfist** [comment]
talking about swc-loader, it opens the possibilities for user to do custom dynamic loaded plugin by swc wasm plugin, which maybe not stable enough, we can also implement wasm-loader(I'm not sure it'a good idea because even the string transformation is easy, but the loader Interface is complex)

**Comment by hardfist** [comment]
> Just side infromation - honestly i don't understand why swc-ecma-parser is not compatibility with estree, that would be just amazing, we can use it in many tools just like a replacement (yes it take some muck more times due since the ast passing from js to rust have large cost), but it will be allow to start smooth transitions for many tooling or at least provide an opportunity to use alternative approaches. Even more - 80-90 percents of the structures are already identical (at the last moment when I worked with swc).

I remember @Boshen's oxc is not compatible with estree too? @Boshen do you think estree compatible ast is a good idea for rust javascript parser?

**Comment by alexander-akait** [comment]
> so this only works for style-loader or you need to do right span calculation in this postcss-loader?

postcss always caculate spans, so there is no problems with it

> talking about swc-loader, it opens the possibilities for user to do custom dynamic loaded plugin by swc wasm plugin, which maybe not stable enough, we can also implement wasm-loader(I'm not sure it'a good idea because even the string transformation is easy, but the loader Interface is complex)

> does babel-loader or swc-loader return ast now? I'm wondering whether babel-loader could get the right span after the transformation or does babel can provides things like untransform to get right span without reparsing

If we look at coode - no, but it was design for it, some decent time ago it was not compatible, but at the moment I don't know, we should check it out, but yeah, this feature was originally created for this, it is a pity that it has not gained popularity, because it makes eveything more faster

**Comment by hardfist** [comment]
> > So do you want to implement presets to hide implementations from users, right? Because developer can setup swc-loader using rules now.
> 
> I think defaultRules is good enough to handle compatibility now, so I don't think introduce `preset` before webpack does is a good idea, and in the long run we consider deprecate the whole `builtins` options and replace it with `swc-loader` with swcOptions and [mock plugin](https://github.com/web-infra-dev/rspack/discussions/3252) this makes rspack more compatible with wepback. but I'm still not sure should we keep things like `type: ts`, because although it's not compatible with webpack but it's user friendly for normal user but it's hard to work with swc-loader, I tend to deprecate it for compatibility

even defaultFules is good enough, but it's not that easy to manipulate the defaultRules, user may need to modify defaultRules config directly to remove the internal swc-loader which seems not ideal? @alexander-akait any suggestions?

**Comment by alexander-akait** [comment]
@hardfist hm, `defaultFules` was design for such purposes :smile: Can you show me what is hard there? Maybe you have a good idea (just an example if a configuration), so we can think about it, technically you also can implement custom `type` for modules, for example `javascript/swc-esm`/`javascript/swc-dynamic` and etc and put them as defaults, also developer always can use `swc-loader` with own options and also we build-in in the one project

**Comment by hardfist** [comment]
its easy to add but hard to delete，because users need to know the internal implementation to safely delete swc rule and not breaking other rule

**Comment by alexander-akait** [comment]
@hardfist How you want to get AST and ranges from swc-loader? Because if it doesn't return ranges, we still need reparse it...
We can implement something like:
```
module.exports = {
  module: {
    parser: {
      defaultTypes: {
        javascript: "javascript/esm",
        css: "css/modules"
        // etc
      }
  },
};
```

**Comment by hardfist** [comment]
> @hardfist How you want to get AST and ranges from swc-loader? Because if it doesn't return ranges, we still need reparse it...
yeah as i said before we just give up reusing ast from swc-loader because of the transform range problems (but we still get performance gain since it's in rust and parallel),

**Comment by hardfist** [comment]
We can implement something like:
> 
> ```
> module.exports = {
>   module: {
>     parser: {
>       defaultTypes: {
>         javascript: "javascript/esm",
>         // javascript: "javascript/esm+swc"
>         css: "css/modules"
>         // etc
>       }
>   },
> };
> ```
the `defaultTypes` seems much more flexible than defaultRules and seems we can keep `type:ts` for this

**Comment by alexander-akait** [comment]
Yeah, we can implement this, it can create a weird case like `javascript: "css"` :laughing: but I think people will not use it (also parser just failed because CSS parser can't parse Javascript)

**Comment by jraoult** [comment]
I stumbled upon this use while trying to find a solution to turn on `useDefineForClassFields`. I don't know if there is another way at this stage but it seemed the most promising.

**Comment by hardfist** [comment]
> I stumbled upon this use while trying to find a solution to turn on `useDefineForClassFields`. I don't know if there is another way at this stage but it seemed the most promising.

it's designed to solve this problem, even it's completed right now but I think it can be used to solve your problem now, what's the blocker for you?

**Comment by jraoult** [comment]
Thanks for the pointer @hardfist. I'll try it when I have a moment. I need `useDefineForClassFields` to get Mobx to work properly (see https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties).

**Comment by hardfist** [comment]
@jraoult it's actually implemented and you can use it now(a example here https://github.com/web-infra-dev/rspack/blob/main/examples/builtin-swc-loader/rspack.config.js#L12), what left is how we disable the default transformation so user's code don't need to transform twice(swc-loader and the default transform)

**Comment by hardfist** [comment]
> Can I extend swc plugins in this way ? like: `jsc: { experimental: { plugins: [ ['swc-plugin-xxx', {}] ], },`

 you mean the swc wasm plugin?

**Comment by thinkey-yang** [comment]
Thank you for your reply ，
I plan to migrate some old projects to rspack,In these old projects I used a custom babel plugin to help configure cssmodule automatically, the babel plugin transform
```
import a from 'foo.less';
Import 'foo.less';
import c from 'foo.sass';
import d from '.. /foo.css';
```
to 
```
import a from "foo.less?modules";
Import 'foo.less'; 
import c from "foo.sass?modules";
import d from ".. /foo.css?modules";
```
Then , with webpack rule.resourceQuery(/modules/)  open cssmodule。
Now , use repack， Do you have any suggestions for this

**Comment by hardfist** [comment]
why not just configure rule directly
```js
{
  module: {
   rule: {
      test: /\.less$/,
      use: [{loader:'css-module', options: {module:true}},'less-loader'],
   }
}
}
```

**Comment by thinkey-yang** [comment]
The same as the demo above, when we use `import 'foo.less'`, the CSS module is not enabled.. It's easier for users to maintain the global style. I also thought about automatically enabling the CSS module by using a file name suffix like 'index.module.less'. However, changing the file names manually would be too expensive。🤔

**Comment by hardfist** [comment]
> The same as the demo above, when we use `import 'foo.less'`, the CSS module is not enabled.. It's easier for users to maintain the global style. I also thought about automatically enabling the CSS module by using a file name suffix like 'index.module.less'. However, changing the file names manually would be too expensive。🤔

can you provide a repro？

**Comment by 9aoy** [comment]
@thinkey-yang resourceQuery is also supported in Rspack, it seems that you can write like this:

```js
    rule: {
      test: /\.less$/,
      oneOf: [
        {
          resourceQuery: /modules/,
          type: 'css/module',
          use: [
            // xxx
          ],
        },
        {
          type: 'css',
          use: [
            // xxx
          ],
        },
      ],
    },
```

**Comment by thinkey-yang** [comment]
@hardfist my project is build by umi ,  you can get more info form : https://github.com/umijs/swc-plugin-auto-css-modules and https://github.com/umijs/umi/blob/3.x/packages/bundler-webpack/src/getConfig/css.ts.

**Comment by hardfist** [comment]
> @hardfist my project is build by umi , you can get more info form : [umijs/swc-plugin-auto-css-modules](https://github.com/umijs/swc-plugin-auto-css-modules) and [umijs/umi@`3.x`/packages/bundler-webpack/src/getConfig/css.ts](https://github.com/umijs/umi/blob/3.x/packages/bundler-webpack/src/getConfig/css.ts?rgh-link-date=2023-08-17T03%3A20%3A34Z).

to be honest this is a bad design of umi, we have no plan to support this bad design, we suggest you configure css module by module.rules other than auto detect in import style in module.

**Comment by h-a-n-a** [comment]
Closed as it has been supported. Let's move the further questions to another issue or here: https://github.com/web-infra-dev/rspack/issues/3067
