### ISSUE TITLE
support `__webpack_chunk_load__` module variable

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3070]
There are third-part codes that rely on this variable, it would be good to support it to improve the compatibility of Rspack to Webpack.

See details https://webpack.js.org/api/module-variables/#__webpack_chunk_load__-webpack-specific.

**Comment by lippzhang** [comment]
please assign to me

**Comment by hyf0** [comment]
> please assign to me

Thank you in advance.
