### ISSUE TITLE
incorrect css order

### ISSUE THREAD

**Issue by urielvan** [web-infra-dev/rspack#3077]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 2.15 GB / 15.64 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566

### Details

css output is different from using webpack

### Reproduce link

https://github.com/urielvan/rspack-css-order

### Reproduce Steps

1. run `npm start`
2. select any row by checking the checkbox, the row will have gray background, which is incorrect.
3. stop the devServer
4. open modern.config.ts, comment line 10
5. run `npm start`
6. select any row by checking the checkbox, the row will have blue background, which is expected.

**Comment by hardfist** [comment]
@hyf0  can you confirm whether this is solved

**Comment by hyf0** [comment]
Please update all modernjs-releated packages to `2.25.2`. I have confirmed that the problem was fixed.
