### ISSUE TITLE
enable RSPACK_CONFIG_VALIDATE to strict in 0.3

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3079]
### What subject does this issue tracking?

RSPACK_CONFIG_VALIDATE is set to loose which make confusing for users we should set it to strict in 2.0

**Comment by hyf0** [comment]
It's better to enable strict checking after we refactor the options part. The current implementation is buggy and complicated.

I suggest we move this to the 0.3.0 version rather than 0.2.0.

**Comment by hardfist** [comment]
since we finished the options refactor, we may could enable it in next minor version

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
we should delay this until we unify the builtin-plugin and swc-loader

**Comment by Boshen** [comment]
Is this resolved? 

https://github.com/search?q=repo%3Aweb-infra-dev%2Frspack%20RSPACK_CONFIG_VALIDATE&type=code

I can't tell from our usages.
