### ISSUE TITLE
support statsPrinter and statsFactory hook

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3090]
### What problem does this feature solve?

lots of plugin use statsFactory and statsPrinter for customize stats like https://github.com/waysact/webpack-subresource-integrity/blob/914fdd9dd5982b4f52782c55eb6cb33fea5861cc/webpack-subresource-integrity/src/hooks.ts#LL19C1-L19C1 and https://github.com/esbuild-kit/esbuild-loader/blob/b207d8bddb70e9bc1a4a520afd551eadebb4568a/src/plugin.ts#L206

### What does the proposed API of configuration look like?

align with webpack

**Comment by hardfist** [comment]
thanks in advance

**Comment by 9aoy** [comment]
@lippzhang hello, do you have any available time to continue following up on this feature? I also require this hook. If you're unable to allocate the time, I can take on the implementation.

**Comment by lippzhang** [comment]
> 
Sorry, I've been working a lot lately. you can take care of this

**Comment by lippzhang** [comment]
> 

Sorry, I've been working a lot lately. you can take care of this
