### ISSUE TITLE
support chunkHash hook

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3092]
### What problem does this feature solve?

chunkHash is important to make sure assets hash is updated in processAssets hook, it's a block for esbuild-loader and terser-webpack-plugin

### What does the proposed API of configuration look like?

align with webpack https://github.com/webpack/webpack/blob/ba56e05b24014bb513eab95f4fa37c751212e0a9/lib/Compilation.js#L4163

**Comment by ahabhgk** [comment]
optimization.realContentHash is a workaround, so p3-has-workaround

**Comment by chenjiahan** [comment]
bump
