### ISSUE TITLE
enable `optimizations.chunkIds: 'deterministic'` by default in production mode for `0.2.0` version

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3096]
Thank you for your wonderful work!

I would merge this PR soon.

`deterministic` id is an important feature,  so I will not make it default in production mode but people could enable it manually, it would be the default option in production mode in the '@0.2.0' version.

_Originally posted by @hyf0 in https://github.com/web-infra-dev/rspack/issues/3053#issuecomment-1541279751_

**Comment by chenjiahan** [comment]
When will deterministic be the default behaviour?

**Comment by hyf0** [comment]
0.4 I think.
