### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by beilo** [web-infra-dev/rspack#3097]
### System Info

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.6.1
    Safari Technology Preview: 16.0

### Details

I often encounter this problem in my company's projects. (PS: It does not affect normal operation. After closing the × in the upper right corner, the function is still normal.) 
Since it is a company project, it is not possible to reproduce a minimal case. 
There are also no relevant errors in the console.
This is a screenshot of the source code that produced the error:
![image](https://github.com/web-infra-dev/rspack/assets/19225489/568121cf-b357-48e5-bd7c-80d911808689)
This is the corresponding source code:
[main.zip](https://github.com/web-infra-dev/rspack/files/11438811/main.zip)
Could you please help me take a look? Thank you~

This is the translated content using GPT

### Reproduce Steps

not simplest

**Comment by hardfist** [comment]
seems similar to https://github.com/web-infra-dev/rspack/issues/2169
