### ISSUE TITLE
Add `system` output type

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3112]
### Discussed in https://github.com/web-infra-dev/rspack/discussions/3110

<div type='discussions-op-text'>

<sup>Originally posted by **jamesarosen** May 11, 2023</sup>
WebPack has [built-in compatibility](https://github.com/systemjs/systemjs#compatibility-with-webpack) with [SystemJS](https://github.com/systemjs/systemjs). As of May 2023, rspack's `output.library.type` [supports many values](https://www.rspack.dev/config/output.html#outputlibrarytype), but not `system`.

SystemJS, while not standards-track, is widely used, especially in micro-frontend systems like [single-spa](https://single-spa.js.org/).

One caveat is that SystemJS imports are context-sensitive, which is why things like [systemjs-webpack-interop](https://github.com/joeldenning/systemjs-webpack-interop) exist.

If the rspack team would prefer this as a plugin, it would be helpful to have a reference plugin for supporting a new `output.libraryTarget` (or `output.library.type`).</div>

**Comment by suxin2017** [comment]
I find this troublesome. Can I have a try?
