### ISSUE TITLE
Bundle size increased when using `experiments.newSplitChunks`

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#3120]
## System Info

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.56 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/Library/Caches/fnm_multishells/37116_1683795276594/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/37116_1683795276594/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/37116_1683795276594/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 15.6.1

## Details

The bundle size of [Modern.js](https://github.com/web-infra-dev/modern.js) applications is increased after bumping Rspack to `v0.1.10`:

![8735c6bb-77f5-4597-aedf-5f318d36b0a6](https://github.com/web-infra-dev/rspack/assets/7237365/3435d168-ed16-4d7f-822c-e384b4dcffe8)

After comparing the changes, I found that the reason is that we enabled the `experiments.newSplitChunks` config.

Our `splitChunks` config:

```js
{
  optimization: {
    splitChunks: {
      chunks: "all",
      enforceSizeThreshold: 50000,
    },
  },
},
```

### experiments.newSplitChunks: false

When `experiments.newSplitChunks` is false, the bundle size is `5.06MB`:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/b6f759d6-eded-47b9-9a9d-aec5c69465be)

### experiments.newSplitChunks: true

After enabling `experiments.newSplitChunks`, the bundle size increased to `5.34MB`, and here one huge bundle is produced instead of multiple bundles of similar size:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/be85e3a4-db64-4054-81e1-e4067cbf4a50)

## Reproduce link

https://github.com/chenjiahan/rspack-new-split-chunks-bug

### Clone

```bash
git clone git@github.com:chenjiahan/rspack-new-split-chunks-bug.git
```

### New split chunks

```bash
cd new-split-chunk && pnpm i && pnpm build --analyze
```

### Old split chunks

```bash
cd old-split-chunk && pnpm i && pnpm build --analyze
```

**Comment by chenjiahan** [comment]
Also I found that async css chunks are not split when using `experiments.newSplitChunks`, I wonder if this is by design.

**Comment by hardfist** [comment]
@hyf0 is this solved?

**Comment by hyf0** [comment]
> @hyf0 is this solved?

Nope.

**Comment by chenjiahan** [comment]
Bump, the current bundle size is even more larger than webpack:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/8d283a3f-136f-465c-b96a-0763a4b9863b)

https://web-infra-dev.github.io/modern-js-benchmark/

**Comment by hyf0** [comment]
I will take a look next week.

**Comment by hyf0** [comment]
It seems that `newSplitChunks: true` now emits smaller output than `newSplitChunks: false` in `2.34.0`. I think we are ok to close this issue.

![image](https://github.com/web-infra-dev/rspack/assets/49502170/5d6549b8-143e-4ca4-8eb4-12a2e34d1125)

> the current bundle size is even more larger than webpack

@chenjiahan Do you think it's ok we close this issue and create a new issue to track this problem?

**Comment by chenjiahan** [comment]
LGTM, I will close this issue and create a new issue later.
