### ISSUE TITLE
support `compilation.mainTemplate.hooks.requireEnsure`

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3127]
block #2313

**Comment by sladyn98** [comment]
@hardfist I could give this a shot, any code pointers.

**Comment by hardfist** [comment]
> @hardfist I could give this a shot, any code pointers.
> 
> CC @hyf0 @Boshen

sorry, it's not easy right now, we need to provide compilation.mainTemplate first then adding hooks should be easy

**Comment by sladyn98** [comment]
Oh no problem, Ill come back to this later. Thanks
