### ISSUE TITLE
support `compilation.mainTemplate.hooks.requireExtensions`

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3129]
block #2313

**Comment by annanShao** [comment]
@hardfist Have anything block this issue ? (●'◡'●)

**Comment by hardfist** [comment]
> @hardfist Have anything block this issue ? (●'◡'●)

since webpack will remove mainTemplate in the future https://github.com/web-infra-dev/rspack/issues/2982#issuecomment-1561191318, we decide not to implement MainTemplate now

**Comment by annanShao** [comment]
Got it, I saw the discussion and the comments. Thank you for your response.

I also found any discussions related to the mainTemplate.hooks.requireExtensions, which could be referenced if needed.
https://github.com/webpack/webpack.js.org/issues/4943

**Comment by shirakaba** [comment]
Just to mention that [@vercel/webpack-asset-relocator-loader](https://github.com/vercel/webpack-asset-relocator-loader) relies on this hook, and without it, we can't build [Electron Forge](https://www.electronforge.io) apps using Rspack. Electron Forge rely on the loader so heavily that they [patch it](https://github.com/electron/forge/blob/6b2d547a7216c30fde1e1fddd1118eee5d872945/packages/plugin/webpack/src/util/AssetRelocatorPatch.ts#L32), and when they do so, they use the same `compliation.mainTemplate` API.
