### ISSUE TITLE
Automatically switch to available port if the default port is occupied for `rspack dev`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3134]
### What problem does this feature solve?

Better DX. People don't need to switch to the available port manually.

### What does the proposed API of configuration look like?

nope.

**Comment by lippzhang** [comment]
please assign to me

**Comment by hyf0** [comment]
> please assign to me

Thank you in advance,

**Comment by lippzhang** [comment]
It seems that this feature is already in the source code
<img width="1123" alt="image" src="https://github.com/web-infra-dev/rspack/assets/9498609/d9466860-913f-4503-8f97-f1bc56123b14">
When I add the `port` setting in the configuration file, the effect will be as shown below
<img width="1129" alt="image" src="https://github.com/web-infra-dev/rspack/assets/9498609/ca59f947-66a9-4816-b424-48028ba8c5ec">

I think it's reasonable

**Comment by hyf0** [comment]
Yeah. If users specify the port explicitly `rspack dev` should not switch to the available port automatically and should throw an error.

If users don't specify the port, we could automatically switch to the available port for better DX.

**Comment by hyf0** [comment]
Thank @lippzhang for investigating. `webpack-dev-server` has already supported this.

**Comment by ywang1724** [comment]
Can you provide port and strictPort like vite? @hyf0
