### ISSUE TITLE
Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rspack#3155]
### System Info

OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 12.02 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: 0.1.10 => 0.1.8

### Details

I'm having this problem, with HMR when I update a component and then I undo it.

My rspack config

```
const path = require('node:path');

const config = {
    entry: {
        main: './src/index.tsx'
    },
    resolve: {
        alias: {
            src: path.resolve(__dirname, 'src'),
            framework: path.resolve(__dirname, 'src/framework'),
            features: path.resolve(__dirname, 'src/features'),
            routing: path.resolve(__dirname, 'src/routing'),
            resources: path.resolve(__dirname, 'src/resources')
        }
    },
    module: {
        rules: [
            {
                test: /\.svg$/i,
                type: 'asset'
            },
            {
                test: /\.(woff2|png|webp)$/i,
                type: 'asset/resource'
            }
        ]
    },
    builtins: {
        html: [
            {
                template: './public/index.html',
                favicon: './public/favicon.png'
            }
        ]
    }
};
module.exports = config;
```

### Reproduce Steps

npx rspack serve
Do a change and undo it

**Comment by eriktvj** [comment]
having the same issue

**Comment by JoseBuendiaDigio** [comment]
Investigating more seems that is due to asset type, because if I set asset/inline instead of asset/resource works fine

**Comment by hyf0** [comment]
Please create a reproduction using https://github.com/web-infra-dev/rspack-repro

**Comment by JoseBuendiaDigio** [comment]
@hyf0 Here you have the problem https://github.com/JoseBuendiaDigio/multiple-assets/tree/main
If you remove the img and undo it, it fails

**Comment by Shad02w** [comment]
This seem still be a issue at version `0.2.3`.
repo: https://github.com/Shad02w/repack-asset-hmr-repo

**repo step**: 
1. In config, change svg rule type to `asset/resource` 
2. run `rspack serve`
3. comment and undo svg img tag in source code
![image](https://github.com/web-infra-dev/rspack/assets/6605655/d0d3cd40-5e9e-463d-9870-efa035362990)

**Comment by underfin** [comment]
Please track here https://github.com/web-infra-dev/rspack/issues/3554
