### ISSUE TITLE
Memory leak when using `@rspack/core` API

### ISSUE THREAD

**Issue by Nikaple** [web-infra-dev/rspack#3169]
### System Info

```
  System:
    OS: Linux
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
    Memory: 19.11 GB / 31.10 GB
    Container: Yes
    Shell: 5.0.2 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    @rspack/cli: latest => 0.1.10 
    @rspack/core: ^0.1.10 => 0.1.10 
```

### Details

<img width="1170" alt="screenshot" src="https://github.com/web-infra-dev/rspack/assets/24775744/96d4268b-92c6-4fcf-962e-13252ccab5bb">

#### With webpack

<img width="1307" alt="screenshot-webpack" src="https://github.com/web-infra-dev/rspack/assets/24775744/16ddeb05-f528-4ba7-9044-9f3b2bb130e8">

### Reproduce Steps

1. Create a project `npm create rspack@latest`
2. Create a script to compile consecutively with `@rspack/core`
3. Run the script to get memory leak

Script content:
```js
const { rspack } = require('@rspack/core')
const config = require('./rspack.config')

function compile() {
    const compiler = rspack(config);
    return new Promise((resolve, reject) => {
        compiler.run((err, stat) => {
            if (err) {
                return reject(err)
            }
            return resolve(stat)
        })
    })
}


async function main() {
    await compile();

    setTimeout(() => {
        const memory = process.memoryUsage();
        console.log(`Total memory used: ${Math.round(memory.rss / 1024 / 1024)} MB`)
        main()
    }, 1000);
}

main().catch(console.error)
```

**Comment by Boshen** [comment]
Confirmed. How did you discover this? We don't normally import it as a package 🤔

**Comment by Nikaple** [comment]
I am currently in the process of migrating a complex build tool that is based on webpack. The tool has the ability to compile multiple projects simultaneously, utilizing webpack's core API. However, when attempting to migrate it to rspack, I encountered a persistent issue of the process being killed due to an OOM error.

**Comment by pratyushseq** [comment]
bump!

**Comment by Nikaple** [comment]
bump

**Comment by h-a-n-a** [comment]
@Nikaple I believe this issue has been mitigated: 
<img width="444" alt="image" src="https://github.com/web-infra-dev/rspack/assets/10465670/cec6d965-e70d-4bba-bb58-64929d4172d2">
But there's still some leaking problem with the `Compiler` and `Compilation`. It's under our investigation.

**Comment by h-a-n-a** [comment]
bump

**Comment by ahqsoftwares** [comment]
bump

**Comment by chestozo** [comment]
We are also experiencing rapidly growing memory consumption of rspack dev build in watch mode.
After app is tarted we have `node` process eating around 5.8gb of memory.
After 5-10 mins it can grow up until 10gb sometimes even reaching 12gb :(

**Comment by ahqsoftwares** [comment]
> We are also experiencing rapidly growing memory consumption of rspack dev build in watch mode. After app is started we have `node` process eating around 5.8gb of memory. After 5-10 mins it can grow up until 10gb sometimes even reaching 12gb :(

Exactly

**Comment by h-a-n-a** [comment]
> We are also experiencing rapidly growing memory consumption of rspack dev build in watch mode. After app is started we have `node` process eating around 5.8gb of memory. After 5-10 mins it can grow up until 10gb sometimes even reaching 12gb :(

Would you please file another issue? This issue is basically related when creating multiple compilers and the memory not getting freed after that.

**Comment by xcfw** [comment]
could you guys link another issue here, as it's hard to find

**Comment by chestozo** [comment]
https://github.com/web-infra-dev/rspack/issues/8976

**Comment by alfaproject** [comment]
For us, this specific issue is not really solved. We also have our own custom build tooling which basically globs a list of lambda handlers in a folder and then for each one, creates a Rspack config to bundle that lambda and runs the compiler on it. Something like this:
```ts
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';

import { ExecutorContext, logger } from '@nx/devkit';
import { Compiler, rspack } from '@rspack/core';
import { globWithWorkspaceContext } from 'nx/src/utils/workspace-context';

import { createRspackConfig } from '../../utils/create-rspack-config';
import { getCopyPatterns } from '../../utils/get-copy-patterns';
import { normalizeAssets } from '../../utils/normalize-assets';
import { WebpackExecutorSchema } from './schema';

export default async function* runExecutor(options: WebpackExecutorSchema, context: ExecutorContext) {
  const entryFiles = await globWithWorkspaceContext(
    context.root,
    typeof options.entryFiles === 'string' ? [options.entryFiles] : options.entryFiles,
  );
  for (const entryFile of entryFiles) {
    yield bundleEntryFile(entryFile, options, context);
  }
}

async function bundleEntryFile(
  entryFile: string,
  options: WebpackExecutorSchema,
  context: ExecutorContext,
): Promise<{ success: boolean }> {
  logger.info(`Memory usage: ', ${JSON.stringify(process.memoryUsage(), undefined, 2)}`);

  logger.info('\n============================================================');
  logger.info(`Bundling ${entryFile}`);

  const projectRoot = context.projectsConfigurations.projects[context.projectName!].root;
  const relativeEntryFile = path.relative(projectRoot, entryFile);
  const { dir: entryDir, name: entryName } = path.parse(relativeEntryFile);

  const project = context.projectGraph.nodes[context.projectName!];
  const sourceRoot = path.join(context.root, project.data.sourceRoot!);
  const outputPath = path.join(context.root, options.outputPath, entryName);

  const config = createRspackConfig({
    context: context.root,
    copyPatterns: getCopyPatterns(normalizeAssets(options.assets, context.root, sourceRoot)),
    devtool: options.sourceMap === 'hidden' ? 'hidden-source-map' : options.sourceMap ? 'source-map' : false,
    entry: {
      [`${entryDir}/${entryName}`]: entryFile,
    },
    minimize: options.optimization ?? false,
    mode: options.mode ?? 'production',
    outputPath,
    tsConfig: options.tsConfig,
  });

  let compiler: Compiler | undefined = rspack(config);
  try {
    const stats = await promisify(compiler.run.bind(compiler))();
    if (!stats) {
      throw new Error('Compiler stats not available');
    }

    const statsOptions = compiler.options.stats;
    const printedStats = stats.toString(statsOptions === true ? 'normal' : statsOptions === false ? 'none' : statsOptions);
    if (printedStats) {
      logger.log(printedStats);
    }

    // Output stats for analyzing if desired
    if (options.stats) {
      await writeFile(path.join(outputPath, 'stats.json'), JSON.stringify(stats.toJson()), 'utf8');
    }

    return {
      success: !stats.hasErrors(),
    };
  } catch (error) {
    logger.error(error);
    return { success: false };
  } finally {
    await promisify(compiler.close.bind(compiler))();
    compiler = undefined;
  }
}
```

On every compilation, the memory increases. On my laptop that's fine and everything works super fast (macbook pro m3 max 36gb memory), but on our CI machines, this script just gets stuck. (every compilation takes longer than the previous one until it gets stuck and the runner times out)

We switched from webpack and in all of our services with less lambdas this was acceptable but in one of our services this happens ):
