### ISSUE TITLE
contenthash is unstable

### ISSUE THREAD

**Issue by ityuany** [web-infra-dev/rspack#3174]
### System Info

System： mac os 13.3.1
npmPackages: pnpm 8.1.0

### Details

[复现仓库](https://github.com/sheinsight/rspack-demo-contenthash)

反复多次执行 npm run build  ， 进入 detail/statics 文件夹， 观察 chunk-shineout.[contenthash:8].js 的文件名 hash 值是不稳定的， 每次都会产生变化

### Reproduce link

https://github.com/sheinsight/rspack-demo-contenthash

### Reproduce Steps

1. pnpm i
2. pnpm run build

**Comment by ityuany** [comment]
不好意思， 刚刚的仓库包含了 内网域名， 已经被移除，  已经更新了最新的仓库地址

**Comment by ahabhgk** [comment]
contenthash 计算目前确实有些问题，可以开启 `optimization.realContentHash = true` 来 workaround，现在不会默认开启，0.2 后会默认生产开启

**Comment by hoivee** [comment]
@ahabhgk 开启realContentHash后contenthash依旧会出现不稳定的情况，build三次之后三个js文件格式化之后的对比：

![image](https://github.com/web-infra-dev/rspack/assets/14292623/a7ad41b4-661d-488f-b50d-e2c5e3972937)

![image](https://github.com/web-infra-dev/rspack/assets/14292623/59edcf92-3b1d-4800-9576-0cc5747bc509)

rspack 版本: 0.1.11

**Comment by ahabhgk** [comment]
@hoivee 可以提供个复现demo不？

**Comment by shaodahong** [comment]
ye, same issue

**Comment by hoivee** [comment]
@ahabhgk 貌似是 @rspack/plugin-node-polyfill 导致的，就用上面的dome，使用了 @rspack/plugin-node-polyfill 插件后，chunk-vendors.[contenthash].js 文件就会出现 contenthash 值不稳定的问题

**Comment by ahabhgk** [comment]
> @ahabhgk 貌似是 @rspack/plugin-node-polyfill 导致的，就用上面的dome，使用了 @rspack/plugin-node-polyfill 插件后，即使开启了 realContentHash， chunk-vendors.[contenthash].js 文件也会出现 contenthash 值不稳定的问题

使用 @rspack/plugin-node-polyfill 导致 realContentHash 不稳定的问题与当前这个 issue 不是同一个问题，单独开了一个 #3202，https://github.com/web-infra-dev/rspack/pull/3204 会修掉

**Comment by hoivee** [comment]
@ahabhgk 还排查到除了 @rspack/plugin-node-polyfill 会导致 contenthash 值不稳定外，sass-loader + sass-resources-loader也会导致 contenthash 不稳定，复现仓库 https://github.com/hoivee/demo-rspack-contenthash

**Comment by hardfist** [comment]
> @ahabhgk 还排查到除了 @rspack/plugin-node-polyfill 会导致 contenthash 值不稳定外，sass-loader + sass-resources-loader也会导致 contenthash 不稳定，复现仓库 [hoivee/demo-rspack-contenthash](https://github.com/hoivee/demo-rspack-contenthash)

is this ok when set realContentHash:true

**Comment by hoivee** [comment]
> > @ahabhgk 还排查到除了 @rspack/plugin-node-polyfill 会导致 contenthash 值不稳定外，sass-loader + sass-resources-loader也会导致 contenthash 不稳定，复现仓库 [hoivee/demo-rspack-contenthash](https://github.com/hoivee/demo-rspack-contenthash)
> 
> is this ok when set realContentHash:true
即使设置 realContentHash 为 true 之后，contenthash 依旧不稳定，复现仓库可以复现

**Comment by ahabhgk** [comment]
@hoivee realContentHash 不稳定和 contenthash 不稳定不是一个问题，另开了个 issue #3379，#3380 会修掉

**Comment by hardfist** [comment]
@ityuany  @ahabhgk can this be closed now?

**Comment by ahabhgk** [comment]
No, it can be workaround by real content hash, but it's different with this issue

**Comment by ahabhgk** [comment]
Just take another look in this reproduce, upgrade to the latest rspack and less, the contenthash is stable now, so I'll close this issue now, feel free to re-open it if you have any further questions
