### ISSUE TITLE
Misleading error message when request is `""`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#3180]
### System Info

system unrelated

### Details

```js
import {} from '';

```

rspack will throw error: 
```bash
'should have context', crates/rspack_plugin_externals/src/plugin.rs:126:16

```

### Reproduce Steps

1. npm create @rspack/cli@latest
2. change index.js to above
3. pnpm build

**Comment by hardfist** [comment]
bump

**Comment by Hamzakh777** [comment]
assign it to me @hardfist

**Comment by hardfist** [comment]
thanks

**Comment by Hamzakh777** [comment]
@hardfist it seems now the compiler is throwing a different error: 
![Screenshot 2023-09-28 at 16 47 07](https://github.com/web-infra-dev/rspack/assets/40059557/faeb8f42-e2fe-47ca-b34b-2e6efd7ae82a)
This is coming from this line: https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/normal_module_factory.rs#L247
Should we use `ModuleFactoryResult` to return the error instead?

**Comment by IWANABETHATGUY** [comment]
duplicated with #5082
