### ISSUE TITLE
[Tracking]: Release Workflow

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3184]
### What subject does this issue tracking?

# [Subject]
current release workflow is buggy and not DX friendly, we plan to improve release workflow progressively
```[tasklist]
### Tasks
- [x] Fix nightly release broken due to missing changeset
- [ ] https://github.com/web-infra-dev/rspack/issues/2502
```

**Comment by Boshen** [comment]
I think I need to automate the Tuesday releasing steps.

**Comment by Boshen** [comment]
This is kind of stable right now so closing. We revisit and improve the workflow in the future.
