### ISSUE TITLE
debug build crashing in arco-pro

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#3185]
### System Info

None

### Details

It's crashing on this [file](https://github.com/nuysoft/Mock/blob/refactoring/dist/mock.js), due to swc parser blowing the stack while parsing some machine generated code (it has a super deep binary expression chain), which in turn blew up the stack for tokio / rayon.

--

Action: remove mock.js from arco-pro example

### Reproduce Steps

None

**Comment by hardfist** [comment]
fixed in #3195
