### ISSUE TITLE
[bug] console['error']('hello') will be compiled to：console('hello')

### ISSUE THREAD

**Issue by zhangliu** [web-infra-dev/rspack#3190]
### System Info

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 AMD EPYC 7Y83 64-Core Processor
    Memory: 12.26 GB / 32.79 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - /usr/local/nvm/versions/node/v16.18.0/bin/npm

### Details

console['error']('hello') will be compiled to：console('hello')：

before compilation：
![image](https://github.com/web-infra-dev/rspack/assets/5234349/1b53cb58-3f75-4445-a119-50cb3895ad02)

after compilation:
![image](https://github.com/web-infra-dev/rspack/assets/5234349/1c3276d5-6208-4327-907a-e80159586c6f)

### Reproduce Steps

1. Create an rspack project with @rspack/cli@0.0.0-canary-7b11360-20230510090658

2. write code like: 
```js
console.log(console['error'], 'xxxxx');
```

3. build code; then you can get content: 
```js
console.log(console, 'xxxxx');
```

**Comment by hardfist** [comment]
why do you use canary version here?

**Comment by zhangliu** [comment]
On the latest version（0.1.11）, the issue still exists!
to reproduce the problem，polyfillPlugin need to be configured：
```
const PolyfillPlugin = require('@rspack/plugin-node-polyfill');

module.exports = {
  plugins: [new PolyfillPlugin()].filter(Boolean),
}
```

**Comment by zhangliu** [comment]
another question：
<img width="980" alt="image" src="https://github.com/web-infra-dev/rspack/assets/5234349/f656fe9c-7d2e-429c-802d-7d39684c72a8">

```...compiler.options.builtins?.provide,``` should on the line below ```...provide```

so user can customize the provide option

**Comment by hardfist** [comment]
seems related to #3187

**Comment by hardfist** [comment]
> another question： <img alt="image" width="980" src="https://user-images.githubusercontent.com/5234349/238921814-f656fe9c-7d2e-429c-802d-7d39684c72a8.png">
> 
> `...compiler.options.builtins?.provide,` should on the line below `...provide`
> 
> so user can customize the provide option

can you help fix it

**Comment by zhangliu** [comment]
no problem, i will try
