### ISSUE TITLE
Analyzer should follow 1-pass visit

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3205]
### What problem does this feature solve?

Currently, dependency analysis costs n-passes. From the perspective of performance, we should change it to a single pass.

### What does the proposed API of configuration look like?

Not related: Internal API

**Comment by Boshen** [comment]
Can you link some source code for this problem? I want to study the code a bit.

**Comment by h-a-n-a** [comment]
> Can you link some source code for this problem? I want to study the code.

Currently, Rspack does not granular split analysis, which would cause a bunch of overhead. https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs

**Comment by h-a-n-a** [comment]
bump
