### ISSUE TITLE
support mini-css-extract-plugin 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3210]
### What problem does this feature solve?

there are lots of difference between experiments.css and mini-css-extract-plugin which makes migrate old application hard

### What does the proposed API of configuration look like?

compatible with mini-css-extract-plugin

**Comment by TimPetricola** [comment]
Hi there! I'm very interested in this feature (to be able to use `html-inline-css-webpack-plugin`). Do you know if it's still planned @hardfist ?

**Comment by hardfist** [comment]
yes it is still on the plan

**Comment by Narretz** [comment]
Blocked (at least) by https://github.com/web-infra-dev/rspack/issues/3519

**Comment by chenjiahan** [comment]
This issue is currently a critical blocker for Rsbuild to unify the CSS implementation.

**Comment by JSerFeng** [comment]
mini-css-extract-plugin needs:
- loaderContext.importModule (Almost done)
- create custom runtime template and runtime modules from JS (not ready yet)
- create custom dependencies from JS (not ready yet)

We are working on it

**Comment by xc2** [comment]
bump

**Comment by OskarLebuda** [comment]
@JSerFeng @hardfist any updates? 
Without this feature we cannot migrate to rspack :(

**Comment by xc2** [comment]
> @JSerFeng @hardfist any updates? Without this feature we cannot migrate to rspack :(

hi there, per discord thread, it's being blocked by newTreeshaking implementation and might land in next two weeks.

ref: https://discord.com/channels/977448667919286283/1221151979871666208/1221477773902872606

**Comment by OskarLebuda** [comment]
> > @JSerFeng @hardfist any updates? Without this feature we cannot migrate to rspack :(
> 
> hi there, per discord thread, it's being blocked by newTreeshaking implementation and might land in next two weeks.
> 
> ref: https://discord.com/channels/977448667919286283/1221151979871666208/1221477773902872606

I see the threat thanks 🙏🏻
