### ISSUE TITLE
simplify nodejs profile process

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3247]
### What problem does this feature solve?

when we met performance  problems on  js thread  we need to use nodejs profile to analyze, but it's not easy to generate nodejs profile right now. so we need a better way to generate nodejs profile

### What does the proposed API of configuration look like?

rspack build --profile to generated a cpu-profile

**Comment by sladyn98** [comment]
@hardfist This is marked as a good first issue, I could give this a shot if there is nothing blocking it

**Comment by hardfist** [comment]
thanks in advance

**Comment by hardfist** [comment]
you can take vites implementation for reference

**Comment by sladyn98** [comment]
@hardfist Is there a link to the PR for that (vites implementation)

**Comment by hardfist** [comment]
> @hardfist Is there a link to the PR for that (vites implementation)

https://github.com/vitejs/vite/blob/e444375d34db1e1902f06ab223e51d2d63cd10de/packages/vite/bin/vite.js#L47

**Comment by sladyn98** [comment]
@hardfist Thanks I understood, just a couple of questions. 
a) Would we want a new script called node.js inside the `bin` directory that would implement the node profiler
b) Or would we just add functionality for profiling nodejs inside `vite.js`
Thanks in advance

**Comment by hardfist** [comment]
@sladyn98  do you still work on this?

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
we are making a redesign about how rspack profile work
