### ISSUE TITLE
Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter  

### ISSUE THREAD

**Issue by zhangliu** [web-infra-dev/rspack#3263]
### System Info

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 124.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.3
  npmPackages:
    @rspack/cli: latest => 0.1.11 

### Details

throw error when visit page:
```js
Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter
    at main.js:26813:20
    at ./src/marked.js (main.js:26814:3)
    at __webpack_require__ (main.js:26896:33)
    at fn (main.js:26972:10)
    at ./src/App.tsx (main.js:26831:1)
    at __webpack_require__ (main.js:26896:33)
    at fn (main.js:26972:10)
    at ./src/main.tsx (main.js:26860:38)
    at __webpack_require__ (main.js:26896:33)
    at main.js:28136:27
```

### Reproduce link

https://github.com/zhangliu/rspack-reports/tree/main/packages/ab-marded-error

### Reproduce Steps

1. run `npm i && npm run dev`
2. open chrome console，and you will see the error infomation.

**Comment by hardfist** [comment]
confirmed it's interop bug. cc @underfin

**Comment by underfin** [comment]
This need implement `__webpack_exports__`

**Comment by underfin** [comment]
Duplicated of https://github.com/web-infra-dev/rspack/issues/2222, please track here.
