### ISSUE TITLE
Core-js imports should not be transpiled

### ISSUE THREAD

**Issue by janmeier** [web-infra-dev/rspack#3267]
### System Info

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 14.90 GB / 31.08 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
  npmPackages:
    @rspack/cli: nightly => 0.0.0-canary-1c6a3dd-20230521164529 

### Details

When including core-js polyfills to support older browser versions (in my case `safari>=12`) I get the error `Uncaught TypeError: $ is not a function`. 

According to https://github.com/zloirock/core-js/issues/912, this is because core-js should not be transpiled.

In webpack we fix this by adding `exclude: [path.resolve(__dirname, 'node_modules')],` to the babel-loader. The same should be possible in rspack, according to https://github.com/web-infra-dev/rspack/pull/1353, so I tried both 
```
 {
  test: /\.js$/,
  include: [path.resolve(__dirname, 'src')],
  type: "javascript/auto",
}
```
and
```
 {
  test: /\.js$/,
  exclude: [path.resolve(__dirname, 'node_modules')],
  type: "javascript/auto",
}
```

But no luck - It seems like the default transforms in rspack are still being applied.

### Reproduce link

https://github.com/janmeier/rspack-corejs

### Reproduce Steps

* Run `pnpm run build`
* Open `webpack-dist/index.htm` in the browser
* `globalThis` object is logged
* Open `rspack-dist/index.html` in the browser
* `Uncaught TypeError: $ is not a function`

**Comment by hyf0** [comment]
blocked by #3067.

**Comment by h-a-n-a** [comment]
bump

**Comment by hardfist** [comment]
should be fixed in builtin:swc-loader
