### ISSUE TITLE
Treeshaking support `Decl::Using`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3280]
@IWANABETHATGUY I'll create an issue for this.

_Originally posted by @hyf0 in https://github.com/web-infra-dev/rspack/pull/3279#discussion_r1203579443_

**Comment by IWANABETHATGUY** [comment]
more context: 
1. tc39 proposal https://github.com/tc39/proposal-explicit-resource-management
2. swc related pull request https://github.com/swc-project/swc/pull/7322

**Comment by hardfist** [comment]
close for stale
