### ISSUE TITLE
rspack panics with `not a valid expression` with uuid-like values in `builltin.define`

### ISSUE THREAD

**Issue by sebvilhelm** [web-infra-dev/rspack#3297]
### System Info

System:

	OS: macOS 12.6.6
	CPU: (8) arm64 Apple M1 Pro
    Memory: 309.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

Binaries:

    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/46543_1684936297222/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/46543_1684936297222/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman

Browsers:

    Chrome: 113.0.5672.126
    Safari: 16.5

npmPackages:

    @rspack/cli: ^0.1.11 => 0.1.12 

### Details

Able to reproduce on my local machine (specs above), and CI Alpine Linux.

```
[rspack-cli] [Error: error[internal]: 88aa83392a-572612741d is not a valid expression.
Raw: panicked at '88aa83392a-572612741d is not a valid expression', /Users/runner/.cargo/registry/src/index
.crates.io-6f17d22bba15001f/swc-0.261.21/src/config/mod.rs:1751:22
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.

   0: _napi_register_module_v1
   1: <unknown>
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: _napi_register_module_v1
  19: _napi_register_module_v1
  20: <unknown>
  21: _napi_register_module_v1
  22: _napi_register_module_v1
  23: _napi_register_module_v1
  24: __pthread_deallocate

] {
  code: 'GenericFailure'
}
ERROR: "build:rspack" exited with 2.
```

### Reproduce link

https://github.com/sebvilhelm/rspack-not-valid-expr-repro

### Reproduce Steps

1. add to rspack config:

```js
builtins: {
	define: {
		ARTIFACT_ID: "88aa83392a-572612741d"
	}
}
```

2. Add `ARTIFACT_ID` somewhere in the entry.
3. run build step
4. panic.

**Comment by sebvilhelm** [comment]
@suxin2017 the repro is simplified, this value is actually coming from `process.env` in my case.

**Comment by suxin2017** [comment]
> @suxin2017 the repro is simplified, this value is actually coming from `process.env` in my case. But thanks for the suggestion!

I tried webpack with your warehouse and had the same problem
```

SyntaxError: Identifier directly after number (1:3)
    at Object.pp$4.raise (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:3460:15)
    at Object.pp.readNumber (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:5270:61)
    at Object.pp.getTokenFromCode (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:5087:19)
    at Object.pp.readToken (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:4815:17)
    at Object.readToken (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn-import-assertions/lib/index.js:45:24)
    at Object.pp.nextToken (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:4806:17)
    at Object.pp.next (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:4767:10)
    at Object.pp$5.parseParenAndDistinguishExpression (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:2921:12)
    at Object.pp$5.parseExprAtom (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:2803:43)
    at Object.pp$5.parseExprSubscripts (/Users/wx/codes/rspack-not-valid-expr-repro/node_modules/acorn/dist/acorn.js:2636:21) {
  pos: 3,
  loc: Position { line: 1, column: 3 },
  raisedAt: 3
}
```
```
  plugins:[new DefinePlugin({
    ARTIFACT_ID: "88aa83392a-572612741d", 
  })],
```
```
JSON.stringify("88aa83392a-572612741d")
                           ^^replace process env
```

**Comment by suxin2017** [comment]
> @suxin2017 the repro is simplified, this value is actually coming from `process.env` in my case. But thanks for the suggestion!
> 
> EDIT: seems like this works:
> 
> ```js
> ARTIFACT_ID: `"${ARTIFACT_ID}"`
> ```

Yeah, that should be okay, too

**Comment by sebvilhelm** [comment]
@suxin2017 Oh, I see why this used to work in the webpack setup: the entry had `process.env.ARTIFACT_ID` directly instead of relying on `DefinePlugin`. Hm.

**Comment by hardfist** [comment]
you should use JSON.stringify when you want to inject string
```js
mdule.exports = {
define: {
   ARTIFACT_ID:JSON.stringify(ARTIFACT_ID)
}
```

**Comment by sebvilhelm** [comment]
@hardfist Oh, I see, looks like that is in the webpack docs: https://webpack.js.org/plugins/define-plugin

> Note that because the plugin does a direct text replacement, the value given to it must include actual quotes inside of the string itself. Typically, this is done either with alternate quotes, such as '"production"', or by using JSON.stringify('production').

Not a bug, then, I guess!

Thank you both @hardfist @suxin2017
