### ISSUE TITLE
bug #2988 persists for more complicated packages.

### ISSUE THREAD

**Issue by aliveornot** [web-infra-dev/rspack#3306]
### System Info

same as #2988 

### Details

in #2988, I reported a bug about importing a very simple package that does not depend on other packages. And for such a simple package, it has been resolved. But same bug persists for a more complicated package that has dependencies.

I changed original "simple-demo-package" to "inline-style-prefixer" and the same bug appears. Here you can see a screenshot with single reverse-slashes.

![image](https://github.com/web-infra-dev/rspack/assets/60848153/c6b2922c-844c-4f5b-8941-dfb8b00099d4)

### Reproduce link

https://github.com/aliveornot/rspack-module-id-bug

### Reproduce Steps

same as #2988. the repo is updated to import and export inline-style-prefixer instead of simple-demo-package.

**Comment by n3rds-inc** [comment]
stuck with the same problem. any progress?

**Comment by aliveornot** [comment]
Of course, here are the simplest repos that I can think of:
https://github.com/aliveornot/rspack-bug-d-drive
https://github.com/aliveornot/rspack-bug-c-drive

The first one(d-drive) is the main repo, which imports a package from the other c-drive repo.  Just clone them into  d:\\src and c:\\src respectively.

Your example seems pretty much like the original issue #2988. The problem happens when importing a "package that imports other packages" from cross-drive. And I used `inline-style-prefixer` as an example of that in c-drive repo.

- I used the latest ver of rspack
![image](https://github.com/web-infra-dev/rspack/assets/60848153/3f925920-a456-4639-9df0-d997ea7b4f60)

- screenshot from the result bundle. (You can check the single slash in the second highlight, while the first highlight shows double backslashes.)
![image](https://github.com/web-infra-dev/rspack/assets/60848153/b9a9660e-4865-4660-b266-4945957a37da)

**Comment by aliveornot** [comment]
Just checked v0.2.5 out, and it works! Thank you so much!
