### ISSUE TITLE
Support passing serializable options to builtin loaders

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3310]
### What problem does this feature solve?

Currently, we does not support inline queries for builtin loader, which makes it hard for us to configure it on in the request.
Ideally, builtin loaders should support passing queries.

### What does the proposed API of configuration look like?

```
// Public API
require("bulitin:swc-loader?jsx=true")
```

**Comment by h-a-n-a** [comment]
bump

**Comment by hardfist** [comment]
still not supported? @h-a-n-a
