### ISSUE TITLE
Support option interoperation for builtin loaders

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3311]
### What problem does this feature solve?

Builtin loaders should accept unserializable options. Rspack should convert these options to a reference table and return an cache friendly identifier. This also allows inline loaders to consume the options with inline requests, for example:
```
require("builtin:swc-loader??module.rule[1]")
```

### What does the proposed API of configuration look like?

Not related

**Comment by hardfist** [comment]
never seen this api before，any webpack link

**Comment by h-a-n-a** [comment]
> never seen this api before，any webpack link

`builtin:xxx` is what Rspack provides. Webpack does not offer these kinds of loaders.

**Comment by h-a-n-a** [comment]
> is loader.ident used in some real world application? I have never seen this usage before?

No, it's not. Only loader developers may consume this field for hacks. This field is not supposed to be used for users.

**Comment by hardfist** [comment]
bump

**Comment by h-a-n-a** [comment]
Implemented in https://github.com/web-infra-dev/rspack/pull/3988 using JS loader runner.
