### ISSUE TITLE
Inject css into the DOM like style loader in development mode

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#3319]
### What problem does this feature solve?

https://github.com/webpack-contrib/css-loader#recommend like css loader recommends, in development mode inject css into DOM works faster, but currently rspack extract css in any mode

### What does the proposed API of configuration look like?

Keep the present behavior in production mode, but inject css into DOM like style loader's behavior in development mode.

**Comment by hardfist** [comment]
this behavior should be left to framework like cra or modernjs on top of rspack

**Comment by alexander-akait** [comment]
I think you don't need `style-loader`, it should be done by frameworks/your application, in future webpack CSS also will be "extracted" in any mode

**Comment by faga295** [comment]
What makes me wonder is why the css-loader recommend users use style loader in development mode, is it outdate?And does rspack have any options to control whether extract css or inject it into dom.

**Comment by hardfist** [comment]
minicss-extract-plugin has some hmr problem when used in development mode https://github.com/web-infra-dev/rspack-website/issues/294

**Comment by alexander-akait** [comment]
@faga295 Because CSS is still under experiments, in future it will be recommended pipeline
