### ISSUE TITLE
aliasedRequire support

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3346]
The following code exists in moment.js. When I build using rspack, I found that './locale/xxx' is not being bundled.

<img width="531" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/2e6d9ce6-b738-41a2-9d46-4ef66ae3748d">

**Comment by 9aoy** [comment]
in webpack:
<img width="806" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/c53ac210-7078-48a6-8b1d-1bb10ebd2bda">

![e1a00158-af39-45b6-8c35-a7ef91c99dad](https://github.com/web-infra-dev/rspack/assets/22373761/584a82d4-630a-467f-8e78-001745007852)

**Comment by hardfist** [comment]
bump

**Comment by chenjiahan** [comment]
@bvanjoi I have tried Rspack 0.5.4 in Rsbuild, and `moment/locale` still can not be bundled.

see: https://github.com/chenjiahan/rspack-repro-moment-locale
