### ISSUE TITLE
output.filename 的 [name] 占位符貌似和webpack不太一致，webpack是优先entry name，没有的话就chunk id，  rspack好像就直接输出文件路径了

### ISSUE THREAD

**Issue by crazyxhz** [web-infra-dev/rspack#3371]
### System Info

 System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 141.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Safari: 16.0

### Details

output.filename 的 [name] 占位符貌似和webpack不太一致，webpack是优先entry name，没有的话就chunk id，  rspack好像就直接输出文件路径了

### Reproduce Steps

![image](https://github.com/web-infra-dev/rspack/assets/6551888/5dd4f144-a279-40ab-b2cb-ec6d6c8babce)
rspack vs webpack
![image](https://github.com/web-infra-dev/rspack/assets/6551888/16f4d4da-5c9d-4f8f-b2d8-55352bdf8750)

**Comment by hardfist** [comment]
@hyf0 is this solved?

**Comment by hyf0** [comment]
@crazyxhz Rspack 现在仅支持 chunkIds: `named` 选项，请把 webpack 配置成对等的值后再进行比较

**Comment by hardfist** [comment]
@JSerFeng help check whether this is solved?

**Comment by JSerFeng** [comment]
It should be the same by default since version 0.5.0
