### ISSUE TITLE
function type `module.rule.resource`

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3383]
### What problem does this feature solve?

```
{
   module: {
    rules: [{
       use: ['less-loader'],
       type: 'css/modules',
       resource: (path: string) => {
         if (!/\.less$/.test(path)) {
           return false;
         }
         if (/node_modules/.test(path)) {
            return /\.module\.\w+$/i.test(path);
         }
        return !/\.global\.\w+$/.test(path);
        }
     }]
   }
}
```

### What does the proposed API of configuration look like?

https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/declarations/WebpackOptions.d.ts#L269

**Comment by h-a-n-a** [comment]
I've tested in `vue-loader`, it seems supported.

**Comment by 9aoy** [comment]
😂 I only looked at the document and thought it was not supported.
