### ISSUE TITLE
`devtool: false` not work

### ISSUE THREAD

**Issue by southorange0929** [web-infra-dev/rspack#3392]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 64.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.volta/tools/image/node/16.14.0/bin/node
    npm: 8.3.1 - ~/.volta/tools/image/node/16.14.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Firefox: 113.0.2
    Safari: 16.4

### Details

By default,field `devtool` is `false` which should not to generator `sourcemap` files. I think the `false` value has been ignored with rust binding options.
Only `Omit<DevTool,false>` support.

https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_binding_options/src/options/mod.rs#L164

### Reproduce Steps

```shell
pnpm create rspack@latest
pnpm run build
```

**Comment by Jdruwe** [comment]
I also seem to experience this issue

**Comment by faga295** [comment]
https://github.com/web-infra-dev/rspack/blob/40fef768bfe8d9c495f6a6ea5c7a13c073517ecd/packages/rspack-cli/src/rspack-cli.ts#L167-L169
Maybe we should remove these code

**Comment by southorange0929** [comment]
> https://github.com/web-infra-dev/rspack/blob/40fef768bfe8d9c495f6a6ea5c7a13c073517ecd/packages/rspack-cli/src/rspack-cli.ts#L167-L169
> 
> 
> This is caused by these code

actually not, `node_binding_options` not support all of `sourcemap` type.You can find this logic with source code.

**Comment by hardfist** [comment]
@southorange0929  ![image](https://github.com/web-infra-dev/rspack/assets/8898718/894da710-6c08-4d9c-b4a9-421c5a646638)
I tested in latest version and it's working, please help check it in latest see whether this problems exists

**Comment by southorange0929** [comment]
> @southorange0929 ![image](https://user-images.githubusercontent.com/8898718/243241161-894da710-6c08-4d9c-b4a9-421c5a646638.png) I tested in latest version and it's working, please help check it in latest see whether this problems exists

Update `@rspack/cli`,it worked. But document told me that `devtool` set to `false` by default. 
<img width="849" alt="image" src="https://github.com/web-infra-dev/rspack/assets/32590310/49fb7a6c-dc8a-497a-b76b-769c493d33df">
 
Should update? Thanks

**Comment by hardfist** [comment]
the document needs update

**Comment by hardfist** [comment]
closed as it's a document problem and which is tracked in website
