### ISSUE TITLE
Support Function of `Rule.use`

### ISSUE THREAD

**Issue by sxzz** [web-infra-dev/rspack#3407]
### What problem does this feature solve?

Be consistent with Webpack behavior

Example: https://github.com/unjs/unplugin/blob/856b0736dbb658ffd6cf32d246359683b622b36f/src/webpack/index.ts#LL68C4-L68C4

### What does the proposed API of configuration look like?

 Type declaration of Webpack:
```ts
(data: {
	resource: string;
	realResource: string;
	resourceQuery: string;
	issuer: string;
	compiler: string;
}) => RuleSetUseItem[]
```

**Comment by faga295** [comment]
Can you assign this to me? @hardfist
