### ISSUE TITLE
Support ResolvePlugin

### ISSUE THREAD

**Issue by sxzz** [web-infra-dev/rspack#3408]
### What problem does this feature solve?

Be consistent with Webpack behavior

Example: https://github.com/unjs/unplugin/blob/bb2444b1f3140968723584dedfe8d5fbec1ee2fb/src/webpack/index.ts

### What does the proposed API of configuration look like?

See https://webpack.js.org/configuration/resolve/#resolveplugins

**Comment by hardfist** [comment]
cc @Boshen, unplugin need resolvePlugin to make rspack support work

**Comment by hardfist** [comment]
resolve plugin seems has large cost than resolve hooks, we may support resolve first and see whether we could provide better unplugin support. cc @h-a-n-a @ahabhgk

**Comment by sxzz** [comment]
bump

**Comment by JounQin** [comment]
So what's current status of this feature now? Is it an accepted feature to be added into rspack core?

**Comment by sxzz** [comment]
bump

**Comment by hardfist** [comment]
@sxzz we already support resolve hook and make resolveId works in unplugin now, can you help take a look https://github.com/unjs/unplugin/pull/388
