### ISSUE TITLE
Set watch:false doesn't work

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3421]
### System Info

-

### Details

Expected behavior 

Set watch:false should disable rspack watch mode.

Actually behavior

The watch mode  also work

### Reproduce Steps

-

**Comment by suica** [comment]
I cannot reproduce this with `42c51b23`, which is a rather new version of code. 

Procedure:

1. `cd ./examples/angular/`. And in the `rspack.config.js`, there is already a `watch: false`, so no need to change config for it.
2. `pnpm run build`

After building, the thread exits and the actual output is:
```
> node scripts/build.js

rspack compiled successfully in 5987 ms
undefined
```

Any further idea for reproducing this issue?  😲

**Comment by LingyuCoder** [comment]
Seems had been fixed. I will close this issue. If this issue occurs again, just reopen it
