### ISSUE TITLE
Interopability issue when running in ESM output mode

### ISSUE THREAD

**Issue by blinkzz** [web-infra-dev/rspack#3423]
### System Info

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 14.13 GB / 15.61 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.5.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
  npmPackages:
    @rspack/cli: nightly => 0.0.0-canary-40fef76-20230604005453 

### Details

When rspack is configured in ESM mode and has dependencies set as external, some modules may fail due to interopability wrapper causing lose of `defaut` export

In this example `axios` package is taken, which at this moment is being packaged as CommonJS

Here is source code

```
import axios from 'axios';

axios.get(`https://jsonplaceholder.typicode.com/posts/1`)
  .then(response => response.data)
  .then(console.log)
```

Webpack output is:

```
/* harmony import */ var axios__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! axios */ "axios");


axios__WEBPACK_IMPORTED_MODULE_0__["default"].get(`https://jsonplaceholder.typicode.com/posts/1`)
  .then(response => response.data)
  .then(console.log)
})();
```

Rspack output is:

```
var _axios = __webpack_require__.ir(__webpack_require__("axios"));
_axios.default.get(`https://jsonplaceholder.typicode.com/posts/1`).then((response)=>response.data).then(console.log);
```

And while webpack gives us correct result after running this complied code in Node.JS environment

![image](https://github.com/web-infra-dev/rspack/assets/17931300/fe4e11b1-8de6-40d8-8737-9163d3767527)

Rspack fails due to `axios` instance not being present as `default` export

![image](https://github.com/web-infra-dev/rspack/assets/17931300/8dadc074-3d92-4b6a-8769-52eec1fc9196)

If we look further into what object is being created by rspack for `axios` import, we notice that it does import everything from `axios` module and puts it as `default`, which requires us to use `axios.default.get` syntax in order to access `default` export the same way webpack does

```
[Module: null prototype] {
  Axios: [class Axios],
  AxiosError: [Function: AxiosError] { from: [Function (anonymous)] },
  AxiosHeaders: [class AxiosHeaders] { [Symbol(internals)]: { accessors: [Object] } },
  Cancel: [Function: CanceledError],
  CancelToken: [class CancelToken],
  CanceledError: [Function: CanceledError],
  HttpStatusCode: {
    ...
  },
  VERSION: '1.4.0',
  all: [Function: all],
  default: <ref *1> [Function: wrap] {
    constructor: [Function: wrap],
    request: [Function: wrap],
    getUri: [Function: wrap],
    delete: [Function: wrap],
    get: [Function: wrap],
    head: [Function: wrap],
    options: [Function: wrap],
    post: [Function: wrap],
    postForm: [Function: wrap],
    put: [Function: wrap],
    putForm: [Function: wrap],
    patch: [Function: wrap],
    patchForm: [Function: wrap],
    defaults: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object]
    },
    interceptors: { request: [InterceptorManager], response: [InterceptorManager] },
    create: [Function: create],
    Axios: [class Axios],
    CanceledError: [Function: CanceledError],
    CancelToken: [class CancelToken],
    isCancel: [Function: isCancel],
    VERSION: '1.4.0',
    toFormData: [Function: toFormData],
    AxiosError: [Function: AxiosError] { from: [Function (anonymous)] },
    Cancel: [Function: CanceledError],
    all: [Function: all],
    spread: [Function: spread],
    isAxiosError: [Function: isAxiosError],
    mergeConfig: [Function: mergeConfig],
    AxiosHeaders: [class AxiosHeaders] { [Symbol(internals)]: [Object] },
    formToJSON: [Function (anonymous)],
    HttpStatusCode: {
      ...
    },
    default: [Circular *1]
  },
  formToJSON: [Function (anonymous)],
  isAxiosError: [Function: isAxiosError],
  isCancel: [Function: isCancel],
  mergeConfig: [Function: mergeConfig],
  spread: [Function: spread],
  toFormData: [Function: toFormData]
}
```

And if we were to remove `__webpack_require__.ir` from output code of rspack, it starts working as intended

### Reproduce link

https://github.com/blinkzz/rspack-interop-issue

### Reproduce Steps

1. Run `npm run build` or `yarn build` to build reproduction example
2. Try running both examples via node rspack-dist/main.js and webpack-dist/main.js

**Comment by underfin** [comment]
closed at https://github.com/web-infra-dev/rspack/pull/3567
