### ISSUE TITLE
setup 中 return 的全局变量不会被 builtins.provide 捕获，报 xxx is not defined 错误

### ISSUE THREAD

**Issue by Lionad-Morotar** [web-infra-dev/rspack#3433]
### System Info

  System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 37.24 GB / 63.71 GB
  Binaries:
    Node: 16.19.0 - ~\OneDrive\Code\NodeJS\node.EXE
    Yarn: 1.22.19 - D:\node-modules\node_modules\yarn.CMD
    npm: 9.4.0 - ~\OneDrive\Code\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.891.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: ^0.2.0 => 0.2.0
    @rspack/plugin-html: ^0.2.0 => 0.2.0

### Details

这样会报错：

```vue
<template>
  <component :fetch="cyber.request" />
</template>

<script lang="ts">
export default {
  setup() {
    return {
      cyber,
    };
  },
};
</script>
```

增加一行 console.log 可以解决这个错误：

```vue
<template>
  <component :fetch="cyber.request" />
</template>

<script lang="ts">
export default {
  setup() {
    console.log('cyber', cyber)
    return {
      cyber,
    };
  },
};
</script>
```

### Reproduce Steps

示例代码比较简单，就不贴复现了。

**Comment by hyf0** [comment]
请提供一个最小可复现的用例仓库

**Comment by Lionad-Morotar** [comment]
```vue
<script lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
let title: string = "Rspack + Vue";
export default {
  components: { HelloWorld },
  setup() {
    // console.log(name);
    return {
      title,
      name,
    };
  },
};
</script>
<template>
  <div>
    <span>my-vars:</span>
    <span>{{ name.get() }}</span>
  </div>
  <HelloWorld :msg="title + name.get()" />
</template>
```

上述代码会导致编译问题：

![image](https://github.com/web-infra-dev/rspack/assets/26913795/72fe5e04-a11e-4b20-b6c5-62136d73f5d2)

换成这种写法就编译通过了：

```diff
export default {
  setup() {
-  // console.log(name);
+ console.log(name);
    return {
      title,
      name,
    };
  },
};
```
