### ISSUE TITLE
Support vue-loader for Vue@2.x

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3434]
### What problem does this feature solve?

Add support for vue-loader@15 for Vue@2.x.

### What does the proposed API of configuration look like?

Checkout the list at https://github.com/rspack-contrib/rspack-vue-loader/issues/1

**Comment by h-a-n-a** [comment]
bump

**Comment by Narretz** [comment]
I'm confused. The docs say rspack already supports vue 2 with vue-loader 15: https://www.rspack.dev/guide/vue.html#vue2

Will your fork improve the support?

**Comment by hardfist** [comment]
> I'm confused. The docs say rspack already supports vue 2 with vue-loader 15: [rspack.dev/guide/vue.html#vue2](https://www.rspack.dev/guide/vue.html#vue2)
> 
> Will your fork of vue-loader improve the support?

we support vue2 by vue-style-loader way but not support extract css now, we need to improve vue-loader@2 to support experiments.css to support exract css like what we do to vue-loader@3, but we don't have manpower now
