### ISSUE TITLE
Support `builtins.styledComponents`

### ISSUE THREAD

**Issue by Asuka109** [web-infra-dev/rspack#3444]
### What problem does this feature solve?

The [babel-plugin-styled-components](https://www.npmjs.com/package/babel-plugin-styled-components) package provides compile-time optimization and server-side rendering support for [styled-components](https://styled-components.com/). To bring it into Rspack, we need a new option field like `builtins.styledComponents`.

> This plugin is a highly recommended supplement to the base styled-components library, offering some useful features:
>
> - consistently hashed component classNames between environments (a must for server-side rendering)
> - better debugging through automatic annotation of your styled components based on their context in the file system, etc.
> - various types of minification for styles and the tagged template literals styled-components uses.

I plan to contribute this feature by integrating the crate [swc_plugin_styled_components](https://crates.io/crates/swc_plugin_styled_components) into `rspack_plugin_javascript`.

### What does the proposed API of configuration look like?

```ts
module.exports = {
  builtins: {
    styledComponents: {
      ssr: true,
      displayName: false,
      meaninglessFileNames: ["index", "styles"]
    }
  }
}
```

**Comment by hyf0** [comment]
After discussions, we are going to support similar features in the `buitins:swc-loader`. You could see the details at #3382.

I'm going to close this issue for we won't support `styledComponents` in this way.

**Comment by jasperlin451** [comment]
@hyf0 `@swc/plugin-styled-components` is loaded as an experimental plugin to swc. It seems like experimental plugins are currently disabled in rspack. Are there plans to change that?

https://www.npmjs.com/package/@swc/plugin-styled-components

**Comment by hyf0** [comment]
> It seems like experimental plugins are currently disabled in rspack.

Yeah. We haven't figured everything out.
