### ISSUE TITLE
support entryOption hook

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3448]
### What problem does this feature solve?

implement https://webpack.js.org/api/compiler-hooks/#entryoption

### What does the proposed API of configuration look like?

same as webpack

**Comment by annanShao** [comment]
@hardfist  Could you assign it to me if there are no blockers?

**Comment by hardfist** [comment]
@annanShao  thanks in advance

**Comment by annanShao** [comment]
https://github.com/web-infra-dev/rspack/blob/42dd56d942986e9951e69e67db87c3f3c71add45/packages/rspack/src/config/types.ts#LL72C1-L72C1

Do we not support dynamic entry, which is supported in webpack?

**Comment by hardfist** [comment]
we can support it

**Comment by hardfist** [comment]
landed in #3499
