### ISSUE TITLE
WASM plugin support for builtin:swc-loader

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3451]
### What problem does this feature solve?

Support customized wasm plugin for swc-loader

### What does the proposed API of configuration look like?

Follow the original swc-loader: https://swc.rs/docs/configuration/compilation#jscexperimentalplugins

**Comment by hyf0** [comment]
I guess we need a way to tell users the `swc_core` version Rspack used.

https://swc.rs/docs/plugin/selecting-swc-core

**Comment by hardfist** [comment]
bump

**Comment by chenjiahan** [comment]
SWC Wasm support has been released, so I will close this issue
