### ISSUE TITLE
Watch config file and auto restart on change

### ISSUE THREAD

**Issue by lsdsjy** [web-infra-dev/rspack#3463]
### What problem does this feature solve?

When using `rspack serve`, changes to config file can automatically trigger a restart of dev server (like `vite dev`).

### What does the proposed API of configuration look like?

N/A

**Comment by hardfist** [comment]
related to https://github.com/webpack/webpack-cli/issues/15 
there're some blockers on webpack side https://github.com/webpack/webpack-cli/issues/15#issuecomment-1533625016
@alexander-akait any plan for https://github.com/webpack/webpack-cli/issues/15 ?

**Comment by th3fallen** [comment]
On the topic it would be amazing if we could provide a list of files to the watch config and cause a restart of the dev server if they change like .env files for example

**Comment by h-a-n-a** [comment]
The behavior is the same with webpack.
