### ISSUE TITLE
Allow output.filename to be a function

### ISSUE THREAD

**Issue by janmeier** [web-infra-dev/rspack#3483]
### What problem does this feature solve?

Webpack supports passing a function to `output.filename`, to be able to dynamically determine the output filename of an entry point.

In our case we are including some entries automagically using the `builtins.html` so we would like to include `[contenthash]` in the file name, but other bundles are being consumed by external scripts, so we would like to keep the output name static.

### What does the proposed API of configuration look like?

From https://webpack.js.org/configuration/output/#outputfilename

```
module.exports = {
  //...
  output: {
    filename: (pathData) => {
      return pathData.chunk.name === 'main' ? '[name].js' : '[name]/[name].js';
    },
  },
};
```

**Comment by janmeier** [comment]
If you can give me a couple of pointers about where to start, I would be happy to contribute this feature

**Comment by hyf0** [comment]
Reading https://web-infra-dev.github.io/rspack-dev-guide/ would be a good start.

**Comment by IronGeek** [comment]
Related to this issue, if it's not too much to ask, it would be nice if the other `output.*Filename` options (such as `output.assetModuleFilename`, `output.chunkFilename`, etc...) could be set as function too 🙏

**Comment by lippzhang** [comment]
please assign this to me

**Comment by lippzhang** [comment]
please assige this to me

**Comment by hardfist** [comment]
bump

**Comment by Hamzakh777** [comment]
assign it to me @hardfist

**Comment by pratyushseq** [comment]
bump!

**Comment by branchseer** [comment]
@hardfist Is anyone working on this? If not, I'd like to give it a try.

**Comment by hardfist** [comment]
@branchseer are you still working on it?

**Comment by branchseer** [comment]
@hardfist Yes
