### ISSUE TITLE
Add support for topLevelAwait option in experiments

### ISSUE THREAD

**Issue by KrzysztofZawisla** [web-infra-dev/rspack#3493]
### What problem does this feature solve?

Adds compatibility to topLevelAwait option from wepback

### What does the proposed API of configuration look like?

```ts
const config = {
  experiments: {
    topLevelAwait: true,
  },
};
```

**Comment by hyf0** [comment]
This issue blocks migration of following Webpack tests

- https://github.com/webpack/webpack/blob/main/test/configCases/graph/issue-11770/webpack.config.js

**Comment by hardfist** [comment]
duplicate of #3889
