### ISSUE TITLE
Webpack compression plugin working

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rspack#3497]
### What problem does this feature solve?

Have static assets compressed by default in the server and not compress it on the fly in the server.

### What does the proposed API of configuration look like?

Webpack have the plugin compression-webpack-plugin that compress to Brotli and Gzip.

https://webpack.js.org/plugins/compression-webpack-plugin/#root

It is not working by now. This is the error.

[rspack-cli] [Error: napi error: GenericFailure - TypeError: Cannot read properties of undefined (reading 'tap')

**Comment by jerrykingxyz** [comment]
It seems that `compilation.hooks.statsPrinter` and `stats.hooks.print` are not supported.

**Comment by faga295** [comment]
I’m willing to work for this

**Comment by hardfist** [comment]
bump

**Comment by JoseBuendiaDigio** [comment]
This is now working!.

I think that https://github.com/web-infra-dev/rspack/pull/3722 solved it
