### ISSUE TITLE
vue2 problems

### ISSUE THREAD

**Issue by Ttou** [web-infra-dev/rspack#3500]
### System Info

System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/Library/Caches/fnm_multishells/68744_1686532466569/bin/node
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/68744_1686532466569/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 16.5

### Details

1. sometimes start app will report an error

![image](https://github.com/web-infra-dev/rspack/assets/4298437/30b62855-637a-49d5-89ef-8aac907a5aac)

2. font icon can't show when use `On-demand Import`

![image](https://github.com/web-infra-dev/rspack/assets/4298437/f4a4ef21-290d-4b6d-a4b4-28a79cb17440)

![image](https://github.com/web-infra-dev/rspack/assets/4298437/ce92b2a3-d938-4d85-a727-c8cef57059a3)

### Reproduce link

https://github.com/Ttou/rspack-issue-font

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by hardfist** [comment]
@Ttou do you still see this problem?

**Comment by Ttou** [comment]
Take your time. You don't have to deal with it.
