### ISSUE TITLE
How to get the same functionality as `tsconfig.json#paths` in Rspack

### ISSUE THREAD

**Issue by tmzdy888** [web-infra-dev/rspack#3501]
### System Info

win10 nodejs18 webpack5+
rspack最新版本

### Details

因为ts.config.js中配置了path: @:"..x/xx"类似这样。ts中引入就不需要写路径前缀，只需要import xx from "@/xx/xx"
而不用带后缀.ts，
但rspack识别不了。不带后缀的引入，也识别不了带@带前缀的路径。
这个我在webpack是正常运行的。

### Reproduce Steps

在ts.config.js中配置：
    "paths": {
      "@/*": ["./xx/*"]
    }
然后在ts中使用import xx from "@/test"
就会报错找不到文件。我找了你们的文档，实在找不到兼容的文档说明。特意来提问。

**Comment by tmzdy888** [comment]
我关闭，不看好这个项目，已经删除。社区全是bug。

**Comment by hardfist** [comment]
https://www.rspack.dev/zh/config/resolve.html#resolvetsconfigpath 你试了这个吗？webpack识别tsconfig里的paths也是需要通过插件支持的
