### ISSUE TITLE
Support `splitChunks.cacheGroups.{cacheGroup}.type`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3504]
Blocks

- https://github.com/webpack/webpack/tree/main/test/configCases/css/conflicting-order
- https://github.com/webpack/webpack/tree/main/test/configCases/css/urls

# Guidance

https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouptype

TODO

---

It blocks

- https://github.com/web-infra-dev/rspack/blob/aa9d7409a4dc6a28180cec04777b8d505f3dabdf/webpack-test/configCases/split-chunks/module-type-filter

**Comment by suxin2017** [comment]
Maybe we can migrate those two test cases over, actually I've already done most of it (including type filtering 😅)
