### ISSUE TITLE
nwjs/node-webkit target support

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#3508]
### What problem does this feature solve?

Compile for usage in WebKit and uses JSONP for chunk loading. Allows importing of built-in Node.js modules and [nw.gui](http://docs.nwjs.io/en/latest/) (experimental)

### What does the proposed API of configuration look like?

`target: "nwjs"` and `target: "node-webkit"`

**Comment by prakhar3062** [comment]
I would like to contribute

**Comment by ahabhgk** [comment]
Thanks in advance

**Comment by chenjiahan** [comment]
Resolved by https://github.com/web-infra-dev/rspack/pull/6880
