### ISSUE TITLE
Dynamic import can be ignored by `/* webpackIgnore: true */`

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3513]
### What problem does this feature solve?

Support ignore dynamic import.
``` js
import(/* webpackIgnore: true */ "./a.js");
```

### What does the proposed API of configuration look like?

Support ignore dynamic import.
``` js
import(/* webpackIgnore: true */ "./a.js");
```

**Comment by hardfist** [comment]
bump
