### ISSUE TITLE
compilation.entries.get('main') does not exist

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3517]
### System Info

all

### Details

When trying to leverage the CommonJSUsageWarnPlugin as part of the Angular CLI we discovered that this function is missing. 

### Reproduce Steps

enable CommonJSUsageWarnPlugin

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by hardfist** [comment]
this api should be supported in 1.0.0
