### ISSUE TITLE
processAssets hook missing stage 4000

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3518]
### System Info

all

### Details

When trying to use the AnyComponentStyleBudgetChecker plugin as part of Angular CLI support we discovered that one of the stages is missing [Compilation.PROCESS_ASSETS_STAGE_ANALYSE = 4000](https://github.com/webpack/webpack/blob/f921a5baca9c7d200eee8204fafaaaf36b7c1451/lib/Compilation.js#LL5302C1-L5302C49) - AnyComponentStyleBudgetChecker.

### Reproduce Steps

enable AnyComponentStyleBudgetChecker

**Comment by zackarychapple** [comment]
still waiting on this one

**Comment by zackarychapple** [comment]
bump

**Comment by hardfist** [comment]
cc @ahabhgk

**Comment by ahabhgk** [comment]
Fixed, hook with any stage is now available in >= v0.6.0
