### ISSUE TITLE
registerLoader throws error

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3519]
### System Info

all

### Details

When working with Angular and trying to use the MiniCssExtractPlugin we found that registerLoader throws an error. 

`webpack.util.serialization.registerLoader(/^mini-css-extract-plugin\//, trueFn);` throws error `TypeError: Cannot read properties of undefined (reading 'registerLoader')` - MiniCssExtractPlugin

### Reproduce Steps

enable the MiniCssExtractPlugin

**Comment by Narretz** [comment]
Still happens.

The docs say we don't need MiniCssExtractPlugin, but in certain configs you cannot use experiments: css (also per docs), which means we cannot use module type: css. Ergo, we need MiniCssExtractPlugin

**Comment by Narretz** [comment]
This problem is already tracked here as well: https://github.com/web-infra-dev/rspack/issues/3158

**Comment by alexanderyarm** [comment]
Basically any usage of `css-loader` leads to this problem. 
Once you add `css-loader` with custom configuration, then css is not extracted into files => you need to use `mini-css-extract-plugin` => getting an error

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by edbzn** [comment]
Hi, any progress with this?

**Comment by xc2** [comment]
I'm closing this issue as an alternative css extract plugin has been provided.
