### ISSUE TITLE
finishModules returning empty array

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3520]
### System Info

all

### Details

When testing the StylesWebpackPlugin we found that the finishModules hook returns an empty array of modules, this behavior is different than webpack for the same project. 

### Reproduce Steps

enable the StylesWebpackPlugin on the Angular16 cli example

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by xc2** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/18117084/b30cddfd-08b3-40ec-ae2f-fb3aceeaffb4)

`finishModules` gives module list now. 

btw, i failed to find the usage of `finishModules` in https://github.com/angular/angular-cli/blob/16.0.x/packages/angular_devkit/build_angular/src/webpack/plugins/styles-webpack-plugin.ts
