### ISSUE TITLE
compilation.chunks.add is not a function

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3521]
### System Info

all

### Details

As part of the build from Angular CLI there is a step that injects scripts directly into the bundle via a configuration in the angular.json this leverages the compilation.chunks.add function which is currently not available.

### Reproduce Steps

add a script file to the angular.json file in an angular cli based rspack build

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by h-a-n-a** [comment]
Fixed in v1.0.0-alpha.0
