### ISSUE TITLE
NormalModuleReplacementPlugin is not a constructor

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3522]
### System Info

all

### Details

As part of the environment file replacement in the Angular cli there is the call below: 

`new NormalModuleReplacementPlugin(new RegExp('^' + key.replace(/[.*+\-?^${}()|[\]\\]/g, '\\$&') + '$'), value).apply(compiler);`

### Reproduce Steps

Enable file replacement in the Angular CLI based builder for Rspack

**Comment by yharaskrik** [comment]
Note on this one: It is not limited to just Angular, in an Nx workspace when we are using the webpack executor currently with say Nest, we can use fileReplacements as well (which we do). I THINK this is the only issue that is preventing us from using rspack in production for our nest servers.

**Comment by hardfist** [comment]
> Note on this one: It is not limited to just Angular, in an Nx workspace when we are using the webpack executor currently with say Nest, we can use fileReplacements as well (which we do). I THINK this is the only issue that is preventing us from using rspack in production for our nest servers.

it seems alias works too https://github.com/nrwl/nx-labs/pull/231/files

**Comment by yharaskrik** [comment]
> > Note on this one: It is not limited to just Angular, in an Nx workspace when we are using the webpack executor currently with say Nest, we can use fileReplacements as well (which we do). I THINK this is the only issue that is preventing us from using rspack in production for our nest servers.
> 
> @yharaskrik it seems alias works too https://github.com/nrwl/nx-labs/pull/231/files

I am actually just looking into that, that PRs change isn't live yet it seems and I am trying to follow to associated Rspack issue saying that a relative alias key works but I cannot get it to work.

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
Very nice!  Thank you
