### ISSUE TITLE
processAssets custom stage number not supported

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#3528]
### System Info

all

### Details

Inside of the index-html-webpack-plugin for [Angular CLI ](https://github.com/angular/angular-cli/blob/6bebc457769846ecbc0fc84a630969c64715948a/packages/angular_devkit/build_angular/src/tools/webpack/plugins/index-html-webpack-plugin.ts#L45)there is an apply call that leverages custom processAssets stages. `Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE + 1` this is not currently supported in Rspack.

### Reproduce Steps

Using Angular builder for Rspack.

**Comment by hardfist** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by zackarychapple** [comment]
bump

**Comment by xc2** [comment]
bump

**Comment by hardfist** [comment]
@ahabhgk this should be resolved now?

**Comment by ahabhgk** [comment]
Yes, hook with any stage number supported in >= v0.6.0
