### ISSUE TITLE
An simple way to find out "Why this css content is rendered in this position of the css file?"

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3532]
I have met many style problems using Rspack with `experiments.css: true`. 

Bundling CSS doesn't have a specification, so it's hard to tell if the output of Rspack is wrong or correct(especially in a large-scale project). However, we need one to know if the result of Rspack is expected.

With the specification, we could emit more information as I did at #3531 to help explain the result if it is expected based on the output.

**Comment by hyf0** [comment]
It would be great for @alexander-akait to give some suggestions :).

**Comment by alexander-akait** [comment]
@hyf0 Yeah, CSS modules specification is old (https://github.com/css-modules/css-modules) and has some compatibility problems, I correctly understand that with normal CSS there are no problems? Maybe you can list of them? We have https://github.com/webpack/webpack/issues/14893 so we can connect issues and sync them. Write some simple spec :smile:

**Comment by hyf0** [comment]
@alexander-akait  Yeah.

> We don't know which module should be first, so we print a warning and try to find the best way,

Yeah. I have met the related error while studying using `mini-css-extract-plugin` and figure out why.

> because we can provide more verbose error - example of code how to fix it.

I don't think this problem is fixable in practice, especially for a project having 20k+ modules.

---

What I want is not to fix the "conflicts" but a specification about how Webpack resolves conflicts currently, so that I could use to explain why this CSS content is rendered in this position of the CSS file.

---

I also have a rough thought that using [`post_order`](https://github.com/webpack/webpack/blob/16143f5fa835ad8c7181b8aeedc52f9cdd0fd39d/lib/ModuleGraph.js#L105) to sort the CSS modules in chunks rather `post_order` per `ChunkGroup`. This strategy should have some traps I don't know yet.

**Comment by hyf0** [comment]
> We don't know which module should be first, so we print a warning and try to find the best way, this is not related only to splitChunks: false. 

I just look into your example. If I understand the algo of Webpack correctly. Your example would emit a CSS file

```css
// entry.css

/* Render a.css */

/* Render b.css */

```

without any warnings or errors.

> We don't know which module should be first

`a.css` should be the first. Because the `post_order` of `a.css` is before `b.css` in the `ChunkGroup(enrty)`.

**Comment by alexander-akait** [comment]
> I just look into your example. If I understand the [algo](https://github.com/webpack/webpack/blob/16143f5fa835ad8c7181b8aeedc52f9cdd0fd39d/lib/css/CssModulesPlugin.js#L385-L386) of Webpack correctly. Your example would emit a CSS file

There are other examples - https://github.com/webpack-contrib/mini-css-extract-plugin/tree/master/test/cases/ignoreOrder, we have more examples of the problem 

And yes we will use the first found module in rendering 

> a.css should be the first. Because the post_order of a.css is before b.css in the ChunkGroup(enrty)

Yes, but this is logic from our logic, but we don't know if the developer expects it or not this :smile: 

Also don't forget about `@import`, especial in nested files (i.e. `@import` inside `@import`)

**Comment by hyf0** [comment]
> Yes, but this is logic from our logic, but we don't know if the developer expects it or not this 😄

It's straightforward and I like this way. It makes me easy to explain to others the reason for CSS output. It just gets complicated with bundle splitting 😂.
