### ISSUE TITLE
Always get error with css syntax?

### ISSUE THREAD

**Issue by southorange0929** [web-infra-dev/rspack#3539]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.volta/tools/image/node/16.18.0/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.2.2 => 0.2.2 

### Details

Add a new picture to project, and use it with css syntax `background: url(./assets/1.jpg)`.
Then got some error info
<img width="1267" alt="image" src="https://github.com/web-infra-dev/rspack/assets/32590310/6cea4dfd-3540-45ee-9840-af9dc6e3562e">

rspack.config.js
```js
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  context: __dirname,
  entry: {
    main: "./src/main.jsx",
  },
  builtins: {
    html: [
      {
        template: "./index.html",
      },
    ],
  },
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [{ loader: "postcss-loader" }, { loader: "less-loader" }],
        type: "css",
      },
      {
        test: /\.module\.less$/,
        use: [{ loader: "postcss-loader" }, { loader: "less-loader" }],
        type: "css/module",
      },
      {
        test: /\.svg$/,
        use: "@svgr/webpack",
      },
      {
        test: /\.png$/,
        type: "asset",
      },
    ],
  },
};

```

### Reproduce Steps

1. create a new project with rspack
2. edit `rspack.config.js`  with my content
3. npm run dev
4. add a new picture to project and use it with css

**Comment by southorange0929** [comment]
https://github.com/web-infra-dev/rspack/issues/3554 may be a same issue.

**Comment by Lionad-Morotar** [comment]
I also used less-loader and imported SVG and PNG images. However, I used JS to import the SVG in the Vue SFC Script Block. Additionally, error still occurs even if I remove the imported images.

```json
// rsconfig.module.rules
[
  {
    test: /\.less$/,
    loader: "less-loader",
    type: "css",
  },
  {
    test: /\.s[ca]ss$/,
    use: [
      {
        loader: "sass-loader",
        options: {},
      },
    ],
    type: "css",
  },
  {
    test: /\.styl(us)?$/,
    loader: "stylus-loader",
    type: "css",
  },
  {
    test: /\.(png|jpe?g|gif|webp|ttf)(\?.*)?$/i,
    type: "asset",
  },
  {
    test: /\.svg/,
    type: "asset/resource",
  },
]
```

```js
// component.vue
import AddIcon from './assets/add.svg';
```

**Comment by hardfist** [comment]
bump
