### ISSUE TITLE
想请问一下，vue3+tsx 该如何配置？

### ISSUE THREAD

**Issue by 895046075** [web-infra-dev/rspack#3546]
从examples文件夹中看到了vue3+jsx的例子，但没找到vue3+tsx的例子，自己折腾了很久也没配出来，想请问一下是暂不支持vue3+tsx吗？若已能支持，能否补一个例子？ 非常感谢

**Comment by 895046075** [comment]
@suxin2017  非常感谢提供的demo，已能满足我的需要

**Comment by hardfist** [comment]
@suxin2017 可以考虑把这个加到rspack example里

**Comment by suxin2017** [comment]
> @suxin2017 可以考虑把这个加到rspack example里

👌

**Comment by suxin2017** [comment]
closed  https://github.com/web-infra-dev/rspack/pull/3578
