### ISSUE TITLE
support resolve.plugin or builtin support ModuleScopePlugin

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3548]
### What problem does this feature solve?

I want to use ModuleScopePlugin to restrict importing paths. In webpack, it's a resolve plugin. but in Rspack, we not support resolve plugin.
Is there any way to implement this function？ Is it necessary to make it builtin?

https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/ModuleScopePlugin.js

### What does the proposed API of configuration look like?

none

**Comment by hardfist** [comment]
close due to duplicate of #3408
