### ISSUE TITLE
Conflict Multiple assets emit different content to the same filename main.xxxxx.hot-update.js

### ISSUE THREAD

**Issue by Lionad-Morotar** [web-infra-dev/rspack#3554]
### System Info

```
  System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 28.16 GB / 63.71 GB
  Binaries:
    Node: 16.19.0 - ~\OneDrive\Code\NodeJS\node.EXE
    Yarn: 1.22.19 - D:\node-modules\node_modules\yarn.CMD
    npm: 9.4.0 - ~\OneDrive\Code\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.891.0), Chromium (114.0.1823.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: ^0.2.2 => 0.2.2
    @rspack/plugin-html: ^0.2.2 => 0.2.2
```

### Details

![image](https://github.com/web-infra-dev/rspack/assets/26913795/bd3e05c7-5419-4423-aa67-db8e5850268d)

### Reproduce Steps

使用热更新有概率触发这个问题，但目前不确定要怎么重现

**Comment by Lionad-Morotar** [comment]
设置 realContentHash 为 false 后，有一段时间没有出现过这个问题。稍晚有空我试试提供复现仓库

**Comment by Lionad-Morotar** [comment]
@h-a-n-a 和 https://github.com/web-infra-dev/rspack/issues/3539 是一个问题

【复现仓库 reproduce project】

https://github.com/Lionad-Morotar/reproduce-rspack-amulty-assets-chunk-emits-hmr-bug/settings

【复现步骤 steps】

```
1. pnpm install
2. pnpm serve
3. remove line 9 in test-page.vue, save to trigger hmr
4. restore step 3, save to trigger hmr
5. error occurred
```

![image](https://github.com/web-infra-dev/rspack/assets/26913795/1fe48d80-0f2a-40c5-9cb6-fcf5cc50474e)

**Comment by Lionad-Morotar** [comment]
@hyf0 Hello, may I ask if is this bug already in plan

**Comment by hyf0** [comment]
> @hyf0 Hello, may I ask if is this bug already in plan

Yes.
