### ISSUE TITLE
Wasm sideEffect analysis failed

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3561]
### System Info

Not related

### Details

SideEffect analysis will be failed.

### Reproduce Steps

code: 
```js
import init from "@swc/wasm-web";
init()
```

Reproduction steps:
1. Use the code above as an entry
2. use the production build(which sets the `optimization.sideEffects` to `true`)
3. See the problem in code
4. Setting the `optimization.sideEffects` to `false`
5. The problem is gone.

**Comment by h-a-n-a** [comment]
cc @zhmushan

**Comment by zhmushan** [comment]
[rspack_build_wasm.tar.gz](https://github.com/web-infra-dev/rspack/files/11767026/rspack_build_wasm.tar.gz)
