### ISSUE TITLE
Support `require.main`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#3562]
It blocks

- https://github.com/web-infra-dev/rspack/blob/1f1e267f29c376b4e9fa2e46c037eb91bb5a5f30/webpack-test/configCases/split-chunks-common/simple/index.js
- https://github.com/web-infra-dev/rspack/blob/aa9d7409a4dc6a28180cec04777b8d505f3dabdf/webpack-test/configCases/split-chunks-common/inverted-order
- https://github.com/web-infra-dev/rspack/blob/aa9d7409a4dc6a28180cec04777b8d505f3dabdf/webpack-test/configCases/split-chunks-common/correct-order

**Comment by hyf0** [comment]
I didn't find this on the Webpack documentation. Is this feature going to be deprecated? @alexander-akait

**Comment by hardfist** [comment]
it's a feature of nodejs commonjs module

**Comment by alexander-akait** [comment]
To be honestly I see `require.main` only one my life in real code :smile:
