### ISSUE TITLE
defineConfig MultiplyCompiler Type not export.

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3607]
### System Info

- 

### Details

MultiplyCompiler Type did not export, caused ts error. 

### Reproduce Steps

You can use a arrray to test type.

``` .ts
// rspack.config.ts
module.exports = [], // expect array shouldn't cause ts error.
```

**Comment by hyf0** [comment]
@underfin Would you mind describing the correct behaviors or giving the related code link of Webpack repo?

**Comment by suica** [comment]
Procedure to reproduce this issue:

Create a `test.js` under `examples/library`, with following content.
```
/** @type {import('@rspack/cli').Configuration} */
const test = [];
module.exports = test;
```

## Expected
No validation error.

## Actual
`const test = [];` fails to be validated, and displays error message.

## Solution
Change the definition of type `Configuration` in `packages/rspack/src/config/types.ts`, to `export type Configuration = MultiRspackOptions | RspackOptions;`

**Comment by underfin** [comment]
@suica I'm not clear description the issue, here should be add `MultiRspackOptions`  for `defineConfig`.
