### ISSUE TITLE
rspack.config.ts configuration error

### ISSUE THREAD

**Issue by ICJR** [web-infra-dev/rspack#3609]
### System Info

System:
OS: Windows 10 10.0.19045
CPU: (12) x64 Intel(R) Core(TM) i7
Memory: 20.73 GB / 31.91 GB
Binaries:
Node: 18.12.0 - C:\Program Files\n
npm: 9.2.0 - C:\Program Files\node
Browsers:
Edge: Spartan (44.19041.1266.0), C
Internet Explorer: 11.0.19041.1566

### Details

I've installed `ts-node` and converted my `rspack.config.js` file to a typescript file but I believe the docs are incorrect and ts support does not work with `export default`

[documentation](https://www.rspack.dev/config/#type-checking) shows configuration object being exported using `export = config` I don't think that's valid ( vscode throws an error as well ) 

When I use `export default config` I receive 
```
Configuration error:
- Unrecognized key(s) in object: 'default'
```

### Reproduce Steps

Create a rspack config using typescript
Build

**Comment by hyf0** [comment]
I could help you solve the issue with a long conversation, but the simplest way is to use `rspack.config.js`.

If you want type checking with `rspack.config.js`, add `@ts-check` and `@type {import('@rspack/cli').Configuration}`.

> https://www.rspack.dev/config/#type-checking

```js
// @ts-check

/** @type {import('@rspack/cli').Configuration} */
const config = {
  entry: {
    main: './src/index.js',
  },
};
module.exports = config;
```

**Comment by hyf0** [comment]
`exports = xxx` is a valid syntax in typescript. The error you met is probably caused by an improper `tsconfig.json`.

**Comment by hardfist** [comment]
we should support export default case in future, let me test whether https://github.com/web-infra-dev/rspack/pull/3222  fix it

**Comment by hardfist** [comment]
@ICJR  it's supported now, you can test on @rspack/cli@0.2.3-canary-bd53ec4-20230623050741
