### ISSUE TITLE
lint package for missing package

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3610]
we met missing dependencies problems many times  such as https://github.com/web-infra-dev/rspack/issues/3594, even we can disable hoisting to avoid some problems but not able to avoid all of them.
so we do need a tool to check whether we import dependency not listed in package.json.

it seems a good case for using https://github.com/Boshen/oxc here, @Boshen are you willing to accept implement this rule in oxc

**Comment by Boshen** [comment]
Why is this a linting problem? Why doesn't Rspack have an integration test to guard this problem?

**Comment by hardfist** [comment]
because devdep and dep is not isolated in node_modules

**Comment by Boshen** [comment]
I think we should fix the setup for integration tests in Rspack. But I'm open for suggestions on how to make a linter rule for these kind phantom dependency problems.

**Comment by hardfist** [comment]
https://github.com/webpack/webpack/blob/1e18b1d1c74e26a84e9adee519c045e2d8ed40a4/.eslintrc.js#L29 webpack also use lint to check this problem
