### ISSUE TITLE
rspack react-ts project integrate formily failed,less-loader resolve error occurred.（rspack的react-ts项目集成formily失败，less-loader出现解析错误）

### ISSUE THREAD

**Issue by codenoobforreal** [web-infra-dev/rspack#3612]
### System Info

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 583.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 3.6.0 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 16.5

### Details

Is it appropriate to use less-loader in this scenario?Am i use this loader correctly?Feel free to close this issue and treat it as a question.It would be great if you could offer some help.

在这种情况下使用less-loader合适吗?我使用它的方式正确吗?你可以随意结束这个issue，把它当作一个问题。如果你能提供一些帮助，那就更好了。

![image](https://github.com/web-infra-dev/rspack/assets/18373253/c2230e68-4e93-4e58-879d-106360c954be)

### Reproduce link

https://github.com/codenoobforreal/reproduce-tracker

### Reproduce Steps

1. yarn install
2. yarn workspace rspack-formily dev

**Comment by hardfist** [comment]
try remove `~` in `~antd/es/style`

**Comment by codenoobforreal** [comment]
> try remove `~` in `~antd/es/style`

I found an similar issue and a working solution in this [link](https://github.com/ant-design/pro-components/issues/4880) and tried to use `resolve.alias` to remove or replace `~` like what the answer did in the issue above.But there is some difference about `resolve.alias` between vite and rspack.Any advice to achieve it?

我在[这个链接](https://github.com/ant-design/pro-components/issues/4880)发现了一个类似的问题和可行的解决方案并尝试使用`resolve.alias`去移除`~`，就像上述问题中的回复所做的那样。但是`vite`和`rspack`在`resolve.alias`上有些不同。有什么实现它的建议吗?

**Comment by hardfist** [comment]
https://github.com/webpack-contrib/less-loader#webpack-resolver ～ is a deprecated behavior of less-loader and should be removed

**Comment by vagusX** [comment]
我也遇到了类似问题，可以考虑用 https://github.com/bundle-matters/less-plugin-module-resolver 把这个行为接管了，把 `~` alias 到 '' ?
