### ISSUE TITLE
Whether rspack supports LimitChunkCountPlugin to limit the number of packages

### ISSUE THREAD

**Issue by ty-concision** [web-infra-dev/rspack#3613]
### What problem does this feature solve?

While writing your code, you may have already added many code split points to load stuff on demand. After compiling you might notice that some chunks are too small - creating larger HTTP overhead. LimitChunkCountPlugin can post-process your chunks by merging them.

### What does the proposed API of configuration look like?

https://webpack.docschina.org/plugins/limit-chunk-count-plugin#root

**Comment by hyf0** [comment]
> Whether rspack supports LimitChunkCountPlugin to limit the number of packages

In general, we want to support all features of Webpack in Rspack. But currently, we don't have the manpower for supporting `LimitChunkCountPlugin`.

For a workaround, you should be able to use `optimization.splitChunks` to merge chunks manually to reduce the number of chunks.

**Comment by annanShao** [comment]
I would like to give it a shot, if it has no blocking.

**Comment by h-a-n-a** [comment]
> I would like to give it a shot, if it has no blocking.

@annanShao Assigned :-)

**Comment by hardfist** [comment]
fixed in #4384
