### ISSUE TITLE
在vue单文件组件中使用tsx语法会构建失败

### ISSUE THREAD

**Issue by pluto369** [web-infra-dev/rspack#3616]
### System Info

System:Win11
Browsers:Chrome: 114

### 使用tsx会构建失败
```tsx
<script setup lang="tsx">

function FCTest() {
  return <div>test</div>
}

</script>

<template>
  <h4>setip tsx</h4>
  <FCTest></FCTest>
</template>
```

### 使用jsx会构建成功
```tsx
<script setup lang="jsx">

function FCTest() {
  return <div>test</div>
}

</script>

<template>
  <h4>setip tsx</h4>
  <FCTest></FCTest>
</template>
```

### Reproduce link

https://github.com/pluto369/rspack-vue3-setup-tsx

### Reproduce Steps

1、pnpm i
2、pnpm run dev/pnpm run build

**Comment by pluto369** [comment]
## 补充System Info 
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 20.22 GB / 31.86 GB
  Binaries:
    Node: 20.2.0 - ~\AppData\Local\nvs\default\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 9.6.6 - ~\AppData\Local\nvs\default\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: ^0.2.3 => 0.2.3

**Comment by hardfist** [comment]
you need add following options to preset-typescript because preset-typescript doesn't recognize .vue extension by default
```js 
presets: [['@babel/preset-typescript', { allExtensions: true, isTSX: true }]],
```

**Comment by hardfist** [comment]
manually configure rspack | webpack project is painful and we're planning to provide cli tools for vue project in the future, cc @chenjiahan

**Comment by chenjiahan** [comment]
> manually configure rspack | webpack project is painful and we're planning to provide cli tools for vue project in the future

I will provide a guide about using [Modern.js Builder](https://modernjs.dev/builder) to build Vue 3 projects.

**Comment by pluto369** [comment]
> you need add following options to preset-typescript because preset-typescript doesn't recognize .vue extension by default
> 
> ```js
> presets: [['@babel/preset-typescript', { allExtensions: true, isTSX: true }]],
> ```
> 
> or you can use `experimentalInlineMatchResource` options, see #3622

感谢您的解答，已经可以正常构建了
