### ISSUE TITLE
dev下，esm的包不会自动按需加载

### ISSUE THREAD

**Issue by July-ing** [web-infra-dev/rspack#3625]
### System Info

 System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 11.04 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.2
    Safari Technology Preview: 14.1

### Details

现象：
![image](https://github.com/web-infra-dev/rspack/assets/26430264/764f9d42-9cb9-4071-8a46-ba34234cd7cb)

期望像 webapck 一样：
![image](https://github.com/web-infra-dev/rspack/assets/26430264/0e5360ca-c957-4338-b447-14497d3f0b11)

demo 中只是用 antd 举例，实际使用中依赖的三方包导出不规范， 如果使用 babel-import-plugin ，需要定义不同的customName

### Reproduce link

https://github.com/July-ing/rspack-demo

### Reproduce Steps

pnpm dev

**Comment by hardfist** [comment]
webpack默认也不会实现该功能，如果需要的话试试这个 https://www.rspack.dev/config/builtins.html#builtinspluginimport

**Comment by July-ing** [comment]
> webpack默认也不会实现该功能，如果需要的话试试这个 https://www.rspack.dev/config/builtins.html#builtinspluginimport

我用cra建的项目默认是支持这个功能的，就是上面第二张图，没有做任何额外的配置。builtins.import 现在无法满足我的诉求，因为需要定义不同的customName

**Comment by July-ing** [comment]
> webpack默认也不会实现该功能，如果需要的话试试这个 https://www.rspack.dev/config/builtins.html#builtinspluginimport

我又仔细看了下文档 我理解我们也是有这个能力的 但好像没有生效？https://www.rspack.dev/zh/guide/tree-shaking.html#basic-tree-shaking

**Comment by hardfist** [comment]
我没有在cra的文档上找到支持该功能，请提供可复现的cra的demo

**Comment by July-ing** [comment]
> 我没有在cra的文档上找到支持该功能，请提供可复现的cra的demo

https://github.com/July-ing/cra-demo

**Comment by hardfist** [comment]
经确认，这个其实是webpack的一个treeshaking优化，当手动配置 antd的package.json的sideEffects:true的时候，导入路径就变成了`antd/lib/index.js`，后续我们跟进下这个treeshaking优化

**Comment by hardfist** [comment]
bump

**Comment by pushkargupta9807** [comment]
bump
![image](https://github.com/web-infra-dev/rspack/assets/93791633/31c89cf3-657e-4cea-8613-26db5f4e1e8b)

**Comment by pushkargupta9807** [comment]
just a gentle nudge, @IWANABETHATGUY @hardfist on  this bug for an approx ETA . 
It is a major blocker for my experiment to transition to rspack and it would help me re-prioritise mu tasks.

**Comment by hardfist** [comment]
bump

**Comment by IWANABETHATGUY** [comment]
You can try 
0.4.0-canary-751d297-20231124070013

with config below: 

```diff

+experiments {
+   rspackFuture {
+     newTreeshaking: true   
+  }
+}
```
