### ISSUE TITLE
css HMR not working when css file name has contenthash

### ISSUE THREAD

**Issue by hoivee** [web-infra-dev/rspack#3629]
### System Info

System:
    OS: Linux 4.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 33.14 GB / 63.74 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @rspack/cli: 0.2.3 => 0.2.3

### Details

if set output filename or cssFilename cause css filename include contenthash, css HMR just not working

### Reproduce Steps

set output.finename  like 'static/js/[name].[contenthash].js' or set output.cssFilename like  'static/css/chunk.[name].[contenthash].css'

**Comment by hyf0** [comment]
Related Webpack issue: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/444.
