### ISSUE TITLE
HMR not working while use builtin:swc-loader

### ISSUE THREAD

**Issue by hoivee** [web-infra-dev/rspack#3633]
### System Info

System:
OS: Linux 4.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
Memory: 33.14 GB / 63.74 GB
Container: Yes
Shell: 5.8.1 - /usr/bin/zsh
Binaries:
Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
npmPackages:
@rspack/cli: 0.2.3 => 0.2.3

### Details

[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./src/test/Root.tsx is not accepted
Update propagation: ./src/test/Root.tsx -> ./src/test/app.ts

### Reproduce Steps

use builtin:swc-loader as js/ts loader

**Comment by hoivee** [comment]
@hyf0 reference: https://github.com/web-infra-dev/rspack/issues/3067 https://github.com/web-infra-dev/rspack/pull/3382

**Comment by hyf0** [comment]
Please provide a reproduction repo.

**Comment by hoivee** [comment]
@hyf0  use this https://github.com/web-infra-dev/rspack/tree/main/examples/builtin-swc-loader
and it's HMR not working
![image](https://github.com/web-infra-dev/rspack/assets/14292623/4d3dde12-47e3-456c-993f-fb8d08908267)

**Comment by hyf0** [comment]
Thanks for reporting. I think I know the cause. We will fix it soon.

**Comment by hyf0** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/49502170/3a37be43-b4ef-44c9-84e0-6ea0642e2359)
Please make `refresh: true` in development mode.

**Comment by hardfist** [comment]
bump, @hyf0 have you fixed it?

**Comment by hyf0** [comment]
> bump, @hyf0 have you fixed it?

I think it's not fixed. This is caused by that `builtin:swc-loader` transpile the input, so the builtin "react hmr runtime injector" doesn't detect the `jsx`.
