### ISSUE TITLE
Parsing error when using generic react component 

### ISSUE THREAD

**Issue by PIMBA** [web-infra-dev/rspack#3638]
### System Info

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 90.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - ~/.npm-global/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.0 - ~/Library/pnpm/pnpm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
  npmPackages:
    @rspack/cli: ^0.2.4 => 0.2.4

### Details

Using React component that props has generics got a tsx parssing error.
```
error[tsx]: TSX parsing error
  ┌─ src/index.tsx:8:11
  │
8 │   return <GProps<any>>child</GProps>;
  │           ^^^^^^ Unexpected token `GProps`. Expected jsx identifier
```

### Reproduce link

https://github.com/PIMBA/rspack-tests/tree/main/tsx-parsing-error

### Reproduce Steps

1. cd tsx-parsing-error
2. pnpm i
3. pnpx rspack dev

**Comment by hardfist** [comment]
can you paste the code to swc playground and see if it works

**Comment by PIMBA** [comment]
> can you paste the code to swc playground and see if it works

![image](https://github.com/web-infra-dev/rspack/assets/7321731/e0554dc3-2bc4-4c88-a4c8-4c3c9622a205)

it works.

**Comment by hyf0** [comment]
> can you paste the code to swc playground and see if it works

We should update  SWC to the latest version to see if the problem still exists.

**Comment by hardfist** [comment]
it's fixed in latest version, please check @PIMBA
