### ISSUE TITLE
Module resolving not works as same as webpack does while module path starts with a slash ('/')

### ISSUE THREAD

**Issue by PIMBA** [web-infra-dev/rspack#3640]
### System Info

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 62.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - ~/.npm-global/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.0 - ~/Library/pnpm/pnpm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
  npmPackages:
    @rspack/cli: ^0.2.4 => 0.2.4 

### Details

```typescript
import "/src/deps.tsx";
```
got an error:
```
error[internal]: Failed to resolve /src/deps.tsx in typescriptx|/.../rspack-test/module-path-starts-with-slash-error/src/index.tsx
```
That's make sense when importing an js module 'casue it's seems like an absolute path.
But css-loader will transpile `~/` to `/`, it works will in webpack but not working in rspack.

```css
@import `~/some/path/test.css`;
```

### Reproduce link

https://github.com/PIMBA/rspack-tests/tree/main/module-path-starts-with-slash-error

### Reproduce Steps

1. pnpm i
2. pnpm run dev
3. pnpm run webpack-dev

working with css-loader case see [here](https://github.com/PIMBA/rspack-tests/tree/main/css-loader-error)

1. pnpm i
2. pnpm run dev
3. pnpm run webpack-dev

**Comment by hardfist** [comment]
can you try webpack with set experiments.css:true, I think this is the same behavior with webpack
![image](https://github.com/web-infra-dev/rspack/assets/8898718/12d6b512-070e-45b9-a535-ed695813b74e)

**Comment by hardfist** [comment]
good to notice that the current rspack's css implementation  align with  webpack native css (not with css-loader, but you can still use css-loader in rspack)

**Comment by PIMBA** [comment]
> can you try webpack with set experiments.css:true, I think this is the same behavior with webpack ![image](https://user-images.githubusercontent.com/8898718/249670506-12d6b512-070e-45b9-a535-ed695813b74e.png)

just had time to test `experiments.css:true`...
I think it's still has some differences between rspack and webpack module resolution.
`@import '/style/some-file.css';`
works well on webpack with `experiments.css:true`:
![image](https://github.com/web-infra-dev/rspack/assets/7321731/93b75306-30cc-4013-af7e-7b03d7dffd5a)
 but got an error on rspack:
![image](https://github.com/web-infra-dev/rspack/assets/7321731/bc88ddb8-0adb-492e-b67d-3fc695c3b9f9)

**Comment by hardfist** [comment]
https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1446 it's because webpack set resolve.roots = [context] as default vaue, but rspack doesn't support roots yet

**Comment by PIMBA** [comment]
bump

**Comment by hardfist** [comment]
@Boshen another user met this issue, can you take a look

**Comment by Boshen** [comment]
Waiting for responses on https://github.com/web-infra-dev/rspack/pull/5572

I cloned the repo and tested the latest Rspack version, it throws the resolution error

```
ERROR in × Resolve error: Can't resolve '/Users/bytedance/github/rspack-tests/module-path-starts-with-slash-error/node_modules/.pnpm/@rspack+core@0.5.3/node_modules/@rspack/core/hot/dev-server.js' in '/
  │ Users/bytedance/github/rspack-tests/module-path-starts-with-slash-error'


ERROR in × Resolve error: Can't resolve '/Users/bytedance/github/rspack-tests/module-path-starts-with-slash-error/node_modules/.pnpm/
  │ @rspack+dev-server@0.5.3_@rspack+core@0.5.3_webpack-cli@5.1.4_webpack@5.88.0/node_modules/@rspack/dev-server/client/index.js?
  │ protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true' in '/Users/bytedance/
  │ github/rspack-tests/module-path-starts-with-slash-error'
```


if I add 

```
  resolve: {
    roots: ["/path/to/rspack-tests/module-path-starts-with-slash-error"]
  }
```

but oxc-resolver passes if I test it alone with `roots`.

**Comment by arjunsoundankar** [comment]
I am doing Migration from webpack.

import commonStyle from "/src/components/CommonStyle.module.css";

Resolve error: Can't resolve '/src/components/CommonStyle.module.css' in '/Users/sbc/new-app/src/components/NewCard'

**Comment by hardfist** [comment]
@PIMBA  this is fixed in latest alpha version, please try
