### ISSUE TITLE
vue使用history模式路由的时候，有路径的情况下开发环境刷新页面会404

### ISSUE THREAD

**Issue by Asarua** [web-infra-dev/rspack#3645]
### System Info

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/Library/Caches/fnm_multishells/44119_1687958603589/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/Library/Caches/fnm_multishells/44119_1687958603589/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.58
    Safari: 16.2
  npmPackages:
    @rspack/cli: latest => 0.2.4 

### Details

新建一个rspack最简单的vue项目，下载vue-router，定义路由，只要地址栏存在路由，刷新页面就会404，在hash路由模式下是没这个问题的

### Reproduce Steps

如上

**Comment by hardfist** [comment]
try this https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback

**Comment by BarrySong97** [comment]
should add this to docs

**Comment by hardfist** [comment]
> should add this to docs

https://www.rspack.dev/zh/config/dev-server.html#devserverhistoryapifallback

**Comment by collins401** [comment]
the same question, chaged config
```
{
   output: {
     publicPath: '/'
  }
}
```
is work
