### ISSUE TITLE
官网的「手动安装指南」的SplitChunksPlugin的文档是不是写错了,我按照文档配置没有和文档一样的构建结果

### ISSUE THREAD

**Issue by fuguid** [web-infra-dev/rspack#3646]
### System Info

 System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 26.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v14.18.1/bin/npm
    pnpm: 7.29.1 - ~/.nvm/versions/node/v14.18.1/bin/pnpm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
  npmPackages:
    @rspack/cli: latest => 0.2.4 

### Details

![image](https://github.com/web-infra-dev/rspack/assets/88193046/17216474-f1e3-45a4-a912-610a515f53c3)

### Reproduce Steps

![image](https://github.com/web-infra-dev/rspack/assets/88193046/3057d80d-488a-49c5-a2fa-e93c247865f5)

**Comment by hyf0** [comment]
请描述
- 你理解的文档的构建结果
- 你的构建结果
- 差异点

**Comment by z1258956799** [comment]
按照文档的配置
![image](https://github.com/web-infra-dev/rspack/assets/88193046/ceccad27-0d79-4fe1-afa4-44765a65a5f4)
![image](https://github.com/web-infra-dev/rspack/assets/88193046/ad0e0ab8-c454-4851-b5fc-be2effb3d4e7)
![image](https://github.com/web-infra-dev/rspack/assets/88193046/1996b4b6-7a0a-4140-a8d1-85164a2fd2da)

![image](https://github.com/web-infra-dev/rspack/assets/88193046/b347d3ea-be7d-4beb-95c9-535378f695bf)
官网的构建结果
![image](https://github.com/web-infra-dev/rspack/assets/88193046/224822a5-87ea-49ef-9cee-e772683bc093)
我的构建结果
![image](https://github.com/web-infra-dev/rspack/assets/88193046/d5354f03-2d6d-44f3-9777-34658a0a4619)
差异点:
插件SplitChunksPlugin并没有把 shared.js 分离到单独的 another~index.bundle.js 中

**Comment by hyf0** [comment]
相关的章节内容是从[这部分](https://webpack.js.org/guides/code-splitting/#splitchunksplugin)翻译过来的。在早先的版本 splitChunks 还没有支持 minSize 功能，结果是和文档一样的。后期加上 minSize 功能后，由于 minSize 的默认值限制，导致文档的事例产物不正确了。

Webpack 的用例使用的是 lodash，体积足够大所以打破了 minSize 的限制。

在用例和 Webpack 对齐后，我发现 Rspack 的产物和 Webpack 不一样，因此我创建了一个[用例仓库](https://github.com/hyf0/rspack-issue-3646)用来测试这个问题，等待这个问题修复后，我会修正官网文档。

**Comment by hyf0** [comment]
这个问题将会在下个版本修复，但是文档的更新会暂缓下，这其中牵涉到一些 chunk 命名逻辑的问题。

**Comment by hardfist** [comment]
@hyf0  any update?

**Comment by hyf0** [comment]
> @hyf0 any update?

working on it.

**Comment by fuguid** [comment]
It's now working as expected in the new version

**Comment by hyf0** [comment]
> It's now working as expected in the new version

Yes. I will fix the document soon.

**Comment by JSerFeng** [comment]
https://github.com/web-infra-dev/rspack-website/pull/507 文档修正，新加了 minSize: 1，来满足 splitChunks 最小体积要求
