### ISSUE TITLE
Remove hygiene at run_before_pass, it can improve peformance

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3650]
### System Info

-

### Details

The hygiene is very slow, it currently adds because the swc react refresh visitor depend on it, it can be strip it.

### Reproduce Steps

-

**Comment by underfin** [comment]
The visitor used `private_ident` and depend on `hygiene`, i can remove  `private_ident` and assign different name to avoid this.

**Comment by hyf0** [comment]
After investigating with @underfin , `private_ident!` could not be removed. Therefore, the `hygiene` pass is required and can not be removed.
