### ISSUE TITLE
更新"@rspack/cli": "0.2.4"后chunkhash无效

### ISSUE THREAD

**Issue by Ting-Code** [web-infra-dev/rspack#3653]
### System Info

更新"@rspack/cli": "0.2.4"后
配置output后chunkhash无效，[ext]作为文件夹无效

### Details

    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: '[ext]/[name]-[chunkhash][ext]',
      chunkFilename: '[ext]/[name]-[chunkhash][ext]',
      cssChunkFilename: '[ext]/[name]-[chunkhash][ext]',
      assetModuleFilename: '[ext]/[name]-[chunkhash][ext]'
    },
配置原来0.1.X版本可以生成类似.js/name-xxx.js文件
现在生成[ext]/name-[chunkhash].js
![image](https://github.com/web-infra-dev/rspack/assets/56524782/0bb7dfdc-5f69-4336-b215-5a3e43b88e11)

### Reproduce Steps

    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: '[ext]/[name]-[chunkhash][ext]',
      chunkFilename: '[ext]/[name]-[chunkhash][ext]',
      cssChunkFilename: '[ext]/[name]-[chunkhash][ext]',
      assetModuleFilename: '[ext]/[name]-[chunkhash][ext]'
    },

**Comment by hyf0** [comment]
我们废弃 `[ext]` 的支持，请参考 https://www.rspack.dev/zh/blog/announcing-0.2.html#breaking-changes

**Comment by Ting-Code** [comment]
祝福已收到，辛苦了

**Comment by hyf0** [comment]
我们文档有误，`[chunkhash]` 可以认为是不支持的，请使用 `[contenthash]`
