### ISSUE TITLE
custom worker syntax

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#3656]
### What problem does this feature solve?

custom worker syntax

### What does the proposed API of configuration look like?

`module.parser.javascript.worker`

https://webpack.js.org/configuration/module/#moduleparserjavascript:~:text=worker%3A%20%5B%27default%20from%20web%2Dworker%27%2C%20%27...%27%5D%2C%20//%20Customize%20the%20WebWorker%20handling%20for%20javascript%20files%2C%20%22...%22%20refers%20to%20the%20defaults.

**Comment by aweary** [comment]
not stale, need this for `AudioWorklet` support

**Comment by hardfist** [comment]
this seems landed in #6899
