### ISSUE TITLE
Feature Request: add a `source` getter on `JsStatsModule`

### ISSUE THREAD

**Issue by SukkaW** [web-infra-dev/rspack#3665]
### What problem does this feature solve?

I am adding a rspack unit test for one of my webpack loader projects, [`forgetti-loader`](https://github.com/SukkaW/forgetti-loader) (see commit https://github.com/SukkaW/forgetti-loader/commit/4620937e47a6cb6b50818a280cc33f5f45b8e4a9), and I want to make a snapshot from the output of one of the transformed modules.

However, rspack's stats API doesn't include the `source` field in the `stats.modules[]`.

### What does the proposed API of configuration look like?

Reading the individual output of each module can and will be very expensive, so the `stats.modules[].source` should only be included with a `verbose` stats preset, and it should be implemented as a getter so that it can be lazily evaluated.

**Comment by h-a-n-a** [comment]
Maybe blocked by https://github.com/web-infra-dev/rspack/issues/3795 depending on your usage
