### ISSUE TITLE
频繁出现 [rspack-cli] [Error: error[internal]: failed to guess mime type of "D:\\xxx.vue" ] {   code: 'GenericFailure' }

### ISSUE THREAD

**Issue by YatomigaAkashi** [web-infra-dev/rspack#3674]
### System Info

@rspack/cli  0.2.4
vue  2.7.14
vue-loader 15.10.1

### Details

在项目上反复运行 “rspack serve” 或 “rspack build”，会频繁出现 [rspack-cli] [Error: error[internal]: failed to guess mime type of "D:\\xxx.vue" ] {   code: 'GenericFailure' }报错导致编译无法通过，我想知道为什么有时候可以编译通过，而有时会编译失败并报这条错误

### Reproduce Steps

rspack serve 或 rspack build

**Comment by hardfist** [comment]
can you provide repro

**Comment by YatomigaAkashi** [comment]
抱歉，我无法提供一个简单的实现，当我使用vite替代它时可以正常工作。我将会在后续持续排查这个问题

**Comment by hyf0** [comment]
是不是配错规则了，这应该是进到 `type:asset` 处理的规则里了
![image](https://github.com/web-infra-dev/rspack/assets/49502170/98f534e4-77d1-4ca0-adf2-a5c41c9bd15c)

**Comment by YatomigaAkashi** [comment]
我确实发现我的 asset 的正则写错了，感谢您的信息
