### ISSUE TITLE
builtins.progress supports profile functionality like progressPlugin

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3678]
### What problem does this feature solve?

progressPlugin provides a nice summary of the build timings about build process which is useful for simple diagnostics
![image](https://github.com/web-infra-dev/rspack/assets/8898718/ae3e2cb7-d7a1-4a86-a9b0-bc10c67fb7d2)

https://webpack.js.org/plugins/progress-plugin/#:~:text=profile%20(boolean%20%3D%20false)%3A%20Tells%20ProgressPlugin%20to%20collect%20profile%20data%20for%20progress%20steps.

### What does the proposed API of configuration look like?

```js
module.exports = 
{
  builtins: {
     progress: { profile:true}
  }
}
```

**Comment by faga295** [comment]
I'm willing to work for this

**Comment by faga295** [comment]
bump
