### ISSUE TITLE
☂️ Iteration plan for Q3 (July - Sept)

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#3679]
### What subject does this issue tracking?

See https://github.com/web-infra-dev/rspack/issues/2048 for Q2 iteration plan.

This issue serves as an Epic to provide transparency for our community and collaborators, internal and external, informed about our current goals and timelines.

We will be actively working on the tasks listed below, which have been aligned with our goals for Q3 (July - Sept 2023).

If you see something that is not on this list but is strongly needed. Please write a detailed requirement on this issue if you feel the need for feature prioritization. Also, remember this is not a complete list, so please search for relevant issues beforehand.

For broader collaboration, you can also find us on [Discord](https://discord.com/invite/79ZZ66GH9E) if you need a quick chat.

---

The theme for Q3 is to make Rspack a super reliable compiler so all projects can be switched to Rspack with extreme confidence.

The reason for focusing on reliability is that we are now dogfooding Rspack over 100 active projects at ByteDance. The goal is to ensure Rspack compilation artifacts will **never ever** break production builds. Our top priority is to pass most of the conformance tests from webpack and [Modern.js](https://modernjs.dev):
* https://github.com/web-infra-dev/rspack/issues/3243

The situation is similar to how React needs to dogfood itself in its early days. 

For API compatibility with the ecosystem, we are going to provide a progress chart for our loader and plugin API development. Once the progress documentation is completed, we aim to provide full compatibility with [Modern.js Rspack mode](https://modernjs.dev/builder/en/guide/advanced/rspack-start.html) and pass all its E2E tests. We are confident that this approach will enable most of the ecosystem compatibility with a clear short-term goal.

To focus on the above key results for Q3, we formed two working groups: @web-infra-dev/rspack-ux and @web-infra-dev/rspack-dx.

The ux team is responsible for all end-user-related tasks and build artifacts. For example, tree shaking, bundle splitting, and runtime.

The dx team is responsible for all developer-facing related tasks, such as API, loaders, plugins, and build performance monitoring.

---

## July (Preparation)

* Pass over 50% of webpack tests
* Provide API development visibility
* Improve feature completeness and code quality of all core functionalities such as cjs/esm * interop, tree-shaking, custom runtime, and CSS-related issues
* Clean up and refactor outstanding issues related to APIs, hooks, loaders, and plugins

## August (Development)

* Complete APIs for [Modern.js Rspack mode](https://modernjs.dev/builder/en/guide/advanced/rspack-start.html)
* Finish artifact alignment between [Modern.js Rspack mode](https://modernjs.dev/builder/en/guide/advanced/rspack-start.html) and its original webpack mode. 
* Develop tools for triaging build artifact problems targeted toward huge projects (20k+ modules internal projects)

## September (Engagement)

* Actively engage with internal and community projects and make sure requirements are satisfied
* Fix outstanding and time-consuming tasks

---

# Champions

There are also a few large sub-projects that are assigned to a specific person, their progress will be hard to track other wise.

* incremental build @hardfist 
* https://github.com/web-infra-dev/rspack/issues/3158 - @zackarychapple 
* https://github.com/web-infra-dev/rspack/issues/1930 - @ScriptedAlchemy

**Comment by zackarychapple** [comment]
@Boshen should we add #1930 as the tracking issue for MF?

**Comment by Boshen** [comment]
Iteration plan for Q4 is to be announced.
