### ISSUE TITLE
webpackEntryOptions magic comments

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#3680]
https://github.com/webpack/webpack/blob/6be4065ade1e252c1d8dcba4af0f43e32af1bdc1/examples/worker/example.js#L83

**Comment by birtles** [comment]
I notice that linked example uses `webpackEntryOptions`

With webpack I've been using:

```js
    /* webpackChunkName: 'db-worker' */
    /* webpackPrefetch: true */
```

and at least the `webpackChunkName` part seems to work.

It's possible the prefetch comment is being ignored, however.

**Comment by Narretz** [comment]
I see regex test for webpackChunkName https://github.com/web-infra-dev/rspack/blob/d9952e8030b0e4d9b31cfcfea7210a024052e80f/crates/rspack_plugin_javascript/src/visitors/dependency/import_scanner.rs#L41

a lots of tests that use webpackPrefetch, but not really any code specific to webpackPrefetch

**Comment by ahabhgk** [comment]
webpackPrefetch and webpackPreload are supported in https://github.com/web-infra-dev/rspack/pull/5031

**Comment by LingyuCoder** [comment]
supported webpackIgnore in https://github.com/web-infra-dev/rspack/pull/5172
supported webpackFetchPriority in https://github.com/web-infra-dev/rspack/pull/7029
supported webpackInclude and webpackExclude in https://github.com/web-infra-dev/rspack/pull/7055
supported webpackExports in https://github.com/web-infra-dev/rspack/pull/7198

all magic comments had been supported
