### ISSUE TITLE
[Tracking]: Error Code Paths

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#3685]
### What subject does this issue tracking?

# [Subject]

While the team is focusing on the good code paths, the error code paths still require a lot of work for improving on-call experience.

These include, for example:

* Better error diagnostics
* Report the "how" and "why" when something breaks
* Report when HMR is broken, it is currently silent

```[tasklist]
### Tasks
- [ ] #3674 Unclear error message
- [ ] make sure @rspack/core version consistent with @rspack/binding-xxx-yyy version
```

**Comment by hyf0** [comment]
We have a similar tracking issue: https://github.com/web-infra-dev/rspack/issues/3459

**Comment by h-a-n-a** [comment]
> We have a similar tracking issue: #3459

@Boshen Can we merge these issues together?

**Comment by Boshen** [comment]
Merged.
