### ISSUE TITLE
strange behavier of dev-server 

### ISSUE THREAD

**Issue by ssddi456** [web-infra-dev/rspack#3695]
### System Info

System:
OS: macOS 10.15.7
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Memory: 1.55 GB / 16.00 GB
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
Browsers:
Chrome: 114.0.5735.198
Safari: 15.6.1
npmPackages:
@rspack/cli: 0.2.4 => 0.2.4

### Details

when i change output.publicPath, dev server suddently become all 404 

### Reproduce Steps

folder structure:
```
|____template
| |____index.html
|____yarn.lock
|____package.json
|____build
| |____rspack.dev.config.js
|____src
| |____index.tsx
```
work spack.dev.config.js:
```
const path = require('path')

module.exports = {
    mode: 'development',
    target: 'web',
    entry: './src/index.tsx',
    output: {
		crossOriginLoading: "anonymous",
    },
    devServer: {
        host: '0.0.0.0',
        port: 9991,
        hot: true,
    },
    builtins: {
        html: [
            {
                template: path.join(__dirname, '../template/index.html'),
            },
        ],
    },
}

```
open http://localhost:9991 works as expected, html and js loaded, change output.publicPath to something like './', which should only effect assets path, which case http://localhost:9991 become 404

**Comment by hardfist** [comment]
do you check the behavior of webpack，is it the same？

**Comment by tobua** [comment]
Taking a quick look, `./` will also fail with webpack. `publicPath: '/'` will work with rspack and webpack, same for `/nested`.

However, when creating a build with `./` as the publicPath the result will work fine when opened separately.

@ssddi456 Are you fine with using `/` or nothing (is the same) as publicPath?

**Comment by ssddi456** [comment]
```publicPath: '/'``` works fine,  ```publicPath: '/publicPath' // which not exists``` wont, neither ```publicPath: '/publicPath/deal/' // which is the old webpack config```

**Comment by tobua** [comment]
When setting `publicPath: '/publicPath'` the URL `http://localhost:8080/publicPath` needs to be opened for anything to show up. Same for `/publicPath/deal/` which requires `http://localhost:8080/publicPath/deal/` to be opened in the browser.

If you want to recreate an environment similar to opening the production page under a public-path, the following configuration will achieve this:

```js
{
  output: {
    publicPath: "/publicPath",
  },
  devServer: {
    open: "/publicPath",
    historyApiFallback: { // SPA configuration.
      index: "/publicPath",
      rewrites: [{ from: /./, to: "/publicPath/index.html" }],
    },
  },
}
```

As far as I know this is configured the same in webpack. Hope this helps.

**Comment by ssddi456** [comment]
ok i found what's diff: the old setup use webpack-dev-server: 3.x and the the rspack now use webpack-dev-server 4.x, 
and the default serve-index path changes from ``cwd()``` to ```cwd()/public```
