### ISSUE TITLE
emit assets with unknown info

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#3701]
### System Info

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 56.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 6.11.0 - ~/.nvm/versions/node/v16.14.2/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.1
  npmPackages:
    @rspack/cli: 0.2.4 => 0.2.4

### Details

When emit assets with unknown info, it doesn't work.
In this example, I emit asset with `{ compressed: true }`, but it doesn't appear in stats
rspack:
<img width="451" alt="image" src="https://github.com/web-infra-dev/rspack/assets/87003751/1c4d6abc-11ae-4e51-99b4-ea4b39454067">
webpack:
<img width="282" alt="image" src="https://github.com/web-infra-dev/rspack/assets/87003751/1e75d8dd-3d70-4d24-8836-c35ad67796d9">

I'm currently working on #3677 this pr,  but blocked by this bug

### Reproduce link

https://github.com/faga295/rspack-reproduce/tree/emit_assets_with_unknown_info

### Reproduce Steps

1. pnpm run build:rspack
2. pnpm run build:webpack
3. compare the difference of output

**Comment by faga295** [comment]
bump

**Comment by LingyuCoder** [comment]
StatsAsset.info has been aligned by https://github.com/web-infra-dev/rspack/pull/6951. I will close this issue, and if you encounter new problems, you can just reopen it.
