### ISSUE TITLE
[Tracking]: Using test.config.js in Rust test cases

### ISSUE THREAD

**Issue by LingyuCoder** [web-infra-dev/rspack#3707]
When I try to fix the issue #2795 in the pull request #3700 , I need to test `builtin.html.favicon` with an absolute path, but  `__dirname` is not available in test.config.json, so I have to use `test.config.js` for the test cases.

I also found that the `rspack_testing::test_fixture` function does support test.config.js but do require the nodejs rspack in the `eval_raw::evaluate_to_json` function.

When I run `cargo test` locally, it works fine. But in the github CI environment, the test crashed because nodejs rspack can not be found:

```
Input: /home/runner/work/rspack/rspack/crates/rspack_plugin_html/tests/fixtures/favicon-absolute-public-path
node:internal/modules/cjs/loader:435
      throw err;
      ^

Error: Cannot find module '/home/runner/work/rspack/rspack/packages/rspack/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:427:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:640:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at [eval]:2:16
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:313:38)
    at node:internal/process/execution:79:19 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/rspack/rspack/packages/rspack/package.json',
  requestPath: '/home/runner/work/rspack/rspack/packages/rspack'
}
```

What is recommended way to using absolute path in Rust test cases?

**Comment by h-a-n-a** [comment]
For the html case alone, I think we could fallback to the JS tests for better porting `html-webpack-plugin` cases.

**Comment by LingyuCoder** [comment]
@h-a-n-a These test cases are used in rspack_plugin_html. So we recommend users to use rspack-plugin-html instead of the builtin rspack_plugin_html?

**Comment by h-a-n-a** [comment]
> @h-a-n-a These test cases are used in rspack_plugin_html. So we recommend users to use rspack-plugin-html instead of the builtin rspack_plugin_html?

`builtins.html` is regarded as a port for `html-webpack-plugin` with which test cases should be aligned. `rspack-plugin-html` is a port on top of the `html-webpack-plugin` as some of the features is not completely aligned, but, in the end, we should support `html-webpack-plugin`.

**Comment by hyf0** [comment]
Test in JS. There are no rules that you must write tests in rust.
