### ISSUE TITLE
thread '<unnamed>' panicked at 'not implemented', crates/rspack_hash/src/lib.rs:19:12 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3713]
### System Info

System:
    OS: macOS 12.5.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 159.71 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/Library/Caches/fnm_multishells/84327_1688609299142/bin/node
    npm: 6.14.18 - ~/Library/Caches/fnm_multishells/84327_1688609299142/bin/npm
    pnpm: 7.32.5 - ~/Library/Caches/fnm_multishells/84327_1688609299142/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.67
    Safari: 15.6.1

### Details

![image](https://github.com/web-infra-dev/rspack/assets/8898718/b35c326b-c46d-45bf-a765-58db56772274)

### Reproduce link

internal projects

### Reproduce Steps

see internal projects

**Comment by IWANABETHATGUY** [comment]
It seems that you don't use the latest rspack binding, it should be https://github.com/web-infra-dev/rspack/blob/956cb5a82641ab7cd164252906bcdd86e097d4f6/crates/rspack_hash/src/lib.rs#L17-L25, 
`not implemented ${xxx value}`
