### ISSUE TITLE
add version check for binding

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3715]
### What problem does this feature solve?

since we distribute @rspack/core and @rspack/binding separately, the version may mismatch here cause unexpected behavior here, we should do version check and provide nicely error message for users other than unreadable error message
![image](https://github.com/web-infra-dev/rspack/assets/8898718/8373f218-0ce0-45fa-9ec0-38d9ba89e8c2)

### What does the proposed API of configuration look like?

no api needed, esbuild provides nice error message for version check
![image](https://github.com/web-infra-dev/rspack/assets/8898718/c3fee7b8-5f9f-4903-a591-b97e65a4351b)

**Comment by lippzhang** [comment]
please assign this to me

**Comment by hardfist** [comment]
thanks in advance
