### ISSUE TITLE
Convert non-webpack APIs to `__internal__`

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3718]
Right now, In Rspack, there are a lot of method in Rspack like `compilation.setNoneAstModuleSource` and this is not a native webpack API. To avoid people from using this, we should convert this to `__internal__` prefixed one.

**Comment by hyf0** [comment]
Why not use private filed `#`?

**Comment by h-a-n-a** [comment]
> Why not use private filed `#`?

Private fields does not support `crate` semantic.

**Comment by hyf0** [comment]
I look at the usage of `compilation.setNoneAstModuleSource` and `compilation.__internal__setAssetSource`. Their usage doesn't require the `pub (crate)` semantic. There might be use cases as you mentioned above. However, we should prefer `#` in the first place and only add the `__internal__` prefix when using `#` is not available.

**Comment by h-a-n-a** [comment]
> I look at the usage of `compilation.setNoneAstModuleSource` and `compilation.__internal__setAssetSource`. Their usage doesn't require the `pub (crate)` semantic. There might be use cases as you mentioned above. However, we should prefer `#` in the first place and only add the `__internal__` prefix when using `#` is not available.

I agree

**Comment by h-a-n-a** [comment]
Tracked here https://github.com/web-infra-dev/rspack/issues/3726
