### ISSUE TITLE
Compatibility issues of [storybook-react-rspack] 

### ISSUE THREAD

**Issue by pointhalo** [web-infra-dev/rspack#3729]
## Description
I'm using storybook v7 with webpack 5. 
According to the following document / issue guide, i try to using rspack in our stoyrbook project 

- https://www.rspack.dev/guide/migrate-storybook.html
- https://github.com/storybookjs/storybook/issues/21561

But I found that my project originally used the [webpackFinal hook](https://storybook.js.org/docs/react/api/main-config-webpack-final#page-top) to specify alias
After switching to rspack, I don't know where to configure that. **I want to ask if there is a corresponding entrance for me to cooperate with**

![image](https://github.com/web-infra-dev/rspack/assets/88709023/10ff00d7-bfc9-49ae-aa18-65488ae97eea)

## What i try
- install `storybook-react-rspack`
- replace storybook config
```diff
    framework: {
-      name: "@storybook/react-webpack5",
+     name: "storybook-react-rspack",
        options: {
            fastRefresh: true
        },
    },
```
- run storybook

## The problem or error I encountered
After I ran it, I found some errors. I roughly divided them into categories according to my understanding.

- [Resolve error]. alias is not configured and the import is not executed correctly
![image](https://github.com/web-infra-dev/rspack/assets/88709023/d704182e-19cb-4b8e-b0b0-3a02a119d872)

- [parsing error] ^^^^^^ Expected ident error (don't know why)
![image](https://github.com/web-infra-dev/rspack/assets/88709023/4d795cb5-a78a-4687-a16a-9b5ea00bcfd5)

## Reproduce codebase and branch
- Codebase：https://github.com/DouyinFE/semi-design/tree/chore-rspack
- Branch：chore-rspack
- StorybookConfigFile Path:   `.storybook/base/base.js`
- How to run it
```
npm run bootstrap   // install dependence
npm run start           // run storybook 
```

Ps: This issue is not urgent, you guys can check it when have time. Thanks❤️

**Comment by JSerFeng** [comment]
You need to add one more configuration in your `.storybook/base/base.js`
```js
{
    rspackFinal(config) {
        config.module.rules.push(
            {
                test: /\.s(a|c)ss$/,
                include: [resolve('packages/semi-ui'), resolve('packages/semi-foundation'), resolve('packages/semi-icons')],
                use: [{ loader: 'sass-loader' }, { loader: resolve('packages/semi-webpack/lib/semi-theme-loader.js') }],
                type: 'css'
            }
        );
        config.resolve.alias = {
            ...config.resolve.alias,
            '@douyinfe/semi-foundation': resolve('packages/semi-foundation'),
            '@douyinfe/semi-icons': resolve('packages/semi-icons/src'),
            '@douyinfe/semi-ui': resolve('packages/semi-ui'),
            '@douyinfe/semi-theme-default': resolve('packages/semi-theme-default'),
            '@douyinfe/semi-illustrations': resolve('packages/semi-illustrations/src'),
            '@douyinfe/semi-animation': resolve('packages/semi-animation'),
            '@douyinfe/semi-animation-react': resolve('packages/semi-animation-react'),
            '@douyinfe/semi-animation-styled': resolve('packages/semi-animation-styled')
        };
        return config;
    },
}
```

And change your stories matcher from `../../packages/semi-ui/**/_story/*.stories.(js|jsx)` to `../../packages/semi-ui/**/_story/*.stories.{js,jsx}`

**Comment by hardfist** [comment]
close issue for long time inactivity, feel free to reopen if you have more question.
