### ISSUE TITLE
Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by Shad02w** [web-infra-dev/rspack#3732]
### System Info

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 39.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/80406_1688879568209/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/80406_1688879568209/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/80406_1688879568209/bin/npm
    pnpm: 8.6.6 - ~/Library/Caches/fnm_multishells/80406_1688879568209/bin/pnpm
  Browsers:
    Safari: 16.5

### Details

remove and undo a image (asset/resource) will cause this issue in dev server
<img width="1489" alt="image" src="https://github.com/web-infra-dev/rspack/assets/6605655/e2591216-fa1a-4587-870f-e189fb603159">

### Reproduce link

https://github.com/Shad02w/rspack-asset-resource-hmr-repo

### Reproduce Steps

1. run `pnpm dev`
2. go to `src/App.tsx`
3. comment `img` tag at line 12 and save it
4. uncomment `img` tag
5. devServer throw error

**Comment by hyf0** [comment]
Tracking at https://github.com/web-infra-dev/rspack/issues/3554

**Comment by underfin** [comment]
> Tracking at #3554

Please track here.
