### ISSUE TITLE
Add flag for tsc class useDefineForClassFields behavior. 

### ISSUE THREAD

**Issue by underfin** [web-infra-dev/rspack#3736]
### What problem does this feature solve?

The tsc provider `useDefineForClassFields` to flag class fileds behavior, please see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier. 
The swc also implement this(please see https://github.com/swc-project/swc/issues/6985), but rspack doesn't provider feature.

The current behavior is `Define` mode at `ts` & `decorate`, and is `Set` mode for target `es5-es202`, the user can't toggle the feature.

### What does the proposed API of configuration look like?

The tsc default is true if [target](https://www.typescriptlang.org/tsconfig#target) is ES2022 or higher, including ESNext, false otherwise. Maybe we should follow this behavior, and use `builtins.useDefineForClassFields: false(`Set`mode) | true (`Define` mode)` to toggele this feature.

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
this could be implemented using builtin:swc-loader, so close it
