### ISSUE TITLE
Webpack compatible builtins should also be available via `new rspack.XXXPlugin()`

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#3740]
### What problem does this feature solve?

This blocked some tests in Rspack. https://github.com/webpack/webpack/blob/6be4065ade1e252c1d8dcba4af0f43e32af1bdc1/test/configCases/loaders/hot-in-context/webpack.config.js

### What does the proposed API of configuration look like?

Make every webpack compatible `builtins` to be registered using `plugins: [new rspack.xxxPlugin()]`.

**Comment by h-a-n-a** [comment]
This can be introduced in a progressive way.

1. On the top of `builtins`, we add support for plugin style and at the same time, deprecating the builtins options
2. Fully support for plugin style

**Comment by ScriptedAlchemy** [comment]
We should throw deprecation warnings for builtins before removing it completely so users have a chance to adopt before build fails.

**Comment by 9aoy** [comment]
I am more concerned about how rspack will set the minimizer behavior. Built-in minimizer is a default value in webpack, and only override is supported, and experiments.css does not yet support built-in compression (https://github.com/webpack/webpack/issues/14893).

![20230814-115330](https://github.com/web-infra-dev/rspack/assets/22373761/c6b9781d-cfe0-4215-8359-e89ea912c952)


ps. In our scenario(modern.js), we want to continue using rspack's built-in js minimizer, but replace css minimizer with cssnano.

**Comment by 9aoy** [comment]
It seems that the webpack experiment css is supporting minimize, but I am more concerned about whether I can use the built-in js compression and custom css compression at the same time. 😂 

https://github.com/webpack/webpack/pull/17309

**Comment by h-a-n-a** [comment]
closed in favor of this https://github.com/web-infra-dev/rspack/discussions/4006
