### ISSUE TITLE
Uncaught (in promise) TypeError: xxx_bgwasm.__wbindgen_start is not a function

### ISSUE THREAD

**Issue by kurisu994** [web-infra-dev/rspack#3744]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 269.05 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh 

  Binaries:
    Node: 16.20.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
    Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman 

  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1

### Details

my project is `modernjs`+`rspack`, and wasm is compiled into an npm package with wasm-bindgen. When importing the project, it will directly prompt:
`Uncaught (in promise) TypeError: xxx_bgwasm.__wbindgen_start is not a function`

I also reported this problem to modernjs,  they thought it was a problem with rspack.
[4144#](https://github.com/web-infra-dev/modern.js/discussions/4144#discussioncomment-6389176)

### Reproduce link

https://gitee.com/makisek/modern-demo

### Reproduce Steps

you just need  `yarn`  and `yarn dev`

**Comment by h-a-n-a** [comment]
I see. This is blocked by the top-level await support of Rspack and asyncWebAssembly support. Currently, we haven't support `experiments.asyncWebAssembly` yet.

**Comment by kurisu994** [comment]
bump

**Comment by h-a-n-a** [comment]
@ahabhgk What's our plan for top-level await?

**Comment by ahabhgk** [comment]
This probably a interop problem, not related to TLA, will fix it later

**Comment by ahabhgk** [comment]
Oh, already fixed, please upgrade to latest version by `npx modern upgrade`
