### ISSUE TITLE
偶发打包报错

### ISSUE THREAD

**Issue by suxiaohei2000** [web-infra-dev/rspack#3759]
### System Info

 System:
    OS: macOS 13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 752.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.3
  npmPackages:
    @rspack/cli: ^0.2.4 => 0.2.4 

### Details

报错信息如下：
Napi Error: GenericFailure - 
import {Component, Prop, Vue} from 'vue-property-decorator';
Unrecognised input. Possibly missing opening '{'

### Reproduce Steps

rspack build --mode=development

**Comment by h-a-n-a** [comment]
@suxiaohei2000 Please send us a link to the reproduction repo.
