### ISSUE TITLE
[Feature Request] builtins.html support `inject: false`

### ISSUE THREAD

**Issue by justforuse** [web-infra-dev/rspack#3761]
### What problem does this feature solve?

```
Configuration error:
- Expected 'head' | 'body', received boolean at "builtins.html[0].inject"
```
For now, the `builtins.html` does not support `inject: false`, but I want to load the `main.js` mannually

### What does the proposed API of configuration look like?

```
type BuiltinsHtml = Array<{
  // ...
  // if set `false`, it should not inject automatically
  inject?: 'head' | 'body' | boolean
}>;
```

**Comment by lippzhang** [comment]
I am interested in this, I make the API like this
```js
type BuiltinsHtml = Array<{
  // if set `false`, it should not inject automatically
  inject?: 'head' | 'body' | ‘automatically’
}>;
```

**Comment by hyf0** [comment]
> I am interested in this, I make the API like this
> 
> ```js
> type BuiltinsHtml = Array<{
>   // if set `false`, it should not inject automatically
>   inject?: 'head' | 'body' | 'automatically'
> }>;
> ```
> 
> @hyf0

I'm not sure. The `builtins.html` should align with `html-webpack-plugin`. We don't introduce new API at this moment.

**Comment by lippzhang** [comment]
> > I am interested in this, I make the API like this我对此感兴趣，我使API像这样
> > ```js
> > type BuiltinsHtml = Array<{
> >   // if set `false`, it should not inject automatically
> >   inject?: 'head' | 'body' | 'automatically'
> > }>;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hyf0
> 
> I'm not sure. The `builtins.html` should align with `html-webpack-plugin`. We don't want to introduce new API at this moment.我不确定。应 `builtins.html` 与 对齐 `html-webpack-plugin` 。我们目前不想引入新的 API。

Understood, let me align with `html-webpack-plugin` , 
```js
type BuiltinsHtml = Array<{
  // ...
  // if set `false`, it should not inject automatically
  inject?: 'head' | 'body' | boolean
}>;
```
