### ISSUE TITLE
react-refresh fails if two components have the same function name

### ISSUE THREAD

**Issue by jraoult** [web-infra-dev/rspack#3765]
### System Info

System: MacOS

### Details

When two (or more) components from different modules have the same function name, rspack's `rect-refresh` implementation gets confused and replaces all the instances with the content of the last one defined. Renaming one of the components fixes the issue. I suspect a problem with the component keys generation for react-refresh that produces a collision in the registry or cache.

### Reproduce Steps

1. Unzip [the attached project](https://github.com/web-infra-dev/rspack/files/12030714/repro-rspack-refresh.zip). Note that it contains two components named `Cell` in two different modules (`First.jsx` and `Second.jsx`).
2. run yarn install
3. run yarn dev
4. check that the test app is working and you can see
   ```
   Cell first
   Cell second
   ```
6. update any react component to trigger refresh
7. you should see
      ```
   Cell second
   Cell second
   ```

If you rename one of the `Cell` component to any other unique name refresh works perfectly.

**Comment by hyf0** [comment]
Thanks for reporting. Would you mind testing the problem to see whether the issue exists in Webpack + react refresh?

**Comment by jraoult** [comment]
> Thanks for reporting. Would you mind testing the problem to see whether the issue exists in Webpack + react refresh?

Thanks for following up @hyf0 . I've been using fast refresh with Webpack + babel loader for months now without this issue. As a matter of fact, I found this issue while trying to migrate from webpack to rspack. Happy to provide the webpack setup for my example project if you need it.

**Comment by jraoult** [comment]
Here we go @hyf0 here's the updated project with a script to run the webpack version that works. You can run it with `yarn dev:w`. Same testing steps and you can see that it works properly.

[repo.zip](https://github.com/web-infra-dev/rspack/files/12038079/repo.zip)

**Comment by suica** [comment]
It seems like it's fixed by #3763, and the fix is available in `@rspack/cli@0.2.8`. 
I tested it with the project provided in this issue with 0.2.8, and everything works fine.
@jraoult @hyf0 
<img width="343" alt="infoflow 2023-07-24 19-38-04" src="https://github.com/web-infra-dev/rspack/assets/8041462/44c5f0f7-7a84-4824-a230-3c347e8171cb">

**Comment by jraoult** [comment]
@suica indeed, it seems to be fixed in 0.2.8 🙏. Thanks for notifying me. @hyf0 should we close this issue then?
