### ISSUE TITLE
React Query useQuery isn't refetching when query-keys changes

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rspack#3776]
### System Info

Need to install the following packages:
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 14.82 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.79)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: 0.2.4 => 0.2.4

### Details

Hi, 

Between version 0.2.4 and version 0.2.5 ReactQuery's useQuery hook is not retriggered when query-keys change.

In version 0.2.4 it is working, and in 0.2.5 it stops working

### Reproduce link

(https://github.com/JoseBuendiaDigio/ReactQueryRsPack)

### Reproduce Steps

With version 0.2.4 useQuery promise is relaunched when query-keys changes.
With version 0.2.5 useQuery promise isn't relaunched when query-keys changes.
The same occurs in 0.2.6, 0.2.7, 0.2.8, 0.2.9 and 0.2.10
This only occurs in the build, in dev mode isn't happening

**Comment by JoseBuendiaDigio** [comment]
@hyf0 

https://github.com/JoseBuendiaDigio/ReactQueryRsPack

In version 0.2.4 of rspack all is good.
In version 0.2.5 React Query isn't launching promises on queryKey changes
The same occurs in 0.2.6, 0.2.7, 0.2.8 and 0.2.9

This only occurs in the build, in dev mode isn't happening

**Comment by rolderman** [comment]
Another possible sign: starting from version 0.2.5 the DevTools icon is not displayed

**Comment by hardfist** [comment]
@JoseBuendiaDigio can you help investigate more about the runtime code, we are not familiar with react-query and your code, if you can provide more detail about the runtime error it can help us to debug rspack problem.

**Comment by JoseBuendiaDigio** [comment]
@hardfist Seems that from 0.2.11 is working, I think that this issue can be closed
