### ISSUE TITLE
Generate invalid CSS when building Vue 3 app

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#3798]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/yarn
    npm: 8.19.3 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/npm
    pnpm: 7.18.1 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: 0.2.7 => 0.2.7

### Details

The CSS generated by the Rspack build contains redundant `;` characters, causing the following style to not take effect:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/60d052ba-d8e1-4def-aee9-d44a9df2bb59)

This issue only appears when I using vue-loader and import css files in the `index.js` file.

### Reproduce link

https://github.com/chenjiahan/rspack-vue3-style-issue

### Reproduce Steps

1. pnpm i
2. pnpm dev
3. open http://localhost:8080/
4. Check the background color of the page.

**Comment by hyf0** [comment]
`#region` seems quite useful for debugging. :).

**Comment by h-a-n-a** [comment]
@chenjiahan I think this one should be working as expected now. Would you test?

**Comment by chenjiahan** [comment]
The problem has been fixed 👍 Well done!
