### ISSUE TITLE
HMR doesn't work when updating context module

### ISSUE THREAD

**Issue by nieyuyao** [web-infra-dev/rspack#3802]
### System Info

  System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    pnpm: 7.32.0 - ~/.nvm/versions/node/v16.17.1/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 15.4
  npmPackages:
    @rspack/cli: latest => 0.1.12 

### Details

HMR don't work when updating the context module. It looks like it's because the module hash hasn't been updated.

https://github.com/web-infra-dev/rspack/blob/14edf78e6d3558fcd7e321b14f4324bf953ad1d1/crates/rspack_core/src/context_module.rs#L378-L383

### Reproduce link

https://codesandbox.io/p/sandbox/jovial-frost-w94ngc?file=%2Fsrc%2Findex.js%3A8%2C1

### Reproduce Steps

 1. update `index.js`.
```
console.log("bbb");
```
2. `bbb` not printed

**Comment by nieyuyao** [comment]
Whether we should add source to the generation of hash?

**Comment by hyf0** [comment]
@underfin Any ideas?

**Comment by nieyuyao** [comment]
You can assign the bug to me if you have any ideas. I am interested in this issue.

**Comment by underfin** [comment]
I will work on it at next weeks.

**Comment by hardfist** [comment]
this  issue is outdated, if you met it again in latest version, please file a new issue
