### ISSUE TITLE
support output stats.info.minimized

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3811]
### What problem does this feature solve?

I want to know if assets have been minimized, but I found that the `asset.info.minimized` is `undefined`, even though the asset has been minimized.

rspack asset：
<img width="666" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/21888b47-669d-4f2d-a2bb-98a4117ffcf2">

webpack asset：

<img width="470" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/56f11615-dbae-4df3-8d76-4495de989d71">

### What does the proposed API of configuration look like?

none

**Comment by faga295** [comment]
#3837 Maybe this pr will resolve it.

**Comment by hardfist** [comment]
@LingyuCoder is this supported now?

**Comment by LingyuCoder** [comment]
> @LingyuCoder is this supported now?

Supported by https://github.com/web-infra-dev/rspack/pull/6951
