### ISSUE TITLE
uncaught Error: React Refresh runtime should not be included in the production bundle.  

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3816]
### System Info

none

### Details

build failed when use rspack `0.2.8-canary-7d28a3a-20230721010304`

<img width="955" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/fa9b34b2-3831-48f7-a531-ef70a19fbe9d">

I already set the refresh is false, but it seems not work, when I remove this `builtins.provide` configuration, I get a new error when I run build & serve 👇 

<img width="1018" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/ce613c6d-883a-40f9-a6e8-f1b4231c47df">

<img width="1086" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/7820442e-eea9-46f5-93b8-e8a603484f05">

### Reproduce link

https://github.com/web-infra-dev/modern.js/tree/update-rspack-test-0721

### Reproduce Steps

1. pnpm i & pnpm prepare
2. cd tests/integration/builder-rspack
3. DEBUG=builder pnpm build
4. npx modern serve

**Comment by ahabhgk** [comment]
@underfin cc
