### ISSUE TITLE
support `optimization.concatenateModules`

### ISSUE THREAD

**Issue by arananegra** [web-infra-dev/rspack#3823]
### What problem does this feature solve?

It would be nice to be able to enable module concatenation the same as webpack does with https://webpack.js.org/plugins/module-concatenation-plugin/#root

### What does the proposed API of configuration look like?

```
	optimization: {
		concatenateModules: true,
                 ......
	},
```

**Comment by hardfist** [comment]
yeah it is on the roadmap

**Comment by arananegra** [comment]
Oh sorry, didn't found any reference. Feel free to close in that case

**Comment by hardfist** [comment]
bump

**Comment by IWANABETHATGUY** [comment]
closed in favor of https://github.com/web-infra-dev/rspack/pull/5559
