### ISSUE TITLE
wrong module treeShaking

### ISSUE THREAD

**Issue by Lionad-Morotar** [web-infra-dev/rspack#3824]
### System Info

  System:
    OS: Windows 10 10.0.22623
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 45.94 GB / 63.77 GB
  Binaries:
    Node: 18.16.1 - ~\OneDrive\Code\NodeJS\node.EXE
    Yarn: 1.22.19 - D:\node-modules\node_modules\yarn.CMD
    npm: 9.5.1 - ~\OneDrive\Code\NodeJS\npm.CMD
    pnpm: 8.6.5 - D:\node-modules\node_modules\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.891.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: ^0.2.8 => 0.2.8
    @rspack/plugin-html: ^0.2.8 => 0.2.8

### Details

createElementNS && createElement is missing when treeShaking enabled (by default)
![image](https://github.com/web-infra-dev/rspack/assets/26913795/9f2e2c2b-97fb-4a51-a595-36b0569c787b)

"createElementNS" in @antv/x6（imported from @antv/x6-common）
![image](https://github.com/web-infra-dev/rspack/assets/26913795/907697a7-1fe3-49f2-99f4-11b9ccd374ff)

### Reproduce link

https://github.com/Lionad-Morotar/reproduce-rspack-treeShaking-bug

### Reproduce Steps

1. `pnpm build`
2. search `createElementNS` in `dist` dir

**Comment by hyf0** [comment]
@IWANABETHATGUY cc

**Comment by IWANABETHATGUY** [comment]
Please give me a valid example, 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/d77a7027-8b09-48bf-8c38-5c0449ae069a)
this example will throw a run time error even I disabled tree shaking.

**Comment by IWANABETHATGUY** [comment]
This bug has been fixed in the main branch. Please use the nightly version, feel free to reopen this issue if you have further question.
