### ISSUE TITLE
configures the global style

### ISSUE THREAD

**Issue by fengyun2** [web-infra-dev/rspack#3827]
### What problem does this feature solve?

rspack configures global styles, such as webpack plugin: `style-resources-loader`.

### What does the proposed API of configuration look like?

```js
rules: [{
   test: /\.less$/,
   use: ['style-loader', 'css-loader', 'less-loader', {
       loader: 'style-resources-loader',
       options: {
           patterns: path.resolve(__dirname, 'path/to/less/variables/*.less'),
           injector: 'append'
       }
   }]
}]
```

**Comment by hyf0** [comment]
I don't understand what you described. Could you add more context?

**Comment by fengyun2** [comment]
The current legacy project is based on vue-cli@5.03 version, I will define all css variables in a file (`src/styles/common/var.less`),
You only need to import this file once to use the css variable directly in all files, no need to import it in every file that needs to be used.

vue.config.js:
```js
//vue.config.js
const path = require('path');
const resolve = dir => path. join(__dirname, dir);

module.exports = {
   ...
   pluginOptions: {
     'style-resources-loader': {
       preProcessor: 'less',
       patterns: [resolve('src/styles/common/var.less')],
     },
   },
   ...
}
```

var.less:

```less
@red: #ee0a24;
@white: #fff;
// font variable
@font-color-gray: @gray-deep;
@font-size-xs: 20px;
@font-size-small: 24px;
@font-size-normal: 28px;
@font-size-lg: 32px;
```

use:
```vue
<style lang="less" scoped>
// After configuring style-resources-loader, there is no need to introduce css global variables like this @import '@/styles/common/var.less';
.title {
   font-size: @font-size-lg;
}
</style>
```

**Comment by fengyun2** [comment]
> /The current legacy project is based on vue-cli@5.03 version, I will define all css variables in a file (`src/styles/common/var.less`), You only need to import this file once to use the css variable directly in all files, no need to import it in every file that needs to be used.
> 
> **vue.config.js:**
> 
> ```js
> //vue.config.js
> const path = require('path');
> const resolve = dir => path. join(__dirname, dir);
> 
> module.exports = {
>    ...
>    pluginOptions: {
>      'style-resources-loader': {
>        preProcessor: 'less',
>        patterns: [resolve('src/styles/common/var.less')],
>      },
>    },
>    ...
> }
> ```
> 
> **var.less:**
> 
> ```css-less
> @red: #ee0a24;
> @white: #fff;
> // font variable
> @font-color-gray: @gray-deep;
> @font-size-xs: 20px;
> @font-size-small: 24px;
> @font-size-normal: 28px;
> @font-size-lg: 32px;
> ```
> 
> **use:**
> 
> ```
> <style lang="less" scoped>
> // After configuring style-resources-loader, there is no need to introduce css global variables like this @import '@/styles/common/var.less';
> .title {
>    font-size: @font-size-lg;
> }
> </style>
> ```

@hyf0

**Comment by ScriptedAlchemy** [comment]
Ahh this is like sass resource loader.

They have global var or mixin they dont want to import into ever style file to use, but instead want to configure injector to inject mixin or variable file import into each style file processed.

I used to do this with sass using

https://github.com/shakacode/sass-resources-loader

**Comment by tuoy1** [comment]
@fengyun2  Is the problem solved ?
