### ISSUE TITLE
Bundle size deviation compared to other bundlers

### ISSUE THREAD

**Issue by s1owjke** [web-infra-dev/rspack#3828]
### System Info

System:
OS: macOS 13.3
 
Binaries:
Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
 
npmPackages:
@rspack/core: ^0.2.3 => 0.2.3 

### Details

When I'm making an optimized build for production I get a [much larger bundle](https://github.com/s1owjke/js-bundler-benchmark/pull/2/commits/c88a3dcbc1052446c6243b6b115c5e291424d49b) compared to Webpack and others. It's also worth noting that I'm using Rspack as a library (similar to Webpack) and not using CLI

| Bundler     | Size       | Size gzip  |
| ----------- | ---------- | ---------- |
| Rspack      | 452.82 KiB | 140.76 KiB |
| Webpack swc | 163.00 KiB | 54.49 KiB  |

I checked the resulting bundle and it contains parts of code wrapped in `process.env.NODE_ENV !== 'production’`, which shouldn’t be included, because production mode is explicitly specified in config.

For example `node_modules/react/index.js` contents

```
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

The development build of React contains many additional checks

```
if (render != null && render.$$typeof === REACT_MEMO_TYPE) {
  error('forwardRef requires a render function but received a `memo` ' + 'component. Instead of forwardRef(memo(...)), use ' + 'memo(forwardRef(...)).');
}
```

And all of them exists in resulting bundle created by Rspack

```
if (render != null && render.$$typeof === REACT_MEMO_TYPE) error("forwardRef requires a render function but received a `memo` component. Instead of forwardRef(memo(...)), use memo(forwardRef(...)).");
```

### Reproduce link

https://github.com/s1owjke/js-bundler-benchmark/tree/add-rspack

### Reproduce Steps

1. Clone the repository
```
git clone git@github.com:s1owjke/js-bundler-benchmark.git
cd js-bundler-benchmark
git checkout add-rspack
```

2. Install dependencies
```
npm i
cd projects/react-empty && npm i && cd ../..
```

3. Run the build
```
npm run build:rspack -- --project react-empty --entrypoint src/index.tsx
npm run build:webpack -- --project react-empty --preset swc --entrypoint src/index.tsx
```

**Comment by IWANABETHATGUY** [comment]
Could you disable `optimization. concatenateModules` and `optimization.mangleExports` and compare again, we don't implement these two features yet.

**Comment by IWANABETHATGUY** [comment]
Also, can you try the latest `@rspack/core` ? We did some optimization in 0.2.3 ~ 0.2.8

**Comment by IWANABETHATGUY** [comment]
> Perhaps it would be better to resolve the configuration in core and leave only the thin wrapper in cli, either this needs to be explicitly described in the documentation, what do you think?

@web-infra-dev/rspack-dx what do you guys think?

**Comment by ahabhgk** [comment]
IMO we should add this, and other conventions in docs, other than resolve it in core

**Comment by hardfist** [comment]
close this issue since this problem seems solved
