### ISSUE TITLE
Content not from webpack is served from 'xxx' directory

### ISSUE THREAD

**Issue by huanglsj** [web-infra-dev/rspack#3836]
### System Info

win10

"@rspack/cli": "^0.2.8"

### Details

<i> [webpack-dev-server] Content not from webpack is served from 'xxx' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<e> [webpack-dev-middleware] [Error: napi error: GenericFailure - TypeError: Cannot read property 'tap' of undefined
<e>     at D:\work\xxx\node_modules\vue-loader\lib\plugin-webpack4.js:14:28
<e>     at Hook.eval (eval at create (D:\work\xxx\node_modules\@rspack\core\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
<e>     at Hook.CALL_DELEGATE [as _call] (D:\work\xxx\node_modules\@rspack\core\node_modules\tapable\lib\Hook.js:14:14)
<e>     at Compiler._Compiler_compilation (D:\work\xxx\node_modules\@rspack\core\dist\compiler.js:730:28)
<e>    0: napi_register_module_v1
<e>    1: napi_register_module_v1
<e>    2: <unknown>
<e>    3: <unknown>
<e>    4: node_module_register
<e>    5: node_module_register
<e>    6: uv_async_send
<e>    7: uv_loop_init
<e>    8: uv_run
<e>    9: v8::internal::AsmJsScanner::GetIdentifierString
<e>   10: node::Start
<e>   11: RC4_options
<e>   12: v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
<e>   13: BaseThreadInitThunk
<e>   14: RtlUserThreadStart
<e> ] {
<e>   code: 'GenericFailure'
<e> }

### Reproduce Steps

npm run dev

**Comment by hardfist** [comment]
This issue will be closed due to inactivity. Feel free to comment and reopen it if you have any further questions.
