### ISSUE TITLE
Duplicate root module name DynamicImport

### ISSUE THREAD

**Issue by huanglsj** [web-infra-dev/rspack#3838]
### System Info

win10
 node 16.18.1
@rspack/cli: ^0.2.8

### Details

thread 'tokio-runtime-worker' panicked at 'Duplicate root module name DynamicImport(missing|D:\work\xxx\src\router//views/salary/monthlySalary/index)', crates\rspack_ids\src\stable_named_chunk_ids_plugin.rs:69:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

<e> [webpack-dev-middleware] [Error: error[internal]: Duplicate root module name DynamicImport(missing|D:\work\xxx\src\router//views/salary/monthlySalary/index).
<e> Raw: 
<e> This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
<e>
<e>
<e> ] {
<e>   code: 'GenericFailure'
<e> }

### Reproduce Steps

npm run dev

**Comment by hardfist** [comment]
@huanglsj can you help try the nightly version and see whether it's fixed

**Comment by huanglsj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by randomVariable2000** [comment]
I've met the same issue as well.

### System Info
```
macOS 13.4
```

```
$ node -v 
v16.20.1
```

```
    "@rspack/cli": "^0.2.5",
    "@rspack/core": "^0.4.0"
```

### Details
```
Rspack █████████████████████████░░░░░░░░░░░░░░░ 63% building                                        Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Rspack █████████████████████████░░░░░░░░░░░░░░░ 64% building ../../../_lib/buildMatchPatternFn/indexthread 'tokio-runtime-worker' panicked at 'Duplicate root module name DynamicImport(missing|/Users/xxxx/xxx/xxx/xxx/BatchManage)', crates/rspack_ids/src/stable_named_chunk_ids_plugin.rs:69:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<e> [webpack-dev-middleware] [Error: error[internal]: Duplicate root module name DynamicImport(missing|/Users/xxx/xxx/xxx/xxx/BatchManage).
<e> Raw: 
<e> This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
<e> 
<e> 
<e> ] {
<e>   code: 'GenericFailure'
<e> }
^C<i> 
```



@hardfist

**Comment by huanglsj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huanglsj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huanglsj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LingyuCoder** [comment]
Close because no feedback. If you meet the same issue, please just reopen this issue and provide your repro.

**Comment by huanglsj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
