### ISSUE TITLE
Tree shaking problem

### ISSUE THREAD

**Issue by arananegra** [web-infra-dev/rspack#3840]
### System Info

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Brave Browser: 115.1.56.11
    Chrome: 114.0.5735.198
    Edge: 115.0.1901.183
    Safari: 16.1

### Details

I'm using rspack alongside material-ui (https://mui.com/material-ui/). They encourage the usage of tree shaking (https://mui.com/material-ui/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking) so that you don't have to deal with nested routes imports like `import Delete from '@mui/icons-material/Delete'`; (which is a common problem in the library).

Testing the production builds of rspack vs webpack I have noticed that wherever you use the named imports (from the mains packages of the library), the build coming from rspack does not run any tree shaking compared with the webpack one.

In the repro I provide, I render an icon using `import { DoNotDisturb } from "@mui/icons-material";` so that if no tree shaking is performed, the whole "icons-material" package would be present

Might be related to https://github.com/web-infra-dev/rspack/issues/3829

### Reproduce link

https://github.com/arananegra/rspack-project

### Reproduce Steps

1. npm i
2. npm run build:perf:webpack  // produce the webpack perf analysis 
3. npm run build:perf // produce the rspack perf analysis

If you compare the bundles, in the rspack you have that the @mui package has an stat size of 6.3mb, a parsed size of 40.24kb and so on:
![image](https://github.com/web-infra-dev/rspack/assets/14930496/6aa46f2f-f7f4-4a4f-bc56-f243f3fe3432)

On the other hand, webpack seems to be using the tree shaking algorithm so that the @mui package is smaller.

![image](https://github.com/web-infra-dev/rspack/assets/14930496/173c8b9b-170f-4fd6-9881-3068f6f34a62)

PS: I've tried to disable concatenate modules in webpack with `optimization.concatenateModules: false,` but the result seems to be the same

**Comment by IWANABETHATGUY** [comment]
**webpack** 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/33d5a24e-ff39-4107-8ef9-533413dc351b)
**rspack** 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/b7218ad1-f4ca-4af5-b5d6-b5fdc0550f55)
According to the final artifacts,  I don't think we keep the whole @mui library in the final bundle.
Currently, we don't 100% align with webpack, so our output is larger than webpack indeed.

**Comment by arananegra** [comment]
Ok! I was a little worried about the stat size but If you know this is the expected behavior feel free to close if needed 😄
