### ISSUE TITLE
window run dev always crash

### ISSUE THREAD

**Issue by suxiaohei2000** [web-infra-dev/rspack#3842]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 545.47 MB / 15.89 GB
  Binaries:
    Node: 14.21.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566

### Details

13 verbose stack Error: gcb-app-web@8.13.0 dev: `rspack serve`
13 verbose stack Exit status 3221226505
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\zhangpan\AppData\Roaming\nvm\v14.21.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\zhangpan\AppData\Roaming\nvm\v14.21.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid gcb-app-web@8.13.0
15 verbose cwd D:\zhangpan\gcb-web-app
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.21.0
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 3221226505
22 error gcb-app-web@8.13.0 dev: `rspack serve`
22 error Exit status 3221226505
23 error Failed at the gcb-app-web@8.13.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221226505, true ]

### Reproduce Steps

1、rspack serve

**Comment by chenjiahan** [comment]
This issue will be closed because there is no reproduce link.

Feel free to comment and reopen it if you have any further questions. For background, see [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).
