### ISSUE TITLE
what is the plan to support `asset.info.sourceFilename` 

### ISSUE THREAD

**Issue by ClarkXia** [web-infra-dev/rspack#3851]
### What problem does this feature solve?

Asset Info returned by `compilation.getAsset(chunkFile)` lost props of `sourceFilename`.
Do we have a plan to support it.

### What does the proposed API of configuration look like?

`compilation.getAsset(chunkFile)` returns `sourceFilename`.

**Comment by hyf0** [comment]
@web-infra-dev/rspack-dx cc

**Comment by faga295** [comment]
Maybe I can help to support this

**Comment by h-a-n-a** [comment]
> Maybe I can help to support this

@faga295 Thanks for the help! Already assigned.

**Comment by LingyuCoder** [comment]
Solved by #4013
