### ISSUE TITLE
Building got stuck with `stats` `verbose` of version `0.2.9`

### ISSUE THREAD

**Issue by xfsnowind** [web-infra-dev/rspack#3858]
### System Info

System:
OS: Mac 13.4.1
CPU: Apple M1 Pro

Binaries:
Node: 18.12.1
npm: 8.19.2
pnpm: 8.6.9

### Details

WIth version 0.2.9, I tried to update `stats` to `verbose` and when I run the command with `nx`: 

```
pnpm cross-env NODE_OPTIONS=--max-old-space-size=6144 NODE_ENV=development DEVELOPMENT_ENV=docker webpack serve --config ./apps/fleet-web/webpack.config.js
```

The building got stuck.

<img width="984" alt="image" src="https://github.com/web-infra-dev/rspack/assets/2863328/f496aa9b-3e5e-4a4f-83a0-dcdc027bf75f">

And it generated two big `node` processes:
<img width="983" alt="image" src="https://github.com/web-infra-dev/rspack/assets/2863328/76a2c1da-e921-46cc-9df7-14c5a4f5f265">

And even when I Ctrl+C the process, the biggest one does not close.

However, it works with version 0.2.8.

I could not reproduce it with project created by the command `pnpm create rspack@latest`. Probably something conflict with the 

### Reproduce Steps

It can not be reproduced with the scratch project. But through change the `stats` to `verbose`, it's stuck.

**Comment by 9aoy** [comment]
<img width="835" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/5f836129-956f-4717-8b00-f4be15a6163b">

Do you mean it can be reproduced after setting stats to "verbose"? Tried this on some large projects, didn't reproduce. Can you give a reproducible demo?

**Comment by xfsnowind** [comment]
Hmm, I can share our configuration, hope it can help:

https://gist.github.com/xfsnowind/ac842b68bb0441971ba702553042bcf0

**Comment by hardfist** [comment]
@xfsnowind  can you try disable forkTsCheckPlugin first and see whether the problem exists

**Comment by xfsnowind** [comment]
> 

Hi, thanks for replying, @hardfist I had commented, but still stuck.

**Comment by hardfist** [comment]
actually you can use vscode to debug stuck problem if it's stuck in js side, you can debug 
launch your process in javascript debug terminal 
![image](https://github.com/web-infra-dev/rspack/assets/8898718/3bec044b-8d2a-495e-b7f4-be6ec324a3b1)
and click the debug button shown below, and it's stuck on js side you can see the stuck call stack
![image](https://github.com/web-infra-dev/rspack/assets/8898718/11bb8030-9994-4863-ba2a-056378777149)
![image](https://github.com/web-infra-dev/rspack/assets/8898718/0019007a-27a2-4f48-a1dc-173a505c7e67)

**Comment by ScriptedAlchemy** [comment]
@xfsnowind following up here, can you debug via vscode?

**Comment by xfsnowind** [comment]
Hi, @ScriptedAlchemy @hardfist sorry for replying late. 

This is the debug screenshot, it finally calls the `cross-env` which is used to handle the env.
<img width="360" alt="image" src="https://github.com/web-infra-dev/rspack/assets/2863328/de5661e0-75f8-4531-b2f1-e92eede530df">

And I tried it without `verbose`, the debug result is the same as `verbose`. Hope it helps.

**Comment by hardfist** [comment]
do you click pause button when you hang? it's weird that it doesn't have rspack stack

**Comment by xfsnowind** [comment]
> do you click pause button when you're stuck? it's weird that it doesn't have rspack stack

I did, but nothing happened, seems like node is stuck. And when I Ctrl+C, the `node` process still exists.

**Comment by hardfist** [comment]
> > do you click pause button when you're stuck? it's weird that it doesn't have rspack stack
> 
> I did, but nothing happened, seems like node is stuck. And when I Ctrl+C, the `node` process still exists.

can you screenshot the process, even node stuck it should stuck on some filesystem call
