### ISSUE TITLE
Rspack and Webpack runtime chunk are  inconsistent.

### ISSUE THREAD

**Issue by hhuwc** [web-infra-dev/rspack#3860]
### System Info

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 74.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    pnpm: 6.35.1 - ~/.nvm/versions/node/v14.21.3/bin/pnpm
  Browsers:
    Safari: 16.4
  npmPackages:
    @rspack/cli: latest => 0.2.9 
    @rspack/core: ^0.2.8 => 0.2.9

### Details

<img width="1491" alt="image" src="https://github.com/web-infra-dev/rspack/assets/20037388/fa0ecce7-eb01-4234-b715-5605fd062739">

### Reproduce link

https://fe-video-qc.xhscdn.com/fe-platform/21f01529993067f9742743ee7a0b302926768e98.zip

### Reproduce Steps

0. download the zip above
1. npm i
2. npm run build
3. open  build/runtime.webpack.js   build/runtime.rspack.js
4. you will find that they are inconsistent.

**Comment by underfin** [comment]
@hhuwc The reproduction link is 404, can you give me your configure?

**Comment by hhuwc** [comment]
> @hhuwc The reproduction link is 404, can you give me your configure?

webpack config
`const { VueLoaderPlugin } = require("vue-loader");

const getConfig = () => {
	return {
		cache: false,
		context: __dirname,
		entry: {
			main: {
				import: "./src/main",
				runtime: "runtime"
			}
		},
		output: {
			library: {
				name: 'XHS_COMPONENTS',
				type: 'umd',
				umdNamedDefine: false,
			},
			globalObject: 'this',
			filename: `[name].webpack.js`
		},
		optimization: {
			splitChunks: false
		},
		externals: {
			vue: 'vue',
		},
		plugins: [new VueLoaderPlugin()],
		module: {
			rules: [
				{
					test: /\.vue$/,
					loader: "vue-loader",
					options: {
						experimentalInlineMatchResource: true
					}
				},
				{
					test: /\.css$/,
					use: ["vue-style-loader", "css-loader"],
					// type: "javascript/auto"
				},
				{
					test: /\.(png|jpe?g|gif)$/,
					type: 'asset/resource',
					generator: {
						filename: 'assets/img/[hash][ext]',
					},
				},
			]
		},
	}
};

module.exports = getConfig()

`

rspack config
`const { VueLoaderPlugin } = require("vue-loader");

const getConfig = () => {
	return {
		cache: false,
		context: __dirname,
		entry: {
			main: {
				import: "./src/main",
				runtime: "runtime"
			}
		},
		output: {
			library: {
				name: 'XHS_COMPONENTS',
				type: 'umd',
				umdNamedDefine: false,
			},
			globalObject: 'this',
			filename: `[name].rspack.js`
		},
		optimization: {
			splitChunks: false
		},
		externals: {
			vue: 'vue',
		},
		plugins: [new VueLoaderPlugin()],
		experiments: {
			css: false,
		},
		devtool: false,
		module: {
			rules: [
				{
					test: /\.vue$/,
					loader: "vue-loader",
					options: {
						experimentalInlineMatchResource: true
					}
				},
				{
					test: /\.css$/,
					use: ["vue-style-loader", "css-loader"],
					type: "javascript/auto"
				},
				{
					test: /\.svg$/,
					type: "asset/resource"
				}
			]
		}
	}
};
module.exports = getConfig()

`
