### ISSUE TITLE
Support emitting sourceRoot in generated source map

### ISSUE THREAD

**Issue by AadamZ5** [web-infra-dev/rspack#3862]
### What problem does this feature solve?

I've searched google and the issues within this repository, I couldn't find anything on this topic. Apologies if I missed an ongoing discussion about this!

In my mono-repo structure (using Nx) I have a project that I am bundling with `rspack` which is truly blazingly fast :)

I'm running the bundled project with Nx's Node executor `@nx/js:node`, but this is probably irrelevant.

I am emitting a source map `main.js.map` alongside my `main.js` in a distribution folder.

`config.devtool = 'source-map nosources';`

My IDE (vscode) is not resolving the sources listed in the source map file, because the code that generates the source map uses relative paths in the map file. I think `rspack_plugin_devtool` is responsible for generating the source map.

If the dev tool plugin supported emitting the `"sourceRoot"` key in the map file, my IDE will be able to correctly resolve the source maps, and my breakpoints will bind. I've tested this by manually adding the `"sourceRoot"` key to the emitted `main.js.map` file. This solves my issue, but is a manual step.

Here's my folder structure:
Workspace root: `workspace/`
Sources: `workspace/apps/my-project/src/*`
Bundle output: `workspace/dist/apps/my-project/*` (holds bundled `main.js` and `main.js.map`)

Currently, the map file be emitted with relative paths from the workspace root. So a source file in `workspace/apps/my-project/src/my-file.ts` gets emitted as `./apps/my-project/src/my-file.ts` in the map. This causes my IDE to resolve the path relative to the map file's directory, in my case `workspace/dist/apps/my-project/main.js.map`. This means the IDE searches for the source at `workspace/dist/apps/my-project/apps/my-project/src/my-file.ts` which is incorrect. 

### What does the proposed API of configuration look like?

Webpack's `SourceMapDevToolPlugin` has an option to explicitly set the `sourceRoot` that will be emitted in the file. 
https://webpack.js.org/plugins/source-map-dev-tool-plugin/#options. I'm not sure how this directly translates to `rspack`'s dev tool configuration. It seems `rspack`'s dev tool configuration is pretty limited from what I can gather, where the only configuration being `config.devtool`, which is just a string of flags.

I see that the [Devtool](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/options/devtool.rs#L17) struct only has an inner member for the flags (parsed from `config.devtool`). 

If the `sourceRoot` configuration should be adjacent to the current `config.devtool` config, I feel that the `config.devtool` would have to be expanded from a string, possibly to an object like `{flags?: string, sourceRoot?: string}`

However, automatically calculating the `sourceRoot` may be a nice place to start. The `sourceRoot` would have to be whatever the "context directory" or cwd is when the relative paths in the `sources` list is being generated.

**Comment by hardfist** [comment]
we need to support SourceMapDevToolPlugin first to provide this functionality. cc @ahabhgk

**Comment by wSedlacek** [comment]
I have also run into this issue. The best I could find was changing the `config.context` to the directory of my entry point then all my modules imported from my libs would work, but the source map for the app would still be broken.
