### ISSUE TITLE
rspack build a constant object into an empty object

### ISSUE THREAD

**Issue by TopGrd** [web-infra-dev/rspack#3864]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 24.51 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/git/nvs/default/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.10.0 - ~/.npm-global/bin/npm
    pnpm: 7.26.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Chrome Canary: 117.0.5920.0
    Safari: 16.5.1

### Details

<img width="773" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4202848/817f9b47-6cd6-46da-968a-5a07be4e72dd">
<img width="1065" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4202848/1b1e989d-8cbc-495a-9d1c-a8efdc3e3a7f">

### Reproduce Steps

This bug only reproduce in production build

**Comment by IWANABETHATGUY** [comment]
Please provide a minimum reproduction repository.

**Comment by TopGrd** [comment]
> Please provide a minimum reproduction repository.

Internal projects with minimal demos are not well reproduced. I now have to put this constant object directly into the method to solve my current problem. I didn't have this problem before with other build tools

**Comment by hardfist** [comment]
try disable minify and see whether the problem still exists

**Comment by tmayr** [comment]
For whatever is worth, we're currently experiencing something similar, but haven't been able to consistently reproduce and/or isolate. And anecdotally we're also seeing `a` being an empty object.

**Comment by ScriptedAlchemy** [comment]
@tmayr if you set optimization.minimize = false, what does it do?

**Comment by hardfist** [comment]
close for stale, if user met this issue again can file a new issue
