### ISSUE TITLE
建议优化开发时弹出日志颜值

### ISSUE THREAD

**Issue by faner11** [web-infra-dev/rspack#3867]
### What problem does this feature solve?

我rspack vite turbopack 都有使用，相比之下，rspack的日志要比后两者丑太多，这也是我在个人项目纠结是否用rspack的原因，希望可以美化一下日志。

vite 
<img width="579" alt="image" src="https://github.com/web-infra-dev/rspack/assets/26560612/fba3350f-48ff-4c56-8ec8-5d38f032fff0">

turbopack
<img width="627" alt="image" src="https://github.com/web-infra-dev/rspack/assets/26560612/0a28473c-b269-471e-81bc-3e8ed26b0992">
rspack
<img width="1086" alt="image" src="https://github.com/web-infra-dev/rspack/assets/26560612/2b6bd524-3644-487a-b2af-51c5649eee84">

### What does the proposed API of configuration look like?

-

**Comment by hardfist** [comment]
this is just webpack-style log generated by webpack-dev-server because we reuse webpack-dev-server

**Comment by nuintun** [comment]
还有网页 `overlay` 是真的简陋啊！

![企业微信截图_20230810160639](https://github.com/web-infra-dev/rspack/assets/1730277/b8873df3-9bc9-40cc-9020-c9d6fcbed9a4)

我自己封的 `koa2` 版 `webpack-dev-server`

https://github.com/nuintun/webpack-dev-service

![企业微信截图_20230810160804](https://github.com/web-infra-dev/rspack/assets/1730277/16ce80d9-d11b-4f14-a98f-dc483c629e2a)

建议优化，另外 `@rspack/core` 最好能移除 `dev-server` 依赖，`webapck` 默认是没依赖 `dev-server` 的！

**Comment by faner11** [comment]
我是建议带着dev-server，当大家都可以开箱即用的时候，你没有就会丢失市场

**Comment by nuintun** [comment]
@faner11 `@rspack/cli` 中集成就行了！

**Comment by hardfist** [comment]
rspack-core依赖webpack-dev-server是一个bug，我们将移除该依赖

**Comment by hardfist** [comment]
@nuintun  至于颜值问题，我们目前没有精力优化这块，我们接受改进日志颜值的 PR

**Comment by hardfist** [comment]
后续会兼容 error-overlay-webpack-plugin,这样的error overlay可以定制的更美观一些

**Comment by clijiac** [comment]
> 后续会兼容 error-overlay-webpack-plugin,这样的error overlay可以定制的更美观一些

试了下,0.3.1版本这个插件是可以用的.就是好像有点慢. 
ps 这个插件里面引用了querystring库,打个patch就可以用
```patch
diff --git a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
index 7f78947..4b13b0d 100644
--- a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
+++ b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
@@ -1,6 +1,6 @@
 /* global __resourceQuery */
 
-import querystring from 'querystring'
+import querystring from 'qs'
 import SockJS from 'sockjs-client'
 import formatWebpackMessages from 'react-dev-utils/formatWebpackMessages.js'
 import { reportBuildError, dismissBuildError } from 'react-error-overlay'

```

**Comment by hardfist** [comment]
> > 后续会兼容 error-overlay-webpack-plugin,这样的error overlay可以定制的更美观一些
> 
> 试了下,0.3.1版本这个插件是可以用的.就是好像有点慢. ps 这个插件里面引用了querystring库,打个patch就可以用
> 
> ```diff
> diff --git a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> index 7f78947..4b13b0d 100644
> --- a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> +++ b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> @@ -1,6 +1,6 @@
>  /* global __resourceQuery */
>  
> -import querystring from 'querystring'
> +import querystring from 'qs'
>  import SockJS from 'sockjs-client'
>  import formatWebpackMessages from 'react-dev-utils/formatWebpackMessages.js'
>  import { reportBuildError, dismissBuildError } from 'react-error-overlay'
> ```

奇怪，如果rspack不能用querystring那么webpack5应该也不能用？

**Comment by clijiac** [comment]
> > > 后续会兼容 error-overlay-webpack-plugin,这样的error overlay可以定制的更美观一些
> > 
> > 
> > 试了下,0.3.1版本这个插件是可以用的.就是好像有点慢. ps 这个插件里面引用了querystring库,打个patch就可以用
> > ```diff
> > diff --git a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> > index 7f78947..4b13b0d 100644
> > --- a/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> > +++ b/node_modules/error-overlay-webpack-plugin/dist/entries/devserver.mjs
> > @@ -1,6 +1,6 @@
> >  /* global __resourceQuery */
> >  
> > -import querystring from 'querystring'
> > +import querystring from 'qs'
> >  import SockJS from 'sockjs-client'
> >  import formatWebpackMessages from 'react-dev-utils/formatWebpackMessages.js'
> >  import { reportBuildError, dismissBuildError } from 'react-error-overlay'
> > ```
> 
> 奇怪，如果rspack不能用querystring那么webpack5应该也不能用？

应该是node14以后废弃了这个库的原因, error-overlay-webpack-plugin自己的GitHub也有人报这个issue的
https://github.com/gregberge/error-overlay-webpack-plugin/issues/107

**Comment by clijiac** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/1262789/31551fc8-016f-4d79-895a-d0ef40aa6d72)
中文变成乱码了, 不知道谁的问题

**Comment by hardfist** [comment]
@clijiac 给个复现demo吧,我本地测试正常 
![image](https://github.com/web-infra-dev/rspack/assets/8898718/60f45253-8050-48dd-af4f-ebc98635cdbc)

**Comment by clijiac** [comment]
> @clijiac 给个复现demo吧,我本地测试正常 ![image](https://user-images.githubusercontent.com/8898718/265309021-60f45253-8050-48dd-af4f-ebc98635cdbc.png)

@hardfist   加上这个就会乱码,去掉就不会
```
	devtool: isProduction ? "nosources-source-map" : "inline-source-map", // 报错的时候在控制台输出哪一行报错 https://www.rspack.dev/zh/config/devtool.html

```

repo 见 https://github.com/clijiac/testRsPack 就是create一个默认的 加上这个就乱码了
![image](https://github.com/web-infra-dev/rspack/assets/1262789/6ea6d1ae-62e2-4876-a8bc-24c8bfe81a2e)

**Comment by clijiac** [comment]
改成"nosources-source-map"直接不能用了, 感觉不是正常case, 我这边直接把"inline-source-map"改回"source-map"了, 能用就行..

**Comment by hardfist** [comment]
可能和sourcemap的处理有关， cc @ahabhgk

**Comment by hardfist** [comment]
@clijiac 测试了下webpack下也有同样问题

**Comment by hardfist** [comment]
@clijiac 定位了下是react-error-overlay的bug

**Comment by hardfist** [comment]
close it now, as you can use https://github.com/gregberge/error-overlay-webpack-plugin to custom error overlay, we may revisit this in the future
