### ISSUE TITLE
Codesandbox cannot be interactive after minimizing

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/rspack#3878]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: latest => 0.2.10

### Details

I use `@codesandbox/sandpack-react` in our project and it's normal to interact with codesandbox component in dev environment.But in production mode, the component cannot be interactive after minimizing the js code.

However, when i disable minimize in production, the component  is interactive again.

### Reproduce link

https://github.com/sanyuan0704/rspack-codesandbox-reproduction

### Reproduce Steps

1.`pnpm i `
2.`pnpm dev`, see the codesandbox component and you can see the preview ui
3. `pnpm build` and preview the output html file, then you will find that the preview ui is empty.
4. Didable the minimize in rspack, then the preview ui is normal in production.

**Comment by h-a-n-a** [comment]
Is there any error popped up?

**Comment by sanyuan0704** [comment]
> Is there any error popped up?

It does not have any error in the console panel.

**Comment by hardfist** [comment]
bump, @h-a-n-a have investigated this?

**Comment by sanyuan0704** [comment]
Any update？

**Comment by chenjiahan** [comment]
Can not reproduce this issue with Rspack 0.6.x
