### ISSUE TITLE
umi的项目该如何迁移？

### ISSUE THREAD

**Issue by baobao12356** [web-infra-dev/rspack#3885]
### What problem does this feature solve?

umi的项目该如何迁移到rswebpack?

### What does the proposed API of configuration look like?

umi的项目该如何迁移到rswebpack?

**Comment by chenjiahan** [comment]
你可以迁移到 Modern.js 框架哈，Modern.js 默认支持 Rspack 构建，并且框架能力也和 Umi 比较类似。

官网：https://modernjs.dev/

**Comment by h-a-n-a** [comment]
I'm going to close this issue, since this does not related to the core feature of Rspack. Feel free to reopen this if you have any further question.
