### ISSUE TITLE
配置target为node时,解析到了没有被引用的文件

### ISSUE THREAD

**Issue by hanyaxxx** [web-infra-dev/rspack#3888]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.78 GB / 15.88 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 9.5.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566

### Details

项目配置从webpack迁移, 目前webpack打包没有类似错误!

//以下rules配置
const resourcePath = path.resolve(`./template/${templateName}`)

const rules = [
  {
    test: /\.(png|svg|jpg|jpeg|gif)$/i,
    type: 'asset/resource'
  },
  {
    test: /\.module\.s[ac]ss$/i,
    use: [
      {
        loader: 'sass-loader',
        options: {
          //importLoaders: 1,
          sourceMap: isDEV,
          additionalData: `@import "~@/${templateName}/src/assets/scss/variables.scss";`
        }
      }
    ],
    include: resourcePath,
    type: 'css/module'
  },
  {
    test: /\.s[ac]ss$/,
    use: [
      {
        loader: 'sass-loader',
        options: {
          // importLoaders: 1,
          sourceMap: isDEV,
          additionalData: `@import "~@/${templateName}/src/assets/scss/variables.scss";`
        }
      }
    ],
    include: resourcePath,
    exclude: /\.module\.s[ac]ss$/i,
    type: 'css'
  },
  //postcss
  {
    test: /\.s[ac]ss$/i,
    use: [
      {
        loader: 'postcss-loader',
        options: {
          postcssOptions: {
            plugins: [
              [
                'postcss-px-to-viewport',
                {
                  unitToConvert: 'px',
                  viewportWidth: 750,
                  unitPrecision: 5,
                  viewportUnit: 'vw',
                  fontViewportUnit: 'vw',
                  selectorBlackList: ['root'],
                  minPixelValue: 1,
                  mediaQuery: false,
                  exclude: [/node_modules/]
                }
              ]
            ]
          }
        }
      }
    ],
    include: resourcePath
  }
]

//以下项目base配置, rules会被merge进去
const config = {
  entry: path.resolve('./server/bin/www.ts'),
  //watch: true,
  target: ['node'],
  output: {
    publicPath: '/public/',
    filename: 'index.js',
    path: resourcePath
  },
  devtool: false,
  builtins: {
    progress: false,
    copy: {
      patterns: [
        {
          from: `./template/${templateName}/public/static`,
          to: './static'
        }
      ]
    }
  },
  plugins,
  stats: isDEV
    ? {
        preset: 'errors-warnings',
        reasons: true
      }
    : true
}

错误信息: 使用的文件名是B,结果错误提示的是A的引用,怀疑打包时把A引用读取进去了

error[javascript]: JavaScript parsing error
  ┌─ template\A\src\components\index.module.scss:1:1
  │
1 │ .container {
  │ ^ Expression expected
template\A 是未被引入的项目路径, 实际引用的路径是 template\B
因为 rules的 include 是动态匹配B项目的路径, 所以引入项目A的scass是无法识别的. 

但是入口匹配的是B项目, 怎么会把A项目的文件路径引入进来了?
ps:这份配置在webpack不会出现这种问题,是不是rspack解析路径会分析当前文件下的所有引用, 我是否要配置tsx,jsx的include选项?

### Reproduce Steps

 command: 'rspack',
 argv: ['build', '-c', './scripts/run/rspack/rspack.server.js', '--watch'],

**Comment by hardfist** [comment]
please provide repro demo

**Comment by hardfist** [comment]
This issue will be closed due to inactivity. Feel free to comment and reopen it if you have any further questions.
