### ISSUE TITLE
Support DynamicEntryPlugin and resolve.plugins

### ISSUE THREAD

**Issue by hhuwc** [web-infra-dev/rspack#3890]
### What problem does this feature solve?

There are serval questions i have meet during migrating  webpack to rspack compiler，i need Rspack team to help me  fix these problems.

the  Reproduce link is  https://github.com/hhuwc/migrate-to-rspack

### What does the proposed API of configuration look like?

https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/DynamicEntryPlugin.js#L17

https://webpack.js.org/configuration/resolve/#resolveplugins

**Comment by hhuwc** [comment]
Okay,   Rspack may not suit the building of complex applications  in current state

**Comment by hardfist** [comment]
1. resolve.plugins目前的确不支持，你有什么定制resolve.plugin的需求？如果是alias的话，目前内置了alias的方案
2. DynamicEntryPlugin目前也不支持

**Comment by hhuwc** [comment]
感谢回复：
1.  resolve  plugin 用来做引用限制的，在小程序场景中有a包 不能引用 b包中的内容这种限制
2. DynamicEntryPlugin   是因为小程序场景中入口是由app.json 中配置的页面决定的，所以需要动态创建的能力


> 1. resolve.plugins目前的确不支持，你有什么定制resolve.plugin的需求？如果是alias的话，目前内置了alias的方案
> 2. DynamicEntryPlugin目前也不支持
> 3. 其他问题好像在最新的rspack版本里不能复现

**Comment by hardfist** [comment]
1. 可以通过resolve hook来实现(暂未实现)
2. dynamicEntryPlugin目前可以通过修改options.entry可以动态组装entry实现
如果你想用来实现小程序编译的话，我之前正好实现过 https://github.com/hardfist/rspack-miniapp，可供参考

**Comment by hardfist** [comment]
DynamicEntryPlugin is supported now, and we don't plan to support  resolve.plugins in near future(you can use https://www.rspack.dev/api/plugin-api/normal-module-factory-hooks#resolve instead) , so close this issue
