### ISSUE TITLE
support get reference chunkGroups via chunk.groupsIterable

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3896]
### What problem does this feature solve?

https://github.com/vuejs/preload-webpack-plugin/blob/master/src/lib/does-chunk-belong-to-html.js#L45

<img width="438" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/f0423066-74af-4c91-ae16-73c12c13a7be">

### What does the proposed API of configuration look like?

just like webpack:
https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/Chunk.js#L516

**Comment by 9aoy** [comment]
also need `chunkGroup.getParents()`

<img width="522" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/5e2b0f62-f703-4f55-ab6d-ebd5e9b66e9c">

https://github.com/vuejs/preload-webpack-plugin/blob/master/src/lib/does-chunk-belong-to-html.js#L53

**Comment by bvanjoi** [comment]
closed by https://github.com/web-infra-dev/rspack/pull/4641
