### ISSUE TITLE
打包的时候没有报任何错误,但是执行index.js文件报错

### ISSUE THREAD

**Issue by hanyaxxx** [web-infra-dev/rspack#3897]
### System Info

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz     
    Memory: 3.63 GB / 15.88 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566

### Details

E:\nextssr\sandwich-react>node ./dist-dev/hernest-m/server/index.js
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'E:\nextssr\sandwich-react\dist-dev\hernest-m\server\templates\dev_error.html'

const config = {
  entry: path.resolve('./server/bin/www.ts'),
  //watch: true,
  target: ['node'],
  output: {
    publicPath: '/public/',
    filename: 'index.js',
    path: resourcePath
  },
  devtool: false,
  builtins: {
    // progress: false,
    copy: {
      patterns: [
        {
          from: `./template/${templateName}/public/static`,
          to: './static'
        }
      ]
    }
  },
  plugins,
  stats: isDEV
    ? {
        preset: 'errors-warnings',
        reasons: true
      }
    : true
}

### Reproduce Steps

rspack build

**Comment by hardfist** [comment]
can you paste your config to code block and format it, it is really hard to read now

**Comment by hanyaxxx** [comment]
Please ignore the two plugins OpenBrowserPlugin and NodePolyfill, whether used or not will not affect the final result

**Comment by hanyaxxx** [comment]
Please ignore the two plugins OpenBrowserPlugin  and NodePolyfill  , whether used or not will not affect the final result

**Comment by hardfist** [comment]
please provide repro demo
