### ISSUE TITLE
Faile to resolve ./xxx.css imported in less file

### ISSUE THREAD

**Issue by ja-plus** [web-infra-dev/rspack#3913]
### System Info

System:
OS: Windows 10 10.0.19041
CPU: (4) x64 Intal(R) Xeon (R) Gold 5218 CPU @ 2.30GHz
Memory: 1.43 GB / 7.99 GB
Binaries:
Node: 16.17.1
npm: 8.19.4
Browsers:
Chrome: 84.0.4147.125
npmPackages: 
@rspack/cli: ^0.2.10 => 0.2.10
@rspack/plugin-html: ^0.2.10 => 0.2.10

### Details

error[internal]: Failed to resolve variable.css in css | D:\code\xxxx\...\node_modules\less-loader\dist\cjs.js!D:\code\...\src\style\index.less

less:^4.1.3
less-loader:^11.1.0

### Reproduce Steps

index.less:
```less
@import './variable.css';
...
```
variable.css:
```css
:root {
  --red-rgb: 255,43,72;
  ...
}
```
rspack.config.js:
```js
{
  test: /\.less$/,
  use: ['less-loader'],
  type: 'css'
}
```

**Comment by h-a-n-a** [comment]
You should set the `Rule.resolve.preferRelative` to `true`
This may sounds a little bit weird to everyone, but it is actually the same as webpack.

Less-loader transforms the code as follows:
```less
import './variable.css';
```
⬇️
```css
import 'variable.css';
```
`preferRelative` is not a default type for those who leverages the `type: "css"`, you should set it by yourself.

**Comment by h-a-n-a** [comment]
Currently, we don't want to diverge the implementation from webpack. Feel free to reopen this if you have any further questions.

**Comment by h-a-n-a** [comment]
Raise an issue on Webpack: https://github.com/webpack/webpack/issues/17569

**Comment by ja-plus** [comment]
Thanks for 'Rule.resolve.preferRelative=true'. it works

Another question:
I tried the following config:
```js
{
  test: /\.less$/,
  use: ['style-loader', 'css-loader', 'less-loader'],
}
```
The rspack didn't throw error, but the `variable.css` was ignored. The code in css didn't take effetc.
The webpack worked in this config.

**Comment by h-a-n-a** [comment]
> The rspack didn't throw error, but the variable.css was ignored. The code in css didn't take effetc.
@ja-plus What do you mean 'ignored'? Can you raise another issue for describing this issue? Let's keep this issue closed as this might be another bug.

**Comment by ja-plus** [comment]
[link issue](https://github.com/web-infra-dev/rspack/issues/3922)
