### ISSUE TITLE
Uncaught reference error : *_WEBPACK_IMPORTED_MODULE_0 is not defined . (Seems like a Parsing error for some .js files -> workaround mentioned as well )

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#3920]
### System Info

rspack v0.2.11

### Details

Hello, 
I run into the below error when I try to bundle a .js file using rspack :
![image](https://github.com/web-infra-dev/rspack/assets/93791633/311fa2fb-0dd8-4c23-967e-6042ef4aae66)

The source code of the file (keyboard.js) in question is :
```
var _a;
import { KeyCodes } from './KeyCodes';
var DirectionalKeyCodes = (_a = {},
    _a[KeyCodes.up] = 1,
    _a[KeyCodes.down] = 1,
    _a[KeyCodes.left] = 1,
    _a[KeyCodes.right] = 1,
    _a[KeyCodes.home] = 1,
    _a[KeyCodes.end] = 1,
    _a[KeyCodes.tab] = 1,
    _a[KeyCodes.pageUp] = 1,
    _a[KeyCodes.pageDown] = 1,
    _a);
/**
 * Returns true if the keycode is a directional keyboard key.
 */
export function isDirectionalKeyCode(which) {
    return !!DirectionalKeyCodes[which];
}
/**
 * Adds a keycode to the list of keys that, when pressed, should cause the focus outlines to be visible.
 * This can be used to add global shortcut keys that directionally move from section to section within
 * an app or between focus trap zones.
 */
export function addDirectionalKeyCode(which) {
    DirectionalKeyCodes[which] = 1;
}
/**
 * Removes a keycode to the list of keys that, when pressed, should cause the focus outlines to be visible.
 * This can be used to remove global shortcut keys that directionally move from section to section within
 * an app or between focus trap zones.
 */
export function removeDirectionalKeyCode(which) {
    delete DirectionalKeyCodes[which];
}
```
In the generated bundle it complains at the property accessing syntax:
![image](https://github.com/web-infra-dev/rspack/assets/93791633/1168593c-c2b9-4621-b956-37df7148fa40).
I do not see any harmony import for the _KeyCodes__WEBPACK_IMPORTED_MODULE_0 above. 

However if I add a dummy code to access the KeyCode directly as below, I do not run into that problem.
```
var _dummy = KeyCodes.left;
console.log(_dummy);
```
And in the generated bundled code I can see the harmony import correctly for KeyCodes__WEBPACK_IMPORTED_MODULE_0_
![image](https://github.com/web-infra-dev/rspack/assets/93791633/1a07d454-679a-4965-95c4-b2f9fa6fed90)

I think there is a bug with how rspack parses the property accessors syntax in .js files ? 

### Reproduce Steps

source code posted above ^

**Comment by f0reclone** [comment]
I did occur the same bug when switching from `0.2.10` to `0.2.11`

**Comment by TopGrd** [comment]
Version 0.2.11 has this problem，I temporarily locked the version 0.2.10 to solve this problem。
