### ISSUE TITLE
Enhancement : expose RunTimeGlobals in rspack

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#3921]
### System Info

rspackv :0.2.11

### Details

we have many webpack plugins which import the RunTimeGlobals from webpack. It would be great if we have such exports in rspack as well. 
![image](https://github.com/web-infra-dev/rspack/assets/93791633/4dd5377d-b16d-4f0b-9a92-6d63e73e97de)

### Reproduce Steps

N/A

**Comment by lippzhang** [comment]
I want to contribute this code
