### ISSUE TITLE
使用npm运行build命令时，插件上报的异常未正常退出

### ISSUE THREAD

**Issue by berwin0415** [web-infra-dev/rspack#3925]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 98.92 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.7 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @rspack/cli: latest => 0.2.11 

### Details

添加一个Error插件, 使用npm run build未退出

```js
class DemoPlugin {
    key = '';
    apply(compiler) {
        this.key = compiler.name ?? 'D_DemoPlugin';
        compiler.hooks.compilation.tap(this.key, (compilation) => {
            compilation.errors.push(error);
        });
    }
}
```

```js
module.exports = {
	context: __dirname,
	entry: {
		main: "./src/main.tsx"
	},
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		]
	},
	module: {
		rules: [
			{
				test: /\.svg$/,
				type: "asset"
			}
		]
	},
	plugins: [
		new DemoPlugin()
	]
};

```

### Reproduce Steps

1. npm create rspack 创建一个react-ts模板
2. 在rspack.config.js中添加一个插件，这个插件仅上报一个error
3. 分别使用npm和yarn1.x运行build命令，结果不一致，期望正常因error退出

**Comment by hardfist** [comment]
请提供复现demo链接
