### ISSUE TITLE
Production build with style-components breaks at runtime

### ISSUE THREAD

**Issue by arananegra** [web-infra-dev/rspack#3928]
### System Info

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 96.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.200
    Safari: 16.6

### Details

From @rspack/cli 0.2.9 and so on (0.2.8 and previous versions don't have this problem), the production builds will break if you are using styled-components (or, in my case through a library). 

The build finishes however, the browser will display a blank screen and log this:

```
styled-components.browser.esm.js:1 Uncaught TypeError: null is not a function
    at e (styled-components.browser.esm.js:1:20991)
    at e_ (styled-components.browser.esm.js:1:21239)
    at styled-components.browser.esm.js:1:22321
    at Array.forEach (<anonymous>)
    at 2666 (styled-components.browser.esm.js:1:22294)
    at f (runtime.js?cb8c77bf3bc6521eb5d6:1:126)
    at 98671 (app.js?cb8c77bf3bc6521eb5d6:1:204268)
    at f (runtime.js?cb8c77bf3bc6521eb5d6:1:126)
    at 91682 (app.js?cb8c77bf3bc6521eb5d6:1:249432)
    at f (runtime.js?cb8c77bf3bc6521eb5d6:1:126)
```

If you try the development build (changing `mode: "development"`) the problem doesn't persist.

### Reproduce link

https://github.com/arananegra/rspack-project/tree/master

### Reproduce Steps

1. npm i
2. npm run build:dev (is the development config file but with "production" enabled so that you can reproduce and debug the bug)
3. serve dist-dev (or similar)

**Comment by underfin** [comment]
Sorry for later feedback, it casued by treeshaking bug. Our team is working on new tree shaking implement to aligin webpack. Please give us some times to focus new implement, thanks.
