### ISSUE TITLE
[Error: error[internal]: Block(Identifier(u!("t"))) doesn't have corresponding ChunkGroup.doesn't have corresponding ChunkGroup

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3932]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 108.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.1 - ~/Library/Caches/fnm_multishells/8062_1691650415207/bin/node
    Yarn: 3.2.2 - ~/Library/Caches/fnm_multishells/8062_1691650415207/bin/yarn
    npm: 8.19.1 - ~/Library/Caches/fnm_multishells/8062_1691650415207/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: nightly => 0.2.11-canary-28bb895-20230810010349 

### Details

![image](https://github.com/web-infra-dev/rspack/assets/8898718/732e815f-12a6-4481-b4a1-7b711d36d9e2)

### Reproduce link

https://github.com/hardfist/AFFiNE/tree/try-rspack

### Reproduce Steps

1. run yarn install
2. run yarn dev and continue press 'enter' key

**Comment by hyf0** [comment]
The problem could reproduced with `entry.{name}.asyncChunks: true`.
