### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by huanglsj** [web-infra-dev/rspack#3936]
### System Info

win10
"@rspack/plugin-node-polyfill": "^0.2.11"
"@rspack/cli": "^0.2.11"

### Details

![image](https://github.com/web-infra-dev/rspack/assets/23072516/a58fbe28-3f63-4e7b-b01f-0ad21240b066)
![image](https://github.com/web-infra-dev/rspack/assets/23072516/8ead5f3c-2318-4de5-b389-e1d8d79aa4e1)

### Reproduce Steps

npm run serve

**Comment by h-a-n-a** [comment]
This behaves the same as webpack5. See more at https://www.rspack.dev/guide/language-support.html#node-polyfills. Feel free to reopen if you have any further questions.
