### ISSUE TITLE
UMD build: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by TopGrd** [web-infra-dev/rspack#3940]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 33.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/git/nvs/default/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.10.0 - ~/.npm-global/bin/npm
    pnpm: 7.26.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 118.0.5939.0
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: latest => 0.2.11 
    @rspack/plugin-minify: ^0.1.12 => 0.1.12 
    @rspack/plugin-node-polyfill: latest => 0.1.12 

### Details

Build error when building with library and optimization config at the same time. Uncaught ReferenceError: require is not defined
<img width="706" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4202848/fbdda0fc-205b-489d-bef0-ad4f835cf3b5">
But when I remove the optimization configuration, every thing is ok.

### Reproduce link

https://github.com/TopGrd/rspack-umd-bug

### Reproduce Steps

1. npm i 
2. npm run build
3. serve ./dist

**Comment by underfin** [comment]
It is expected because you configure `externals`, the `externals` module always render to `require(xxx)`  at umd library.

**Comment by TopGrd** [comment]
> It is expected because you configure `externals`, the `externals` module always render to `require(xxx)` at umd library.

为啥移除 optimization 这个配置可以，另外虽然打包成require，但是这个require not defined 呀

**Comment by TopGrd** [comment]
<img width="891" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4202848/cadf4301-a859-4671-bcb1-fffc840afa61">
配置 optimization 后的报错，是因为这里M P都被赋值了 ，走到了下面的require逻辑

**Comment by TopGrd** [comment]
未配置时为报错，是因为 exports module 都是undefined 走的是下面的逻辑
<img width="788" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4202848/3c955d63-38a4-4f81-8b1e-401dcde12d18">



**所以问题是因为配置了 optimization   打包出来的产物有差异**
