### ISSUE TITLE
[Bug] In production build, the bundle appear runtime error when using `react-markdown`

### ISSUE THREAD

**Issue by sanyuan0704** [web-infra-dev/rspack#3941]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 150.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: latest => 0.2.11 
    @rspack/plugin-minify: ^0.2.10 => 0.2.10 

### Details

I use `react-markdown` in some components, but it appears runtime error `Uncaught ReferenceError: _normalize_js__WEBPACK_IMPORTED_MODULE_0_ is not defined
` in production.

![image](https://github.com/web-infra-dev/rspack/assets/39261479/eabd564c-f2c5-4715-9671-e320191b226d)

### Reproduce link

https://github.com/sanyuan0704/rspack-codesandbox-reproduction

### Reproduce Steps

- git checkout feat/add-react-markdown
- pnpm i
- pnpm build

**Comment by underfin** [comment]
It already fixed at https://github.com/web-infra-dev/rspack/pull/3929. Please use 0.2.11-canary-c6335d3-20230810034337 version to fix it.
