### ISSUE TITLE
When using the @mui/material library, there are no issues during development, but problems arise after packaging.

### ISSUE THREAD

**Issue by suxiaoshao** [web-infra-dev/rspack#3952]
### System Info

System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 64.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/Library/Caches/fnm_multishells/50124_1692009561527/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/50124_1692009561527/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.2.11 => 0.2.11

### Details

When using the @mui/material library, there is no problem with rspack serve, but there is a problem with rspack build. The issue lies in the file node_modules/@mui/material/styles/useTheme.js:

```js
'use client';

import * as React from 'react';
import { useTheme as useThemeSystem } from '@mui/system';
import defaultTheme from './defaultTheme';
import THEME_ID from './identifier';
export default function useTheme() {
  const theme = useThemeSystem(defaultTheme);
  if (process.env.NODE_ENV !== 'production') {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    React.useDebugValue(theme);
  }
  return theme[THEME_ID] || theme;
}
```

The line `theme[THEME_ID] || theme` causes an error during build. However, there is no problem when printing THEME_ID on the previous line (using this variable beforehand).

### Reproduce link

https://github.com/suxiaoshao/rspack-mui-bugs

### Reproduce Steps

```bash
pnpm install

pnpm dev

# Everything is normal.

pnpm build
pnpm preview

# This is where the problem arises.
```

**Comment by IWANABETHATGUY** [comment]
try nightly, this issue has been fixed, IIRC.

**Comment by IWANABETHATGUY** [comment]
feel free to reopen this issue if you have any further question.

**Comment by suxiaoshao** [comment]
> try nightly, this issue has been fixed, IIRC.

怎么使用nightly,有版本号吗

**Comment by hardfist** [comment]
> > try nightly, this issue has been fixed, IIRC.
> 
> 怎么使用nightly,有版本号吗

@rspack/cli@nightly
