### ISSUE TITLE
Deps error: external react can`t be used in main app.

### ISSUE THREAD

**Issue by MatrixAge** [web-infra-dev/rspack#3966]
### System Info

  System:
    OS: macOS 13.5
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900KF
    Memory: 17.94 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/local/bin/node
    npm: 9.7.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
    Watchman: 2023.06.12.00 - /usr/local/bin/watchman

### Details

![image](https://github.com/web-infra-dev/rspack/assets/25472851/7c8521f5-46e8-4bd5-9327-e85b09e463cb)

The error shown above occurs when applying a local package within a monorepo for the application. However, in reality, React can be required (as seen in the locally packaged code through console.log), but it still throws an error at the code level (only for React; other external dependencies are recognized within the main application).

Currently, a method has been discovered to avoid the error, but it will incur a slight additional compilation overhead:

![image](https://github.com/web-infra-dev/rspack/assets/25472851/4bdd19b0-b0eb-493d-a094-867a3bd3cd64)

Local menorepo package config:
![image](https://github.com/web-infra-dev/rspack/assets/25472851/451bef36-ca05-446c-bc40-d6747f2f8a9e)

### Reproduce Steps

upup.

**Comment by underfin** [comment]
Look like your menorepo packages is not install react, so react couldn't be resolved, but it worked fine using resolver.alias react, because the react is point to node_modules of main package.

**Comment by MatrixAge** [comment]
> Look like your menorepo packages is not install react, so react couldn't be resolved, but it worked fine using resolver.alias react, because the react is point to node_modules of main package.

![image](https://github.com/web-infra-dev/rspack/assets/25472851/d2a95f6e-8326-408b-a131-e3ab836e2aef)
In fact, my subpackage has installed React. What puzzles me is that 'fast-equals' has also been marked as external. Why can 'fast-equals' still function properly?

**Comment by underfin** [comment]
Please give a reproduction for this.

**Comment by MatrixAge** [comment]
Case solved: It's due to different little versions of React being used in the sub-package and the main application.

![image](https://github.com/web-infra-dev/rspack/assets/25472851/e0b861f6-9c44-4538-a4d2-44acc2b9e3d1)

![image](https://github.com/web-infra-dev/rspack/assets/25472851/22be615b-9a07-4453-9800-5c12ed42e6f4)

Even a slight difference in minor versions can lead to errors.It might be because the main application is using an experimental version of React.

**Comment by MatrixAge** [comment]
https://github.com/MatrixAge/rspack_reproduces


However, I believe the underlying cause of this issue needs further investigation. It might be worth mentioning in the monorepo discussions in the future.
