### ISSUE TITLE
improve rspack progress style 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3967]
### What problem does this feature solve?

webpackbar has more pretty progress style than progressPlugin, we may following webpackbar way to improve the progress style.
<img width="1076" alt="截屏2023-08-16 11 33 59" src="https://github.com/web-infra-dev/rspack/assets/8898718/cd0f5abb-1de2-4e2e-8bce-6f7397efafa1">

### What does the proposed API of configuration look like?

No api needed, only change the style

**Comment by Hamzakh777** [comment]
assign it to me, I'll work on it

**Comment by hardfist** [comment]
> assign it to me, I'll work on it

thanks in advance
