### ISSUE TITLE
windows 11 使用scoop安装的pnpm 创建项目执行pnpm dev报错：系统找不到指定的路径。 (os error 3)

### ISSUE THREAD

**Issue by chenjiandmw** [web-infra-dev/rspack#3968]
### System Info

System:
OS: Windows11
Binaries:
scoop: 0.3.1
pnpm: 8.6.11

### Details

![image](https://github.com/web-infra-dev/rspack/assets/54097812/442b201d-5bbb-43d9-b2bc-8d9cb42572d9)

![image](https://github.com/web-infra-dev/rspack/assets/54097812/207de097-376d-4c8d-b5b1-15caf30aa47c)

![image](https://github.com/web-infra-dev/rspack/assets/54097812/81c99175-e976-4e8f-9e6c-ecb9f5f0895a)

### Reproduce Steps

1. 安装scoop
2. 使用scoop安装pnpm
3. pnpm create rspack@latest
4. cd xxx
5. pnpm install
6. pnpm dev

**Comment by h-a-n-a** [comment]
是什么项目呢？有没有复现链接可以发一下，是不是引用了没有兼容 windows 的 loader？

**Comment by chenjiandmw** [comment]
@h-a-n-a 可能无法提供在线复现链接，项目就是通过 rspack cli 创建的初始项目, 没有修改任何内容，目前我测试只有通过scoop安装pnpm才会出现该问题

**Comment by chenjiahan** [comment]
Closed because we can not reproduce this issue. Feel free to reopen it if it is needed.
