### ISSUE TITLE
`$ReactRefreshRuntime$.refresh is not a function` error

### ISSUE THREAD

**Issue by oleksify** [web-infra-dev/rspack#3984]
### System Info

**System:**

   - OS: macOS 13.5
   - CPU: (8) arm64 Apple M1
   - Memory: 102.47 MB / 16.00 GB
   - Shell: 3.6.1 - /opt/homebrew/bin/fish
   
**Binaries:**
- Node: 18.12.1 - ~/.local/share/rtx/installs/node/18.12.1/bin/node
- Yarn: 1.22.19 - ~/.local/share/rtx/installs/yarn/1.22.19/bin/yarn
- npm: 9.8.1 - ~/.local/share/rtx/installs/node/18.12.1/bin/npm
- pnpm: 8.6.12 - ~/.local/share/rtx/installs/node/18.12.1/bin/pnpm

**Browsers:**
  - Firefox: 116.0.3

**npmPackages:**
- @rspack/cli: 0.2.12 => 0.2.12
- @rspack/plugin-node-polyfill: 0.2.12 => 0.2.12

### Details

Starting from version `0.2.9` I noticed `$ReactRefreshRuntime$.refresh is not a function` error in browser dev tools console. When I downgrade to `0.2.8` the issue is gone.

### Reproduce Steps

I can't share link to our private repo, but it's basically:

- `yarn rspack serve -c rspack/rspack.config.dev.cjs` 

The config is pretty basic, so I doubt it's something there. Also, I did not set `builtins.react` manually, defaults are used. We're using React 17.

**Comment by h-a-n-a** [comment]
Please provide a reproduction repo
