### ISSUE TITLE
May I ask if the externalsType in webpack.config.js can support multiple ?

### ISSUE THREAD

**Issue by lzs246** [web-infra-dev/rspack#3986]
### What problem does this feature solve?

Feat:
```js
// source.js
import a from 'a';
import b from 'b';
a;
b;

// through rspack build, Get dist.js

// dist.js
const a = require('a')
const b = global.b
a;
b;
```
I found that only one **externalsType** can exist in the configuration file，Can there be multiple externalsTypes？Or may I ask if there is any other way to complete it
Thank!

### What does the proposed API of configuration look like?

```js
{
 externals: {
    a: {
      type: "commom.js",
      value: "a"
    },
     b: {
      type: "global",
      value: "b"
    },
  },
}
```

**Comment by hardfist** [comment]
https://webpack.js.org/configuration/externals/#:~:text=similar%20to%20the%20string%20syntax%2C%20you%20can%20specify%20the%20external%20library%20type%20with%20the%20%24%7Bexternalstype%7D%20%24%7Blibraryname%7D%20syntax%2C%20in%20the%20first%20item%20of%20the%20array%2C%20for%20example%3A supported

**Comment by lzs246** [comment]
Thank!
