### ISSUE TITLE
偶现编译后icon乱码

### ISSUE THREAD

**Issue by congxiaobai** [web-infra-dev/rspack#3991]
### System Info

System:
OS: macOS 13.4.1
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 426.29 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
Yarn: 1.22.17 - ~/.nvm/versions/node/v16.0.0/bin/yarn
npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
pnpm: 7.27.0 - ~/.nvm/versions/node/v16.0.0/bin/pnpm
Browsers:
Chrome: 115.0.5790.170
Safari: 16.5.2
npmPackages:
@rspack/cli: 0.2.11 => 0.2.11
@rspack/dev-server: 0.2.11 => 0.2.11

### Details

1.使用某第三方组件时。偶现icon乱码
正常是如下：
![image](https://github.com/web-infra-dev/rspack/assets/20089891/04e82ca5-53c2-4037-9964-51a5feeeb59e)

![image](https://github.com/web-infra-dev/rspack/assets/20089891/e552c53e-ad58-4a98-a1e3-3747ba80f238)
2. css  配置如下
```
 {
                    test: /\.s[ac]ss$/,
                    use: [
                        {
                          loader: 'sass-loader',
                          options: {
                            implementation: require('sass'),
                            sassOptions: {
                                 outputStyle: 'expanded',
                            },
                          },
                        },
                      ],
                    type: 'css',
                },
                {
                    test: /\.less$/,
                    use: ['less-loader'],
                    type: 'css',
                },
                {
                    test: /\.css$/,
                    use: [
                        {
                         loader: 'postcss-loader',
                          options: {
                            postcssOptions: {
                                 outputStyle: 'expanded',
                            },
                          },
                        },
                      ],
                    type: 'css',
                },
```

### Reproduce Steps

偶现，且只在线上环境出现。

**Comment by h-a-n-a** [comment]
Please provide a reproduction repo

**Comment by congxiaobai** [comment]
https://github.com/congxiaobai/rspack-css-icon-bug
css中存在roo-icon,源码部分为：
![image](https://github.com/web-infra-dev/rspack/assets/20089891/1b1a50a5-c82d-46c3-a14d-8eba9e60d2b6)

但是编译之后：
![image](https://github.com/web-infra-dev/rspack/assets/20089891/a360f83c-9c75-47bf-ba83-451e18f8857f)

**Comment by congxiaobai** [comment]
>您好，已经贴上了复现demo。请帮忙看一下，非常感谢

**Comment by ununian** [comment]
@congxiaobai 如果的发布后偶发的话，会不会是网络问题啊？ 输出的这个框框是没问题的，是压缩 Unicode 来的，webpack 那边是由 OptimizeCssAssetsPlugin 的 normalizeUnicode 控制的

**Comment by hardfist** [comment]
@ununian @congxiaobai  既然这是个swc-css压缩的bug，可以麻烦在swc-css提一个issue吧

**Comment by jetBn** [comment]
怎么解决的 ？ 先打包icon都是乱码

**Comment by k4281613** [comment]
现在有没解决办法啊

**Comment by hardfist** [comment]
> 现在有没解决办法啊
如果有问题，请额外提新的issue

**Comment by jzsn2018** [comment]
用了  rspack.CssExtractRspackPlugin.loader 感觉必现了。。。
