### ISSUE TITLE
Support aliased resolving 

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4009]
Currently, Due to the fact that nodejs-resolver does not support resolving with alias, Rspack does not support resolve aliased loader. We should fix this.

_Originally posted by @h-a-n-a in https://github.com/web-infra-dev/rspack/pull/4008#discussion_r1301293077_

**Comment by Boshen** [comment]
Where are the tests for "resolve aliased loader"? Let's try and turn them on so we can close this issue.

**Comment by hardfist** [comment]
> Where are the tests for "resolve aliased loader"? Let's try and turn them on so we can close this issue.

@Boshen  try turn on this for oxc resolver https://github.com/web-infra-dev/rspack/pull/4008/files#diff-cd6dcd934ac301a223707a61b3bba520be1c3ee63a00ba24e6cbe8bb79ccf266R6

**Comment by Boshen** [comment]
This PR from webpack indicates that this should be solved on the Rspack side?

https://github.com/webpack/webpack/pull/3445/files#diff-d73b6d4cb18e533b6d82864565571fb5d0b87455a67503db7464eff699bfea1a

**Comment by Narretz** [comment]
Any news on this? This kinda makes developing impossible, because re-compilation on file changes doesn't work.

**Comment by h-a-n-a** [comment]
> So this is about the `alias` option in the config, right?
> 
> It does compile with aliases, but re-compilation on file changes doesn't work if the file path is imported via alias. Is this the correct issue for this problem, and are there any news on this?

@Narretz I assume this is a different issue than this one, would you please create another issue?

**Comment by Narretz** [comment]
I believe this is still unresolved, at least it's not clear if everything os tested correctly.

**Comment by h-a-n-a** [comment]
bump
