### ISSUE TITLE
Looks like iframe causes infinite loops of rspack logs

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#4015]
### System Info

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 4.70 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.1
  npmPackages:
    @rspack/cli: ^0.2.12 => 0.2.12

### Details

Here is an example of simple application for display react component stories:
https://github.com/sima-land/ui-nucleons/tree/showcase

In this package there is 
- main html for see list of stories with ability to pick from list and see result in iframe
- story html for display selected story 

When i run `npm run showcase` it runs `rspack serve`

When i change some source file contents it causes infinite logs in console:
<img width="462" alt="изображение" src="https://github.com/web-infra-dev/rspack/assets/13140130/8299c461-85ae-4437-aea5-7322ee64b1f8">

For example i just change `./.showcase/src/index.tsx` and this happens

### Reproduce Steps

1. clone https://github.com/sima-land/ui-nucleons/tree/showcase
2. `npm i`
3. `npm run showcase`
4. open in browser `http://localhost:8080` and open developer console
5. change `.sowcase/src/index.tsx` (for example just add some text to jsx in any place)
6. see infinite logs in console `[HMR] Nothing hot updated`

**Comment by underfin** [comment]
Sorry for later feedback, It  cuased by your config `targe: web`, but `chunkFormat: 'commonjs'`. It will caused runtime can't loading the update manifest file.

**Comment by krutoo** [comment]
@underfin but in webpack there is no such error with same config

**Comment by underfin** [comment]
> @underfin but in webpack there is no such error with same config

Can you debugger this at your webpack config at webpack dist.
```

function hotCheck(applyOnUpdate) {
	if (currentStatus !== "idle") {
		throw new Error("check() is only allowed in idle status");
	}
	return setStatus("check")
		.then(__webpack_require__.hmrM) // __webpack_require__.hmrM is undefined
		.then(function (update) {
			if (!update) {
				return setStatus(applyInvalidatedModules() ? "ready" : "idle").then(
					function () {
						return null;
					}
				);
			}

			return setStatus("prepare").then(function () {
				var updatedModules = [];
				currentUpdateApplyHandlers = [];

				return Promise.all(
                                             // __webpack_require__.hmrC is also not inject
					Object.keys(__webpack_require__.hmrC).reduce(function (  
						promises,
						key
					) {
						__webpack_require__.hmrC[key](
							update.c,
							update.r,
							update.m,
							promises,
							currentUpdateApplyHandlers,
							updatedModules
						);
						return promises;
					},
					[])
				).then(function () {
					return waitForBlockingPromises(function () {
						if (applyOnUpdate) {
							return internalApply(applyOnUpdate);
						} else {
							return setStatus("ready").then(function () {
								return updatedModules;
							});
						}
					});
				});
			});
		});
}
```

**Comment by krutoo** [comment]
@underfin not sure that understand, what should i do with this function?

**Comment by underfin** [comment]
> @underfin but in webpack there is no such error with same config

Please provider your reproduction.

**Comment by krutoo** [comment]
It looks like I was wrong and it turned out that the behavior is identical to webpack
