### ISSUE TITLE
解析html ejs模版时报错

### ISSUE THREAD

**Issue by sunft1996** [web-infra-dev/rspack#4039]
### System Info

System:
  OS: macOS 13.4
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 63.73 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 14.1.0 - /usr/local/opt/nvm/versions/node/v14.1.0/bin/node
  npm: 6.14.4 - /usr/local/opt/nvm/versions/node/v14.1.0/bin/npm
Browsers:
  Chrome: 116.0.5845.96
  Safari: 16.5

### Details

rspack配置：
```js
html: [
            {
                meta: {
                    manifest: manifestName,
                },
                template: path.join(__dirname, './public/index.html'),
                filename: 'index.html',
                inject: 'head',
            },
],
```
index.html模版：
```html
<body>
  <div id="vite-react"></div>

  <% if (process.env.NODE_ENV==='development' ) {%>
    <script type="systemjs-importmap">
```
报错如下：
```shell
error[html]: HTML parsing error
   ┌─ public/index.html:19:4
   │
19 │   <% if (process.env.NODE_ENV==='development' ) {%>
   │    ^ Invalid first character of tag name



error[html]: HTML parsing error
   ┌─ public/index.html:34:4
   │
34 │   <% } else {%>
   │    ^ Invalid first character of tag name
```

### Reproduce Steps

rspack serve

**Comment by sunft1996** [comment]
背景：项目从webpack迁移，相同的配置webpack是正常的

**Comment by hardfist** [comment]
试下js版本的@rspack/html-plugin是否正常

**Comment by sunft1996** [comment]
> 

换@rspack/html-plugin是可以的

**Comment by ahabhgk** [comment]
rspack/plugin-html 和html-webpack-plugin 默认用的lodash template 作为模版引擎，builtins html 内置的dojang(rust 版ejs），这俩语法不太一样

**Comment by ahabhgk** [comment]
可以参考下dojang 或ejs 的文档改一下语法
