### ISSUE TITLE
Build dist  Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4044]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 29.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: ^0.3.0 => 0.3.0 
    @rspack/plugin-minify: ^0.2.12 => 0.2.12 

### Details

![image](https://github.com/web-infra-dev/rspack/assets/19773879/1a82498a-7bf1-4174-9552-2d003a36ff0c)

Require is not replaced with a runtime variable of __webpack_require__，so require can not be found at runtime. maybe implementing full AMD DEFINITIONS will fix this. refer https://github.com/webpack/webpack/blob/main/lib/dependencies/AMDDefineDependency.js#L20

### Reproduce link

https://github.com/jeromehan/rspack-demo.git

### Reproduce Steps

1. pnpm i 
2. pnpm run build 
3. cd dist
4. preview index.html

**Comment by underfin** [comment]
It's in our roadmap, but the priority is low. Here is already has same issue https://github.com/web-infra-dev/rspack/issues/4044, please track here.
