### ISSUE TITLE
Support webpack @sentry/webpack-plugin plugin

### ISSUE THREAD

**Issue by stephen-tyro** [web-infra-dev/rspack#4049]
### What problem does this feature solve?

[Sentry](http://sentry.io) is a popular service for catching bugs before they are reported. This plugin is used to upload the source maps to Sentry's service to match with the correct code when there is an error.

### What does the proposed API of configuration look like?

The proposed code for their current library are in [this readme](https://www.npmjs.com/package/@sentry/webpack-plugin) and looks like this:

```js
// webpack.config.js
const { sentryWebpackPlugin } = require("@sentry/webpack-plugin");

module.exports = {
  // ... other config above ...

  devtool: "source-map", // Source map generation must be turned on
  plugins: [
    sentryWebpackPlugin({
      org: process.env.SENTRY_ORG,
      project: process.env.SENTRY_PROJECT,

      // Auth tokens can be obtained from https://sentry.io/settings/account/api/auth-tokens/
      // and need `project:releases` and `org:read` scopes
      authToken: process.env.SENTRY_AUTH_TOKEN,
    }),
  ],
};
```

I have tested out the current plugin with rspack v0.3 and there seems to be some missing `tap` methods:
<img width="1182" alt="CleanShot 2023-08-28 at 12 54 54@2x" src="https://github.com/web-infra-dev/rspack/assets/117398188/7ed0325c-0a78-4028-8c5c-f025491ec584">

The `compilation.hooks.childCompiler` seems to be `undefined` in the file mentioned above:
![CleanShot 2023-08-28 at 12 55 54@2x](https://github.com/web-infra-dev/rspack/assets/117398188/2c440dbb-9fbb-484e-94d6-e9b6ac3dfe32)

**Comment by h-a-n-a** [comment]
Created an issue for this: https://github.com/web-infra-dev/rspack/issues/4066

**Comment by declanchiu** [comment]
I'm sorry, but can I ask what this font is? It's not really the right place to ask, but I couldn't find a way to contact you. @stephen-tyro 

![image](https://github.com/web-infra-dev/rspack/assets/55419399/f7f621cc-d6ce-4676-9469-21fd628d941d)

**Comment by stephen-tyro** [comment]
> I'm sorry, but can I ask what this font is? It's not really the right place to ask, but I couldn't find a way to contact you. @stephen-tyro
> 
> ![image](https://user-images.githubusercontent.com/55419399/265356097-f7f621cc-d6ce-4676-9469-21fd628d941d.png)

Hi @declanchiu, the font is [Dank Mono](https://philpl.gumroad.com/l/dank-mono). I bought it a few years back for a small fee, but still enjoying it today!

**Comment by declanchiu** [comment]
> > I'm sorry, but can I ask what this font is? It's not really the right place to ask, but I couldn't find a way to contact you. 对不起，我能问一下这是什么字体吗？在这里问不合适，但我找不到联系你的方法。 @stephen-tyro
> > ![image](https://user-images.githubusercontent.com/55419399/265356097-f7f621cc-d6ce-4676-9469-21fd628d941d.png)
> 
> Hi @declanchiu, the font is [Dank Mono](https://philpl.gumroad.com/l/dank-mono). I bought it a few years back for a small fee, but still enjoying it today!你好，字体是 Dank Mono。我几年前花了一点钱买的，但现在仍然很喜欢！

Thank you very much, but in order not to pollute the current issues I chose to have to delete the question I just asked, have a great day and thanks again.  😃

**Comment by declanchiu** [comment]
Thank you very much, but in order not to pollute the current issues I chose to have to delete the question I just asked, have a great day and thanks again. 😃
&nbsp;


coder_zj
***@***.***

前端开发


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月4日(星期一) 下午4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [web-infra-dev/rspack] Support webpack @sentry/webpack-plugin plugin (Issue #4049)





  
I'm sorry, but can I ask what this font is? It's not really the right place to ask, but I couldn't find a way to contact you. 
对不起，我能问一下这是什么字体吗？在这里问不合适，但我找不到联系你的方法。 @stephen-tyro
 

  
Hi @declanchiu, the font is Dank Mono. I bought it a few years back for a small fee, but still enjoying it today!
你好，字体是 Dank Mono。我几年前花了一点钱买的，但现在仍然很喜欢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
直接回复此邮件，在 GitHub 上查看，或取消订阅。
You are receiving this because you were mentioned.
您收到这个是因为您被提及了。  Message ID: ***@***.***&gt;

**Comment by hardfist** [comment]
https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/407 @declanchiu @stephen-tyro  tracking the sentry progress here

**Comment by yanhaijing** [comment]
我这测试是好使的，sourceMap 能上传到sentry
@sentry/webpack-plugin/1.20.1

**Comment by hardfist** [comment]
@stephen-tyro can you try @sentry/webpack-plugin@1.20.1, it seems work

**Comment by stephen-tyro** [comment]
@hardfist just got a chance to check now. It looks like v1.20.1 works atm and will be good to get us by for now. Would be nice if we could get the latest version work in the future just incase they do something to deprecate the old version.

@sentry/webpack-plugin is currently on v2.9.0

**Comment by decahedron1** [comment]
Just want to add that, with https://github.com/web-infra-dev/rspack/issues/4066 completed, I'm able to use `@sentry/webpack-plugin` v2.19.0 (latest) with rspack v0.7.5. I think this can be closed?

**Comment by hardfist** [comment]
> Just want to add that, with #4066 completed, I'm able to use `@sentry/webpack-plugin` v2.19.0 (latest) with rspack v0.7.5. I think this can be closed?

thanks

**Comment by inaseem** [comment]
Thank you for this info. @decahedron1 . I was about to open a new issue. I will update to the latest version now.
