### ISSUE TITLE
externals 配置在umd模式下编译报错

### ISSUE THREAD

**Issue by nanyuantingfeng** [web-infra-dev/rspack#4060]
### System Info

rspack : 0.3.0
pnpm : 8.6.12
node: 20.5.1
typescript: 5.0
os: macosx

### Details

 文档中说明是支持下面语法的, 但此配置编译将会抛出异常, adapter.js 中并没有支持此配置

externals: {
    lodash: {
      commonjs: 'lodash',
      amd: 'lodash',
      root: '_', // 指向全局变量
    },
  },
};

![image](https://github.com/web-infra-dev/rspack/assets/10877047/c359d88b-69e3-4b5e-ac2f-8fe4cfb8596e)

### Reproduce Steps

1. rspack.config.js: 

externals: {
    react: {
      commonjs: 'react',
      root: 'React', 
    },
  },
};

2. rspack build

**Comment by ahabhgk** [comment]
This will be fixed in v0.3.5 release
