### ISSUE TITLE
example build failed in windows ci

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4065]
https://github.com/web-infra-dev/rspack/actions/runs/6020915278/job/16333122639?pr=4061#step:8:368 the windows ci failed because of other reasons, fix it in other PR

_Originally posted by @hardfist in https://github.com/web-infra-dev/rspack/issues/4061#issuecomment-1698539953_

**Comment by h-a-n-a** [comment]
Seems to be caused by some memory issue. https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
