### ISSUE TITLE
Support childCompiler

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4066]
Support child compiler in order to support html-webpack-plugin and so on.
See: https://webpack.js.org/api/compilation-object/#createchildcompiler

**Comment by hardfist** [comment]
> 建议提升这件事件的优先级，sentry 插件用不了很痛苦

事实上sentry并不被child compiler阻塞，sentry使用unplugin实现了插件，unplugin已经支持了rspack，实际上只需要给sentry官方提一个-sentry-rspack-plugin即可

**Comment by hardfist** [comment]
it's supported
