### ISSUE TITLE
react demo not working

### ISSUE THREAD

**Issue by blurname** [web-infra-dev/rspack#4076]
### System Info

chrome 116

### Details

shows `invalid host header`
![image](https://github.com/web-infra-dev/rspack/assets/50226652/509bfc08-e76c-4f25-a483-e766f79b9f1a)
I also tried Modern.js demo, it worked

### Reproduce link

https://codesandbox.io/p/github/modern-js-dev/rspack-demo/main?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clehvnfj8000x3b6ifm9yoyfi%2522%253A%257B%2522key%2522%253A%2522clehvnfj8000x3b6ifm9yoyfi%2522%252C%2522name%2522%253A%2522Terminal%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev-app%2522%252C%2522port%2522%253A8080%252C%2522key%2522%253A%2522clehw4thl005l3b6iwrbsllbd%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev-app%2522%252C%2522key%2522%253A%2522clehw4rpt002h3b6imd77t1vz%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clehvnfj8000x3b6ifm9yoyfi%2522%252C%2522spacesOrder%2522%253A%255B%2522clehvnfj8000x3b6ifm9yoyfi%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Reproduce Steps

1. https://www.rspack.dev/guide/introduction.html
2. try `Rspack with React`

**Comment by zakuru** [comment]
I opened a PR for that: https://github.com/web-infra-dev/rspack-demo/pull/3
