### ISSUE TITLE
webAsync target support

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4080]
### What problem does this feature solve?

Treat references to http(s)://... and std:... as external and load them via async import() when used (Note that this external type is an async module, which has various effects on the execution).

### What does the proposed API of configuration look like?

[externalsPresets.webAsync](https://webpack.js.org/configuration/externals/#externalspresets:~:text=boolean-,webAsync,-Treat%20references%20to)

**Comment by lippzhang** [comment]
I'm interested, can you assign it to me?

**Comment by ahabhgk** [comment]
Thanks in advance

**Comment by ahabhgk** [comment]
Some implement guide: we already have a `HttpExternalsRspackPlugin` for `target.web`, and for `target.webAsync` you can add async support to it, the only different between `target.web` and `target.webAsync` is [it use `import` as the externalType](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L135) and [`target.web` use `module` as the externalType](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L152)

for reference, the webpack code: https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L119-L138

**Comment by lippzhang** [comment]
> Some implement guide: we already have a `HttpExternalsRspackPlugin` for `target.web`, and for `target.webAsync` you can add async support to it, the only different between `target.web` and `target.webAsync` is [it use `import` as the externalType](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L135) and [`target.web` use `module` as the externalType](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L152)
> 
> for reference, the webpack code: https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/WebpackOptionsApply.js#L119-L138

Thank you very much, I will study it
