### ISSUE TITLE
not allow use swc target and env configuration toghether

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4081]
we should not allow use jsc.target and env toghether, since they are incompatible and may cause unexpected behavior
![image](https://github.com/web-infra-dev/rspack/assets/8898718/49e14c25-7880-4fcd-9579-db98abcb3ca7)

**Comment by hardfist** [comment]
guidance
you can use emit_diagnostic generate warnings for conflict options for rspack_loader_swc
https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_loader_swc/src/lib.rs#L80

**Comment by Hamzakh777** [comment]
assign it to me @hardfist

**Comment by hardfist** [comment]
thanks
