### ISSUE TITLE
Rspack dist uncertainty, execute multiple times  may produce unexpected dist, may also be the dist of the right.

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4112]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Apple M1
    Memory: 32.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: ^0.3.1 => 0.3.1 

### Details

<img width="981" alt="image" src="https://github.com/web-infra-dev/rspack/assets/19773879/550dd569-561c-4b4f-a3d0-48e7ffa3a681">
After several executions of packaging, the result, as shown in the figure, made me afraid to use Rspack again, perhaps because rust was unsure about performing parallel tasks.

### Reproduce link

https://github.com/jeromehan/vue-rspack-demo

### Reproduce Steps
execute multiple times

npm run build

**Comment by h-a-n-a** [comment]
I believe this is caused by the vue-loader's implementation. See this one for details: https://github.com/web-infra-dev/rspack/issues/4003#issuecomment-1689662380

**Comment by jeromehan** [comment]
> I believe this is caused by the vue-loader's implementation. See this one for details: [#4003 (comment)](https://github.com/web-infra-dev/rspack/issues/4003#issuecomment-1689662380). A fix to vue-loader is required to avoid parallel issue when it is called from Rust.

thanks

**Comment by hardfist** [comment]
@jeromehan sorry for causing problems for your, and since this is a bug and we're gonna fix it

**Comment by h-a-n-a** [comment]
@jeromehan Feel free to test it out with version: 0.3.1-canary-efd2bf0-20230906032925.

**Comment by jeromehan** [comment]
> @jeromehan Feel free to test it out with version: 0.3.1-canary-efd2bf0-20230906032925.

it is great
