### ISSUE TITLE
webpack-assets-plugin support

### ISSUE THREAD

**Issue by thinkey-yang** [web-infra-dev/rspack#4123]
We are using [webpack-assets-plugin](https://github.com/webdeveric/webpack-assets-manifest) to generate json file, but this plugin causes a runtime error with rspack. 
We use this plugin to get a list of assets for each entry， like:
```
"main": {
      "js": [
        "js/runtime.6b509e0d.js",
        "js/vendors.066af6ec2.js",
        "js/main.5f10cd1d.js"
      ],
      "css": [
        "css/vendors.ac89822e.css",
        "css/main.5ceab323.css"
      ]
    }
```
for microfront-end loading subapplications。
Do you have any plans to support this plugin? or there are other ways to do this with rspack

**Comment by hardfist** [comment]
try https://github.com/hardfist/rspack-manifest-plugin

**Comment by hardfist** [comment]
this seems not a hard job, you can get all these info in stats.json and extract the info you need, can you try? if you met problems we can help here

**Comment by thinkey-yang** [comment]
Thanks to your reply, I implemented a custom plugin using the `compilation.entrypoints` to get the assets json

**Comment by hardfist** [comment]
are you willing to make a rspack-asset-plugin，so others can use

**Comment by bpinto** [comment]
@thinkeyy could you share the solution you used to obtain that manifest structure?
