### ISSUE TITLE
Stats snapshot is not stable

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4139]
See: https://github.com/web-infra-dev/rspack/actions/runs/6095708875/job/16540851129#step:7:2035

**Comment by h-a-n-a** [comment]
@ahabhgk Do you have any idea on this one?

**Comment by ahabhgk** [comment]
Caused by issuer, issuer is not stable, `a.js` is required by `abc.js` and `c.js`, `c.js` also required by `abc.js`, so the issuer of `a.js` could be `abc.js` or `c.js`, depend on how fast build queue build the module, let me open a PR to disable this

**Comment by h-a-n-a** [comment]
> Caused by issuer, issuer is not stable, `a.js` is required by `abc.js` and `c.js`, `c.js` also required by `abc.js`, so the issuer of `a.js` could be `abc.js` or `c.js`, depend on how fast rspack build these modules, let me open a PR to disable this

Would this cause hashing issue?

**Comment by ahabhgk** [comment]
Nope, since module hash wouldn't hash issuer in webpack
