### ISSUE TITLE
[Bug]: Modern.js Builder 使用 vue3 rspack 热更新报错

### ISSUE THREAD

**Issue by 94ashui** [web-infra-dev/rspack#4143]
### Version

```sh
Mac os
Chrome 116
```

### Details

随意修改模版里面的值保存后重新编译，热更新出现下面的错误

10% building ./HelloWorld.vue.css?vue&type=style&index=0&id=469af010&scoped=true&lang=css!=!-!../.thread 'tokio-runtime-worker' panicked at 'Module(missing|/Users/allen/Documents/tele-zone/builder-vue3-rspack/./HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=css) should be added before using', crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:68:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduce link

https://github.com/web-infra-dev/modern-js-examples/tree/main/examples/builder-vue3-rspack

### Reproduce Steps

修改 HelloWorld 组件

<img width="759" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/89236888/012a7f78-e487-4de5-a121-9c4b053a24ab">

**Comment by chenjiahan** [comment]
@94ashui You can lock the version of modern.js packages to use Rspack 0.2.12:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/3f9344e2-c814-4f97-a59c-48d085c6c257)

**Comment by h-a-n-a** [comment]
After my debugging, I found this one is caused by PR: https://github.com/web-infra-dev/rspack/pull/4026. Would you please to take a look? @underfin

**Comment by h-a-n-a** [comment]
@chenjiahan Just for heads-up: v0.3.0 is working as well.
