### ISSUE TITLE
documentation for @rspack/plugin-html

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4157]
since @rspack/plugin-html may exist  for long time, we may need a real documentation for it,
related to https://github.com/web-infra-dev/rspack/issues/3990

**Comment by hardfist** [comment]
cc @h-a-n-a @ahabhgk , what do you think

**Comment by ahabhgk** [comment]
We don't need doc if we can use html-webpack-plugin directly, I'll use 2-3 days to give it a try
