### ISSUE TITLE
The difference in bundle size between Rspack and Webpack artifacts

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4171]
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.64 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/Library/Caches/fnm_multishells/70582_1694424744062/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/70582_1694424744062/bin/yarn
    npm: 9.3.1 - ~/Library/Caches/fnm_multishells/70582_1694424744062/bin/npm
    pnpm: 7.18.1 - ~/Library/Caches/fnm_multishells/70582_1694424744062/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6

### Details

The bundle size of Rspack and Webpack artifacts are very different.

### Webpack

Webpack creates smaller chunks, the difference in size between chunks is not as great as Rspack.

And the total size is smaller, but the gzipped size is larger than Rspack.

- Total size:  6.16 MB
- Gzipped size:  1.74 MB

![image](https://github.com/web-infra-dev/rspack/assets/7237365/a4b5fa51-5273-4c31-9e7c-101e6266163b)

### Rspack

Rspack creates a 3.73 MB large chunk, and the total size is larger.

- Total size:  6.78 MB
- Gzipped size:  1.71 MB

![image](https://github.com/web-infra-dev/rspack/assets/7237365/648a590a-5ebb-4d32-a3e2-ca684639caaf)

### Reproduce link

https://github.com/chenjiahan/rspack-split-chunks-size

### Clone

```bash
git clone git@github.com:chenjiahan/rspack-split-chunks-size.git
```

### Webpack

```bash
cd webpack && pnpm i && pnpm build --analyze
```

### Rspack

```bash
cd rspack && pnpm i && pnpm build --analyze
```

**Comment by chenjiahan** [comment]
Ref: https://github.com/web-infra-dev/rspack/issues/3120

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
@JSerFeng can you help revisit the issue ?

**Comment by JSerFeng** [comment]
bump

**Comment by chenjiahan** [comment]
Now (Rspack v0.6.1) the total size is smaller than webpack and no more large chunks, so I will close this issue.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/3c14c77c-aea1-4028-b2fa-4787bd71849a)
