### ISSUE TITLE
window  react-refresh compile error

### ISSUE THREAD

**Issue by thinkeyy** [web-infra-dev/rspack#4177]
### System Info

System:
OS: win10 64
CPU: intel xeon gold 6226R
Memory: 16.00 GB
Shell: prowershell
Binaries:
Node: 16.20.2
Yarn: 1.22.19
npm: 6.14.6 
Browsers:
Chrome: 116.0.5845.96
Safari: 16.1
npmPackages:
@rspack 0.3.1

### Details

In my project, configure with:
```
builtins: {
      react: {
        refresh: true,
       }
    },
```
it can compiled success on mac,But failed to compile under window，get the error:
```
error Compile error:
Failed to compile,check the errors for troubleshooting.
error[internal]:  系统找不到指定的路径，（os error 3）,failed to read
```

### Reproduce Steps

none

**Comment by thinkey-yang** [comment]
now, by  congfigure 
```
react: {
      refresh: platform !== 'win32',
      }
```
Avoid this problem

**Comment by xuzhouchen1104** [comment]
the same problem ， and  more unknown problems when using Windows than on mac

**Comment by thinkey-yang** [comment]
> now, by congfigure
> 
> ```
> react: {
>       refresh: platform !== 'win32',
>       }
> ```
> 
> Avoid this problem

first compile is ok ,But eidt something and save, get new error 
```
[webpack-dev-moddle][Error:[error internal]]module   xxxxxx  should be add before using
```

**Comment by thinkey-yang** [comment]
> > now, by congfigure
> > ```
> > react: {
> >       refresh: platform !== 'win32',
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Avoid this problem
> 
> first compile is ok ,But eidt something and save, get new error
> 
> ```
> [webpack-dev-moddle][Error:[error internal]]module   xxxxxx  should be add before using
> ```

with this cofnfig, and setting rspack => 0.03, is compile success

**Comment by h-a-n-a** [comment]
@thinkeyy Would you please give a reproduction demo?
