### ISSUE TITLE
not support preserveJsx when use builtin:swc-loader

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#4180]
### System Info

none

### Details

I want use vue jsx in rspack, but get an  `ReferenceError: React is not defined` error

![a6dd4828-0bcf-464a-83a6-30adcc1eb8be](https://github.com/web-infra-dev/rspack/assets/22373761/ffecb842-d7d1-4481-94b2-61bbcd82b08e)

![1e027edb-84a7-4924-8640-d1eeea78aedf](https://github.com/web-infra-dev/rspack/assets/22373761/9b255437-1fa9-4098-bbee-cc888ca4a3e4)

### Reproduce Steps

none

**Comment by h-a-n-a** [comment]
See thread here: https://github.com/swc-project/swc/pull/5661

**Comment by 9aoy** [comment]
After adjusting the order of swc-loader and babel jsx plugin, the problem was solved...

<img width="1050" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/fd56e317-4434-4096-aa75-3ef69bb265bc">

**Comment by dejour** [comment]
@9aoy  could you share how to achieve this in rsbuild config.

**Comment by 9aoy** [comment]
@dejour In rsbuild, we let jsx syntax be processed by `babel-loader` first, so that when passing through `swc-loader`, there will be no jsx syntax.
