### ISSUE TITLE
compiled error need restart dev

### ISSUE THREAD

**Issue by xiaoxin-sky** [web-infra-dev/rspack#4182]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (12) x64 AMD Ryzen 5 5500                               
    Memory: 3.36 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 3.6.1 - ~/.volta/tools/image/yarn/3.6.1/bin/yarn
    npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
    pnpm: 8.6.9 - ~/.volta/tools/image/pnpm/8.6.9/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5.2
  npmPackages:
    @rspack/cli: latest => 0.3.2 
    @rspack/plugin-node-polyfill: ^0.3.2 => 0.3.2

### Details

refactor file name cause compiled error，and can‘t compiled after fix the error ,need rerun the server.

https://github.com/web-infra-dev/rspack/assets/42181585/fb0893ef-4cfb-4834-bd93-379b1f2e9fdd

### Reproduce link

https://github.com/xiaoxin-sky/rspack-project-demo

### Reproduce Steps

1. pnpm dev
2. refactor app.js file name to index.js and save 
3. fix main.js file import  `import App from './app'` to `import App from './foo'`

**Comment by jerrykingxyz** [comment]
This issue has been fixed by https://github.com/web-infra-dev/rspack/pull/4149. You can try the 0.3.3.

**Comment by h-a-n-a** [comment]
Feel free to reopen this if you have any further question.

**Comment by xiaoxin-sky** [comment]
It has indeed been fixed.
