### ISSUE TITLE
[bug]resolve.alias 无法正确解析 moment 包

### ISSUE THREAD

**Issue by Fi2zz** [web-infra-dev/rspack#4187]
### System Info

  System:
    OS: macOS 13.5.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 153.21 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
  npmPackages:
    @rspack/cli: latest => 0.3.2 

#### case 1

```js

/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	context: __dirname,
	entry: { main: "./case-1/src/main.js" },
	builtins: { html: [{ template: "./case-1/index.html" }] },
	resolve: {
		alias: { moment: require.resolve("moment/min/moment.min.js") },
	},
};


```

```bash

    # install
    yarn
    # run build
    yarn build:case1

    # $ rspack build
    # error[internal]: Failed to resolve ./locale in project root



    # rspack compiled with 1 error in 299 ms
    # error Command failed with exit code 1.
    # info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



```

#### case 2

```js

/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	context: __dirname,
	entry: { main: "./case-2/src/main.js" },
	builtins: { html: [{ template: "./case-2/index.html" }] },

};


```

```bash

    # install
    yarn
    # run build
    yarn build:case2

    # $ rspack build
    # error[internal]: Failed to resolve ./locale in project root



    # rspack compiled with 1 error in 299 ms
    # error Command failed with exit code 1.
    # info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



```

### Reproduce link

https://github.com/Fi2zz/rspack-alias-bug

### Reproduce Steps

1. run yarn 
2. run yarn build:case1  or  yarn build:case2

**Comment by h-a-n-a** [comment]
I believe this is an issue related to this: https://github.com/moment/moment/issues/6092. Have you try to use moment with locale package?

**Comment by Fi2zz** [comment]
> I believe this is an issue related to this: [moment/moment#6092](https://github.com/moment/moment/issues/6092). Have you try to use moment with locale package?

no, but when use with esbuild, it did not throw an error

**Comment by Fi2zz** [comment]
> I believe this is an issue related to this: [moment/moment#6092](https://github.com/moment/moment/issues/6092). Have you try to use moment with locale package?

when  direct import like below which also can reproduce this issue.

```js

import moment from "moment/min/moment.min.js"
moment(new Date()).format("yyy-mm-dd");

```

I think `rspack` eval the code before parse

**Comment by h-a-n-a** [comment]
Would you take a look? @underfin

**Comment by ahabhgk** [comment]
Tried with webpack, webpack also have the problem, and checkout the code in `moment`, they use `require("./locale"+t)` but no `locale` directory under `min`
<img width="810" alt="Screenshot 2023-09-18 at 13 48 29" src="https://github.com/web-infra-dev/rspack/assets/42857895/fff37c94-8893-4b16-8140-0722a16df45a">
so the error is correct, it's expected, caused by https://github.com/moment/moment/issues/6092

actually you can avoid this problem by importing "moment.js" instead of "moment.min.js", and in production rspack will minimize the code anyway

but besides this there is also another blocker: 

```js
aliasedRequire = require;
aliasedRequire('./locale/' + name);
```

aliasedRequire hasn't supported in rspack yet, so you need to patch it to make it works

```js
// aliasedRequire = require;
require('./locale/' + name);
```

**Comment by Fi2zz** [comment]
> Tried with webpack, webpack also have the problem, and checkout the code in `moment`, they use `require("./locale"+t)` but no `locale` directory under `min` <img alt="Screenshot 2023-09-18 at 13 48 29" width="810" src="https://user-images.githubusercontent.com/42857895/268563368-fff37c94-8893-4b16-8140-0722a16df45a.png"> so the error is correct, it's expected, caused by [moment/moment#6092](https://github.com/moment/moment/issues/6092)
> 
> actually you can avoid this problem by importing "moment.js" instead of "moment.min.js", and in production rspack will minimize the code anyway
> 
> but besides this there is also another blocker:
> 
> ```js
> aliasedRequire = require;
> aliasedRequire('./locale/' + name);
> ```
> 
> aliasedRequire hasn't supported in rspack yet #3955, so you need to patch it to make it works
> 
> ```js
> // aliasedRequire = require;
> require('./locale/' + name);
> ```

thanks , I tried with webpack in development mode which throw error but production mode don't. 



this solution also works for `rspack` [#6092](https://github.com/moment/moment/issues/6092#issuecomment-1669127853)
