### ISSUE TITLE
css 热更新失效

### ISSUE THREAD

**Issue by noshower** [web-infra-dev/rspack#4206]
### System Info

  System:

      OS: macOS 13.4.1
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 966.71 MB / 32.00 GB
      Shell: 5.9 - /bin/zsh
  Binaries:

      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:

      Chrome: 116.0.5845.187
      Firefox: 109.0.1
      Safari: 16.5.2
  npmPackages:

      @rspack/cli: latest => 0.3.4 

### Details

# 复现配置
只要配置了 filename 和 cssFilename ，css 热更新失效。
```
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  context: __dirname,
  entry: {
    main: "./src/main.tsx",
  },
  output: {
    // 配置了 filename 和 cssFilename 后，开发环境的 css 热更新失效
    filename: "js/[name].[contenthash].js",
    cssFilename: "css/[name].[contenthash].css",
  },
  builtins: {
    html: [
      {
        template: "./index.html",
      },
    ],
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        type: "asset",
      },
    ],
  },
};

```

### Reproduce Steps

复现步骤：
1.  npm create rspack@latest
2. 给 rspack.config.js 加上以下配置
```
  output: {
    // 配置了 filename 和 cssFilename 后，开发环境的 css 热更新失效
    filename: "js/[name].[contenthash].js",
    cssFilename: "css/[name].[contenthash].css",
  },
```
3. npm run dev
4. 修改任一样式，样式不会热更新

**Comment by hardfist** [comment]
same as #3629
