### ISSUE TITLE
 Failed to resolve element-ui component by using builtins.pluginImport 

### ISSUE THREAD

**Issue by xiaochuan1719** [web-infra-dev/rspack#4207]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 7.59 GB / 15.88 GB
  Binaries:
    Node: 18.17.1 - ~\AppData\Local\fnm_multishells\11888_1694930812991\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.7 - ~\AppData\Local\fnm_multishells\11888_1694930812991\npm.CMD
    pnpm: 8.7.5 - F:\UserLocal\npm\global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.81)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: latest => 0.3.4

### Details

 Failed to resolve element-ui component by using builtins.pluginImport 

![2023-09-17_193908](https://github.com/web-infra-dev/rspack/assets/38381164/497841c5-cd4f-4374-b270-14105992269b)

![2023-09-17_195240](https://github.com/web-infra-dev/rspack/assets/38381164/c4c1a744-f87a-47be-8724-2bd7722c2042)

### Reproduce link

https://github.com/xiaochuan1719/bug-demos/tree/main/rspack-vue2-element-plugin-import

### Reproduce Steps

1. pnpm install && pnpm dev

**Comment by hardfist** [comment]
this issue is outdate, please file a new issue if you met it in latest version
