### ISSUE TITLE
Builtin progress bar is broken when using multi compiler

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4214]
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 375.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/41106_1695025348387/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/41106_1695025348387/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @rspack/cli: workspace:* => 0.3.4

### Details

When there are multiple compilers, the builtin progress bar can not render as expected. The two bars overlap instead of being rendered separately:

<img width="610" alt="Screenshot 2023-09-18 at 19 05 14" src="https://github.com/web-infra-dev/rspack/assets/7237365/41b0f93a-d3fb-4d8b-a303-a35489aab441">

### Reproduce link

https://github.com/web-infra-dev/rspack/tree/main/examples/basic

### Reproduce Steps

1. cd examples/basic
2. add following configs:

```js
/** @type {import('@rspack/cli').Configuration} */

module.exports = [
  {
    name: "Client",
    context: __dirname,
    mode: "development",
    entry: {
      main: "./src/index.js"
    }
  },
  {
    name: "Server",
    target: "node",
    context: __dirname,
    mode: "development",
    entry: {
      main: "./src/index.js"
    }
  }
];
```

3. pnpm run dev

**Comment by chenjiahan** [comment]
bump

**Comment by chenjiahan** [comment]
bump

**Comment by chenjiahan** [comment]
bump

**Comment by hardfist** [comment]
the current hooks seems enough for a progressbar implementation it's just the current progress bar implementation maybe too complex and calls too much hook
