### ISSUE TITLE
[Bug]: strange error when updating the file and dev server fails to refresh

### ISSUE THREAD

**Issue by AsuraKev** [web-infra-dev/rspack#4231]
### System Info

chrome, modern.js latest, rspack

### Details

I am using react-i18next for translation, I am making some small update on my tsx file to change translation key but the dev server fails to refresh page with the updated changes. It sometimes fixes itself.

![image](https://github.com/web-infra-dev/rspack/assets/52765572/c26f4064-4567-4533-85b2-6097dd1eda45)

### Reproduce Steps

Install react-i18next and i18next
Setup translation
live update the code to see changes
error occurs

**Comment by AsuraKev** [comment]
Does this help?
https://github.com/web-infra-dev/rspack/assets/52765572/dc1c398d-e3b2-4b6a-8533-f0477cb5c7be

**Comment by h-a-n-a** [comment]
@AsuraKev Sorry for the late response, but unfortunately no, you have to give us a minimal reproduction repo. Please fork this to make one: https://github.com/web-infra-dev/rspack-repro

**Comment by hardfist** [comment]
bump

**Comment by hardfist** [comment]
close due to missing repro
