### ISSUE TITLE
Add JSDoc for all configuration options as webpack

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4241]
### What problem does this feature solve?

Can we add JSDoc for all configuration options as webpack?

- webpack:

<img width="692" alt="Screenshot 2023-09-25 at 11 03 39" src="https://github.com/web-infra-dev/rspack/assets/7237365/cad22942-9c6d-4e6c-9bee-6cecab5a2b5d">

- Rspack:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/2880cf43-54c0-45f8-8fbd-3323f9a816bb)

### What does the proposed API of configuration look like?

Same as webpack:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/aa80951e-15ed-49f6-9c10-3b3157e1165b)

**Comment by hyf0** [comment]
The type of rspack options is inferred by `zod`. It's not possible in the current time. See https://github.com/colinhacks/zod/issues/200#issuecomment-718979724 for details.

**Comment by chenjiahan** [comment]
It seems that JSDoc can work in some cases:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/f55f4da5-03cf-4605-b1c4-4b2a529cacfb)

https://github.com/colinhacks/zod/issues/200#issuecomment-1198922371

**Comment by dinckelman** [comment]
This appears to be very much situational, because as shown below, VSCode cannot detect the comment, and Webstorm is... well, trying to do something else entirely
<img width="406" alt="Screenshot 2023-10-14 at 23 21 57" src="https://github.com/web-infra-dev/rspack/assets/12545914/ede19f05-d36e-4bdd-8693-9e1a4cef2a8f">
<img width="682" alt="Screenshot 2023-10-14 at 23 21 32" src="https://github.com/web-infra-dev/rspack/assets/12545914/d9483972-0de5-4ce3-8233-cfd8672b36b6">

**Comment by hardfist** [comment]
it indeed hurt DX for users，we will try to find better ways to do this

**Comment by xc2** [comment]
bump

**Comment by chenjiahan** [comment]
bump

**Comment by chenjiahan** [comment]
bump

**Comment by chenjiahan** [comment]
@hardfist  handwritten json schema or handwritten config types?

**Comment by ecraig12345** [comment]
In addition to the missing documentation, it's extremely hard to understand the generated zod types when looking at the `.d.ts` or intellisense in an editor. And it seems like TS can't always infer the types of functions in complex union types--I filed a bug #7979 for `externals` functions specifically.

**Comment by GiveMe-A-Name** [comment]
I have some ideas about this.

1. One is using json schema, like webpack. It means we need maintain a json schema.
2. Another one is that maintain another types for UX. Like the code bellow: 
```ts
interface Address {
    id?: string
    addressText: string
    line1: string
    line2?: string
    city: string
    state: string
    postalCode: string
    country: string
}

const addressSchema = z.object( {
    id: z.string().optional(),
    addressText: z.string(),
    line1: z.string(),
    line2: z.string().optional(),
    city: z.string(),
    state: z.string(),
    postalCode: z.string(),
    country: z.string(),
} ) satisfies z.ZodType<Address>
```
see https://github.com/colinhacks/zod/discussions/1870 more detail.

Actually, if we can transform [ts to zod](https://www.npmjs.com/package/ts-to-zod) or zod to ts, it's a better way. But Rspack Configuration types is so complex, `ts-to-zod` can't transform it correctly. 
see https://github.com/colinhacks/zod/discussions/779 more transform way.

So I prefer second way. But the drawback is we need maintain a another types.

**Comment by chenjiahan** [comment]
The second one LGTM 👍 If we take this approach, we can incrementally migrate types and add JSDoc comments.

**Comment by GiveMe-A-Name** [comment]
# Tasks
- [x] https://github.com/web-infra-dev/rspack/pull/8003
- [ ] refactor: add types & JSDoc to improve HtmlRspackPlugin options types
- [ ] ....

**Comment by chenjiahan** [comment]
All tasks have been completed, thanks to the hard work of @GiveMe-A-Name ! ❤️
