### ISSUE TITLE
不支持 node 环境打包

### ISSUE THREAD

**Issue by zhuzeyu22** [web-infra-dev/rspack#4246]
### System Info

Cannot find module 'node:path'

### Details

Cannot find module 'node:path'

### Reproduce Steps

pnpm i

**Comment by hardfist** [comment]
配置了 `target:'node'`吗？

**Comment by h-a-n-a** [comment]
target 是 web 的情况下需要引入 [node-polyfills](https://www.rspack.dev/guide/language-support.html#node-polyfills)，否则用 target node

**Comment by zhuzeyu22** [comment]
@h-a-n-a 我这里实际的需求是 编译 electron 程序， node 只是基础，target 是 electron 相关的 target

**Comment by hardfist** [comment]
> @h-a-n-a 我这里实际的需求是 编译 electron 程序， node 只是基础，target 是 electron 相关的 target

你配置是啥贴下吧，没配置没法给你看问题

**Comment by zs1713347080** [comment]
估计是node版本太低了，我上午也是这个问题，切到16以及16以上就可以了应该，我上午就是用的12报的一样的错误

**Comment by zhuzeyu22** [comment]
@zs1713347080 @hardfist 再来详细回复下背景情况，是基于 opensumi 的框架来写的业务，这个框架是基于 node 12 以及以上迭代的，但是业务场景要求再 win7 上可执行，因此由于一些历史原因，node 的版本维持在 14.17.x 的版本。

**Comment by hardfist** [comment]
不好意思，16都已经EOL了，我们也不会对14提供长期支持
