### ISSUE TITLE
error[internal]: Base64Error

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4258]
### System Info

System:
    OS: macOS 13.5.1
    CPU: (8) x64 Apple M1
    Memory: 43.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.3.4 => 0.3.4 

### Details

<img width="647" alt="image" src="https://github.com/web-infra-dev/rspack/assets/19773879/9d144634-c1cd-4563-bc8e-2aa680baf994">

### Reproduce link

https://github.com/jeromehan/vue3-rspack-demo

### Reproduce Steps

1. npm run dev

**Comment by jeromehan** [comment]
@ahabhgk  #3494 maybe not completely

**Comment by jeromehan** [comment]
@ahabhgk  `base64_simd::STANDARD.decode_to_vec` , there is a problem with this method,  The decoding in  `js-base64` is correct

**Comment by ahabhgk** [comment]
I did take a look while ago, but have no idea about what the root error is causing this and how to fix it, I found there are different behavior between node's `Buffer.from(.., 'base64')` and `base64_simd`, `base64_simd` is more strict and node's `Buffer.from(.., 'base64')` is compatible with some cases, sadly I'm not a pro about base64 and there are lots of task waiting for me so I can't help more about this in short term, but if you are interested in this feel free to take this and give a try, PR is welcoming

**Comment by jeromehan** [comment]
> I did take a look while ago, but have no idea about what the root error is causing this and how to fix it, I found there are different behavior between node's `Buffer.from(.., 'base64')` and `base64_simd`, `base64_simd` is more strict and node's `Buffer.from(.., 'base64')` is compatible with some cases, sadly I'm not a pro about base64 and there are lots of task waiting for me so I can't help more about this in short term, but if you are interested in this feel free to take this and give a try, PR is welcoming

👌
