### ISSUE TITLE
RsPack 从0.2.12升级到0.3.5报错

### ISSUE THREAD

**Issue by congxiaobai** [web-infra-dev/rspack#4259]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 30.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    pnpm: 7.27.0 - ~/.nvm/versions/node/v16.0.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5.2
  npmPackages:
    @rspack/cli: 0.3.5 => 0.3.5 
    @rspack/dev-server: 0.3.5 => 0.3.5 
     mobx: ^6.6.1
     mobx-react: 7.2.0

### 问题一
 ```
import Icon from '第三方的组件包';
// 用于一些初始化脚本
export const setUp = () => {
  console.log({Icon:Icon})
  // Icon 初始化
  Icon?.extend({
      scriptUrl: [
          'XXXXXXXXX'
      ]
  });
}
```
可以看到正常打印
![image](https://github.com/web-infra-dev/rspack/assets/20089891/8104ed0e-b24f-47a3-a645-0e1f257425ad)
但是执行到extend时报错undefine
![image](https://github.com/web-infra-dev/rspack/assets/20089891/e8a78658-2a30-4cf3-a617-d18d9bf6fca0)

### 问题二
对于使用了mobx的页面
![image](https://github.com/web-infra-dev/rspack/assets/20089891/02ed87b0-3c81-4091-9ec0-de3ae57522dd)
会报错
![image](https://github.com/web-infra-dev/rspack/assets/20089891/bab79768-7572-40d4-9992-5073e5c5b57b)

以上问题在0.2.12z'ho中均不存在
RS的主要配置如下：
```
     devtool: 'source-map', // 报错的时候在控制台输出哪一行报错
 
        mode: mode,
        optimization:{
            minimize:false,
            removeAvailableModules:false,
            removeEmptyChunks:false,
            sideEffects:false,
        },
        target: ['web', 'es5'],
        builtins: {
            progress: true,
            react: {
                runtime: 'classic',
            },
            minifyOptions: {
                dropConsole: mode !== 'development',
            },
            decorator: { legacy: true },    
        },
        resolve: {
            extensions: ['.tsx', '.ts', '.js', '.jsx', '.less', '.css'], //后缀名自动补全

            fallback: {
                'react/jsx-runtime': 'react/jsx-runtime.js',
                'react/jsx-dev-runtime': 'react/jsx-dev-runtime.js',
            },
            modules: [nodeModulesPath, 'node_modules'],
        },
```

### Reproduce Steps

按描述即可复现

**Comment by hardfist** [comment]
请提供可复现demo

**Comment by congxiaobai** [comment]
https://github.com/congxiaobai/rpsack-update-failed-demo
由于使用了公司内部的组件，因此限制了权限。只给您一个人加了访问权限。
