### ISSUE TITLE
Dynamic import can not generate async chunks as expected

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4261]
### System Info

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 282.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/Library/Caches/fnm_multishells/58681_1695821782583/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/58681_1695821782583/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/58681_1695821782583/bin/npm
    pnpm: 8.6.12 - ~/Library/Caches/fnm_multishells/58681_1695821782583/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.5.2
  npmPackages:
    @rspack/cli: latest => 0.3.5 

### Details

1. Use `React.lazy` and dynamic import:

```js
import { lazy } from "react";

const LazyComponent = lazy(() => import("./Component"));

console.log(LazyComponent);
```

2. Add `enforceSizeThreshold` config:

```js
{
  optimization: {
    splitChunks: {
      chunks: "all",
      enforceSizeThreshold: 50000,
    },
  },
}
```

Webpack can split dynamic chunks as expected:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/f6668d10-eeca-4cbf-b09c-34df65dd382d)

Rspack can not split the dynamic chunk:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/a4087f74-d4ba-4664-8e63-6b15b1b0e674)

### Reproduce link

https://github.com/chenjiahan/rspack-dynamic-import-issue

### Reproduce Steps

1. pnpm i
2. pnpm build

**Comment by JSerFeng** [comment]
Fixed by #4280, you can try using 0.3.5-canary-10b7fe6-20231008143835
