### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by clijiac** [web-infra-dev/rspack#4265]
### System Info

 System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 51.67 GB / 79.92 GB
  Binaries:
    Node: 16.19.1 - ~\AppData\Local\fnm_multishells\29312_1695879977808\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\fnm_multishells\29312_1695879977808\yarn.CMD
    npm: 9.8.0 - ~\AppData\Local\fnm_multishells\29312_1695879977808\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Local\fnm_multishells\29312_1695879977808\pnpm.CMD
    Watchman: 20230408.180552.0 - D:\SmallTools\watchman\watchman.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.43), ChromiumDev (119.0.2116.0)
    Internet Explorer: 11.0.19041.1566

### Details

just import this lib `"white-web-sdk"`

0.1.12 is good but 0.3.5 is not.
webpack is good

```
VM24:190516  Uncaught (in promise) ReferenceError: require is not defined
    at ./node_modules/.pnpm/white-web-sdk@2.16.44/node_modules/white-web-sdk/index.js (VM24:190516:37)
    at __webpack_require__ (VM23:8178:33)
    at fn (VM23:8256:10)
    at ./src/app.js (VM25:18:69)
    at __webpack_require__ (VM23:8178:33)
    at fn (VM23:8256:10)
    at ./src/render.js (VM25:84:60)
    at __webpack_require__ (VM23:8178:33)
    at Function.fn (VM23:8256:10)
```

### Reproduce link

https://github.com/clijiac/rspack-repro

### Reproduce Steps

1. npm run dev:rspack 
2. then see the broswer console

**Comment by ScriptedAlchemy** [comment]
`uR = 'function' != "undefined" ? require : function(e) {`

It looks like the package tries to use a dynamic require, and it is not getting parsed and converted to __webpack_require__

**Comment by hardfist** [comment]
@clijiac can you help check whether this problem still exist in latest version

**Comment by xc2** [comment]
This problem is gone with rspack 0.7.5. Close as fixed.
