### ISSUE TITLE
ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by WindrunnerMax** [web-infra-dev/rspack#4274]
### System Info

System:
    OS: Windows 10 10.0.15063
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 5.58 GB / 7.90 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (40.15063.0.0)
    Internet Explorer: 11.0.15063.0
  npmPackages:
    @rspack/cli: ^0.2.5 => 0.2.12
    @rspack/plugin-html: ^0.2.5 => 0.2.12

### Details

When I used my windows computer to run the project, an ERR_DLOPEN_FAILED exception was thrown (there was no problem on my MAC computer), so I tried to verify it and found that as long as I quoted @rspack/binding-win32-x64-msvc, it would throw an exception:

![image](https://github.com/web-infra-dev/rspack/assets/33169019/39174a5a-d3b0-44a6-b8f8-ac735979f024)

Judging from the error results, it was caused by a lack of dlls, but the failure to call process.dlopen did not clearly prompt me which dlls were missing. Is there any way to solve this problem, or can you provide a list of dlls?

This problem was mentioned in #3598, and it seems to be solved by installing Visual Studio. It is a bit scary to install such a heavy IDE to solve this problem.

### Reproduce Steps

This kind of environmental problem may not be easy to reproduce stably. I just switched from mac to windows development, and this windows computer was just reinstalled.

**Comment by hardfist** [comment]
what's the minimal environment for napi-rs related library run on windows? @Brooooooklyn is Visual Studio a must need?
