### ISSUE TITLE
css module in vue3 template cannot work as expected

### ISSUE THREAD

**Issue by monster1935** [web-infra-dev/rspack#4289]
### System Info

 System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 256.72 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.10.0/bin/npm
    pnpm: 8.2.0 - ~/.nvm/versions/node/v18.10.0/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 16.6
  npmPackages:
    @rspack/cli: latest => 0.3.6 

### Details

in the file [HelloWorld.vue](https://github.com/monster1935/rspack-project/blob/main/src/components/HelloWorld.vue), I tried to use css module in vue3 template. Just as:
```
<template>
   <p :class="$style.read_the_docs">Click on the Rspack and Vue logos to learn more</p>
</template>
<style lang="scss" module>
.read_the_docs {
  color: red;
}
</style>
```
the text cannot show color red. In browser, it shows like that the class name is empty.
<img width="2017" alt="image" src="https://github.com/web-infra-dev/rspack/assets/10126576/abdd6477-78db-4923-8d27-d05de5e143f8">

I don’t know if it’s a misconfiguration that causes this behavior or it’s a bug in itself.

the config is in [rspack.config.js](https://github.com/monster1935/rspack-project/blob/main/rspack.config.js).

I would be grateful if you could help take a look at this issue.

### Reproduce link

https://github.com/monster1935/rspack-project/tree/main

### Reproduce Steps

download the repo and do like this
```
1. yarn
2. yarn dev
```

**Comment by hardfist** [comment]
you should configure css module in css-loader according to vue documenation https://vue-loader.vuejs.org/zh/guide/css-modules.html#%E7%94%A8%E6%B3%95
```js
 use: ["vue-style-loader", {loader: "css-loader", options: {
              // 开启 CSS Modules
              modules: true,
        }}, "sass-loader"],
```

**Comment by kychok98** [comment]
In case someone is looking for this, spent hours of debugging and docs swimming, trial and errors.

I am using rspack version, with VueJS
"@rspack/cli": "0.6.2",
"@rspack/core": "0.6.2",

https://www.rspack.dev/guide/tech/css#css-modules
U need to set `namedExports` to false in modules, by default Rspack treat `*.module.css` as module types.

```
{
    test: /\.css$/,
    use: [
      "vue-style-loader",
      {
        loader: "css-loader",
        options: {
          modules: {
            localIdentName: "[local]__[hash:base64:8]",
            namedExport: false,
          },
        },
      },
    ],
  },
```

**Comment by thedemons** [comment]
@kychok98 `namedExport: false` worked! I nearly gave up after hours and hours of googling, thanks you kind stranger.
