### ISSUE TITLE
support resourceQuery options as object

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4297]
### What problem does this feature solve?

webpack support resourceQuery as object which is very useful for svgr configuration
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/i,
        type: 'asset',
        resourceQuery: /url/, // *.svg?url
      },
      {
        test: /\.svg$/i,
        issuer: /\.[jt]sx?$/,
        resourceQuery: { not: [/url/] }, // exclude react component if *.svg?url
        use: ['@svgr/webpack'],
      },
    ],
  },
}
```

### What does the proposed API of configuration look like?

same as webpack

**Comment by hardfist** [comment]
it seems we support this option but it's not working

**Comment by suxin2017** [comment]
nodejs_resolver seems to be the problem

nodejs_resolver resolves index.js
{"query": None} is returned.

enhanced-resolve resolves index.js
Returns {"query": ""}

// require('xxx.svg')
// query = None

```
  if let Some(resource_query_rule) = &module_rule.resource_query {


    if let Some(resource_query) = &resource_data.resource_query {
      if !resource_query_rule.try_match(resource_query).await? {

        return Ok(false);
      }
    } else {
// query = None
// This code executes
      return Ok(false);
    }
  }
```
 
I was wondering whether to change nodejs_resolve or rspack_core🤔️
Do you have any suggestions?

**Comment by hardfist** [comment]
> nodejs_resolver seems to be the problem
> 
> nodejs_resolver resolves index.js {"query": None} is returned.
> 
> enhanced-resolve resolves index.js Returns {"query": ""}
> 
> // require('xxx.svg') // query = None
> 
> ```
>   if let Some(resource_query_rule) = &module_rule.resource_query {
> 
> 
>     if let Some(resource_query) = &resource_data.resource_query {
>       if !resource_query_rule.try_match(resource_query).await? {
> 
>         return Ok(false);
>       }
>     } else {
> // query = None
> // This code executes
>       return Ok(false);
>     }
>   }
> ```
> 
> I was wondering whether to change nodejs_resolve or rspack_core🤔️ Do you have any suggestions?

nodejs_resolver is deprecated，try https://www.rspack.dev/zh/config/experiments.html#experimentsrspackfuturenewresolver

**Comment by suxin2017** [comment]
> nodejs_resolver is deprecated，try https://www.rspack.dev/zh/config/experiments.html#experimentsrspackfuturenewresolver

oxc_resolver is also None

I could just change the oxc_resolver code to keep it consistent with webpack,
You could also modify the try_match implementation to match None if you like

**Comment by hardfist** [comment]
both makes sense, but change resolver to return same result as enhanced-resolve seems more suitable, @Boshen what do you think?

**Comment by Boshen** [comment]
@suxin2017 Can you give me a repro? There is no `resourceQuery` API inside the resolver, I'm not sure if we are aligned on the same context ...

**Comment by suxin2017** [comment]
> @suxin2017 Can you give me a repro? There is no `resourceQuery` API inside the resolver, I'm not sure if we are aligned on the same context ...

I write it in oxc-resolver 
```
#[test]
fn simple() {
    // mimic `enhanced-resolve/test/simple.test.js`
    let dirname = env::current_dir().unwrap().join("fixtures");
    let f = dirname.join("enhanced_resolve/test");

    let resolver = Resolver::default();

    let data = [
        ("direct", f.clone(), "../lib/index"),
        ("as directory", f, ".."),
        ("as module", dirname.clone(), "./enhanced_resolve"),
    ];

    for (comment, path, request) in data {
        let resolve_result = resolver.resolve(&path, request);
        dbg!(&resolve_result);
//      ^^^^^^^^^^^^^^^^
// output 
// {..
//  query: None,
//  fragment: None,
// ..}
        let resolved_path = resolve_result.map(|f| f.full_path());
        let expected = dirname.join("enhanced_resolve/lib/index.js");
        assert_eq!(resolved_path, Ok(expected), "{comment} {path:?} {request}");
    }
}
```

enhanced-resolve
![image](https://github.com/web-infra-dev/rspack/assets/28481035/5688ad6f-38f7-449b-981b-a0806da40c2c)

**Comment by JiangWeixian** [comment]
`resourceQuery` like https://www.rspack.dev/zh/config/module.html#condition docs said is supported now?

**Comment by hardfist** [comment]
@Boshen can you help take a look at this, if cause problems of using svg and svgr together

**Comment by JiangWeixian** [comment]
Looks like hack fix by this way...

```
resourceQuery: (value) => { return !/url/.test(value) }
```

**Comment by steveostudios** [comment]
I'm also looking for a fix for this. I was unable to get the hack by @JiangWeixian to work :(

**Comment by Boshen** [comment]
@h-a-n-a Can you take a look at webpack alignment with `resourceQuery`? I'm confused by all the context provided above.

**Comment by h-a-n-a** [comment]
> @h-a-n-a Can you take a look at webpack alignment with `resourceQuery`? I'm confused by all the context provided above.

@Boshen Sure, I will get back to you once I looked into this problem ;-)
