### ISSUE TITLE
HMR API exist in production build

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#4300]
### System Info

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.40 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.6.9 - ~/.nvm/versions/node/v18.14.0/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
  npmPackages:
    @rspack/cli: ^0.3.6 => 0.3.6 

### Details

`import.meta.hot` and `import.meta.webpackHot` exist in production build.

input:

```js
if (import.meta.hot) {
  import.meta.hot.accept();
}
if (import.meta.webpackHot) {
  import.meta.webpackHot.accept();
}
if (module.hot) {
  module.hot.accept()
}
```

webpack output:

```js
if (false) {}
if (false) {}
if (false) {}
```

rspack output
```js
if (undefined) undefined();
if (import.meta.webpackHot) import.meta.webpackHot.accept();
if (module.hot) module.hot.accept();
```

### Reproduce link

https://github.com/JSerFeng/rspack-issues

### Reproduce Steps

pnpm i

see the differences between `pnpm run build:webpack` and `pnpm run build:rspack`

**Comment by ahabhgk** [comment]
blocked by parser hook
- https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/dependencies/ImportMetaPlugin.js#L237
- https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/ConstPlugin.js#L164-L172
