### ISSUE TITLE
NestJS Example is not working

### ISSUE THREAD

**Issue by maggimer** [web-infra-dev/rspack#4303]
### System Info

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 506.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.2
  npmPackages:
    @rspack/cli: ^0.3.6 => 0.3.6
    @rspack/core: ^0.3.6 => 0.3.6

### Details

While trying to solve some issues at work I checked the NestJS example rspack provides under `examples/nestjs`

Sadly this example doesn't work for the same reason: Providers in the `app.controller.ts` constructor are not properly injected.
This effect can be observed because the should-be injected instance of `AppService` is undefined at runtime.

Leading to a `TypeError: Cannot read properties of undefined (reading 'getHello')` when actually opening `localhost:3000` in the browser.

Providing an explicit `@Inject` like so `constructor(@Inject(AppService) private readonly appService: AppService)`
seems to solve the problem but this workaround should not be required according to the NestJS docs https://docs.nestjs.com/providers and isn't needed when using webpack/tsc instead

### Reproduce Steps

From `examples/nestjs`:
- pnpm install
- pnpm run build
- pnpm run start
- GET `localhost:3000` in the browser/curl/...

**Comment by hardfist** [comment]
missing some configuration on swc-loader
https://github.com/web-infra-dev/rspack/pull/4308/files#diff-c731c9e2095190f907b29c0cc6bf0873c5b0b4309a5a6ae1ede3a21f179b519fR22-R30
