### ISSUE TITLE
support require.ensure

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4304]
### What problem does this feature solve?

- webpack-test/cases/chunks/context
- webpack-test/cases/chunks/named-chunks

### What does the proposed API of configuration look like?

require.ensure()

**Comment by WbaN314** [comment]
Is there any timeline when this will be supported?

**Comment by ahabhgk** [comment]
Not sure, this is low priority since it can be replaced by `import()`, but PR welcome

**Comment by h-a-n-a** [comment]
bump
