### ISSUE TITLE
support webpackMode and other inline magic comments

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4306]
### What problem does this feature solve?

- webpack-test/cases/chunks/inline-options

### What does the proposed API of configuration look like?

`import(/* webpackMode: "lazy" */ "./dir4/" + name);`

**Comment by WbaN314** [comment]
Any timeline when this will be implemented?

**Comment by ahabhgk** [comment]
`webpackMode: "lazy"` is on the plan, will likely be implemented in this or next month, other inline magic comments don't have a clearly timeline

**Comment by yimingjfe** [comment]
In Modern.js, we have a configuration implementation that relies on `webpackMode: eager`, can this feature be included in the plan?
