### ISSUE TITLE
Slow performance after upgrade with devtool and importing a minified js bundle

### ISSUE THREAD

**Issue by marco2216** [web-infra-dev/rspack#4307]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 2.74 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.3.6 => 0.3.6
    @rspack/core: 0.3.6 => 0.3.6
    @rspack/dev-server: 0.3.6 => 0.3.6
    @rspack/plugin-minify: 0.3.6 => 0.3.6

### Details

In our web app, we are importing a large JS bundle (6.7 MB) which is already minified. The bundle is causing the issue, since if I stop importing, everything is fast.
After upgrading from 0.2.9 to 0.3.6, rspack is much slower due to this file. From ~5s to ~15s, and hot reload went from ~1s to ~10s now. It seems to get stuck in the `(90%) processing assets` step.
I think it has to do with the devtool - currently we are using cheap-module-source-map in dev, and turning it off or setting it to one of the many other options improves performance a lot, e.g. changing to cheap-source-map makes hot reload takes 1s instead of 10s.
I think it could have to do with the minified bundle being on one line, formatting the file so it's on many lines actually seems to improve the performance?

### Reproduce Steps

Try to bundle something that includes a large minified JS bundle.
Sorry I can't include the specific JS file as it's proprietary code :(

**Comment by hardfist** [comment]
@marco2216  can you help upload profile result according to https://www.rspack.dev/guide/profile.html

**Comment by marco2216** [comment]
Of course, here you go
[jscpuprofile.json](https://github.com/web-infra-dev/rspack/files/12870036/jscpuprofile.json)
[logging.json](https://github.com/web-infra-dev/rspack/files/12870037/logging.json)
[trace.json](https://github.com/web-infra-dev/rspack/files/12870038/trace.json)

**Comment by marco2216** [comment]
Maybe it's useful information, not sure - we have a splitChunks plugin specifically for this file so it always gets bundled as a single file. If I remove this plugin, the build actually gets even slower, ~30s instead of ~15s with it.
```
    splitChunks: {
      cacheGroups: {
        messenger: {
          test: /static\/messenger\/app\.js/,
          name: 'messenger',
          chunks: 'all',
        },
      },
    },
```
Here is the profile without this splitChunks plugin:
[jscpuprofile.json](https://github.com/web-infra-dev/rspack/files/12870117/jscpuprofile.json)
[logging.json](https://github.com/web-infra-dev/rspack/files/12870118/logging.json)
[trace.json](https://github.com/web-infra-dev/rspack/files/12870119/trace.json)

**Comment by hardfist** [comment]
can you help check the size of sourcemap when setting devtool:cheap-module-source-map and devtool:cheap-source-map, it may related to sourcemap size

**Comment by marco2216** [comment]
It doesn't seem like there's any difference at all in the output size with those two options. Other options produce slightly different size .map files, but those two it's the same.

**Comment by marco2216** [comment]
Bump, still happening on 0.5.0

**Comment by Boshen** [comment]
Our current webpack-sources port chokes on large texts, @SyMind has started studying it.

**Comment by SyMind** [comment]
I've proposed two pull requests aimed at enhancing HMR performance:

1. Implement a memory cache within the SourceMapDevToolPlugin to eliminate redundant Source Map calculations for identical sources during the HMR phase. https://github.com/web-infra-dev/rspack/pull/5709

2. Implement caching in the stream_chunks function of CachedSource to accelerate source map generation significantly. https://github.com/web-infra-dev/rspack-sources/pull/89

You can try it in the next Rspack version.

@Boshen cc
