### ISSUE TITLE
Rspack bus error  

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4309]
### System Info

System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 968.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 118.0.5993.70
    Firefox: 97.0.1
    Safari: 16.6
  npmPackages:
    @rspack/cli: workspace:* => 0.3.6 

### Details

```js
Process 6508 stopped
* thread #21, name = 'tokio-runtime-worker', stop reason = EXC_BAD_ACCESS (code=2, address=0x17574afa8)
    frame #0: 0x000000013b6e5b70 rspack.darwin-arm64.node`swc_ecma_parser::parser::stmt::_$LT$impl$u20$swc_ecma_parser..parser..Parser$LT$I$GT$$GT$::parse_stmt_internal::h5a9e3dcd4ddc8e45(self=0x0000000000000000, start=BytePos @ 0x000000017574ef60, include_decl=false, top_level=false, decorators=<unavailable>) at stmt.rs:115
   112      }
   113 
   114      /// `parseStatementContent`
-> 115      fn parse_stmt_internal(
   116          &mut self,
   117          start: BytePos,
   118          include_decl: bool,
Target 0: (node) stopped.
```

### Reproduce Steps

rspack serve

**Comment by hardfist** [comment]
may caused by swc stackoverflow try adjust stacksize using RSPACK_STACK_SIZE to adjust stack size to debug this sort of problems

**Comment by jeromehan** [comment]
I'll try
