### ISSUE TITLE
Nestjs dependencies not being included in bundle

### ISSUE THREAD

**Issue by p-v-d-Veeken** [web-infra-dev/rspack#4319]
### System Info

  System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 440.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    Watchman: 2023.08.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    @rspack/core: ~0.3.6 => 0.3.6 
    @rspack/dev-server: ~0.3.6 => 0.3.6 
    @rspack/plugin-minify: ~0.3.6 => 0.3.6 

### Details

I've set up a basic NestJS + RSPack repo and when building the app, the resulting main.js does not include the necessary @nestjs/*  dependencies. This means, that the bundle can only be executed if the corresponding node_modules are available. Which kind of defeats the purpose of using a bundler.

### Reproduce link

https://github.com/p-v-d-Veeken/nest-rspack

### Reproduce Steps

1. Clone this repo: https://github.com/p-v-d-Veeken/nest-rspack
2. Run `npm install`
3. Run `nx build demo`
4. Run `node dist/apps/demo/main.js` this will output:
```
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG [NestFactory] Starting Nest application...
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG [InstanceLoader] AppModule dependencies initialized +14ms
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG [RoutesResolver] AppController {/api}: +20ms
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG [RouterExplorer] Mapped {/api, GET} route +3ms
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG [NestApplication] Nest application successfully started +3ms
[Nest] 14258  - 10/13/2023, 2:34:34 PM     LOG 🚀 Application is running on: http://localhost:3000/api
```
5. Run `mv node_modules node_modules.tmp`
6. Run `node dist/apps/demo/main.js` again, this time it will output:
```
/Users/user/code/nest-rspack/dist/apps/demo/main.js:721
            throw e;
            ^

Error: Cannot find module '@nestjs/common'
Require stack:
- /Users/user/code/nest-rspack/dist/apps/demo/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at @nestjs/common (/Users/user/code/nest-rspack/dist/apps/demo/main.js:4:18)
    at __webpack_require__ (/Users/user/code/nest-rspack/dist/apps/demo/main.js:718:33)
    at fn (/Users/user/code/nest-rspack/dist/apps/demo/main.js:798:10)
    at ./apps/demo/src/main.ts (/Users/user/code/nest-rspack/dist/apps/demo/main.js:674:70)
    at __webpack_require__ (/Users/user/code/nest-rspack/dist/apps/demo/main.js:718:33)
    at /Users/user/code/nest-rspack/dist/apps/demo/main.js:1647:27 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/code/nest-rspack/dist/apps/demo/main.js'
  ]
}

**Comment by hardfist** [comment]
@antoinepairet seems bundle nestjs successfully, and we have an example https://github.com/web-infra-dev/rspack/blob/main/examples/nestjs/rspack.config.js which bundles most of the library in node_modules,
but it seems there're still some problems with Nestjs itself and other library, I'm not sure whether it could bundle all third party libraries because it mostly depends on third party library implementation
