### ISSUE TITLE
error[internal]: No such file or directory (os error 2), failed to read

### ISSUE THREAD

**Issue by scull7** [web-infra-dev/rspack#4321]
### System Info

npx envinfo --system --npmPackages '@rspack/*' --binaries --browsers

  System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M2
    Memory: 54.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Firefox: 118.0.2
    Safari: 16.6

### Details

Hi,

We are attempting to utilize rspack to build our React project.  Everything seems to be going well until the very end of the build.  I've attempted to utilize the TRACING feature, but I'm still not able to get additional information on the following error:
```
error[internal]: No such file or directory (os error 2), failed to read
```

I've included the last portion of the trace file below where you can see that the tracing reports that the build is ok, but then we receive the above error. I'm completely stumped at this point.

``` Log file output with tracing
  2023-10-13T20:07:59.333488Z  INFO rspack_node: build ok
    at crates/node_binding/src/lib.rs:142

error[internal]: No such file or directory (os error 2), failed to read



Rspack compiled with 1 error in 64425 ms
```

## rspack.config.js
```javascript
const rspack = require('@rspack/core');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '.env.client') });

module.exports = (_, argv) => ({
  entry: ['./index.tsx'],
  module: {
    rules: [
      {
        test: /\.js$/,
        type: 'jsx',
      },
      {
        test: /\.(pdf)$/,
        type: 'asset/resource',
      },
      {
        test: /\.(?:txt|md)$/,
        type: 'asset/source',
      },
      {
        test: /\.(png|jpg|jpeg|ttf|gif)$/,
        type: 'asset',
      },
    ],
  },
  resolve: {
    extensions: ['*', '.ts', '.tsx', '.js', '.jsx'],
  },
  devServer: {
    port: process.env.CLIENT_PORT || 3000,
    open: false,
    server: 'https',
    proxy: {
      '/api': `http://127.0.0.1:${process.env.SERVER_PORT || 8080}`,
    },
    historyApiFallback: true,
    allowedHosts: 'all',
  },
  devtool: 'eval-cheap-source-map',
  builtins: {
    html: [
      {
        template: '../../public/index.html',
        // favicon: '../../public/favicon.ico',
      },
    ],
  },
  plugins: [
    new rspack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(argv.mode), // production or development
        DISABLE_GOOGLETAG: JSON.stringify(process.env.DISABLE_GOOGLETAG),
      },
    }),
  ],
});
```

### Reproduce Steps

`npx rspack serve` or `npx rspack build`

**Comment by hipstersmoothie** [comment]
@hardfist any guidance on getting more debug info out of rspack? I can't really provide a repro since it would probably be the whole app

**Comment by h-a-n-a** [comment]
The error is intended to provide enough resource information:

```
error[internal]: No such file or directory (os error 2), failed to read xxxx
```

This seems failing to print the correct resource path. Would you check if the resource is requested with unsupported protocol? for example: 

```
import "test://abc"
```

We will fix this.

**Comment by hipstersmoothie** [comment]
Yeah I'm getting no path

Importing that path I get the same thing

![CleanShot 2023-10-25 at 08 59 17](https://github.com/web-infra-dev/rspack/assets/1192452/8d7940b8-cc81-4a7e-8dff-48bd3268fc2c)

**Comment by h-a-n-a** [comment]
> Yeah I'm getting no path
> 
> Importing that path I get the same thing
> 
> ![CleanShot 2023-10-25 at 08 59 17](https://user-images.githubusercontent.com/1192452/278074200-8d7940b8-cc81-4a7e-8dff-48bd3268fc2c.png)

@hipstersmoothie It will be great if you can provide me with a reproduction repo :-)

**Comment by hipstersmoothie** [comment]
I wish I could but it would take a long time to track all that down. fwiw that error I screenshotted was just from this program

```js
import "test://abc"
```

I can provide my config if you want

**Comment by hardfist** [comment]
oh it seems a unknown schema, how do you make it run in webpack? it seems you need some alias for it?

**Comment by h-a-n-a** [comment]
bump
