### ISSUE TITLE
support parser.javascript.exportsPresence and importExportsPresence

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4323]
- [parser.javascript.exportsPresence](https://webpack.js.org/configuration/module/#moduleparserjavascriptexportspresence)
- [parser.javascript.importExportsPresence](https://webpack.js.org/configuration/module/#moduleparserjavascriptimportexportspresence)

https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/dependencies/HarmonyImportDependency.js#L125

- webpack-test/cases/cjs-interop/non-existing-export

**Comment by IWANABETHATGUY** [comment]
recover this warning file after support this feature https://github.com/web-infra-dev/rspack/pull/4858#discussion_r1419869788
