### ISSUE TITLE
support hideStack in WebpackError

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4326]
https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/WebpackError.js#L32

- webpack-test/cases/compile/error-hide-stack

**Comment by h-a-n-a** [comment]
I would like to add **part** of this to the new error refactor.

**Comment by h-a-n-a** [comment]
Related: https://github.com/web-infra-dev/rspack/issues/4339
