### ISSUE TITLE
Improve the relevant APIs of StatsError.

### ISSUE THREAD

**Issue by ityuany** [web-infra-dev/rspack#4339]
### What problem does this feature solve?

see [friendly-errors-webpack-plugin](https://github.com/geowarin/friendly-errors-webpack-plugin) , We need to implement similar functionality. This functionality requires extracting information such as StatsError stack, moduleId, etc. Currently, the api for rspack StatsError is not perfect.

### What does the proposed API of configuration look like?

like webpack StatsError

**Comment by h-a-n-a** [comment]
Related https://github.com/web-infra-dev/rspack/issues/4326

**Comment by hardfist** [comment]
bump

**Comment by LingyuCoder** [comment]
Most of StatsError fields had been aligned with webpack:

```ts
export interface JsStatsError {
  message: string
  chunkName?: string
  chunkEntry?: boolean
  chunkInitial?: boolean
  file?: string
  moduleIdentifier?: string
  moduleName?: string
  moduleId?: string
  chunkId?: string
  details?: string
  stack?: string
  moduleTrace: Array<JsStatsModuleTrace>
}
```

Cause the error handling of rspack on the rust side cannot be completely consistent with nodejs of webpack. Can these fields meet your needs?

**Comment by LingyuCoder** [comment]
I will close this issue as completed. If you meet some problem again, please just reopen this.
