### ISSUE TITLE
SplitChunks async node tests hang forever

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#4342]
There are some reasons that webpack-test/configCases/split-chunks/runtime-chunk-foo hangs

- webpack-test/configCases/split-chunks/runtime-chunk-async-node
- webpack-test/configCases/split-chunks/runtime-chunk-node
- webpack-test/configCases/split-chunks/runtime-chunk-node-13130

**Comment by hardfist** [comment]
@JSerFeng  is this solved?
