### ISSUE TITLE
better resolve error message

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4348]
webpack:

<img width="606" alt="Screenshot 2023-10-17 at 20 13 32" src="https://github.com/web-infra-dev/rspack/assets/42857895/065f9706-22d8-4b73-896a-c8de830050eb">

rspack: 

<img width="606" alt="Screenshot 2023-10-17 at 20 14 02" src="https://github.com/web-infra-dev/rspack/assets/42857895/2c9c3c23-071e-4d25-9319-246dd4c0ea58">

webpack will show how it resolved, sometime it's helpful developer for finding why not the path is resolved

and a good looking error frame is also good to have

**Comment by hardfist** [comment]
does oxc_resolver already supports track resolve process by tracing?

**Comment by chenjiahan** [comment]
It can be helpful to output detailed resolve information by default.

Considering that the number of logs will increase, we need to provide a friendly log format / frame

**Comment by Boshen** [comment]
Should be fixed by the latest changes.
