### ISSUE TITLE
use unplugin-vue-components, after build, element-ui component style miss

### ISSUE THREAD

**Issue by Ttou** [web-infra-dev/rspack#4354]
### System Info

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/Library/Caches/fnm_multishells/61651_1697593992058/bin/node
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/61651_1697593992058/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 17.0
  npmPackages:
    @rspack/cli: ^0.3.7 => 0.3.7 

### Details

when use `unplugin-vue-components` with import `sass` style

Development is ok

![image](https://github.com/web-infra-dev/rspack/assets/4298437/eed9b42f-3ac8-4170-8c83-b5309f4f8c85)

After build, css file content error

![image](https://github.com/web-infra-dev/rspack/assets/4298437/e925b69b-c654-41c7-ba66-0efbe32cf88b)

![image](https://github.com/web-infra-dev/rspack/assets/4298437/651b972f-186d-450a-be5b-3240ac5d5edb)

Remove the `@font-face` style, component style will be ok

### Reproduce link

https://github.com/Ttou/rspack-issue-vue2-style

### Reproduce Steps

1. pnpm i
2. pnpm build
3. pnpm serve
4. http://localhost:3000/

**Comment by h-a-n-a** [comment]
We don't guarantee the correctness output of `unplugin-vue-components` for now. This will be fixed as soon as we fully supported this https://github.com/web-infra-dev/rspack/issues/4408

**Comment by chenjiahan** [comment]
`unplugin-vue-components/rspack` has been supported, you can upgrade `unplugin` to >= 1.6.0
