### ISSUE TITLE
support import attributes

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4358]
https://github.com/tc39/proposal-import-attributes

- webpack-tests/cases/json/import-assertions-type-json

**Comment by chenjiahan** [comment]
@ahabhgk what's the current status of this issue?

I tried the following code in Rspack and it works:

```js
import test from "./foo.json" with { type: "json" };

console.log(test);
```

**Comment by chenjiahan** [comment]
I think it was transformed by SWC, if I add the `swc.jsc.experimental.keepImportAttributes: true` option, I will get the parsing error:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/14829fc3-ed7c-4778-ac0f-b39ea667b4e6)

**Comment by hardfist** [comment]
close since this seems solved
