### ISSUE TITLE
function type support missing for critical splitChunks options

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#4376]
### System Info

N/A

### Details

Hello, 
with rspack we are currently missing the support of function type for the below critical options.

1) splitChunks.cacheGroups.{cacheGroup}.test: https://www.rspack.dev/config/optimization-split-chunks.html#splitchunkscachegroupscachegrouptest
2) splitChunks.cacheGroups.{cacheGroup}.name :  https://www.rspack.dev/config/optimization-split-chunks.html#splitchunkscachegroupscachegroupname

Both of these options are supported as function types in webpack which makes it possible to parse modules at build time. 
https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouptest

### Reproduce Steps

N/A

**Comment by pushkargupta9807** [comment]
@hardfist fyi ^

**Comment by pushkargupta9807** [comment]
@JSerFeng @hardfist just wanted to follow up with this item - do we have nay updates? I have been blocked to move one of our apps in production. Thanks!

**Comment by hardfist** [comment]
@pushkargupta9807 it's a common need, we may support it in near future

**Comment by pushkargupta9807** [comment]
Thanks @hardfist - but it is kinda urgent  for the timelines I am running into.  Initially I was told it was an easier need to support - hence the follow up since it is a little more than a month.   Can it please be prioritized?

**Comment by bvanjoi** [comment]
I will handle it today.
