### ISSUE TITLE
Sourcemap cannot be turned off

### ISSUE THREAD

**Issue by ZLY201** [web-infra-dev/rspack#4382]
### System Info

```bash
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    pnpm: 8.6.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.3.5 => 0.3.7
```

### Details

Sourcemap cannot be turned off.

I tried the follow way to close sourcemap:

1. set `--devtool false` to build command
2. set `builtins.emotion.sourceMap: false`
3. set `tsconfig.json sourceMap: false`
4. set `NODE_ENV=production` to build command

But still not working. My output `js` files always has '*.js.map'.

### Reproduce Steps

1. use `npm create rspack@latest` create rspack project
2. install packages
3. run build

And then you can see all the files has its sourcemap.

**Comment by ahabhgk** [comment]
add `devtool: false` in your rspack.config.js

**Comment by tjx666** [comment]
webpack will turn off sourcemap in production mode, why rspack behaviour different with webpack?
