### ISSUE TITLE
Clean up `.vscode/launch.json`

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#4390]
### System Info

nothing

### Details

The configuration in ﻿`.vscode/launch.json` is not universal, thus we need to add it to the `﻿.gitignore` file.

And I suggest we add a `﻿.vscode/launch.example.json` file to aid developers in debugging this project.

### Reproduce Steps

nothing

**Comment by hardfist** [comment]
why do we need to add it to .gitignore ? it seems works for every vscode users now?

**Comment by bvanjoi** [comment]
It's not a universal configuration; it's possible that you want to debug file `A`, but someone else wants to debug file `B`, which can be very confusing if it's all logged by git.

**Comment by hardfist** [comment]
oh I get your point, vscode lacks the ability to interactive prompt argument for users like clion

**Comment by hardfist** [comment]
but I am thinking .vscode/launch.example.json maybe not better, since you need to rename file and change debug target too, an out of box debugging would be better

**Comment by hardfist** [comment]
a related issue https://github.com/microsoft/vscode/issues/93823
