### ISSUE TITLE
Debugging some cases in a single step.

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#4391]
### What problem does this feature solve?

I've detailed the process of mixed debugging between JS and Rust in a test suite in https://github.com/web-infra-dev/rspack/discussions/4389. However, this may still be complex. Could we perhaps create a script to invoke the debugger in a single step, like ﻿`./x debug examples/basic`?

### What does the proposed API of configuration look like?

nothing

**Comment by hardfist** [comment]
if it works it will be nice, but I'm not sure whether we can make it work

**Comment by bvanjoi** [comment]
Completed at https://github.com/web-infra-dev/rspack/pull/4611
