### ISSUE TITLE
CI: failed to write output.md in Test Compatibility Diff

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4392]
### System Info

None

### Details

<img width="954" alt="image" src="https://github.com/web-infra-dev/rspack/assets/1430279/af2bbeb5-13bb-42df-b458-181fae3e6bc5">

### Reproduce link

https://github.com/web-infra-dev/rspack/actions/runs/6585548894/job/17892441857?pr=4374

### Reproduce Steps

None

**Comment by jerrykingxyz** [comment]
The ci seems successful, please check the link address.

**Comment by Boshen** [comment]
The error causes it not to post a Test Compatibility Diff comment.
