### ISSUE TITLE
splitChunks.cacheGroups.{cacheGroup}.test support function type

### ISSUE THREAD

**Issue by lemon-yogurt** [web-infra-dev/rspack#4399]
### What problem does this feature solve?

splitChunks.cacheGroups.{cacheGroup}.test support function type

### What does the proposed API of configuration look like?

module.exports = {
  //...
  optimization: {
    splitChunks: {
      cacheGroups: {
        svgGroup: {
          test(module) {
            // `module.resource` contains the absolute path of the file on disk.
            // Note the usage of `path.sep` instead of / or \, for cross-platform compatibility.
            const path = require('path');
            return (
              module.resource &&
              module.resource.endsWith('.svg') &&
              module.resource.includes(`${path.sep}cacheable_svgs${path.sep}`)
            );
          },
        },
        byModuleTypeGroup: {
          test(module) {
            return module.type === 'javascript/auto';
          },
        },
      },
    },
  },
};

**Comment by JSerFeng** [comment]
completed in #4722
