### ISSUE TITLE
[Tracking]:  Support unplugin-vue-components/webpack

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4408]
### What subject does this issue tracking?

# [Subject]

```[tasklist]
### Tasks
- [ ] Support `unplugin-vue-components/webpack` resolvers
- [ ] Support transform with `unplugin-vue-components/webpack`
```

**Comment by chenjiahan** [comment]
@h-a-n-a Do we still need this issue? I think `unplugin-vue-components/rspack` can work now.

**Comment by h-a-n-a** [comment]
> @h-a-n-a Do we still need this issue? I think `unplugin-vue-components/rspack` can work now.

We still have some blockers, like https://github.com/web-infra-dev/rspack/issues/3408. But yes, we have nothing to do with webpack now. So let's close this issue and switch to rspack.
