### ISSUE TITLE
Running into a resolution error with experimental newResolver

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#4415]
### System Info

rspack v 0.3.8

### Details

I tried to use the below newResolver , but ran into a resolution issue .   
```
  experiments: {
    rspackFuture: {
      newResolver: true
    }
  }
```
![Screenshot 2023-10-24 at 10 58 05 AM](https://github.com/web-infra-dev/rspack/assets/93791633/b48e009f-df65-4312-8ad8-3a4bca425b2d)
Strangely it is unable to resolve 'path' package

  

### Reproduce Steps

N/A

**Comment by hardfist** [comment]
it seems right behavior if you target web since path is a builtin nodejs module，you can check the behavior of wrbpack
