### ISSUE TITLE
support String.raw for context module

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4420]
https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/dependencies/ContextDependencyHelpers.js#L130

- webpack-test/cases/parsing/complex-require

**Comment by faga295** [comment]
Can you assign this to me?I can help to support this @ahabhgk

**Comment by hardfist** [comment]
thanks in advance
