### ISSUE TITLE
Should emit diagnostics using shared reference of compilation

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#4433]
Some stages in plugin, it can only access shared reference of compilation, but we need mutable ref to push diagnostics

**Comment by ahabhgk** [comment]
Which test blocked by this?

**Comment by JSerFeng** [comment]
configCases/css/conflicting-order should emit warnings

**Comment by JSerFeng** [comment]
bump

**Comment by JSerFeng** [comment]
We can return diagnostics and make caller to handle diagnostics
