### ISSUE TITLE
resolve to wrong module with aliasFields

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4446]
`webpack-test/cases/resolving/browser-field` should pass

**Comment by Boshen** [comment]
Here are the missing pieces:

1. `node_modules` is missing from https://github.com/web-infra-dev/rspack/tree/main/webpack-test/cases/resolving/browser-field

2. To pass this: https://github.com/web-infra-dev/rspack/blob/6f85b0360cf8a65569c2d5188c882269c891688b/webpack-test/cases/resolving/browser-field/index.js#L2

We need to set `browserField: true` in the webpack config

https://github.com/web-infra-dev/rspack/blob/6f85b0360cf8a65569c2d5188c882269c891688b/packages/rspack/src/config/zod.ts#L321-L325

But it seems like there is a big mismatch between all these configs - See https://www.rspack.dev/config/resolve.html#resolvealiasfield and https://webpack.js.org/configuration/resolve/#resolvealiasfields

**Comment by Boshen** [comment]
I'm still investigating on how to pass

https://github.com/web-infra-dev/rspack/blob/6f85b0360cf8a65569c2d5188c882269c891688b/webpack-test/cases/resolving/browser-field/index.js#L40-L43

**Comment by Boshen** [comment]
For debugging what's being passed into `oxc_resolver`:

```
cd webpack-test
OXC_RESOLVER=TRACE pnpm t -- -t "resolving browser-field" | grep  alias_fields
```

and you should see `alias_fields: [["browser"]]`

<img width="1272" alt="image" src="https://github.com/web-infra-dev/rspack/assets/1430279/4b374a52-c93a-4ca6-8585-b13fdf44933b">
