### ISSUE TITLE
Cannot bundle Modules correctly

### ISSUE THREAD

**Issue by navanshu** [web-infra-dev/rspack#4454]
### System Info

I am bundling an express server for local development, the repo uses type: module

### Details

Webpack is able to run it perfectly, almost same config

### Reproduce link

https://codesandbox.io/p/sandbox/rspack-type-module-pz3vhx?file=%2Frspack.config.js%3A11%2C5

### Reproduce Steps

.

**Comment by hardfist** [comment]
@navanshu  it's fixed in latest 1.0.0-beta.4 please check
