### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rspack#4458]
### System Info

    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: 0.3.6 => 0.3.6

### Details

When I'm attempting to get an environment variable with new rspack.DefinePlugin I can't get it.

`new rspack.DefinePlugin({
    'process.env.REACT_APP_API_URL': JSON.stringify(process.env.REACT_APP_API_URL)
}),`

I have the environment variable in .env | .env.local | .env.development . I tried all but allways undefiend. If the environment variable is setted in the machine seems that it's getting correct values.

### Reproduce Steps

1. Put a environment variable in a file.
2. rspack serve and get undefined

**Comment by IWANABETHATGUY** [comment]
You need https://github.com/rspack-contrib/rspack-plugins/tree/main/packages/plugin-dotenv to load your `.env` file into process env.

**Comment by JoseBuendiaDigio** [comment]
Hi @IWANABETHATGUY I saw that this plugin in 0.0.3 isn't working, should we use another ? Webpack-dot-env ?
