### ISSUE TITLE
`reg_str` in `ContextOptions` not works

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#4464]
### System Info

nothing

### Details

It appears that ﻿`reg_str` is not works, and we should attempt to implement the `﻿Eq` trait for ﻿`RspackRegexp`.

<img width="282" alt="image" src="https://github.com/web-infra-dev/rspack/assets/30187863/830f0e24-cffc-4cc5-9a0a-b83c3b550fcc">

### Reproduce Steps

nothing

**Comment by LingyuCoder** [comment]
Resolved by #6273
