### ISSUE TITLE
使用rspack serve 启动服务报 Cannot find module '@rspack/core'

### ISSUE THREAD

**Issue by tal-elemer** [web-infra-dev/rspack#4472]
### System Info

node: v16.19.0
 npm: v8.19.3

### Details

<img width="1018" alt="image" src="https://github.com/web-infra-dev/rspack/assets/131746180/0dacc14d-a346-414e-9673-4a9c00e80b99">

### Reproduce Steps

使用https://github.com/web-infra-dev/rspack/blob/main/examples/vue2/rspack.config.js上的demo，执行npm run dev之后

**Comment by IWANABETHATGUY** [comment]
如果你用的是自己独立的仓库，需要手动安装 pnpm i -D `@rspack/core`

**Comment by tal-elemer** [comment]
最后用pnpm 是ok了
