### ISSUE TITLE
html-webpack-plugin has a warn that does not meet expectations.

### ISSUE THREAD

**Issue by ityuany** [web-infra-dev/rspack#4473]
### System Info

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 71.67 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/64416_1698647082843/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/64416_1698647082843/bin/npm
    pnpm: 8.1.0 - ~/Library/Caches/fnm_multishells/64416_1698647082843/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
  npmPackages:
    @rspack/cli: 0.3.7 => 0.3.7 
    @rspack/core: 0.3.7 => 0.3.7 
    @rspack/dev-server: 0.3.7 => 0.3.7 

### Details

https://github.com/sheinsight/rspack-demo-contenthash/tree/html-plugin-warn

<img width="1322" alt="image" src="https://github.com/web-infra-dev/rspack/assets/13724214/1cbd2b8f-44b1-429a-9134-717120d38d3d">

### Reproduce link

https://github.com/sheinsight/rspack-demo-contenthash/tree/html-plugin-warn

### Reproduce Steps

1. pnpm install
2. pnpm run build

**Comment by hardfist** [comment]
same as #https://github.com/web-infra-dev/rspack/issues/4467
