### ISSUE TITLE
output.chunkLoadingGlobal can't handle string like '__xxx__';

### ISSUE THREAD

**Issue by GiveMe-A-Name** [web-infra-dev/rspack#4476]
### System Info

  System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.21 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/11279_1676208385213/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6

### Details

Rspack output.chunkLoadingGlobal can't resolve the string like '__xxx__'.
When we set the output.chunkLoadingGlobal as '__LOADABLE_LOADED_CHUNKS__', the rspack output is:
```ts
(self['_LOADABLE_LOADED_CHUNKS_'] = self['_LOADABLE_LOADED_CHUNKS_'] || [])
```
then webpack output is:
```ts
(self["__LOADABLE_LOADED_CHUNKS__"] = self["__LOADABLE_LOADED_CHUNKS__"] || [])
```
The chunkLoadingGlobal as `__LOADABLE_LOADED_CHUNKS__` was set by `loadable-compnent`. It ensures`loadable` loaded normally.

![image](https://github.com/web-infra-dev/rspack/assets/58852732/1c3d2422-08bf-4458-9028-815018fc0d98)

### Reproduce link

https://github.com/GiveMe-A-Name/rspack-chunkLoadingGlobal

### Reproduce Steps

1. pnpm install 
2. pnpm run build:all
3. watch the `dist/rspack/web` && `dist/webpack/web`

**Comment by hardfist** [comment]
!canary
