### ISSUE TITLE
Hope to increase support for svg-sprite-loader

### ISSUE THREAD

**Issue by allenli178** [web-infra-dev/rspack#4483]
### What problem does this feature solve?

![image](https://github.com/web-infra-dev/rspack/assets/53218750/6e8ff1c3-370d-4c1a-a7ea-f9886ea5f0aa)
目前无法使用svg-sprite-loader,希望增加支持。

@rspack/cli:v0.3.8
svg-sprite-loader:v6.0.11

[svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader)

### What does the proposed API of configuration look like?

-

**Comment by wuchengwei-tal** [comment]
There are subtle differences in the structure of loaderContext between rspack and webpack. For non extract mode in svg-sprite-loader,  you could just add some property placeholder to make the loader works
// svg-sprite-loader-compat.js
```js
const { NAMESPACE } = require('svg-sprite-loader/lib/config');
const configure = require('svg-sprite-loader/lib/configurator');
const Exceptions = require('svg-sprite-loader/lib/exceptions');

 // --snip--
  if (!content.includes('<svg')) {
    throw new Exceptions.InvalidSvg(content, matchedRules);
  }

  /* compat code */
  loaderContext.target = 'web';
  loaderContext._module = {};

  const configObj = { context: loaderContext };
 // --snip--
```
// in config file
```
loader: resolve('./svg-sprite-loader-compat.js')
```

**Comment by xc2** [comment]
bump

**Comment by coderwyd** [comment]
Will an official solution be provided please?

**Comment by h-a-n-a** [comment]
Landed in https://github.com/web-infra-dev/rspack/pull/6631
