### ISSUE TITLE
builtin:swc-loader do not provide a type declaration 

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#4485]
### What problem does this feature solve?

we use builtin:swc-loader, but can't get  type declaration from rspack, only reference document.

https://www.rspack.dev/guide/loader.html#builtinswc-loader

### What does the proposed API of configuration look like?

```
import { SwcLoaderOptions } from '@rspack/core';
```

**Comment by hardfist** [comment]
after a second thought and suggestion from @07akioni, we can put this type in @rspack/cli other than pollute @rspack/core.
```js
import { defineSwcLoader }  from '@rspack/cli';
export default ({
  module: {
     rules: [{
       test: /\.js/,
       loader: defineSwcLoader.Loader,
       options: defineSwcLoader({
              jsc: {},
              transformer: {}
        })
     }]
  }
});
```

**Comment by chenjiahan** [comment]
We can also use the `@type` jsdoc:

```js
export default {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: 'builtin:swc-loader',
            /** @type {import('@rspack/utils').SwcLoaderOptions} */
            options: {
              jsc: {},
            },
          },
        ],
      },
    ],
  },
};
```

> From https://github.com/mdx-js/mdx/tree/main/packages/loader#use

**Comment by chenjiahan** [comment]
I do not prefer the `@rspack/utils' solution, as users have to install an extra package just to type the SWC loader.

**Comment by xc2** [comment]
prefer `RspackSwcLoader` and `defineRspackSwcLoaderOptions`  exported by both `@rspack/core` and `@rspack/cli` just as same as other rspack/webpack builtin things like `SwcJsMinimizerRspackPlugin` and `SwcJsMinimizerRspackPluginOptions`

**Comment by chenjiahan** [comment]
I will add the typing this week.
