### ISSUE TITLE
第三方依赖package入口指向问题

### ISSUE THREAD

**Issue by a599155162** [web-infra-dev/rspack#4489]
### System Info

编译后结果
![image](https://github.com/web-infra-dev/rspack/assets/28429119/6815cb9f-0a6b-4b1a-8f93-71be67308064)

依赖 package.json
![image](https://github.com/web-infra-dev/rspack/assets/28429119/4684174e-d690-48a6-8980-689d91cbf668)

### Details

第三依赖入口路径不是 `./` 开头

### Reproduce Steps

依赖
```
{
  "name": "vue-property-decorator",
  "version": "9.1.2",
  "main": "lib/index.umd.js",
  "module": "lib/index.js"
...
  }
```

**Comment by bvanjoi** [comment]
Could you provide the reduced repo where the issue was reproduced?

**Comment by a599155162** [comment]
> Could you provide the reduced repo where the issue was reproduced?

你好！
添加了 `resolve.exportsFields` 字段出现问题。
```
{
  resolve: {
    "exportsFields": ["unpkg", "module", "main"],
  },
}
```

原因：部分依赖引用指向不是项目所需，我需要自定义依赖指向
