### ISSUE TITLE
Upgrade pnpm so it won't error in nodejs 20

### ISSUE THREAD

**Issue by Austaras** [web-infra-dev/rspack#4509]
### System Info

-

### Details

pnpm/pnpm#6424

### Reproduce Steps

-

**Comment by bvanjoi** [comment]
pr weclome

**Comment by Austaras** [comment]
This is unactionable because pnpm 8 doesn't support nodejs 14.

**Comment by hverlin** [comment]
Why is NodeJS 14 required for the pipeline?

**Comment by hardfist** [comment]
> Why is NodeJS 14 required for the pipeline?

https://github.com/web-infra-dev/rspack/discussions/4579 discuss here about NodeJS compatible

**Comment by hardfist** [comment]
We will deprecate NodeJS 14 support since 0.4.0

**Comment by Boshen** [comment]
I pushed some changes to branch `try-node-20` https://github.com/web-infra-dev/rspack/tree/try-node-20. I haven't got a clue what pnpm 8 is doing, any help is appreciated 😅 

It's currently failing on `pnpm run test:example`:

```
examples/loader-compat build$ rspack build
│ error[internal]: Napi Error: GenericFailure - Thread Loader (Worker 0)
│ Cannot find module 'ajv/dist/compile/codegen'
│ Require stack:
│ - /Users/bytedance/github/rspack/node_modules/babel-loader/node_modules/ajv-formats/dist/limit.js
│ - /Users/bytedance/github/rspack/node_modules/babel-loader/node_modules/ajv-formats/dist/index.js
│ - /Users/bytedance/github/rspack/node_modules/babel-loader/node_modules/schema-utils/dist/validate.js
```

We have ajv 6 somewhere but it requires ajv 7+

**Comment by Boshen** [comment]
This is on the 0.4.0 branch.
