### ISSUE TITLE
Support for entry.dependOn option. 

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#4511]
### What problem does this feature solve?

https://webpack.js.org/concepts/entry-points/#entrydescription-object

For some of the apps, I need to load some other bundle before the main bundle. So requesting this option . 

 Also open to any suggestions/ alternatives for the same. 

### What does the proposed API of configuration look like?

https://webpack.js.org/concepts/entry-points/#entrydescription-object

**Comment by pushkargupta9807** [comment]
bump

**Comment by instagibb** [comment]
I am also needing this feature! Or are there any other ways to do the same with rspack?

**Comment by pushkargupta9807** [comment]
bump

**Comment by chenjiahan** [comment]
Supported, see https://github.com/web-infra-dev/rspack/pull/6069
