### ISSUE TITLE
rspack generates the wrong style sort, In some extreme cases there are error products

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4513]
### System Info

System:
    OS: macOS 13.5.1
    CPU: (8) x64 Apple M1
    Memory: 46.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.3.8 => 0.3.8 

### Details

In this complex demo, rspack generated incorrect style sorting
The close button did not close correctly
<img width="1336" alt="image" src="https://github.com/web-infra-dev/rspack/assets/19773879/af98be9f-ed4c-4cc0-8b03-dd2df512525e">

But that's right in the webpack
<img width="1355" alt="image" src="https://github.com/web-infra-dev/rspack/assets/19773879/0676c1f8-0b8b-40ee-b235-ed64ca3b6f74">

so seriously affect the use of production

### Reproduce link

https://github.com/jeromehan/rspack-import-demo

### Reproduce Steps

1. pnpm i
2. npm run dev 
3. npm dev:webpack
4. browse https://10.242.16.131:8089/#/hello

**Comment by jeromehan** [comment]
@hardfist This product problem is in urgent need of help in locating the problem，Thank you

**Comment by jeromehan** [comment]
@JSerFeng Can you quickly locate the problem? Thanks

**Comment by hardfist** [comment]
@jeromehan even rspack behaves different with webpack here, it doesn't always mean rspack is wrong here, because bundle splitting itself can't guarantee css order,see https://github.com/webpack-contrib/mini-css-extract-plugin/issues/959#issuecomment-1744582081, so it's may caused the result of bundle splitting diffs here

**Comment by hardfist** [comment]
@JSerFeng when I disable splitChunks, rspack have 2 css chunk why webpack 3 css chunk, which seems weird

**Comment by jeromehan** [comment]
Looks like it's caused by enabled devFriendlySplitChunks.

**Comment by hardfist** [comment]
@jeromehan  since devFriendlySplitChunks will be deprecated in the future and webpack &rspack behaves the same now, this issue can be closed now
