### ISSUE TITLE
Dotenv support after rspack-plugin-dotenv abandonment

### ISSUE THREAD

**Issue by dmathisen** [web-infra-dev/rspack#4521]
### What problem does this feature solve?

I've been using [/IWANABETHATGUY/rspack-plugin-dotenv](https://github.com/IWANABETHATGUY/rspack-plugin-dotenv) to support `.env` configurations and it's worked great until very recently.

After the rspack v0.3.10 release and the migration over to [DefinePlugin](https://www.rspack.dev/config/plugins.html#defineplugin), the `rspack-plugin-dotenv` author archived the repo because of the warnings rspack throws. There is [1 open issue](https://github.com/IWANABETHATGUY/rspack-plugin-dotenv/issues/3) in the repo that talks about the archival. It suggests using the [/rspack-contrib/rspack-plugins](https://github.com/rspack-contrib/rspack-plugins/tree/main/packages/plugin-dotenv) repo... but the installation instructions point right back to the abandoned package. It's very confusing. I've [raised an issue](https://github.com/rspack-contrib/rspack-plugins/issues/8) on that repo.

In any case, I can't figure out any way to use Dotenv without throwing this warning and using an abandoned package. Any direction on this will be greatly appreciated. Thank you!

![image](https://github.com/web-infra-dev/rspack/assets/684701/352ff9c9-d516-4ad7-9cdb-8a1b8bef097e)

**Edit **
I'm just realizing that IWANABETHATGUY is a main contributor for rspack. So there must good reason for this and I'm just missing something. I'm still lost through and can't find anything online that has helped.

**Comment by hardfist** [comment]
sorry for confusing，gonna fix it

**Comment by bvanjoi** [comment]
https://github.com/rspack-contrib/rspack-plugins/pull/9 will help

**Comment by bvanjoi** [comment]
closed as completed.
