### ISSUE TITLE
missing linked comments when enable extractComments

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#4524]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.77 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 7.29.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 15.6.1

### Details

In webpack mode, when we enable extractComments, it extracts comments from original dist file into `.LICENSE.txt`, and meanwhile, adds a linked comment into origina; dist file. but in rspack, this linked comment is missing from original dist file.

![image](https://github.com/web-infra-dev/rspack/assets/22373761/45b513f3-58be-4542-80b4-eee5b3c3fa27)

### Reproduce link

https://github.com/9aoy/rspack-issue-4524/tree/main

### Reproduce Steps

1. pnpm install
2. pnpm dev

disable this line to test webpack: 
<img width="531" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/97defb82-9a6b-4724-a75d-277531abcee2">

**Comment by chenjiahan** [comment]
@bvanjoi In some cases, `*.LICENSE.txt` is not generated, so this banner is unnecessary in this case. 

![image](https://github.com/web-infra-dev/rspack/assets/7237365/cf52fbe2-db72-45bb-b83e-12df588980ed)

**Comment by bvanjoi** [comment]
close by #4592
