### ISSUE TITLE
Compatibility with @emotion/babel-preset-css-prop

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rspack#4527]
### What problem does this feature solve?

Hello, we are going to try to migrate a somewhat large application that is in CRA with 3 custom customize-cra configurations.

1. The first of them is `babel-imports`, I understand that there should be no problem because this can currently be done by swc and you support it.
2. The following is a babel preset `@emotion/babel-preset-css-prop` that I have seen that right now could not be used with rspack as I understand. TRUE?
3. And finally it is a less loader with `javascriptEnabled`, this I understand is only about less-loader and there should be no problem either.

### What does the proposed API of configuration look like?

Should be able to migrate from `@emotion/babel-preset-css-prop`

**Comment by hardfist** [comment]
have you tried builtin.emotion？
