### ISSUE TITLE
deprecate builtins.devFriendlySplitchunks

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4531]
builtins.devFriendlySplitchunks is not maintained anymore and we should deprecate it in 0.3.x and remove it in 0.4.x for better maintaince

**Comment by hardfist** [comment]
cc @h-a-n-a @JSerFeng

**Comment by h-a-n-a** [comment]
With respect to the deprecation stage. This ought to be removed in v0.5
