### ISSUE TITLE
Alter sourcemap url?

### ISSUE THREAD

**Issue by dispalt** [web-infra-dev/rspack#4532]
### What problem does this feature solve?

Previously it was pretty easy to alter your sourcemap url so you could point your sourcemaps to something behind some authentication.

### What does the proposed API of configuration look like?

Expose something similar to `SourceMapDevToolPlugin` or if there is an option to configure it, update the docs to do that.

**Comment by xc2** [comment]
have been supported by https://github.com/web-infra-dev/rspack/pull/5108 by @SyMind , and documented by https://github.com/web-infra-dev/rspack-website/pull/624

please follow "[Host Source Maps Externally](https://www.rspack.dev/config/plugins.html#host-source-maps-externally)" section to alter the source map url.
