### ISSUE TITLE
Refactor: use JsUnknown and downcast instead of specific type payload

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4544]
`JsUnknown` and `downcast_into`:

<img width="935" alt="Screenshot 2023-11-06 at 17 53 30" src="https://github.com/web-infra-dev/rspack/assets/42857895/b13ac60b-d4cd-4d31-b8fb-aceda8dc1497">

v.s.

specific type payload:

<img width="935" alt="Screenshot 2023-11-06 at 17 56 21" src="https://github.com/web-infra-dev/rspack/assets/42857895/79a2242e-e4e6-4299-bf56-c000e75ddc00">

Currently we are blocked by `Debug` derive and `Deserialize` derive, since `JsUnknown` didn't implement these trait, if we can remove `rspack_testing` (rust side test) in the future, we might not need to implement these trait on `RawOptions`

**Comment by h-a-n-a** [comment]
Nice idea :--)

**Comment by ahabhgk** [comment]
Implemented
