### ISSUE TITLE
`experiments.rspackFuture.disableTransformByDefault` should include minification

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4556]
Minification should not be a builtin or it will have conflicts with Rspack plugins. Thus we have to turn off the builtin minification if `disableTransformByDefault` is enabled.

**Comment by chenjiahan** [comment]
This issue will be closed as minification is now supported by standalone plugins.

https://www.rspack.dev/plugins/rspack/swc-js-minimizer-rspack-plugin.html
