### ISSUE TITLE
Official method for integrating OXC into Rspack?

### ISSUE THREAD

**Issue by uneknown** [web-infra-dev/rspack#4558]
Is there an official method for integrating OXC into Rspack? I've developed a project designed to analyze JavaScript code and enhance its performance, and I'm now interested in integrating it with Rspack.

**Comment by hardfist** [comment]
you mean oxlint or other tools based on oxc？

**Comment by hardfist** [comment]
cc @Boshen may know better than me.

**Comment by Boshen** [comment]
@uneknown can you provide more context? "a project designed to analyze JavaScript code and enhance its performance" is a bit too vague for me.

**Comment by hardfist** [comment]
closing for missing more info
