### ISSUE TITLE
feat(resolver): print detailed error messages for oxc_resolver

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4564]
### System Info

None

### Details

The current implementation doesn't cover all error messages thrown by oxc_resolver:

https://github.com/web-infra-dev/rspack/blob/f3b27b9d7ad425ea97c06c35d088437558d022db/crates/rspack_core/src/resolver/resolver_impl.rs#L406-L433

Notice it only catches 2 errors and falls back to a generic error. oxc_resolver actually throws a lot more errors: https://github.com/web-infra-dev/oxc/blob/7d85492a03e34fec11e27eae42db28a7c3f12e16/crates/oxc_resolver/src/error.rs#L6

It would be nice to cover and print nice error messages for all of them.

### Reproduce Steps

To get started, try Rspack with the `experiments.rspackFuture.new_resolver = true` configuration and then introduce any of the oxc_resolver errors in your setup.

**Comment by msdlisper** [comment]
hi~ I need some help :), I try to deal with `oxc_resolver: : ResolveError: : IOError` errors, found the inside of the rspack `Error: : Io `is the need to accept the` io: : Error `types, like this:
```
   oxc_resolver::ResolveError::IOError(error) => ResolveError(
      format!("IOError"),
      Error::Io {
        source: error.0.as_ref().unwrap(), // or error.into()
      },
    ),
```
But I found that oxc lacked such an implementation:
https://github.com/oxc-project/oxc/blob/7d85492a03e34fec11e27eae42db28a7c3f12e16/crates/oxc_resolver/src/error.rs#L124

like this: 
```
impl Into<io::Error> for ResolveError
```

Is that true? Or is there another solution?

**Comment by Boshen** [comment]
> https://github.com/oxc-project/oxc/blob/7d85492a03e34fec11e27eae42db28a7c3f12e16/crates/oxc_resolver/src/error.rs#L124

Feel free to add the From / Into trait in oxc_resolver as well, and link it with `oxc_resolver = { path = "..." }` in `rspack_core/Cargo.toml`.

Otherwise give me your work-in-progress branch and I'll add the trait.

**Comment by msdlisper** [comment]
thx~ , I'll submit some code to oxc_resolver later

**Comment by msdlisper** [comment]
I'll have a try

**Comment by msdlisper** [comment]
I have successfully debugging `oxc_resolver` locally, but after all, this needs to update the `oxc-project/oxc` code, so I want to leave a TODO here, and first handle `ResolveError::IOError`, Later I will go to `oxc-project /oxc` to submit a pr and come back to solve this TODO

**Comment by Boshen** [comment]
> I have successfully debugging `oxc_resolver` locally, but after all, this needs to update the `oxc-project/oxc` code, so I want to leave a TODO here, and first handle `ResolveError::IOError`, Later I will go to `oxc-project /oxc` to submit a pr and come back to solve this TODO

I can make a quick release after your PR in oxc 😁
