### ISSUE TITLE
[Tracking]: 打包未生产ts文件

### ISSUE THREAD

**Issue by wyqjs** [web-infra-dev/rspack#4566]
### What subject does this issue tracking?

打包未生产ts文件,配置如下
![image](https://github.com/web-infra-dev/rspack/assets/95618257/de17e003-9d93-42e5-a411-08b0d20f6bc1)
打包后的文件
![image](https://github.com/web-infra-dev/rspack/assets/95618257/5c77af75-6354-44a7-b965-8558909ede4a)

**Comment by hardfist** [comment]
打包产物应该是js，为啥产物会需要ts呢，你是什么场景？

**Comment by wyqjs** [comment]
> 打包产物应该是js，为啥产物会需要ts呢，你是什么场景？

![image](https://github.com/web-infra-dev/rspack/assets/95618257/8a4bea58-2048-4945-958c-4f12513d2070)
就是除了生成js,还需生成对应的声明文件

**Comment by hardfist** [comment]
webpack也不会生成dts，这需要自己用插件处理
