### ISSUE TITLE
打包输出是空对象

### ISSUE THREAD

**Issue by wyqjs** [web-infra-dev/rspack#4582]
### System Info

 System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 27.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 8.7.0 - /usr/local/bin/pnpm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 15.1

### Details

![image](https://github.com/web-infra-dev/rspack/assets/95618257/404efe4c-1ee8-4cda-b785-69c8f4420d8b)
![image](https://github.com/web-infra-dev/rspack/assets/95618257/67912278-6d45-4e75-ba83-21d6c4492ee1)
![image](https://github.com/web-infra-dev/rspack/assets/95618257/6cf2f0bf-77c7-4d1d-a39f-3dd3ec7c1220)
![image](https://github.com/web-infra-dev/rspack/assets/95618257/1f423f65-4ff5-43d2-9b89-9f37263da7e1)
入口文件导出test文件夹内容, 打包后打印是空对象,下图是rspack.config.ts配置
![image](https://github.com/web-infra-dev/rspack/assets/95618257/c2fcaf02-1fde-4b60-8756-54a8d2bde092)

### Reproduce Steps

rspack build && tsc --declaration

**Comment by IWANABETHATGUY** [comment]
Please provide a minimum produce repository.
