### ISSUE TITLE
Remove schema-utils from @rspack/core and @rspack/plugin-react-refresh

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4588]
### What problem does this feature solve?

The `schema-utils` package is based on `ajv`, it causes the following problems:

- `@rspack/core` have more dependencies: [ajv](https://www.npmjs.com/package/ajv), [ajv-formats](https://www.npmjs.com/package/ajv-formats), [ajv-keywords](https://www.npmjs.com/package/ajv-keywords)
- The start-up time of Rspack project is slow down. Ajv will take 50+ms to verify a single plugin.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/4c4bb6af-a087-447c-8dd1-d34ee12774d6)

### What does the proposed API of configuration look like?

Remove `schema-utils` from `@rspack/core` and `@rspack/plugin-react-refresh`.

**Comment by chenjiahan** [comment]
@h-a-n-a Do you think we should remove the `schema-utils` from `@rspack/plugin-react-refresh`?

**Comment by h-a-n-a** [comment]
Sure, Let's do this :-). Providing typing seems enough to me. Only few webpack plugins provide schema checking...

**Comment by chenjiahan** [comment]
Ok~ I will submit the pull requests later.
