### ISSUE TITLE
Logic of exportsInfo.getUsedName is different with webpack

### ISSUE THREAD

**Issue by LingyuCoder** [web-infra-dev/rspack#4596]
Related to #4584 

In CommonJsExportsDependency, it needs to check out that which member of `exports/module.exports/this` is used by `exports_info.get_used_name`.  It should return `UsageState::Unused` when `exports.xxx` is not used by the incoming module, but currently it returns `UsageState::Unknown`.

You can check out this branch https://github.com/web-infra-dev/rspack/tree/chore/runtime-compact-get-default-export , and then run command `npm run test-diff` under `packages/rspack`.

![image](https://github.com/web-infra-dev/rspack/assets/2663351/fa80cb6b-33ff-42aa-b64c-46afc2e3a44b)

And also find that the `__esModule` on exports should sometimes be `UsageState::Unused`, I can not figure out what is wrong. The test case is:  https://github.com/web-infra-dev/rspack/pull/4584/files#diff-0ebf41c140527a83ae3a911c27db6892087096153d942fa0fdc5220f22bc6feaR9

**Comment by IWANABETHATGUY** [comment]
Closed, since it is fixed.
