### ISSUE TITLE
Cannot get `module.exports` when target is `node`

### ISSUE THREAD

**Issue by ZLY201** [web-infra-dev/rspack#4618]
### System Info

```bash
System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 4.41 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 8.12.1 - /opt/homebrew/bin/npm
  pnpm: 8.9.2 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 119.0.6045.123
  Safari: 16.6
npmPackages:
  @rspack/cli: ^0.3.5 => 0.3.11 
  @rspack/plugin-html: ^0.3.11 => 0.3.11 
```

### Details

When I set `target` to `node` to compile the content `module.exports = 1;` I get the output file which `module.exports` is replaced by compressed variables.

So if I use `require('output.js')` I got empty object.

```js
// output.js
!function(){var r={966:function(r,t,o){r.exports=1}},t={};!function o(n){var e=t[n];if(void 0!==e)return e.exports;var i=t[n]={exports:{}};return r[n](i,i.exports,o),i.exports}("966")}();
```

```js
require('output.js'); // {}
```

```js
// rsconfig.js
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
	context: __dirname,
	target: 'node',
	entry: {
		main: "./src/main.jsx"
	},
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		],
		emotion: {
			sourceMap: false
		}
	},
	module: {
		rules: [
			{
				test: /\.svg$/,
				type: "asset"
			}
		]
	}
};
```

### Reproduce Steps

1. Run `npm create rspack@latest`
2. Set `target` to `node` at `rspack.config.js`
3. Set content of `main.jsx` to `module.exports = 1;`

**Comment by h-a-n-a** [comment]
To consume the artifact as a library, you have to set [output.library](https://webpack.js.org/configuration/output/#outputlibrary).
If you have any further questions, please reopen this issue :-)

**Comment by ZLY201** [comment]
> To consume the artifact as a library, you have to set [output.library](https://webpack.js.org/configuration/output/#outputlibrary). If you have any further questions, please reopen this issue :-)

@h-a-n-a But the word `module` is a keyword in `node` env. Why should be compressed?

**Comment by h-a-n-a** [comment]
> > To consume the artifact as a library, you have to set [output.library](https://webpack.js.org/configuration/output/#outputlibrary). If you have any further questions, please reopen this issue :-)
> 
> @h-a-n-a But the word `module` is a keyword in `node` env. Why should be compressed?

@ZLY201 It's kind of different than what you thought. For any modules, there will always be an internal webpack runtime wrapper `__webpack_require__` that works like the same CommonJS runtime provided by Node runtime. This is how Webpack generates internally. Additionally, based on the `output.library`, webpack will generate the corresponding module format using the correct statement like `module.exports.xxx`;
