### ISSUE TITLE
a bot for issue claiming

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#4622]
### What problem does this feature solve?

There are some contributors who don't have the permissions to assign issues to themselves. It would likely be beneficial to employ a bot to handle this functionality. Please refer to https://rustc-dev-guide.rust-lang.org/rustbot.html to get an idea of the desired effect.

### What does the proposed API of configuration look like?

nothing

**Comment by hardfist** [comment]
Good idea, Just Do It
