### ISSUE TITLE
Doctor need some apis or rspack loader data for the builtin: loader analysis.

### ISSUE THREAD

**Issue by easy1090** [web-infra-dev/rspack#4626]
### What problem does this feature solve?

Rsbuild Doctor would interceptor the loader and wrapper the repo's original loader by doctor's proxy loader to get loader execting time and compiled codes data. The details is following:
1. Getting loader resolve path by enhance-resolve,
2. Wrapper the original loader's configs in proxy loader's options[xxx] propoty, and replace the original loader to proxy loader.
3. When execing the proxy loader for modules compiling, proxy loader would getOriginalLoader from the proxy loader's options, and report the start and end time of the execution of OriginalLoader, and obtain the code before and after compilation through the callback function of the loaderContext of the loader.

But, for builtin: loader, doctor cannot get the loader resolve path by enhance-resolve, need rspack support some apis for this or loader data, maybe support loader execting time first.

Thanks~

### What does the proposed API of configuration look like?

Can rspack support built-in loader's pre and post hook? I don't sure if this can support or a good idea. We can discuss this. Maybe we can support loader execting time first.

**Comment by JSerFeng** [comment]
Solutions I thought before:
1: put 2 probe loaders right before and after the builtin loader, and we can get the transform result and rough time cost of the builtin loader, by compare the pre and post probe loaders
2: expose a builtin JS loader function, which internally invokes the native loader, in users view, it has no different with normal loaders. ( not sure if it's easy to implement, Im not familiar with js loader binding

**Comment by easy1090** [comment]
> Sorry for the delay, solutions I thought before:
> 
> 1. put 2 probe loaders right before and after the builtin loader, and you can get the transform result and rough time cost of the builtin loader, by compare the pre and post probe loaders
> 2. expose a builtin JS loader function, which internally invokes the native loader, in users view, it has no different with normal loaders. ( not sure if it's easy to implement, Im not familiar with js loader binding, I can look at it if I got time

Thanks and wonderful ! And I will try the first idea after the rsbuild doctor finish the beta version.

**Comment by h-a-n-a** [comment]
@easy1090 How would you do with inline loaders now? Isn't this expecting some internal APIs in `NormalModule`?

**Comment by easy1090** [comment]
> @easy1090 How would you do with inline loaders now? Isn't this expecting some internal hooks in `NormalModule`?

Sry, just saw this  reply yesterday.

doctor-probe-loader will add before and after the builtin:loader, and the doctor-probe-loader have two functions:
1. report time;
2. report code by loaderContext's fallback function.

**Comment by hardfist** [comment]
I wonder can we solve this by generate tracing file which contains needed loader data

**Comment by easy1090** [comment]
> I wonder can we solve this by generate tracing file which contains needed loader data

For doctor, this idea is ok. Doctor can compatible this.

**Comment by hardfist** [comment]
bump

**Comment by h-a-n-a** [comment]
> there's an optimization when the `builtin:swc-loader` is the first loader in the rule use list.
> 
> https://github.com/web-infra-dev/rspack/blob/6b6429d851009746f73d66bbbf26f10a9241e2bc/crates/rspack_loader_swc/src/lib.rs?plain=1#L131-L155
> 
> i wonder if the current solution of rsdoctor will harm performance.
> 
> Schrödinger's cat?

This is removed in the latest update of loader runner impl: https://github.com/web-infra-dev/rspack/pull/6753.

**Comment by h-a-n-a** [comment]
Been discussed about this. This is deprecated
