### ISSUE TITLE
vue3使用中文目录/文件名启动时报错

### ISSUE THREAD

**Issue by 0604hx** [web-infra-dev/rspack#4630]
### System Info

操作系统：windows 11
处理器：11th Gen Intel(R) i5-11300H 3.11 GHz
node版本：20.8.0 64位
vue版本：3.3.8
vue-loader版本：17.2.2
rspack版本：0.3.11

### Details

您好，我使用官方提供的 vue3 模板项目，能够正常跑起来👍

此时修改 `HelloWorld.vue` 为 `哈喽.vue`，报错如下：

```shell
[webpack-dev-middleware] [Error: error[internal]: Failed to resolve loader: ./node_modules/vue-loader/dist/index.js in E:\workspace\study\rspack-project\src\components NodejsResolver(ResolveFailedTag)
{
 code: 'GenericFailure'
}
```

![image](https://github.com/web-infra-dev/rspack/assets/3523216/1521679c-31b6-4b47-b7aa-59f3d22a0894)

rspack.config.js 配置如下：
```javascript
const { VueLoaderPlugin } = require("vue-loader");

/** @type {import('@rspack/cli').Configuration} */
const config = {
	context: __dirname,
	devtool: false,
	entry: "./src/main.js",
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		]
	},
	plugins: [new VueLoaderPlugin()],
	module: {
		rules: [
			{
				test: /\.vue$/,
				loader: "vue-loader",
				options: {
					experimentalInlineMatchResource: true
				}
			},
			{
				test: /\.svg/,
				type: "asset/resource"
			}
		]
	}
};
module.exports = config;
```

### Reproduce Steps

1. 创建官方 vue3 示例项目
2. 修改组件名或路径，带有中文
3. yarn dev

**Comment by h-a-n-a** [comment]
Added a reproduction demo for 0.4: https://github.com/h-a-n-a/issue_1130_rspack_new_resolver
