### ISSUE TITLE
unplugin-auto-import support

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4638]
we receives lots of issues related to unplugin-auto-import support, we may need to fix this

**Comment by hardfist** [comment]
related to https://github.com/unjs/unplugin/issues/328

**Comment by bvanjoi** [comment]
https://github.com/unjs/unplugin/pull/354

**Comment by bvanjoi** [comment]
For more information, please visit https://github.com/web-infra-dev/rspack/issues/4759#issuecomment-1873689577
