### ISSUE TITLE
[Bug]: Loading css chunk index failed when use magic comments

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#4664]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 7.29.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: latest => 0.3.13 

### Details

I have an async chunk named 'index', and the config as following.
1. I wish it can be output into `/dist/async/index.xxx.js`. but it merged into `/dist/index.xxx.js`
2. When I run build and preview, I get a 'Loading css chunk index failed ' error 
<img width="725" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/a52083e1-795d-4422-80ab-ef35674198f8">

![image](https://github.com/web-infra-dev/rspack/assets/22373761/171e8869-9502-4af6-ae73-882351f6114b)

<img width="1271" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/807d8bcf-e7b7-4202-bdbe-b4dcd1a7387e">

### Reproduce link

https://github.com/9aoy/rspack-issue-reproduce/tree/main/webpack-chunk-name

### Reproduce Steps

1. cd webpack-chunk-name && pnpm i
2. pnpm build
3. pnpm preview

**Comment by bvanjoi** [comment]
related to https://github.com/web-infra-dev/rspack/issues/4318
