### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'xxxx')

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rspack#4669]
### System Info

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 162.64 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.3.13 => 0.3.13 

### Details

在迁移到 Rspack 的时候发现了下面的错误，在业务代码中有些地方会见到这个错误，有些地方显示正常，所以我怀疑是打包器的问题，麻烦看看哈谢谢～

![image](https://github.com/web-infra-dev/rspack/assets/74575471/fb33a16d-44e7-41c6-bd58-9c22b06a1aad)
![image](https://github.com/web-infra-dev/rspack/assets/74575471/bf7ae55e-ca0d-4402-b480-e31880d5b6b8)

### Reproduce link

https://github.com/Lzzzs/rspack-error

### Reproduce Steps

1. pnpm dev
2. 打开浏览器就可以看到报错

**Comment by h-a-n-a** [comment]
Would you try adding this to `module.rules`: 

https://github.com/web-infra-dev/rspack/blob/e1934125d5e003e408f07403bb6ce89e1d379f24/examples/arco-pro/rspack.config.js#L34-L75

And this:

https://github.com/web-infra-dev/rspack/blob/e1934125d5e003e408f07403bb6ce89e1d379f24/examples/arco-pro/rspack.config.js#L120-L123

**Comment by Lzzzs** [comment]
添加了还是这样

**Comment by h-a-n-a** [comment]
> 添加了还是这样

Would you update the reproduction repo so I can see the latest changes?

**Comment by Lzzzs** [comment]
在这个demo 已经不报错了👍 但是我把对应的配置 copy 到了业务项目中，出现了另外一个问题，我尝试下能否在 demo 中复现

![image](https://github.com/web-infra-dev/rspack/assets/74575471/67046373-3aba-4e01-b1fa-99e0402f19c2)

**Comment by Lzzzs** [comment]
在 module.rules中我将 jsx 和 tsx 的配置改成如下，就没问题了，该配置是我通过 Rsbuild 拿的，因为我之前在 Rsbuild 中没出现过这个问题，请问下目前这个配置和刚才你提供的配置有什么本质上的区别吗～

```js
{
    test: /\.(j|t)sx$/,
    loader: 'builtin:swc-loader',
    exclude: [/[\\/]node_modules[\\/]/],
    options: {
        jsc: {
            externalHelpers: true,
            parser: {
                tsx: true,
                syntax: 'typescript',
                decorators: true
            },
            preserveAllComments: true,
            transform: {
                legacyDecorator: true,
                decoratorMetadata: true,
                react: {
                    development: false,
                    refresh: false,
                    runtime: 'automatic'
                }
            }
        },
        isModule: 'unknown',
        minify: false,
        env: {
            targets: [
                '>0.2%',
                'not dead',
                'not op_mini all'
            ],
            mode: 'usage',
            coreJs: '3.32',
            shippedProposals: true
        },
        sourceMaps: true,
        exclude: [],
        inlineSourcesContent: true
    }
},
```

**Comment by h-a-n-a** [comment]
> 在 module.rules中我将 jsx 和 tsx 的配置改成如下，就没问题了，该配置是我通过 Rsbuild 拿的，因为我之前在 Rsbuild 中没出现过这个问题，请问下目前这个配置和刚才你提供的配置有什么本质上的区别吗～
> 
> ```js
> {
>     test: /\.(j|t)sx$/,
>     loader: 'builtin:swc-loader',
>     exclude: [/[\\/]node_modules[\\/]/],
>     options: {
>         jsc: {
>             externalHelpers: true,
>             parser: {
>                 tsx: true,
>                 syntax: 'typescript',
>                 decorators: true
>             },
>             preserveAllComments: true,
>             transform: {
>                 legacyDecorator: true,
>                 decoratorMetadata: true,
>                 react: {
>                     development: false,
>                     refresh: false,
>                     runtime: 'automatic'
>                 }
>             }
>         },
>         isModule: 'unknown',
>         minify: false,
>         env: {
>             targets: [
>                 '>0.2%',
>                 'not dead',
>                 'not op_mini all'
>             ],
>             mode: 'usage',
>             coreJs: '3.32',
>             shippedProposals: true
>         },
>         sourceMaps: true,
>         exclude: [],
>         inlineSourcesContent: true
>     }
> },
> ```

看起来 decorator 是新加入的配置。。

**Comment by h-a-n-a** [comment]
@Lzzzs 考虑到你用的是 rsbuild，rsbuild 应该已经内置了 `builtin:swc-loader` 的转译，重复配置可能会造成比较大的性能损耗。
这个 issue 我先关闭了，后续有问题可以重开 :-)

**Comment by Lzzzs** [comment]
我发现 HMR 失效是咋回事。我看控制台是正常打印信息，但是页面不会更新。

我初始化了一个 Rspack 的项目，能看到浏览器有 reload 的动作。但是在业务代码中，只有控制台在不断输出信息，看不到 reload 的动作，这是啥情况呢？是模块太多了，还是有什么别的问题

![image](https://github.com/web-infra-dev/rspack/assets/74575471/b8c68eb8-818d-4ad4-b4db-6bd3e5d98ff9)

**Comment by h-a-n-a** [comment]
你要不重新提一个 issue？我们再来看下

**Comment by LingyuCoder** [comment]
似乎是一个已知问题，试试这个版本 0.3.13-canary-2e891df-20231116130948 ？

**Comment by Lzzzs** [comment]
> 似乎是一个已知问题，试试这个版本 0.3.13-canary-2e891df-20231116130948 ？

试了下，还是失效，我重新提一个 issue 吧
