### ISSUE TITLE
js loader should use rust side resolver other than enhanced-resolve

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4672]
currently js loader use enhanced-resolver which cause resolve.tsconfig not working for js loader like sass-loader, so we don't support sass alias now， see https://github.com/hardfist/rspack-webpack-nest-alias/pull/1

**Comment by bvanjoi** [comment]
#4945 will address the issue, but I'm uncertain if it's the correct solution.

**Comment by xc2** [comment]
bump

**Comment by 9aoy** [comment]
bump

**Comment by xc2** [comment]
bump
