### ISSUE TITLE
Change webpack test suite to run all tests and produce a compatibility report

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4684]
### What problem does this feature solve?

The webpack test suite ported from the webpack repo contains all the tests that we aim to run. There is also https://rspack-cov.vercel.app/ which shows our current conformance.

Our current strategy for passing these tests is to actively turn these tests on. What we actually want is to run the whole suite and record all the passed and failed tests in a conformance report and have them stored within the repo. This will give us a diff for passing and failing tests for each PR.

This has the advantage of knowing our actual conformance, and also catch regressions where we pass or fail certain cases unknowingly.

I have success of doing this in the oxc project, e.g. https://github.com/oxc-project/oxc/blob/main/tasks/transform_conformance/babel.snap.md https://github.com/oxc-project/oxc/blob/main/tasks/prettier_conformance/prettier.snap.md

Current problems I see:
* We need to commit the snapshot into the repo, which is not dx friendly
* Need to spend more work if we don't require a snapshot

**Comment by hardfist** [comment]
good summary!

**Comment by Boshen** [comment]
Bump. I'm still cleaning up the webpack tests.

**Comment by Boshen** [comment]
Update: need to have all the panics fixed before doing this.
