### ISSUE TITLE
Turn on tracing for oxc_resolver on the Rspack side

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4685]
### What problem does this feature solve?

`oxc_resolver` currently registers its own tracing subscriber globally, this is not really nice and causes some tetsts to fail.

https://github.com/web-infra-dev/rspack/blob/9e53989bab724242e52ac54530dfb1c713545cc6/crates/rspack_core/Cargo.toml#L26

We need to move the logic to https://github.com/web-infra-dev/rspack/tree/main/crates/rspack_tracing

The problem I have is that I don't know what rspack_tracing is doing, and I don't know how to turn oxc_resolver's tracing on :-(

cc @ahabhgk

**Comment by ahabhgk** [comment]
IMO, for oxc_resolver using in Rspack, oxc_resolver is a library, Rspack is the application, so oxc_resolver shouldn't have its own tracing-subscriber, as long as you keep the `tracing::info!()` in oxc_resolver, then those info will be collected into Rspack's tracing-subscriber

**Comment by ahabhgk** [comment]
`RSPACK_PROFILE='TRACE=filter=oxc_resolver=trace&layer=logger' ~/path/to/rspack` this should already works for branch 0.4.0 😄

**Comment by Boshen** [comment]
> `RSPACK_PROFILE='TRACE=filter=oxc_resolver=trace&layer=logger' ~/path/to/rspack` this should already works for branch 0.4.0 😄

I'll never come up with such complicate logging expression ... adding it to the dev guide.
