### ISSUE TITLE
HMR invalid

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rspack#4687]
### System Info

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 1.41 GB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.3.13-canary-2e891df-20231116130948 => 0.3.13-canary-2e891df-20231116130948 

### Details

我发现 HMR 失效是咋回事。我看控制台是正常打印信息，但是页面不会更新。

我初始化了一个 Rspack 的项目，能看到浏览器有 reload 的动作。但是在业务代码中，只有控制台在不断输出信息，看不到 reload 的动作，这是啥情况呢？是模块太多了，还是有什么别的问题

![image](https://github.com/web-infra-dev/rspack/assets/74575471/f28c47bf-78f5-4812-8339-59d825c023d4)

### Reproduce Steps

更新代码，打开浏览器 HMR 未生效

**Comment by hardfist** [comment]
能提供一个最小demo吗？否则不太好查

**Comment by Lzzzs** [comment]
好的，我看看怎么复现出来～
