### ISSUE TITLE
deprecate experiments.IncrementalRebuild

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4708]
it seems experimental.incrementalRebuild is not necessary now(seems no one will use Rspack without setting experimental.incrementalRebuild due to performance issue), we may need to deprecate experimental.incrementalRebuild

**Comment by hardfist** [comment]
cc @h-a-n-a @jerrykingxyz

**Comment by h-a-n-a** [comment]
closed as finished
