### ISSUE TITLE
Rspack production build outputs development build of react instead of production build

### ISSUE THREAD

**Issue by darkenergy96** [web-infra-dev/rspack#4734]
### System Info

  System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 6.87 GB / 31.69 GB
  Binaries:
    Node: 18.16.0 - ~\AppData\Local\pnpm\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 9.5.1 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.6.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: ^0.3.14 => 0.3.14
    @rspack/core: ^0.3.14 => 0.3.14
    @rspack/dev-server: ^0.3.14 => 0.3.14
    @rspack/plugin-html: ^0.3.14 => 0.3.14

### Details

I have migrated an existing ejected CRA React app. I was able to make rspack build work, but the production build outputs the development version of react.

![image](https://github.com/web-infra-dev/rspack/assets/16614251/d0e00f1c-8fac-4c9e-9670-eb3ba26c045b)

**Expected Behaviour**: It should output the production build of Reactjs.

I have referenced the repo link to reproduce and I have not too complicated `rspack.config.js` that works for reproduction.
Environment variables for the production build are set in `build-rspack.js` file.

### Reproduce link

https://github.com/darkenergy96/migrate-cra-to-rspack

### Reproduce Steps

1. run `npm i`
2. run `npm run build-rspack`
3. serve the build folder and view the page
4. check the react build type using the web [extension](https://react.dev/learn/react-developer-tools)

**Comment by hardfist** [comment]
it seems @darkenergy96 you forget to set define
```js
builtins: {
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
  }
}
```

**Comment by darkenergy96** [comment]
It worked for me.
I have used new rspack.DefinePlugin({
 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
})


But this didn't work for me before I have assumed that `rspack.DefinePlugin` works similar to `webpack.DefinePlugin`.

`webpack.DefinePlugin` accepts parameter in this format

```js
{
  'process.env': {
    NODE_ENV: '"production"',
    PUBLIC_URL: '""',
    WDS_SOCKET_HOST: undefined,
    WDS_SOCKET_PATH: undefined,
    WDS_SOCKET_PORT: undefined,
    FAST_REFRESH: 'true'
  }
}
```

This doesn't seem to be the case with `rspack.DefinePlugin`.
It accepts parameter in this format

```js
{
  'process.env.NODE_ENV': '"production"',
  'process.env.PUBLIC_URL': '""',
  'process.env.WDS_SOCKET_HOST': undefined,
  'process.env.WDS_SOCKET_PATH': undefined,
  'process.env.WDS_SOCKET_PORT': undefined,
  'process.env.FAST_REFRESH': 'true'
}
```
