### ISSUE TITLE
官网示例报错

### ISSUE THREAD

**Issue by Ezreal09** [web-infra-dev/rspack#4745]
### System Info

System:
    OS: macOS 11.7.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 224.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
    bun: 1.0.3 - ~/.nvm/versions/node/v18.12.1/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 14.1.2
  npmPackages:
    @rspack/cli: ^0.4.0 => 0.4.0 

### Details

按照https://www.rspack.dev/zh/guide/quick-start.html示例来，执行npx rspack build直接报错
![image](https://github.com/web-infra-dev/rspack/assets/44263381/0272f8ae-6fb0-4064-97ce-8f2812bf3d61)

### Reproduce Steps

官网示例即可

**Comment by xiaojingzhao** [comment]
Just initializing a react-ts project without changing any code, I also got a javascript parsing error.
node: v18.18.2
pnpm: 7.32.0

![image](https://github.com/web-infra-dev/rspack/assets/9643477/532060e1-2660-484e-b520-161870de44d8)
![image](https://github.com/web-infra-dev/rspack/assets/9643477/420cb3e3-8d29-4ffa-ac21-168f348222d6)
![image](https://github.com/web-infra-dev/rspack/assets/9643477/8db00b36-68d0-45f5-bf10-b64994aa0c05)

**Comment by Boshen** [comment]
感谢尝试使用 Rspack。

根据 【Rspack 0.4 发布公告](https://www.rspack.dev/zh/blog/announcing-0.4.html), 我们需要主动在 `module.rules` 中添加

```javascript
{
	test: /.jsx$/,
	loader: 'builtin:swc-loader',
	type: 'javascript/auto',
	options: {
		jsc: {
			parser: {
				syntax: "ecmascript",
				jsx: true
			},
			transform:{
				react: {
					runtime: "automatic"
				}
			},
		},
	},
}
```

`npm create rspack@latest` 暂未对此做适配，我们将尽快修复。

**Comment by hardfist** [comment]
@xiaojingzhao @Ezreal09 it is fixed now，can you retry

**Comment by Ezreal09** [comment]
> @xiaojingzhao @Ezreal09 it is fixed now，can you retry

还是不行，建议你们自己按照官方示例，然后加上上面的配置试一下。

**Comment by Ezreal09** [comment]
> 感谢尝试使用 Rspack。
> 
> 根据 [Rspack 0.4 发布公告](https://www.rspack.dev/zh/blog/announcing-0.4.html), 我们需要主动在 `module.rules` 中添加
> 
> ```js
> {
> 	test: /.jsx$/,
> 	loader: 'builtin:swc-loader',
> 	type: 'javascript/auto',
> 	options: {
> 		jsc: {
> 			parser: {
> 				syntax: "ecmascript",
> 				jsx: true
> 			},
> 			transform:{
> 				react: {
> 					runtime: "automatic"
> 				}
> 			},
> 		},
> 	},
> }
> ```
> 
> `npm create rspack@latest` 暂未对此做适配，我们将尽快修复。
需要将默认禁用转换设置为false
experiments: {
    rspackFuture: {
      disableTransformByDefault: false
    }
  }

**Comment by hardfist** [comment]
@Ezreal09 the `npm create rspack` is fixed, but website is not updated, will update soon

**Comment by dribble-njr** [comment]
配置中针对的是 `jsx` 文件，`test: /.jsx$/`，我在使用 `pnpm create rspack@latest`，选择 `react-ts` 模版。

安装完成后手动指定 `rspack` 为 `0.4`：

```
"@rspack/cli": "^0.4.0",
"@rspack/core": "^0.4.0",
```

此时会报错：

<img width="630" alt="image" src="https://github.com/web-infra-dev/rspack/assets/72367140/37d88613-0b7c-4479-ae82-46a0445a3bda">

对于 `tsx` 应该配置什么规则？

**Comment by dribble-njr** [comment]
版本号：

<img width="216" alt="image" src="https://github.com/web-infra-dev/rspack/assets/72367140/a7b4620c-47bc-4b85-ba61-d7132d650219">

其余配置和下载的模版一样，仅仅更新了 `rspack` 版本。
