### ISSUE TITLE
[Bug]: Rsbuild 使用 unplugin-auto-import 插件报错

### ISSUE THREAD

**Issue by 94ashui** [web-infra-dev/rspack#4759]
### 版本信息

```sh
System:
    OS: macOS 13.4.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 1.13 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.5.2
  npmPackages:
    @rsbuild/core: ^0.1.0 => 0.1.0 
    @rsbuild/plugin-vue: ^0.1.0 => 0.1.0
```

### 问题详情

<img width="632" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/89236888/d5f15986-9fe2-4883-859b-f333fdc077a2">

<img width="1280" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/89236888/eeb0e873-b2bd-4de1-a8b2-873e43b6492f">

在配置文件中添加配置后 rsbuild dev 报错

### 复现链接

https://github.com/94ashui/rsbuild-app

### 复现步骤

1. pnpm install
2. pnpm dev

**Comment by 9aoy** [comment]
Also reproducible in original rspack project (use rspack + html-webpack-plugin).

Minimize demo: https://github.com/9aoy/rspack-issue-reproduce/tree/main/rspack-vue
- pnpm i
- pnpm dev

**Comment by bvanjoi** [comment]
related to https://github.com/unjs/unplugin/pull/354

**Comment by bvanjoi** [comment]
`@rspack/core@0.4.5` + `unplugin-auto-import@0.17.3` + `vue@3.2.45` + `html-webpack-plugin@5.5.7` can work well:

<img width="741" alt="image" src="https://github.com/web-infra-dev/rspack/assets/30187863/b4a49a52-6383-45b9-99d0-74351583b77d">
