### ISSUE TITLE
Support resource end with `.PNG`

### ISSUE THREAD

**Issue by hanhan9449** [web-infra-dev/rspack#4767]
### System Info

rspack: 0.4.0
npm: 10.1.0
node: 20.9.0
os: windows 11 23e2

### Details

When trying to use resources ending in .PNG, the system reports an error.

code:

![image](https://github.com/web-infra-dev/rspack/assets/28822945/fa6594f3-b0a9-4914-98c8-9ee8b57b0b91)

config:

![image](https://github.com/web-infra-dev/rspack/assets/28822945/f6375f26-3fdc-465c-85e5-ac99c60a688d)

error:

![image](https://github.com/web-infra-dev/rspack/assets/28822945/dcc0ae15-5233-4c4d-93ae-31d9e6c29b27)

### Reproduce link

https://github.com/hanhan9449/rspack-040-demo

### Reproduce Steps

- npm i
- npm run build

**Comment by hanhan9449** [comment]
ref: web-infra-dev/rspress#395

**Comment by nomyfan** [comment]
It seems it's caused by no copying regex flags from JS side to RS side.

**Comment by nomyfan** [comment]
Hi, I want to have a try to fix this, would you like to assign it to me? @hardfist
