### ISSUE TITLE
rspack 4.0 版本新模块解析 styled-components 报错

### ISSUE THREAD

**Issue by towavephone** [web-infra-dev/rspack#4770]
### System Info

  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.44 GB / 15.43 GB
    Container: Yes
    Shell: 5.1.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
    pnpm: 7.33.6 - ~/.volta/tools/image/pnpm/7.33.6/bin/pnpm
  Browsers:
    Chrome: 111.0.5563.64
  npmPackages:
    @rspack/cli: 0.4.0 => 0.4.0 
    @rspack/core: 0.4.0 => 0.4.0 

### Details

在使用新解析模块导入时，会报 styled-components 编译错误，报错信息如下：
```bash
Failed to resolve stream in /frontend_example/node_modules/.pnpm/styled-components@5.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/styled-components/dist/styled-components.cjs.js
```

在使用旧解析模块编译正常，即设置以下值：
```js
  experiments: {
    rspackFuture: {
      newResolver: false
    }
  }
```

报错的完整配置如下：
```js
const path = require('path')
const { defineConfig } = require('@rspack/cli')
const fs = require('fs')
const rspack = require('@rspack/core')
// const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
// const NodePolyfill = require('@rspack/plugin-node-polyfill')

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)

const dotenv = resolveApp('.env')

const NODE_ENV = process.env.NODE_ENV
// https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use
const dotenvFiles = [
  `${dotenv}.${NODE_ENV}.local`,
  // Don't include `.env.local` for `test` environment
  // since normally you expect tests to produce the same
  // results for everyone
  NODE_ENV !== 'test' && `${dotenv}.local`,
  `${dotenv}.${NODE_ENV}`,
  dotenv
].filter(Boolean)

// Load environment variables from .env* files. Suppress warnings using silent
// if this file is missing. dotenv will never modify any environment variables
// that have already been set.  Variable expansion is supported in .env files.
// https://github.com/motdotla/dotenv
// https://github.com/motdotla/dotenv-expand
dotenvFiles.forEach(dotenvFile => {
  if (fs.existsSync(dotenvFile)) {
    require('dotenv-expand')(
      require('dotenv').config({
        path: dotenvFile
      })
    )
  }
})

const { DISABLE_OVERLAY } = process.env

module.exports = defineConfig({
  mode: 'development',
  entry: {
    main: './src/index.js'
  },
  builtins: {
    // html: [
    //   {
    //     template: './public/index.html'
    //   }
    // ],
    pluginImport: [
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true
      }
    ]
    // define: {
    //   // 'process.env.NODE_ENV': "'development'",
    //   'import.meta.env': "'development'",
    //   'import.meta.env.MODE': "'development'",
    //   'process.env.NODE_DEBUG': false,
    //   'process.env.BUILD_TOOL': "'rspack'"
    // }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: /src/,
        // use: {
        //   loader: 'builtin:swc-loader',
        //   options: {
        //     // Enable source map
        //     sourceMap: true,
        //     jsc: {
        //       parser: {
        //         syntax: 'ecmascript',
        //         jsx: true
        //       },
        //       externalHelpers: true,
        //       preserveAllComments: false,
        //       transform: {
        //         react: {
        //           runtime: 'automatic',
        //           pragma: 'React.createElement',
        //           pragmaFrag: 'React.Fragment',
        //           throwIfNamespace: true,
        //           useBuiltins: false
        //         }
        //       }
        //     },
        //     rspackExperiments: {
        //       import: [
        //         {
        //           libraryName: 'antd',
        //           libraryDirectory: 'es',
        //           style: true
        //         }
        //       ]
        //     }
        //   }
        // },
        // type: 'javascript/auto',
        type: 'jsx'
      },
      {
        test: /\.less$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'less-loader',
            options: {
              lessOptions: { javascriptEnabled: true }
            }
          }
        ],
        type: 'css/module'
      },
      {
        test: /\.less$/,
        include: /node_modules/,
        use: [
          {
            loader: 'less-loader',
            options: {
              lessOptions: { javascriptEnabled: true }
            }
          }
        ],
        type: 'css'
      },
      // {
      //   test: /\.css$/,
      //   type: 'css'
      // },
      {
        test: /\.(png|svg|jpg|jpeg|ttf)$/,
        type: 'asset'
      }
    ]
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'antd/es/theme': false // 修复因 @ant-design/pro-components 导致的编译报错问题
    },
    extensions: ['.js'],
    mainFields: ['main', 'browser', 'module']
  },
  // plugins: [
  //   new MonacoWebpackPlugin({
  //     languages: ['json']
  //   })
  //   // new NodePolyfill()
  // ],
  devServer: {
    port: 3000,
    allowedHosts: 'all',
    client: {
      overlay: !DISABLE_OVERLAY
    }
  },
  devtool: 'source-map',
  snapshot: {
    resolve: {
      hash: true,
      timestamp: false
    },
    module: {
      hash: true,
      timestamp: false
    }
  },
  experiments: {
    rspackFuture: {
      // 先开启默认转换，因为有些三方库不兼容，比如会报 ahooks 下的 export 未定义
      disableTransformByDefault: false, // 开启默认转换
      // newResolver: false
    }
  },
  stats: {
    preset: 'errors-only',
    reasons: true,
    hash: true,
    builtAt: true,
    timings: true
  },
  plugins: [
    new rspack.HtmlRspackPlugin({
      template: './public/index.html'
    }),
    new rspack.ProgressPlugin(),
    new rspack.DefinePlugin({
      // 'process.env.NODE_ENV': "'development'",
      'import.meta.env': "'development'",
      'import.meta.env.MODE': "'development'",
      'process.env.NODE_DEBUG': false,
      'process.env.BUILD_TOOL': "'rspack'"
    })
  ]
})
```

### Reproduce Steps

1. pnpm i styled-components@5.2.1
2. 使用以上 rspack 配置
3. 启动项目

**Comment by Boshen** [comment]
<img width="921" alt="image" src="https://github.com/web-infra-dev/rspack/assets/1430279/9532b56b-2298-4841-a6ec-1624c8d81acf">

5.2.1 的 package.json 提供了 main 和 browser 两个导出，你的 resolve.mainFields 配置了 

```
    mainFields: ['main', 'browser', 'module']
  },
```

所以读到了 `dist/styled-components.cjs.js`

该文件中有 `require('stream')` 导致报错。

**Comment by Y80** [comment]
为什么 `@rspack/plugin-node-polyfill` 处理不了呢？

**Comment by hardfist** [comment]
> 为什么 `@rspack/plugin-node-polyfill` 处理不了呢？

你配置里不是把nodePolyfill插件注释了吗？

**Comment by Y80** [comment]
> 你配置里不是把nodePolyfill插件注释了吗？

@hardfist 

提 issue 的是另一个人，我们有个项目之前用 rspack@0.3.8 的时候没问题，今天升级到 rspack@0.4.0 遇到这个问题了。

这是我用当前最新版的 rsbuild 创建的一个 demo，用的的是 rspack@0.4.0，复现了这个问题

<img width="1680" alt="image" src="https://github.com/web-infra-dev/rspack/assets/40132433/d677f675-c398-4851-ac41-6fcc552b4ccc">

你可以看到 address@1.2.2 这个依赖只有 lib/address.js 这一个入口文件

<img width="1521" alt="image" src="https://github.com/web-infra-dev/rspack/assets/40132433/407ab88d-83c3-4bf8-b484-9f5071af1366">

**Comment by hardfist** [comment]
@Y80 提最小demo请使用模板，不要使用截图

**Comment by Y80** [comment]
> @Y80 提最小demo请使用模板提供仓库，不要使用截图

@hardfist 好的，这里是仓库地址：https://github.com/Y80/demo-vue2-rsbuild

**Comment by hardfist** [comment]
因为nodePolyfill本身就没polyfill fs https://github.com/Richienb/node-polyfill-webpack-plugin/blob/main/index.js#L60

**Comment by hardfist** [comment]
@Y80  polyfill如果有问题，单开issue吧，不要在这里讨论了

**Comment by Y80** [comment]
如果 `@rspack/plugin-node-polyfill` 是和 `node-polyfill-webpack-plguin` 完全对齐的话，那这算不上一个问题，因为它确实没有提供对 fs、child_process 这些模块的 polyfill。

但是我看 rsbuild 的插件 `@rsbuild/plugin-node-polyfill` 依赖了模块 `node-libs-browser`，这个是处理了 fs、child_process，项目可以正常跑起来。

我很迷惑啊，rsbuild 是基于 rspack 构建的，但是二者各自的插件是竟然单独实现的......

提供下我的解决方案吧，配置 rspack: `resolve: { fallback: { fs: false, child_process: false} }`

**Comment by hardfist** [comment]
> 如果 `@rspack/plugin-node-polyfill` 是和 `node-polyfill-webpack-plguin` 完全对齐的话，那这算不上一个问题，因为它确实没有提供对 fs、child_process 这些模块的 polyfill。
> 
> 但是我看 rsbuild 的插件 `@rsbuild/plugin-node-polyfill` 依赖了模块 `node-libs-browser`，这个是处理了 fs、child_process，项目可以正常跑起来。
> 
> 我很迷惑啊，rsbuild 是基于 rspack 构建的，但是二者各自的插件是竟然单独实现的......
> 
> 提供下我的解决方案吧，配置 rspack: `resolve: { fallback: { fs: false, child_process: false} }`

cc @chenjiahan

**Comment by chenjiahan** [comment]
Rsbuild 的 Node Polyfill 插件并没有 polyfill fs 模块哈，只是配置了 fs 的 fallback 规则，这个是 webpack / Rspack 里推荐的方案。

参考 https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a#replacing-a-node-module-with-an-empty-implementation

**Comment by chenjiahan** [comment]
感觉这个问题的根因并不是用户配置了 mainFields 导致的。

Rsbuild 没有配置 mainFields，使用了 Rspack 默认的 mainFields，依然存在这个问题。

![image](https://github.com/web-infra-dev/rspack/assets/7237365/9cf2ae3b-704f-4e15-ad07-068c1188ecad)

从现象来看，是开启 newResolver 后没有读取到 styled-components 的 browser 字段，而关闭 newResolver 后可以正常解析。

@Boshen

**Comment by chenjiahan** [comment]
@Boshen 有空看一下哈～

**Comment by Boshen** [comment]
> @Boshen 有空看一下哈～

Which repro should I be looking at? 

This one? https://github.com/Y80/demo-vue2-rsbuild

**Comment by hardfist** [comment]
> > @Boshen 有空看一下哈～
> 
> Which repro should I be looking at?
> 
> This one? [Y80/demo-vue2-rsbuild](https://github.com/Y80/demo-vue2-rsbuild)

you can reproduce the error  in https://github.com/hardfist/rsp-sc

**Comment by Boshen** [comment]
`styled-components` v5 is using some really old techniques for loading browser modules:

https://github.com/styled-components/styled-components/blob/7c065e0b6f890760d7a6759ec5e4a95775b6e688/packages/styled-components/package.json#L6C1-L12C5

```json
  "main": "dist/styled-components.cjs.js",
  "module": "./dist/styled-components.esm.js",
  "browser": {
    "./dist/styled-components.esm.js": "./dist/styled-components.browser.esm.js",
    "./dist/styled-components.cjs.js": "./dist/styled-components.browser.cjs.js"
  },
```

Module resolution has to go from `"module": "./dist/styled-components.esm.js"`, then to `browser`'s `"./dist/styled-components.esm.js": "./dist/styled-components.browser.esm.js"` part in order for things to get resolved correctly.

`oxc_resolver` is currently not doing the second part so it failed to load return `./dist/styled-components.browser.esm.js`.

I'll try and patch it tomorrow.
