### ISSUE TITLE
Error: Cannot find module '/rspack/crates/node_binding/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' in example folder

### ISSUE THREAD

**Issue by xiaojingzhao** [web-infra-dev/rspack#4774]
### System Info

  System:
    OS: macOS 13.6
    CPU: (12) arm64 Apple M2 Pro
    Memory: 134.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.0
  npmPackages:
    @rspack/cli: workspace:^ => 0.4.0 

### Details

I've just clone this repo to local and run `pnpm install` and try to run examples in this repo: examples/basic.

```
cd examples/basic
pnpm run dev
```

And I got this error:
<img width="1053" alt="image" src="https://github.com/web-infra-dev/rspack/assets/9643477/3fdc101f-19e7-44df-8812-fe5a298ef101">

Even though I installed this dependency manually in `rspack/crates/node_binding`, I still got this error as there is no `@rspack/binding-darwin-arm64/rspack.darwin-arm64.node` in node_modules?
<img width="296" alt="image" src="https://github.com/web-infra-dev/rspack/assets/9643477/7b0ed19e-2791-4d96-86bd-1b9bf9d6972c">

### Reproduce Steps

1. git clone https://github.com/web-infra-dev/rspack.git
2. cd rspack
3. pnpm i
4. cd examples/basic
5. pnpm run dev

**Comment by jerrykingxyz** [comment]
The example/basic will use rspack from the workspace, so you should build rspack first.
Here is the doc about building rspack: https://web-infra-dev.github.io/rspack-dev-guide/building/intro.html

**Comment by xiaojingzhao** [comment]
> The example/basic will use rspack from the workspace, so you should build rspack first. Here is the doc about building rspack: https://web-infra-dev.github.io/rspack-dev-guide/building/intro.html

Works for me. Thanks a lot!!
