### ISSUE TITLE
Starter examples in CLI not working as expected in windows

### ISSUE THREAD

**Issue by asrvd** [web-infra-dev/rspack#4798]
### System Info

  System:
    OS: Windows 11 10.0.22621
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 1.13 GB / 7.73 GB
  Binaries:
    Node: 18.18.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 9.8.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 7.9.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: 0.4.0 => 0.4.0
    @rspack/core: 0.4.0 => 0.4.0
    @rspack/plugin-react-refresh: 0.4.0 => 0.4.0

### Details

I used the cmd given in the docs to create a new rspack project `pnpm create rspack@latest`, everything worked perfectly until I ran `pnpm dev`

Here's the error I got -

![image](https://github.com/web-infra-dev/rspack/assets/68690233/dfe779b2-44c2-4eb3-bb37-c500046b2482)

The error arises because you can't set env vars like that on widows, the correct syntax for windows will be - 
`SET NODE_ENV=something`

I changed the scripts in package.json to this and it worked as expected -

```json
...
"scripts": {
    "dev": "SET NODE_ENV=development && rspack serve",
    "build": "SET NODE_ENV=production && rspack build"
  },
...
```

Is there any way we can check for the os info before copying the package.json and make changes accordingly? I'm willing to help on this issue :)

### Reproduce Steps

1. Run `pnpm create rspack@latest` 
2. Choose any starter
3. Run `pnpm dev`

**_note: this is a windows specific issue_**

**Comment by hardfist** [comment]
we need to use [cross-env](https://www.npmjs.com/package/cross-env) to set environment, @asrvd can you give it a try

**Comment by asrvd** [comment]
sure, will update on this soon

**Comment by asrvd** [comment]
> we need to use [cross-env](https://www.npmjs.com/package/cross-env) to set environment, @asrvd can you give it a try

worked perfectly! will make a pr soon 
![image](https://github.com/web-infra-dev/rspack/assets/68690233/653b8a6b-eb61-4885-87cc-a9d82df14396)

**Comment by hardfist** [comment]
thanks in advance

**Comment by asrvd** [comment]
> thanks in advance

just finished making the changes, wanted to run package specific tests but there are no scripts for the package ?

![image](https://github.com/web-infra-dev/rspack/assets/68690233/d78ec506-89ed-4c89-95c3-aad6f61335b0)

**Comment by asrvd** [comment]
tried installing the deps so that I can run the cli manually, but getting this error again

![image](https://github.com/web-infra-dev/rspack/assets/68690233/2efb0b43-46d5-485a-a43c-710b1e5cdf68)

**Comment by daydayhappychao** [comment]
It's still broken, how about use `cross-env` in starter-templates scripts ?
If you think it is useful, I can create a PR soon.

**Comment by hardfist** [comment]
> It's still broken, how about use `cross-env` in starter-templates scripts ? If you think it is useful, I can create a PR soon.

thanks in advance

**Comment by xc2** [comment]
bump
