### ISSUE TITLE
Dynamic import not working with ` (template string)

### ISSUE THREAD

**Issue by LeuisKen** [web-infra-dev/rspack#4800]
### System Info

  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 271.03 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.6.12 - ~/.yarn/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @rspack/cli: 0.4.1 => 0.4.1 
    @rspack/core: 0.4.1 => 0.4.1 
    @rspack/plugin-react-refresh: 0.4.1 => 0.4.1 

### Details

Create a repo for reproducing: https://github.com/LeuisKen/rspack-lazy-load

See: `src/App.tsx`

```
// This line will produce a bad production bundle which can not work.
const Logo = lazy(() => import(`./Logo`));
// This line will works fine.
// const Logo = lazy(() => import('./Logo'));
```

### Reproduce link

https://github.com/LeuisKen/rspack-lazy-load

### Reproduce Steps

- yarn && yarn start, everything works fine.
- run `yarn build`, and use things like `live-server ./dist` to serve the assets
- see the error.

**Comment by bvanjoi** [comment]
reduced:

- `@rspack/cli`: 0.4.1
- `@rspack/core`: 0.4.1

```html
<!-- index.html -->
<!DOCTYPE html>
<body>
</body>
```

```js
// Logo.js
export default "logo"

// index.js
import(`./Logo`).then((res) => {
        if (res.default !== "logo") {
              throw Error('error')
        }
})

// rspack.config.js
const rspack = require("@rspack/core");

module.exports = {
	plugins: [
		new rspack.HtmlRspackPlugin({
			template: "./index.html"
		}),
	]
};
```

steps:

- run `npx rspack build`
- open `dist/index.html` in browser:

![image](https://github.com/web-infra-dev/rspack/assets/30187863/7618f54d-51f2-4476-b0f9-b13855913c25)
