### ISSUE TITLE
Failed to resolve fs

### ISSUE THREAD

**Issue by dmaklygin** [web-infra-dev/rspack#4808]
### System Info

System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.12 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: 7.24.3 - /usr/local/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Safari: 16.5.2
  npmPackages:
    @rspack/core: ~0.1.12 => 0.1.12 
    @rspack/dev-server: ~0.1.12 => 0.1.12 
    @rspack/plugin-minify: ~0.1.12 => 0.1.12 

### Details

The `build/run` commands fail if they face with conditionally imported FS or PATH packages.

```
node_modules/node-email-reply-parser/index.js:30:16
   │
30 │     var path = require('path');
   │                ^^^^^^^^^^^^^^^ Failed to resolve path in .../rspack-demo/node_modules/node-email-reply-parser/index.js
```

### Reproduce Steps

Install please a package `node-email-reply-parser` and use it in application with rspack. I use application created with `@nx/rspack`.

in the `main.tsx` file use the following code:

```tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';

import App from './app/app';

import replyParser from 'node-email-reply-parser'

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

replyParser('blablabla')

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

expectation: the builder must build properly
actual: it fails with error described above

**Comment by Boshen** [comment]
`node-email-reply-parser` has the following snippet https://github.com/t2bot/node-email-reply-parser/blob/ffc9cb00cd118900a4bed6eaff13d2a034d6376e/index.js#L26-L30

```
// Only run this code if we're the main entry point (useful for quick testing locally)
if (require.main === module) {
    // we only import fs and path here because it is bloat to the library otherwise
    var fs = require('fs');
    var path = require('path');

    if (process.argv.length != 3) {
        console.error("Invalid argument. Syntax: node index.js <file path>");
        process.exit(1);
    }

    var fileContents = fs.readFileSync(process.argv[2], 'utf8');
    var text = parse(fileContents, true);

    console.log(text);
}
```

I'm not sure why rspack ended up having `require.main === module` equal to `true` ...

You may create your own `replyParser` function by copying the code from https://github.com/t2bot/node-email-reply-parser/blob/ffc9cb00cd118900a4bed6eaff13d2a034d6376e/index.js#L6C25-L22
