### ISSUE TITLE
support CommonJsSelfReferenceDependency

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#4833]
### What problem does this feature solve?

https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/dependencies/CommonJsSelfReferenceDependency.js#L1-L158

### What does the proposed API of configuration look like?

https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/dependencies/CommonJsSelfReferenceDependency.js#L1-L158

**Comment by LingyuCoder** [comment]
Support by #5114
