### ISSUE TITLE
feat: support prefetch/preload modules

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#4839]
### What problem does this feature solve?

Prefetch and preload chunk

### What does the proposed API of configuration look like?

https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules

**Comment by faga295** [comment]
I can try to support this

**Comment by LingyuCoder** [comment]
> I can try to support this

My work depends on this feature, do you have any plans to implement it in the near future? If not, I will start working on this.

**Comment by faga295** [comment]
ok, currently I'm working on another pr, expecting your your nice work~

**Comment by LingyuCoder** [comment]
Supported in #5031
