### ISSUE TITLE
Does Rspack have a svg logo ?

### ISSUE THREAD

**Issue by lalalazero** [web-infra-dev/rspack#4840]
Hello

I'd like to add framework guide at tailwindcss document side.

like this

![image](https://github.com/web-infra-dev/rspack/assets/20458239/6f0295be-148a-4512-90a0-06d1c3759a08)

so I found out that these brand logos are all svg format. 

Does Rspack have a svg logo too ?

**Comment by chenjiahan** [comment]
Look forward to seeing the Rspack logo on the Tailwindcss page. Maybe Rsbuild should be added too 😄

https://rsbuild.dev/guide/basic/tailwindcss

**Comment by chenjiahan** [comment]
Of course, please check 😄

- minified
![rsbuild-minified](https://github.com/web-infra-dev/rspack/assets/7237365/977e9f1c-1f5f-4915-9389-0ba0483e9947)

- original

![rsbuild-original](https://github.com/web-infra-dev/rspack/assets/7237365/0343ac3b-4395-4487-967f-74044aba3089)
