### ISSUE TITLE
Optimization.splitChunks.cacheGroups.{cacheGroups}.name 

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rspack#4843]
### System Info

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 173.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.4.1 => 0.4.1 
    @rspack/core: 0.4.1 => 0.4.1 

### Details

在 Webpack 中 name 作为函数接收的第一个参数接收的 module，有 size、context 这些属性。但是我看 Rspack 中接收的第一个参数没有这些 key，并且我打印了下，拿到的是一个空的 Module 对象

![image](https://github.com/web-infra-dev/rspack/assets/74575471/692b0c4c-a9c8-4557-88da-2c39b879378c)
![image](https://github.com/web-infra-dev/rspack/assets/74575471/4303d84c-b7b7-4a12-898a-65397c7dc29f)

### Reproduce Steps

1. 配置 cacheGroups 的 name
2. 打印 name 接收的参数

**Comment by h-a-n-a** [comment]
Working as expected. Feel free to file another one if you have other questions ;-)
