### ISSUE TITLE
Build message missing

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rspack#4846]
### System Info

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 370.84 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.4.1 => 0.4.1 
    @rspack/core: 0.4.1 => 0.4.1

### Details

之前 Rspack 打包之后会输出打包出来的详细包信息，现在打包没有信息了 
于是我根据文档去配 https://www.rspack.dev/zh/config/stats.html#statsassets ，打包信息出来了，但不是之前那样的，显示很混乱。并且文档里面默认值是 true 呀，按理说不配也有打包信息的

![image](https://github.com/web-infra-dev/rspack/assets/74575471/8160b2e8-512c-4a5c-9c36-92ade1a7305e)

### Reproduce Steps

1. rspack build

**Comment by xc2** [comment]
你好，文档默认值有误，即将修复。

请问“显示混乱”的样子和“之前不一样”的样子分别是什么样子的。

我试了一下 `0.3.13` 和 `0.4.1` ，在设置 `stats: true` 的情况下：

![image](https://github.com/web-infra-dev/rspack/assets/18117084/eaf90bc7-f69e-44a9-a28a-49e17d54dcf5)
![image](https://github.com/web-infra-dev/rspack/assets/18117084/f4ee9f76-901a-4aad-9e62-c9089ed96918)

两者看起来是一样的

**Comment by Lzzzs** [comment]
是的，cra 迁移的
![image](https://github.com/web-infra-dev/rspack/assets/74575471/acb564ef-0817-4909-8c26-b9ed6d61d8b5)
但是也就是最近更新版本才发现打包的信息变了，之前打包一直都是这样

**Comment by xc2** [comment]
rspack 本身是没有输出这个信息的。

stats 默认值（跟这个问题无关）也只有在 0.0.x -> 0.1.0 的时候从 `normal` 变成了 `errors-warnings`。

如果确认之前执行的命令也是 rspack 不是 react-scripts 的话，有可能是哪个 Plugin 的输出，辛苦提供一下脱敏后的完整配置或者复现仓库或者 codesandbox，以确认是不是 Plugin API 有 breaking

**Comment by Lzzzs** [comment]
我这边也没办法复现了，可能是之前的操作问题吧，我一直以为 rspack 也是这样打包输出的。我就先把 issue 关了，谢谢你哈～
