### ISSUE TITLE
can't load wasm

### ISSUE THREAD

**Issue by ZstoreA** [web-infra-dev/rspack#4860]
### System Info

system: window

### Details

it can't run wasm file

[out3d.zip](https://github.com/web-infra-dev/rspack/files/13540058/out3d.zip)

### Reproduce Steps

1.run npm start
2. error[javascript]: JavaScript parsing error
  ┌─ ..\pkg\out3d\out3d_bg.wasm:1:6
  │
1 │ asm�5```````````~```|`}}`~`}``||`}``|`
  │     Unexpected eof
./out3d_bg.js#__wbg_texStorage3D_c01c31c1b02d75fd8e5f04092346c513bf717
./out3d_bg.js(__wbg_getAttribLocation_7dbdbad935433494bb869d4
./out3d_bg.js)__wbg_getUniformLocation_9f6eb60c560a347b037d
./out3d_bg.js*__wbg_vertexAttribPointer_316ffe2f0458fde7
./out3d_bg.js!__wbg_getContext_6d1f155bb5c1096at_da5f9efa0688cf6d
./out3d_bg.js(__wbg_getAttribLocation_a5a98d5272b01c0dfa9c452
./out3d_bg.js)__wbg_getUniformLocation_688976233799a45ac
./out3d_bg.js*__wbg_vertexAttribPointer_ca11984ee8843c0a
./out3d_bg.js__wbindgen_closure_wrapper1405��f_69193e31c844b792
%&'(

)
!⸮+
,-⸮.#

**Comment by ahabhgk** [comment]
Need a reproduction, and from the error you are using `type: "javascript/auto" to parse wasm, you should use `type: "webassembly/async"`
