### ISSUE TITLE
NPM package treeshaking not handled properly causing split chunks not working

### ISSUE THREAD

**Issue by 07akioni** [web-infra-dev/rspack#4865]
### System Info

Doesn't matter

### Details

![hAM1mxKiAW](https://github.com/web-infra-dev/rspack/assets/18677354/c913614d-9c23-4b75-9226-85f5d4331b50)

![MKXLgvgUzw](https://github.com/web-infra-dev/rspack/assets/18677354/dc6e66a1-9f63-4c0f-bd90-22768b038e6b)

### Reproduce link

https://github.com/07akioni/rspack-treeshaking-issue-reprod

### Reproduce Steps

Follow reproduction link

**Comment by hardfist** [comment]
should be fixed by setting  experiments.rspackFuture.newTreeshaking to true

**Comment by h-a-n-a** [comment]
I will close this issue. If you have tried and find it still not working, feel free to reopen this ;-)
