### ISSUE TITLE
bug(rspack_core): Reading empty path when a path contains a `:`

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4868]
### System Info

Any

### Details

When importing a file path with a plain `:`, e.g. `import "foo:bar"`, Rspack errors with

```
error[internal]: No such file or directory (os error 2), failed to read
```

## Analysis

This is where it throws the error:

https://github.com/web-infra-dev/rspack/blob/30a5647f076c27835f66752d7d9aca6dbfa53e3c/crates/rspack_loader_runner/src/runner.rs#L235-L247

`loader_context.__resource_data` prints

```
[crates/rspack_loader_runner/src/runner.rs:236] &loader_context.__resource_data = ResourceData {
    resource: "foo:bar",
    resource_path: "",
    resource_query: None,
    resource_fragment: None,
    resource_description: None,
    mimetype: None,
    parameters: None,
    encoding: None,
    encoded_content: None,
    scheme: OnceCell(
        Custom(
            "foo",
        ),
    ),
}
```

Notice `resource_path` is an empty string.

### Reproduce link

None

### Reproduce Steps

To reproduce: import any file with a path that contains a `:`, e.g. `import "foo:bar"`.

A real word scenario is importing by `uno:foo.css` (for unocss plugin) + a resolve.alias of `uno:foo.css` -> some file path.

**Comment by Boshen** [comment]
@h-a-n-a You may want to fill in more context here.

**Comment by h-a-n-a** [comment]
@ahabhgk I think this is related to some `UriPlugin`, would you please take a look?

**Comment by ahabhgk** [comment]
webpack does the same:

```js
// webpack.config.js
module.exports = {
	entry: "./index.js",
	resolve: {
		alias: {
			"foo:bar": path.resolve(__dirname, './bar.js')
		}
	}
};
```

```js
// index.js
import 'foo:bar';
```

<img width="1078" alt="Screenshot 2023-12-04 at 17 55 54" src="https://github.com/web-infra-dev/rspack/assets/42857895/d7162b37-36f2-4e4c-9452-f16034751da9">


and https://github.com/web-infra-dev/rspack/pull/4877 align the error message with webpack

**Comment by xc2** [comment]
bump
