### ISSUE TITLE
options apply should not lazily

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#4898]
a history debt, deprecate this by `experiments.rspackFuture.disableApplyOptionsLazily` in 0.5.0 and remove it in 0.6.0

https://github.com/web-infra-dev/rspack/blob/fc6ad596398fc806325053bdae26596468281582/packages/rspack/src/rspackOptionsApply.ts#L43

**Comment by hardfist** [comment]
why deprecate in 0.5 other than 0.4.x?

**Comment by ahabhgk** [comment]
I can deprecate in 0.4.x? Nice, will do it in 0.4.x

**Comment by hardfist** [comment]
> I can deprecate in 0.4.x? Nice, will do it in 0.4.x

of course
