### ISSUE TITLE
`node_modules` being uploaded to npm for `template-*` packages

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4902]
### System Info

None

### Details

https://github.com/web-infra-dev/rspack/actions/runs/7097804716/job/19320624543

![img_v3_025r_c3fb2831-65c0-44ad-b628-f9c8b1d19d8g](https://github.com/web-infra-dev/rspack/assets/1430279/2d3389ff-9d28-44ba-88e6-0d2dae758359)

### Reproduce Steps

None

**Comment by burhanuday** [comment]
Could this be because the gitignore file is named `_gitignore` rather than `.gitignore` in the templates

**Comment by burhanuday** [comment]
The solution would be to have an `.npmignore` file in the templates so that node modules would not be published - https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package
