### ISSUE TITLE
Rspack v0.4.1 minify generates invalid token

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4906]
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.32 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/yarn
    npm: 9.3.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/npm
    pnpm: 7.18.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6

### Details

Rspack v0.4.1 minify generates invalid token and breaks Rspress SSG.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/13628e1a-fe1d-428e-973d-74f79951cb59)

![image](https://github.com/web-infra-dev/rspack/assets/7237365/1830263a-a2ad-4f62-ac69-53f4adcf1cea)

### Reproduce link

https://github.com/chenjiahan/rspack-repro-rspress-ssg-fail

### Reproduce Steps

1. pnpm i
2. pnpm build

**Comment by bvanjoi** [comment]
I think this issue had been fixed.

Related to:
- pr in swc: https://github.com/swc-project/swc/pull/8351 
- bump swc in rspack: https://github.com/web-infra-dev/rspack/pull/4824

And I believe ﻿`rspack@0.4.2` should work just fine.
