### ISSUE TITLE
react-konva resolve error & can`t use outputModule when rspack version > 0.4.0. 

### ISSUE THREAD

**Issue by 1yasa** [web-infra-dev/rspack#4919]
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900KF
    Memory: 11.93 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
    Watchman: 2023.09.18.00 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: 0.4.2 => 0.4.2 
    @rspack/core: 0.4.2 => 0.4.2 
    @rspack/plugin-react-refresh: 0.4.2 => 0.4.2 

### Details

After rspack version 0.4.0, the usage of `outputModule` is no longer supported, and errors are encountered when utilizing react-konva.
<img width="1458" alt="截屏2023-12-06 13 24 30" src="https://github.com/web-infra-dev/rspack/assets/127166080/1f3d10d7-ebfd-4dd5-9888-6acdbac83c3a">
<img width="1176" alt="截屏2023-12-06 13 24 55" src="https://github.com/web-infra-dev/rspack/assets/127166080/c30c059c-5bcd-4f23-bdc4-cfca0336aa8f">

### Reproduce link

https://github.com/1yasa/rspack_reproduce

### Reproduce Steps

1. pnpm run dev
2. Konva import resolve error

**Comment by 1yasa** [comment]
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Konva = void 0;
var _CoreInternals_1 = require("./_CoreInternals");
Object.defineProperty(exports, "Konva", { enumerable: true, get: function () { return _CoreInternals_1.Konva; } });
const _CoreInternals_2 = require("./_CoreInternals");
module.exports = _CoreInternals_2.Konva;
```

https://www.npmjs.com/package/konva?activeTab=code

Possibly caused by the above trick.

**Comment by 1yasa** [comment]
@Boshen take a look, thx, momoda!

**Comment by 1yasa** [comment]
<img width="624" alt="截屏2023-12-10 13 03 05" src="https://github.com/web-infra-dev/rspack/assets/127166080/6ea0b61f-1334-4073-8066-52b5df1fb515">
https://github.com/konvajs/konva/blob/master/src/Core.ts

<img width="794" alt="截屏2023-12-10 13 02 14" src="https://github.com/web-infra-dev/rspack/assets/127166080/b9cf026b-a21e-4d07-94df-9d53771d2b3b">
https://github.com/konvajs/react-konva/blob/master/src/ReactKonvaHostConfig.ts

I'm not sure what caused it, but one thing certain is that, for versions above 4.0, rspack handles modules differently compared to before.

**Comment by Boshen** [comment]
This is the classic problem of import cjs from esm, not a problem with module resolution. Need help from someone who is more familiar with this.

**Comment by 1yasa** [comment]
My question is, why does v4.0 run normally, but v4.1 and v4.2 both report this error? I want to know what updates in rspack caused this issue.

Someone shuold check this.

@hardfist

**Comment by 1yasa** [comment]
> This is the classic problem of import cjs from esm, not a problem with module resolution. Need help from someone who is more familiar with this.

Konva resolve error had been fix by 0.4.3, but `experiments.outputModule`is still in an unavailable state, compared to version 0.4.0.

**Comment by 1yasa** [comment]
<img width="977" alt="截屏2023-12-14 13 35 31" src="https://github.com/web-infra-dev/rspack/assets/127166080/cf79bd3b-4794-4863-8f93-1bd2ce8d267c">
<img width="763" alt="截屏2023-12-14 13 35 43" src="https://github.com/web-infra-dev/rspack/assets/127166080/648b4e54-75a7-45cd-a262-b6c605f182a3">

https://github.com/web-infra-dev/rspack/pull/2684/files

After 0.4.0, `ImportMetaPlugin` seems not to have hit `import.meta.url`.

@ahabhgk

**Comment by LingyuCoder** [comment]
Has the same issue on webpack. When you specify `outputModule: true`, you need to run it in the browser via `<script type="module">`. Therefore, you need to modify the html-rspack-plugin as follows:
```js
new HtmlRspackPlugin({
	template: './public/index.html',
	scriptLoading: "module"
}),
```

I have tried on rspack 0.4.5 and it works

**Comment by 1yasa** [comment]
> Has the same issue on webpack. When you specify `outputModule: true`, you need to run it in the browser via `<script type="module">`. Therefore, you need to modify the html-rspack-plugin as follows:
> 
> ```js
> new HtmlRspackPlugin({
> 	template: './public/index.html',
> 	scriptLoading: "module"
> }),
> ```
> 
> I have tried on rspack 0.4.5 and it works

v0.4.0 not needed.
