### ISSUE TITLE
Rsbuild Vue JSX is broken after enabling newTreeshaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4921]
### System Info

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 964.63 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/yarn
    npm: 8.19.3 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/npm
    pnpm: 8.9.2 - ~/Library/Application Support/fnm/node-versions/v16.19.1/installation/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6

### Details

Rsbuild Vue JSX demo is broken after enabling newTreeshaking:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/46395986-88f5-4c0b-9fcb-39e03670984b)

### Reproduce link

https://github.com/chenjiahan/rsbuild-repro-vue-new-tree-shaking

### Reproduce Steps

1. pnpm i
2. pnpm build
3. pnpm preview
4. open http://localhost:8080/

(dev mode can't repro this issue)

**Comment by IWANABETHATGUY** [comment]
0.4.2-canary-f25925c-20231206112226
