### ISSUE TITLE
Unable to resolve variables defined in definePlugin in rspack mode

### ISSUE THREAD

**Issue by nanianlisao** [web-infra-dev/rspack#4926]
### System Info

pnpm@8.6.0

### Details

I'm encountering an issue where variables defined in definePlugin are not being resolved in rspack mode. Specifically, the variable "ddd" defined in defineConfig's define property is not being resolved when used in an ejs template.

### Reproduce link

https://github.com/nanianlisao/rspack-bug-reproduction
### Reproduce Steps

1. pnpm i
2. pnpm run build:webpack
3. pnpm run build:rspack

Expected behavior: build successed!

Actual behavior: webpack build successed but rspack build **failed**! 

<img width="806" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22850210/690889b4-62dc-4d5b-a804-15f3efc6dc9a">

Please let me know if you need any further information. Thank you!

**Comment by nanianlisao** [comment]
@hardfist 
please take another look . Thx!

**Comment by nanianlisao** [comment]
Okay, but that doesn't seem to be the key. Even if I do it this way, there will still be this error

**Comment by puppet-666** [comment]
> Okay, but that doesn't seem to be the key. Even if I do it this way, there will still be this error

You need to use the [DefinePlugin](https://www.rspack.dev/config/plugins.html#defineplugin) in rspack

**Comment by nanianlisao** [comment]
> I see that the title is used in html in the reproduction repository, but you are defining it in DefinePlugin, perhaps [htmlrspackplugin](https://www.rspack.dev/config/plugins.html#htmlrspackplugin) is what you need to use?

This is just a simple example to demonstrate this phenomenon. In fact, there are a large number of variables in the template that are replaced by definePlugin. This feature works normally in webpack, but an error occurred when switching to rspack.

What I mainly hope to convey is this meaning.

Additionally, using htmlrspackplugin may not achieve the expected results.

**Comment by nanianlisao** [comment]
Using webpack allows for the direct use of define defined variables in the template, which cannot be achieved in rspack.

**Comment by ahabhgk** [comment]
I will take a look in next week

**Comment by ahabhgk** [comment]
It's a bug, https://github.com/web-infra-dev/rspack/pull/5093 will fix it

**Comment by ahabhgk** [comment]
The fix will land in 0.4.5 in next week
