### ISSUE TITLE
官方 vue2 demo 例子，启动提示 Content not from webpack is served from

### ISSUE THREAD

**Issue by godkun** [web-infra-dev/rspack#4934]
### System Info

  System:
    OS: macOS 12.2.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 33.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 15.3

### Details

https://github.com/web-infra-dev/rspack/tree/main/examples/vue2 运行得下图：

![image](https://github.com/web-infra-dev/rspack/assets/26134303/787e0b3c-7fb7-44a4-b35e-994ae56d49c7)

输出 [webpack-dev-server] Content not from webpack is served from 'xxx'

### Reproduce link

https://github.com/web-infra-dev/rspack/tree/main/examples/vue2

### Reproduce Steps

官方此 demo 运行  https://github.com/web-infra-dev/rspack/tree/main/examples/vue2

**Comment by hardfist** [comment]
这个显示有什么问题吗？我看代码运行正常

**Comment by godkun** [comment]
运行是正常，这日志属于正确日志吗？为什么我不用 rspack，用 vite 或者react的脚手架，没有这种输出日志

**Comment by godkun** [comment]
好嘞，非常感谢解答，这个issue可以关掉了，
