### ISSUE TITLE
Support compilation.hooks.optimizeAssets 

### ISSUE THREAD

**Issue by jeromehan** [web-infra-dev/rspack#4938]
### System Info

null

### Details

@unocss/webpack@0.58.0 
```
compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
       compilation.hooks.optimizeAssets.tapPromise(PLUGIN_NAME, async () => {
           ...
       });
});
```
need compilation.hooks.optimizeAssets API

### Reproduce Steps

1. const UnoCSS = require('@unocss/webpack').default
2. plugins: [ UnoCSS()]

**Comment by burhanuday** [comment]
While this is needed for a few plugins to work, the `optimizeAssets` hook is deprecated and to be removed in Webpack 6 @hardfist 
In webpack 5, `optimizeAssets` is just a shim over the `processAssets` hook. should i do the same in Rspack as well?

**Comment by hardfist** [comment]
@burhanuday thank you for this helpful information, I think we can hold on the optimizeAssets implementation until we really need，@jeromehan can you help file a issue | PR in @unocss/webpack@0.58.0 and see whether they're willing to replace it with processAssets implementation

**Comment by hardfist** [comment]
@burhanuday https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/Compilation.js#L817  it seems webpack only deprecate it in source code comment, the users are not aware this hook is deprecated, maybe we should give deprecate warning to plugin author in webpack

**Comment by alexander-akait** [comment]
@hardfist Yeah, you are right, but we are avouding deprecation messages because it was implemented/refactored in the minor version and adding the deprecation message will make mess in console, but for webpack 6 we will add soft deprecation (still a lot of plugins use it, but we will check it before), so I think better do not implement `optimizeAssets` for rspack

**Comment by xc2** [comment]
bump

**Comment by xc2** [comment]
@unocss/webpack will use processAssets hooks in the next version. Stay tuned for updates.

and you also need to create an empty file named `__uno.css` for the plugin to work with rspack.

example: https://github.com/xc2/rspack-usecases/tree/4be82c900bd6af47ada2c63f53922b731bb63a28/rspack/unocss-webpack

**Comment by ljianc** [comment]
> @unocss/webpack will use processAssets hooks in the next version. Stay tuned for updates.
> 
> and you also need to create an empty file named `__uno.css` for the plugin to work with rspack.
> 
> example: https://github.com/xc2/rspack-usecases/tree/4be82c900bd6af47ada2c63f53922b731bb63a28/rspack/unocss-webpack

这样当npm run dev的时候就生成一次css,此后再修改className就不会再生成了

**Comment by hardfist** [comment]
close this issue since we don't plan to support hooks.optimizeAssets hooks
