### ISSUE TITLE
Module Federation: Remote Failed to consume shared lib from Host - App breaks

### ISSUE THREAD

**Issue by saravanan10393** [web-infra-dev/rspack#4948]
### System Info

MAC - M1
Chrome 107

### Details

When configuring Module federation with shared lib option, remotes are failing to consume specified shared library from host, causes application to break. If i disabled library sharing it works

Host Config
```
new rspack.container.ModuleFederationPlugin({
			name: "host",
			remotes: {
				"remote1": "remote1@http://localhost:8081/remoteEntry.js",
				"remote2": "remote2@http://localhost:8082/remoteEntry.js"
			},
			shared: {
				"react": {
					singleton: true,
					eager: true
				},
				"react-dom": {
					singleton: true,
					eager: true
				}
			}
		}),
```

Remote Config
```
new rspack.container.ModuleFederationPlugin({
			name: "remote1",
			filename: "remoteEntry.js",
			exposes: {
				"./button": "./src/button.jsx"
			},
			shared: {
				"react": {
					singleton: true,
					eager: true
				},
				"react-dom": {
					singleton: true,
					eager: true
				}
			}
		}),
```

I have tried setting `eager:true` but still no luck. 
Getting following error in browser console
```
undefined factory webpack/sharing/consume/default/react/react?2aac
__webpack_require__ @ data:text/javascript,import "/Users/saravanan/projects/rspack/mf/basic/host/node_modules/.pnpm/@rspack+core@0.4.2/node_modules/@rspack/core/dist/sharing/initializeSharing.js";
import "/Users/saravanan/projects/rspack/mf/basic/host/node_modules/.pnpm/@rspack+core@0.4.2/node_modules/@rspack/core/dist/container/remotesLoading.js";
import "/Users/saravanan/projects/rspack/mf/basic/host/node_modules/.pnpm/@rspack+core@0.4.2/node_modules/@rspack/core/dist/sharing/consumesLoading.js";:3

```

### Reproduce link

https://github.com/saravanan10393/rspack-module-federation-example/tree/main/basic

### Reproduce Steps

Clone the above repo: 
Start the host - `pnpm run dev`
Start the remote1 - `pnpm run dev`
Start the remote2 - `pnpm run dev`

navigate to `http://localhost:8080`

**Comment by ScriptedAlchemy** [comment]
try not using eager?

**Comment by saravanan10393** [comment]
yes I first tried without eager only. when i searched for the cause , i saw your comment in next js repo to try with eager for this kind of issues. so that tried eager.

**Comment by ScriptedAlchemy** [comment]
yeah i see, it does seem like issue @ahabhgk is Federation Intended to be used yet? is this known issue?

**Comment by ahabhgk** [comment]
Not ready yet, have you tried this in webpack, does this also have error in webpack? if not, then it's a bug

**Comment by saravanan10393** [comment]
I am actively using shared libs with webpack  in live @ahabhgk .

**Comment by ahabhgk** [comment]
Made some debug on the reproduce, this is caused by uniqueName conflict, the package.json name of all three app are the same, so change them into different name solve the problem
