### ISSUE TITLE
[Bug]: Can't use unplugin-vue-components/rspack plugin with html-webpack-plugin

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4963]
### System Info

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v16.20.1/installation/bin/yarn
    npm: 8.19.4 - ~/Library/Application Support/fnm/node-versions/v16.20.1/installation/bin/npm
    pnpm: 7.17.1 - ~/Library/Application Support/fnm/node-versions/v16.20.1/installation/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.0
  npmPackages:
    @rspack/cli: 0.4.2 => 0.4.2 
    @rspack/core: 0.4.2 => 0.4.2 

### Details

Can't use unplugin-vue-components/rspack plugin with html-webpack-plugin:

```bash
error[internal]:   Error: Expression expected
  Expected ';', '}' or <eof>
  
  - default_index.ejs:5 Object../node_modules/.pnpm/html-webpack-plugin@5.5.4_webpack@5.89.0/node_modules/html-webpack-plugin/lib/load    er.js!./node_modules/.pnpm/html-webpack-plugin@5.5.4_webpack@5.89.0/node_modules/html-webpack-plugin/default_index.ejs
    [rspack-repro-unplugin-vue-components]/[html-webpack-plugin@5.5.4_webpack@5.89.0]/[html-webpack-plugin]/default_index.ejs:5:7
  
  - default_index.ejs:27 __webpack_require__
    [rspack-repro-unplugin-vue-components]/[html-webpack-plugin@5.5.4_webpack@5.89.0]/[html-webpack-plugin]/default_index.ejs:27:36
  
  - default_index.ejs:64 
    [rspack-repro-unplugin-vue-components]/[html-webpack-plugin@5.5.4_webpack@5.89.0]/[html-webpack-plugin]/default_index.ejs:64:27
  
  - default_index.ejs:66 
    [rspack-repro-unplugin-vue-components]/[html-webpack-plugin@5.5.4_webpack@5.89.0]/[html-webpack-plugin]/default_index.ejs:66:3
```

If we remove the `html-webpack-plugin` plugin, it can work.

### Reproduce link

https://github.com/chenjiahan/rspack-repro-unplugin-vue-components

### Reproduce Steps

1. pnpm i
2. pnpm build:rspack

**Comment by bvanjoi** [comment]
related to https://github.com/unjs/unplugin/pull/354

**Comment by bvanjoi** [comment]
`@rspack/core@0.4.2` + `html-webpack-plugin@5.5.4` + `unplugin-vue-components@0.26.0` + `unplugin@1.6.0`(overrides)  can work well:

<img width="621" alt="image" src="https://github.com/web-infra-dev/rspack/assets/30187863/040f8f92-ba97-4286-b7e3-2aaf162fcf35">

**Comment by chenjiahan** [comment]
🎉🎉
