### ISSUE TITLE
Align resolver error messages with webpack

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4966]
### What problem does this feature solve?

Part of https://github.com/web-infra-dev/rspack/pull/4952

https://github.com/web-infra-dev/rspack/pull/4952#discussion_r1420119580

> Try not to modify webpack-test, so we can track the different, we may back to align the error message or not to align the error message one day, but let's track it for now
> 

### What does the proposed API of configuration look like?

None

**Comment by hardfist** [comment]
if our resolver error message is better than enhanced-resolve, then it seems we don't need to align this with webpack since error message is not public API

**Comment by Boshen** [comment]
I think it's a case by case problem at this point, let's improve the error message if any one of them is confusing. Aligning all error messages is quiet difficult because the messages are not consolidated in place in webpack.
