### ISSUE TITLE
progressPlugin({profile:true}) result is not accurate

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4973]
the processAssets actually only takes 2ms but the profile reports 185ms
![image](https://github.com/web-infra-dev/rspack/assets/8898718/ef847047-0115-4e7d-835d-3942323c68fe)
![image](https://github.com/web-infra-dev/rspack/assets/8898718/6059ee7a-3f21-4430-b3d9-ff5b540e8b6c)

**Comment by hardfist** [comment]
@faga295 can you help take a look, I'm also wondering how profile caculates the process_assets duration

**Comment by faga295** [comment]
Actually the start time of each hook's duration is the end time of its previous hook, so the process_assets duration is caculated using `optimize_chunk —— process_assets`.In webpack it intercept many hooks, so each hook's duration will be more precise

https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/ProgressPlugin.js#L468-L508

Maybe I can help to intercept more hooks

**Comment by hardfist** [comment]
@faga295 give it a try

**Comment by xc2** [comment]
link #4890

**Comment by hardfist** [comment]
I'm not sure whether we need this functionality considering it's mechanism it not accurate enough, maybe logging.json is more suitable and accurate than progressPlugin({profile:true}), cc @ahabhgk

**Comment by ahabhgk** [comment]
I prefer stats logging for inspecting the time of every hook, but it is not nevertheless, this is a addon feature on top of progress plugin, it's useful for simple cases, but the premise is that it must be accurate enough.

**Comment by xc2** [comment]
bump

**Comment by hardfist** [comment]
seems fixed in #187
