### ISSUE TITLE
Error in production build with library "downsample"

### ISSUE THREAD

**Issue by scttcper** [web-infra-dev/rspack#4980]
### System Info

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.12 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - ~/.volta/tools/image/node/21.3.0/bin/node
    Yarn: 1.22.21 - ~/.volta/tools/image/yarn/1.22.21/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/npm/10.2.4/bin/npm
    pnpm: 8.11.0 - ~/.volta/tools/image/pnpm/8.11.0/bin/pnpm
    bun: 1.0.16 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.1

### Details

When looking at rspack for Sentry ran across this error in the production build. It's just a random library but errors in produciton.

```ts
import { ASAP } from 'downsample/methods/ASAP';

function main() {
  const chartWidth = 1000;
  const smooth = ASAP(
    [
      [0, 1000],
      [1, 1243],
    ],
    chartWidth
  );
  console.log({ smooth });
}

main();
```

The file being imported can be seen here https://cdn.jsdelivr.net/npm/downsample@latest/methods/ASAP.js

```console
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at x (index.bb40e6e0.js:2:785)
    at l (index.bb40e6e0.js:2:583)
    at index.bb40e6e0.js:2:1252
    at r (index.bb40e6e0.js:2:5619)
    at 957 (index.bb40e6e0.js:7:33)
    at n (index.bb40e6e0.js:7:179)
    at index.bb40e6e0.js:7:380
    at index.bb40e6e0.js:7:389
```

### Reproduce link

https://github.com/scttcper/downsample-rspack-error

### Reproduce Steps

npm run build && npm run preview

**Comment by IWANABETHATGUY** [comment]
[minimizer](https://www.rspack.dev/config/optimization.html#optimizationminimizer), a temp workaround

**Comment by IWANABETHATGUY** [comment]
This maybe a upstream minify bug, the code works well when I disable `optimization.minimize`

**Comment by xc2** [comment]
bump

**Comment by xc2** [comment]
I'm closing this issue as the problem is no more reproducable with rsbuild 0.7.10/rspack 0.7.5.

Free feel to ask if you need further help.
