### ISSUE TITLE
Node js API docs/example

### ISSUE THREAD

**Issue by wclr** [web-infra-dev/rspack#4981]
### What problem does this feature solve?

In docs https://www.rspack.dev/api/node-api.html is empty.

I tried to start with Rspack as drop-in replacement for my webpack configs, I use nodejs API and I just do:

```js
import Webpack from "webpack"
import WebpackDevServer from "webpack-dev-server"

// Webpack build
Webpack(config, (err, stats) => {
   
})

// Webpack dev server
  const compiler = Webpack(config)

  const wds = new WebpackDevServer(config.devServer, compiler)

  wds.start()
```

I tried to mimic this with Rspack:
```js
import Rspack from "@rspack/core"
import { RspackDevServer } from "@rspack/dev-server"

const compiler = new Rspack.Compiler("context", config) //  don't know what context is
    
 compiler.run((err, stats) => {
})
```
But I couldn't lauch it it reports errors and here it expects `RspackOptionsNormalized` options.

### What does the proposed API of configuration look like?

So could you explain how to mimic simple Webpack node API with Rspack.

**Comment by noghartt** [comment]
You can use it like this and will have a similar behavior:

```ts
import { rspack } from '@rspack/core';

const compiler = rspack(options);
```

See the type signature [here](https://github.com/web-infra-dev/rspack/blob/fdbe43e49514ca1916b460eff82b8ec3e1c08734/packages/rspack/src/rspack.ts) and how they handle the creation of the compilers [here](https://github.com/web-infra-dev/rspack/blob/9e53989bab724242e52ac54530dfb1c713545cc6/packages/rspack/src/rspack.ts#L118-L129)

**Comment by chenjiahan** [comment]
Document updated, see [JavaScript API](https://www.rspack.dev/api/javascript-api)
