### ISSUE TITLE
Support for glob imports (import.meta.glob)

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#4986]
### What problem does this feature solve?

Vite supports importing multiple modules from the file system via the special `import.meta.glob` function:

```js
const modules = import.meta.glob('./dir/*.js')
```

Rspack supports dynamic import with dynamic paths, but glob imports can import a subset of matching modules more explicitly. So it would be nice if Rspack can support glob imports too.

### What does the proposed API of configuration look like?

Same API as Vite provides: https://vitejs.dev/guide/features.html#glob-import

- ref: https://twitter.com/patak_dev/status/1732667993039986994

**Comment by chenjiahan** [comment]
@hardfist do you think it's time to beyond webpack?

**Comment by chenjiahan** [comment]
A related issue: https://github.com/webpack/webpack/issues/15833

**Comment by hardfist** [comment]
webpack supports require.ensure for sync glob import

**Comment by chenjiahan** [comment]
`import.meta` is part of the ECMAScript standard but `require.context` is a webpack-only API.

I just found webpack has supported `import.meta.webpackContext` and Rspack also supports it: https://github.com/web-infra-dev/rspack/pull/4466

We should document this and recommend users to use `import.meta.webpackContext` instead of `require.context`.

**Comment by MuyianKing** [comment]
![Image](https://github.com/user-attachments/assets/49b004a0-ebf1-453a-9b90-d81bc8ffaed3)
vite的import.meta.glob返回的格式可以和vue-router的路由懒加载完美契合；
我们现在手动维护了一份路由的配置文件
![Image](https://github.com/user-attachments/assets/4e8f43a3-e8f1-42d1-93b9-8c8f70835c0a)
import.meta.webpackContext可以干掉这份文件，但是不支持路由懒加载
