### ISSUE TITLE
perf: 80ms blocking call from node `util.inspect`

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#4996]
### System Info

None

### Details

![image](https://github.com/web-infra-dev/rspack/assets/1430279/4af4ee99-81f6-4b0b-9a55-d501250c5218)

https://github.com/web-infra-dev/rspack/blob/788691710ca2884c934f795583d978180a7c9263/packages/rspack/src/rspack.ts#L66

https://github.com/web-infra-dev/rspack/blob/788691710ca2884c934f795583d978180a7c9263/packages/rspack/src/rspack.ts#L81

The options object is fairly large, which yields a huge blocking call.

### Reproduce Steps

I used `node --inspect-brk` and looked at the js profile from chrome inspect.

**Comment by hardfist** [comment]
never expect util.inspect takes so long, It seems we can just remove it or enable it by environment variable

**Comment by Boshen** [comment]
> never expect util.inspect takes so long, It seems we can just remove it or enable it by environment variable

Either is fine, I don't even know how to get this debug print working ...
