### ISSUE TITLE
Passing MinifyOptions to `minify` option in `rspack.HtmlRspackPlugin`

### ISSUE THREAD

**Issue by wojtekmaj** [web-infra-dev/rspack#5005]
### What problem does this feature solve?

In `webpack-plugin-html`, as well as in `@rspack/plugin-html`, it was possible to pass MinifyOptions as value for `minify` option. This allowed for, for example, turning on JS minification in HTML files. In my setup, this is the biggest difference between how I configure Webpack and Rspack, and a quite painful one, since I would have to manually update all CSP checksums for un-minified JS.

### What does the proposed API of configuration look like?

Refer to `webpack-plugin-html` or `@rspack/plugin-html`.

**Comment by ahabhgk** [comment]
@rspack/plugin-html is deprecated, you can use html-webpack-plugin in rspack, I'd like to know if the difference still exists after switching to html-webpack-plugin

**Comment by wojtekmaj** [comment]
When I use html-webpack-plugin TypeScript gets my config all red. I figured it might not be compatible yet, but I need to dig deeper if that's not expected. Thanks!

**Comment by wojtekmaj** [comment]
Hmm. Checked the latest rspack & latest html-webpack-plugin, still getting TypeScript errors.

```
rspack.config.ts:165:3 - error TS2322: Type '(HtmlWebpackPlugin | { name: BuiltinPluginName; _options: Record<string, string>; affectedHooks: "emit" | "done" | "compilation" | ... 27 more ... | undefined; raw(): BuiltinPlugin; apply(compiler: Compiler): void; } | { ...; } | ReactRefreshRspackPlugin)[]' is not assignable to type '(false | "" | 0 | RspackPluginInstance | RspackPluginFunction | null | undefined)[]'.
  Type 'HtmlWebpackPlugin | { name: BuiltinPluginName; _options: Record<string, string>; affectedHooks: "emit" | "done" | "compilation" | ... 27 more ... | undefined; raw(): BuiltinPlugin; apply(compiler: Compiler): void; } | { ...; } | ReactRefreshRspackPlugin' is not assignable to type 'false | "" | 0 | RspackPluginInstance | RspackPluginFunction | null | undefined'.
    Type 'HtmlWebpackPlugin' is not assignable to type 'false | "" | 0 | RspackPluginInstance | RspackPluginFunction | null | undefined'.
      Type 'HtmlWebpackPlugin' is not assignable to type 'RspackPluginInstance'.
        Types of property 'apply' are incompatible.
          Type '(compiler: import("/Users/wmaj/Projekty/Rewardo/web/node_modules/webpack/types").Compiler) => void' is not assignable to type '(compiler: import("/Users/wmaj/Projekty/Rewardo/web/node_modules/@rspack/core/dist/Compiler").Compiler) => void'.
            Types of parameters 'compiler' and 'compiler' are incompatible.
              Type 'Compiler' is missing the following properties from type 'Compiler': recordsInputPath, recordsOutputPath, records, managedPaths, and 11 more.

165   plugins: [
      ~~~~~~~

  node_modules/@rspack/core/dist/config/zod.d.ts:4807:5
    4807     plugins?: (false | "" | 0 | RspackPluginInstance | RspackPluginFunction | null | undefined)[] | undefined;
             ~~~~~~~
    The expected type comes from property 'plugins' which is declared here on type '{ name?: string | undefined; dependencies?: string[] | undefined; entry?: string | string[] | Record<string, string | string[] | { import: (string | string[]) & (string | string[] | undefined); ... 7 more ...; library?: { ...; } | undefined; }> | undefined; ... 25 more ...; bail?: boolean | undefined; }'


Found 1 error in rspack.config.ts:165
```

**Comment by wojtekmaj** [comment]
A workaround worth exploring (for the end user) is to use:

`new HtmlWebpackPlugin() as unknown as RspackPluginInstance`

but this feels a bit like a hack to me?

**Comment by ahabhgk** [comment]
I see, we will improve the types recently

**Comment by ahabhgk** [comment]
> A workaround worth exploring (for the end user) is to use:
> 
> `new HtmlWebpackPlugin() as unknown as RspackPluginInstance`
> 
> but this feels a bit like a hack to me?

Tracking in another issue, https://github.com/web-infra-dev/rspack/issues/5360

close this issue since the original html issue is solved
