### ISSUE TITLE
Tracking issue for `Stats`

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#501]
Details see [Stats Options](https://webpack.js.org/configuration/stats/#stats-options)

- [ ] stats.all
- [ ] stats.assets
- [ ] stats.assetsSort
- [ ] stats.builtAt
- [ ] stats.moduleAssets
- [ ] stats.assetsSpace
- [ ] stats.modulesSpace
- [ ] stats.chunkModulesSpace
- [ ] stats.nestedModules
- [ ] stats.nestedModulesSpace
- [ ] stats.cached
- [ ] stats.cachedModules
- [ ] stats.runtimeModules
- [ ] stats.dependentModules
- [ ] stats.groupAssetsByChunk
- [ ] stats.groupAssetsByEmitStatus
- [ ] stats.groupAssetsByExtension
- [ ] stats.groupAssetsByInfo
- [ ] stats.groupAssetsByPath
- [ ] stats.groupModulesByAttributes
- [ ] stats.groupModulesByCacheStatus
- [ ] stats.groupModulesByExtension
- [ ] stats.groupModulesByLayer
- [ ] stats.groupModulesByPath
- [ ] stats.groupModulesByType
- [ ] stats.groupReasonsByOrigin
- [ ] stats.cachedAssets
- [ ] stats.children
- [ ] stats.chunks
- [ ] stats.chunkGroups
- [ ] stats.chunkModules
- [ ] stats.chunkOrigins
- [ ] stats.chunksSort
- [ ] stats.context
- [ ] stats.colors
- [ ] stats.depth
- [ ] stats.entrypoints
- [ ] stats.env
- [ ] stats.orphanModules
- [ ] stats.errors
- [ ] stats.errorDetails
- [ ] stats.errorStack
- [ ] stats.excludeAssets
- [ ] stats.excludeModules
- [ ] stats.exclude
- [ ] stats.hash
- [ ] stats.logging
- [ ] stats.loggingDebug
- [ ] stats.loggingTrace
- [ ] stats.modules
- [ ] stats.modulesSort
- [ ] stats.moduleTrace
- [ ] stats.optimizationBailout
- [ ] stats.outputPath
- [ ] stats.performance
- [ ] stats.preset
- [ ] stats.providedExports
- [ ] stats.errorsCount
- [ ] stats.warningsCount
- [ ] stats.publicPath
- [ ] stats.reasons
- [ ] stats.reasonsSpace
- [ ] stats.relatedAssets
- [ ] stats.source
- [ ] stats.timings
- [ ] stats.ids
- [ ] stats.usedExports
- [ ] stats.version
- [ ] stats.chunkGroupAuxiliary
- [ ] stats.chunkGroupChildren
- [ ] stats.chunkGroupMaxAssets
- [ ] stats.warnings
- [ ] stats.warningsFilter
- [ ] stats.chunkRelations
- [ ] Sorting fields
- [ ] EExtending stats behaviours

**Comment by h-a-n-a** [comment]
Closed for stale
