### ISSUE TITLE
Should pass runtimeTemplate to `TemplateContext`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#5013]
### What problem does this feature solve?

here are some examples:  https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/dependencies/HarmonyExportImportedSpecifierDependency.js#L938-L947

https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/dependencies/HarmonyExportImportedSpecifierDependency.js#L1104-L1106

## reference
https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/RuntimeTemplate.js#L1-L1060

### What does the proposed API of configuration look like?

same as webpack

**Comment by IWANABETHATGUY** [comment]
@LingyuCoder would you mind having a look?

**Comment by LingyuCoder** [comment]
> @LingyuCoder would you mind having a look?

OK

**Comment by IWANABETHATGUY** [comment]
Alright, we can align with webpack when we have manpower.

**Comment by alfaproject** [comment]
I've just stumbled upon this issue coming from https://github.com/web-infra-dev/rspack/issues/5316 so I think it's still a valid ask

Any reason to not just use ES5 syntax for everyone anyway? People that need <ES5 can keep using Webpack, surely?

**Comment by LingyuCoder** [comment]
This issue is duplicated with #5136, so I will close this issue and just discuss there.
