### ISSUE TITLE
newTreeshaking seems to confuse the interface definition when exporting all.

### ISSUE THREAD

**Issue by Livre1431** [web-infra-dev/rspack#5017]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 14.10 GB / 47.72 GB
  Binaries:
    Node: 18.18.0 - ~\AppData\Local\nvs\default\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\nvs\default\yarn.CMD
    npm: 9.8.1 - ~\AppData\Local\nvs\default\npm.CMD
    pnpm: 8.12.0 - ~\AppData\Local\nvs\default\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rspack/cli: ^0.4.3 => 0.4.3
    @rspack/core: ^0.4.3 => 0.4.3
    @rspack/plugin-node-polyfill: ^0.4.3 => 0.4.3

### Details

As follows in the repo
```ts
// src/utils/object.ts
export function obj1() {}

export function obj2() {}

export function obj3() {}

// src/utils/index.ts
export * from './object'

// src/index.ts (entry)
export * as utils from '@/utils'
```

```js
// rspack config
... 
experiments: {
  rspackFuture: {
    newTreeshaking: true,
  },
},
...

```

```js 
// output lost my obj definition
!function(){var t={163:function(t,e,n){"use strict";n.r(e),n.d(e,{utils:function(){return r}});var r=n("462")},462:function(t,e,n){"use strict";n.r(e);var r=n("429");n.es(r,e)},429:function(t,e,n){"use strict";function r(){}function o(){}function u(){}n.r(e),n.d(e,{rQ:function(){return r},GN:function(){return o},$n:function(){return u}})}},e={};function n(r){var o=e[r];if(void 0!==o)return o.exports;var u=e[r]={exports:{}};return t[r](u,u.exports,n),u.exports}n.es=function(t,e){return Object.keys(t).forEach(function(n){"default"!==n&&!Object.prototype.hasOwnProperty.call(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:function(){return t[n]}})}),t},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.d=function(t,e){for(var r in e)n.o(e,r)&&!n.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})};var r=n("163");self.main=r}();
//# sourceMappingURL=main.js.map
```
![Snipaste_2023-12-14_17-30-32](https://github.com/web-infra-dev/rspack/assets/50002410/1f7c8aeb-7538-4ea2-abbe-df4758123282)

When I shut down newTreeSharing they went back to normal

![Snipaste_2023-12-14_17-31-54](https://github.com/web-infra-dev/rspack/assets/50002410/f67c955c-f8b3-491a-a751-fa1391599492)

### Reproduce link

https://github.com/Livre1431/rspack-demo

### Reproduce Steps

```bash
pnpm i
pnpm build
```

**Comment by IWANABETHATGUY** [comment]
try this: 
https://github.com/web-infra-dev/rspack/pull/4995

**Comment by IWANABETHATGUY** [comment]
0.4.3-canary-f853ea4-20231214144454

**Comment by Livre1431** [comment]
This version doesn't seem to be settled yet

npmPackages:
    @rspack/cli: 0.4.3-canary-f853ea4-20231214144454 => 0.4.3-canary-f853ea4-20231214144454
    @rspack/core: 0.4.3-canary-f853ea4-20231214144454 => 0.4.3-canary-f853ea4-20231214144454
    @rspack/plugin-node-polyfill: 0.4.3-canary-f853ea4-20231214144454 => 0.4.3-canary-f853ea4-20231214144454

**Comment by IWANABETHATGUY** [comment]
Closed in favor of https://github.com/web-infra-dev/rspack/pull/4995
