### ISSUE TITLE
'symlinks' at "resolve" validation error

### ISSUE THREAD

**Issue by bostondv** [web-infra-dev/rspack#5022]
### System Info

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 37.57 GB / 62.01 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.4 - ~/carrot/customers/store/node_modules/.bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Watchman: 20231210.093346.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: 0.4.3 => 0.4.3 
    @rspack/core: 0.4.3 => 0.4.3 
    @rspack/plugin-react-refresh: 0.4.3 => 0.4.3

### Details

When specifying the `symlinks` option in `resolve` section a config validation error is thrown `Unrecognized key(s) in object: 'symlinks' at "resolve"`

However this is a valid option in webpack and appears to work in rspack.

The option is missing from the validation types here: https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/config/zod.ts#L353

Can we add it to the config validation? 🙏 

### Reproduce Steps

1. Take the [basic example](https://github.com/web-infra-dev/rspack/blob/main/examples/basic/rspack.config.js) and change the config to

```
{
	entry: "./src/index.js",
	plugins: [
		new rspack.HtmlRspackPlugin({
			template: "./index.html"
		})
	],
        resolve: {
               symlinks: false
        }
}
```

2. Run build or serve
3. Observe config error (or warning)

**Comment by hardfist** [comment]
@bostondv can you help make a pr to fix this

**Comment by bostondv** [comment]
> @bostondv can you help make a pr to fix this

For sure, thanks for looking!
