### ISSUE TITLE
Incorrect CSS order after enabling new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5024]
### System Info

@rspack/core 0.4.3

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.15 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    npm: 9.3.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/npm
    pnpm: 8.9.0 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 16.6

### Details

Incorrect CSS order after enabling new tree shaking:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/324a86a1-2978-43bb-afd7-6d83f5ece2a1)

see https://github.com/web-infra-dev/rsbuild/tree/main/e2e/cases/css/css-modules for more details.

### Reproduce link

https://github.com/web-infra-dev/rsbuild

### Reproduce Steps

1. git clone https://github.com/web-infra-dev/rsbuild
2. git checkout new_tree_shaking_1206
3. pnpm i
4. pnpm run e2e:rspack cases/css/css-modules/index.test.ts

or:

4. cd e2e/cases/css/css-modules && npx rsbuild build

**Comment by IWANABETHATGUY** [comment]
try 
0.4.3-canary-3e50d4e-20231218070056
