### ISSUE TITLE
UMD outputs are broken after enabling new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5025]
### System Info

@rspack/core 0.4.3

System:
OS: macOS 13.5.2
CPU: (10) arm64 Apple M1 Pro
Memory: 3.15 GB / 32.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
npm: 9.3.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/npm
pnpm: 8.9.0 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/pnpm
Browsers:
Chrome: 120.0.6099.109
Safari: 16.6

### Details

UMD outputs are broken after enabling new tree shaking.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/83715901-fb34-4cd4-a4bc-230c6a4e4bc4)

![image](https://github.com/web-infra-dev/rspack/assets/7237365/31b6f214-76b1-4837-836f-fecd119dde30)

see https://github.com/web-infra-dev/rsbuild/tree/main/e2e/cases/umd/basic for more details.

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/e2e/cases/umd/basic

### Reproduce Steps

1. git clone https://github.com/web-infra-dev/rsbuild
2. git checkout new_tree_shaking_1206
3. pnpm i
4. cd e2e/cases/umd/basic
5. npx rsbuild build && npx rsbuild preview

**Comment by IWANABETHATGUY** [comment]
maybe related to https://github.com/web-infra-dev/rspack/pull/4901/files

**Comment by chenjiahan** [comment]
@IWANABETHATGUY The `umd/basic` case works now, but the `umd/export` and `umd/export-array` cases are still broken.

1. git clone https://github.com/web-infra-dev/rsbuild
2. git checkout new_tree_shaking_1206
3. pnpm i
4. cd e2e/cases/umd/export
5. npx rsbuild build && npx rsbuild preview
