### ISSUE TITLE
Svelte app is broken after enabling new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5026]
### System Info

@rspack/core 0.4.3

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.15 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    npm: 9.3.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/npm
    pnpm: 8.9.0 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 16.6

### Details

The basic Svelte app is broken after enabling new tree shaking:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/2c98fe4c-aba7-4402-9cf0-7b740e79da79)

see https://github.com/web-infra-dev/rsbuild/tree/main/e2e/cases/svelte/basic/src for more details.

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/e2e/cases/svelte/basic/src

### Reproduce Steps

1. git clone https://github.com/web-infra-dev/rsbuild
2. git checkout new_tree_shaking_1206
3. pnpm i
4. cd e2e/cases/svelte/basic
5. npx rsbuild build && npx rsbuild preview

**Comment by IWANABETHATGUY** [comment]
Seems fixed in main branch
![image](https://github.com/web-infra-dev/rspack/assets/17974631/1d979d4d-4434-4042-88b8-8946e3a41b1c)

**Comment by chenjiahan** [comment]
Good 👍
