### ISSUE TITLE
Can't resolve "@wangeditor/editor-for-vue" 

### ISSUE THREAD

**Issue by inooNgt** [web-infra-dev/rspack#5039]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 7.59 GB / 15.96 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.30.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (114.0.1823.41)
    Internet Explorer: 11.0.19041.3636

### Details

install and import @wangeditor/editor-for-vue,then run rspack ,can see this error:
× Can't resolve "@wangeditor/editor-for-vue" in builtin:swc-loader??clonedRuleSet-1!F:\app\rspack-demo\node_modules\vue-loader\lib\index.js??vue-loader-options!F:\app\rspack-demo\src\App.vue?
  │ vue&type=script&setup=true&lang=ts , maybe it had cycle alias

### Reproduce link

https://github.com/web-infra-dev/rspack/tree/main/examples/vue2-tsx

### Reproduce Steps

1. download vue2-tsx examples:https://github.com/web-infra-dev/rspack/tree/main/examples/vue2-tsx
2. npm i @wangeditor/editor-for-vue
3. import { Editor } from "@wangeditor/editor-for-vue";
4. npm run dev

**Comment by inooNgt** [comment]
"@rspack/cli": "^0.4.3"

**Comment by xc2** [comment]
A minimal reproduce: https://github.com/xc2/rspack-usecases/blob/b037895fb5ac053ba37e8d59a805b82415614052/rspack/same-req-n-path-in-description/mod/package.json
