### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by inooNgt** [web-infra-dev/rspack#5040]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 9.23 GB / 15.96 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.30.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (114.0.1823.41)
    Internet Explorer: 11.0.19041.3636

### Details

use rspack 0.4.3,run this code in app.vue:
`
function test() {
  if (typeof require !== "undefined" && typeof require.ensure === "function") {
    console.log(1111);
  }
}
test();
`

this code will compile to:

`
 function test() {
        if ( true && typeof require.ensure === "function") console.log(1111);
  }
  test();
`
you will see error in browser:
ReferenceError: require is not defined.

I holp 'typeof require' will not change in runtime.

### Reproduce Steps

run this code in rspack project:
`
function test() {
  if (typeof require !== "undefined" && typeof require.ensure === "function") {
    console.log(1111);
  }
}
test();
`

**Comment by bvanjoi** [comment]
> I holp 'typeof require' will not change in runtime.

What is the behavior of Webpack?

**Comment by inooNgt** [comment]
> > I holp 'typeof require' will not change in runtime.
> 
> What is the behavior of Webpack?

function test() {\n  if (true) {\n    console.log(1111);\n  }\n}\ntest();

**Comment by bvanjoi** [comment]
This is not bug.

Currently, it closely resembles Webpack and will ultimately be perfectly aligned with Webpack.

**Comment by inooNgt** [comment]
> This is not bug.
> 
> Currently, it closely resembles Webpack and will ultimately be perfectly aligned with Webpack.
please take a closer look.
rspack does not compile “require.ensure”，but webpack has compiled  it to be true.
