### ISSUE TITLE
panic succeedModule compilation hook 

### ISSUE THREAD

**Issue by bostondv** [web-infra-dev/rspack#5054]
### System Info

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 31.93 GB / 62.01 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.4 - ~/carrot/customers/store/node_modules/.bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Watchman: 20231210.093346.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: 0.4.3 => 0.4.3 
    @rspack/core: 0.4.3 => 0.4.3 
    @rspack/plugin-react-refresh: 0.4.3 => 0.4.3 

### Details

We have a dev server that panics when many source files are changed -- for example changing a git branch with a large diff from main or when running codegen scripts to generate GraphQL types.

The panic appears to be induced only when using the `succeedModule` hook in our dev server script. For example:

```
compiler.hooks.compilation.tap('rspack', compilation => {
  compilation.hooks.succeedModule.tap('rspack', callback)
})
```

When this hook is not used, the panic does not occur.

Panic output (I ran with `RUST_BACKTRACE=full` but didn't get any other output)

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Failed to convert module to JsModule: Error { status: GenericFailure, reason: "Failed to convert module to JsModule", maybe_raw: 0x0 }
Location: crates/node_binding/src/plugins/mod.rs:737

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<empty backtrace>
```

Thank you

### Reproduce Steps

I don't have a simple reproduction example but it should be reproducible as follows:

1. Create a dev server
2. Tap into compilation `succeedModule` hook
3. Modify/delete a large number of source files (there may be a more specific root cause but this is how I've been able to consistently reproduce)

**Comment by alfaproject** [comment]
Just pasting from Discord for reference. This hook also panics:
```
compilation.hooks.buildModule.tap(pluginName, module => {
                    module.useSourceMap = true;
                });
```

**Comment by h-a-n-a** [comment]
> Just pasting from Discord for reference. This hook also panics:
> 
> ```js
> compilation.hooks.buildModule.tap(pluginName, module => {
>   module.useSourceMap = true;
> });
> ```

Modules are now readonly.
