### ISSUE TITLE
support rspack.SourceMapDevToolPlugin

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5060]
### What problem does this feature solve?

support custom sourceMap options 

### What does the proposed API of configuration look like?

same as https://webpack.js.org/plugins/source-map-dev-tool-plugin/

**Comment by bvanjoi** [comment]
There is some overlap with https://github.com/web-infra-dev/rspack/issues/4893.

**Comment by hardfist** [comment]
yeah it's overlapped but both need support
