### ISSUE TITLE
removes all deprecate warning in CI 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5067]
https://github.com/web-infra-dev/rspack/actions/runs/7261029436/job/19781998400#step:5:77
some of the test cases are still using deprecated configuration which should be migrated to new configuration
![image](https://github.com/web-infra-dev/rspack/assets/8898718/2dcb2bc1-417a-4707-8d3f-ebbb2f813cf0)

**Comment by lippzhang** [comment]
please assige to me

**Comment by LingyuCoder** [comment]
resolved by #5127
