### ISSUE TITLE
Support fine-grained tracing analysis

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5071]
![image](https://github.com/web-infra-dev/rspack/assets/8898718/733624ee-9453-4dc6-9797-b9a78797f831)
the current trace data missing lots of internal details which makes it hard to do performance analysis

**Comment by bvanjoi** [comment]
It's better to use instrument or pref rather than tracing

**Comment by hardfist** [comment]
> It's better to use instrument or pref rather than tracing

you cant get useful perf data from users

**Comment by xc2** [comment]
bump
