### ISSUE TITLE
Panic occurred at runtime.

### ISSUE THREAD

**Issue by ssddi456** [web-infra-dev/rspack#5085]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 4.15 GB / 15.95 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 120.0.6099.110
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rspack/cli: ^0.4.3 => 0.4.3
    @rspack/core: ^0.4.3 => 0.4.3
    @rspack/plugin-html: ^0.4.3 => 0.4.3
    @rspack/plugin-node-polyfill: ^0.4.3 => 0.4.3

### Details

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: httpscom/web-infra-dev/rspack/issues
Message:  byte index 382 is not a char boundary; it is inside '色' (bytes 380..383) of ` e,t,a)=>{Object.defineProperty(t,"__esModule",{value:!0}),t.ProgressPlugin=void 0;var n=a9756),i=a(9933),o=a(9547),r=function(e){function t(){var t=null!==e&&e.apply(this,argumenreturn t.rendererName="progress",t.$schema="/sc`[...]
Location: C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\mie\src\handlers\graphical.rs:640

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: napi_register_module_v1
    at <unknown source file>
 6: napi_register_module_v1
    at <unknown source file>
 7: napi_register_module_v1
    at <unknown source file>
 8: node::Stop
    at <unknown source file>
 9: v8::internal::Builtins::code_handle
    at <unknown source file>
10: v8::internal::Builtins::code_handle
    at <unknown source file>
11: v8::internal::Builtins::code_handle
    at <unknown source file>
12: v8::internal::Builtins::code_handle
    at <unknown source file>
13: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
14: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
15: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
16: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
17: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
18: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
19: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
20: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
21: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
22: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
23: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
24: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
25: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
26: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
27: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
28: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
29: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
30: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
31: v8::internal::SetupIsolateDelegate::SetupHeap
    at <unknown source file>
32: v8::internal::Execution::CallWasm
    at <unknown source file>
33: v8::internal::Execution::Call
    at <unknown source file>
34: v8::Function::Call
    at <unknown source file>
35: napi_call_function
    at <unknown source file>
36: node_module_register
    at <unknown source file>
37: node_module_register
    at <unknown source file>
38: uv_async_send
    at <unknown source file>
39: uv_loop_init
    at <unknown source file>
40: uv_run
    at <unknown source file>
41: node::SpinEventLoop
    at <unknown source file>
42: cppgc::internal::Marker::visitor
    at <unknown source file>
43: node::Start
    at <unknown source file>
44: RC4_options
    at <unknown source file>
45: v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor
    at <unknown source file>
46: BaseThreadInitThunk
    at <unknown source file>
47: RtlUserThreadStart
    at <unknown source file>

### Reproduce Steps

havnt found which file trigger this

**Comment by ssddi456** [comment]
0.3.14 is ok  0.4.0 not work

**Comment by h-a-n-a** [comment]
Would you please try this version 0.4.5-canary-b3497fe-20231227113840?

**Comment by ssddi456** [comment]
works fine in v0.5.1

**Comment by dxhsmwqcwelllee** [comment]
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message: Module(/Users/doorgod/Desktop/www/AbcPc/node_modules/sax/lib/sax.js) should be added before using
Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:75

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.

Accidental phenomena, why?

**Comment by h-a-n-a** [comment]
> Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
> 
> Message: Module(/Users/doorgod/Desktop/www/AbcPc/node_modules/sax/lib/sax.js) should be added before using
> 
> Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:75
> 
> 
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> 
> Run with RUST_BACKTRACE=full to include source snippets.
> 
> 
> 
> Accidental phenomena, why?

 This issue has been resolved. Please file a new one instead.
