### ISSUE TITLE
core_1.createCompiler is not a function

### ISSUE THREAD

**Issue by rexizam** [web-infra-dev/rspack#5086]
### System Info

OS: Kubuntu 23.10
Node: 18
@nx: 16.9.1
@nx/rspack: 16.8.2
@rspack/core: 0.4.3

### Details

I'm running rspack in an NX monorepo, when I try to build my app with @nx/rspack I get the following error which originates from node_modules/@nx/rspack/src/utils/create-compiler.js:14:42

```
TypeError: (0 , core_1.createCompiler) is not a function
    at /home/toch/WebstormProjects/instrument/node_modules/@nx/rspack/src/utils/create-compiler.js:14:42
    at Generator.next (<anonymous>)
    at fulfilled (/home/toch/WebstormProjects/instrument/node_modules/tslib/tslib.js:114:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduce Steps

1. Bundle application using @nx/rspack
2. The task returns TypeError: (0 , core_1.createCompiler) is not a function

**Comment by hardfist** [comment]
nx is not compatible with Rspack 0.4.x yet and should be fixed in https://github.com/nrwl/nx-labs/pull/352#pullrequestreview-1792991769
