### ISSUE TITLE
Unexpected tree shaking of antd.css when using newResolver in rspack@0.3.14

### ISSUE THREAD

**Issue by nanianlisao** [web-infra-dev/rspack#5090]
### System Info

"packageManager": "pnpm@8.6.2"
"@rspack/cli": "0.3.14"

### Details

When I enable `experiments.rspackFuture.newResolver` in rspack@0.3.14, the `antd.css` file gets removed during tree shaking, even though it is listed in the `sideEffects` array in `package.json`:

```json
"sideEffects": [
    "dist/*",
    "es/**/style/*",
    "lib/**/style/*",
    "*.less"
]
```

This issue does not occur when newResolver is disabled, and it also does not occur in rspack@0.4.0. However, I could not find any information about this issue being fixed in the changelog.

### Reproduce link

https://github.com/nanianlisao/rspack-bug-reproduction/tree/fix-newResolver

### Reproduce Steps

1. pnpm i
2.pnpm run build

**Comment by IWANABETHATGUY** [comment]
Since it is fixed in 0.4.0, and it is not a tree shaking bug according to the description
