### ISSUE TITLE
remove Rspack deps to reduce Rspack install size

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5097]
people care about install size and Rspack | Rsbuild install size is much bigger than Vite or other bundlers, even we can't make our install size the same as Vite, we should try our best to reduce install size
here are some deps we can remove

- [ ] browserslist(2.22Mb): no need when we remove builtins.presetEnv
- [x] compare-versions(59kb): no necessary, we only needs limited functionality, handwritten function is enough
- [ ] enhanced-resolve(260kb): no need when we support using native-loader
- [ ] graceful-fs(31kb): no need 
- [ ] noe-async(291kb): no need, handwritten async workflow
- [ ] webpack-sources(90kb): seems we only need type?
- [x] terminal-link(180kb):  no need, handwritten color 
- [ ] zod(613kb): very large, but we need this functionality, better alternative?
- [ ] zod-validation-error(643kb): may include zod size again? very large
- [x] events(82kb): can be handwritten

**Comment by xc2** [comment]
just tried `config/zod.ts` -> json schema -> ajv standalone code, resulting in ~500k mangled js code, whose size is very near zod.

```js
import { zodToJsonSchema } from "zod-to-json-schema";
import Ajv from "ajv";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const standaloneCode = require("ajv/dist/standalone");
const { rspackOptions } = await import("@rspack/core/zod"); // exports hacked

const jsonSchema = zodToJsonSchema(rspackOptions, "rspackOptions");

const ajv = new Ajv({ code: { source: true, esm: true, es5: false } });
const validate = ajv.compile(jsonSchema);
const moduleCode = standaloneCode(ajv, validate);

console.log(moduleCode.length);
```

**Comment by tatchi** [comment]
I've heard about https://github.com/fabian-hiller/valibot which apparently could be a smaller alternative to zod
