### ISSUE TITLE
Some CSS is missing after upgrading to Rspack v0.4.4

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5107]
### System Info

@rspack/core v0.4.4

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 229.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/39265_1702908249200/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/39265_1702908249200/bin/npm
    pnpm: 8.8.0 - ~/Library/Caches/fnm_multishells/39265_1702908249200/bin/pnpm
    bun: 0.1.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.0

### Details

I upgraded the rspack from v0.4.3 to v0.4.4 on the Vant website, then I noticed that some CSS were missing:

- v0.4.3:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/490161e8-c39a-43da-859c-5de8b03d12e9)

- v0.4.4

![image](https://github.com/web-infra-dev/rspack/assets/7237365/3be31539-9a94-4678-b861-d4cb97170456)

### Reproduce link

https://github.com/youzan/vant/tree/rspack_repro_1223

### Reproduce Steps

1. git clone git@github.com:youzan/vant.git --branch rspack_repro_1223
2. pnpm i
3. pnpm dev
4. open http://localhost:8080/mobile#/en-US/button
5. Inspect the `demo-button-row` element:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/c535dd99-65a0-49a5-b17b-ed5f94d7523e)

You can override `@rspack/core` in the root package.json to v0.4.3 to compare the build results.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/10e1c657-174e-4e49-8a7f-ba7a738d2412)

> I have tried to provide a minimal reproduction, but it is hard to reproduce this issue in the demo project.

**Comment by bvanjoi** [comment]
I've noticed that this issue can't be reproduced in the latest commit:

![image](https://github.com/web-infra-dev/rspack/assets/30187863/ea605235-d606-4ef1-a577-5df669322625)

**Comment by chenjiahan** [comment]
@bvanjoi because I have manually reverted the Rspack version...

https://github.com/youzan/vant/pull/12525

**Comment by bvanjoi** [comment]
What I meant was the latest commit of rspack: 0b9a919a2001877acd0cd54ac28b8f6eb72b37d9

**Comment by chenjiahan** [comment]
@bvanjoi haha, good news 👍

**Comment by bvanjoi** [comment]
Closing this as `﻿@rspack/core@0.4.5` functions as expected
