### ISSUE TITLE
react 热更新失效

### ISSUE THREAD

**Issue by noshower** [web-infra-dev/rspack#5111]
### System Info

<img width="542" alt="image" src="https://github.com/web-infra-dev/rspack/assets/15035094/f379bb6a-5996-464e-8d3f-86eb1aedfab4">

resolve.modules 配置为绝对路径后，会导致热更新失效。

### Details

例如，resolve.modules 配置为：['/xxx/app/node_modules']

期望代码更新后，控制台显示：
![image](https://github.com/web-infra-dev/rspack/assets/15035094/5a9a46c8-a238-45ac-a21e-652fc0dd7a50)

实际显示卡住了：
![image](https://github.com/web-infra-dev/rspack/assets/15035094/3721365b-bea2-4f91-96a7-5c0da177121c)

### Reproduce Steps

1. 在已经配置好 react refresh 的项目中，配置上 resolve.modules ，并且值为绝对路径
2. npm start
3. 更新 react 代码
4. 页面没有变化

**Comment by hardfist** [comment]
can you provide a repro or check the behavior of webpack when set resolve.modules

**Comment by noshower** [comment]
复现项目：
[rspack-react-typescript-template.zip](https://github.com/web-infra-dev/rspack/files/13791422/rspack-react-typescript-template.zip)

rspack/rspack.resolve.ts 这个文件中 配置了 modules，不过把 node_modules 配置成了绝对路径，就导致热更新失败。

**Comment by LingyuCoder** [comment]
这是一个 node_modules 下多个 webpack 的问题。

@rspack/dev-server 内使用了 webpack-dev-server, 在其内部会通过 require.resolve 获取 [webpack/hot/dev-server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L714) 的路径。webpack hot 内部通过相对路径获取了 [webpack/hot/emitter](https://github.com/webpack/webpack/blob/main/hot/dev-server.js#L64)。因此其固定指向了 @rspack/dev-server 内依赖的 webpack-dev-server 的 peerDependencies 的 webpack runtime。

而在 webpack-dev-server 内，则直接通过 [webpack/hot/emitter](https://github.com/webpack/webpack-dev-server/blob/master/client-src/utils/reloadApp.js#L1C8-L1C8) 引入，此时就会命中 resolve modules 的逻辑，从配置的 node_modules 绝对路径开始查找，而非查找 @rspack/dev-server 内部。因此当 node_modules 存在两个 webpack 版本时，即会引入一个新的 emitter/log。导致事件和日志丢失。

由于这些都是 webpack 和 webpack-dev-server 的代码 rspack 不好修改。因此可以通过 alias 实现，如修改 rspack.resolve.ts 文件：

```ts
/* eslint-disable import/no-extraneous-dependencies */
import { Configuration } from '@rspack/cli';
import { nodeModulesPath, srcDirPath, tsConfigPath } from './utils/paths';
import path from 'path';

export const resolveConfig: Configuration['resolve'] = {
  // node_modules 不能配置为绝对路径，否则会导致热更新失败
  modules: [srcDirPath, nodeModulesPath],
  // 将 webpack/hot 定位到 @rspack/dev-server 的依赖
  alias: {
    'webpack/hot': path.resolve(require.resolve('webpack', {
      paths: [require.resolve('@rspack/dev-server')]
    }), '../../hot'),
  },
  extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
  tsConfigPath,
};
```

**Comment by noshower** [comment]
> 这是一个 node_modules 下多个 webpack 的问题。
> 
> @rspack/dev-server 内使用了 webpack-dev-server, 在其内部会通过 require.resolve 获取 [webpack/hot/dev-server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L714) 的路径。webpack hot 内部通过相对路径获取了 [webpack/hot/emitter](https://github.com/webpack/webpack/blob/main/hot/dev-server.js#L64)。因此其固定指向了 @rspack/dev-server 内依赖的 webpack-dev-server 的 peerDependencies 的 webpack runtime。
> 
> 而在 webpack-dev-server 内，则直接通过 [webpack/hot/emitter](https://github.com/webpack/webpack-dev-server/blob/master/client-src/utils/reloadApp.js#L1C8-L1C8) 引入，此时就会命中 resolve modules 的逻辑，从配置的 node_modules 绝对路径开始查找，而非查找 @rspack/dev-server 内部。因此当 node_modules 存在两个 webpack 版本时，即会引入一个新的 emitter/log。导致事件和日志丢失。
> 
> 由于这些都是 webpack 和 webpack-dev-server 的代码 rspack 不好修改。因此可以通过 alias 实现，如修改 rspack.resolve.ts 文件：
> 
> ```ts
> /* eslint-disable import/no-extraneous-dependencies */
> import { Configuration } from '@rspack/cli';
> import { nodeModulesPath, srcDirPath, tsConfigPath } from './utils/paths';
> import path from 'path';
> 
> export const resolveConfig: Configuration['resolve'] = {
>   // node_modules 不能配置为绝对路径，否则会导致热更新失败
>   modules: [srcDirPath, nodeModulesPath],
>   // 将 webpack/hot 定位到 @rspack/dev-server 的依赖
>   alias: {
>     'webpack/hot': path.resolve(require.resolve('webpack', {
>       paths: [require.resolve('@rspack/dev-server')]
>     }), '../../hot'),
>   },
>   extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
>   tsConfigPath,
> };
> ```

涨知识了，3Q
