### ISSUE TITLE
Strict mode warning not working in entry module

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5120]
### System Info

Not related

### Details

In webpack, entry module is being translated into an `EntryDependency` and it will be using strict parsing as it's categorized as `Esm`. Rspack does not respect to this option. 

## Expected
1. Create a demo
2. Add `let let = let` to entry module
3. Run and there should be a parsing error.

## Actual
Rspack does not have a parsing error.

**Comment by LingyuCoder** [comment]
After testing, I found that the `sourceType` of EntryDepedency is `auto` in webpack, and it will try to parse as `module` first, and then parse as `script` if failed([code](https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js#L4505)).

Rspack use `swc_esma_parser::parse_file_as_program` to handle this, it may not throw any error. But acorn throws no matter in strict mode or not. If use `let` or `const` to declare variables, `let` can not be the binding name([code](https://github.com/acornjs/acorn/blob/6770c2ecbf8e01470f6c9a2f59c786f014045baf/acorn/src/lval.js#L261)). This means that `var let = let` is also legal in webpack.

According to this, I think this a bug of swc, and we could fix this by throw an error in our scanner
