### ISSUE TITLE
Performance degradation after turning on new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5123]
### System Info

@rspack/core: 0.4.5

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.69 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    npm: 9.3.1 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/npm
    pnpm: 8.8.0 - ~/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.6

### Details

I have tried to enable tree shaking in the Vant website, and found that the compile time increased from **3s to 23s**.

- newTreeshaing: false:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/bbe4849a-e3a4-40ef-8bd8-d2d02b5e1ad1)

- newTreeshaing: true:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/f198c26b-2b53-4910-adcb-ff6965d5dacf)

### Reproduce link

https://github.com/youzan/vant/tree/new_tree_shaking_1226

### Reproduce Steps

Enable new tree shaking:

1. git clone git@github.com:youzan/vant.git --branch new_tree_shaking_1226
2. pnpm i
3. pnpm dev

Disable new tree shaking:

1. search `newTreeshaking: true`, change the value to `false`.
2. pnpm i (to trigger rebuild)
3. pnpm dev

**Comment by IWANABETHATGUY** [comment]
I think we should compare the speed between production, since if you open `newTreeshaking` rspack will execute `flagDepenencyExports` and  rspack will do nothing if you disable it.

**Comment by IWANABETHATGUY** [comment]
Still it should not take so long.

**Comment by chenjiahan** [comment]
The performance of the production build is not affected, but I am quite curious as to why there is such a significant regression in the dev performance.

Maybe there is some performance issue with `flagDepenencyExports`?

**Comment by IWANABETHATGUY** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/17974631/795077b4-4c70-4782-a517-da81787ad6e2)
`exports_info_hash` almost cost 10s, why do we need to hash the whole `ExportsInfo` struct instead of a UniqueId?

**Comment by IWANABETHATGUY** [comment]
see https://github.com/web-infra-dev/rspack/pull/5125
