### ISSUE TITLE
Failed to upgrade to 0.4.5

### ISSUE THREAD

**Issue by xfsnowind** [web-infra-dev/rspack#5132]
### System Info

System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.101
    Chrome: 119.0.6045.105
    Edge: 119.0.2151.97
    Safari: 17.2.1

### Details

<img width="1058" alt="image" src="https://github.com/web-infra-dev/rspack/assets/2863328/4d197042-2495-4ff7-8821-ca040ab008d4">

### Reproduce Steps

1. set the version of `@rspack/core` to 0.4.5
2. Run the `pnpm i`

**Comment by hardfist** [comment]
it seems your network problem, it works for me

**Comment by xfsnowind** [comment]
weird, thanks for reply.

**Comment by xfsnowind** [comment]
Seems like I have to login to the `privjs.com` in the terminal to solve this authentication problem

**Comment by ScriptedAlchemy** [comment]
Remove privjs registry from your npmrc or remove @module federation from its scope.
