### ISSUE TITLE
Compiling time increases from 10s with version 0.3.14 to around 60s of version 0.4.x

### ISSUE THREAD

**Issue by xfsnowind** [web-infra-dev/rspack#5133]
### System Info

System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.91 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.101
    Chrome: 119.0.6045.105
    Edge: 119.0.2151.97
    Safari: 17.2.1

### Details

After I upgraded to version 0.4.x (even the latest version 0.4.4) from version 0.3.14, the compiling time increased from around 10s to 50-60s.
I tried with the debug option `RSPACK_PROFILE=ALL` within command, and found most of time was spent on this line:

```json
{"ph":"B","pid":1,"ts":16077628.584,"name":"plugin:optimize_chunks","cat":"rspack_core::plugin::plugin_driver","tid":1,".file":"crates/rspack_core/src/plugin/plugin_driver.rs",".line":529},
{"ph":"E","pid":1,"ts":83898296.75,"name":"plugin:optimize_chunks","cat":"rspack_core::plugin::plugin_driver","tid":1,".file":"crates/rspack_core/src/plugin/plugin_driver.rs",".line":529},
```

Time from 16s to 83s.

Here are my [rspack config file](https://gist.github.com/xfsnowind/a412a5b4434a821c3d3237252208e702)

### Reproduce Steps

1. upgrade to 0.4.4
2. compile

**Comment by hardfist** [comment]
can you share the profile file?

**Comment by xfsnowind** [comment]
Here is the trace.json
[Uploading trace.json…]()

**Comment by jerrykingxyz** [comment]
Optimize_chunks seems to use a lot of time, you can try disable optimization.mergeDuplicateChunks. cc @JSerFeng 
![image](https://github.com/web-infra-dev/rspack/assets/9291503/f84b9404-1cd5-487c-bc19-09bf23955de9)

**Comment by xfsnowind** [comment]
> Optimize_chunks seems to use a lot of time, you can try disable optimization.mergeDuplicateChunks. cc @JSerFeng !

@jerrykingxyz is there this `mergeDuplicateChunks` under `optimization`? I didn't find it in the doc.

**Comment by JSerFeng** [comment]
Sorry, the doc is missing, yes it's optimization.mergeDuplicateChunks

**Comment by xfsnowind** [comment]
> Optimize_chunks seems to use a lot of time, you can try disable optimization.mergeDuplicateChunks. cc @JSerFeng !

Thanks, it works, even though the time increases from around 10s to 16s, still better than 60s

**Comment by JSerFeng** [comment]
Btw you probably should enable splitChunks with chunk: 'all' been enabled in production build

**Comment by xfsnowind** [comment]
OK, thx for suggestion, currently we are using `initial`, will try `all`
