### ISSUE TITLE
No ESM export when compiled to ESM

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5138]
### System Info

@rspack/cli@0.4.5

### Details

Rspack should generate export { xxx} but generate var xxx
https://github.com/web-infra-dev/rspack-repro/blob/esm-output/rspack-dist/main.mjs#L68 
which webpack is right 
https://github.com/web-infra-dev/rspack-repro/blob/esm-output/webpack-dist/main.mjs#L89

### Reproduce link

https://github.com/web-infra-dev/rspack-repro/tree/esm-output

### Reproduce Steps

```
yarn install && yarn build
```

**Comment by LingyuCoder** [comment]
New tree shaking will resolve this issue, close as not planned

**Comment by alfaproject** [comment]
@LingyuCoder I'm using the new tree-shaking. This was reported under it

**Comment by LingyuCoder** [comment]
> @LingyuCoder I'm using the new tree-shaking. This was reported under it

@alfaproject Try this version `[0.4.5-canary-285c5f3-20231228011645](https://www.npmjs.com/package/@rspack/core/v/0.4.5-canary-285c5f3-20231228011645)`, it has been resolved but not published yet

**Comment by alfaproject** [comment]
I can confirm that version fixes the module output but now I'm getting this panic in another library:
```
Bundling apps/lambda-api/src/handlers/slack-server.ts
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  range end index 18446744073709551615 out of range for slice of length 0
Location: crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs:57

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<empty backtrace>
```

Not sure if it's related to your fix but it looks like something else. That is a regression tho

**Comment by LingyuCoder** [comment]
> I can confirm that version fixes the module output but now I'm getting this panic in another library:
> 
> ```
> Bundling apps/lambda-api/src/handlers/slack-server.ts
> Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
> Message:  range end index 18446744073709551615 out of range for slice of length 0
> Location: crates/rspack_plugin_javascript/src/dependency/commonjs/common_js_self_reference_dependency.rs:57
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> Run with RUST_BACKTRACE=full to include source snippets.
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> <empty backtrace>
> ```
> 
> Not sure if it's related to your fix but it looks like something else. That is a regression tho

This seems to be a bug caused by #5114. Could you provide a demo for reproduction?

**Comment by alfaproject** [comment]
Oh man, it's a really big monorepo. Not even sure where to start but I'll see if I can tomorrow

**Comment by LingyuCoder** [comment]
I cannot reproduce the specific scenario, but I think it is caused by the simultaneous occurrence of side effects and `module.exports()` in some cases, resulting in an empty names and causing an array access error.

The version [0.4.5-canary-d2f6abe-20231228172844](https://www.npmjs.com/package/@rspack/core/v/0.4.5-canary-d2f6abe-20231228172844) is compatible with array out-of-bounds situations, you can try it.

**Comment by alfaproject** [comment]
Alright, that sorted the other issue as well, thanks!
