### ISSUE TITLE
disable color when do profile

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5149]
current tracing log contains lots of color log which make the log.txt is hard to read and grep
![image](https://github.com/web-infra-dev/rspack/assets/8898718/71a550ad-79b9-4564-8007-5245fca4f8b0)

**Comment by bvanjoi** [comment]
How can I reproduce this log?

**Comment by bvanjoi** [comment]
ohhh I get it: `RSPACK_PROFILE=TRACE=layer=logger rspack build > log.log`
