### ISSUE TITLE
Resolver should be able to pass dependencies back to core

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5151]
### What problem does this feature solve?

This makes rspack watch to those dependencies that is missing.
Used for error recovery, etc.
Currently, resolve does not support this feature: https://github.com/web-infra-dev/rspack/blob/359b393cf273f51000c9d74049bc4392207d8d21/crates/rspack_core/src/resolver/resolver_impl.rs#L151.

### What does the proposed API of configuration look like?

Internal API change.

**Comment by Boshen** [comment]
I'll add `file_dependencies` and `missing_dependencies` this week.

I won't implement `context_dependencies`, it seems to be always empty https://github.com/search?q=repo%3Awebpack%2Fenhanced-resolve+contextDependencies&type=code

**Comment by Boshen** [comment]
PR: https://github.com/oxc-project/oxc_resolver/pull/50/files

**Comment by hardfist** [comment]
> I'll add `file_dependencies` and `missing_dependencies` this week.
> 
> I won't implement `context_dependencies`, it seems to be always empty https://github.com/search?q=repo%3Awebpack%2Fenhanced-resolve+contextDependencies&type=code

just like other dependencies, context_dependencies can be  passed by users and can be modified by resolver plugin, so it's not always empty

**Comment by Boshen** [comment]
We can add `context_dependencies` to `oxc_resolver` when requirements are met, it won't expose an API for it yet. 

Rspack can pass it around to other plugins though.
