### ISSUE TITLE
splitChunks.{cacheGroup}.chunks to also support "function (chunk) | RegExp"

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5188]
Add the function type or regexp for splitChunks.{cacheGroup}. chunks.

Just like below in webpack
https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks

This sure improves the perf in our case, because there are tons of 'async' chunks in our use-case and we do not want to go through each of the chunk. 

This is related to the previously completed request by @bvanjoi : https://github.com/web-infra-dev/rspack/issues/4376

Thanks!

**Comment by pushkargupta9807** [comment]
Bump ^

**Comment by pushkargupta9807** [comment]
bump

**Comment by LingyuCoder** [comment]
Supported by https://github.com/web-infra-dev/rspack/pull/5019
