### ISSUE TITLE
js file will be compiled when copied by copyRspackPlugin 

### ISSUE THREAD

**Issue by X-W-W** [web-infra-dev/rspack#5194]
### System Info

`
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 12.96 GB / 31.73 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.9 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rspack/cli: ^0.4.2 => 0.4.2
    @rspack/core: ^0.4.2 => 0.4.2
`

### Details

I use Rspack to replace webpack for bundling electron-main.
Then use `CopyRspackPlugin` instead of `webpack-copy-plugin`
js file copied by CopyRspackPlugin will be compiled 

用Rspack替代webpack进行electron主进程打包，使用`CopyRspackPlugin`插件替代`webpack-copy-plugin`，js文件会被解析编译

expected result:  just copy,not compile
current result: compile and throw error

期待结果：与webpack-copy-plugin一样仅复制文件
目前结果：js被编译并报错

### Reproduce Steps

```
patterns of copyRspackPlugin 
{
        from: 'a.js'
        to: path.join(__dirname, '/dist/b.js'),
        toType: 'file'
},
```
a.js
`
export const a = 1;
`

Error:
```
 export const a = 1;
  │ ^^^^^^ 'import', and 'export' cannot be used outside of module code
```

**Comment by JSerFeng** [comment]
Sorry for the delay, I tried but not able to reproduce, if you can provide the repro repo I will reopen this
![image](https://github.com/web-infra-dev/rspack/assets/57202839/0efd6c4e-e31d-4d74-88c5-cfa67fa1e06b)

**Comment by Clarkkkk** [comment]
@JSerFeng Hi, i've encountered the same problem. Here is the [reproduction](https://github.com/Clarkkkk/rspack-sourcemap-issue/tree/copy-plugin-issue). Run `pnpm i` and `node scripts/compile.js`, and you will see the error. Could you please check it again?

**Comment by LingyuCoder** [comment]
All assets with a ".js" suffix will trigger code compression, which has the same behavior with Webpack.

However, due to the default compression configuration of swc minimizer in Rspack not allowing "import" and "export", while terser does allow it, Rspack will throw an error while Webpack won't. You can try writing some new syntax in "example.js", which will also cause an error in Webpack and terser-webpack-plugin.

Therefore, it is recommended that you filter the assets of the copy plugin through ["exclude"](https://www.rspack.dev/config/plugins.html#swcjsminimizerrspackplugin).

**Comment by Clarkkkk** [comment]
> All assets with a ".js" suffix will trigger code compression, which has the same behavior with Webpack.
> 
> However, due to the default compression configuration of swc minimizer in Rspack not allowing "import" and "export", while terser does allow it, Rspack will throw an error while Webpack won't. You can try writing some new syntax in "example.js", which will also cause an error in Webpack and terser-webpack-plugin.
> 
> Therefore, it is recommended that you filter the assets of the copy plugin through ["exclude"](https://www.rspack.dev/config/plugins.html#swcjsminimizerrspackplugin).

For anyone who isn't clear how to do it, here is the example config:
```
optimization: {
    minimizer: [
        new rspack.SwcJsMinimizerRspackPlugin({
            exclude: [/.js$/]
        })
    ]
}
```
