### ISSUE TITLE
Should not parse require() in mjs+esm

### ISSUE THREAD

**Issue by LingyuCoder** [web-infra-dev/rspack#5197]
```js
// a.mjs
import a from './b.js';
var b = require('./c.js');
console.log(a, b);
```

```js
// webpack did not parse require('./c.js');
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _b_mjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./src/b.mjs");


var b = require('./c');

console.log(_b_mjs__WEBPACK_IMPORTED_MODULE_0__["default"], b);
```

```js
// rspack parsed require('./c.js')
__webpack_require__.r(__webpack_exports__);
/* harmony import */var _b_mjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./b.mjs */"./src/b.mjs");

var b = __webpack_require__(/*! ./c */"./src/c.js");
console.log(_b_mjs__WEBPACK_IMPORTED_MODULE_0__["default"], b);
```

**Comment by 9aoy** [comment]
<img width="955" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/74656568-6246-487a-b660-6637eb5ad488">

This problem also causes modern.js to fail  in rspack-ecosystem-ci.  It is OK in rspack 0.4.5, but it is fail in 0.4.5-canary.

https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7428373212/job/20215610121

**Comment by LingyuCoder** [comment]
> <img alt="image" width="955" src="https://private-user-images.githubusercontent.com/22373761/294699922-74656568-6246-487a-b660-6637eb5ad488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODI5MzQsIm5iZiI6MTcwNDY4MjYzNCwicGF0aCI6Ii8yMjM3Mzc2MS8yOTQ2OTk5MjItNzQ2NTY1NjgtNjI0Ni00ODdhLWI2NjAtNjYzN2ViNWFkNDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNDZhNjFiNjg0NGRiZjc2ZDFjZTU5YjVkZTlkMzhjNDQyZjYzNWQ5MDc5NmUzYTMxMmYwM2I2YTMzMWUyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zohkMvlo4PcGs8BNNssuVFI37KtfcVUaaBA3Dt2TiBE">
> This problem also causes modern.js to fail in rspack-ecosystem-ci. It is OK in rspack 0.4.5, but it is fail in 0.4.5-canary.
> 
> https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7428373212/job/20215610121

Caused by a bug, `require()` in try catch block should not be parsed with optional flag.

Fix https://github.com/web-infra-dev/rspack/pull/5262
