### ISSUE TITLE
SplitChunks Strategy Fails with rspackFuture.newTreeshaking Enabled

### ISSUE THREAD

**Issue by Moudicat** [web-infra-dev/rspack#5206]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 12.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 6.26.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Chrome Canary: 122.0.6223.0
    Safari: 16.3

### Details

**Problem Description:**
I have encountered an issue with the `rspackFuture.newTreeshaking` feature in my project. When `rspackFuture.newTreeshaking` is set to `true`, the `splitChunks` packaging strategy seems to malfunction.

**Expected Behavior:**
The splitChunks strategy should work consistently, splitting the vant components into a separate package, similar to how webpack behaves.

**Observed Behavior:**
When `rspackFuture.newTreeshaking` is enabled (true), the splitChunks strategy does not split the vant components as expected. Disabling `rspackFuture.newTreeshaking` (false) restores the normal splitting behavior.

<img width="313" alt="image" src="https://github.com/web-infra-dev/rspack/assets/6613538/610198d4-7857-4018-8335-b43c70e59200">

### Reproduce link

https://github.com/Moudicat/rspack-new-tree-shaking-split-chunk

### Reproduce Steps

1. In my project, I've integrated the vant component library.
2. I've configured `splitChunks` with the following strategy for packaging `vant`:

```
splitChunks: {
  chunks: 'all',
  minChunks: 1,
  minSize: 20000,
  cacheGroups: {
    vant: {
      name: 'lib-vant',
      test: createDependenciesRegExp('vant'),
      reuseExistingChunk: true,
      priority: 15,
    },
  }
}
```
3. With the above configuration, webpack correctly applies the splitChunks strategy.
4. However, when using rspack with `rspackFuture.newTreeshaking` set to true, the expected package splitting does not occur.

**Comment by JSerFeng** [comment]
Strange, I run `npm run build:rspack`, get the expected result 
![image](https://github.com/web-infra-dev/rspack/assets/57202839/ea3b6dc1-99f7-4fc1-8b4d-473eb2b67f6f)

**Comment by Moudicat** [comment]
> Strange, I run `npm run build:rspack`, get the expected result ![image](https://private-user-images.githubusercontent.com/57202839/293913909-ea3b6dc1-99f7-4fc1-8b4d-473eb2b67f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTIzNDAsIm5iZiI6MTcwNDI5MjA0MCwicGF0aCI6Ii81NzIwMjgzOS8yOTM5MTM5MDktZWEzYjZkYzEtOTlmNy00ZmMxLThiNGQtNDczZWIyYjY3ZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE0MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MjZlMzA5NTk3ZWE2YTM2OTI0OGVhNWY3ZWZhNTAzNTA4NmIzODM2M2UzYTQ1YzhkMzVlMzIxYzk0OGMxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z5gYPqb6-OyrvO-y5YiR8LhkzmWR0dnzeuvoq4lnIPQ)

To provide more context, I performed another build on a Windows machine, and unfortunately, I still encountered the same issue. Here are some additional details that might help in diagnosing the problem:

```
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 20.00 GB / 31.75 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: latest => 0.4.5
    @rspack/core: latest => 0.4.5

  Additionally, I would like to mention that I am using pnpm as my package manager for this project.
```

![image](https://github.com/web-infra-dev/rspack/assets/6613538/3d1cc231-101a-460b-94b3-217bbbd529f7)

I appreciate your assistance in resolving this issue. If there are any additional information I can provide to help diagnose the issue, please let me know. thanks

**Comment by JSerFeng** [comment]
Have you tried setting minSize to 0, not sure if that help.

**Comment by Moudicat** [comment]
Thank you for the suggestion to set minSize to 0. I gave that a try, but unfortunately, it didn't resolve the issue. 

I collaborated with several colleagues to test the build process on different machines.

1. Windows:    0/4 
2. MacOS:  2/4   
3. Linux: 1/1

Indeed, this is a strange issue. 

**MacOS Environments compare:**

<img width="941" alt="image" src="https://github.com/web-infra-dev/rspack/assets/6613538/2fadc3f6-76f8-423b-b14d-872391a960c1">

**Comment by JSerFeng** [comment]
Using my windows laptop, it works fine,
![image](https://github.com/web-infra-dev/rspack/assets/57202839/50634fc9-7ffe-4779-9174-ea06f5d1beed)

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.70 GB / 15.76 GB
  Binaries:
    Node: 16.18.0 - ~\AppData\Local\fnm_multishells\11352_1704351179827\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\11352_1704351179827\yarn.CMD
    npm: 8.19.2 - ~\AppData\Local\fnm_multishells\11352_1704351179827\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Local\fnm_multishells\11352_1704351179827\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rspack/cli: latest => 0.4.5
    @rspack/core: latest => 0.4.5

**Comment by IWANABETHATGUY** [comment]
Can you help with testing this version: 


0.5.3-canary-431379d-20240206044033

**Comment by Moudicat** [comment]
> Can you help with testing this version:
> 
> 0.5.3-canary-431379d-20240206044033

Sorry for the delay.
it's works!   both 0.5.3-canary-431379d-20240206044033 and 0.5.4 are functioning properly now.
Thank you for resolving the issue ✌️
