### ISSUE TITLE
Peer dependency issue with fork-ts-checker-webpack-plugin in rspack

### ISSUE THREAD

**Issue by sivanzheng** [web-infra-dev/rspack#5211]
### What problem does this feature solve?

I'm currently using fork-ts-checker-webpack-plugin in rspack. However, fork-ts-checker-webpack-plugin has a peerDependencies requirement for webpack, which means that my project needs to install an additional webpack. This issue seems similar to https://github.com/web-infra-dev/rspack/issues/4537. I would like to know if there are any plans to address this or if there are any alternative plugins that can be used as a replacement.

### What does the proposed API of configuration look like?

```json
{
  "peerDependencies": {
    "typescript": ">3.6.0",
    "webpack": "^5.11.0"
  },
  "peerDependenciesMeta": {
    "webpack": {
      "optional": true
    },
    "@rspack/core": {
      "optional": true
    }
  }
}
```

**Comment by hardfist** [comment]
yeah, you can make a pr to add @rspack/core as optional  peerDeps of fork-ts-checker-webpack-plugin like what we do for webpack-dev-server https://github.com/webpack/webpack-dev-server/pull/4778

**Comment by sivanzheng** [comment]
> yeah, you can make a pr to add @rspack/core as optional peerDeps of fork-ts-checker-webpack-plugin like what we do for webpack-dev-server [webpack/webpack-dev-server#4778](https://github.com/webpack/webpack-dev-server/pull/4778)

I followed the approach outlined at https://github.com/webpack/webpack-dev-server/pull/4778 to fork the `fork-ts-checker-webpack-plugin` to my local repository. I added the following to the `package.json` file:

```json
"peerDependenciesMeta": {
    "webpack": {
        "optional": true
    }
}
```

However, when building the project, I still encounter the error: `Error: Cannot find module 'webpack'`.

**Comment by sivanzheng** [comment]
@hardfist Are there any alternative approaches I could resolve this issue, please?

**Comment by hardfist** [comment]
@sivanzheng  can you provide a repro demo?

**Comment by sivanzheng** [comment]
[Archive.zip](https://github.com/web-infra-dev/rspack/files/14819400/Archive.zip)
![image](https://github.com/web-infra-dev/rspack/assets/23274663/8ecab860-2fbb-4657-b3e0-59c304224a4d)
@hardfist The compressed package is a demo provided for you. Running npm run build in the CI environment will reproduce the issue. The current package in the compressed file still uses fork-ts-checker-webpack-plugin. I have forked fork-ts-checker-webpack-plugin, made modifications as described above, and published it to a private repository. However, the issue persists.

**Comment by sivanzheng** [comment]
@hardfist Have you had the chance to try out this demo? I look forward to your response.

**Comment by hardfist** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/8898718/70c73152-809d-4e2d-b855-6742d3144436)
 not met any problem in your project

**Comment by sivanzheng** [comment]
@hardfist  After multiple attempts, the problem seems to be in my build process. Thank you for your response.
