### ISSUE TITLE
编译报错 thread 'tokio-runtime-worker' panicked

### ISSUE THREAD

**Issue by yreenchan** [web-infra-dev/rspack#5232]
### System Info

配置：
```
import { defineConfig } from '@rsbuild/core';
import { pluginVue2 } from '@rsbuild/plugin-vue2';
import { pluginVue2Jsx } from '@rsbuild/plugin-vue2-jsx';
import { pluginStylus } from '@rsbuild/plugin-stylus';


export default defineConfig({
  plugins: [pluginVue2(), pluginVue2Jsx(), pluginStylus()],
  source: {
    entry: {
      index: './client/index.js'
    },
    alias: {
      '@': './client',
    },
  },
  html: {
    template: './public/index.html',
  },
  module: {
    rules: [
      {
        test: /\.styl(us)?$/,
        loader: "stylus-loader",
        type: "css",
      },
    ],
  },
  include: [/\.vue\.js$/],
  tools: {
    bundlerChain(chain, utils) {
      chain.module.rule(utils.CHAIN_ID.RULE.STYLUS).test(/\.styl(us)?$/);
    },
  },
  server: {
    port: 8081,
  },
});

```

### Details

thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_codegen-0.146.9/src/lib.rs:358:17:
not implemented: codegen of `export default from 'foo';`
stack backtrace:
   0:        0x1116fc3bb - _napi_register_module_v1
   1:        0x1117212b3 - _napi_register_module_v1
   2:        0x1116f8e5e - _napi_register_module_v1
   3:        0x1116fc199 - _napi_register_module_v1
   4:        0x1116fd4e5 - _napi_register_module_v1
   5:        0x1116fd264 - _napi_register_module_v1
   6:        0x1116fd943 - _napi_register_module_v1
   7:        0x1116fd82c - _napi_register_module_v1
   8:        0x1116fc899 - _napi_register_module_v1
   9:        0x1116fd5b2 - _napi_register_module_v1
  10:        0x1118c3935 - _napi_register_module_v1
  11:        0x110686b59 - <unknown>
  12:        0x1106b2206 - <unknown>
  13:        0x11067f1cb - <unknown>
  14:        0x110756850 - <unknown>
  15:        0x110756168 - <unknown>
  16:        0x110757f1f - <unknown>
  17:        0x1108c57e8 - <unknown>
  18:        0x1108e234b - <unknown>
  19:        0x1108de723 - <unknown>
  20:        0x10fa8c396 - <unknown>
  21:        0x10f9b63c5 - <unknown>
  22:        0x10f9d751a - <unknown>
  23:        0x10fa844c6 - <unknown>
  24:        0x1116c5e18 - _napi_register_module_v1
  25:        0x1116c4685 - _napi_register_module_v1
  26:        0x10fa8229f - <unknown>
  27:        0x1116ba4c7 - _napi_register_module_v1
  28:        0x1116bb69d - _napi_register_module_v1
  29:        0x1117029a9 - _napi_register_module_v1
  30:     0x7ff81be59202 - __pthread_start
<e> [webpack-dev-middleware] [Error: error[internal]: not implemented: codegen of `export default from 'foo';`
<e> This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
<e>    0: _napi_register_module_v1
<e>    1: _napi_register_module_v1
<e>    2: <unknown>
<e>    3: <unknown>
<e>    4: <unknown>
<e>    5: <unknown>
<e>    6: _napi_register_module_v1
<e>    7: _napi_register_module_v1
<e>    8: <unknown>
<e>    9: _napi_register_module_v1
<e>   10: _napi_register_module_v1
<e>   11: _napi_register_module_v1
<e>   12: __pthread_start
<e> 
<e> 
<e> ] {
<e>   code: 'GenericFailure'
<e> }

### Reproduce Steps

如上图，运行后提示编译报错

**Comment by h-a-n-a** [comment]
这个问题已经修复了，可以用最近的 nightly，或者等下周升级到 0.5。
