### ISSUE TITLE
abnormal behavior of object assignment under vue2

### ISSUE THREAD

**Issue by lp0124** [web-infra-dev/rspack#5249]
### System Info

 System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 529.15 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/Library/Caches/fnm_multishells/70141_1704468490944/bin/node
    Yarn: 1.22.21 - ~/.npm_global/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/70141_1704468490944/bin/npm
    pnpm: 8.12.1 - ~/.npm_global/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.5.1
  npmPackages:
    @rspack/cli: latest => 0.4.5
    @rspack/core: latest => 0.4.5

### Details

<img width="385" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22974194/d0205331-a5cc-4084-9f5b-c9fe1f8ad820">
以上代码在 rspack 下打印的结果为  undefined

### Reproduce link

https://github.com/lp0124/rspack-vue2

### Reproduce Steps

1. 运行 dev:webpack ，浏览器打印 1 正常
2. 运行 dev:rspack，浏览器打印 undefined 异常

**Comment by hardfist** [comment]
it's fixed in latest main branch, try @rspack/core@nightly
