### ISSUE TITLE
Support `rspack.CopyRspackPlugin`'s `to` method accept function and string feature from `copy-webpack-plugin`

### ISSUE THREAD

**Issue by jainChetan81** [web-infra-dev/rspack#5250]
### What problem does this feature solve?

Right now I am trying to migrate my`react17`, `webpack`, `loadable`, `express`, `babel` etc application to rspack and for the most part I have been successful in doing so except for `copy-webpack-plugin` 
In my codebase I am using it like this
```
  new CopyWebpackPlugin({
      patterns: [
        {
          from: "src/components/**/assets/*.*",
          to({ absoluteFilename }: any) {
            return `../assets/images/components/${absoluteFilename.split("src/components/")[1]}`;
          },
        },
        {
          from: "src/pages/**/assets/*.*",
          to({ absoluteFilename }: any) {
            return `../assets/images/pages/${absoluteFilename.split("src/pages/")[1]}`;
          },
        },
        {
          from: "src/app/**/assets/*.*",
          to({ absoluteFilename }: any) {
            return `../assets/images/app/${absoluteFilename.split("src/app/")[1]}`;
          },
        },
        { from: "src/app/assets/favicon.ico", to: "../" },
        { from: "src/app/assets/manifest.json", to: "../" },
        { from: `src/newrelic${isDev ? "-dev" : ""}.js`, to: "../newrelic.js" },
        { from: `src/newrelic${isDev ? "-dev" : ""}.js`, to: "./newrelic.js" },
      ],
    })
```
    

- currently `CopyRspackPlugin` only takes string in the `to` method not function
- Ignoring `ts` issues and using `copy-webpack-plugin` with `rspack` instead of `webpack`, the build process gets stuck!

PS: is there something in the doc that I am missing?

### What does the proposed API of configuration look like?

```
new rspack.CopyRspackPlugin({
      patterns: [
        {
          from: "src/components/**/assets/*.*",
          to: ({ absoluteFilename }: any) =>
            `../assets/images/components/${absoluteFilename.split("src/components/")[1]}`,
        },]
})
```

**Comment by jainChetan81** [comment]
May i know if this is being worked upon or is in planned upcoming release..?
Thankyou

**Comment by JSerFeng** [comment]
yes it's in planned

**Comment by JSerFeng** [comment]
Sorry, I confused this issue with another issue. 
The main goal we create Rspack version of copy plugin is for performance, if function type option is supported, the performance benefits are gone, so this feature is not planned for now.

Notice that you said the build process gets stuck, can you try copy-webpack-plugin@6 or 5?

**Comment by jainChetan81** [comment]
Same, the process gets stuck with `copy-webpack-plugin@6.4.1` here is the repro with `webpack` and `rspack`
This works fine with webpack
here is the repro: [github here](https://github.com/jainChetan81/rspack-example)
webpack: `yarn dev`
rspack : `yarn dev-rs`

**Comment by jainChetan81** [comment]
I tried 6.0.0 as well, but that version doesn't support the functionality I am requesting here, any version that I use with this functionality(`6.4.0` onwards), the process is stuck somehow

**Comment by JSerFeng** [comment]
currently I'm busy at something else, I will check it immediately when I got time

**Comment by martijn-veenstra** [comment]
Do you mind sharing that solution @jainChetan81  ?

**Comment by jainChetan81** [comment]
The solution is very specific to our architecture , when we copy static files to public directory, we give it a name like `cat.jpg` becomes `src/comp/assets/cat.jpg` and push this to s3 from where gumlet servers our images.
We figured out a way to handle this from s3 itself.
@martijn-veenstra if you want this feature, you can reopen the issue
