### ISSUE TITLE
Legacy tree shaking will remove exports from ES modules

### ISSUE THREAD

**Issue by Asuka109** [web-infra-dev/rspack#5256]
### System Info

```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 135.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/1502_1704621740095/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/1502_1704621740095/bin/npm
  Browsers:
    Edge: 120.0.2210.121
    Safari: 17.0
  npmPackages:
    @rspack/binding: workspace:* => 0.4.5 
    @rspack/core: workspace:* => 0.4.5 
    @rspack/plugin-minify: workspace:^ => 0.4.5 
    @rspack/plugin-node-polyfill: workspace:^ => 0.4.5
```

### Details

A configuration file that can package esmodule artifacts will reproduce this problem when using legacy Treeshaking in development mode.

```js
module.exports = {
	mode: "development",
	output: {
		libraryTarget: "module",
		chunkFormat: "module",
	},
	experiments: {
		outputModule: true,
		rspackFuture: {
			newTreeshaking: false
		}
	},
};
```

<img width="1478" alt="image" src="https://github.com/web-infra-dev/rspack/assets/18379948/794dd82b-b021-4e09-9841-5995bd53db00">

### Reproduce link

https://github.com/web-infra-dev/rspack/pull/5255

### Reproduce Steps

I modified the `packages/rspack/tests/configCases/library/esmodule` case to reproduce it.

**Comment by IWANABETHATGUY** [comment]
legacy tree shaking will not shake exports in development mode, let me have a look.

**Comment by IWANABETHATGUY** [comment]
This is not a bug related to tree shaking, it works well when enabling `builtins.treeShaking` in development.
The main difference is the legacy implementation doesn't provide Exports info when disabling the `builtins.treeShaking`,  you could enable `builtins.treeShaking` or  enable `experiments.rspackFuture.newTreeshaking`
