### ISSUE TITLE
React does not work in --mode=production

### ISSUE THREAD

**Issue by cut0** [web-infra-dev/rspack#5258]
### System Info
```  
  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Max
    Memory: 64 GB
  Binaries:
    Node: v18.16.0
    pnpm: v8.2.0
  Browsers:
    Chrome: v120.0.6099.199
  npmPackages:
    @rspack/binding: workspace:* => 0.4.5 
    @rspack/core: workspace:* => 0.4.5 
```
### Details

After executing 
```bash
pnpm create rsbuild@latest
``` 

according to "[Using the Rspack CLI](https://www.rspack.dev/guide/quick-start#using-the-rspack-cli)", when specifying `production` in the [mode](https://www.rspack.dev/config/mode.html#mode) of `rspack.config.js`, or when specifying 
```bash
rspack -----mode=production serve
``` 
in the npm script and opening the web page, the following display appears.

![スクリーンショット 2024-01-08 午前10 17 57](https://github.com/web-infra-dev/rspack/assets/59341902/12bed494-1cb3-47b6-89a0-6351f02d65fa)

When 'development' is specified for mode, it displays normally as shown below.

![スクリーンショット 2024-01-08 午前10 17 37](https://github.com/web-infra-dev/rspack/assets/59341902/166e0160-b1f3-4e8c-9d9c-254341a99c31)

### Reproduce link

https://github.com/cut0/rspack-project

### Reproduce Steps

Please follow the steps below.

1. pnpm i
2. pnpm dev
3. Please open Chrome (the issue may also be reproducible in other browsers).

**Comment by hardfist** [comment]
https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/793d57c95ee64a1b9612a96066f091db08b226cb/lib/index.js#L48 react-refresh-webpack-plugin will skip inject refresh runtime when mode set to `production` which `@rspack/plugin-react-refresh` not align with now, cc @ahabhgk 
you can manually disable @rspack/plugin-react-refresh when mode set to production now, we will fix it soon
