### ISSUE TITLE
`rspack_error` should not have dependencies on `﻿rspack_*` and `﻿swc_*`

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#5263]
### System Info

nothing

### Details

`rspack_error` should have its own independent error logic and should not depend on any other crates:

https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_error/Cargo.toml#L14-L19

### Reproduce Steps

nothing

**Comment by Boshen** [comment]
It's weird `Diagnostic` stores identifiers

```
#[derive(Debug, Default, Clone)]
struct DiagnosticMeta {
  module_identifier: Option<Identifier>,
}
```

and creating an error from swc SourceFile

```
  pub fn from_source_file(
    source_file: &swc_core::common::SourceFile,
```

But I don't think there are nice ways to decouple these ...
