### ISSUE TITLE
Rspress HMR is broken after enabling new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5270]
### System Info

@rspack/core 0.5.0 canary (0.4.5-canary-be59383-20240105051840)

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/22567_1704199739974/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/22567_1704199739974/bin/npm
    pnpm: 8.14.0 - ~/Library/Caches/fnm_multishells/22567_1704199739974/bin/pnpm
    bun: 0.1.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.0

### Details

Rspress HMR is broken after enabling new tree shaking:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/1afe2be5-2815-4481-82ab-988e9951ebe8)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/new_tree_shaking_0108

### Reproduce Steps

1. git clone git@github.com:web-infra-dev/rsbuild.git --branch new_tree_shaking_0108
2. pnpm i
3. cd packages/document
4. pnpm dev
5. open http://localhost:8080/guide/basic/json-files in browser
6. open `packages/document/docs/en/guide/basic/json-files.md` in editor, type something.

**Comment by IWANABETHATGUY** [comment]
try this 
0.4.5-canary-058c885-20240108162457

**Comment by chenjiahan** [comment]
@IWANABETHATGUY I can still reproduce this issue in `@rspack/core` v0.5.1...

![image](https://github.com/web-infra-dev/rspack/assets/7237365/69e52155-5074-4d90-af70-207d6f7d9c46)


branch: https://github.com/web-infra-dev/rsbuild/tree/new_tree_shaking_01172

**Comment by chenjiahan** [comment]
Can not reproduce this issue in Rspack 0.5.3, I will close it.

**Comment by IWANABETHATGUY** [comment]
@jerrykingxyz  can you have a look?

**Comment by IWANABETHATGUY** [comment]
Can you try the latest **0.5.6**?

**Comment by chenjiahan** [comment]
Fixed 👍
