### ISSUE TITLE
Rspack build product contains es6 syntax class

### ISSUE THREAD

**Issue by waleiwalei** [web-infra-dev/rspack#5274]
### System Info

node: v16.18.0
npm: v8.19.2

### Details

when exec [npm run build], i found es6 syntex in dist directory.

### Reproduce link

https://github.com/waleiwalei/rspack-project

### Reproduce Steps

1. npm run build
2. npm run check:ES6
3. Then there is an error about a class in dist
4. delete exclude: /node_modules/ in rspack.config.js
5. npm run build && npm run check:ES6
6. there is no class in dist

**Comment by LingyuCoder** [comment]
I think this is as expected, its behavior aligns with webpack. Modules will first pass the test of "include" rules, and then go through the test of "exclude" rules. Only when both tests pass will the loader used to process this module.

If you want to exclude node_modules except some specfic packages, you can use rule like this:
```js
{
    test: /\.(js|ts)$/,
    exclude: {
        and: [/node_modules/],
        not: [/src/, /node_modules\/dom7/, /node_modules\/swiper/]
    },
    //...
}
```

**Comment by waleiwalei** [comment]
I Got it . exclude can only be the subset of include ~
