### ISSUE TITLE
rspack vs webpack handling of circular dependencies at module level

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5293]
### System Info

N/A

### Details

Hello All,

I am running into an issue with rspack with one of the components which is unused in serve/ development mode. 

We have a components file which exports a bunch of components. In the app we import 2 components from this ./components.tsx .  When the app is started and served in devlopment mode, I run into an error  below :

Uncaught ReferenceError: Cannot access 'LightWeightLobbyRosterItem' before initialization

This component is not even being used by the app. Upon looking at the stack trace, it looks like a circular dependency in one of the un-used components in ./components.tsx  which I am not sure why is getting initialized. The app used to work in serve mode just fine using rspack prior to the above change of adding ./components to the app. 

Any idea what could be wrong here? 
With webpack it works fine so I was wondering is circular dependencies at module level  being handled differently in webpack than rspack ? If so what is the difference and if there are any workarounds with rspack .

I wanted to create and share a reproducible example, but the codebase is too complex and not easy to create a repro.

This is a known issue for @hardfist and he is investigating the same here :
https://twitter.com/hardfist_1/status/1742597089887125591

wanted to open this bug for tracking purposes. 

### Reproduce Steps

N/A

**Comment by IWANABETHATGUY** [comment]
I don't see any difference when rspack enable `rspack.experiments.rspackFuture.newTreeshaking` , here is the repo link: 

https://github.com/IWANABETHATGUY/circular-dependeny-cases

**Comment by pushkargupta9807** [comment]
@hardfist I believe you were able to reproduce it at your end, right?

**Comment by IWANABETHATGUY** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/17974631/599a8cdc-6b78-4f62-978d-86815efe0847)
You can see the results are the same as webpack.

**Comment by hardfist** [comment]
@pushkargupta9807 do you use newTreeshaking? it maybe caused the old treeshaking not works like webpack

**Comment by IWANABETHATGUY** [comment]
https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking
