### ISSUE TITLE
请问支持在 uni-app小程序项目中接入rspack吗? 能否有相关示例?

### ISSUE THREAD

**Issue by MQL9011** [web-infra-dev/rspack#5306]
### What problem does this feature solve?

请问支持在 uni-app小程序项目中接入rspack吗? 能否有相关示例?

### What does the proposed API of configuration look like?

请问支持在 uni-app小程序项目中接入rspack吗? 能否有相关示例?

**Comment by hardfist** [comment]
目前没有

**Comment by luoriwusheng-xia** [comment]
uni-app 官方能接，才有戏吧。 如果是 cli的形式，可能存在不确定性的问题， 毕竟 uni-app也是比较庞大的另一个分支。
rspack 也不能100% 干预其他产品的规划

**Comment by hardfist** [comment]
> uni-app 官方能接，才有戏吧。 如果是 cli的形式，可能存在不确定性的问题， 毕竟 uni-app也是比较庞大的另一个分支。
> rspack 也不能100% 干预其他产品的规划

是这样的，更多的方式是用户给 uni-app官方反馈意愿，看官方的态度，官方愿意做了，我们则会考虑配合官方进行支持
