### ISSUE TITLE
Improve bundler size after tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5317]
### What problem does this feature solve?

I noticed that in some cases, the bundle size of Rspack (v0.5.0) / Rsbuild is still larger than that of Vite / rollup after using new tree shaking.

I wonder if this is a bug or if the tree shaking strategy is different.

### Test case

This is my test case:

https://github.com/chenjiahan/rsbuild-repro-tree-shaking-size

---

- source code:

```js
import { createApp } from "vue";
import { Button, Swipe } from "vant";

console.log(createApp, Button, Swipe);
```

---

- npx rsbuild build with new tree shaking **(91.9 kB)**:

```text
➜  npx rsbuild build 

  Rsbuild v0.3.2

ready   Client compiled in 0.32 s
info    Production file sizes:

  File                                Size       Gzipped    
  dist/index.html                     0.26 kB    0.20 kB
  dist/static/js/index.1a4d2b1d.js    91.9 kB    33.9 kB

  Total size:  92.1 kB
  Gzipped size:  34.1 kB
```

---

- npx rsbuild build without new tree shaking  **(361.4 kB)**:

```text
➜  npx rsbuild build

ready   Client compiled in 0.34 s
info    Production file sizes:

  File                                Size        Gzipped    
  dist/index.html                     0.26 kB     0.20 kB
  dist/static/js/index.e227bbd7.js    361.4 kB    108.4 kB

  Total size:  361.7 kB
  Gzipped size:  108.6 kB
```

---

- npx vite build **(67.83 kB)**:

```text
➜  npx vite build   
vite v5.0.11 building for production...
✓ 277 modules transformed.
dist/index.html                 0.30 kB │ gzip:  0.23 kB
dist/assets/index-tluu1stB.js  67.83 kB │ gzip: 27.65 kB
✓ built in 660ms
```

**Comment by IWANABETHATGUY** [comment]
Can you try webpack? It would not be considered as a bug, if our bundle size isn't bigger than webpack (at least for current stage).

**Comment by chenjiahan** [comment]
Sure, I will add webpack soon 😄

**Comment by chenjiahan** [comment]
I have updated the demo and added webpack.

The bundle size of webpack is `81.0 kB`, smaller than Rspack, but still larger than Vite/Rollup. Maybe we can align with webpack first.

```text
> rsbuild build --config ./rsbuild.config.webpack.mjs

  Rsbuild v0.3.2

ready   Client compiled in 0.76 s
info    Production file sizes:

  File                                Size       Gzipped    
  dist/index.html                     0.32 kB    0.22 kB
  dist/static/js/index.81390de4.js    1.4 kB     0.77 kB
  dist/static/js/3.45f7ec6d.js        81.0 kB    30.6 kB

  Total size:  82.8 kB
  Gzipped size:  31.5 kB
```


- Rspack: 91.9 kB
- webpack: 81.0 kB
- rollup: 67.83 kB

**Comment by IWANABETHATGUY** [comment]
**rspack patch** 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/3ba0d6e6-15eb-4372-89a1-1348ad1a5eb3)
**webpack without concatenate module**
![image](https://github.com/web-infra-dev/rspack/assets/17974631/a41fe7e0-ed4a-4c66-ad6f-0325cd140166)

**Comment by IWANABETHATGUY** [comment]
The rest size diff caused by `concatenateModule`

**Comment by IWANABETHATGUY** [comment]
after enable `concatenateModules` the size reduced to 
![image](https://github.com/web-infra-dev/rspack/assets/17974631/4b49bb08-a8e9-45a3-9e99-0ca4e654abe8)
