### ISSUE TITLE
HMR panic in Module Federation

### ISSUE THREAD

**Issue by Sunny-117** [web-infra-dev/rspack#5321]
### System Info

mac

### Details

![image](https://github.com/web-infra-dev/rspack/assets/73089592/a1a9147f-8f23-4748-a95d-c3050eb4d7a4)

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Failed to convert module to JsModule: Error { status: GenericFailure, reason: "Failed to convert module to JsModule", maybe_raw: 0x0 }
Location: crates/node_binding/src/plugins/mod.rs:758

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<empty backtrace>
 ELIFECYCLE  Command failed with exit code 1.

### Reproduce Steps

pnpm dev
更改模块联邦子应用
改子应用panic报错退出

**Comment by Boshen** [comment]
Can you provide a repro? 

@ahabhgk Maybe we need a MF repro to go along with https://github.com/web-infra-dev/rspack-repro

cc @ScriptedAlchemy

**Comment by ahabhgk** [comment]
One of the js plugin panics, not related with MF. Can you provide a reproduction? Or find the panic plugin by turning it off one by one

**Comment by h-a-n-a** [comment]
It could've been fixed in https://github.com/web-infra-dev/rspack/issues/5054. Haven't released it yet.

**Comment by ahabhgk** [comment]
Feel free to reopen if the problem still exists in v0.5.2

**Comment by sunft1996** [comment]
> Feel free to reopen if the problem still exists in v0.5.2

针对panic这个问题，0.4的版本可以发个patch版本吗，目前用的0.4.2（偶尔会遇到这个问题），已经接了好几个项目了，如果升级0.5又有新的成本
