### ISSUE TITLE
`asyncWebAssembly` not work

### ISSUE THREAD

**Issue by magic-akari** [web-infra-dev/rspack#5328]
### System Info

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 442.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/81844_1705300125272/bin/node
    Yarn: 3.3.1 - ~/Library/Caches/fnm_multishells/81844_1705300125272/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/81844_1705300125272/bin/npm
    pnpm: 8.14.0 - ~/Library/Caches/fnm_multishells/81844_1705300125272/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @rspack/cli: ^0.5.0 => 0.5.0 

### Details

```error
stylua_lib_bg.js:671 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'buffer')
    at stylua_lib_bg.js:671:1
    at __webpack_require__.a (index.js:4:1)
    at ./node_modules/.pnpm/@johnnymorganz+stylua@0.19.1/node_modules/@johnnymorganz/stylua/stylua.bundler/stylua_lib_bg.js (stylua_lib.js:2:1)
    at __webpack_require__ (index.js:4:1)
    at fn (index.js:4:1)
    at index.js:4:1
    at __webpack_require__.a (index.js:4:1)
    at ./node_modules/.pnpm/@johnnymorganz+stylua@0.19.1/node_modules/@johnnymorganz/stylua/stylua.bundler/stylua_lib_bg.wasm (index.js:4:1)
    at __webpack_require__ (index.js:4:1)
    at fn (index.js:4:1)
```

Rspack:
<img width="756" alt="image" src="https://github.com/web-infra-dev/rspack/assets/7829098/df5f89d9-8594-4841-b143-4502351378ca">

Webpack:
<img width="820" alt="image" src="https://github.com/web-infra-dev/rspack/assets/7829098/c0a77627-736e-4f9c-86b3-49309fa09d55">

### Reproduce link

https://github.com/magic-akari/rspack_wasm_debug

### Reproduce Steps

```bash
pnpm i # install dependencies
pnpm webpack:dev 
# open the browser and check the console
# you will see the result `local a = 1` and everything is ok

# press ctrl+c to stop the dev server

pnpm rspack:dev
# open the browser and check the console
# you will see the error:
# TypeError: Cannot read properties of undefined (reading 'buffer')
```

**Comment by IWANABETHATGUY** [comment]
try: 
https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking

**Comment by magic-akari** [comment]
> try: https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking

it works like a charm.

**Comment by magic-akari** [comment]
However, the HMR is broken in new treeshaking.

**Comment by IWANABETHATGUY** [comment]
https://github.com/web-infra-dev/rspack/pull/5053, I fixed it before, I will take a look ASAP

**Comment by IWANABETHATGUY** [comment]
Do you use the same reproduced repo?

**Comment by magic-akari** [comment]
No. it's about Vue HMR. I think it's not related this issue ant it's OK to close it.
