### ISSUE TITLE
[Tracking]: ES Modules may not assign module.exports or exports.*, Use ESM export syntax

### ISSUE THREAD

**Issue by a599155162** [web-infra-dev/rspack#5334]
### What subject does this issue tracking?

示例地址：
https://codesandbox.io/p/devbox/rspack-test-4v5wwj?file=%2Findex.js%3A46%2C29

加入 polyfill core-js 运行后，浏览器报错：
`Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ../../../../node_modules/.pnpm/core-js@3.33.1/node_modules/core-js/internals/array-buffer-view-core.js`

**Comment by sunft1996** [comment]
同，esm项目中如果导入了commonjs模块，会报这个错误

**Comment by a599155162** [comment]
> 同，esm项目中如果导入了commonjs模块，会报这个错误

添加: isModule: "unknown" ， 可以解决这个模块兼容问题

**Comment by sunft1996** [comment]
> > 同，esm项目中如果导入了commonjs模块，会报这个错误
> 
> 添加: isModule: "unknown" ， 可以解决这个模块兼容问题

可以解决，十分感谢~
