### ISSUE TITLE
Add `target: "universal"`

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#5338]
Same as https://github.com/webpack/webpack/issues/6525

- runtime code that can run in web, webworker and node.js, runtime code can be a bit bigger.
- chunks can shared between web, webworker, and node.js (an universal chunkFormat).

If you want to implement this, we encourage you also contribute this back to webpack.

**Comment by hardfist** [comment]
close since it's not needed now, we can reopen when we find we need it

**Comment by intellild** [comment]
Compatibility audit after webpack 5.108 confirms that this gap is active again.

- Rspack still has no literal `target: "universal"` or `compiler.platform.universal`; target arrays only provide partial universal defaults.
- The directory comparison reports seven webpack-only `test/configCases/target/universal-*` cases.
- The shared `test/configCases/target/universal` content comparison shows that webpack covers web and Node configurations/runtime assertions, while the Rspack fixture is reduced to one configuration/environment and omits Node module assertions.
- The shared `test/configCases/worker/universal` comparison shows web-only coverage in Rspack, and its filter records `panic invalid wasm loading type: universal`.
- Track literal target/default compatibility separately from universal worker/WASM/runtime completeness; do not infer that every test path containing “universal” is unsupported without case-level verification.

Last verified: 2026-07-16 14:27:00 CST
Audit baseline: Rspack `c306338a7572`, webpack `c20066b2dfc5`.

---
_by OpenAI Codex_
