### ISSUE TITLE
realContentHash replace content in user code

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#5339]
Also see https://github.com/webpack/webpack/issues/14058

`optimization.realContentHash` will use RegExp to replace the contenthash in generated code, it's possible to replace the user code which contains the same content as contenthash. Although the longer the contenthash length, the less likely it is to occur, it is still easy to appear when the contenthash length is very short.

If you want to implement this, we encourage you also contribute this back to webpack.

**Comment by hardfist** [comment]
bump

**Comment by chenjiahan** [comment]
I will close this and let's track the progress here: https://github.com/web-infra-dev/rspack/issues/8474
