### ISSUE TITLE
Panic occurred at runtime.

### ISSUE THREAD

**Issue by knames** [web-infra-dev/rspack#5352]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H        
    Memory: 42.67 GB / 63.68 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 120.0.6099.224
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.133)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: ^0.5.1 => 0.5.1
    @rspack/core: ^0.5.1 => 0.5.1
    @rspack/plugin-react-refresh: ^0.5.1 => 0.5.1

### Details

When running a simple template project using rspack, I get the below issues. It's only on a windows machine, my mac works perfectly fine.

●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (11%) building scheduler
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  internal error: entered unreachable code
Location: C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\oxc_resolver-1.2.0\src\path.rs:69

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.      
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: napi_register_module_v1
    at <unknown source file>
 6: napi_register_module_v1
    at <unknown source file>
 7: napi_register_module_v1
    at <unknown source file>
 8: napi_register_module_v1
    at <unknown source file>
 9: napi_register_module_v1
    at <unknown source file>
10: napi_register_module_v1
    at <unknown source file>
11: napi_register_module_v1
    at <unknown source file>
12: napi_register_module_v1
    at <unknown source file>
13: BaseThreadInitThunk
    at <unknown source file>
14: RtlUserThreadStart
    at <unknown source file>
 ELIFECYCLE  Command failed with exit code 3221226505.
\

### Reproduce Steps

I'll have to make a simpler project without a bunch of internal company libraries. Will be back with a link for that..

**Comment by pushkargupta9807** [comment]
I am running into a similar issue with the 0.5.2. Works fine on Mac OS but runs into the Panic with windows.
[/](https://github.com/web-infra-dev/rspack/issues/5592)
 
 @knames how did you get around this issue on windows?

**Comment by knames** [comment]
> I am running into a similar issue with the 0.5.2. Works fine on Mac OS but runs into the Panic with windows.
> 
> #5592 @knames how did you get around this issue on windows?

Might be hitting the limit on windows path length (256 characters unless you enable long paths), especially when using pnpm (crazy long nesting, they have a ticket to change it to hashes after 30 chars but who knows when that’s out). 

Try getting as close to c:/ as possible, don’t use long names for folders. That’s what it was for my coworkers at least.

**Comment by pushkargupta9807** [comment]
well I tried by enabling the long paths in the registry - still running into that same panic. And I am using yarn.

**Comment by hardfist** [comment]
> well I tried by enabling the long paths in the registry - still running into that same panic. And I am using yarn.

what is your rspack version and try set chunkIds to deterministic

**Comment by pushkargupta9807** [comment]
> > well I tried by enabling the long paths in the registry - still running into that same panic. And I am using yarn.
> 
> what is your rspack version and try set chunkIds to deterministic

I am on rspack v 0.5.3 and I tried setting the chunkIds to "deterministic", but  ran into the same error below:

Message:  internal error: entered unreachable code
Location: C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\oxc_resolver-1.2.2\src\path.rs:69

**Comment by dxhsmwqcwelllee** [comment]
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Module(/Users/doorgod/Desktop/www/AbcPc/node_modules/sax/lib/sax.js) should be added before using
Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:75

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.

Accidental phenomena, why?
