### ISSUE TITLE
Plugin type incompatible with webpack plugin

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#5360]
A workaround worth exploring (for the end user) is to use:

`new HtmlWebpackPlugin() as unknown as RspackPluginInstance`

but this feels a bit like a hack to me?

_Originally posted by @wojtekmaj in https://github.com/web-infra-dev/rspack/issues/5005#issuecomment-1872075482_

**Comment by tjx666** [comment]
```typescript
type RspackPluginInstance  = ReturnType<typeof definePlugin>
```

**Comment by wojtekmaj** [comment]
Bump

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/rspack/pull/7455
