### ISSUE TITLE
incorporate ﻿`acro-pro` into the benchmark

### ISSUE THREAD

**Issue by bvanjoi** [web-infra-dev/rspack#5368]
### What problem does this feature solve?

`acro-pro` can yield more reliable data.

### What does the proposed API of configuration look like?

nothing

**Comment by SyMind** [comment]
@bvanjoi I'll take care of this.

**Comment by SyMind** [comment]
It's ready.

![image](https://github.com/web-infra-dev/rspack/assets/19852293/a1509e80-229e-4662-be6a-59190778fe28)
