### ISSUE TITLE
为了使用rspackExperiments.import，导致vue文件Module build failed

### ISSUE THREAD

**Issue by yizixu** [web-infra-dev/rspack#5372]
### System Info

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 24.56 GB / 47.94 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.1566

### Details

```javascript
const rspack = require('@rspack/core')
const { VueLoaderPlugin } = require('vue-loader')
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const { name: packageName } = require('./package.json')
const path = require('path')
const chalk = require('chalk')
const isProd = /production/i.test(process.env.NODE_ENV)

/** @type {import('@rspack/cli').Configuration} */
const port = 9527
const config = {
  context: __dirname,
  entry: {
    main: './src/main.js'
  },
  output: isProd
    ? {
        filename: 'static/js/[name].[contenthash:8].js',
        cssFilename: 'static/css/[name].[contenthash:8].css',
        assetModuleFilename: 'static/asset/[name].[hash][ext][query]',
        publicPath: process.env.VUE_APP_PUBLIC_PATH,
        clean: true
      }
    : {},
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src')
    },
    extensions: ['.js', '.vue', '.json', '.css']
  },
  devServer: {
    historyApiFallback: true,
    port,
    open: true
  },
  devtool: false,
  plugins: [
    new rspack.DefinePlugin({
      BASE_URL: process.env.VUE_APP_PUBLIC_PATH
    }),
    new rspack.ProgressPlugin({
      prefix: chalk.green(`端口${port}，接口环境${process.env.VUE_APP_STATIC_API}，${isProd ? '生产' : '开发'}环境${process.env.NODE_ENV} \n`)
    }),
    new NodePolyfillPlugin(),
    new VueLoaderPlugin(),
    new HtmlWebpackPlugin({
      template: './index.html',
      title: packageName
    }),
    new rspack.CopyRspackPlugin({
      patterns: [
        {
          from: './public'
        }
      ]
    })
  ],
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: {
              experimentalInlineMatchResource: true
            }
          }
        ]
      },
      {
        test: /\.css$/,
        // use: ['vue-style-loader', 'css-loader'],
        type: 'css'
      },
      {
        test: /\.s(a|c)ss$/,
        use: [
          // 'vue-style-loader',
          // 'css-loader',
          'sass-loader',
          {
            loader: 'sass-resources-loader',
            options: {
              resources: [
                path.resolve(__dirname, 'src/unilumin-style/vars.scss'),
                path.resolve(__dirname, 'src/unilumin-style/mixin.scss')
              ]
            }
          }
        ],
        type: 'css'
      },
      {
        test: /\.(png|jpe?g|gif|webp|svg|woff|woff2|eot|ttf)$/i,
        type: 'asset/resource'
      },
      {
        test: /^BUILD_ID$/,
        type: 'asset/source'
      },
      {
        use: [
          {
            loader: 'builtin:swc-loader',
            options: {
              rspackExperiments: {
                import: [
                  {
                    libraryName: 'element-ui',
                    styleLibraryDirectory: 'lib/theme-chalk'
                  },
                  {
                    libraryName: 'unilumin-ui',
                    styleLibraryDirectory: 'lib/style'
                  }
                ]
              }
            }
          }
        ]
      }
    ]
  }
  // experiments: {
  //   css: false // 此时需要关闭 `experiments.css` 以适配 `vue-loader` 内部处理逻辑
  // }
}
module.exports = config
```
## 执行`rspack serve`后，在去掉builtin:swc-loader的情况下，能启动成功，但是这样就没有引入第三方库了。加上builtin:swc-loader后，就报错了，报错如下
ERROR in ./src/views/System/user-list/index.vue?vue&type=template&id=c9440e86&scoped=true (./src/views/System/user-list/index.vue?vue&type=template&id=c9440e86&scoped=true!=!../../../../node_modules/.pnpm/vue-loader@15.11.1_css-loader@6.9.0_lodash@4.17.21_vue-template-compiler@2.6.14_webpack@5.89.0/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!builtin:swc-loader??clonedRuleSet-5.use[0]!../../../../node_modules/.pnpm/vue-loader@15.11.1_css-loader@6.9.0_lodash@4.17.21_vue-template-compiler@2.6.14_webpack@5.89.0/node_modules/vue-loader/lib/index.js??vue-loader-options!./src/views/System/user-list/index.vue?vue&type=template&id=c9440e86&scoped=true)
ModuleBuildError

  × Module build failed:
  ╰─▶   × Error:
        │   × Expression expected
        │    ╭─[E:\Project\3.0\unilumin-cas\src\views\System\user-list\index.vue:1:1]
        │  1 │
        │  2 │ <div class="app-container page-user">
        │    · ─
        │  3 │   <vxe-toolbar
        │  4 │     ref="ToolbarRef"
        │  5 │     :loading="loading"
        │    ╰────
        │
        │   × Expected ';', '}' or <eof>
        │    ╭─[E:\Project\3.0\unilumin-cas\src\views\System\user-list\index.vue:1:1]
        │  1 │
        │  2 │ <div class="app-container page-user">
        │    · ──┬─ ─────
        │    ·   ╰── This is the expression part of an expression statement
        │  3 │   <vxe-toolbar
        │  4 │     ref="ToolbarRef"
        │  5 │     :loading="loading"
        │    ╰────
        │
        │

  help: File was processed with this loader: 'E:\Project\3.0\unilumin-cas\node_modules\.pnpm\vue-loader@15.11.1_css-loader@6.9.0_lodash@4.17.21_vue-template-
        compiler@2.6.14_webpack@5.89.0\node_modules\vue-loader\lib\loaders\templateLoader.js??vue-loader-options$builtin:swc-loader??clonedRuleSet-5.use[0]$E:\Project\3.0\unilumin-
        cas\node_modules\.pnpm\vue-loader@15.11.1_css-loader@6.9.0_lodash@4.17.21_vue-template-compiler@2.6.14_webpack@5.89.0\node_modules\vue-loader\lib\index.js??vue-loader-options'

### Reproduce Steps

如上面详情描述

**Comment by yizixu** [comment]
"@rspack/cli": "^0.5.1"

**Comment by yizixu** [comment]
谢谢你的回复，这是地址[https://github.com/yizixu/rspack-vue2-elementui](可复现的仓库)，谢谢

**Comment by yizixu** [comment]
明明有回复啊

**Comment by xc2** [comment]
@yizixu 请按照下面的例子添加 `test` 和 `resourceQuery`

```js
      {
        test: /\.js$/,
        resourceQuery: (a) => !a || !/type=template/.test(a),
        use: [
          {
            loader: 'builtin:swc-loader',
            options: {
              rspackExperiments: {
                import: [
                  {
                    libraryName: 'element-ui',
                    styleLibraryDirectory: 'lib/theme-chalk'
                  },
                  {
                    libraryName: 'unilumin-ui',
                    styleLibraryDirectory: 'lib/style'
                  }
                ]
              }
            }
          }
        ]
      }
```

**Comment by yizixu** [comment]
@xc2 好了，非常感谢，但是这种写法真的很少用到，文档中也没提到多少，希望官方团队在1.0稳定版做得更好，祝rspack越来越好

**Comment by xc2** [comment]
谢谢 @yizixu 

resourceQuery 这句是临时避免 vue 2.6 + vue-loader 15 的一个特定问题，还得看一下问题的原因是什么。

**Comment by Camusama** [comment]
这是个值得纪念的时刻， debug 了 14个小时终于找到这个  resourceQuery: (a) => !a || !/type=template/.test(a) 了
