### ISSUE TITLE
[Feature Request]: Dynamic entry

### ISSUE THREAD

**Issue by OrangeXC** [web-infra-dev/rspack#5377]
### What problem does this feature solve?

We plan to migrate from webpack. The existing function is to implement access-time building through dynamic entry (that is, the build task is triggered when the user accesses the local URL). The entry configuration code is as follows:

```js
// The file record entry changes
const entryDynamicFile = `${process.env.BUILD_ENTRY_DYNAMIC}-${type}.json`
const ENTRY_DYNAMIC = 'entry-dynamic'

module.exports = {
  entry: () => {
    // Return object include all entries key value
    const entries = getEntry()
    const list = JSON.parse(readFileSync(entryDynamicFile))
    const dynamicEntries = {}
    list.forEach((name) => { dynamicEntries[name] = path.join(process.cwd(), entries[name]) })
    dynamicEntries[ENTRY_DYNAMIC] = entryDynamicFile
    return dynamicEntries
  }
}
```

We find the corresponding entry based on the URL visited by the user. If the current entry history has not been constructed, a loading page will be returned. We use this feature to dynamically change the entry. When the construction is completed, refresh the entry page again to display the true content of the entry.

### What does the proposed API of configuration look like?

The Webpack Document: https://webpack.js.org/configuration/entry-context/#dynamic-entry

**Comment by OrangeXC** [comment]
> By now, you can try to export a function type option as a workaround.

I don’t understand. Currently rspack does not support function type entries. Can you provide a simple code example?

**Comment by faga295** [comment]
Maybe @h-a-n-a  means, you can export function tyoe rspack config https://www.rspack.dev/config.html#exporting-a-configuration-function

**Comment by h-a-n-a** [comment]
> Maybe @h-a-n-a means, you can export function type rspack config https://www.rspack.dev/config.html#exporting-a-configuration-function

That's exactly that I mean. Sorry for making it confusing.

**Comment by childrentime** [comment]
bump

**Comment by childrentime** [comment]
https://github.com/childrentime/rspack-EntryOptionPlugin-diff-with-webpack

**Comment by childrentime** [comment]
I am using the EntryOptionPlugin to add a route when a page route is accessed. However, I found that rspack's EntryOptionPlugin does not allow a function to be used as an entry. This is clearly inconsistent with the plugins in webpack.

**Comment by childrentime** [comment]
https://github.com/webpack/webpack/blob/4b4ca3b/lib/EntryOptionPlugin.js#L31-L34

**Comment by childrentime** [comment]
https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/lib/EntryOptionPlugin.ts#L28-L31 Just saw that it's not supported yet. 😭

**Comment by SyMind** [comment]
Close with https://github.com/web-infra-dev/rspack/pull/6393
