### ISSUE TITLE
provide traverse module graph api

### ISSUE THREAD

**Issue by JiangWeixian** [web-infra-dev/rspack#5383]
### What problem does this feature solve?

I looks for moduleGraph api to traverse module graph to find all client components during build process. Looks like module_graph api only able  used in rust side.

https://github.com/web-infra-dev/rspack/blob/1ba8e10b5434ab20b8ac4ae5f2cf8ed1a79616cd/crates/rspack_core/src/chunk_graph/chunk_graph_module.rs#L232-L234

### What does the proposed API of configuration look like?

1. Provide moduleGraph api in js side
2. Register rust version rspack plugin

**Comment by h-a-n-a** [comment]
We are not going to support Rust plugin in the near future. Compiling from scratch as soon as rspack rust API is stable might be a good choice. But still we don't have plans for that at least this time.

**Comment by JiangWeixian** [comment]
So also no any plan to provide moduleGraph js api?

**Comment by h-a-n-a** [comment]
> > Compiling from scratch as soon as rspack rust API is stable might be a good choice.
> 
> You mean rspack will publish `rspack_core` to crates.io, user can create new compiler from scratch

Sorry for the late reply. Yes, that's what I mean.
