### ISSUE TITLE
部分第三方库在webpack4中引入正常，使用rspack后引入有问题

### ISSUE THREAD

**Issue by tiannengyu** [web-infra-dev/rspack#5384]
### System Info

node 18 
react

### Details

项目由webpack4升级至rsbuild，发现第三方包在webpack4下正常使用
import watermark from 'watermark-dom';
当mode为development时，改为import  {watermark} from 'watermark-dom';可正常使用
在mode为production生成产物或者使用preview功能时，import watermark from 'watermark-dom';打印出watermark为空
对应的watermark-dom包的地址：
github:https://github.com/saucxs/watermark-dom
npm:https://www.npmjs.com/package/watermark-dom

### Reproduce Steps

yarn
yarn add watermark-dom
yarnbuld

import watermark from 'watermark-dom';
console.log(watermark)打印为空

**Comment by h-a-n-a** [comment]
@LingyuCoder Would you please help to triage this issue?

**Comment by chenjiahan** [comment]
The behavior of Rspack is the same as Webpack 5, so this issue won't be fixed.

see: 

- https://github.com/webpack/webpack/issues/16126
- https://github.com/web-infra-dev/rsbuild/issues/1389

**Comment by chenjiahan** [comment]
- target 有的：https://www.rspack.dev/zh/config/target.html
- noParse 正在支持，参考：https://github.com/web-infra-dev/rspack/issues/4739 和 https://github.com/web-infra-dev/rspack/pull/5252

**Comment by wChenonly** [comment]
> > The behavior of Rspack is the same as Webpack 5, so this issue won't be fixed.
> > see:
> > 
> > * [discuss for remove unused argument in runtime function template in webpack5 webpack/webpack#16126](https://github.com/webpack/webpack/issues/16126)
> > * [[Bug]: 部分第三方库在webpack4中引入正常，使用rsbuild后引入有问题 rsbuild#1389](https://github.com/web-infra-dev/rsbuild/issues/1389)
> 
> `module.exports = { module: { noParse: /watermark-dom/, }, target: ["web", "es5"], // remove arrow function in output };` webpack5的该配置，rspack的api支持吗，参考[rspack.dev/zh/config.html](https://www.rspack.dev/zh/config.html) 好像没有module.noParse和target相关配置说明

只需要noParse，只要去不解析即可。
