### ISSUE TITLE
automatic update outdated dependency 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#5387]
Rsbuild uses [renovate](https://github.com/apps/renovate) to do automatic update dependency https://github.com/web-infra-dev/rsbuild/issues/1316, Rspack can also integrate this to ensure dependency is updated.

**Comment by Boshen** [comment]
I can turn it on for Rust and github actions.

Our npm dependencies are too convoluted to be updated automatically yet. I tried using `depcheck` and `skott` but things start falling apart when I start removing dependencies.

**Comment by Boshen** [comment]
Rust crates and github actions are done.

FYI https://developer.mend.io/github/web-infra-dev/rspack shows the update list at the bottom.

**Comment by Boshen** [comment]
Bulk of the work is done https://github.com/web-infra-dev/rspack/blob/main/.github/renovate.json

I'll update it when things become convoluted.
