### ISSUE TITLE
taps inflation on serve mode

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rspack#5398]
### System Info

```

  System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 123.84 MB / 32.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.10.0 - ~/.managed/n/bin/node
    npm: 10.2.3 - ~/.managed/n/bin/npm
    pnpm: 8.14.2 - ~/.managed/n/bin/pnpm
    bun: 1.0.22 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.3
  npmPackages:
    @rspack/cli: canary => 0.5.1-canary-38ebbd3-20240118010407 
    @rspack/core: canary => 0.5.1-canary-38ebbd3-20240118010407 

```

Also produced with:
- 0.5.1 
- nightly (0.5.1)
- 0.5.2-canary-6f90fc7-20240123030502 #5400

Not produced with:
- 0.5.0

### Details

![image](https://github.com/web-infra-dev/rspack/assets/18117084/26685843-ec58-4c61-8bcd-f4b8cbcf4ffd)

### Reproduce link

https://github.com/xc2/rspack-hooks-repro

### Reproduce Steps

```js
// a plugin in js
const plugin = {
    apply(compiler) {
        const name = 'plugin-xx';
        compiler.hooks.compilation.tap(name, (compilation) => {
            compilation.hooks.optimizeChunkModules.tap(name, () => {
                console.log('optimizeChunkModules called');
            })
            
            console.log('optimizeChunkModules taps:', compilation.hooks.optimizeChunkModules.taps.filter(tap => tap.name === name).length);
        })
    }
}
```

### Steps

- Run serve mode
- See once `optimizeChunkModules called` following `optimizeChunkModules taps: 1`
- Modify source codes like `src/index.js`
- See double `optimizeChunkModules called` following `optimizeChunkModules taps: 2`
- Modify source codes like `src/index.js`
- See triple `optimizeChunkModules called` following `optimizeChunkModules taps: 3`

### Expected

- Always see once `optimizeChunkModules called` following `optimizeChunkModules taps: 1` after every source change.

### More

I use `compiler.hooks.compilation` and `compilation.hooks.optimizeChunkModules` just for instance - seems that this issue applies to not only these hooks.

**Comment by h-a-n-a** [comment]
Hi, thanks for reporting this to us. Would you like to fix this?

**Comment by xc2** [comment]
> Hi, thanks for reporting this to us. Would you like to fix this?

sure i would

**Comment by h-a-n-a** [comment]
Original place that introduced this issue: https://github.com/web-infra-dev/rspack/pull/5202
