### ISSUE TITLE
webpack-test/cases/cjs-tree-shaking/reexports paniced when remove the `test.filter.js` 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#5403]
### System Info

not related

### Details

15: rspack_plugin_javascript::utils::eval::BasicEvaluatedExpression::string::h88091c3a89a816ad
    at /xxx/Documents/rspack/rspack/crates/rspack_plugin_javascript/src/utils/eval/mod.rs:321
rspack_plugin_javascript::parser_plugin::common_js_imports_parse_plugin::CommonJsImportsParserPlugin::chain_handler::h9098f792a2ea80ff
    at /xxx/Documents/rspack/rspack/crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs:84
17: <rspack_plugin_javascript::parser_plugin::common_js_imports_parse_plugin::CommonJsImportsParserPlugin as rspack_plugin_javascript::parser_plugin::trait::JavascriptParserPlugin>::member::hf05e24027384a17d
    at /xxx/Documents/rspack/rspack/crates/rspack_plugin_javascript/src/parser_plugin/common_js_imports_parse_plugin.rs:291
18: <rspack_plugin_javascript::parser_plugin::drive::JavaScriptParserPluginDrive as rspack_plugin_javascript::parser_plugin::trait::JavascriptParserPlugin>::member::h0b497de9ccbc66fa
    at /xxx/Documents/rspack/rspack/crates/rspack_plugin_javascript/src/parser_plugin/drive.rs:53
19: rspack_plugin_javascript::visitors::dependency::parser::walk::<impl rspack_plugin_javascript::visitors::dependency::parser::JavascriptParser>::walk_member_expression::h43576cf9ca1ccd5b
    at /xxx/Documents/rspack/rspack/crates/rspack_plugin_javascript/src/visitors/dependency/parser/walk.rs:568

### Reproduce Steps

1. cd webpack-tests
2. remove `test.filter.js` under webpack-test/cases/cjs-tree-shaking/reexports
3. pnpm test

**Comment by bvanjoi** [comment]
I think #5427 will provide assistance.

**Comment by IWANABETHATGUY** [comment]
Yeah, this issue should be fixed when https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/ConstPlugin.js#L478-L502 is finished
