### ISSUE TITLE
InnerGraph does not rename the usage of the renamed class in if statement

### ISSUE THREAD

**Issue by LingyuCoder** [web-infra-dev/rspack#5441]
InnerGraph use PureExpressionDependency to flag `/* unused pure expression or super */` on unused variables and set it to `null`

But when a class is renamed and access its prototype in an if statement, it is actually used, but currently rspack consider it as unused. See the code below:

https://github.com/web-infra-dev/rspack/blob/451e2791835a6dd5b046d91251a3cfd3e7684215/crates/rspack/tests/tree-shaking/unused-class-rename/app.js#L8-L11

And the [codegen result](https://github.com/web-infra-dev/rspack/blob/bug/unused-class-rename/crates/rspack/tests/tree-shaking/unused-class-rename/snapshot/new_treeshaking.snap#L13-L16) of rspack will cause an error:

```js
if (__AAA__) {
    const __Cls = (/* unused pure expression or super */ null && (Cls));
    __Cls.prototype.aaa = function(a, b) {};
}
```

The codegen result of webpack should be like this, it just works:

```js
if (__AAA__) {
    const __Cls = Cls;
    __Cls.prototype.aaa = function(a, b) {};
}
```

You can reproduce it on `bug/unused-class-rename` branch and the case is under the `crates/rspack/tests/tree-shaking/unused-class-rename` directory

**Comment by LingyuCoder** [comment]
Seem to be caused by this line, identifier's parser context in block is not same with top level context.

https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_javascript/src/plugin/inner_graph_plugin.rs#L311

**Comment by IWANABETHATGUY** [comment]
yeah, maybe we need a temp scope impl to fix this. `top_level_ctxt` in swc  is different from `webpack`

**Comment by LingyuCoder** [comment]
maybe this line can be modified to `if self.is_toplevel() {`
