### ISSUE TITLE
0.5.1+版本VUE3项目HMR失效

### ISSUE THREAD

**Issue by 0604hx** [web-infra-dev/rspack#5446]
### System Info

操作系统：windows 11
处理器：11th Gen Intel(R) i5-11300H 3.11 GHz
node版本：21.4.0 64位
vue版本：3.4.10
vue-loader版本：17.4.2
rspack版本：0.5.1+

### Details

更新到 0.5.1+ 后，项目在开发环境下 HMR 失效，0.5.0 版本则正常

### Reproduce link

https://github.com/0604hx/grid-form

### Reproduce Steps

1. 拉取代码
2. 修改 packages/example/package.json 中 rspack 版本到最新（0.5.2）
3. pnpm i
4. pnpm dev
5. 访问 http:://localhost:8080
6. 修改任意 vue 文件（页面不生效）

**Comment by xc2** [comment]
问题 #5398 相关，已被 #5436 修复，但尚未发布。

请使用这个 canary 版本重新试一下： `0.5.2-canary-10e7787-20240124092141`

related #5398, was fixed by #5436, not published yet.

please recheck with the canary version: `0.5.2-canary-10e7787-20240124092141`

**Comment by xc2** [comment]
@0604hx 这个版本可以吗。

可以提供以下你的 pnpm-lock.yaml 吗，我昨天在外面可以重现你的问题，换个版本好了，我今天在家又没法重现你的问题了。

**Comment by xc2** [comment]
该 bug 跟 windows build 和 alias 有关，将在另一个 issue 里面跟进 #5445
