### ISSUE TITLE
在vue里面怎么使用 svg 呢 ？

### ISSUE THREAD

**Issue by luoriwusheng-xia** [web-infra-dev/rspack#5450]
### System Info

```
node: 20.10.0
 "@rspack/cli": "^0.5.2",
"@rspack/core": "^0.5.2"
```

```
 "vue": "^2.7.16",
```

### Details

在 webpack5 里面可以直接配置 

```
{
        test: /\.(png|svg|jpg|jpeg|gif|webp)$/i,
        type: 'asset/resource',
        exclude: /node_modules/
      },
```

vue中能加载svg文件

那么在 rspack里面好像不好使

### Reproduce Steps

我是在项目里面测试发现没有加载出来

**Comment by luoriwusheng-xia** [comment]
官方文档：资源（如：图片、字体、视频等）是 Rspack 的一等公民，这意味着你不需要任何的 Loader 来处理这些内容。 资源和其他的模块类型不同，它们通常是独立存在的，因此资源会以模块的粒度做最终的生成。

那么，好像没有单独说 svg, 不确定是不是一等公民，直接使用

**Comment by h-a-n-a** [comment]
> 官方文档：
> 
> > 资源（如：图片、字体、视频等）是 Rspack 的一等公民，这意味着你不需要任何的 Loader 来处理这些内容。 资源和其他的模块类型不同，它们通常是独立存在的，因此资源会以模块的粒度做最终的生成。
> 
> 那么，好像没有单独说 svg, 不确定是不是一等公民，直接使用

详细贴一下使用方式吧

**Comment by luoriwusheng-xia** [comment]
> > 官方文档：
> > > 资源（如：图片、字体、视频等）是 Rspack 的一等公民，这意味着你不需要任何的 Loader 来处理这些内容。 资源和其他的模块类型不同，它们通常是独立存在的，因此资源会以模块的粒度做最终的生成。
> > 
> > 
> > 那么，好像没有单独说 svg, 不确定是不是一等公民，直接使用
> 
> 详细贴一下使用方式吧，或提供一个最小 demo

这个仓库，怎么让svg图标能使用

https://gitee.com/luoriwusheng/vue-element-admin.git

**Comment by SyMind** [comment]
@luoriwusheng-xia 给出的仓库目录下存在 `vue.config.js`，其中对于 svg 的处理使用 [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader)，你需要采取相同的配置来处理。

**Comment by luoriwusheng-xia** [comment]
> @luoriwusheng-xia 给出的仓库目录下存在 `vue.config.js`，其中对于 svg 的处理使用 [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader)，你需要采取相同的配置来处理。

好的 好的， 我试试， 我以为 rspack自己处理了这个，不需要我们单独指定

**Comment by luoriwusheng-xia** [comment]
> @luoriwusheng-xia 给出的仓库目录下存在 `vue.config.js`，其中对于 svg 的处理使用 [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader)，你需要采取相同的配置来处理。

尝试了一下，[svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader) 插件目前接入到 rspack中会报错， 经过调试， 发现rspack 注入到 svg-sprite-loader 中的上下问为 undefined

svg-sprite-loader 内部的 原始文件 lib/configurator.js

![image](https://github.com/web-infra-dev/rspack/assets/152823466/270022d7-ea6e-48f7-82b4-f759da9e7e97)

做了参数补齐以后，项目运行目前不报错了，但是svg文件并没有生效。


修改后 完整的configurator：

```js

/**
 * @param {Object} params
 * @param {Object} [params.config] Parsed loader config {@see SVGSpriteLoaderConfig}
 * @param {LoaderContext} context Loader context {@see https://webpack.js.org/api/loaders/#the-loader-context}
 * @return {Object}
 */
module.exports = function configurator({ config, context, target }) {
  // 在 rspack中， context._module 是undefined, 导致下面的 utils.isModuleShouldBeExtracted 内部报错
  // 目前猜测是 rspack或者 webpack版本断层导致当前插件 在运行时， context._module 为undefined
  let _module = {
    resource: context.resource,
    request: context.request,
    loader: context.loader
  }

  // 这是原来的代码
  // const module = context._module;
  const module = _module;
  const compiler = context._compiler;
  const compilation = context._compilation;
  const compilerName = compiler.name;

  const autoConfigured = {
    spriteModule: isTargetBrowser(target) ? loaderDefaults.spriteModule : isomorphicSpriteModule,
    symbolModule: isTargetBrowser(target) ? loaderDefaults.symbolModule : isomorphicSymbolModule,
    // 这里方法对 _module 有一个解构的动作， 不能对undefined 做解构，所有报错， 上面做了参数补齐
    extract: utils.isModuleShouldBeExtracted(module, compilation && compilation.moduleGraph),
    esModule: context.version && context.version >= 2
  };

  const finalConfig = merge.all([loaderDefaults, autoConfigured, config || {}]);

  /**
   * esModule should be `false` when compiles via extract-text-webpack-plugin or html-webpack-plugin.
   * Because this compilers executes module as usual node module so export should be always in commonjs style.
   * This could be dropped when Node.js will support ES modules natively :)
   * @see https://git.io/vS7Sn
   * @see https://git.io/v9w60
   */
  if (compilerName && (
    compilerName.includes('extract-text-webpack-plugin') ||
      compilerName.includes('html-webpack-plugin')
  )) {
    finalConfig.esModule = false;
  }

  return finalConfig;
};

```

**Comment by luoriwusheng-xia** [comment]
@h-a-n-a @SyMind    这个issue 还可以在跟进一下不 ？

**Comment by coderwyd** [comment]
@h-a-n-a 请问一下这个问题是解决了吗，为什么给关闭了？

**Comment by SyMind** [comment]
@luoriwusheng-xia 十分感谢你对问题的详细描述，Rspack 对于 Webpack 的 loader 上下文支持目前确实不完善，我将会跟进此问题。
@coderwyd 我重新打开了 issue。

**Comment by SyMind** [comment]
@luoriwusheng-xia 你目前可以考虑尝试使用以下配置在 vue 中使用 svg：

```js
rules: [
    {
        test: /\.svg/,
        type: "asset/resource"
    }
]
```
