### ISSUE TITLE
devServer.proxy 不支持cookieDomainRewrite

### ISSUE THREAD

**Issue by gzzhengbingyi** [web-infra-dev/rspack#5469]
### What problem does this feature solve?

本地代理接口的时候用到，但是将 vue-cli 正常使用的配置放到 Rspack.config.js 里面，发现没有用：
devServer: {
    allowedHosts: 'all',
    proxy: {
      '/v2/static': {
        target: 'http://localhost:8080',
        pathRewrite: { '^/v2': '' },
      },
      '/api': {
        target: 'https://test-xxx.com',
        changeOrigin: true,
        cookieDomainRewrite: 'localhost',
      },
      '/pro': {
        target: 'https://test-xxx.com',
        changeOrigin: true,
        cookieDomainRewrite: 'localhost',
      },
    },
  },

### What does the proposed API of configuration look like?

devServer: {
    allowedHosts: 'all',
    proxy: {
      '/v2/static': {
        target: 'http://localhost:8080',
        pathRewrite: { '^/v2': '' },
      },
      '/api': {
        target: 'https://test-xxx.com',
        changeOrigin: true,
        cookieDomainRewrite: 'localhost',
      },
      '/pro': {
        target: 'https://test-xxx.com',
        changeOrigin: true,
        cookieDomainRewrite: 'localhost',
      },
    },
  },

**Comment by xc2** [comment]
我用你这一小段配置试了下 cookieDomainRewrite 是能正常工作的，可以辛苦你创建一个最小复现仓库吗
