### ISSUE TITLE
Can't resolve request with resouceQuery including multiple '?'

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#5475]
### System Info

System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 88.83 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/Library/Caches/fnm_multishells/43477_1706014487935/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/43477_1706014487935/bin/yarn
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/43477_1706014487935/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.6
  npmPackages:
    @rspack/binding: workspace:* => 0.5.2
    @rspack/core: workspace:* => 0.5.2
    @rspack/plugin-minify: workspace:^ => 0.5.2
    @rspack/plugin-node-polyfill: workspace:^ => 0.5.2

### Details

when I import a module with resourceQuery including multiple '?', like this `import answer from './answer?query?string' `, it compiles successfully in webpack but fails in rspack

### Reproduce link

https://github.com/faga295/rspack-reproduce/tree/resolve_request_resourceQuery

### Reproduce Steps

1. pnpm install
2. pnpm build:webpack(success)
3. pnpm build:rspack(fail)

**Comment by h-a-n-a** [comment]
Fixed
