### ISSUE TITLE
rspack_core: ustr may not be the ideal choice for module identifier

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#5481]
### Details

While upgrading to ustr 1.0 https://docs.rs/ustr/latest/ustr/, ahash upgrade yielded inconsistent hash results. 

From ahash's documentation https://github.com/tkaitchuck/ahash:

> AHash does not have a fixed standard for its output. This allows it to improve over time. 

> Because it does not have a fixed standard, different computers or computers on different versions of the code will observe different hash values. As such, aHash is not recommended for use other than in-memory maps.

Unfortunately we are currently using it as part of our hash:

https://github.com/web-infra-dev/rspack/blob/88e5557dee8cc2acce3be53cbf054065ab81610d/crates/rspack_core/src/compiler/compilation.rs#L1996

**Comment by IWANABETHATGUY** [comment]
Using the `str`  may fix your issue, `module.identifier().as_str().hash(xxx)`

**Comment by Boshen** [comment]
> Using the internal `str` may fix your issue, `module.identifier().as_str().hash(xxx)`

This is a footgun, how would anyone remember to use this form?

**Comment by h-a-n-a** [comment]
This, for sure, is not the ultimate solution for us if portable caching is the ultimate goal of us. But it should be ok for now as we haven't got the plan in the near future to support this. Nevertheless, it still cause unstable hash in snapshots we might have to fix this.

> Using the internal `str` may fix your issue, `module.identifier().as_str().hash(xxx)`

This might be a temporary solution as it's not performant ;-( (precomputed-hash is gone)

**Comment by Boshen** [comment]
@IWANABETHATGUY @h-a-n-a How do you feel about https://github.com/web-infra-dev/rspack/pull/5504, it's only a 2 line change in the ustr crate https://github.com/anderslanglands/ustr/compare/master...Boshen:ustr-fxhash:master

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY @h-a-n-a How do you feel about #5504, it's only a 2 line change in the ustr crate [anderslanglands/ustr@master...Boshen:ustr-fxhash:master](https://github.com/anderslanglands/ustr/compare/master...Boshen:ustr-fxhash:master)

the consistent hash function is the best way to solve this issue.

**Comment by IWANABETHATGUY** [comment]
> > consistent hash function
> 
> Can you elaborate? Is my change acceptable or not?

I mean using  rustc hash function should make the hash result of `Ustr` consistent, yeah, your solution is acceptable.

**Comment by h-a-n-a** [comment]
> @IWANABETHATGUY @h-a-n-a How do you feel about #5504, it's only a 2 line change in the ustr crate [anderslanglands/ustr@master...Boshen:ustr-fxhash:master](https://github.com/anderslanglands/ustr/compare/master...Boshen:ustr-fxhash:master)

Looks good to me ;-)
