### ISSUE TITLE
Add `need demo` or `need example` label

### ISSUE THREAD

**Issue by LingyuCoder** [web-infra-dev/rspack#5501]
Somtimes after a new feature being implemented, an example should be added to tell users that how this feature should be used.

So perhaps, we need a new label `need demo` or `need example`, just like `need document`, relate to [rspack-examples](https://github.com/rspack-contrib/rspack-examples) and the workflows shall be added

**Comment by chenjiahan** [comment]
The label has been created:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/08093af5-a432-485d-b7ac-64ee499a8b25)
