### ISSUE TITLE
HtmlRspackPlugin add support for alwaysWriteToDisk

### ISSUE THREAD

**Issue by raix** [web-infra-dev/rspack#5516]
### What problem does this feature solve?

In hybrid application setups with mixed front-end and back-end technologies it can often be useful for the back-end to serve the `index.html`
This works fine in production but the `index.html` file is not outputted in development mode.

Current solution is to use the  `HtmlWebpackHarddiskPlugin` to enable `alwaysWriteToDisk` in `HtmlWebpackPlugin` - this works fine, but would be great to use the `HtmlRspackPlugin` and have less dependencies to install.

### What does the proposed API of configuration look like?

One proposal could be to add an option `alwaysWriteToDisk` to the `HtmlWebpackPlugin`:

```js
    new HtmlWebpackPlugin({
      template: "./public/index.html",
      meta: {
        runtimeEnv: "%ENCODED_RUNTIME_ENV%",
      },
      alwaysWriteToDisk: true, // Always write the index.html file to disk
      publicPath: "%CDN_URL%",
    }),
```

*One could also add a similar option in the dev server options, maybe allowing a filter to prevent all assets to be written to disk*

**Comment by xc2** [comment]
```js
module.exports = {
// ...other configs
  devServer: {
    devMiddleware: {
      writeToDisk: (filename) => {
        return /index.html$/.test(filename);
      },
    },
  },
}
```

should work. please give a try

**Comment by raix** [comment]
Thanks @xc2 that worked perfectly! ❤️
