### ISSUE TITLE
Can't resolve dynamic import when target is 'webworker' and set dynamicImportMode: "eager"

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5548]
### System Info

  System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.19 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.21 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/yarn
    npm: 10.2.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/npm
    pnpm: 8.14.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 16.6
  npmPackages:
    @rspack/cli: latest => 0.5.3
    @rspack/core: latest => 0.5.3

### Details

Rspack build gets `Can't resolve dynamic import` error when target is 'webworker' and set dynamicImportMode: "eager".

```js
const config = {
  mode: "production",
  target: "webworker",
  module: {
    parser: {
      javascript: {
        dynamicImportMode: "eager",
      },
    },
  },
};
```

Error (webpack is ok): 

![image](https://github.com/web-infra-dev/rspack/assets/7237365/50a594e8-e040-4417-9f5f-8ee598800d7d)

### Reproduce link

https://github.com/chenjiahan/rsbuild-repro-worker-dynamic-import

### Reproduce Steps

1. pnpm i
2. pnpm build:rspack
3. pnpm build:webpack

**Comment by bvanjoi** [comment]
`newTreeshaking` will fix this:

```js
module.exports = {
  //.....
  experiments: {
    rspackFuture: {
      newTreeshaking: true
    }
  }
}
```
