### ISSUE TITLE
[Feature]: Website Playground

### ISSUE THREAD

**Issue by INeedJobToStartWork** [web-infra-dev/rspack#5570]
### What problem does this feature solve?

Add playground which could show output of inputed code.

With this users could:
- understand threeshaking of rspack
- check the code output correctness 
- Find and report potentional problems with code samples (it could work like in SWC playground)

### What does the proposed API of configuration look like?

Alternative/Example: https://swc.rs/playground

**Comment by hardfist** [comment]
we need wasm support to support playground first
