### ISSUE TITLE
[Bug]: panic "Run build_module hook failed" in compiler queue

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#5573]
### What problem does this feature solve?

Should exit gracefully in webpack-test 

https://github.com/web-infra-dev/rspack/blob/b4a98eef5d7d27635e87daca48a6fca0da2789c7/webpack-test/configCases/deprecations/invalid-dependencies/webpack.config.js#L18-L21

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Run succeed_module hook failed: TypeError: webpack.util.LazySet is not a constructor

Location: crates/rspack_core/src/compiler/queue.rs:413
```

### What does the proposed API of configuration look like?

https://github.com/web-infra-dev/rspack/blob/b4a98eef5d7d27635e87daca48a6fca0da2789c7/crates/rspack_core/src/compiler/queue.rs#L384

https://github.com/web-infra-dev/rspack/blob/b4a98eef5d7d27635e87daca48a6fca0da2789c7/crates/rspack_core/src/compiler/queue.rs#L413

**Comment by h-a-n-a** [comment]
@LingyuCoder Would you please have a look?
