### ISSUE TITLE
[Bug]: panic "should have dependency id" in import_meta_context_dependency

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#5580]
### Details

https://github.com/web-infra-dev/rspack/blob/9e92b5c76b930c98d68c271f21a53170131979f3/crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs#L92

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have dependency id
Location: crates/rspack_plugin_javascript/src/dependency/context/import_meta_context_dependency.rs:92
```

### Reproduce Steps

webpack-test/configCases/resolve/issue-15580

**Comment by mateonunez** [comment]
I'm facing with the same issue:

```
$ rsbuild dev
  Rsbuild v0.3.11

  > Local:    http://localhost:8080/
  > Network:  http://192.168.1.70:8080/

start   Compiling...
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have dependency id
Location: crates/rspack_plugin_javascript/src/dependency/context/import_context_dependency.rs:100

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _napi_register_module_v1
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: _napi_register_module_v1
    at <unknown source file>
21: _napi_register_module_v1
    at <unknown source file>
22: _napi_register_module_v1
    at <unknown source file>
23: _napi_register_module_v1
    at <unknown source file>
24: _napi_register_module_v1
    at <unknown source file>
25: _napi_register_module_v1
    at <unknown source file>
26: _napi_register_module_v1
    at <unknown source file>
27: _napi_register_module_v1
    at <unknown source file>
28: _napi_register_module_v1
    at <unknown source file>
29: _napi_register_module_v1
    at <unknown source file>
30: _napi_register_module_v1
    at <unknown source file>
31: _napi_register_module_v1
    at <unknown source file>
32: _napi_register_module_v1
    at <unknown source file>
33: __pthread_joiner_wake
    at <unknown source file>
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sachin-walunj** [comment]
I am getting this error 

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  internal error: entered unreachable code
Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:82

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by bvanjoi** [comment]
@sachin-walunj this doesn't appear to be the same error. Can you create a new issue and provide a repository to enable us to reproduce the error?

**Comment by xinlanlan** [comment]
> I am getting this error
> 
> ```
> Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
> Message:  internal error: entered unreachable code
> Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:82
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> Run with RUST_BACKTRACE=full to include source snippets.
> Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
> Message:  internal error: entered unreachable code
> Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:82
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> Run with RUST_BACKTRACE=full to include source snippets.
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>  1: _napi_register_module_v1
>     at <unknown source file>
>  2: _napi_register_module_v1
>     at <unknown source file>
>  3: _napi_register_module_v1
>     at <unknown source file>
>  4: _napi_register_module_v1
>     at <unknown source file>
>  5: _napi_register_module_v1
>     at <unknown source file>
>  6: _napi_register_module_v1
>     at <unknown source file>
>  7: _napi_register_module_v1
>     at <unknown source file>
>  8: _napi_register_module_v1
>     at <unknown source file>
>  9: _napi_register_module_v1
>     at <unknown source file>
> 10: _napi_register_module_v1
>     at <unknown source file>
> 11: _napi_register_module_v1
>     at <unknown source file>
> ```

I used the " jszip" and this error occurred
