### ISSUE TITLE
[Bug]: Panic occurred at runtime. with v 0.5.2 on Windows

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5592]
### System Info

Windows, rspack v 0.5.2

### Details

Hello, I ran into the below issue when running the rspack serve command to start an application on a windows machine. However I do not run into this issue on a Mac device.  

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  internal error: entered unreachable code
Location: C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\oxc_resolver-1.2.2\src\path.rs:69

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (60%) building builtin:swc-loader??ruleSet[1].rules[13].use[0]!D:\source\cd━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (60%) 

### Reproduce Steps

N/A

**Comment by pushkargupta9807** [comment]
@h-a-n-a I am not sure how to create a repro for this, since this error is not on MacOS. Someone else also reported the same issue:
[rspack](https://github.com/web-infra-dev/rspack/issues/5352)

**Comment by hardfist** [comment]
cc @Boshen  this panic raises from oxc_resolver, do you have any clue?

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc-resolver/issues/79

I'll get it fixed.

**Comment by pushkargupta9807** [comment]
Thanks @Boshen

**Comment by Boshen** [comment]
@pushkargupta9807 can you help me a bit by posting your `resolve` config? I have a feeling there's something similar to `path.resolve(__dirname, "src"`. Try use a relative path before this is fixed.
