### ISSUE TITLE
[Bug]: using `concatenateModules` with `experiments.css` and results in no CSS in output

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5593]
### System Info

```
  Binaries:
    Node: 18.17.1 - ~/Library/Caches/fnm_multishells/3027_1706874775530/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/3027_1706874775530/bin/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/3027_1706874775530/bin/npm
    pnpm: 7.33.6 - ~/Library/Caches/fnm_multishells/3027_1706874775530/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Firefox Nightly: 115.0
    Safari: 17.0
  npmPackages:
    @rspack/cli: ^0.5.1 => 0.5.1 
    @rspack/core: 0.5.3-canary-c9f8d78-20240201071306 => 0.5.3-canary-c9f8d78-20240201071306 
```

### Details

I'm using the concatenateModules from https://github.com/web-infra-dev/rspack/pull/5415. It is great that the bundle size reduced significantly!

But it seems that there is no CSS in the output :(

And if I add `@import './bar.css';` in the CSS, the imported CSS will be emitted to the output. Seems like only the CSS directly imported by JS is not emitted correctly.

### Reproduce Steps

Using the following example:

```js
// index.js
import styles from './foo.css'

console.log(styles)
```

```css
/** foo.css */
.foo {
    background-color: red;
}
```

```js
// rspack.config.js
export default {
  mode: "production",
  entry: {
    main: "./index.js",
  },
  optimization: {
    concatenateModules: true,
    minimize: false,
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        type: "css/module",
      },
    ],
  },
  experiments: {
    css: true,
    rspackFuture: {
      newTreeshaking: true,
    },
  },
};
```

**Comment by IWANABETHATGUY** [comment]
https://github.com/IWANABETHATGUY/rspack-concate-css-module
looks like the output is already different from `webpack` so there is no way to align with webpack `concatenateModules`, can you have a look @JSerFeng

**Comment by JSerFeng** [comment]
Though the runtime is different, we should still generate correct CSS output.
The reason of this issue is that, concate module will remove module from original chunk, but only if the module's sourceType === javascript. For CSS module, it can have 2 sourceType, it should delete the javascript sourceType, and do not disconnect module from that chunk
