### ISSUE TITLE
[Bug]: using `concatenateModules` with `rspack serve` cause runtime panic "should have build info"

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5594]
### System Info

```
  Binaries:
    Node: 18.17.1 - ~/Library/Caches/fnm_multishells/180_1706947163882/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/180_1706947163882/bin/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/180_1706947163882/bin/npm
    pnpm: 7.33.6 - ~/Library/Caches/fnm_multishells/180_1706947163882/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Firefox Nightly: 115.0
    Safari: 17.0
  npmPackages:
    @rspack/cli: 0.5.3-canary-c9f8d78-20240201071306 => 0.5.3-canary-c9f8d78-20240201071306
    @rspack/core: 0.5.3-canary-c9f8d78-20240201071306 => 0.5.3-canary-c9f8d78-20240201071306
```

### Details

I'm using the `concatenateModules` from https://github.com/web-infra-dev/rspack/pull/5415. It is great that the bundle size reduced significantly!

But when using `rspack serve`, the following panic happens.

https://github.com/web-infra-dev/rspack/blob/1b057d6ab0b1cc758897ec8a5b03c1ab712299ad/crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs#L575

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have build info
Location: crates/rspack_plugin_javascript/src/plugin/module_concatenation_plugin.rs:575
```

### Reproduce Steps

With the following files:
```js
// src/index.js
console.log('Hello, rspack');
```

```js
// rspack.config.js
export default {
  entry: {
    main: "./src/index.js",
  },
  optimization: {
    concatenateModules: true,
    minimize: false,
  },
  experiments: {
    rspackFuture: {
      newTreeshaking: true,
    },
  },
};
```

run `rspack serve` and edit the `src/index.js` will re-produce the panic.

**Comment by IWANABETHATGUY** [comment]
It is a known issue, cc @jkzing

**Comment by IWANABETHATGUY** [comment]
It's a known issue, @jerrykingxyz

**Comment by sachin-walunj** [comment]
I am also facing error 
```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  internal error: entered unreachable code
Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:82

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _napi_register_module_v1
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
```

**Comment by IWANABETHATGUY** [comment]
> I am also facing error
> 
> ```
> Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
> Message:  internal error: entered unreachable code
> Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:82
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> Run with RUST_BACKTRACE=full to include source snippets.
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>  1: _napi_register_module_v1
>     at <unknown source file>
>  2: _napi_register_module_v1
>     at <unknown source file>
>  3: _napi_register_module_v1
>     at <unknown source file>
>  4: _napi_register_module_v1
>     at <unknown source file>
>  5: _napi_register_module_v1
>     at <unknown source file>
>  6: _napi_register_module_v1
>     at <unknown source file>
>  7: _napi_register_module_v1
>     at <unknown source file>
>  8: _napi_register_module_v1
>     at <unknown source file>
>  9: _napi_register_module_v1
>     at <unknown source file>
> 10: _napi_register_module_v1
>     at <unknown source file>
> 11: _napi_register_module_v1
>     at <unknown source file>
> ```

It looks like your issue is irrelated, could you please file another issue?

**Comment by colinaaa** [comment]
I tried the canary version in #5692 with the same demo, and another panic occurred:

`Module(<path>) should be added before using`.

```
Message:  Module(/home/webpack-app/node_modules/.pnpm/@rspack+dev-server@0.5.4_cfxbo3brkdttvrslyfa2opfk5e/node_modules/@rspack/dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true|94e243c27d9fb0a2fa50cb7b8d90fd3f) should be added before using
Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:75
```

Should I file another issue? Or re-open this one?

BTW, I can make a workaround by setting `devServer.client` to `false`.

**Comment by IWANABETHATGUY** [comment]
can you try 0.5.7-canary-6007430-20240313111541
