### ISSUE TITLE
[Bug]: Treeshaking output error

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#5595]
### System Info

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.36 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @rspack/cli: latest => 0.5.2 
    @rspack/core: /Users/bytedance/libs/rspack/packages/rspack => 0.5.3 

### Details

<img width="757" alt="image" src="https://github.com/web-infra-dev/rspack/assets/57202839/29149261-cfdd-40c4-8dfb-dd41edcf1cca">

![image](https://github.com/web-infra-dev/rspack/assets/57202839/dd311a3f-138d-48db-a788-3b5ad8698b5a)

### Reproduce link
https://github.com/web-infra-dev/rspack-repro/tree/issue-5595
_No response_

### Reproduce Steps

npm run build:rspack

Search `node_modules/uuid/dist/esm-node/v5.js` in the output

**Comment by JSerFeng** [comment]
uncomment those lines 
![image](https://github.com/web-infra-dev/rspack/assets/57202839/1da06999-bd2a-466e-b79d-be7d1f4ae2ff)

**Comment by IWANABETHATGUY** [comment]
I tried disabling the `splitChunks` and it works.

**Comment by IWANABETHATGUY** [comment]
0.5.3-canary-431379d-20240206044033

**Comment by alfaproject** [comment]
That canary seems to fix the broken bundles that I reported with my small repro. I'll try it out in our main project later today and report back
