### ISSUE TITLE
[Bug]: handlebars = "5.1.1" in  swc_plugin_import was yanked

### ISSUE THREAD

**Issue by youth95** [web-infra-dev/rspack#5613]
### System Info

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 407.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3

### Details

<img width="796" alt="image" src="https://github.com/web-infra-dev/rspack/assets/15139527/63dc8466-b5ae-4734-b09a-021f695efa08">

### Reproduce Steps

use rspack_core in rust

**Comment by h-a-n-a** [comment]
Thanks for the report. 

Using rust crate is not recommended now as it's not stable yet ;-). The recommended way is to use node package.
