### ISSUE TITLE
[Feature]: improve diagnostic when resolve failed with missing `resolve.extensions`

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5627]
### What problem does this feature solve?

For example, if a module resolution is failed as I do `import("./foo")`. 
Then we will check the files in the **current directory** with name "foo" but with different extensions or the directory named "foo" with its "index" file(according to `mainFiles`) with different extension than preconfigured resolve.extensions. This could avoid us from setting arbitrary extensions and keep rspack as more Web-spec as possible. 
Then rspack can list these suggestions in the help section of each diagnostic.

### What does the proposed API of configuration look like?

NO API change.

**Comment by h-a-n-a** [comment]
To add this support, you may refer to this for details:
1. Add a new error hint helper in this file https://github.com/web-infra-dev/rspack/blob/a4b8196a493076b790313ad1deec227d3c04813c/crates/rspack_core/src/resolver/mod.rs#L70.
2. Add a test in `packages/rspack/test/diagnostics` to test out the diagnostic

**Comment by luhc228** [comment]
I want to have a try.

**Comment by hardfist** [comment]
@luhc228  thanks in advance
