### ISSUE TITLE
[Feature]: built-in `type: "css"` support like `insert` option of `style-loader`

### ISSUE THREAD

**Issue by JounQin** [web-infra-dev/rspack#5628]
### What problem does this feature solve?

https://github.com/webpack-contrib/style-loader#insert

Usage https://github.com/backstage/backstage/blob/0cd632560246c37aa55699efe83445afe0eb1420/packages/cli/src/lib/bundler/transforms.ts#L35-L50

### What does the proposed API of configuration look like?

Align with `style-loader`.

**Comment by JSerFeng** [comment]
We should align builtin CSS behavior with Webpack. you can use css-loader and style-loader in Rspack

**Comment by JounQin** [comment]
> We should align builtin CSS behavior with Webpack. you can use css-loader and style-loader in Rspack

Yeah, I'm using `style-loader` now.

**Comment by JSerFeng** [comment]
Yes, If it's implemented by webpack builtin-in, we will align this
