### ISSUE TITLE
[Bug]: eval-source-map doesn't work

### ISSUE THREAD

**Issue by tjx666** [web-infra-dev/rspack#5639]
### System Info

```node
System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M2
  Memory: 795.52 MB / 24.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.11.0 - ~/Library/Caches/fnm_multishells/3269_1707315445505/bin/node
  Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/3269_1707315445505/bin/yarn
  npm: 10.4.0 - ~/Library/Caches/fnm_multishells/3269_1707315445505/bin/npm
  pnpm: 8.15.1 - ~/Library/Caches/fnm_multishells/3269_1707315445505/bin/pnpm
  bun: 1.0.26 - /opt/homebrew/bin/bun
Browsers:
  Chrome: 121.0.6167.160
  Edge: 121.0.2277.106
  Safari: 17.3
npmPackages:
  @rspack/cli: ^0.5.3 => 0.5.3 
  @rspack/core: ^0.5.3 => 0.5.3 
  @rspack/plugin-react-refresh: ^0.5.3 => 0.5.3 
```

### Details

<img width="1433" alt="image" src="https://github.com/web-infra-dev/rspack/assets/41773861/0e259d09-5c22-473f-a7e8-647daf49183d">

### Reproduce link

https://github.com/tjx666/react-rspack-boilerplate

### Reproduce Steps

1. git clone git@github.com:tjx666/react-rspack-boilerplate.git
2. git checkout 4bc5c7166973d3a811ad5927953e2901fe745972
3. pnpm install
4. pnpm dev
5. open chrome devtools to check the source

**Comment by ahabhgk** [comment]
Should been fixed by https://github.com/web-infra-dev/rspack/pull/5717

**Comment by ahabhgk** [comment]
Today or tomorrow will release it in 0.5.5
