### ISSUE TITLE
[Feature]: add support for generator.dataUrl as a function in loader config

### ISSUE THREAD

**Issue by SkReD** [web-infra-dev/rspack#5640]
### What problem does this feature solve?

Allow to generate more optimized base64 representation of svg. Used like so
```typescript
import svgToMiniDataURI from 'mini-svg-data-uri'

{
    test: /\.svg$/,
    issuer: /\.css$/,
    type: 'asset',
    parser: {
      dataUrlCondition: {
        maxSize: 2048,
      },
    },
    generator: {
      dataUrl: (content: string) => svgToMiniDataURI(content),
    },
  },
}  
```

### What does the proposed API of configuration look like?

https://webpack.js.org/configuration/module/#rulegeneratordataurl

**Comment by luhc228** [comment]
Can I have a try?

**Comment by hardfist** [comment]
@luhc228  thanks in advance
/assign @luhc228
