### ISSUE TITLE
[Feature]: Expose ChunkGraph APIs, compilation.chunkGroups 

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5641]
### What problem does this feature solve?

Many plugins in our application use the chunkGraphAPIs and compilation.chunkGroups with webpack which are currently not exposed by rspack. 

### What does the proposed API of configuration look like?

https://github.com/webpack/webpack/blob/a16909c5fd/lib/ChunkGraph.js#L474

https://github.com/webpack/webpack/blob/51f0f0aeac072f989f8d40247f6c23a1995c5c37/lib/Compilation.js#L999

**Comment by h-a-n-a** [comment]
We are not going to expose internal graph to the Rust side as it is too complicated. The possible way to do this in the future is to use the rust plugin.
