### ISSUE TITLE
[Bug]: react-refresh not working when i use observer hoc，and works fine if i remove observer or put it inside function component file.

### ISSUE THREAD

**Issue by ssehacker** [web-infra-dev/rspack#5655]
### System Info

System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 102.83 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Firefox Nightly: 120.0a1
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.5.4 => 0.5.4 
    @rspack/core: ^0.5.4 => 0.5.4 
    @rspack/plugin-react-refresh: 0.5.4 => 0.5.4 

### Details

version1: not working:
<img width="747" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4142097/6c67a09e-8df6-4e41-be18-d10604d3ead8">
<img width="636" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4142097/e88f2907-997c-4a9e-89d3-2c33ffbbb096">

version2: works fine:
<img width="864" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4142097/b69a80ad-b796-412e-8dd7-bdabdc76d00b">
<img width="804" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4142097/0d262bb8-65d7-4f74-ab91-6a90f8565075">

### Reproduce Steps

1. Create project as rspack website description:
``` shell
npm create rspack@latest
```
2. update `main.tsx`  and  `App.tsx` like screenshot
3. run `npm run dev`
4. edit `App.tsx` and save it. Then you can see version1 doesn't work， But version2 works well。

I found a related issue [here](https://github.com/facebook/react/issues/20417), But  react fast refresh still  not work even if my version of react-refresh is `react-refresh@0.14.0`.

Thank you for your help.

**Comment by LingyuCoder** [comment]
After replacing with webpack, the same issue still exists, and it seems that the component of hot-update.js is being generated correctly.

It appears to be an issue with mobx-react and react refresh. Perhaps need to report this to mobx-react and react-refresh
