### ISSUE TITLE
[Bug]: "asset/resource"  module used to handle ".lottie"-animations works in dev-mode but breaks animation-file in production mode 

### ISSUE THREAD

**Issue by fredrik-lindqvist** [web-infra-dev/rspack#5656]
### System Info

System:
OS: macOS 14.2.1,
CPU: Apple M2 pro
Memory: 16gb
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0
npm: 10.2.3
Browsers:
Chrome 121.0.6167.160
Safari 17.2.1
npmPackages:
@rspack/cli: 0.5.4
@rspack/core:  0.5.4
@dotlottie/player-component: 1.3.2
react: 18.2.0
react-dom: 18.2.0

### Details

To handle import of animations (".lottie"-files ) in my app i use builtin "asset/resource" module. This works great in development mode and all animations are imported correctly. However when I switch to production mode, all imported animations break and can not be loaded correctly. If i switch to webpack 5 (version 5.89.0) all files are loaded correctly in both production and development mode. 

### Reproduce Steps

1. setup "asset/resource" to handle ".lottie" files  in rspack.config
2. set mode to "production" in rspack.config
3. import a ".dotlottie"-file to dot-lottie-player from @dotlottie/player-component
5.  animation wont work
6. switch to development mode in  rspack.config
7. animation will work

**Comment by fredrik-lindqvist** [comment]
just downgraded to version 0.5.1 for @rspack/cli and @rspack/core: and then all dotLottie-animations work great in dev and production mode. Also tried version 0.5.2 and then the files break in production. Seems that the files loses their mimetype.

**Comment by magic-akari** [comment]
Same issue.

I attempted to address the issue by replacing the JSON path loading method with an inline JSON object([animationData](https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#path-or-animationdatamandatory-at-least-one)), but the problem persisted. Therefore, I speculate that this issue is unrelated to the assets loader.

**Comment by magic-akari** [comment]
Here is a minimal reproduction.
[rspack-lottie-1.0.0.tgz](https://github.com/web-infra-dev/rspack/files/14341358/rspack-lottie-1.0.0.tgz)

**Comment by fredrik-lindqvist** [comment]
@magic-akari thanks for the repo. @h-a-n-a  see comment above.

**Comment by xc2** [comment]
thanks @magic-akari

it's swc_ecma_minifier related bug, i've created an issue for this case, please help with it

https://github.com/swc-project/swc/issues/8651
