### ISSUE TITLE
[Bug]: HMR compilation get failed when config both `newTreeshaking` and `importSource` of swc loader

### ISSUE THREAD

**Issue by ClarkXia** [web-infra-dev/rspack#5659]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.44 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Chrome Canary: 123.0.6305.2
    Safari: 16.3
  npmPackages:
    @rspack/cli: 0.5.4 => 0.5.4 
    @rspack/core: 0.5.4 => 0.5.4

### Details

When both configure `importSource` of swc-loader options and `newTreeshaking`, compiler will throw error when source code is changed.
![image](https://github.com/web-infra-dev/rspack/assets/4219965/5bb677d2-764d-4b82-8660-cfe5701bf059)

![image](https://github.com/web-infra-dev/rspack/assets/4219965/0d1665f6-210f-4cfc-8550-85ccf3868bdd)

### Reproduce link

https://github.com/ClarkXia/rspack-issue/tree/master/react

### Reproduce Steps

1. run `npm run dev`
2. change source code to trigger HMR compile
3. `should have connection` error will occur in terminal

**Comment by IWANABETHATGUY** [comment]
try nightly

**Comment by IWANABETHATGUY** [comment]
I can't reproduce in latest **0.5.6**, you could reopen if you have any further issues.
