### ISSUE TITLE
[Bug]: antd  DatePicker  error

### ISSUE THREAD

**Issue by changchuncun** [web-infra-dev/rspack#5695]
### System Info

System:
OS: macOS Mojave 10.14.6
CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Memory: 236.47 MB / 16.00 GB
Shell: 5.3 - /bin/zsh
Binaries:
Node: 16.16.0 - /usr/local/bin/node
Yarn: 1.22.18 - /usr/local/bin/yarn
npm: 6.14.15 - /usr/local/bin/npm
Browsers:
Chrome: 116.0.5845.187
Edge: 114.0.1823.67
Safari: 12.1.2
npmPackages:
@rspack/cli: ^0.5.4 => 0.5.4
@rspack/core: ^0.5.4 => 0.5.4
@rspack/plugin-node-polyfill: ^0.5.4 => 0.5.4
@rspack/plugin-react-refresh: ^0.5.4 => 0.5.4

### Details

ERROR
(0 , moment__WEBPACK_IMPORTED_MODULE_0__.default) is not a function
TypeError: (0 , moment__WEBPACK_IMPORTED_MODULE_0__.default) is not a function
    at Object.getNow (eval at ../node_modules/rc-picker/es/generate/moment.js (http://localhost:9999/vendors-node_modules_ant-design_icons_es_icons_ArrowLeftOutlined_js-node_modules_ant-design_i-dd7c3b.js:1:4444556), <anonymous>:9:67)
    at postState (eval at ../node_modules/rc-picker/es/PickerPanel.js (http://localhost:9999/vendors-node_modules_ant-design_icons_es_icons_ArrowLeftOutlined_js-node_modules_ant-design_i-dd7c3b.js:1:4275048), <anonymous>:99:38)
    at useMergedState (eval at ../node_modules/rc-util/es/hooks/useMergedState.js (http://localhost:9999/vendors-node_modules_ant-design_icons_es_icons_ArrowLeftOutlined_js-node_modules_ant-design_i-dd7c3b.js:1:6813457), <anonymous>:28:39)
    at PickerPanel (eval at ../node_modules/rc-picker/es/PickerPanel.js (http://localhost:9999/vendors-node_modules_ant-design_icons_es_icons_ArrowLeftOutlined_js-node_modules_ant-design_i-dd7c3b.js:1:4275048), <anonymous>:95:104)
    at renderWithHooks (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:11733:24)
    at mountIndeterminateComponent (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:14595:17)
    at beginWork (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:15625:24)
    at HTMLUnknownElement.callCallback (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:3274:22)
    at Object.invokeGuardedCallbackDev (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:3308:22)
    at invokeGuardedCallback (eval at ../node_modules/react-dom/cjs/react-dom.development.js (http://localhost:9999/chunk-react.js:1:21078), <anonymous>:3355:37)

### Reproduce Steps

yarn dev

**Comment by changchuncun** [comment]
index.js

import React, { PureComponent } from 'react';
import ReactDOM from 'react-dom/client';
import { Row, Col, DatePicker } from 'antd';

const RootDom = document.getElementById('root');

ReactDOM.createRoot(RootDom).render(
    <div>
        <DatePicker
            style={{ width: 200 }}
            placeholder="日期"
            inputReadOnly={true}
            format={'YYYYMMDD'}
            suffixIcon={null}
        />
    </div>
);


dev.config.js

/**
 *
 */
const path = require('path');
const dayjs = require('dayjs');
const current_min = dayjs().format('YYYYMMDDHHmm');
const rspack = require('@rspack/core');

const SRC_DIR = path.join(__dirname, '../src');
const DIST_DIR = path.join(__dirname, '../dist');

//
const NODE_ENV = process.env.NODE_ENV;
//
const APP_ENV = process.env.APP_ENV;
const APP_NAME = process.env.APP_NAME;

const ReactRefreshPlugin = require('@rspack/plugin-react-refresh');

module.exports = {
    //target: 'web',
    mode: 'development',
    devtool: 'eval-cheap-source-map',
    stats: {
        preset: 'errors-only',
        reasons: true,
    },
    context: SRC_DIR,
    devServer: {
        port: 9999,
        hot: true,
        historyApiFallback: true,
    },
    entry: {
        app: './index.js',
    },
    output: {
        publicPath: '/',
        path: DIST_DIR,
        filename: '[name].js',
        chunkFilename: '[name].js',
    },
    resolve: {
        preferRelative: true,
        extensions: ['.js', '.jsx', '.json', '.less', '.css'],
        alias: {
            '@base': path.join(SRC_DIR, `base`),
            '@assets': path.join(SRC_DIR, `assets`),
            '@less': path.join(SRC_DIR, 'less'),
            '@components': path.join(SRC_DIR, 'components'),
            '@utils': path.join(SRC_DIR, 'utils'),
            '@store': path.join(SRC_DIR, 'store'),
            '@views': path.join(SRC_DIR, 'views'),
            '@config': path.join(SRC_DIR, 'config'),
        },
    },
    optimization: {
        splitChunks: {
            chunks: 'all',
            // minSize: 50000,
            // minChunks: 3,
            cacheGroups: {
                react: {
                    name: 'chunk-react',
                    test: /[\\/]node_modules[\\/]_?react(.*)/,
                    priority: 100,
                },
                antd: {
                    name: 'chunk-antd',
                    priority: 80,
                    test: /[\\/]node_modules[\\/]_?antd(.*)/,
                },
                utils: {
                    name: 'chunk-utils',
                    priority: 60,
                    test: /[\\/]src[\\/]_?utils(.*)/,
                },
                commons: {
                    // split async commons chunk
                    name: 'chunk-commons',
                    minChunks: 4,
                    priority: 40,
                    chunks: 'async',
                },
            },
        },
    },
    module: {
        rules: [
            {
                test: /\.[jt]sx?$/,
                type: 'javascript/auto',
                exclude: /[\\/]node_modules[\\/]/,
                use: {
                    loader: 'builtin:swc-loader',
                    options: {
                        sourceMap: true,
                        jsc: {
                            parser: {
                                syntax: 'typescript',
                                tsx: true,
                                decorators: true,
                            },
                            transform: {
                                legacyDecorator: true,
                                react: {
                                    runtime: 'automatic',
                                    pragma: 'React.createElement',
                                    pragmaFrag: 'React.Fragment',
                                    throwIfNamespace: true,
                                    development: true,
                                    useBuiltins: false,
                                },
                            },
                            target: 'es5',
                        },
                        rspackExperiments: {
                            emotion: true,
                        },
                    },
                },
            },
            {
                // .css 解析
                test: /\.css$/,
                use: ['style-loader', 'css-loader', 'postcss-loader'],
            },
            {
                // .less 解析
                test: /\.less$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                    {
                        loader: 'less-loader',
                        options: { lessOptions: { javascriptEnabled: true } },
                    },
                ],
            },
            {
                test: /\.(png|jpg|jpeg|gif|svg)$/i,
                type: 'asset',
                parser: {
                    dataUrlCondition: {
                        // 小于等于 4kb，且以 `.png` 结尾的模块将被 Base64 编码
                        maxSize: 8192,
                    },
                },
                generator: {
                    filename: 'assets/imgs/[name].[hash:4].[ext]',
                },
            },
        ],
    },
    plugins: [
        new ReactRefreshPlugin(),
        new rspack.ProgressPlugin(),
        //new rspack.HotModuleReplacementPlugin(),
        new rspack.SwcJsMinimizerRspackPlugin({
            extractComments: true,
        }),
        new rspack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(NODE_ENV),
        }),
        new rspack.CopyRspackPlugin({
            patterns: [
                {
                    from: path.join(SRC_DIR, `./assets`),
                    to: path.join(DIST_DIR, './assets'),
                },
            ],
        }),
        new rspack.HtmlRspackPlugin({
            templateParameters: { version: current_min },
            template: `./config/temp/web.ejs`,
            filename: './index.html', //生成的html存放路径，相对于 output.path
            inject: 'head',
            //hash: true,
            chunks: ['app'],
        }),
    ],
};

package.json

{
    "name": "li-web",
    "private": true,
    "version": "0.0.1",
    "scripts": {
        "build": "rimraf dist && rspack build -c ./rspack/prod.config.js",
        "kline": "cross-env NODE_ENV=development APP_ENV=test rspack serve -c ./rspack/kline.config.js",
        "dev": "cross-env NODE_ENV=development APP_ENV=test rspack serve -c ./rspack/dev.config.js",
        "test": "cross-env NODE_ENV=development APP_ENV=test rspack serve -c ./rspack/dev.config.js",
        "prod": "cross-env NODE_ENV=development APP_ENV=pre rspack serve -c ./rspack/dev.config.js"
    },
    "dependencies": {
        "@rematch/core": "^2.2.0",
        "antd": "^4.24.12",
        "axios": "^0.27.2",
        "bignumber.js": "^9.0.1",
        "classnames": "^2.3.1",
        "dayjs": "^1.8.33",
        "js-cookie": "^3.0.1",
        "prop-types": "^15.7.2",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-loadable": "^5.5.0",
        "react-redux": "^8.0.2",
        "react-router-dom": "^6.3.0",
        "redux": "^4.2.0"
    },
    "devDependencies": {
        "@rspack/cli": "^0.5.4",
        "@rspack/core": "^0.5.4",
        "@rspack/plugin-node-polyfill": "^0.5.4",
        "@rspack/plugin-react-refresh": "^0.5.4",
        "@types/react": "^18.0.25",
        "@types/react-dom": "^18.0.8",
        "autoprefixer": "^8.0.0",
        "cross-env": "^7.0.3",
        "eslint": "^7.4.0",
        "eslint-loader": "^4.0.2",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-react": "^7.20.3",
        "eslint-plugin-react-hooks": "^4.0.8",
        "gulp": "^4.0.2",
        "prettier": "2.0.5",
        "rimraf": "^3.0.2",
        "react-refresh": "0.14.0",
        "less": "^3.12.2",
        "less-loader": "^6.2.0",
        "postcss-loader": "^3.0.0",
        "style-loader": "1.2.1",
        "style-resources-loader": "^1.3.3",
        "css-loader": "^3.6.0",
        "url-loader": "^4.1.0"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "description": ""
}

**Comment by changchuncun** [comment]
all files

**Comment by xc2** [comment]
@changchuncun 你好，因为你配置了 resolve.preferRelative 所以有些地方比如 `rc-picker/es/generate/moment` 里面的 `import "moment"` 会优先当前目录下的 moment.js ，导致循环依赖，所以找不到 moment 了。

把 preferRelative 关掉就好了
