### ISSUE TITLE
[Bug]: How to add an asset to a chunk?

### ISSUE THREAD

**Issue by karl93572** [web-infra-dev/rspack#5725]
### System Info

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  npmPackages:
    @rspack/core: ^0.5.4 => 0.5.4 
    @rspack/dev-server: ^0.5.4 => 0.5.4 
    @rspack/plugin-react-refresh: ^0.5.4 => 0.5.4 

### Details

I'm writing a custom plugin to create new css file asset (based on each css file asset in chunk.files) using hooks like compilation.hooks.processAssets.

It's ok to use compilation.emitAsset to create an asset.
But how can i add the asset to the chunk?
In webpack, i can write "chunk.files.add(newAsset)"
In Rspack, chunk is stored in rust, it cannot be modified in javascript.

### Reproduce Steps

compilation.emitAsset(newFile, newFileResource);
chunk.files.push(newFile)

**Comment by xc2** [comment]
duplicated with #5631, please follow up that one.
