### ISSUE TITLE
[Bug]: Rspack build stuck if using splitChunks.maxSize and import CSS

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5734]
### System Info

  System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.73 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/yarn
    npm: 10.2.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/npm
    pnpm: 8.15.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 16.6
  npmPackages:
    @rspack/cli: 0.5.4 => 0.5.4
    @rspack/core: 0.5.4 => 0.5.4

### Details

Rspack build paused when settting minSize/maxSize in splitChunks and import CSS:

```js
const config = {
  mode: "production",
  optimization: {
    splitChunks: {
      chunks: 'all',
      cacheGroups: {},
      minSize: 10 * 1000,
      maxSize: 50 * 1000
    }
  },
  experiments: {
    css: true,
  },
};
```

- Webpack succeed:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/60d32b89-2aeb-4d9f-8327-901b4b1994da)

- Rspack stuck:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/705d1f60-72fe-4303-8ece-c9ea7fa11d18)

- Rsbuild stuck:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/38597bbc-7d3d-45d0-8dd5-71ebbf562083)

### Reproduce link

https://github.com/chenjiahan/rsbuild-repo-split-by-size

### Reproduce Steps

1. git clone git@github.com:chenjiahan/rsbuild-repo-split-by-size.git
2. pnpm i
3. pnpm build:rspack

**Comment by JSerFeng** [comment]
Should be fixed by #5700
