### ISSUE TITLE
[Feature]: Support native ESM loader

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5735]
### What problem does this feature solve?

This allows using a native ESM loader `loader.js` with `"type": "module"` in `package.json` (which webpack supports, see: https://github.com/webpack/webpack/tree/main/test/cases/loaders/_esm-loader-type).

## Use case

I'm developing a rspack plugin with loader and `"type": "module"` in `package.json`. I have to run `cp lib/loader.js lib/loader.mjs` after every build to make it work with rspack. And the `tsc --watch` I used to build the whole project cannot do that for me(it also does not support output `.mjs` files).

### What does the proposed API of configuration look like?

```js
// loader.js
/** @type {import('webpack').LoaderDefinitionFunction} */
export default function loader() {
  return /** content */
}
```

Pitching loader:

```js
// loader.js
/** @type {import('webpack').PitchLoaderDefinitionFunction} */
export const pitch = function() {
  return /** content */
}
```

**Comment by colinaaa** [comment]
I found a workaround by creating a `loader.cjs` with:

```js
const loader = require('./lib/loader.js')

module.exports = loader.default
module.exports.pitch = loader.pitch
```

But it would be nice for rspack to have native ESM support.

**Comment by h-a-n-a** [comment]
This is on our roadmap. Stay tuned ;-) You may use `.mjs` wrapper for now.

**Comment by hardfist** [comment]
@h-a-n-a is it fixed now?

**Comment by h-a-n-a** [comment]
> @h-a-n-a is it fixed now?

Not yet supported
