### ISSUE TITLE
[Bug]: reading assets in the plugin takes a long time

### ISSUE THREAD

**Issue by liangyuetian** [web-infra-dev/rspack#5758]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 217.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.4.3 => 0.4.3 
    @rsbuild/plugin-vue: ^0.4.3 => 0.4.3
```

### Details

```js
compiler.hooks.compilation.tap("RsBuildPlugin1", (compilation) => {
            compilation.hooks.processAssets.tap(
                {
                    name: 'MyPlugin',
                    stage: webpack.Compilation.PROCESS_ASSETS_STAGE_DERIVED, // see below for more stages
                },
                (assets) => {

                    const t1 = collectTime(() => {
                        const length = Object.entries(assets).length
                        return length
                    })
                    console.log(`1. count: ${t1[1]}; time: ${t1[0]}ms`)
                    const t2 = collectTime(() => {
                        const length = Object.entries(assets).length
                        return length
                    })
                    console.log(`2. count: ${t2[1]}; time: ${t2[0]}ms`)

                })
        })

```

<img width="356" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22701373/064309fc-92a1-41a5-97bc-27f939c4dc3a">

### Reproduce link

https://github.com/liangyuetian/rsbuild-hmr-slow-demo/blob/webpack_assets_long_time/rspack.plugin1.js#L24

### Reproduce Steps

1. git checkout -b webpack_assets_long_time
2. npm run dev

**Comment by xc2** [comment]
In my computer (m2 max mac studio), it takes 14ms every time to access `assets.x` when `x` is a js asset.

@h-a-n-a 

Whenever I access `assets.x`, it always involves retrieving the source of `x` from the rust side.

I believe this step is necessary because `assets.x` is being synchronized for read and write operations with the rust side before the `processAssets` and `afterProcessAssets` hooks are completed.

Therefore, I don't think rspack can improve the performance in this case at the moment, correct?

**Comment by h-a-n-a** [comment]
> In my computer (m2 max mac studio), it takes 14ms every time to access `assets.x` when `x` is a js asset.
> 
> @h-a-n-a
> 
> Whenever I access `assets.x`, it always involves retrieving the source of `x` from the rust side.
> 
> I believe this step is necessary because `assets.x` is being synchronized for read and write operations with the rust side before the `processAssets` and `afterProcessAssets` hooks are completed.
> 
> Therefore, I don't think rspack can improve the performance in this case at the moment, correct?

@xc2 

Currently, we try to mitigate the performance by using a thin proxy layer on `compilation.assets`, which is also the parameter of the hooks that've been mentioned above. So that means it's an on-demand FFI communication and it contains converting Rust struct into Node-API compatible way, and passing it to node, then recreate a `webpack-source` compatible `Source` struct.

When retrieving assets source from Rust, the recommended way is, if you know the exact name of it, to access with the name of the asset. For example, use `assets.x`. The communication between Rust and Node side is necessary considering if there's some changes made to this asset before reading this again.

**Comment by liangyuetian** [comment]
> > In my computer (m2 max mac studio), it takes 14ms every time to access `assets.x` when `x` is a js asset.
> > @h-a-n-a
> > Whenever I access `assets.x`, it always involves retrieving the source of `x` from the rust side.
> > I believe this step is necessary because `assets.x` is being synchronized for read and write operations with the rust side before the `processAssets` and `afterProcessAssets` hooks are completed.
> > Therefore, I don't think rspack can improve the performance in this case at the moment, correct?
> 
> @xc2
> 
> Currently, we try to mitigate the performance impact by using a thin proxy layer on `compilation.assets`, which is also the parameter of the hooks that've been mentioned above. So that means it's an on-demand FFI communication and it contains converting Rust struct into Node-API compatible way, and passing it to node, then recreate a `webpack-source` compatible `Source` struct.
> 
> When retrieving assets source from Rust, the recommended way is, if you know the exact name of it, to access with the name of the asset. For example, use `assets.x`, this only passes `Source` of `x` to JS. Also to note, the communication between Rust and Node side is necessary considering if there's some changes made to this asset before reading this again.
> 
> `Object.entries(assets)` is not recommended. This will pass every `filename` and `source` to JS side.

The time consumption of a single `FFI `+ `Node-API `+ `webpack source` is also not short

In demo project
https://github.com/liangyuetian/rsbuild-hmr-slow-demo/blob/webpack_assets_long_time/rspack.plugin1.js#L30
<img width="218" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22701373/efe9c45f-c88e-4b4e-b016-14b9c1b8bd20">


In real projects
<img width="524" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22701373/9a669366-30af-4029-9172-7b69fe87f3cb">

**Comment by h-a-n-a** [comment]
bump

**Comment by h-a-n-a** [comment]
> > > In my computer (m2 max mac studio), it takes 14ms every time to access `assets.x` when `x` is a js asset.
> > > @h-a-n-a
> > > Whenever I access `assets.x`, it always involves retrieving the source of `x` from the rust side.
> > > I believe this step is necessary because `assets.x` is being synchronized for read and write operations with the rust side before the `processAssets` and `afterProcessAssets` hooks are completed.
> > > Therefore, I don't think rspack can improve the performance in this case at the moment, correct?
> > 
> > 
> > @xc2
> > Currently, we try to mitigate the performance impact by using a thin proxy layer on `compilation.assets`, which is also the parameter of the hooks that've been mentioned above. So that means it's an on-demand FFI communication and it contains converting Rust struct into Node-API compatible way, and passing it to node, then recreate a `webpack-source` compatible `Source` struct.
> > When retrieving assets source from Rust, the recommended way is, if you know the exact name of it, to access with the name of the asset. For example, use `assets.x`, this only passes `Source` of `x` to JS. Also to note, the communication between Rust and Node side is necessary considering if there's some changes made to this asset before reading this again.
> > `Object.entries(assets)` is not recommended. This will pass every `filename` and `source` to JS side.
> 
> The time consumption of a single `FFI `+ `Node-API `+ `webpack source` is also not short
> 
> In demo project https://github.com/liangyuetian/rsbuild-hmr-slow-demo/blob/webpack_assets_long_time/rspack.plugin1.js#L30 <img alt="image" width="218" src="https://private-user-images.githubusercontent.com/22701373/307308015-efe9c45f-c88e-4b4e-b016-14b9c1b8bd20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc2NzEsIm5iZiI6MTcxNDAyNzM3MSwicGF0aCI6Ii8yMjcwMTM3My8zMDczMDgwMTUtZWZlOWM0NWYtYzg4ZS00YjRlLWIwMTYtMTRiOWMxYjhiZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYjgzY2ZmZjcxYjNmNjE2NmQxMGNkMmYzMjZiMDkxYWExNDQ0NDZhMDA5ODRiMjBmMjUyMTIyMWNmMTRiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jM872UpYH4bc_30r6D3Lo0WirK-k_-YItOjQAwgieQY">
> 
> In real projects <img alt="image" width="524" src="https://private-user-images.githubusercontent.com/22701373/307307498-9a669366-30af-4029-9172-7b69fe87f3cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjc2NzEsIm5iZiI6MTcxNDAyNzM3MSwicGF0aCI6Ii8yMjcwMTM3My8zMDczMDc0OTgtOWE2NjkzNjYtMzBhZi00MDI5LTkxNzItN2I2OWZlODdmM2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2NDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMDcwM2E5NmIwOWE3OTI4Zjk0NjI0MTQ0NGI3MmZmOWNjYWE1MGJkNzdlYzY2Yjk0ZDYxZjgyYjhjNDk3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1-AemV5hF8XEmFf1o5_BiVW5Mg_AlvdiLACI_SQmVg">

@liangyuetian  It would be nice to provide your real-world example to see if there's anything else we can do. The solution could be enqueue the changes in the same tick and flush them all at once. Feel free to ping me.

**Comment by hardfist** [comment]
close for stale, you can reopen or open a new issue for this
