### ISSUE TITLE
[Bug]: 升级到 v0.4.5 本地运行正常，线上运行报错 

### ISSUE THREAD

**Issue by iwtem** [web-infra-dev/rspack#5760]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 8.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.57
    Safari: 17.2.1
```

### Details

本地开发均正常，升级到测试环境会有报错，部分页面显示正常，正常的应该是未加载下面的这个文件。

![image](https://github.com/web-infra-dev/rsbuild/assets/76606053/039741e4-6cfc-4472-8eef-af2bfa7a4da1)

### Reproduce link

[CodeSandbox 复现链接](https://codesandbox.io/p/devbox/rsbuild-demo-lghkqk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltcu93vi00063b6lgn66cwwj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltcu93vi00023b6lrmwry4tx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltcu93vi00043b6l0sugocnb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltcu93vi00053b6le2n0qiet%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltcu93vi00023b6lrmwry4tx%2522%253A%257B%2522id%2522%253A%2522cltcu93vi00023b6lrmwry4tx%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltcu93vi00053b6le2n0qiet%2522%253A%257B%2522id%2522%253A%2522cltcu93vi00053b6le2n0qiet%2522%252C%2522activeTabId%2522%253A%2522cltcuixk600gx3b6lifu5ykxf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A8080%252C%2522id%2522%253A%2522cltcuixk600gx3b6lifu5ykxf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltcu93vi00043b6l0sugocnb%2522%253A%257B%2522id%2522%253A%2522cltcu93vi00043b6l0sugocnb%2522%252C%2522activeTabId%2522%253A%2522cltcuhxz700e53b6ld5qhmx4c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltcu93vi00033b6lx0gec2cd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522cltcuhxz700e53b6ld5qhmx4c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltcuhy7v000qd7a9bue04diu%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduce Steps

如果在项目中引用 `slate-history` 这个包，就会出现本地开发正常，打包部署错误的问题

使用 rsbuild dev 运行正常

使用 rsbuild preview 报错

<img width="557" alt="image" src="https://github.com/web-infra-dev/rspack/assets/76606053/134fb8e0-4bd1-4e0e-8d46-dc3cbc7a292b">

**Comment by chenjiahan** [comment]
我先 transfer issue 到 Rspack 仓库来跟进

**Comment by iwtem** [comment]
复现链接及步骤如上。

看了下打包后的产物：
![image](https://github.com/web-infra-dev/rspack/assets/76606053/a7e80fa9-8a1d-43f2-a55e-602e70ba1330)

源代码：
<img width="280" alt="image" src="https://github.com/web-infra-dev/rspack/assets/76606053/6bd10867-9220-45db-b892-70405c0a7c79">

![image](https://github.com/web-infra-dev/rspack/assets/76606053/574c94ed-03d7-4043-9a1f-fbee4e760941)

这是 slate-history 地址：https://github.com/ianstormtaylor/slate/tree/main/packages/slate-history

**Comment by xc2** [comment]
minimal reproducing: https://github.com/xc2/issue-5760

**Comment by xc2** [comment]
@iwtem @martijn-veenstra and everyone who searched for this problem, here is a workaround:

try any of minify options below:

1. `{ compress: { passes: 2 } }`
2. `{ compress: { hoist_props: false } }`
3. `{ mange: false }`

here's guides to set minify options:

- for rsbuild: https://rsbuild.dev/config/output/minify
- for rspack: https://www.rspack.dev/config/plugins.html#swcjsminimizerrspackplugin

---

it is an upstream bug and can be skip by options.

it is confirmed that swc has been fix this bug https://github.com/swc-project/swc/pull/8593.

rspack needs to bump swc_ecma_minifier to fix it.

**Comment by iwtem** [comment]
> 2\. hoist_props: false
