### ISSUE TITLE
[Feature]: SWC plugins support

### ISSUE THREAD

**Issue by intpp** [web-infra-dev/rspack#5763]
### What problem does this feature solve?

Additional abilities

In my case, to migrate to rspack/rsbuild I need the plugin for SWC - https://github.com/intpp/swc-plugin-jsx-control-statements

### What does the proposed API of configuration look like?

https://github.com/web-infra-dev/rspack/blob/30570575c2eb1af99144fb3a83fa6f30469bb954/crates/rspack_loader_swc/src/lib.rs#L74

It could be used as is and set through Plugin API `modifyRspackConfig`.

**Comment by h-a-n-a** [comment]
PR welcome ;-)
