### ISSUE TITLE
[Bug]: HtmlPlugin conflicts with EslintPlugin options "threads"

### ISSUE THREAD

**Issue by liangyuetian** [web-infra-dev/rspack#5771]
### System Info

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 62.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @rspack/cli: ^0.5.4 => 0.5.4 
    @rspack/core: ^0.5.4 => 0.5.4 

### Details

`HtmlPlugin` conflicts with the `threads` options of `EslintPlugin`

<img width="732" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22701373/5ba484c3-d621-4c99-b434-6d689e22209c">

### Reproduce link

https://github.com/liangyuetian/rsbuild-hmr-slow-demo/blob/htmlPlugin-eslintPlugin/rsbuild.config.ts#L41

### Reproduce Steps

1. pnpm install
2. npm run dev

**Comment by LingyuCoder** [comment]
I can't understand what exactly the "conflict" means. Please describe your expected behavior and the problems you encounter in more detail.

**Comment by liangyuetian** [comment]
> I can't understand what exactly the "conflict" means. Please describe your expected behavior and the problems you encounter in more detail.

sorry，I didn't describe it clearly

in htmlPlugin, it is not equal to false and EslintPlugin options When threads coexist, the second compilation will get stuck，as shown in the above figure

**Comment by LingyuCoder** [comment]
seems that there is some bug in jest-worker which used in eslint-webpack-plugin. The javascript main thread keep running in this line https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/src/getESLint.js#L73, but the lintFiles in worker.js does not been called. Perhaps you can report this to jest-worker or eslint-webpack-plugin for help.

**Comment by chenjiahan** [comment]
does webpack has this issue?

**Comment by LingyuCoder** [comment]
> does webpack has this issue?

I meet the same issue while using webpack-provider

**Comment by hardfist** [comment]
closed since it seems not a rspack bug, feel free to open if you have further question
