### ISSUE TITLE
[Bug]: webpackChunkName doesn't work on template strings

### ISSUE THREAD

**Issue by glenjamin** [web-infra-dev/rspack#5775]
### System Info

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (3) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 2.91 GB / 5.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.8.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.18.0 - /usr/bin/npm
  Browsers:
    Chrome: 117.0.5938.132
  npmPackages:
    @rspack/cli: ^0.5.4 => 0.5.4
    @rspack/core: ^0.5.4 => 0.5.4

### Details

When specifying the import filename using a template string (with no interpolation), `webpackChunkName` doesn't take effect.

eg. this works
```
import(/* webpackChunkName: "topojson" */ 'vendors/topojson'),
```
but this doesn't
```
import(/* webpackChunkName: "topojson" */ `vendors/topojson`),
```

Obviously the workaround is quite simple - but this was pretty surprising!

### Reproduce Steps

As noted above, use an import like this
```
import(/* webpackChunkName: "topojson" */ `vendors/topojson`),
```

The chunk should be named, but instead it just gets a default ID

**Comment by xc2** [comment]
<img width="1715" alt="image" src="https://github.com/web-infra-dev/rspack/assets/18117084/7bab0b8c-b780-4b69-b823-636e9c2ec6c4">

attempted to reproduce the issue with no luck. would you please provide a reproduce repo?

**Comment by xc2** [comment]
oh, the template string statement might be transformed by loaders. let me check

**Comment by LingyuCoder** [comment]
> oh, the template string statement might be transformed by loaders. let me check
> 
> **Update** no reproduction need anymore
> 
> the root cause is `builtin:swc-loader` transforming
> 
> ```js
> import(/* webpackChunkName: "issue-5775" */ `./a`);
> ```
> 
> into
> 
> ```js
> import("./a");
> ```
> 
> while
> 
> ```js
> import(/* webpackChunkName: "issue-5775" */ "./a");
> ```
> 
> into
> 
> ```js
> import(/* webpackChunkName: "issue-5775" */ "./a");
> ```

You are right, test this case without any loader, it just works

**Comment by LingyuCoder** [comment]
Using swc-loader meets the same issue and this can be resolved by setting `jsc.preserveAllComments = true`

```js
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: "builtin:swc-loader",
          options: {
            jsc: {
              preserveAllComments: true,
            }
          }
        }
      }
    ]
  },
```
