### ISSUE TITLE
[Bug]: Panic occurred when recompile/ reloading

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5794]
### System Info

  System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 47.35 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.23.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Edge: 122.0.2365.59
    Safari: 17.3.1
  npmPackages:
    @rspack/cli: 0.5.4 => 0.5.4 
    @rspack/core: 0.5.4 => 0.5.4 

### Details

So I am running an app in serve mode. The app boots up fine but when I make a change in one of the files and hit save, I run into the below panic.  Also tried setting the env RUST_BACKTRACE=full for more verbose error info, but it doesn't output anything more.

![image](https://github.com/web-infra-dev/rspack/assets/93791633/cce78bc3-952c-4639-9da1-775b4bf57f66)

### Reproduce Steps

1) start an app in serve mode
2) make a change in any of the components file and observe the above mentioned run time Panic

**Comment by IWANABETHATGUY** [comment]
Did you use newTreeshaking? try latest nightly or 0.5.5

**Comment by pushkargupta9807** [comment]
@IWANABETHATGUY yes I am using the newTreeshaking as below: 
    experiments: {
      rspackFuture: {
        newTreeshaking: true,
      },
    },

Shall try out the latest 0.5.5 and let you know, thanks!

**Comment by xc2** [comment]
@pushkargupta9807 did it work?

**Comment by LingyuCoder** [comment]
Cause no feedback for a long time, I will close this issue. If you encounter this issue again, please just reopen it.
