### ISSUE TITLE
[Tracking]: Stabilizing JS Hooks

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5821]
This issue tracks the interoperability of JS hooks between Rust and JS.

## Goals

**1. Correctness** JS hooks in v1.0 stable rspack should be fully tested. This includes arguments that passed to the JS side, and the return value passed back to the Rust side should also be included.

**2. Performance** Performance of JS hooks should be benchmarked, for example: `processAssets`.

**3. Deprecations** Hooks that are no longer supported in v1.0 well be kindly removed. This includes BREAKING CHANGES to the current codebase. This will be well-documented.

**4. Documentation** Documentation needs to be rewritten. For example, arguments with readonly fields will be marked as `Readonly<T>`. We will also add documentations to these fields to avoid mental burden. related: https://github.com/web-infra-dev/rspack-website/issues/629

## Tasks

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by hardfist** [comment]
close since this seems resolved
