### ISSUE TITLE
[Bug]: running into ReferenceError with latest 0.5.5v but not with 0.5.4

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5835]
### System Info

N/A

### Details

I see that the object (enum in this case) is exported as * from the lower level package and included in the main bundle for that file, as shown below:

        "../../core/auth/core-auth-types/index.ts": (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {
            "use strict";
            eval("__webpack_require__.r(__webpack_exports__);\n__webpack_require__.d(__webpack_exports__, {
......
......
.......|
\n  LogLevel: function() { return /* reexport safe */ _src_core_auth_interfaces__WEBPACK_IMPORTED_MODULE_4__.LogLevel; },\n  
........
/* harmony import */var _src_core_auth_interfaces__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./src/core-auth.interfaces */\"../../core/auth/core-auth-types/src/core-auth.interfaces.ts\");\n/*

The code that exports the LogLevel enum is in ./../core/auth/core-auth-types/index.ts
export * from "./src/core-auth.interfaces";

However, the code that imports this enum from the above file gets an undefined error, as shown below:

"LogLevel is not defined"
stack
: 
"ReferenceError: LogLevel is not defined\n    at Logger.initialize (eval at ../../services/utilities/services-utilities-authentication-users/src/logger/auth-logger.ts 

And auth-logger.ts simply does this:

import { LogLevel } from "@core-auth-types";

and its bundled code:

 "../..//src/logger/auth-logger.ts": (function(__unused_webpack_module, __webpack_exports__, __webpack_require__) {
            "use strict";
            eval("__webpack_require__.r(__webpack_exports__);\n__webpack_require__.d(__webpack_exports__, {\n  AuthLogger: function() { return AuthLogger; }\n});\n/* harmony import */var _core_auth_types__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @core-auth-types */\"../../core/auth/core-auth-types/src/core-auth.interfaces.ts\");

**Comment by xc2** [comment]
hard to reproduce without a repro repo.

looks like a recursive dependency issue

could you please check if all imported modules by `core/auth/core-auth-types/index.ts` have imported the`auth-logger.ts` module

**Comment by pushkargupta9807** [comment]
its the other way around - the auth-logger.ts is importing { LogLevel } from `core/auth/core-auth-types/index.ts`

**Comment by pushkargupta9807** [comment]
Any further tips/ suggestions I can try for this ? Thanks

**Comment by LingyuCoder** [comment]
Dependency analysis and tree shaking are quite complex. We can't locate the problem just by textual description. Can you provide a demo for reproducing the problem?
