### ISSUE TITLE
[Bug]: build error when using LimitChunkCountPlugin plugin

### ISSUE THREAD

**Issue by Lionad-Morotar** [web-infra-dev/rspack#5839]
### System Info

 System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13980HX
    Memory: 21.43 GB / 63.64 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\fnm_multishells\8128_1709479642558\node.EXE
    npm: 10.2.4 - ~\AppData\Local\fnm_multishells\8128_1709479642558\npm.CMD
    pnpm: 8.15.4 - G:\node_modules\v20.11.0\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.59), ChromiumDev (123.0.2420.10)
    Internet Explorer: 11.0.22621.1

### Details

![Clip_2024-03-03_23-48-50](https://github.com/web-infra-dev/rspack/assets/26913795/fdbe3d8b-ecab-4420-a99b-158443582784)

### Reproduce link

https://github.com/Lionad-Morotar/rspack-webpack-limit-chunk-counts-plugin-error-produce

### Reproduce Steps

1. pnpm install
2. pnpm build

**Comment by LingyuCoder** [comment]
The webpack.optimize.LimitChunkCountPlugin can not be used in rspack. This plugin has been native support in rspack, you can try to use `require("@rspack/core").optimize.LimitChunkCountPlugin` instead.
