### ISSUE TITLE
[Feature]: Configurable prefix for module ids, chunk ids

### ISSUE THREAD

**Issue by levshits** [web-infra-dev/rspack#5859]
### What problem does this feature solve?

In case if we are using RSBuild/RSPack to build microfrontend application with async modules we can get issues when the same id gets assigned to chunks/modules and in result  application starts using chunks/modules from a different app.

It would be nice to have a way to configure prefix for ids within the config or allow this to be done via plugins

### What does the proposed API of configuration look like?

It seems to be relatively easy to have configuration like below for existing plugins to allow to have prefix for module names

rspack: {     
  optimization: {         
    moduleIds: 'deterministic' ,
    moduleIdPrefix: 'my-app-01' ,
    chunkIds: 'deterministic' ,
    chunkIdPrefix: 'my-app-01' ,
   },
 },

Another options is to allow plugins with similar functionality
https://github.com/porsche-design-system/porsche-design-system/blob/42d4773819327e73885cee7af35aa4c4a70dbd13/packages/components-js/projects/components-wrapper/CustomNamedChunkIdsPlugin.js#L18

**Comment by LingyuCoder** [comment]
In rspack, the chunk graph is implemented on the Rust side, and transferring it to the JavaScript side incurs a high cost. This feature may be considered when supporting Rust-side plugins in the future.

**Comment by levshits** [comment]
> In rspack, the chunk graph is implemented on the Rust side, and transferring it to the JavaScript side incurs a high cost. This feature may be considered when supporting Rust-side plugins in the future.

In case if we are not talking about proper plugin, can we have something more lightweight? Let's say a prefix config for existing rust middleware to generate id? Basically the only thing we need is to add constant prefix for ids

**Comment by hardfist** [comment]
not planned yet, may support js api to modify this in the future. we'll revisit this issue when we think we have enough api to support this.
