### ISSUE TITLE
[Bug]: the type of webpack-sources is any

### ISSUE THREAD

**Issue by Amour1688** [web-infra-dev/rspack#5867]
### System Info

Every System

### Details

![image](https://github.com/web-infra-dev/rspack/assets/31695475/a0a8716e-bf18-4497-b2de-e062c4bbef3d)

![image](https://github.com/web-infra-dev/rspack/assets/31695475/1fdc0058-eb3f-4bc0-93d3-26bcf2f4005d)

### Reproduce Steps

Every repo

**Comment by SyMind** [comment]
First, we should fix the `@types/webpack-sources`. I have already addressed the PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69710.
