### ISSUE TITLE
[Bug]: `newTreeshaking` compiles css modules to wrong parameters

### ISSUE THREAD

**Issue by guomio** [web-infra-dev/rspack#5869]
### System Info

```
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.80 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 16.6
  npmPackages:
    @rspack/cli: latest => 0.5.6 
    @rspack/core: latest => 0.5.6 
```

### Details

如图更改配置, 按照复现项目改写css module, 构建后发现className不正确，导致页面元素丢失样式
@rspack/core 0.5.4 版本是正常的，0.5.5和0.5.6版本不正常

<img width="704" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22063439/7e772c75-bf83-434b-b1f6-6db9f54d3df6">

<img width="602" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22063439/76ae0bc7-d72e-479b-81e7-9ad2dbe28666">

### Reproduce link

https://github.com/guomio/rspack-issue-SassModuleShaking

### Reproduce Steps

git clone https://github.com/guomio/rspack-issue-SassModuleShaking
npm i
npm run build:rspack

look at `rspack-dist/121.js`, something like `e.classList.add(r.f)`, it's wrong

**Comment by IWANABETHATGUY** [comment]
a temp workaround , disable ` optimization.mangleExports`, we will fix it ASAP

**Comment by IWANABETHATGUY** [comment]
try 
0.5.5-canary-936dff6-20240306115523

**Comment by guomio** [comment]
> try 0.5.5-canary-936dff6-20240306115523

thanks, this version works fine
