### ISSUE TITLE
[Bug]: Using `extends: []` in `tsconfig.json` cause error "invalid type: sequence, expected a string"

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5877]
### Version

```sh
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 6.91 GB / 96.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 122.0.6261.94
    Firefox Nightly: 115.0
    Safari: 17.0
  npmPackages:
    @rsbuild/core: ^0.4.12 => 0.4.12
    @rsbuild/plugin-react: ^0.4.12 => 0.4.12
```

### Details

I upgraded the `rsbuild` packages recently and an error showed up:

```
start   Compiling...
error   Compile error:
Failed to compile, check the errors for troubleshooting.
× JSONError { path: "<root>/rsbuild-app/tsconfig.json", message: "invalid type: sequence, expected a string at line 2 column 13", line: 2, column: 13 }
```

It is complaining about my `"extends": ["../../tsconfig.json"]`.

I also made some breakpoints. It shows that the error is emitted here:

https://github.com/web-infra-dev/rsbuild/blob/c6020c420ae6c8c76a5c6085c769c20c8fd6372f/packages/core/src/provider/build.ts#L53-L56

And the `err` is `null`, and the `stats` contains the previous error message. I'm not sure if this is an issue of `rspack` or `rsbuild`, since directly using `rspack` does not give this error.

### Reproduce link

https://github.com/colinaaa/rsbuild-repro-tsconfig-extends

### Reproduce Steps

1. `pnpm install`
2. `npm run build`

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxc-resolver/issues/101 🥲
