### ISSUE TITLE
[Feature]: Support enable incremental rebuild with new treeshaking

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#5887]
### What problem does this feature solve?

Currently we can not enable incremental rebuild with new treeshaking because of the side effects cased by new treeshaking modified module_graph.

### What does the proposed API of configuration look like?

there are some steps we should to do:
1. move all module graph structure definitions to the module_graph directory
2. set compilation.module_graph as private
3. adjust the data structure and method signature in module_graph to be more reasonable
4. split module_graph into module_graph_partial
5. support accessing fields through module_graph as before

**Comment by xc2** [comment]
reference of a case telling that the new_treeshaking negatively affects build performance:

https://discord.com/channels/977448667919286283/1219528136543440988

not sure if it is related to this issue.
