### ISSUE TITLE
[Feature]: Support `namedChunkGroups` on `compilation` object

### ISSUE THREAD

**Issue by Clarkkkk** [web-infra-dev/rspack#5908]
### What problem does this feature solve?

In webpack, when using `optimization.splitChunks.chunks: 'all'`, it is able to get all the assets names of a named entry by `compilation.namedChunkGroups.get('entryName')`. It is useful for plugins like workbox plugin that need to generate a precache list for entries. Is there a way to do so in rspack?

### What does the proposed API of configuration look like?

Please refer to: https://github.com/webpack/webpack/blob/main/lib/Compilation.js#L1008

**Comment by LingyuCoder** [comment]
You can try to use `compilation.entrypoints` to get chunk groups of entries

**Comment by Clarkkkk** [comment]
> You can try to use `compilation.entrypoints` to get chunk groups of entries

Thanks! It solves my problem.
