### ISSUE TITLE
[Feature]: Support diagnostics reporting API like `esbuild.formatMessages` or swc `HANDLER`

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5913]
### What problem does this feature solve?

We are using `esbuild` as our bundler and we are trying to migrate to `rspack`.

`esbuild` has a great API [`esbuild.formatMessages`](https://esbuild.github.io/api/#format-messages) that we use to print the compilation warnings and errors. It makes all the printed diagnostics(directly by `esbuild` or by our plugins) look the same.

We also made some `esbuild` transform plugins with `swc`. And we use the [`HANDLER`](https://rustdoc.swc.rs/swc_common/errors/struct.Handler.html) API of `swc` a lot to print diagnostics(with a custom [`Emitter`](https://rustdoc.swc.rs/swc_common/errors/emitter/trait.Emitter.html) to print 
 `esbuild` compatible messages).

It would be nice if `rspack` could provide such an API so that all the ecosystems(`oxc`, `rsbuild` and third-party plugins) can make diagnostics in the same format.

## Rust

The `swc` has a great API:

```rust
use swc_core::common::errors::HANDLER;

HANDLER.with(|handler| {
  handler
    .struct_span_warn(
      n.span,
      format!("DEPRECATED: old package \"{}\" is removed", n.src.value).as_str(),
    )
    .emit()
});
```

Maybe `rspack` could provide rust API like this(in a standalone crate so than it can be used by our rust transformers).

## JS

It would be nice if it has the same API as `esbuild`.

```js
import * as rspack from '@rspack/core'

let formatted = await rspack.formatMessages([
  {
    text: 'This is an error',
    location: {
      file: 'app.js',
      line: 10,
      column: 4,
      length: 3,
      lineText: 'let foo = bar',
    },
  },
], {
  kind: 'error',
  color: false,
  terminalWidth: 100,
})

console.log(formatted.join('\n'))
```

It also LGTM if `rspack` uses a different data structure that is more rust-style :)

**Comment by LingyuCoder** [comment]
cc @h-a-n-a

**Comment by h-a-n-a** [comment]
Thanks for reaching out! Currently, we do have some APIs for internal error reportings. However, we haven't expose these as stable API instead its an internal API. We've put this into consideration ;-)  More followups will be provided as soon as Rspack 1.0 is released.

**Comment by h-a-n-a** [comment]
bump

**Comment by colinaaa** [comment]
bump
