### ISSUE TITLE
[Bug]: Panic occurred when using SWC plugin in development mode

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5921]
### System Info

  System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.03 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/yarn
    npm: 10.2.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/npm
    pnpm: 8.15.4 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 16.6
  npmPackages:
    @rspack/cli: latest => 0.5.7
    @rspack/core: latest => 0.5.7

### Details

Panic occurred when using SWC plugin in development mode:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/a2d46858-479a-4165-a225-c1dea7f62cdd)

Rspack config:

```js
const config = {
  mode: "development",
  module: {
    rules: [
      {
        test: /\.(?:js|jsx|mjs|cjs|ts|tsx|mts|cts)$/,
        type: 'javascript/auto',
        use: {
          loader: "builtin:swc-loader",
          options: {
            sourceMap: true,
            jsc: {
              parser: {
                syntax: "typescript",
                jsx: true,
              },
              experimental: {
                plugins: [
                  [
                    "@swc/plugin-remove-console",
                    {
                      exclude: ["error"],
                    },
                  ],
                ],
              },
            },
          },
        },
      },
    ],
  },
};
```

### Reproduce link

https://github.com/chenjiahan/rspack-repro-swc-warn-plugin

### Reproduce Steps

1. pnpm i
2. pnpm dev:rspack

**Comment by chenjiahan** [comment]
@h-a-n-a cc~

**Comment by xc2** [comment]
more panic cases related to swc-plugins:

- #5972

**Comment by h-a-n-a** [comment]
There's an AST breaking change introduced in the latest version of swc. For current version of SWC, you may now use plugins of version `1.5.113`

**Comment by huhuaaa** [comment]
I have a similar problem. If using other plugins like [swc-plugin-auto-css-modules](https://www.npmjs.com/package/swc-plugin-auto-css-modules?activeTab=readme), how do I choose which version to use? Is there any corresponding guidance for the swc version used by rspack?

**Comment by h-a-n-a** [comment]
> Thanks @h-a-n-a, I'm not clear on what the 1.5.113 version refers to and is this a change the plugin maintainers would need to make?

Thanks for reaching out. It's the version of [official plugins](https://github.com/swc-project/plugins) provided by swc. If It's provided by the third party author. You have to check if the crate `swc_core` version of that wasm plugin is between `0.88.x ~ 0.89.x`.

**Comment by esturcke** [comment]
Ok, so for [swc-plugin-coverage-instrument](https://github.com/kwonoj/swc-plugin-coverage-instrument/blob/6438b88c2f58c072115d021c1b3c05f836bf4f83/Cargo.toml#L23C1-L23C44)

```
swc_core           = { version = "0.90.7" }
```

So that means I would need to wait for an `rspack` update to use that plugin because there's an API breaking change in SWC?

**Comment by h-a-n-a** [comment]
> Ok, so for [swc-plugin-coverage-instrument](https://github.com/kwonoj/swc-plugin-coverage-instrument/blob/6438b88c2f58c072115d021c1b3c05f836bf4f83/Cargo.toml#L23C1-L23C44)
> 
> ```
> swc_core           = { version = "0.90.7" }
> ```
> 
> So that means I would need to wait for an `rspack` update to use that plugin because there's an API breaking change in SWC?

Yes, or you can downgrade to plugin of the version within that range.

**Comment by esturcke** [comment]
I tried a few versions of [`swc-plugin-coverage-instrument`](https://github.com/kwonoj/swc-plugin-coverage-instrument) but they seem to all cause an error during build. I think I can use [`babel-plugin-istanbul`](https://github.com/istanbuljs/babel-plugin-istanbul) in the mean time (build time goes up from 15s to 2min :) but we don't need coverage builds as often).

Thanks for all the work on `rspack`, it's been so much easier to migrate from webpack than vite and performance is incredible.

**Comment by h-a-n-a** [comment]
> I tried a few versions of [`swc-plugin-coverage-instrument`](https://github.com/kwonoj/swc-plugin-coverage-instrument) but they seem to all cause an error during build. I think I can use [`babel-plugin-istanbul`](https://github.com/istanbuljs/babel-plugin-istanbul) in the mean time (build time goes up from 15s to 2min :) but we don't need coverage builds as often).
> 
> Thanks for all the work on `rspack`, it's been so much easier to migrate from webpack than vite and performance is incredible.

We're going to release a minor version of rspack. In this version, we bumped `swc_core` to the latest version, which should support the latest version of `swc-plugin-coverage-instrument`. https://github.com/web-infra-dev/rspack/pull/6009.

**Comment by h-a-n-a** [comment]
This issue would be closed. For followup plugin selections, please refer to https://swc.rs/docs/plugin/selecting-swc-core.
