### ISSUE TITLE
[Bug]: Failed to get normal module of container entry (default)

### ISSUE THREAD

**Issue by rainydayDY** [web-infra-dev/rspack#5923]
### System Info

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M2
    Memory: 108.34 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    pnpm: 7.14.1 - /usr/local/bin/pnpm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 15.5
  npmPackages:
    @rspack/cli: ^0.5.7 => 0.5.7 
    @rspack/core: ^0.5.7 => 0.5.7 

### Details

$ rspack --config scripts/rspack.build.js
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Failed to get normal module of container entry (default) [["./ui-focus-jump",{"name":null,"import":["/Users/dongyu/Documents/mi-tvb/mitv-webpage/lubanComponents/ui-focus-jump/index.ts"]}],["./ui-rn-image",{"name":null,"import":["/Users/dongyu/Documents/mi-tvb/mitv-webpage/lubanComponents/ui-rn-image/index.ts"]}]]
Location: crates/rspack_core/src/tree_shaking/optimizer.rs:663

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: __pthread_deallocate
    at <unknown source file>
error Command failed with signal "SIGABRT".

### Reproduce Steps

rspack --config scripts/rspack.build.js

new rspack.container.ModuleFederationPlugin({
      name: "luban-components",
      filename: "luban-components",
      exposes: {
        "./ui-focus-jump": resolve("lubanComponents/ui-focus-jump/index.ts"),
        "./ui-rn-image": resolve("lubanComponents/ui-rn-image/index.ts"),
      },
      shared: {
        vue: {
          singleton: true,
          requiredVersion: "2.7.16",
        },
      },
    }),
上述配置即报错，使用webpack5没有报错

**Comment by IWANABETHATGUY** [comment]
https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking
