### ISSUE TITLE
[Bug]: circular dependency problem

### ISSUE THREAD

**Issue by jayjliang** [web-infra-dev/rspack#5928]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 83.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    @rsbuild/core: ^0.4.14 => 0.4.15 
    @rsbuild/plugin-node-polyfill: ^0.4.14 => 0.4.15 
    @rsbuild/plugin-react: ^0.4.14 => 0.4.15 
    @rsbuild/plugin-styled-components: ^0.4.15 => 0.4.15
```

### Details

webpack5 build is ok, but rspack will cause circular dependency problem, the reason is that webpack5 will change `import { defineLocale } from 'packageA'` to `import { defineLocale } from './src/locale.js'`, but rspack will not, so circular dependency problem occur

ps: webpack4 is also not ok

i wonder if there has some option to make this behavior same as webpack

### Reproduce link

https://github.com/jayjliang/rsbuild-demo

### Reproduce Steps

yarn
cd ./packages/package-b
yarn dev
yarn dev:webpack

**Comment by hardfist** [comment]
newTreeshaking solve this problem，try it

**Comment by jayjliang** [comment]
> [newTreeshaking](https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking) solve this problem，try it

ok, already try `newTreeshaking`, but the build time increase from 10s to 1.46min, I will use some tools like Rsdoctor to analyse the build time

**Comment by IWANABETHATGUY** [comment]
Do you mean the same repo?

**Comment by IWANABETHATGUY** [comment]
Please file another issue if the problem couold not be solved.
