### ISSUE TITLE
[Bug]: Panic occurred at runtime，when remove webpack in dependencies

### ISSUE THREAD

**Issue by linzebingo** [web-infra-dev/rspack#5933]
### System Info

node 18.19.1
npm 6.14.15
rspack 0.4.5
rsbuild 0.3.1

### Details

我项目从 webpack 升级 rspack 后报这个错，手动安装 webpack@3 的依赖后就不报错了，请问这种问题要怎么排查呢？
PS：安装webpack@5 也会报错，3 和 4 正常

![image](https://github.com/web-infra-dev/rspack/assets/12185104/22f396d4-55dd-4f3b-b542-d4df503ff186)

### Reproduce link

如果需要话，我提供下

### Reproduce Steps

1. npm uninstall webpack
2. rsbuild dev

**Comment by LingyuCoder** [comment]
需要提供一下用于复现的样例项目
