### ISSUE TITLE
[Bug]: error report can not update when report existed

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rspack#5961]
### Version

```sh
latest
```

### Details

see https://github.com/fi3ework-reproduction/rsbuild-error-report-stuck/blob/main/src/a.ts#L3-L7

### Reproduce link

https://github.com/fi3ework-reproduction/rsbuild-error-report-stuck/blob/main/src/a.ts

### Reproduce Steps

1. clone
2. pnpm dev
3. change `const a = 2` to `const a = 3`
4. you'll see the error report does not update, which is not expected.

**Comment by jerrykingxyz** [comment]
fixed by https://github.com/web-infra-dev/rspack/pull/6565
