### ISSUE TITLE
[Bug]: rspack does not seem to warn about missing exports, like webpack does

### ISSUE THREAD

**Issue by MagicDuck** [web-infra-dev/rspack#5967]
### System Info

    "@rspack/cli": "^0.5.7",
    "@rspack/core": "^0.5.7",
    "@rspack/plugin-react-refresh": "^0.5.7",

### Details

First, thank you for this awesome tool. It's already speeding up our build immensely!
Just running into a minor issue. 
When an export is missing/invalid, webpack will helpfully warn about it. rspack seems to be missing this functionality atm.
Would be a great helper to have that warning show up.

Example warn from webpack:
<img width="2446" alt="image" src="https://github.com/web-infra-dev/rspack/assets/95201/8fdc2cf8-5bdb-445f-ace9-6ec52eb81ba9">

### Reproduce Steps

simply have an import like:
```
a.js
-------
import foo, {something} from 'bar'

b.js
------
export const something = 42;
// note no default export
```

**Comment by h-a-n-a** [comment]
Should warn and provide better diagnostic than webpack. Error frame should print with span.

**Comment by ahabhgk** [comment]
bump, I will take a look in next week

**Comment by MagicDuck** [comment]
nice! Thank you!
