### ISSUE TITLE
[Bug]: CSS Modules is missing after enabling new tree shaking

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#5968]
# System Info

  System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 574.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    npm: 10.2.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/npm
    pnpm: 8.15.4 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.6
  npmPackages:
    @rspack/core: 0.5.7 => 0.5.7

# Details

CSS Modules is missing after enabling new tree shaking.

CSS source code: `packages/document/src/components/Overview.module.scss`

## new tree shaking: true

![image](https://github.com/web-infra-dev/rspack/assets/7237365/5866923f-e251-4b74-98f3-ed5581b11bf9)

## new tree shaking: false

![image](https://github.com/web-infra-dev/rspack/assets/7237365/be656eeb-c56d-46f0-b476-7bc23ead780b)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/new_tree_shaking_css_missing_0319

### Reproduce Steps

1. pnpm i
2. cd pacakges/document
3. pnpm build:doc
4. pnpm preview
5. open http://localhost:4173/config/index

**Comment by chenjiahan** [comment]
related issue: https://github.com/web-infra-dev/rspack/issues/5869

**Comment by IWANABETHATGUY** [comment]
can you try 
0.5.8-canary-2e1be96-20240321104547?

**Comment by chenjiahan** [comment]
It worked 👍
