### ISSUE TITLE
[Bug]: There is some errors, when I run pnpm add @rsbuild/core @rsbuild/plugin-vue2 -D

### ISSUE THREAD

**Issue by LukerSpringtree** [web-infra-dev/rspack#5976]
### System Info

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 11.28 GB / 31.67 GB
  Binaries:
    Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (Active code page: 65001), Chromium (122.0.2365.52), ChromiumDev (Active code page: 65001)
    Internet Explorer: 11.0.19041.3636

### Details

There is some errors, when I run pnpm add @rsbuild/core @rsbuild/plugin-vue2 -D

```bash
 WARN  deprecated vuex-persistedstate@4.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @rspack/core@0.5.8

This error happened while installing the dependencies of @rsbuild/core@0.5.1
The latest release of @rspack/core is "0.5.7".

Other releases are:
  * snapshot,test: 0.0.0-20220909030737
  * canary: 0.5.7-canary-6007430-20240313111541
  * nightly: 0.5.7-canary-3320ea8-20240312032922
  * alpha: 0.0.4
  * snapshot: 0.0.0-canary-2d5264852-20230525090643

If you need the full list of all 867 published versions run "$ pnpm view @rspack/core versions".
Progress: resolved 729, reused 727, downloaded 2, added 0
```

### Reproduce Steps

pnpm add @rsbuild/core @rsbuild/plugin-vue2 -D

**Comment by xc2** [comment]
if you're install packages from an npm mirror registry, please check the latest version of @rspack/* has been synced to the mirror registry.
