### ISSUE TITLE
Support more intuitive CSS diagnostic for `~` as a alias

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#5986]
Currently, if user uses `~` as an alias to `node_modules`, rspack will file a warning:

```
css: Deprecated '~'
        │ '@import' or 'url()' with a request starts with '~' is deprecated.
```

This is not intuitive. We should give the solution for user and teach them how to make the next move.
It would be better to provide span(location) information pointing to the exact place that should be improved.

**Comment by luhc228** [comment]
Can I have a try?

**Comment by h-a-n-a** [comment]
> Can I have a try?

Take your time ;-)
