### ISSUE TITLE
[Bug]: ModuleFederation with output.library.type: 'module' (ESM) build doesn't produce a valid module

### ISSUE THREAD

**Issue by MadaraUchiha-314** [web-infra-dev/rspack#5989]
### System Info

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 55.42 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.8.1 - ~/code/github.com/MadaraUchiha-314/rollup-plugin-module-federation/node_modules/.bin/npm
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Chrome Canary: 125.0.6369.0
    Safari: 17.2.1

### Details

When I try to build using Module Federation (v1.5 or enhanced) and keep the output format as `module` (ESM), the generated remote entry doesn't seem to work. It doesn't have the the `init` and the `get` methods exported.

The same config works in webpack.

```js
{
  "name": "sample_project_a",
  "filename": "my-remote-entry.js",
  "exposes": {
    "./react": "react",
    "./pqr": "./src/pqr.js",
    "./index": {
      "import": "./src/index.js"
    }
  },
  "remoteType": "module",
  "remotes": {
    "project-b": {
      "external": "http://localhost:8080/packages/examples/project-b/dist/rspack/esm/my-remote-entry.js"
    }
  },
  "shared": {
    "react": {
      "eager": true
    },
    "react-dom": {},
    "uuid": {},
    "redux": {}
  },
  "library": {
    "type": "module"
  }
}
```

PR: https://github.com/MadaraUchiha-314/rollup-plugin-module-federation/pull/47

webpack build: https://rollup-plugin-module-federation-pro-git-2c5fbc-madarauchiha-314.vercel.app/webpack/esm/

rspack build: https://rollup-plugin-module-federation-pro-git-2c5fbc-madarauchiha-314.vercel.app/rspack/esm/

### Reproduce link

https://rollup-plugin-module-federation-pro-git-2c5fbc-madarauchiha-314.vercel.app/rspack/esm/

### Reproduce Steps

1. Go to the URL
2. Click on all the buttons one by one

### rspack

<img width="1470" alt="Screenshot 2024-03-20 at 10 12 29 PM" src="https://github.com/web-infra-dev/rspack/assets/6977429/967a0af6-f5d6-4f92-b703-545da0821e21">

### webpack

Do the same steps with the webpack build, it works fine.
<img width="1470" alt="Screenshot 2024-03-20 at 10 11 43 PM" src="https://github.com/web-infra-dev/rspack/assets/6977429/679da102-cbf0-4dc6-b5f8-8981a0df98c8">

**Comment by ahabhgk** [comment]
Could you try enable `experiments.rspackFuture.newTreeshaking` and see whether the problem still exists?

**Comment by ckken** [comment]
same here

**Comment by ckken** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/3890513/a41a8b6f-45c2-4331-812b-3bbe9d34596c)
use `experiments.rspackFuture.newTreeshaking`

**Comment by ckken** [comment]
css module also displays abnormally under esm

**Comment by MadaraUchiha-314** [comment]
> Could you try enable `experiments.rspackFuture.newTreeshaking` and see whether the problem still exists?

Doesn't seem to work. Getting the same error as @ckken 

<img width="1470" alt="Screenshot 2024-03-21 at 8 38 55 AM" src="https://github.com/web-infra-dev/rspack/assets/6977429/8e0abf58-2e2b-4468-8d70-a8bc1dc8e61d">

**Comment by ckken** [comment]
@MadaraUchiha-314 Is the css module normal after you switch to esm?

**Comment by ckken** [comment]
fixed css module don`t display!
```
    //     {
    //       chunkFormat: 'module',
    //       chunkLoading: 'import',
    //       library: {
    //         type: 'module',
    //       },
    //     },
```

**Comment by ahabhgk** [comment]
#6010 should fix it, will release the fix soon
