### ISSUE TITLE
[Bug]: Using ProvidePlugin causes duplicated identifiers

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#5994]
### System Info

```
  npmPackages:
    @rspack/cli: ^0.5.8 => 0.5.8
    @rspack/core: ^0.5.8 => 0.5.8
```

### Details

I'm using the ProvidePlugin with a class having a static property(transformed by `swc-loader` with a top-level function call).

```js
// foo.js
export class Foo {}
foo(Foo)
```

```js
// rspack.config.js
/** @type {import('webpack').Configuration} */
export default {
  // ...
  plugins: [
    function (compiler) {
      const { ProvidePlugin } = compiler.webpack;
      new ProvidePlugin({
        Foo: [require.resolve("./src/foo.js"), "Foo"],
      }).apply(compiler);
    },
  ],
};
```

```js
// index.js
console.log(new Foo().bar()) // the `Foo` should be provided.
```

And I got the following error at runtime:

```
SyntaxError: Identifier 'Foo' has already been declared
```

The output of `foo.js` also contains the `provided dependency`. See:

```js
/* provided dependency */ var Foo = __webpack_require__(/*! /Users/bytedance/rspack-provide-repro/src/foo.js */"./src/foo.js")["Foo"];
class Foo {
    bar() {
        return 42;
    }
}
```
https://github.com/colinaaa/rspack-provide-repro/blob/350a0d841cbddc7a9f9bf74eeee3ba9d1d684c0f/dist_rspack/main.js#L9-L20

If I change `export class Foo {}` to `class Foo {}; export { Foo }`, the problem would be gone.

### Reproduce link

https://github.com/colinaaa/rspack-provide-repro

### Reproduce Steps

Run:

```bash
pnpm install
./node_modules/.bin/rspack
node dist/main.js # SyntaxError: Identifier 'Foo' has already been declared
```

Also, the webpack is added for reference:

```bash
pnpm install
./node_modules/.bin/webpack --config rspack.config.js
node dist/main.js # [class Foo] 42
```

**Comment by xc2** [comment]
> I've tried the following methods to make it work:
> 
> The source code is written as export class WebSocket. If I change it to class WebSocket + export { WebSocket }, the problem will be gone.
> 
> Also, the WebSocket has a static property CONNECTING, if I remove it, the problem will be gone, too.
> 
> Meanwhile, if I remove the swc-loader, the problem will be gone, too.

minimal reproduce without swc-loader:

```js
export class Answer {}

foo(Answer);
```

while the code below works fine.

```js
class Answer {}

foo(Answer);
```

> Besides, if I move the entry of the EntryPlugin to the real entry(mv src/entry.js src/index.js and remove EntryPlugin), the problem will be gone again.

the problem will also happen without EntryPlugin.

**Comment by colinaaa** [comment]
@xc2 Thanks! I simplified the repro and the issue.

**Comment by xc2** [comment]
@bvanjoi @ahabhgk could you please help

**Comment by xc2** [comment]
@colinaaa try `0.5.8-canary-cff2c4f-20240325162043` please
