### ISSUE TITLE
[Bug]: In concatenated css output, `@import`s are not moved to the top of the file

### ISSUE THREAD

**Issue by chungwu** [web-infra-dev/rspack#6000]
### Version

```sh
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Xeon(R) W-11855M CPU @ 3.20GHz
    Memory: 51.21 GB / 62.51 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 122.0.6261.128
  npmPackages:
    @rsbuild/core: ^0.5.2 => 0.5.2 
    @rsbuild/plugin-react: ^0.5.2 => 0.5.2
```

### Details

Suppose I have entry file `src/index.tsx`:

```
import "./a.css"
import "./b.css"

export function App() {

}
```

And in `a.css`, I have
```
@import url('https://fonts.googleapis.com/css2?family=Roboto');

.a {
  color: blue;
}
```

In `b.css` I have

```
@import url('https://fonts.googleapis.com/css2?family=Inter');

.b {
  color: red;
}
```

The `rsbuild` build output gives me:

```
@import"https://fonts.googleapis.com/css2?family=Roboto";.a{color:blue}@import"https://fonts.googleapis.com/css2?family=Inter";.b{color:red}
```

But per [spec](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) the `@import` rules must be at the top of the stylesheet.  Here the two files are just concatenated, without moving the `@import` from `b.css` to the top.

`parcel` for example outputs this correctly

```
@import "https://fonts.googleapis.com/css2?family=Roboto";@import "https://fonts.googleapis.com/css2?family=Inter";.a{color:#00f}.b{color:red}
```

### Reproduce link

none

### Reproduce Steps

1. Run `npm create rsbuild@latest` with React
2. Create `a.css` and `b.css` as described above and import them from `App.tsx`
3. Run `npm run build`
4. Examine the css output

**Comment by chenjiahan** [comment]
This should be a bug of Rspack's experimental css, so I have transfered this issue to the Rspack repo.

**Comment by woai3c** [comment]
bug hash already fix. see https://github.com/web-infra-dev/rspack/pull/6016
