### ISSUE TITLE
[Bug]: nternal error: entered unreachable code.

### ISSUE THREAD

**Issue by xinlanlan** [web-infra-dev/rspack#6007]
### System Info

系统：mac M1
node版本：18.18.2
使用pnpm
jszip版本：3.7.1
@rspack/cli: 0.5.8

发现使用jszip包就报错，卸载掉这个包就好了。

### Details

报错：Message:  internal error: entered unreachable code
Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:85

 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1

### Reproduce Steps

npm run start

**Comment by xc2** [comment]
有用 ProvidePlugin 吗

**Comment by xinlanlan** [comment]
> 有用 ProvidePlugin 吗
new rspack.ProvidePlugin({
    process: require.resolve('process/browser'),
    Buffer: [require.resolve('buffer'), 'Buffer']
  })
使用了这两个

**Comment by xinlanlan** [comment]
> > 有用 ProvidePlugin 吗
> > new rspack.ProvidePlugin({
> > process: require.resolve('process/browser'),
> > Buffer: [require.resolve('buffer'), 'Buffer']
> > })
> > 使用了这两个

知道原因了，没有下载buffer这个包
