### ISSUE TITLE
[Bug]:  Imported Module Not Included in Output File

### ISSUE THREAD

**Issue by woai3c** [web-infra-dev/rspack#6013]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 7.37 GB / 15.30 GB
  Binaries:
    Node: 18.19.1 - D:\software\nodejs\node.EXE
    Yarn: 1.22.22 - D:\software\nodejs\yarn.CMD
    npm: 10.2.4 - D:\software\nodejs\npm.CMD
    pnpm: 8.15.4 - D:\software\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rspack/cli: ^0.5.8 => 0.5.8
    @rspack/core: ^0.5.8 => 0.5.8

### Details

When I import another module directly and build the bundle, it should include the other module. For example:
```js
// rspack.config.js
const rspack = require("@rspack/core");
/** @type {import('@rspack/cli').Configuration} */
const config = {
	mode: "production",
	entry: "./src/index.js",
	plugins: [
		new rspack.HtmlRspackPlugin({
			template: "./index.html"
		})
	],
	devtool: false
};
module.exports = config;
```
```js
// index.js
import "./answer.js";
console.log("hello world!");
```
```js
// answer.js
export function ab() {
    console.log("ab");
}

export function test() {
    console.log("test");
}

ab();

console.log(1 + 1);
```
Normally, the output would be:
```
ab
2
hello world!
```
However, in reality, it outputs:
```
hello world!
```
Upon examining the bundled `main.js` file and after formatting the code, it shows me:
```js
!function() {
    var e = {
        138: function(e, o, r) {
            "use strict";
            r.r(o),
            console.log("hello world!")
        }
    },
    o = {};
    function r(t) {
        var n = o[t];
        if (void 0 !== n) return n.exports;
        var i = o[t] = {
            exports: {}
        };
        return e[t](i, i.exports, r),
        i.exports
    }
    r.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }),
        Object.defineProperty(e, "__esModule", {
            value: !0
        })
    },
    r("138")
}();
```
I noticed that `answer.js` isn't included in the `main.js` bundle. However, webpack's output is as expected.
I've compared the source code of rspack and webpack and found that webpack bundles everything into the main file first and only then removes the dead code. Rspack, on the other hand, filters the module, then bundles the remaining modules into the main file.
When using the statement import `'./answer'` in `index.js`, the `answer.js` should not be filtered out. I've tried to fix the issue, but my understanding of the source code is limited, and I haven't been able to resolve it.

### Reproduce link

https://github.com/woai3c/reproduce-rspack-issue-project

### Reproduce Steps

1. `pnpm i`
2. `pnpm build`

**Comment by LingyuCoder** [comment]
You specified `sideEffects=false` at https://github.com/woai3c/reproduce-rspack-issue-project/blob/main/package.json#L11. This will disable the analysis of `optimization.sideEffects` in tree shaking, and only consider the usage based on exports. Therefore, the `answer.js` was removed.

**Comment by woai3c** [comment]
> You specified `sideEffects=false` at https://github.com/woai3c/reproduce-rspack-issue-project/blob/main/package.json#L11. This will disable the analysis of `optimization.sideEffects` in tree shaking, and only consider the usage based on exports. Therefore, the `answer.js` was removed.

I see. Thank you
