### ISSUE TITLE
[Bug]: build CSS code will escape ！！

### ISSUE THREAD

**Issue by hatedMe** [web-infra-dev/rspack#6057]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.57 GB / 23.79 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD      
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD       
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636

### Details

build css style code will escape!!

#### example：
``` 
// input
.el-icon-knife-fork:before{content:"\e6c1"}  
// out
.el-icon-knife-fork:before{content:" "}  
```

The output will be a blank placeholder

### Reproduce Steps

build css style code will escape!!

#### example：
``` 
// input
.el-icon-knife-fork:before{content:"\e6c1"}  
// out
.el-icon-knife-fork:before{content:" "}  
```

The output will be a blank placeholder
The manifestation is as follows:
![image](https://github.com/web-infra-dev/rspack/assets/16054689/e1adcc36-5153-4ee8-bc93-c2eaad3b54dd)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by SyMind** [comment]
@hatedMe I've attempted to replicate the issue you encountered but wasn't able to. Here are the steps I followed:

1. `npm create rspack@latest`
2. Chose the React template when prompted.
3. Inserted the following CSS rule into the `App.css` file: `.el-icon-knife-fork:before{content:"\e6c1"}`.

**Comment by xc2** [comment]
@SyMind it would happen on production build.

@hatedMe does it break things? 

the blank symbol you have seen was actually an unicode character that was invisible with your system font.

`.el-icon-knife-fork:before{content:"\e6c1"}` and `.el-icon-knife-fork:before{content:""}` are equivalent in css file so the transform happened should not cause any issue.

**Comment by hatedMe** [comment]
@SyMind  不好意思，之前没有注意到issues已经回复，在打包之后确实会造成一个类似问号的空白框， @xc2   会正常影响网页的图标的显示成乱码。目前使用```rspack@0.5.9```已经能正常打包。

Sorry @SyMind , I didn't notice that the issues had already been replied to before. After packaging, it did create a blank box similar to a question mark, @xc2  which would normally affect the display of webpage icons as garbled characters. Currently used rspack@0.5.9 It can already be packed normally.

以下是我之前想到的一个解决方案
Here is a solution that I previously thought of

```js
import postcss from "postcss";
import glob from "glob";
import fs from "node:fs";
import path from "node:path";
const UNICODE_MATCH_REG = /[^\x00-\xff]/g; // 找出非单字节符

const replaceContentPlugin = postcss.plugin("replace-content-unicode", () => {
    return (root) => {
        root.walkDecls("content", (decl) => {
            if (decl.prop === "content") {
                if (decl.value === '""' || decl.value === "''") return;
                decl.value = decl.value.replace(UNICODE_MATCH_REG, (match) => {
                    return "\\" + match.charCodeAt(0).toString(16);
                });
            }
        });
    };
});

function replaceContentUnicode(outputPath) {
    const cssFiles = glob.sync(`${outputPath}/**/*.css`);
    console.log("cssFiles: ", cssFiles);
    cssFiles.forEach((filePath) => {
        const css = fs.readFileSync(filePath, "utf-8");
        postcss([replaceContentPlugin])
            .process(css, { from: filePath })
            .then((result) => {
                fs.writeFileSync(filePath, result.css);
            })
            .catch((error) => {
                throw new Error(`Error processing CSS file: ${filePath}`);
            });
    });
}

const pluginCssUnicode = () => ({
    name: "@rsbuild:pluginCssUnicode",
    setup: (api) => {
        api.onAfterBuild((config) => {
            replaceContentUnicode(config.stats.compilation.outputOptions.path);
        });
    }
});

export default pluginCssUnicode;

export { pluginCssUnicode };
```
