### ISSUE TITLE
[Feature]: Support for Webpack merge

### ISSUE THREAD

**Issue by OskarLebuda** [web-infra-dev/rspack#6059]
### What problem does this feature solve?

Merge rspack configurations like `webpack-merge` does. For example we need to merge `common.config.ts` with `prod.config.ts` or `dev.config.ts`. Without this feature we have to duplicate code between `prod` and `dev`.

### What does the proposed API of configuration look like?

```typescript
import { RsConfigurationMerge } from '@rspack/common';

const finalConfig = RsConfigurationMerge(CONFIG_1, CONFIG_2); 
```

Inspiration: https://www.npmjs.com/package/webpack-merge

**Comment by LingyuCoder** [comment]
You can try to use webpack-merge directly. It is also used in rsbuild and is currently working well.

**Comment by OskarLebuda** [comment]
> You can try to use webpack-merge directly. It is also used in rsbuild and is currently working well.

Of course I can :) The feature request is to create internal method to merge it

**Comment by hardfist** [comment]
> > You can try to use webpack-merge directly. It is also used in rsbuild and is currently working well.
> 
> Of course I can :) The feature request is to create internal method to merge it

this is out of scope of rspack

**Comment by OskarLebuda** [comment]
> > > You can try to use webpack-merge directly. It is also used in rsbuild and is currently working well.
> > 
> > 
> > Of course I can :) The feature request is to create internal method to merge it
> 
> this is out of scope of rspack, and since webpack-merge is not coupled with webpack, it seems there are no benefits if we integrate it in @rspack/common

Sounds good for me 🙏🏻
