### ISSUE TITLE
[Bug]: Production mode causes LinkError in WebAssembly.instantiate

### ISSUE THREAD

**Issue by allsey87** [web-infra-dev/rspack#6061]
### System Info

```
System:
    OS: Linux 6.8 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.98 GB / 23.26 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
npmPackages:
    @rspack/cli: ^0.5.8 => 0.5.8
```

### Details

I am seeing a difference between when I run rspack in development mode and production mode that I guess is not intended. When I run in development mode, everything is fine, however in production mode, I get the following error in the browser:
```
Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="./frontend_bg.js" function="__wbindgen_is_undefined": function import requires a callable
```
This sounds like rspack is removing the function definition for `__wbindgen_is_undefined` from the wasm-bindgen JS glue code (perhaps as a result of its tree shaking).

### Reproduce link

https://github.com/allsey87/rspack-test

### Reproduce Steps

1. Clone the repository
2. Open in VS Code with the Dev Containers extension installed and let the Docker image build
3. Run the DevOps script `dev.py`. It will build the Rust project, run wasm-bindgen, and run rspack before starting a Python server and opening the browser with Selenium (if Selenium is not available, a warning is printed and you can open the browser manually).
4. The checked in version has `--mode production` which is when the error shows up. Switching this back to `development` makes the error disappear.

It might be possible to run this in Github codespaces but I haven't tried that before.

**Comment by allsey87** [comment]
Setting tree-shaking to false seems to make this problem disappear:
```diff
diff --git a/rspack.config.js b/rspack.config.js
index 982372b..76d7218 100644
--- a/rspack.config.js
+++ b/rspack.config.js
@@ -1,4 +1,7 @@
 module.exports = {
+  builtins: {
+    treeShaking: false,
+  },
   experiments: {
     asyncWebAssembly: true,
   },
```

**Comment by IWANABETHATGUY** [comment]
Can you try enabling https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking in production?

**Comment by allsey87** [comment]
```js
module.exports = {
  experiments: {
    rspackFuture: {
      newTreeshaking: true,
    },
  },
};
```
Also seems to solve the problem.

**Comment by IWANABETHATGUY** [comment]
We will deprecate the `builtins.treeShaking` in the future,  so I recommend you enable `newTreeshaking`. If you have any issues, please file an issue.
