### ISSUE TITLE
[Bug]: rspack.HtmlRspackPlugin favicon behavior inconsistent with html-webpack-plugin

### ISSUE THREAD

**Issue by kgregory** [web-infra-dev/rspack#6063]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.27 GB / 31.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636

### Details

When using the html-webpack-plugin and supplying a path to a favicon property, the file at that path is copied into the output directory and the resulting html file has the favicon link pointing to the path of where the file was copied into the output directory. This works whether providing a relative or an absolute path.

When using `rspack.HtmlRspackPlugin`, the behavior is different.  Whether an absolute or relative path is provided, the directory structure to obtain that relative path will be copied into the output directory prepended with a forward slash.

For comparison purposes:

**Webpack Absolute Path**
Input: favicon: path.resolve(process.cwd(), 'static', 'favicon.ico'),
Output: <link rel="icon" href="/favicon.ico">

**Rspack Absolute Path**
Input: favicon: path.resolve(process.cwd(), 'static', 'favicon.ico'),
Output: <link rel="icon" href="/static/favicon.ico">

**Webpack Relative Path**
Input: favicon: path.join('static', 'favicon.ico'),
Output: <link rel="icon" href="/favicon.ico">

**Rspack Relative Path**
Input: favicon: path.join('static', 'favicon.ico'),
Output: <link rel="icon" href="/static/favicon.ico" />

Although the Rspack behavior should work, webpack's behavior is preferable because the input directory as your input directory structure doesn't necessarily need to align with the output directory structure.

A similar closed issue existed for `builtins.html`, which is now deprecated: #2795

### Reproduce link

https://github.com/kgregory/rspack-issue-htmlrspackplugin-favicon

### Reproduce Steps

1. Provide favicon option when instantiating `rspack.HtmlRspackPlugin`
2. Run build process
3. Inspect build output folder's index.html file and look at the favicon <link> which has been generated.

**Comment by LingyuCoder** [comment]
Webpack uses [path.basename](https://github.com/jantimon/html-webpack-plugin/blob/main/index.js#L1032-L1035) to ensure that the favicon is generated under the root directory of publicPath. 

But the rspack.HtmlRspackPlugin will generate based on the path which relative to compilerOptions.context.

I will try to fix this.
