### ISSUE TITLE
[Bug]: `enforce` option is not working

### ISSUE THREAD

**Issue by sxzz** [web-infra-dev/rspack#6068]
### System Info

_Unrelated to environment_

### Details

`module.rules[].enforce` is not working.

### Reproduce link

https://github.com/sxzz/rspack-enforce-issue

### Reproduce Steps

- Run `pnpm rspack build`, then we can see the output

```js
export default {
  __name: 'App',
  setup(__props) {
    console.log('HelloWorld')

    return { __sfc: true }
  },
}
```

- Run `pnpm webpack build`

```js
<script setup>
console.log('HelloWorld')
</script>

<template>
  <div id="app">hello</div>
</template>
```

They're different, but the configuration is the same. 

If we remove the `enforce` option in `webpack.config.js`, the output will be the same. So the `enforce` option is not working as expected in Rspack.

In this demo, I used `unplugin` for convenience, but I guess result will not be affected.
https://github.com/unjs/unplugin/blob/867b71d8f52a6fe8b32b0de801cdf3351da6ff79/src/rspack/index.ts#L81

**Comment by SoonIter** [comment]
I reproduced this bug when `use` is a function type and use together with `enforce: 'pre'`
https://github.com/sooniter/rspack-enforce-issue

```js
const { VueLoaderPlugin } = require('vue-loader');

/** @type {import('webpack').Configuration} */
module.exports = {
  context: __dirname,
  mode: 'development',
  entry: {
    main: './src/main.js',
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: { experimentalInlineMatchResource: true },
      },
      {
        enforce: 'pre',
        test: /\.vue/,
        use: () => {
          return [
            {
              loader: `./hello-loader.js`,
            },
          ];
        },
      },
    ],
  },
  devtool: 'source-map',
  plugins: [new VueLoaderPlugin()],
};
```
