### ISSUE TITLE
[Feature]: Module Federation supports runtime URLs

### ISSUE THREAD

**Issue by zimo888** [web-infra-dev/rspack#6077]
### What problem does this feature solve?

I previously raised an issue in the rsbuild repository discussing this request, and I received a reply suggesting that a new issue should be created here instead. [https://github.com/web-infra-dev/rsbuild/issues/1876](https://github.com/web-infra-dev/rsbuild/issues/1876)

Currently, the Module Federation URL in rspack is configured locally, and changing it to runtime would have the following effects:

1. Modules can be pre-compiled and then placed on a CDN in advance, significantly reducing the size of the local build.
2. Developers can proxy production environment code locally, making debugging easier.
3. Some larger third-party libraries’ index.js files can be split and transformed into a Module Federation approach, configurable for runtime on-demand loading, reducing the size of the third-party libraries.

### What does the proposed API of configuration look like?

```js
 moduleFederation: {
    options: {
      name: 'host',
      remotes: {
        remote: 'remote@[window.entry.remote]',
        antd: 'antd@[window.entry.base]',
      },
    },
  }
```

Host source somewhere before loading main entry file
```js
window.entry=  {
   remote: "[cdn_url]",
   base: "[cdn_url]",
}

//proxy modules from localStorage
const proxyEntry = localStorage.getItem('mf_entry')
if(proxyEntry){
     window.entry = {
          ...window.entry,
          ...JSON.parse(proxyEntry)
    }
}
import("./bootstrap");
```

And then we can use ast transform convert third party code to module federation

```js
import {Button} from 'antd'

->

import {Button} from 'base/antd'
```

**Comment by ahabhgk** [comment]
I guess this is what you need: https://webpack.js.org/concepts/module-federation/#promise-based-dynamic-remotes, this is also supported in Rspack

**Comment by foxaltus** [comment]
Hey, the solution to this question might not be 100% obvious to anyone reading the answer above, so here is the code in question that loads the `remote` app based on what's in the `window.entry.remote` variable (eg: `http://localhost:3002/remoteEntry.js`):

```typescript
import { dependencies } from "./package.json";
import type { Rspack } from "@rsbuild/core";

export const mfConfig: Rspack.ModuleFederationPluginOptions = {
  name: "host",
  remotes: {
    remote: `promise new Promise((resolve, reject) => {
      // This part depends on how you plan on hosting and versioning your federated modules
      const remoteUrl = window.entry.remote
      const script = document.createElement('script')
      script.src = remoteUrl
      script.onload = () => {
        // the injected script has loaded and is available on window
        // we can now resolve this Promise
        const proxy = {
          get: (request) => window.host.get(request),
          init: (arg) => {
            try {
              return window.host.init(arg)
            } catch(e) {
              console.log('remote container already initialized')
            }
          }
        }
        resolve(proxy)
      }
      script.onerror = (event) => { reject(event.error) }
      // inject this script with the src set to the versioned remoteEntry.js
      document.head.appendChild(script);
    })
    `,
  },
  shared: {
    ...dependencies,
    react: {
      singleton: true,
      requiredVersion: dependencies.react,
    },
    "react-dom": {
      singleton: true,
      requiredVersion: dependencies["react-dom"],
    },
  },
};
```

(config adapted from module-federation example at https://github.com/rspack-contrib/rspack-examples/blob/main/rsbuild/module-federation/host/module-federation.config.ts)

Ideally, the code that builds the promise would be located in a utility function or plugin...

**Comment by esia-block** [comment]
Is this already solved? I can't really tell how the above function can be mapped/scalable like `ExternalTemplateRemotesPlugin`? 
Not too familiar with the syntaxes, If we are having more than 10 remotes, how do we inject the promise without duplicating the whole section `promise new Promise(() => {})`?

**Comment by ahabhgk** [comment]
It's just strings `promise new Promise(${commonPart})`

**Comment by pureliani** [comment]
I wrote a helper function but i am having other issues right now, so someone else will have to check if this works:
```js
function dynamicRemote(moduleName, urlExpression) {
  return `promise new Promise(resolve => {
      const urlValue = ${urlExpression};
      const remoteUrl = typeof urlValue === 'function' ? urlValue() : urlValue;
      const script = document.createElement('script');
      script.src = remoteUrl;
      script.onload = () => {
        const proxy = {
          get: (...arg) => window.${moduleName}.get(...arg),
          init: (...arg) => {
            try {
              return window.${moduleName}.init(...arg)
            } catch(e) {
              console.log('remote container already initialized')
            }
          }
        }
        resolve(proxy)
      }
      script.onerror = (event) => { reject(event.error) }
      document.head.appendChild(script);
    })`;
}
```

```js
new rspack.container.ModuleFederationPluginV1({
    name: "host1",
    filename: "remoteEntry.js",
    remotes: {
      control: dynamicRemote("app1", `window.app1Url`),
    },
    exposes: {},
    shared: [],
})
```

**Comment by dxhsmwqcwelllee** [comment]
> ### What problem does this feature solve?
> I previously raised an issue in the rsbuild repository discussing this request, and I received a reply suggesting that a new issue should be created here instead. [web-infra-dev/rsbuild#1876](https://github.com/web-infra-dev/rsbuild/issues/1876)
> 
> Currently, the Module Federation URL in rspack is configured locally, and changing it to runtime would have the following effects:
> 
> 1. Modules can be pre-compiled and then placed on a CDN in advance, significantly reducing the size of the local build.
> 2. Developers can proxy production environment code locally, making debugging easier.
> 3. Some larger third-party libraries’ index.js files can be split and transformed into a Module Federation approach, configurable for runtime on-demand loading, reducing the size of the third-party libraries.
> 
> ### What does the proposed API of configuration look like?
>  moduleFederation: {
>     options: {
>       name: 'host',
>       remotes: {
>         remote: 'remote@[window.entry.remote]',
>         antd: 'antd@[window.entry.base]',
>       },
>     },
>   }
> Host source somewhere before loading main entry file
> 
> window.entry=  {
>    remote: "[cdn_url]",
>    base: "[cdn_url]",
> }
> 
> //proxy modules from localStorage
> const proxyEntry = localStorage.getItem('mf_entry')
> if(proxyEntry){
>      window.entry = {
>           ...window.entry,
>           ...JSON.parse(proxyEntry)
>     }
> }
> import("./bootstrap");
> And then we can use ast transform convert third party code to module federation
> 
> import {Button} from 'antd'
> 
> ->
> 
> import {Button} from 'base/antd'

How to solve it ?   rspack mf v1

**Comment by dxhsmwqcwelllee** [comment]
@zimo888

**Comment by zimo888** [comment]
> [@zimo888](https://github.com/zimo888)

[pureliani](https://github.com/pureliani) 's  dynamicRemote  helper worked for me.

@dxhsmwqcwelllee
