### ISSUE TITLE
[Bug]: rspack not support amd

### ISSUE THREAD

**Issue by nanianlisao** [web-infra-dev/rspack#6080]
### System Info

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 61.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/Library/Caches/fnm_multishells/25629_1711942481602/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/25629_1711942481602/bin/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/25629_1711942481602/bin/npm
    pnpm: 7.3.0 - ~/Library/Caches/fnm_multishells/25629_1711942481602/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 16.3
  npmPackages:
    @rspack/cli: latest => 0.5.9 
    @rspack/core: latest => 0.5.9 

### Details

rspack not support amd.

### Reproduce link

https://github.com/nanianlisao/rspack-bug-reproduction/tree/fix_amd_require

### Reproduce Steps

1. pnpm i
2. pnpm run dev:rspack

Opening in the browser will result in the following error:

```bash
main.js:7242 Uncaught TypeError: _test__WEBPACK_IMPORTED_MODULE_0___default(...).add is not a function
    at ./src/index.js (main.js:7242:46)
    at __webpack_require__ (main.js:7280:33)
    at main.js:8496:27
    at main.js:8497:3
```

Will not appear in webpack because amdPlugin is imported by default in webpack.

https://github.com/webpack/webpack/blob/23c39437617d5ff8de4120911e728b0f56a5fed5/lib/WebpackOptionsApply.js#L361-L365

**Comment by hardfist** [comment]
amd support is low priority now, but pr welcome if you need it

**Comment by sunft1996** [comment]
> https://github.com/nanianlisao/rspack-bug-reproduction/tree/fix_amd_require

优先级可以提升一下吗，也遇到了

**Comment by sunft1996** [comment]
也遇到了，希望优先级能提升一下

**Comment by xc2** [comment]
Sorry but I'm closing this issue as there's already an issue tracking this feature:

#4313

Please subscribe that issue to stay tuned.

**Comment by sunft1996** [comment]
> > 也遇到了，希望优先级能提升一下
> 
> 你也是既加载了 amd loader 又需要 import 一个 umd 模块吗

是的，umd内部判断是amd环境了，最终导出amd格式
