### ISSUE TITLE
[Bug]: Unmatched version @rspack/core@0.5.9-canary-8778e17-20240328104834, @rspack/binding@0.5.9-canary-8778e17-20240328104834, @rspack/binding-linux-arm64-musl@0.5.8

### ISSUE THREAD

**Issue by linzebingo** [web-infra-dev/rspack#6101]
### Version

```sh
0.5.6
```

### Details

Unmatched version @rspack/core@0.5.9-canary-8778e17-20240328104834, @rspack/binding@0.5.9-canary-8778e17-20240328104834, @rspack/binding-linux-arm64-musl@0.5.8

![image](https://github.com/web-infra-dev/rsbuild/assets/12185104/afca0232-8514-4d90-ae44-0a9d8ddd7135)

maybe @rspack/binding-linux-arm64-musl don't have 0.5.9-canary-8778e17-2024032810483 version

after rollback to @rsbuild@0.5.4, problem resolved.

### Reproduce link

N/A

### Reproduce Steps

1、login linux-arm64 server
2、run rsbuild build

**Comment by chenjiahan** [comment]
Fixed: https://github.com/web-infra-dev/rsbuild/releases/tag/v0.5.7
