### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'set') in react-refresh-webpack-plugin

### ISSUE THREAD

**Issue by tzachbon** [web-infra-dev/rspack#6130]
### System Info

 System:
    OS: macOS 14.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 344.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/25528_1712483917618/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Projects/autodesk/acs-sc-web-platform/node_modules/.bin/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 123.0.6312.107
    Edge: 123.0.2420.81
    Safari: 17.2
Packages:
    "@module-federation/enhanced": "^0.1.2"
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.11"
    "@rsbuild/core": "^0.5.8"
    "@rspack/core": "^0.5.9"

## Description
While running the application, I encountered an unexpected TypeError. Here are the details:

**Command:** `rsbuild dev --open`
**Expected Result:** No crash and react hmr support
**Actual Result:** Application crashes with a TypeError
**Error Message:** 
```
<e> [webpack-dev-middleware] [Error:   × TypeError: Cannot read properties of undefined (reading 'set')
<e>   │     at Object.fn (/Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:309:47)
<e>   │     at SyncHook.callAsyncStageRange (/Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@rspack/core/dist/lite-tapable/index.js:215:21)
<e>   │     at SyncHook.callStageRange (/Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@rspack/core/dist/lite-tapable/index.js:233:14)
<e>   │     at QueriedHook.call (/Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@rspack/core/dist/lite-tapable/index.js:194:26)
<e>   │     at /Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@rspack/core/dist/Compiler.js:524:244
<e>   │     at last.function (/Users/x/Projects/autodesk/acs-sc-web-platform/node_modules/@rspack/core/dist/Compiler.js:685:28)
<e>   │ 
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

### Reproduce Steps

Add the plugin to the webpack config:
```
 this.compiler.options.plugins.push(new ReactRefreshPlugin());
```

**Comment by ahabhgk** [comment]
@hardfist I have an idea: add something like `unsupported()` (like `todo!()` in rust but works in runtime) to emit warnings for unsupported hooks and APIs, this can also detect which plugin we already supported

**Comment by hardfist** [comment]
> @hardfist I have an idea: add something like `unsupported()` (like `todo!()` in rust but works in runtime) to emit warnings for unsupported hooks and APIs, this can also help to detect which plugin we already supported

good idea，it helps for public api
