### ISSUE TITLE
[Bug]: first stats error not cleaned when rebuild

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#6160]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 625.61 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.20.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: 0.5.4 => 0.5.4 

### Details

In my case, when I ran rspack dev first I got an error, after fixed it, this error was still printed in the terminal (a new one not the previous log).

<img width="1003" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/25da8e2b-f9b4-4ce1-b46e-ffdce29f5814">

<img width="1082" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/c4f63fd5-ccda-416c-a135-6064589e84d9">

### Reproduce link

none

### Reproduce Steps

fake a dom structure error, such as:
<img width="1015" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/29153d9c-0a4d-4fcc-a011-648e40e3b695">

**Comment by h-a-n-a** [comment]
related https://github.com/web-infra-dev/rspack/issues/5961

**Comment by 9aoy** [comment]
duplicated
