### ISSUE TITLE
[Bug]: Use of global in class being replaced with __webpack__.g

### ISSUE THREAD

**Issue by JohnDaly** [web-infra-dev/rspack#6164]
### Details

Use of the `global` identifier is being replaced with `__webpack__.g` unexpectedly

## Input
```ts
class Example {
  constructor(global = false) {
    this.global = global;
  }
}
```

## Output
```ts
class Example {
    constructor(__webpack_require__.g = false){
        this.global = __webpack_require__.g;
    }
}
```

### Reproduce link

https://github.com/JohnDaly/rspack-global-in-class-repro/tree/main

### Reproduce Steps

1. Create a class that takes a parameter with the identifier `global` in the constructor
2. Bundle with `rspack` and notice that `global` is replaced with  `__webpack__.g`

**Comment by robert-irelan-tiktokusds** [comment]
Possibly related - I'm getting the following error when building my code (I've seen this on 0.6.0):

```
× JavaScript parsing error: Expected ',', got '.'
       ╭─[64625:1]
 64625 │ 
 64626 │ let CanvasLayerHandlerContribution = class {
 64627 │     constructor(__webpack_require__.g){
       ·                                    ─
 64628 │         this.global = __webpack_require__.g, this.type = "static", this.offscreen = !1;
 64629 │     }
       ╰────
```

**Comment by JohnDaly** [comment]
Looks like the behavior of v0.5.9 also generates code that is unexpected:

## Input
```ts
class Example {
  constructor(global = false) {
    this.global = global;
  }
}
```

## Output
```ts
class Example {
    constructor(global = false){
        this.global = __webpack_require__.g;
    }
}
```

The workaround to avoid this is to disable the [node.global](https://www.rspack.dev/config/node.html#nodeglobal) setting
