### ISSUE TITLE
[Bug]: The panic location includes the Rspack CI path

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#6192]
### System Info

Rspack v0.6.0

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 197.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/99377_1712756954621/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/99377_1712756954621/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/99377_1712756954621/bin/npm
    pnpm: 7.17.1 - ~/Library/Caches/fnm_multishells/99377_1712756954621/bin/pnpm
    bun: 0.1.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1

### Details

The panic location includes the Rspack CI path, is this expected?

![image](https://github.com/web-infra-dev/rspack/assets/7237365/00424cf0-5752-4b1a-bfcc-b6df9a74db0b)

### Reproduce link

https://github.com/colinaaa/rsbuild-vitest-crash-repro

### Reproduce Steps

1. pnpm i
2. pnpm vitest

**Comment by xc2** [comment]
please run vitest under `forks` mode via

```ts
import { defineProject } from 'vitest/config'

export default defineProject({
  test: {
     // pool: 'forks'
  }
});
```

running rspack in worker_threads has not been well tested yet.

**Comment by xc2** [comment]
sry never realized that this issue was related to the location path (*/ω＼*)

**Comment by chenjiahan** [comment]
Haha never mind~

**Comment by h-a-n-a** [comment]
Panic handler we've been using does not support mapping the location file. This can be achieved mapping the `print_panic_info` result and handle the panic by youself.

**Comment by chenjiahan** [comment]
Get it 👌
