### ISSUE TITLE
[Feature]: Make the rspack-dev-server dependency of cli optional?

### ISSUE THREAD

**Issue by bluetech** [web-infra-dev/rspack#6193]
### What problem does this feature solve?

rspack-cli depends on rspack-dev-server to support the `serve` and `preview` sub-commands. Since I am not using these commands (I only use `build`), I was wondering whether the dependency can be made optional in some way?

The reason for the request is that rspack-dev-server brings in 270 extra dependencies, including webpack itself. Also, `npm audit` complains about some of these dependencies.

<details><summary>npm audit report</summary>
<p>

```
express  <4.19.2
Severity: moderate
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc
fix available via `npm audit fix --force`
Will install @rspack/cli@0.0.6, which is a breaking change
node_modules/express
  @rspack/dev-server  <=0.0.0-ff9366411-20230221070252 || >=0.0.8
  Depends on vulnerable versions of express
  Depends on vulnerable versions of webpack-dev-middleware
  node_modules/@rspack/dev-server
    @rspack/cli  <=0.0.0-ff9366411-20230221070252 || >=0.0.8
    Depends on vulnerable versions of @rspack/dev-server
    node_modules/@rspack/cli

webpack-dev-middleware  6.0.0 - 6.1.1
Severity: high
Path traversal in webpack-dev-middleware - https://github.com/advisories/GHSA-wr3j-pwj9-hqq6
fix available via `npm audit fix --force`
Will install @rspack/cli@0.0.6, which is a breaking change
node_modules/webpack-dev-middleware

4 vulnerabilities (2 moderate, 2 high)
```

</p>
</details> 

### What does the proposed API of configuration look like?

I'm not sure what is the best way to achieve this, perhaps it can become an `optionalDependencies` and if it's not present and `serve` or `preview` is used, then an error is printed saying to install `@rspack/dev-server`.

**Comment by xc2** [comment]
i believe rspack cli requires dev-server package to be auto installed for development experience.

however there's no common way to make an npm dependency "optional" like gem's `:group` or rust's `feature`.

please consider pnpm's `pnpm.overrides`, yarn's `resolution`, npm's `overrides` to override `@rspack/dev-server` to a empty package from your project.

---

btw 1. `"optionalDependencies"` is just a thing as `"dependencies"`. it is always installed but will not break installation when building failed.

btw 2. the latest version of `@rspack/cli` is `0.6.1`

**Comment by bluetech** [comment]
> i believe rspack cli requires dev-server package to be auto installed for development experience.

Right, it's a helpful default.

> please consider pnpm's pnpm.overrides, yarn's resolution, npm's overrides to override @rspack/dev-server to a empty package from your project.

Didn't know about these options, thanks for the hint!

For reference, I got it to work like this:

- Add an empty stub project to a local directory `overrides/@rspack/dev-server`.
- Add `"@rspack/dev-server": "file:overrides/@rspack/dev-server"` to `devDependencies
- Add `"@rspack/dev-server": "file:overrides/@rspack/dev-server"` to `overrides`

> btw 1. "optionalDependencies" is just a thing as "dependencies". it is always installed but will not break installation when building is failed.

Oops, should have read more carefully.
