### ISSUE TITLE
[Bug]: Default identifiers not transformed in constructor parameters

### ISSUE THREAD

**Issue by JohnDaly** [web-infra-dev/rspack#6197]
### System Info

rspack 0.6.1

### Details

Identifiers that are used as default values of a constructor's parameters are not being transformed properly.

## Input
```ts
import { Foo } from './mod';

class Example {
  constructor(global = Foo) {
    this.global = global;
  }
}
```

## Output
```ts
/* harmony import */var _mod__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./mod */"./src/mod.js");

class Example {
    constructor(global = Foo){
        this.global = global;
    }
}
```

## Expected Output
```ts
/* harmony import */var _mod__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./mod */"./src/mod.js");

class Example {
    constructor(global = _mod__WEBPACK_IMPORTED_MODULE_0__.Foo){
        this.global = global;
    }
}
```

### Reproduce Steps

Create a class that has constructor parameters with default values that are identifiers.

Build with `rspack` and notice that the identifier is not transformed properly

**Comment by JohnDaly** [comment]
I think this is probably related to this change: https://github.com/web-infra-dev/rspack/pull/6183

**Comment by h-a-n-a** [comment]
Please use canary version published in https://github.com/web-infra-dev/rspack/pull/6198
