### ISSUE TITLE
[Bug]: OS can't spawn worker thread: Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by dm33tri** [web-infra-dev/rspack#6209]
### System Info

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (56) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 14.66 GB / 24.00 GB
    Container: Yes
    Shell: 5.0.0 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.0 - /usr/bin/npm

### Details

Using some versions of swc plugins on big codebases triggers this error. I am trying to create artificial example for this but I need many files.

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                               ⋮ 1 frame hidden ⋮                               
 2: clone
    at /build/glibc-vjB4T1/glibc-2.28/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  OS can't spawn worker thread: Resource temporarily unavailable (os error 11)
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447
```

I think this only happens on large codebases and only with `swc_core = "0.90.*"` (previous commit with `0.89.4` surprisingly worked with `@rspack/core@0.5.9-canary`)

Here are the versions of `swc_*` crates that mostly match `rspack` https://github.com/dm33tri/swc-plugin-mark-expressions/blob/master/Cargo.toml. 

### Reproduce Steps

```
 RUST_BACKTRACE=full DEBUG=rsbuild  rsbuild build -c rsbuild.config.ts
```

**Comment by h-a-n-a** [comment]
Would you confirm if this error happens all the time or occasionally? According to tokio: 
> There are no worker threads available to take the task and the OS failed to spawn a new one.

**Comment by dm33tri** [comment]
> Would you confirm if this error happens all the time or occasionally? According to tokio:

It happens constantly

**Comment by dm33tri** [comment]
I've tried a build with this `swc` patch and it works

Thanks!
