### ISSUE TITLE
[Bug]: rspack v0.6.0/v0.6.1 breaks if imports are directly used as default constructor parameters

### ISSUE THREAD

**Issue by ska-kialo** [web-infra-dev/rspack#6213]
### System Info

```
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 175.55 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v21.5.0/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
Browsers:
  Chrome: 123.0.6312.59
  Edge: 113.0.1774.35
  Safari: 17.4.1
npmPackages:
  @rspack/cli: ^0.6.1 => 0.6.1 
  @rspack/core: ^0.6.1 => 0.6.1 
  @rspack/plugin-react-refresh: ^0.6.1 => 0.6.1 
```

### Details

When bundling an app that uses framer-motion using rspack v0.6.0 or v0.6.1, framer-motion breaks.
It seems to be that the default value for the constructor parameter `KeyFrameResolver` of `MainThreadAnimation` is not touched during bundling but should be renamed to the corresponding import. See line 29 of [this file](https://yarnpkg.com/package?q=framer-motion&name=framer-motion&file=%2Fdist%2Fes%2Fanimation%2Fanimators%2FMainThreadAnimation.mjs) for the source.

### Example
Source:
```js
// default-value.js
export const defaultValue = 'default-value';

// render.js
import { defaultValue } from "./default-value";

class SomeClass {
    constructor(value = defaultValue) {
        this.value = value;
    }

    run() {
        console.log(this.value);
    }
}

export function render() {
    new SomeClass().run();
}
```

The following is the output currently. As you can see the module in question is imported but the constructor default parameter is not updated to reference this import.
```js
// somewhere above this is the `default-value` module
/* harmony import */var _default_value__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./default-value */"./src/default-value.js");

class SomeClass {
    constructor(value = defaultValue){
        this.value = value;
    }
    run() {
        console.log(this.value);
    }
}
function render() {
    new SomeClass().run();
}
```

Whereas extracting the default parameter to a const and using that as the default argument like this:
```js
// ...
import { defaultValue } from "./default-value";

const aliasedDefault = defaultValue;

class SomeClass {
    constructor(value = aliasedDefault) {
// ...
```

produces a working result:
```js
// ...
/* harmony import */var _default_value__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./default-value */"./src/default-value.js");

const aliasedDefault = _default_value__WEBPACK_IMPORTED_MODULE_1__.defaultValue;
class SomeClass {
    constructor(value = aliasedDefault){
// ...
```

### Reproduce link

https://github.com/ska-kialo/rspack-repro-framer-motion-issue

### Reproduce Steps

1. Build the app using `npm build`.
2. The webpack version logs `default-value` to the console.
3. The rspack version fails with `ReferenceError: defaultValue is not defined`.

**Comment by ska-kialo** [comment]
Note: I have updated the linked repro repository with a much simpler example that has the same issue.

**Comment by sfc-gh-jdaly** [comment]
https://github.com/web-infra-dev/rspack/issues/6197

Try out the canary mentioned here ^
