### ISSUE TITLE
[Feature]: Support function type for CssExtractRspackPlugin.filename and CssExtractRspackPlugin.chunkFilename

### ISSUE THREAD

**Issue by JohnDaly** [web-infra-dev/rspack#6215]
### What problem does this feature solve?

Allow the `filename` and `chunkFilename` to use functions to align with the APIs from `mini-css-extract-plugin`. Currently, these can only be configured with `string`. Functions allow for more flexibility to handle special cases for generated files.

The rationale is the same as `output.filename` and `output.chunkFilename`, mentioned here:
https://github.com/web-infra-dev/rspack/issues/3483 

### What does the proposed API of configuration look like?

The new APIs would align with those used in [mini-css-extract-plugin](https://www.npmjs.com/package/mini-css-extract-plugin#filename)

**Comment by dartess** [comment]
@JSerFeng hey, I see this issue is closed, but `CssExtractRspackPluginOptions`'s field `filename` is still a `string`. Should we expect it to become a `string | function`?

**Comment by hustcer** [comment]
Please make `output.filename.css`  accept a function too, thanks, we are looking forward for this feature in our production usage.

**Comment by xc2** [comment]
@dartess function is allowed actually while the type is not correct, we'll fix the type.

**Comment by xc2** [comment]
@hustcer rspack's `output.cssFilename` allows function, you might be asking a **rsbuild** feature, please file a new issue here: https://github.com/web-infra-dev/rsbuild/issues

btw, `tools.rspack.output.cssFilename` night help for you.
