### ISSUE TITLE
[Bug]: `childCompilation.errors.map` is not a function

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#6222]
### System Info

rspack 0.6.1

### Details

rspack's compilation errors structure is different from webapck's (Array). Unable to use `errors.map` api.

This causes an error when executing the following code and prevents the actual error from being thrown:
![img_v3_029s_8cb44b5f-a267-4749-a6da-812a908178bg](https://github.com/web-infra-dev/rspack/assets/22373761/6a1587c6-e865-45f9-afaf-8d6b7c5f5c9f)

https://github.com/jantimon/html-webpack-plugin/blob/v5.6.0/lib/child-compiler.js#L165-L167

### Reproduce Steps

https://github.com/web-infra-dev/rspack/blob/958b55764e46203b7969cf1e0bb4fec8a28b00b6/packages/rspack/src/Compilation.ts#L548-L577

**Comment by coder-xiaotian** [comment]
Let me add a map function to it.
