### ISSUE TITLE
[Bug]: Rspack不兼容Webpack performance配置项，官方是否有考虑支持？

### ISSUE THREAD

**Issue by mopduan** [web-infra-dev/rspack#6226]
### System Info

OS: Mac Sonoma 14.4.1
Node.js：18.9.0

### Details

Rspack不兼容Webpack performance配置项

### Reproduce Steps

官方是否会考虑支持？

**Comment by LingyuCoder** [comment]
The `SizeLimitsPlugin` does not have high priority. If you all willing, welcome to contribute

**Comment by inottn** [comment]
If possible, I would like to give it a try.

**Comment by hardfist** [comment]
> If possible, I would like to give it a try.

thanks in advance
