### ISSUE TITLE
[Bug]: Panic occurred at runtime - builtins.define: Failed to parse Member

### ISSUE THREAD

**Issue by hcbelias** [web-infra-dev/rspack#6227]
### System Info

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 270.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.volta/tools/image/node/20.10.0/bin/node
    Yarn: 3.3.0 - ~/.volta/tools/image/yarn/3.3.0/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/npm/10.2.3/bin/npm
    pnpm: 8.12.1 - ~/.volta/bin/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 123.0.6312.122
    Safari: 17.4.1
  npmPackages:
    @rspack/cli: ^0.5.9 => 0.5.9 
    @rspack/core: ^0.5.9 => 0.5.9 

### Details

Just started to notice this error when building the app - it looks like it is related to how I inject my env variables

When I run rspack:build, I get the following error message:

`anic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  builtins.define: Failed to parse Member(MemberExpr { span: 1..25#0, obj: Member(MemberExpr { span: 1..12#0, obj: Ident(Ident { span: 1..8#0, sym: "process", optional: false }), prop: Ident(Ident { span: 9..12#0, sym: "env", optional: false }) }), prop: Ident(Ident { span: 13..25#0, sym: "MIXPANEL_KEY", optional: false }) })
Location: crates/rspack_swc_visitors/src/define.rs:40`

### Reproduce Steps

Run rsbuild build

**Comment by hcbelias** [comment]
Just noticed that If I define my env variables like below - it works:

<img width="166" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4955014/47098d2a-0864-4566-b091-555c5f22d7a1">

But if I try to follow the recommendation and do like:
<img width="508" alt="image" src="https://github.com/web-infra-dev/rspack/assets/4955014/e282204a-26af-498d-bc31-d2be50833a32">

It fails

**Comment by xc2** [comment]
> Just noticed that If I define my env variables like below - it works:
> 
> <img alt="image" width="166" src="https://private-user-images.githubusercontent.com/4955014/322298344-47098d2a-0864-4566-b091-555c5f22d7a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTQxNzksIm5iZiI6MTcxMzE1Mzg3OSwicGF0aCI6Ii80OTU1MDE0LzMyMjI5ODM0NC00NzA5OGQyYS0wODY0LTQ1NjYtYjA5MS01NTVjNWYyMmQ3YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDQwNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVlOTllYWVkMjBmNzIwMjk3MDAzZDE5MGY0ODlhODE3YmFjYjFiMmIyMGJkOTQzNDFlZDkzMjhjMDJkNzEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kUTlvVoxgEI9Soseqh8dlpm1NV1JhHDYofJNOzUej6w">
> But if I try to follow the recommendation and do like: <img alt="image" width="508" src="https://private-user-images.githubusercontent.com/4955014/322298499-e282204a-26af-498d-bc31-d2be50833a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTQxNzksIm5iZiI6MTcxMzE1Mzg3OSwicGF0aCI6Ii80OTU1MDE0LzMyMjI5ODQ5OS1lMjgyMjA0YS0yNmFmLTQ5OGQtYmMzMS1kMmJlNTA4MzNhMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDQwNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JkYjU2M2JiNGQ2NTZhZDNiNTYxMmEwMjkzZmYzNmMzMzc3ZTg2YmZhZDNiNGRhNWViNjhjYzBlYTAwNjNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0-29ec6bYGnX_iKLPsceDaUoUKZfoSWWuMMAPQvY-7U">
> 
> It fails

@hcbelias yup you have to wrap string values with `JSON.stringify`.

i believe the document you referred has elaborated how's it coming.

@chenjiahan is there any plan that `source.globalVars` comes to rsbuild?

**Comment by chenjiahan** [comment]
No plan at the moment. We hope to maintain the atomicity of the configuration, and the functions of `source.define` and `source.globalVas` are too similar, so it is not appropriate to provide them at the same time.

**Comment by xc2** [comment]
I've closed this issue for not a bug. Feel free to reopen it if rspack should report a friendly message here to improve dx.
