### ISSUE TITLE
[Bug]: Cannot use external modules as constructor parameter default values

### ISSUE THREAD

**Issue by leewhite97** [web-infra-dev/rspack#6230]
### System Info

Rspack:0.6.1

### Details

code:
<img width="301" alt="image" src="https://github.com/web-infra-dev/rspack/assets/46445588/4f1a903a-b7c2-47bb-9719-5edb5c27cea4">

output:
![image](https://github.com/web-infra-dev/rspack/assets/46445588/5ebeca57-c68e-4547-807f-67ff6d9d67eb)

This problem occurs in the latest version

### Reproduce link

https://github.com/leewhite97/rspack-project

### Reproduce Steps

1.run `pnpm dev`
2.error:`Uncaught ReferenceError: React is not defined`

**Comment by xc2** [comment]
should have been fixed in https://github.com/web-infra-dev/rspack/pull/6198

please try out the nightly version.
