### ISSUE TITLE
[Bug]: Rspack 0.6.1 未支持以“import 'xx.css';”方式插入页面CSS

### ISSUE THREAD

**Issue by mopduan** [web-infra-dev/rspack#6240]
### System Info

OS: Mac Sonoma 14.4.1
Node.js：18.9.0
@rspack/core version: 0.6.1

### Details

Rspack 0.6.1 未支持以“import 'xx.css';”方式插入页面CSS。

### Reproduce Steps

1、在https://github.com/rspack-contrib/rspack-examples/tree/main/rspack/basic/src 新建xx.css并写入若干行样式代码；
2、在index.js里import 'xx.css';构建后页面没有找到CSS代码。

**Comment by xc2** [comment]
> ### System Info
> OS: Mac Sonoma 14.4.1 Node.js：18.9.0 @rspack/core version: 0.6.1
> 
> ### Details
> Rspack 0.6.1 未支持以“import 'xx.css';”方式插入页面CSS。
> 
> ### Reproduce link
> _No response_
> 
> ### Reproduce Steps
> 1、在https://github.com/rspack-contrib/rspack-examples/tree/main/rspack/basic/src 新建xx.css并写入若干行样式代码； 2、在index.js里import 'xx.css';构建后页面没有找到CSS代码。

请把 `package.json` 里面的 `"sideEffects": false` 删掉

**Comment by mopduan** [comment]
> > ### System Info
> > OS: Mac Sonoma 14.4.1 Node.js：18.9.0 @rspack/core version: 0.6.1
> > ### Details
> > Rspack 0.6.1 未支持以“import 'xx.css';”方式插入页面CSS。
> > ### Reproduce link
> > _No response_
> > ### Reproduce Steps
> > 1、在https://github.com/rspack-contrib/rspack-examples/tree/main/rspack/basic/src 新建xx.css并写入若干行样式代码； 2、在index.js里import 'xx.css';构建后页面没有找到CSS代码。
> 
> 请把 `package.json` 里面的 `"sideEffects": false` 删掉

使用的是Rspack Node.js API调用方式，是否支持把sideEffects传入配置？
