### ISSUE TITLE
[Bug]: Cyclic dependency from re-exported module error (v0.6.1)

### ISSUE THREAD

**Issue by dm33tri** [web-infra-dev/rspack#6243]
### System Info

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 170.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1
  npmPackages:
    @rspack/binding-linux-x64-gnu: ^0.6.1 => 0.6.1 

### Details

New import resolver introduced a tiny bug when importing re-exported modules from parent:

```javascript
// a.js:
import { b } from './b';

export const a = () => {
  return 'a';
};

b();

// b.js:
import { a } from ".";

export const b = () => {
  console.log(a())
}

// index.js:
import { a } from "./a"
import { b } from './b'

export { a, b };

b();

```

Gives the following error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'a')
    at Object.a (index.e69c31cd.js:29:78)
    at b (index.e69c31cd.js:23:52)
    at 840 (index.e69c31cd.js:13:39)
    at __webpack_require__ (index.e69c31cd.js:53:36)
    at 553 (index.e69c31cd.js:31:59)
    at __webpack_require__ (index.e69c31cd.js:53:36)
    at index.e69c31cd.js:75:27
    at index.e69c31cd.js:76:3
```

This is how module `a.js` looks compiled:
```
"553": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  a: function() { return /* reexport safe */ _a__WEBPACK_IMPORTED_MODULE_0__.a; }
});
/* harmony import */var _a__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./a */"840");
/* harmony import */var _b__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./b */"617");



(0, _b__WEBPACK_IMPORTED_MODULE_1__.b)();
}),

}
```

If I replace import with `import { a } from "./a";` it works without an error.

Is this expected behaviour?

### Reproduce Steps

`rsbuild build && rsbuild preview`

**Comment by LingyuCoder** [comment]
After testing in webpack, seems that webpack enable `optimization.concatenateModules` by default which can avoid this error. The error will also be caused by disabling it.

And in rspack, `optimization.concatenateModules` is still in the experimental stage and is not enabled by default. It also works well when I enable it.

You can also try to enable `optimization.concatenateModules`, and if you encounter any issues, please provide feedback.

**Comment by h-a-n-a** [comment]
This is expected. Without module concatenation, `a` exported from `./index` is not available until the module `./a` is evaluated.
