### ISSUE TITLE
[Bug]: rspack not support codemirror

### ISSUE THREAD

**Issue by SeonJun-Hwang** [web-infra-dev/rspack#6268]
### System Info

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.55 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.4.1
  npmPackages:
    @rspack/cli: ^0.6.1 => 0.6.2 
    @rspack/core: ^0.6.1 => 0.6.2 
    @codemirror/view: => ^6.26.3

### Details

rspack dosen't work

### Reproduce Steps

1. pnpm install @codemirror/view
2. typo `new EditorView({ ... })` on code
3. pnpm rspack --watch

then show error in shell

```
[rspack] Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
[rspack] Message:  internal error: entered unreachable code
[rspack] Location: crates/rspack_plugin_javascript/src/dependency/esm/provide_dependency.rs:83
```

**Comment by xc2** [comment]
tried to reproduce with a minimal setup and a typical ts setup with builtin:swc-loader with no luck.

please provide a repro repo.

btw, does the build using ProvidePlugin?
