### ISSUE TITLE
Support Module Federation library type:'module'

### ISSUE THREAD

**Issue by k4rl1** [web-infra-dev/rspack#6272]
When I use 

`moduleFederation: {
        options: {
            name: 'template-rspack-react',
            library: { type: 'module' },
            ...
`

when I build the application with 'rsbuild build' I get 

` JavaScript parsing error: 'import', and 'export' cannot be used outside of module code
      ╭─[4498:1]
 4498 │ var __webpack_exports__ = __webpack_require__("581");var __webpack_exports__get = __webpack_exports__.get;
 4499 │ var __webpack_exports__init = __webpack_exports__.init;
 4500 │ export { __webpack_exports__get as get, __webpack_exports__init as init };
      · ──────
 4501 │ 
 4502 │ })()
`

which is in my opinion related to the webpack config property environment: {module: true} which does not work with rspack but works fine with webpack.

`module.exports = {
    output: {
        environment: { module: true },
    },`

https://webpack.js.org/configuration/output/#outputenvironment

Thanks!

**Comment by ahabhgk** [comment]
Already supported

> which is in my opinion related to the webpack config property environment: {module: true} which does not work with rspack but works fine with webpack.

What problem have you encountered? Would you provide a minimal reproduce?

**Comment by k4rl1** [comment]
Will post a demo today

**Comment by k4rl1** [comment]
Here is the demo: https://github.com/k4rl1/rspack-repro-mf-module-demo
npm run build:rsbuild tries to build it with rsbuild and fails
npm run build:webpack builds it with webpack and works

Adding:
```
 experiments: {
    outputModule: true,
  },
```
AND
` environment: { module: true, dynamicImport: true }`

like it is in the webpack config which is necessary to get it working in webpack does not do anything in the rspack config.

**Comment by ahabhgk** [comment]
Have you tried using the same configuration in rspack? It should work if you also add `environment: { module: true, dynamicImport: true }` in rspack

**Comment by k4rl1** [comment]
Yes, this is what I mentioned above. It does not work in the rspack config but it works fine in webpack which is the reason a opened this ticket.

**Comment by ahabhgk** [comment]
I see.. Rspack didn't extract the entry module out of the iife https://github.com/web-infra-dev/rspack/issues/6402, which cause the parsing error above, we will fix it in the next few days, thanks for report this

**Comment by k4rl1** [comment]
Great to hear, thanks for the effort you put into it :) I will happily test it when it's done.

**Comment by ahabhgk** [comment]
Could you try the latest rsbuild, and add `config.experiments.outputModule = true;` in `tools.rspack`, rsbuild didn't enable it by default, and in the `webpack.config.cjs` it's enabled, that's why webpack build succeed but rsbuild failed

**Comment by k4rl1** [comment]
Ah thank you was not aware that it works like that. Thanks for your help :) Works fine now.
