### ISSUE TITLE
[Bug]: rspack module comments can't be removed when set comments: 'some'

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#6276]
### System Info

rspack 0.6.2

### Details

`/*!` is a specail comment and Rsbuild will extract all legal comments to a .LEGAL.txt file and link to them with a comment by default.

when I run `rsbuild build`, I find that many rspack module info comments are saved in `.LEGAL.txt`. 

by the way, if I set `legalComments: inline`, they all remain in the js bundle file.

https://rsbuild.dev/config/output/legal-comments

<img width="647" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/08e41678-f5b3-4eba-85ae-fc56abafc99f">

<img width="993" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/ee3ed805-1e0b-4bc6-b77a-028899ef4224">

### Reproduce link

https://rsbuild.dev/guide/start/quick-start#creating-an-rsbuild-project

### Reproduce Steps

1. npm create rsbuild@latest 
2. pnpm build
3. see dist file

**Comment by LingyuCoder** [comment]
relate to https://github.com/web-infra-dev/rspack/issues/5254
