### ISSUE TITLE
[Bug]: ts-loader runs into an error with rspack

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6306]
### System Info

System:
OS: Linux 6.2 Ubuntu 20.04.6 LTS (Focal Fossa)
CPU: (32) x64 AMD EPYC 7763 64-Core Processor
Memory: 113.67 GB / 125.78 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 20.11.0 - /usr/local/share/nvm/versions/node/v20.11.0/bin/node
Yarn: 1.23.19 - /usr/bin/yarn
npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.0/bin/npm
Watchman: 20240317.093234.0 - /usr/local/bin/watchman
Browsers:
Chrome: 124.0.6367.60
npmPackages:
@rspack/cli: 0.6.2 => 0.6.2
@rspack/core: 0.6.2 => 0.6.2

### Details

So running into the below error when using ts-loader for some files. (for other files I am using builtin:swc-loader) . 

```
ERROR in ../../someFile.graphql.ts
  × Module build failed:
  ╰─▶   × TypeError: Cannot read properties of undefined (reading 'buildMeta')
        │     at setModuleMeta (/workspaces/teams-modular-packages/node_modules/ts-loader/dist/index.js:62:31)
        │     at makeSourceMapAndFinish (/workspaces/teams-modular-packages/node_modules/ts-loader/dist/index.js:56:5)
        │     at successLoader (/workspaces/teams-modular-packages/node_modules/ts-loader/dist/index.js:39:5)
```
And this error is coming from the following piece of code in ts-loader:

```
function setModuleMeta(loaderContext, instance, fileVersion) {
    // _module.meta is not available inside happypack
    if (!instance.loaderOptions.happyPackMode &&
        loaderContext._module.buildMeta !== undefined) {
        // Make sure webpack is aware that even though the emitted JavaScript may be the same as
        // a previously cached version the TypeScript may be different and therefore should be
        // treated as new
        loaderContext._module.buildMeta.tsLoaderFileVersion = fileVersion;
    }
}
```
I do not run into this error with webpack. 
Currently I am getting around this issue with setting happyPackMode as true for rspack. 

### Reproduce Steps

try using ts-loader for some .tsx. file -> should repro this error.

**Comment by h-a-n-a** [comment]
`LoaderContext` does not support `_module` yet, but PR is welcome

**Comment by coder-xiaotian** [comment]
> `LoaderContext` does not support `_module` yet, but PR is welcome

I would like to give it a try.

**Comment by h-a-n-a** [comment]
@coder-xiaotian Adding custom fields to `buildMeta` does not quite reasonable while we need to pass the value back and forth from rust to node. This is not related to this issue, but exposing a readonly `_module` is fine.

**Comment by coder-xiaotian** [comment]
> @coder-xiaotian Adding custom fields to `buildMeta` does not quite reasonable while we need to pass the value back and forth from rust to node. This is not related to this issue, but exposing a readonly `_module` is fine.@coder-xiaotian 在 `buildMeta` 中添加自定义字段不太合理，而我们需要在 rust 和节点之间来回传递值。这与此问题无关，但公开只读 `_module` 就可以了。

Ok, Get it.

**Comment by viqcinese-axur** [comment]
Any follow-ups here? Would love to see typescript errors integrated with hot refresh

**Comment by coder-xiaotian** [comment]
> Any follow-ups here? Would love to see typescript errors integrated with hot refresh

I have committed my code to fix ts-loader error.
