### ISSUE TITLE
[Bug]: require("@rspack/core").version incorrectly returns the "webpackVersion"

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6307]
### System Info

N/A

### Details

need to add the rspack version info for telemetry purposes. However the below code incorrectly returns the "webpackVersion" and not the "version" property. 

![image](https://github.com/web-infra-dev/rspack/assets/93791633/24e72cdb-9e4b-4525-bd2c-4fa224771c86)

The following code returns version as "5.75.0" instead of 0.6.2

const {version} = require("@rspack/core")

### Reproduce Steps

Please refer to details section above.

**Comment by hardfist** [comment]
use require('@rspack/core').rspackVersion instead, `version` is used for compatibility for webpack plugin
