### ISSUE TITLE
[Bug]:v0.6.4 配置namedExports无效

### ISSUE THREAD

**Issue by NexxLuo** [web-infra-dev/rspack#6339]
### Version

```sh
windows
chrome
@rsbuild/core 0.6.4
```

### Details

0.5.9一切运行正常，更新到0.6.4后，node_modules下的less文件均无法使用默认导出（报错`Cannot read properties of undefined (reading 'test')`） ,`test`为less文件中的类名；

参照0.6.0的发布文档，通过config.module.parser手动配置namedExports依然无效;

场景：
对node_modules中某一个包的less文件进行cssModule处理；
如codesandbox中的`nexx-test-less`，包中使用了less文件`import styles from "./style.less"`

### Reproduce link

[codesandbox](https://codesandbox.io/p/github/NexxLuo/rsbuild-codesandbox-example/main?file=%2Frsbuild.config.mjs%3A11%2C7&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv6tk5ks0006356fjcslivum%2522%252C%2522sizes%2522%253A%255B88.90688259109312%252C11.093117408906878%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv6tk5ks0002356fzoyeva4o%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv6tk5ks0004356fh3vcftfm%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv6x3hnq013c356hpuqmfa2a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv6tk5ks0005356f5ujar2c4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv6tk5ks0002356fzoyeva4o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6tk5ks0001356f72y8sowz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv6uj3tm0002356h4jm71419%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A1%257D%255D%257D%252C%257B%2522id%2522%253A%2522clv6x98sw0002356n2yoa4r6z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A7%257D%255D%252C%2522filepath%2522%253A%2522%252Frsbuild.config.mjs%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv6tk5ks0002356fzoyeva4o%2522%252C%2522activeTabId%2522%253A%2522clv6x98sw0002356n2yoa4r6z%2522%257D%252C%2522clv6tk5ks0005356f5ujar2c4%2522%253A%257B%2522id%2522%253A%2522clv6tk5ks0005356f5ujar2c4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clv6tlor000au356f8n9d7hin%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv6tlor000au356f8n9d7hin%2522%257D%252C%2522clv6tk5ks0004356fh3vcftfm%2522%253A%257B%2522id%2522%253A%2522clv6tk5ks0004356fh3vcftfm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6tk5ks0003356fgmuybnz8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clv6tk668000mdoi686yr4j5l%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clv6tkk7x0061356fshqw7lds%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv6tkk7x0061356fshqw7lds%2522%257D%252C%2522clv6x3hnq013c356hpuqmfa2a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6x3fcr0138356hir8zyynl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clv6x3ipa001kdoi61k13efhb%2522%257D%255D%252C%2522id%2522%253A%2522clv6x3hnq013c356hpuqmfa2a%2522%252C%2522activeTabId%2522%253A%2522clv6x3fcr0138356hir8zyynl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Reproduce Steps

访问上面的codesandbox库，查看控制台输出信息

**Comment by chenjiahan** [comment]
done👌

**Comment by ahabhgk** [comment]
虽然这里配置了 `namedExports: false`，并且 node_modules 中的 index.js 也是 `import styles from "./styles.less";` 这样引入的，但 node_modules 这个包实际的代码会经过 father-build 打包成如下 cjs：

```js
var _style = _interopRequireDefault(require("./style.less"));
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

所以实际 Rspack 打包时读到的代码是这份 cjs，Rspack v0.5.9 能够正常工作是因为之前并没有给 css module 添加 `__esModule`:

v0.5.9 `require("./style.less")` 的结果:

```js
Object { test: "xxx (hash of the class name)" }
```

v0.6+ `require("./style.less")` 的结果:

```js
Object {
  __esModule: true, // <-- 注意这里
  test: "xxx (hash of the class name)",
}
```

这就导致 `_interopRequireDefault` 这个函数返回了不同的结果

但实际上 v0.5.9 的行为严格上来说并不正确，v0.6+ 默认添加 `__esModule` 才是更为常见的行为，webpack experiments.css、style-loader、css-loader、mini-css-extract-plugin loader 都会默认添加这个 `__esModule`，但 style-loader、css-loader 和 mini-css-extract-plugin loader [提供了选项不添加 `__esModule`，来兼容 cjs](https://github.com/webpack-contrib/mini-css-extract-plugin?tab=readme-ov-file#esmodule)，目前 webpack experiments.css 和 rspack experiments.css 还没有提供该选项

目前有以下方案：
1. rspack experiments.css 实现 `esModule` 配置，需要先在 webpack experiments.css 实现，所以花费时间可能会比较久
2. 使用 rspack.CssExtractPlugin，该插件对齐 mini-css-extract-plugin，并开启 `esModule: false`
3. 引这个包的 esm 格式的产物

**Comment by NexxLuo** [comment]
@xc2 `rspack.CssExtractPlugin`在`rsbuild`中该如何使用

**Comment by chenjiahan** [comment]
Rsbuild 近期会默认切换到 `rspack.CssExtractPlugin`, PR：https://github.com/web-infra-dev/rsbuild/pull/1577

预计还需要 1～2 周进行测试验证

**Comment by xc2** [comment]
@NexxLuo 如果比较紧急的话可以用 bundlerChain 来临时使用，这里有一个最小的例子：

```ts
import { defineConfig } from "@rsbuild/core";

export default defineConfig({
  output: {
    // 临时借用 injectStyle 这个配置项来自动配置 css-loader
    injectStyles: true,
  },
  tools: {
    bundlerChain(chain, { CHAIN_ID }) {
      const coreRequire = require("node:module").createRequire(require.resolve("@rsbuild/core"));
      const { CssExtractRspackPlugin } = require(coreRequire.resolve("@rspack/core"));

      chain.plugin("--css-extract").use(CssExtractRspackPlugin, [{ /* plugin options */ }]);

      for (const styleRuleId of [CHAIN_ID.RULE.CSS, CHAIN_ID.RULE.LESS, CHAIN_ID.RULE.SASS]) {
        const rule = chain.module.rule(styleRuleId);

        rule.uses.delete(CHAIN_ID.USE.STYLE);
        rule.use("--css-extract").loader(CssExtractRspackPlugin.loader).before(CHAIN_ID.USE.CSS);
      }
    },
  },
});

```

**Comment by NexxLuo** [comment]
0.6.15版本是还没包含这个更改吗

**Comment by xc2** [comment]
> 0.6.15版本是还没包含这个更改吗

0.7.0 会包含

**Comment by leimonio** [comment]
I'm testing with latest release candidate `v0.7.0-beta.1` and this issue is not resolved for me. 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'offset')
    at eval (eval at 51082 (main.bundle.js:1:489113), <anonymous>:82:96)
```
where offset is defined as `{importedModule}.default.offset`.

**Comment by leimonio** [comment]
I was able to resolve the issue by setting `esModule: false` in the `generator`, as below. Thanks to @hardfist 

```
 module: {
      generator: {
        'css/auto': {
          exportsOnly: true,
          exportsConvention: 'camel-case-only',
          esModule: false,
          localIdentName: isDev ? '[path][name][ext]__[local]' : '[hash]',
        },
        css: {
          exportsOnly: true,
          exportsConvention: 'camel-case-only',
          esModule: false,
        },
        'css/module': {
          exportsOnly: true,
          esModule: false,
          exportsConvention: 'camel-case-only',
          localIdentName: isDev ? '[path][name][ext]__[local]' : '[hash]',
        },
      },
      ...
 }
```
