### ISSUE TITLE
[Bug]:  Scss Module not work

### ISSUE THREAD

**Issue by childrentime** [web-infra-dev/rspack#6350]
### System Info

 System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M3
    Memory: 65.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.62
    Edge: 124.0.2478.51
    Safari: 17.1
  npmPackages:
    @rspack/cli: 0.6.2 => 0.6.2 
    @rspack/core: 0.6.2 => 0.6.2 
    @rspack/plugin-react-refresh: 0.6.2 => 0.6.2 

### Details

使用rspack-cli创建一个脚手架项目，安装`sass sass-loader`，参考https://www.rspack.dev/zh/guide/tech/css#sass，修改rspack.config.js。然后将 `App.css`文件修改为 `App.module.scss` 文件，并且使用 `import styles from "./App.module.scss";`引入。运行项目之后控制台报错，因为styles的值是 `undefined`。

<img width="973" alt="image" src="https://github.com/web-infra-dev/rspack/assets/58261676/54fd28ec-044a-485a-9df4-c1af8b23577b">

### Reproduce link

https://github.com/childrentime/rspack-project

### Reproduce Steps

```sh
pnpm i
pnpm dev
```
```[tasklist]
### Tasks
```

**Comment by SyMind** [comment]
You should use with namespace import like `import * as styles from "./App.module.scss";`.

If you want to use with default import, should set `module.parser.css.namedExports=true`.
