### ISSUE TITLE
[Feature]: request to add watchOptions.aggregaTimeOut 

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6356]
### What problem does this feature solve?

This would be benefitting developer productivity in scenarios where they are modifying multiple files at once, and want to recompile and reload once for all of them . 

Fir instance we have a scenario where modifying/saving a file generates an artefact in a particular directory which is also watched .  So we want to trigger re-compile after a certain timeout , say like 300ms so as to ensure that artefact is generated. 

 
https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout

### What does the proposed API of configuration look like?

Here is the webpack implementation for it :
https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout

**Comment by wxiaoyun** [comment]
It seems this feature is already implemented by importing WatchPack?

There is even a performance PR regarding this: https://github.com/web-infra-dev/rspack/pull/4724/files

**Comment by h-a-n-a** [comment]
Closed as finished
