### ISSUE TITLE
[Bug]: `WEBPACK_SERVE` environment variable is set when running `rspack` builds

### ISSUE THREAD

**Issue by JohnDaly** [web-infra-dev/rspack#6359]
### System Info

`rspack` v0.6.3

### Details

The `WEBPACK_SERVE` environment variable, which can be used to determine if the `webpack-dev-server` is active, is surprisingly enabled when running `rspack` for production builds.

This means that `WEBPACK_SERVE` cannot be relied upon within the `rspack.config.js` to conditionally run code.

Here is how it's getting set:
- The `@rspack/cli` package imports `ServeCommand` ([code](https://github.com/web-infra-dev/rspack/blob/90f81d72830ac14205429b722407e3adcc7eb564/packages/rspack-cli/src/rspack-cli.ts#L12))
- `@rspack/dev-server` is imported ([code](https://github.com/web-infra-dev/rspack/blob/90f81d72830ac14205429b722407e3adcc7eb564/packages/rspack-cli/src/commands/serve.ts#L2))
- `webpack-dev-server` is imported ([code](https://github.com/web-infra-dev/rspack/blob/90f81d72830ac14205429b722407e3adcc7eb564/packages/rspack-dev-server/src/server.ts#L17))
- `WEBPACK_SERVE` is set to true ([code](https://github.com/webpack/webpack-dev-server/blob/d1fcc72011840a74025b861dee56697b14d8f196/lib/Server.js#L207))

### Reproduce Steps

Add the following to the configuration file used by `rspack`:

```js
console.log(`Is WEBPACK_SERVE set: ${process.env.WEBPACK_SERVE}`);
```

Run a build with `rspack` and notice that the following is logged to the console:
```
Is WEBPACK_SERVE set: true
```

**Comment by xc2** [comment]
a recommended alternative:

```js
// rspack.config.js

module.exports = (env) => {
  const isServe = env.RSPACK_SERVE;
  return {
    // config
  }
}
```

webpack-cli loads `webpck-dev-server` on demand so the problem won't happen on webpack-cli alone.

will try to make it to be loaded on demand
