### ISSUE TITLE
[Bug]: legalComments issue - not executable code if we retain comments

### ISSUE THREAD

**Issue by Tsymalyi** [web-infra-dev/rspack#6366]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 1.92 GB / 15.31 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 121.0.6167.139
    Chromium: 124.0.6367.60
    Firefox: 124.0.2
  npmPackages:
    @rsbuild/core: ^0.6.6 => 0.6.6 
    @rsbuild/plugin-react: ^0.6.6 => 0.6.6
```

### Details

In production mode we have not exucutable code for libraries with comments. 
**lib-lodash.js** example without **legalComments** property

`...    /*! ./_stackHas */.nodeType&&t,i=u&&u.exports===o?e.Buffer:void  ....`

Error in browser:
![errorLodash](https://github.com/web-infra-dev/rsbuild/assets/15413557/cd7989a9-e96e-4aa8-acb8-436d655ad61f)

It can be fixed by setting **legalComments ='none'** 
In this case we have executable code with webpack wrapper
![correct](https://github.com/web-infra-dev/rsbuild/assets/15413557/318de9e2-31bf-4c41-8be8-893555b58475)

**rsbuild.config.js**

>
```javascript
const isProd = process.env.NODE_ENV === 'production';
const devDefaultFilename = {
  js: '[name].js',
  css: '[name].css',
  svg: '[name].[contenthash:8].svg',
  font: '[name].[contenthash:8][ext]',
  image: '[name].[contenthash:8][ext]',
  media: '[name].[contenthash:8][ext]',
};
// Production files names
const prodDefaultFilename = {
  js: '[name].js?[contenthash:8]',
  css: '[name].css?[contenthash:8]',
  svg: '[name].svg?[contenthash:8]',
  font: '[name].[ext]?[contenthash:8]',
  image: '[name].[ext]?[contenthash:8]',
  media: '[name].[ext]?[contenthash:8]',
};
export default defineConfig({
  dev: {
    hmr: true,
    cache: false,
    setupMiddlewares: isProd
      ? []
      : [
          (middleware) => {
            middleware.unshift(getSeverInstance());
          },
        ],
  },
  server: {
    port: process.env.PORT || 3000,
  },
  performance: {
    buildCache: false,
  },
  plugins: [pluginReact()],
  tools: {
    swc: {
      jsc: {
        experimental: {
          plugins: [['swc-plugin-jsx-control-statements', {}]],
        },
      },
    },
    rspack(config, { appendPlugins }) {
      // Only register the plugin when RSDOCTOR is true, as the plugin will increase the build time.
      if (process.env.RSDOCTOR === 'true') {
        appendPlugins(
          new RsdoctorRspackPlugin({
            // plugin options
          })
        );
      }
    },
  },
  html: {
    template: './public/index.html',
  },
  output: {
    sourceMap: {
      js: 'source-map',
    },
    cleanDistPath: true,
    charset: 'utf8',
    distPath: {
      root: 'build',
    },
    dataUriLimit: 0,
    filename: isProd ? prodDefaultFilename : devDefaultFilename,
  },
});
```  

### Reproduce link

Don't have

### Reproduce Steps

1. Add lodash to your project    
   `"lodash": "^4.17.21"`
2. Run **rsbuild build**

**Comment by chenjiahan** [comment]
A minimal reproduction repo: https://github.com/chenjiahan/rsbuild-repro-invalid-legal-comments

Setps:

1. pnpm i
2. pnpm build

Open dist/static/js/index.js, there are three possible random results:

1. empty file:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/2f90f202-584e-497b-91b0-cb2f0c38d102)

2. invalid comments:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/9b53ec18-3ae8-4393-a90d-afb556813443)

3. correct comments:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/b9b72d01-84cf-47f2-a2c9-ecfdbf6bcc33)

**Comment by LingyuCoder** [comment]
There are three part of this issue:
- Comment like `/*! lodash*/` should not be generated by default, controled by `output.pathinfo`, this has been fixed by https://github.com/web-infra-dev/rspack/pull/6326
- Filename with content hash should not has query while writing `.LICENSE.txt` files, I will try to fix it in https://github.com/web-infra-dev/rspack/pull/6386
- License of javascript source file which is in node_modules with leading comments lost during parsing phase, seems like some config of swc parser is different with swc-loader ([repro](https://github.com/LingyuCoder/rspack-lost-license-bug)) cc @h-a-n-a
