### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rspack#6372]
### System Info

System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^0.6.1",
    "@rsbuild/plugin-vue2": "^0.6.1",

### Details

插件在webpack中可以使用，在rspack中报错TypeError: Cannot read properties of undefined (reading 'set')

### Reproduce link

https://github.com/wengjiacheng/rspack-repro

### Reproduce Steps

npm run dev:webapck
npm run dev:rspack 会报错

**Comment by h-a-n-a** [comment]
如果还有其他问题欢迎重开 issue～

**Comment by wengjiacheng** [comment]
@h-a-n-a 
我更改成new compiler.webpack.DefinePlugin不报错了，当时编译好像没生效
![33333](https://github.com/web-infra-dev/rspack/assets/24770388/80b90572-a599-417f-8389-809b56614ae2)
我在插件中设置了一个值
在webpack中是可以编译的
<img width="430" alt="12233" src="https://github.com/web-infra-dev/rspack/assets/24770388/93f8fa8b-0ad9-422d-b79a-0b5a8df7a4b3">
但是在rspack中没有编译
<img width="395" alt="22222111" src="https://github.com/web-infra-dev/rspack/assets/24770388/0c4095b0-0ffe-499d-8573-fdeb0326e7a6">
并且在控制台有报错信息
<img width="1437" alt="1221111" src="https://github.com/web-infra-dev/rspack/assets/24770388/5b1a0c12-758c-4736-a2c0-18059ba887e2">

**Comment by h-a-n-a** [comment]
> @h-a-n-a 我更改成new compiler.webpack.DefinePlugin不报错了，当时编译好像没生效 ![33333](https://private-user-images.githubusercontent.com/24770388/325914424-80b90572-a599-417f-8389-809b56614ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjM1MzUsIm5iZiI6MTcxNDEyMzIzNSwicGF0aCI6Ii8yNDc3MDM4OC8zMjU5MTQ0MjQtODBiOTA1NzItYTU5OS00MTdmLTgzODktODA5YjU2NjE0YWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMGFiNjFhYzRiYjY3OGYzMGNmMTBjMGY3NDYwOTk3MjczMTU1MzE4MjU0ZWM1MjBkZDQ1YjQwMDgzNDY1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fK5RaX0wD4v0rpl6XWrt2G34xcOnoRvdRP6G2jwiDc4) 我在插件中设置了一个值 在webpack中是可以编译的 <img alt="12233" width="430" src="https://private-user-images.githubusercontent.com/24770388/325914651-93f8fa8b-0ad9-422d-b79a-0b5a8df7a4b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjM1MzUsIm5iZiI6MTcxNDEyMzIzNSwicGF0aCI6Ii8yNDc3MDM4OC8zMjU5MTQ2NTEtOTNmOGZhOGItMGFkOS00MjJkLWI3OWEtMGI1YThkZjdhNGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YzAzYmY4ZjJjYzU1ZDdlOGY1MTc3NDMzZmRjMjc1ZTk0YTUxNDE4OTcxOTY5ZGU3MTIzZWI1OGRiNDhjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jhuaprnzrxCDMKtpqnMEzs2MNDp52AQglQFtzWL5bLU"> 但是在rspack中没有编译 <img alt="22222111" width="395" src="https://private-user-images.githubusercontent.com/24770388/325914749-0c4095b0-0ffe-499d-8573-fdeb0326e7a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjM1MzUsIm5iZiI6MTcxNDEyMzIzNSwicGF0aCI6Ii8yNDc3MDM4OC8zMjU5MTQ3NDktMGM0MDk1YjAtMGZmZS00OTlkLTg1NzMtZmRlYjAzMjZlN2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTkwYjE3NGM0ZTUyYmUyYTE4ZjY3NWY3NDI0NzJkYWRkNTI2MmFiZTZlOGI5NjQzMzNjZmI3N2Y0MDIxNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GFHLLrXm1TsriLghInYsy2AcdCc2DDN-5kO59P9C64"> 并且在控制台有报错信息 <img alt="1221111" width="1437" src="https://private-user-images.githubusercontent.com/24770388/325914892-5b1a0c12-758c-4736-a2c0-18059ba887e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjM1MzUsIm5iZiI6MTcxNDEyMzIzNSwicGF0aCI6Ii8yNDc3MDM4OC8zMjU5MTQ4OTItNWIxYTBjMTItNzU4Yy00NzM2LWEyYzAtMTgwNTliYTg4N2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5MjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDI1N2M0ZWM4MzMyMGUzNjI5ODk4NWUzZTIzNjBlNWFjY2M0ZTNlYzY0MTZkZGI2YzliMzc0ZTU0M2NkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzxiROgTXecqbG2TEk7kH6E8LFfYQl2ygcqMIccvpNc">

可以看下产物中的结果吗？上述截图是否是根据 source-map 还原的代码片段？

**Comment by wengjiacheng** [comment]
上面代码我没有开启source-map
https://github.com/wengjiacheng/rspack-repro 这有个demo，这个可以吗  ？
npm run dev:webpack
npm run dev:rspack

**Comment by wengjiacheng** [comment]
@h-a-n-a 你好，编译好像没生效问题，找到问题了吗？

**Comment by h-a-n-a** [comment]
> @h-a-n-a 你好，编译好像没生效问题，找到问题了吗？

@wengjiacheng 能否根据产物结果确认一下 `DefinePlugin` 是否生效？

**Comment by wengjiacheng** [comment]
@h-a-n-a 打包测试了，产物里是编译的了的
<img width="603" alt="123" src="https://github.com/web-infra-dev/rspack/assets/24770388/23a5e18c-2c5e-4959-9d70-a2b9c913b000">
这个是rspack的
<img width="529" alt="456" src="https://github.com/web-infra-dev/rspack/assets/24770388/7fc451ab-1b8f-46c9-9cfa-099c9eb4418b">
这个是webpack

**Comment by h-a-n-a** [comment]
> @h-a-n-a 打包测试了，产物里是编译的了的 <img alt="123" width="603" src="https://private-user-images.githubusercontent.com/24770388/326243226-23a5e18c-2c5e-4959-9d70-a2b9c913b000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTUxODAsIm5iZiI6MTcxNDI5NDg4MCwicGF0aCI6Ii8yNDc3MDM4OC8zMjYyNDMyMjYtMjNhNWUxOGMtMmM1ZS00OTU5LTlkNzAtYTJiOWM5MTNiMDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNTUzZTQ2MTg0MjhmOGNlNjY1ZTA2YWUwZmM4YmQ5ZTY5Y2IzMjg0MTQzNjk0MmIzYTVmOGQ2YzE5ODMyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.77nmEdZyl9ZZKJT45rw71TDKYL2WowYNuXKjRJWQJaU"> 这个是rspack的 <img alt="456" width="529" src="https://private-user-images.githubusercontent.com/24770388/326243257-7fc451ab-1b8f-46c9-9cfa-099c9eb4418b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTUxODAsIm5iZiI6MTcxNDI5NDg4MCwicGF0aCI6Ii8yNDc3MDM4OC8zMjYyNDMyNTctN2ZjNDUxYWItMWI4Zi00NmM5LTljZmEtMDk5YzllYjQ0MThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMGI5NzIwYzZiMTQ3YWIyOTU4YWQ3YWJmNzcxMzJhODhiMWM1YmM5ZjViZWYwZDZhZDIyODM2Y2FkMDk5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jkafjA9CJR3lV_zStwuV6NnY8AbX3U5JiOtOvUrLlck"> 这个是webpack

@wengjiacheng 那 `DefinePlugin` 这部分就没有问题了，可以看看其他方面是不是有不符合预期的部分。如果有其他关于 rspack 的问题可以开新的 issue 处理
