### ISSUE TITLE
[Feature]: Support moment-locales-webpack-plugin

### ISSUE THREAD

**Issue by SyMind** [web-infra-dev/rspack#6373]
### What problem does this feature solve?

Easily remove unused Moment.js locales when building with webpack.

https://www.npmjs.com/package/moment-locales-webpack-plugin

### What does the proposed API of configuration look like?

const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

```js
module.exports = {
    plugins: [
        // To strip all locales except “en”
        new MomentLocalesPlugin(),
 
        // Or: To strip all locales except “en”, “es-us” and “ru”
        // (“en” is built into Moment and can’t be removed)
        new MomentLocalesPlugin({
            localesToKeep: ['es-us', 'ru'],
        }),
    ],
};
```

**Comment by escaton** [comment]
This actually enables `ContextReplacementPlugin` which is indicated as `Unsupported yet` [here](https://www.rspack.dev/plugins/webpack/index) 🎉 Great work!

**Comment by obennett-m** [comment]
> This actually enables `ContextReplacementPlugin` which is indicated as `Unsupported yet` [here](https://www.rspack.dev/plugins/webpack/index) 🎉 Great work!

It doesn't based on my testing. The below still fails :-(
```
const rspack = require('@rspack/core')
...

  plugins: [
    new rspack.ContextReplacementPlugin(/moment[\/\\]locale$/, /(da|de|fr|es|en|it|nl|pt|sv)$/),
  ],
...
```

**Comment by escaton** [comment]
Works for me: `new webpack.ContextReplacementPlugin`

**Comment by obennett-m** [comment]
> Works for me: `new webpack.ContextReplacementPlugin`

It seems you still have webpack installed in your project.  If you use the same require line: `const rspack = require('@rspack/core')` what happens then? 
Here are the version I'm using btw:
```
    "@rspack/cli": "^0.7.5",
    "@rspack/core": "^0.7.5",
 ```

**Comment by escaton** [comment]
If you look under the hood of [moment-locales-webpack-plugin](https://www.npmjs.com/package/moment-locales-webpack-plugin) it uses `webpack.ContextReplacementPlugin`. it doesn't mean that the whole `webpack` is used there. Just one of its built-in plugins works thanks for the changes in this PR.

**Comment by obennett-m** [comment]
> If you look under the hood of [moment-locales-webpack-plugin](https://github.com/iamakulov/moment-locales-webpack-plugin/blob/master/index.js#L3) it uses `webpack.ContextReplacementPlugin`. it doesn't mean that the whole `webpack` is used there. Just one of its built-in plugins works thanks for the changes in [this PR](https://github.com/web-infra-dev/rspack/pull/6420).

I _did_ look under the hood when I didn't get this working with only `@rspack/core` installed. This is how I know webpack needs to still be installed in order for this to work. rspack isn't providing `ContextReplacementPlugin`, so what is documented at https://www.rspack.dev/plugins/webpack/index is still correct.

If you were to completely uninstall webpack from your project you would see the same issues I do.
`TypeError: rspack.ContextReplacementPlugin is not a constructor` means it is not implemented in `@rspack/core`.
