### ISSUE TITLE
[Bug]: [fullhash] not works in production mode

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#6407]
### System Info

rspack 0.6.3

### Details

Filename "[fullhash]" does not work in production mode, the output filename hash is different from the compilation hash.

However, when I set `optimization.realContentHash` is false, it works. Seems we should not add `contentHash` if  this chunk is a `fullHashModule` when `createHash`.

![20240429-200000](https://github.com/web-infra-dev/rspack/assets/22373761/b1e02d09-96cf-44b0-8191-0f5c5c2e84a0)

Reference webpack:

https://github.com/webpack/webpack/blob/7b4775cebe372f9396d8f3b61ef1347cb633956e/lib/Compilation.js#L4334-L4337

https://github.com/webpack/webpack/blob/ab47c696a403862dbd996f8c2f1ef3770f24ee09/lib/optimize/RealContentHashPlugin.js#L173-L192

### Reproduce Steps

Apply the following configuration in `rspack.config.js`: 
```
	output: {
		filename: `[name].[fullhash].js`
	},
	optimization: {
		realContentHash: true // or false
	},
	stats: {
		hash: true
	},
```

**Comment by LingyuCoder** [comment]
need to align fullhashModules and dependentHashModules on chunk graph and hot module replacment
