### ISSUE TITLE
[Bug]: webpack-workbox-plugin not working with rspack

### ISSUE THREAD

**Issue by saifislamrepos** [web-infra-dev/rspack#6437]
### System Info

node 20
react 18
"workbox-webpack-plugin": "^7.1.0"

### Details

webpack-workbox plugin is giving error on rspack build
ERROR in × TypeError: Cannot read properties of undefined (reading 'source')
  │     at InjectManifest.addAssets   node_modules/workbox-webpack-plugin/build/inject-manifest.js:223:39
  
  ERROR in × Error:   × TypeError: Cannot read properties of undefined (reading 'set')
  │   │     at Object.fn ** /node_modules/webpack/lib/EntryPlugin.js:37:37

### Reproduce Steps

add const { InjectManifest } = require('workbox-webpack-plugin'); in your build config will give trigger above error in build process

**Comment by LingyuCoder** [comment]
Please try to use [inject-manifest-plugin](https://www.npmjs.com/package/inject-manifest-plugin) instead

**Comment by nguyenbatranvan** [comment]
> Please try to use [inject-manifest-plugin](https://www.npmjs.com/package/inject-manifest-plugin) instead

 I'm not sure but the library you introduced really has too few uses. I'm more familiar with using `workbox-webpack-plugin `and its strong community!!! Will you support integrating this plugin into rspack?

**Comment by LingyuCoder** [comment]
> > Please try to use [inject-manifest-plugin](https://www.npmjs.com/package/inject-manifest-plugin) instead
> 
> I'm not sure but the library you introduced really has too few uses. I'm more familiar with using `workbox-webpack-plugin `and its strong community!!! Will you support integrating this plugin into rspack?

This is an InjectManifest implementation compatible with Rspack. It is based on the original plugin and is compatible with the Rspack API. This plugin is currently contributed by the community and will not be integrated into rspack internally. If you encounter any issues, you can directly submit an issue or pull request to it.

**Comment by nguyenbatranvan** [comment]
> > > Please try to use [inject-manifest-plugin](https://www.npmjs.com/package/inject-manifest-plugin) instead
> > 
> > 
> > I'm not sure but the library you introduced really has too few uses. I'm more familiar with using `workbox-webpack-plugin `and its strong community!!! Will you support integrating this plugin into rspack?
> 
> This is an InjectManifest implementation compatible with Rspack. It is based on the original plugin and is compatible with the Rspack API. This plugin is currently contributed by the community and will not be integrated into rspack internally. If you encounter any issues, you can directly submit an issue or pull request to it.

yess!! have some issue with plugin!! i suggest use [workbox-rspack-plugin](https://github.com/Clarkkkk/workbox-rspack-plugin)!! This plugin work well
