### ISSUE TITLE
[Bug]: Unable to recognize the less variable in the third-party library (like component library)

### ISSUE THREAD

**Issue by Sunny-117** [web-infra-dev/rspack#6439]
### System Info

macOS
node:v16.14.2
pnpm: 6.32.3

### Details

webpack can operate normally： 
![img_v3_02ai_1fb756d7-f27c-428b-815d-20f2be8317bg](https://github.com/web-infra-dev/rspack/assets/73089592/82918f9f-5ba1-4593-8826-f77ff0d7bc63)

rspack：
![img_v3_02ai_2b5bd3bd-0514-449e-af5f-9a80824b502g](https://github.com/web-infra-dev/rspack/assets/73089592/bee74d9d-461f-4682-baf9-aee7e7a5ed5e)
![img_v3_02ai_a865a334-6836-4584-acdd-41b9ba692eag](https://github.com/web-infra-dev/rspack/assets/73089592/0b66c751-1a56-4d5e-bd43-48783eaebf2d)

I can directly use the less variable in the project. The less variable used inside the third-party component library will report an error.

### Reproduce link

https://github.com/op-sources/rspack-bug-playground

### Reproduce Steps

There is no need to install node_modules, because the reproduce link is already included.

Run project: 
start webpack server: cd packages/active: pnpm dev
start rspack server: cd packages/home: pnpm dev

**Comment by LingyuCoder** [comment]
Fail to build because node_modules of packages/* are lost.

**Comment by Sunny-117** [comment]
> Fail to build because node_modules of packages/* are lost.

It has been updated. Please take a look

node_modules download address and project start method: https://jzq422bol5.feishu.cn/wiki/Pe7pwcmdaitTBNk18vKcXuQjnth?from=from_copylink

**Comment by xc2** [comment]
this file is a css file other than a less file and the highlighted variable is a css variable as well.

`min(1 * var(--dls-transition-from-y, 0), 0)` is not valid in less by default.

please separate rules for less and css. e.g.,

```js
[
    {
        test: /\.css$/,
        use: [
            {
              loader: 'style-resources-loader',
              options: {
                 // ...
              }
          }
        ],
        type: 'css'
    },
    {
        test: /\.less$/,
        use: [
            'less-loader',
            {
              loader: 'style-resources-loader',
              options: {
                 // ...
              }
          }
        ],
        type: 'css'
    },
]
```

or setting the `math` option of less.js to `parens`

```js
    {
        test: lessRule,
        use: [
            {
                loader: 'less-loader',options: {lessOptions: {math: 'parens'}}
            },
            {
              loader: 'style-resources-loader',
              options: {
                 // ...
              }
          }
        ],
        type: 'css'
    },
```

**Comment by Sunny-117** [comment]
> this file is a css file other than a less file and the highlighted variable is a css variable as well.
> 
> `min(1 * var(--dls-transition-from-y, 0), 0)` is not valid in less by default.
> 
> please separate rules for less and css. e.g.,
> 
> ```js
> [
>     {
>         test: /\.css$/,
>         use: [
>             {
>               loader: 'style-resources-loader',
>               options: {
>                  // ...
>               }
>           }
>         ],
>         type: 'css'
>     },
>     {
>         test: /\.less$/,
>         use: [
>             'less-loader',
>             {
>               loader: 'style-resources-loader',
>               options: {
>                  // ...
>               }
>           }
>         ],
>         type: 'css'
>     },
> ]
> ```
> 
> or setting the `math` option of less.js to `parens`
> 
> ```js
>     {
>         test: lessRule,
>         use: [
>             {
>                 loader: 'less-loader',options: {lessOptions: {math: 'parens'}}
>             },
>             {
>               loader: 'style-resources-loader',
>               options: {
>                  // ...
>               }
>           }
>         ],
>         type: 'css'
>     },
> ```

Thanks a lot
