### ISSUE TITLE
[Bug]: Panic occurred at runtime.

### ISSUE THREAD

**Issue by vijaybritto** [web-infra-dev/rspack#6474]
### System Info

  System:

    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)

    CPU: (2) x64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz

    Memory: 6.91 GB / 7.77 GB

    Container: Yes

    Shell: 5.1.4 - /bin/bash

  Binaries:

    Node: 22.1.0 - /usr/local/bin/node

    Yarn: 1.22.19 - /usr/local/bin/yarn

    npm: 10.7.0 - /usr/local/bin/npm

    bun: 1.1.7 - ~/.bun/bin/bun

### Details

Running `rsbuild build` in Docker on Jenkins causes this panic. However it builds successfully in my M1 Mac.
In Jenkins:
<img width="979" alt="image" src="https://github.com/web-infra-dev/rspack/assets/3725668/c69efb87-f895-4bfe-a3ab-b7ecd5fecef4">
```sh
$ rsbuild build



  Rsbuild v0.6.8



Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues

Message:  should have dependency id

Location: crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs:92



Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

Run with RUST_BACKTRACE=full to include source snippets.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 1: start_thread

    at <unknown source file>

 2: clone

    at <unknown source file>

error: script "build" was terminated by signal SIGABRT (Abort)

Aborted (core dumped)

The command '/bin/sh -c bun run build' returned a non-zero code: 134
```
In Mac:
![image](https://github.com/web-infra-dev/rspack/assets/3725668/ed3a87dd-45bb-4509-8bae-b08aecfe9e38)

### Reproduce Steps

will update this

**Comment by xc2** [comment]
This panic may happen when the code includes `require.context("./foo")` and `"./foo"` can not be resolved.

When it is reproducsible on linux only, your code or deps might include `require.context("./foo")` and there is a directory named `foo` with different case like `Foo`.

**Comment by xc2** [comment]
Rspack should give a good error/warn message instead of panic.

**Comment by vijaybritto** [comment]
That's good to know. I will check if the third party code has infact incorrect path. But I think it would be great to have this as a compilation error rather than a panic. Let me know if I should close this?

**Comment by xc2** [comment]
> That's good to know. I will check if the third party code has infact incorrect path. But I think it would be great to have this as a compilation error rather than a panic. Let me know if I should close this?

Please just keep it open.

**Comment by chenjiahan** [comment]
I have created a reproduction and a bug report issue for it, see: https://github.com/web-infra-dev/rspack/issues/6735

I will close this issue to avoid duplication
