### ISSUE TITLE
[Bug]: Panic occured with rspack v0.6.4

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6482]
### System Info

N/A

### Details

Ran into the below panic when trying the latest 0.6.4 to start the application. Was previously on 0.6.2, which works fine.  

●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (60%) building /workspaces/teams-modular-packages/node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js                                                                                                        Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  index out of bounds: the len is 2 but the index is 2
Location: crates/rspack_plugin_javascript/src/utils/eval/eval_tpl_expr.rs:44

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (42%) building builtin:swc-loader??ruleSet[1].rules[14].use[0]!/workspaces/packages/core/services/something/src/something.ts                                            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                               ⋮ 1 frame hidden ⋮                               
 2: clone
    at /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Done in 13.19s. Peak memory usage 30.66MB.

### Reproduce Steps

please refer to details section

**Comment by xc2** [comment]
Has been fixed in https://github.com/web-infra-dev/rspack/pull/6473. Please try out rspack 0.6.5
