### ISSUE TITLE
[Bug]: after some build watches, memory crashes, as something leaks and grows in ram

### ISSUE THREAD

**Issue by VanderSP** [web-infra-dev/rspack#6487]
### System Info

windows 11, powershell

### Details

if i remember it started to happens after 0.6.4 ~

### Reproduce Steps

Just work for example 1 hour at medium/high saving frequency... build watch mode...
at some point you will hit

start   Compiling...
● Client ━━━━━━━━━━━━━━━━━━━━━━━━━ (1%) make         
memory allocation of 150994944 bytes failed

**Comment by h-a-n-a** [comment]
Would you please create a minimal reproduction?

**Comment by VanderSP** [comment]
It´s a nice idea, anytime i will try to make some project and trigger a lot of build watches

**Comment by VanderSP** [comment]
Sorry not managed yet a repro, but maybe its not ram... but disk... when i break the build watch process after a while, i reclaim 6gb of space, maybe hitting low disk, because i always run low on disk, round ~6 ~8gb free... but why it´s accumulating?

**Comment by LingyuCoder** [comment]
not sure why this happens, perhaps you can try to disable the virtual memory setting of windows 11

**Comment by VanderSP** [comment]
I just would like to add that, i have been running alternative build script (because i needed minifying shaders), so now i back to npm run bulid as usual (rspack build --watch), and i can say that it still leaking ram, leading to eventual crash of cli (when ram got full)
While i apologize not being able to really isolate a reproduction case.... i can say that´s a js project that uses threejs/t3d.js and some other few dependencies.... and after hmm idk 30/40/50??? build watches.... the full ram leak hits and exits

**Comment by VanderSP** [comment]
just found that my rsbuild was not updating to latest versions
i will test with newer ones!
