### ISSUE TITLE
[Feature]: FormatJs plugin

### ISSUE THREAD

**Issue by huanghlun** [web-infra-dev/rspack#6496]
### What problem does this feature solve?

I used to use  `babel-loader` and `babel-plugin-formatjs` to automatically inject formatted message ID. But when I use `builtin:swc-loader`, I don't know how to use this plugin.

The message ID is neccessary in `react-intl`.
![intl-bug](https://github.com/web-infra-dev/rspack/assets/28281750/d1336df8-2a0c-413d-9136-6739315c3355)

### What does the proposed API of configuration look like?

Is it possible for `builtin:swc-loader` to support `plugins`

**Comment by hardfist** [comment]
it already did https://www.rspack.dev/zh/guide/features/builtin-swc-loader#jscexperimentalplugins
