### ISSUE TITLE
[Feature]: 同步webpack.ProgressPlugin能力

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#6501]
### What problem does this feature solve?

提供自定义进度显示

### What does the proposed API of configuration look like?

和webpack.ProgressPlugin参数一致即可

**Comment by chenjiahan** [comment]
See:

- https://github.com/web-infra-dev/rspack/discussions/4202
- https://github.com/web-infra-dev/rspack/pull/4522
