### ISSUE TITLE
[docs] test guide 

### ISSUE THREAD

**Issue by darksouls3quin** [web-infra-dev/rspack#6504]
Update test guide documentations

**Comment by xc2** [comment]
DARKSWORD +21

**Comment by chenjiahan** [comment]
The testing guide has been updated in https://github.com/web-infra-dev/rspack/pull/6519.

You can refer to https://www.rspack.dev/contribute/development/testing for details.

Please note that we are still improving the testing process and the content in the document will be continuously updated.
