### ISSUE TITLE
[Bug]: Error: Resolve error: Can't resolve './locale' , but it is a warning in webpack.

### ISSUE THREAD

**Issue by huhuaaa** [web-infra-dev/rspack#6523]
### System Info

![image](https://github.com/web-infra-dev/rspack/assets/10042927/ece8bedf-805a-471d-87c8-31ab8d715762)

### Details

![image](https://github.com/web-infra-dev/rspack/assets/10042927/90e20ce8-82e5-4a8b-bbde-3b7f8e22bb3d)
![image](https://github.com/web-infra-dev/rspack/assets/10042927/8c253f54-87bb-4013-9713-97a8825e94bf)

### Reproduce link

https://github.com/huhuaaa/rspack-demo.git

### Reproduce Steps

1. cd ./projects/import-bug
2. pnpm install
3. pnpm run rspack  /  pnpm run webpack

**Comment by LingyuCoder** [comment]
this is a bug, rspack does not handle optional context dependency in try-catch correctly

**Comment by LingyuCoder** [comment]
> This problem has bobbed up again.

Can you provide a repro?

**Comment by Chang1ng** [comment]
> > This problem has bobbed up again.
> 
> Can you provide a repro?

Unfortunately, this is an internal npm source. Trying to solve it.
