### ISSUE TITLE
[Bug]: Error when adding new imports from third-party packages in dev mode

### ISSUE THREAD

**Issue by Moudicat** [web-infra-dev/rspack#6532]
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 394.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.202
    Chrome Canary: 126.0.6477.3
    Safari: 16.3
  npmPackages:
    @rspack/cli: 0.6.5 => 0.6.5 
    @rspack/core: 0.6.5 => 0.6.5

## Description

I'm encountering an issue when using rspack in development mode with third-party packages. Initially, importing a single component from a package works fine. For example:

```javascript
import { Button } from 'vant';
```

However, when I modify the import statement to add new components from the same package:

```javascript
import { Button, Calendar } from 'vant';
```

the application throws an error:

```
Uncaught Error: Cannot find module 'vant'
```

This issue is not limited to 'vant' but occurs with other third-party packages as well whenever a new import is added.

### Reproduce link

https://github.com/Moudicat/rspack-repo-dev-mode-error-importing

### Reproduce Steps

1. pnpm i
2. pnpm run dev:rspack
3. open http://localhost:8080/
4. go to src/main.js
5. try add new components from vant

**Comment by JSerFeng** [comment]
I'm working on it, during this time you can set cache to false to avoid this issue
