### ISSUE TITLE
[Bug]: Pseudoclass ":global" not affect in classes inner ":not()" pseudoclass

### ISSUE THREAD

**Issue by mrakobes27** [web-infra-dev/rspack#6550]
### System Info

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 6.81 GB / 19.52 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: 0.6.3 => 0.6.3
    @rspack/core: 0.5.6 => 0.5.6
    @rspack/plugin-minify: 0.6.3 => 0.6.3
    @rspack/plugin-react-refresh: 0.6.3 => 0.6.3

### Details

The built-in CSS/module loader does not handle the ":global" pseudo-selector correctly - its context stops working inside the ":not()".

Example (my.module.css):
`.select :global .ant-select:not(.ant-select-customize) .ant-select-selector {
  padding-right: 28px;
}`

Result:
`.module_select_hash .ant-select:not(.module_ant-select-customize_hash) .ant-select-selector {
  padding-right: 28px;
}`

With original "css-loader":
`.module_select_hash .ant-select:not(.ant-select-customize) .ant-select-selector {
  padding-right: 28px;
}`

### Reproduce Steps

Set the style of any modular component (css-in-module) using the pseudo-classes ":global" and ":not" as in the example.

**Comment by LingyuCoder** [comment]
seems to be a bug of swc cc @JSerFeng @SyMind

**Comment by JSerFeng** [comment]
can you try latest nightly version of @rspack/core

**Comment by mrakobes27** [comment]
> can you try latest nightly version of @rspack/core

Updated to version v0.7.0-beta.0, the problem persisted

**Comment by chenjiahan** [comment]
@mrakobes27 Can you try Rspack v0.7.0?

**Comment by chenjiahan** [comment]
This should have been fixed.
