### ISSUE TITLE
[Bug]: ModuleFederationPlugin remote not support IE11

### ISSUE THREAD

**Issue by wzc321** [web-infra-dev/rspack#6556]
### System Info

  System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 2.84 GB / 15.73 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.3 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22000.120

### Details

set browserslist:
"browserslist": [
    "> 0.5%",
    "not dead",
    "IE 11"
  ]

and run `npm run  build`  the remoteEntry.js are many `let` and  `=>` but IE 11 not support

![1715779847671](https://github.com/web-infra-dev/rspack/assets/11954894/3ed6ff68-6050-41ac-a734-366fb85d84db)

### Reproduce link

https://github.com/rspack-contrib/rspack-examples/tree/main/rsbuild/module-federation

### Reproduce Steps

1. Run `npm install`
2. Set package.json `"browserslist": [
    "> 0.5%",
    "not dead",
    "IE 11"
  ]`
3. Run `npm run build`

**Comment by LingyuCoder** [comment]
this comes from @module-federation/runtime and the es6+ code does not been converted by loader because node_modules is exclude by default

**Comment by ahabhgk** [comment]
This is same behavior with https://github.com/module-federation/core/tree/main/packages/enhanced, user should add it to `builtin:swc-loader`/`babel-loader` by themselves

**Comment by wzc321** [comment]
When I set source.include node_modules/@module-federation, no use

**Comment by chenjiahan** [comment]
@wzc321 Hi, you can try Rsbuild >= 1.0.0-aplha.7，now Rsbuild will transform Module Federation runtime by default.

See: https://github.com/web-infra-dev/rsbuild/pull/2850
