### ISSUE TITLE
[Bug]: dev模式下，使用css-loader之后，若在样式中写了一个错误，再修改正确也一直报错

### ISSUE THREAD

**Issue by huhuaaa** [web-infra-dev/rspack#6560]
### System Info

System:
    OS: macOS 14.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 310.04 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 7.33.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.203
    Safari: 17.2.1
  npmPackages:
    @rspack/cli: ^0.6.5 => 0.6.5 
    @rspack/core: ^0.6.5 => 0.6.5 

### Details

当在样式代码写入一段错误代码之后，再修改正确；构建过程始终在报之前的错误，没能按预期的识别到代码已经修改正确。
![image](https://github.com/web-infra-dev/rspack/assets/10042927/e5cd5d42-02cf-4454-9c7c-a798fe129d61)

### Reproduce link

https://github.com/huhuaaa/rspack-demo.git

### Reproduce Steps

1. cd projects/css-bug
2. pnpm install
3. pnpm run rspack
4. 打开 src/index.module.less，然后随便写一个错误进去，比如直接写{}触发报错
5. 再删掉{}让代码变正确

**Comment by 9aoy** [comment]
除了控制台输出错误外，实际样式有更新么？如果只是控制台输出的话，可能和这个问题有关： https://github.com/web-infra-dev/rspack/issues/5961

**Comment by huhuaaa** [comment]
错误的样式引起页面白屏之后，修改正确也还是白屏并在终端和控制台中都有错误显示
