### ISSUE TITLE
[Bug]: CopyRspackPlugin is not wokring

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#6574]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 17.48 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.60
  npmPackages:
    @rspack/cli: ^0.6.5 => 0.6.5 

### Details

Trying to copy files by CopyRspackPlugin does not have effect - there is no copied files in dist folder

### Reproduce link

https://github.com/krutoo/try-copy-rspack-plugin

### Reproduce Steps

1. clone repo
2. `npm i`
3. `npx rspack`
4. see no copied files in dist folder

**Comment by LingyuCoder** [comment]
Please wrap `from` inside `patterns`. This aligns with copy-webpack-plugin

```diff
new CopyWebpackPlugin({
+  patterns: [{
    from: "src/static/favicon/**/*",
+  }]
})
```
