### ISSUE TITLE
[Bug]: v0.7.0-beta.1 dynamic import error.

### ISSUE THREAD

**Issue by 1yasa** [web-infra-dev/rspack#6590]
### System Info

  System:
    OS: macOS 14.4
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900KF
    Memory: 10.78 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.0.4 - /usr/local/bin/pnpm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman

### Details

<img width="2673" alt="截屏2024-05-21 16 00 55" src="https://github.com/web-infra-dev/rspack/assets/127166080/5f7859f2-4728-4a36-9eb4-926a1c62ef23">

v0.6.5 => v0.7.0-beta.1 ,disable `lazyCompilation`, dynamic import show above error.

### Reproduce Steps

above.

**Comment by ahabhgk** [comment]
Could you provide a reproduce? I tried to reproduce with the image you provided but didn't see the error

**Comment by 1yasa** [comment]
> Could you provide a reproduce? I tried to reproduce with the image you provided but didn't see the error

I guess this bug is cause by path(`@/locales/dayjs/${lang}` => './en'), I will submit repro later.

**Comment by ahabhgk** [comment]
Thanks for reporting, the fix will release in v0.7.0
