### ISSUE TITLE
[Feature]: Use exclusively the asset content hash for assets filenames

### ISSUE THREAD

**Issue by jchavarri** [web-infra-dev/rspack#6606]
### What problem does this feature solve?

It is sometimes useful to be able to generate paths to assets from external tools (not Rspack or Webpack). In our case, we use OCaml to generate paths to assets referred from code.

In Rspack case, it's currently impossible to replicate the way hashes are created, because the asset filenames use hashes produced with a lot of additional information like chunk graph:

https://github.com/web-infra-dev/rspack/blob/a19d601eb37b504a5e25b5133c0dee344b68141b/crates/rspack_plugin_asset/src/lib.rs#L392-L397

### What does the proposed API of configuration look like?

Similarly to Webpack (see [lib/asset/AssetGenerator.js](https://github.com/webpack/webpack/blob/4baf1c075d59babd028f8201526cb8c4acfd24a0/lib/asset/AssetGenerator.js#L299)), Rspack could just take the contents of a given file and use that as filename (combined with whatever is defined as template).

Upsides:

- Files with the same content across the project would only be produced once
- External tools that need to interact with Rspack (like described above in "Problem" section) can also produce filenames from content 
- Behavior closer to Webpack

For example, for a file `foo.txt` with the following contents:
```
String: hello\n
Decimal values: 104 101 108 108 111 10
Hexadecimal values: 68 65 6c 6c 6f 0a
```
When using `xxhash64`, it should produce hash `2a46a2ab9a81fc99` and filename `2a46a2ab9a81fc99.txt` (it currently produces `f08eb0ee2582d45c.txt`).

(Note the current functions used (`xxhash64` or `md4`) wouldn't need to change. Just making sure the filename is produced from a hash of the file content would be enough).

Thank you!

**Comment by jchavarri** [comment]
I guess what I want is [realContentHash](https://www.rspack.dev/config/optimization#optimizationrealcontenthash), but from what i've tested, enabling or disabling this config doesn't seem to have any effect at the moment (the hash never gets the real content value).

**Comment by LingyuCoder** [comment]
Rspack calculate the hash with the content and its length by default with Rust hash trait. But webpack calculate the hash with adding the content only. This make the hashes different. It is a bug of realContentHash and we will try to fix it
