### ISSUE TITLE
[Bug]: incorrect file matching with `**.js` glob pattern in sideEffects

### ISSUE THREAD

**Issue by SyMind** [web-infra-dev/rspack#6613]
### System Info

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.41 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.14.3 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.76
    Safari: 17.0
  npmPackages:
    @rspack/cli: workspace:* => 0.7.0-beta.0 

### Details

Bug in https://github.com/devongovett/glob-match
Fix: https://github.com/devongovett/glob-match/pull/12

### Reproduce Steps

package.json like:

```json
{
    "sideEffects": ["**.js"]
}
```

`dir/a.js` can not hit.

**Comment by LingyuCoder** [comment]
Fixed by https://github.com/web-infra-dev/rspack/pull/6668
