### ISSUE TITLE
[Bug]: There appears to be an extra space after buildIcon in rspack.ProgressPlugin if the `prefix` option not provided

### ISSUE THREAD

**Issue by dingff** [web-infra-dev/rspack#6632]
### System Info

System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.35 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    pnpm: 8.15.7 - ~/.nvm/versions/node/v16.15.0/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.112
    Safari: 17.4.1

### Details

![image](https://github.com/web-infra-dev/rspack/assets/69964024/7eb18ac0-04ca-4f41-a804-6b0324a3da16)

### Reproduce Steps

pnpm build

**Comment by LingyuCoder** [comment]
Rspack uses `indicatif::ProgressBar` to draw the progress bar with template `"● {prefix:.bold} {bar:25.green/white.dim} ({percent}%) {wide_msg:.dim}"` ([code](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_progress/src/lib.rs#L57)), with has spaces around the prefix. So there are two spaces between the dot and the bar by default.

Perhaps ProgressPlugin can provide configuration to customize the template. And also PR is welcome.

**Comment by LingyuCoder** [comment]
has been implemented by #6722
