### ISSUE TITLE
[Bug]: hmr failed when adding or modifying new initial chunk

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspack#6633]
### System Info

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 296.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/Library/Caches/fnm_multishells/996_1716862511218/bin/node
    npm: 10.5.2 - ~/Library/Caches/fnm_multishells/996_1716862511218/bin/npm
    pnpm: 8.15.4 - ~/Library/Caches/fnm_multishells/996_1716862511218/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.112
    Chrome Canary: 127.0.6504.0
    Safari: 17.5

### Details

Cannot find module '@icon-park/react'

It seems to be an issue of esm hmr.

Add the import in the devlopment environment, only updated `index.js`, but not updated `vendors-node_modules_pnpm_icon-park_react_1_4_2_react-dom_18_3_1_react_18_3_1_nod E_modules.js` (the bundle of the iconPark package)

![faKUSl028L](https://github.com/web-infra-dev/rspack/assets/79413249/c3f12323-8305-4813-92f2-b7bb988b8c2f)

### Reproduce link

https://github.com/SoonIter/rsbuild-provided-exports-issue

### Reproduce Steps

1. pnpm install
2. npm run dev
3. modify index.js, and add import from iconPark
```
import {
  SunOne,
  // ACane,      <--- add import
} from '@icon-park/react';
```

**Comment by SoonIter** [comment]
There is still a problem with this place in 0.7.0
<img width="400" alt="image" src="https://github.com/web-infra-dev/rspack/assets/79413249/4b03a5ad-c58f-4a0e-8aeb-0a7d01009ebc">

@JSerFeng said he might take a look at this issue

**Comment by SoonIter** [comment]
related to https://github.com/web-infra-dev/rspack/issues/6612

**Comment by JSerFeng** [comment]
FYI: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/847

**Comment by SoonIter** [comment]
related to
https://github.com/webpack/webpack/issues/18548
https://github.com/JSerFeng/webpack-lazy-compilation-issue/tree/hmr

**Comment by SoonIter** [comment]
webpack devServer should watch the index.html and initial chunk changes and trigger the page reload. 
Align with webpack, but it can be better.
