### ISSUE TITLE
[Bug]: LazyCompilationBackend header overflow

### ISSUE THREAD

**Issue by ckken** [web-infra-dev/rspack#6636]
### System Info

  System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 500.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 125.0.6422.78
    Safari: 17.4.1
  npmPackages:
    @rspack/core: 0.7.0 => 0.7.0 
    @rspack/dev-server: 0.7.0 => 0.7.0 

### Details

<w> [LazyCompilationBackend] [Error: Parse Error: Header overflow] {
<w>   bytesParsed: 16539,
<w>   code: 'HPE_HEADER_OVERFLOW',
<w>   reason: 'Header overflow',
<w>   rawPacket: <Buffer 47 45 54 20 2f 6c 61 7a 79 2d 63 6f 6d 70 69 6c 61 74 69 6f 6e 2d 75 73 69 6e 67 2d 62 75 69 6c 74 69 6e 3a 73 77 63 2d 6c 6f 61 64 65 72 25 33 46 25 ... 16773 more bytes>
<w> }
<w> [LazyCompilationBackend] Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
<w>     at onRequestTimeout (node:_http_server:830:30)
<w>     at Server.checkConnections (node:_http_server:643:7)
<w>     at listOnTimeout (node:internal/timers:573:17)
<w>     at process.processTimers (node:internal/timers:514:7) {
<w>   code: 'ERR_HTTP_REQUEST_TIMEOUT'
<w> }

### Reproduce Steps

npm run dev 
```shell
<w> [LazyCompilationBackend] [Error: Parse Error: Header overflow] {
<w>   bytesParsed: 16539,
<w>   code: 'HPE_HEADER_OVERFLOW',
<w>   reason: 'Header overflow',
<w>   rawPacket: <Buffer 47 45 54 20 2f 6c 61 7a 79 2d 63 6f 6d 70 69 6c 61 74 69 6f 6e 2d 75 73 69 6e 67 2d 62 75 69 6c 74 69 6e 3a 73 77 63 2d 6c 6f 61 64 65 72 25 33 46 25 ... 16773 more bytes>
<w> }
<w> [LazyCompilationBackend] Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
<w>     at onRequestTimeout (node:_http_server:830:30)
<w>     at Server.checkConnections (node:_http_server:643:7)
<w>     at listOnTimeout (node:internal/timers:573:17)
<w>     at process.processTimers (node:internal/timers:514:7) {
<w>   code: 'ERR_HTTP_REQUEST_TIMEOUT'
<w> }
```

**Comment by 1yasa** [comment]
+1 

same error:
<img width="1301" alt="截屏2024-05-28 18 21 52" src="https://github.com/web-infra-dev/rspack/assets/127166080/48d0ee4a-e02a-4560-94be-32e0e45f1e8f">
