### ISSUE TITLE
[Bug]:  Bug with fonts during local development

### ISSUE THREAD

**Issue by exocornet** [web-infra-dev/rspack#6644]
### System Info

fonts disappear

### Details

If the font is connected via scss (css) and caching is enabled, when you change the scss or ts files where scss (css) is not connected, the fonts are deleted, which makes development difficult.

### Reproduce Steps

![image](https://github.com/web-infra-dev/rspack/assets/57918887/f101beb8-b961-4502-a3c2-b6b49c4b9527)
![image](https://github.com/web-infra-dev/rspack/assets/57918887/7f1aa2d2-aae3-400f-bc30-01676a9c266c)
![image](https://github.com/web-infra-dev/rspack/assets/57918887/b699d9a7-8095-4173-89d9-2f99c4b1b459)

**Comment by exocornet** [comment]
Hello, I provide a repository
https://github.com/exocornet/express-template/tree/rspack

File rspack.config.js 139 line. I had to disable caching to work correctly locally, but the collector began to work slower.
https://github.com/exocornet/express-template/blob/rspack/rspack.config.js


I connect the fonts in fonts.scss
https://github.com/exocornet/express-template/blob/rspack/src/shared/styles/layer-generic/fonts.scss


I also have two more questions:

1. Will there be plugin support webpack-remove-empty-scripts? It doesn't work now, you have to do it with additional code in file server.js 208 - 220 line.
webpack-remove-empty-scripts
https://github.com/exocornet/express-template/blob/rspack/server.js


2. Will there be full support for the plugin in the near future image-minimizer-webpack-plugin? It is sorely missed the way it worked before.


Thanks for the help and quick response.

**Comment by LingyuCoder** [comment]
cc @jerrykingxyz , seems to be a bug incremental build when handling assets, I made a more simple repro [here](https://github.com/LingyuCoder/bundler-playground/tree/main/rspack/incremental-assets), just `rspack serve` and modify the `other.css`

**Comment by exocornet** [comment]
> cc @jerrykingxyz , seems to be a bug of incremental build while handling assets, I made a more simple repro [here](https://github.com/LingyuCoder/bundler-playground/tree/main/rspack/incremental-assets), just `rspack serve` and modify the `other.css`


Hello. Yes, that's right, that's true. But webpack did not have this bug. Can you please tell me how to solve this problem? And also tell me, with the other two questions, are there already answers or solutions?

**Comment by jerrykingxyz** [comment]
@exocornet you can try set [output.clean](https://www.rspack.dev/config/output#outputclean) to false to workaround. The other two questions about plugin compatibility @h-a-n-a cc

**Comment by exocornet** [comment]
> @exocornet you can try set [output.clean](https://www.rspack.dev/config/output#outputclean) to false to workaround. The other two questions about plugin compatibility @h-a-n-a cc

Thank you very much, everything works. But I would like to have support like in webpack. And so I have to set isProd for clean. Although this may be more correct for local assembly, here I rely on your expertise.

@h-a-n-a Hello, I was advised to contact you regarding the two questions above. Can you suggest something?

> I also have two more questions:
> 
> Will there be plugin support webpack-remove-empty-scripts? It doesn't work now, you have to do it with additional code in file server.js 208 - 220 line.
> webpack-remove-empty-scripts
> https://github.com/exocornet/express-template/blob/rspack/server.js
> 
> Will there be full support for the plugin in the near future image-minimizer-webpack-plugin? It is sorely missed the way it worked before.

Thanks for the help and quick response.

**Comment by h-a-n-a** [comment]
> > @exocornet you can try set [output.clean](https://www.rspack.dev/config/output#outputclean) to false to workaround. The other two questions about plugin compatibility @h-a-n-a cc
> 
> Thank you very much, everything works. But I would like to have support like in webpack. And so I have to set isProd for clean. Although this may be more correct for local assembly, here I rely on your expertise.
> 
> @h-a-n-a Hello, I was advised to contact you regarding the two questions above. Can you suggest something?
> 
> > I also have two more questions:
> > Will there be plugin support webpack-remove-empty-scripts? It doesn't work now, you have to do it with additional code in file server.js 208 - 220 line.
> > webpack-remove-empty-scripts
> > https://github.com/exocornet/express-template/blob/rspack/server.js
> > Will there be full support for the plugin in the near future image-minimizer-webpack-plugin? It is sorely missed the way it worked before.
> 
> Thanks for the help and quick response.

The plugin's been relying on a few hooks that does quite expensive jobs on the JS side. We're not likely to support this.

**Comment by h-a-n-a** [comment]
Since the bug has been resolved, I will close this issue.

**Comment by exocornet** [comment]
> Since the bug has been resolved, I will close this issue.


Hello. Yes, the issue was closed. But above I asked 2 more questions that were not answered. Can you give me some advice on them? :)
