### ISSUE TITLE
[Feature]: update swc to 1.5.11

### ISSUE THREAD

**Issue by dribble-njr** [web-infra-dev/rspack#6645]
### What problem does this feature solve?

Since SWC@1.5.8, it [fix(es/minifier): Abort array property inliner if the array is used as a ref](https://github.com/swc-project/swc/pull/8956).

I think this fix the following error.

[You can change the SWC version to 1.5.8 below to see the error.](https://play.swc.rs/?version=1.5.11&code=H4sIAAAAAAAAA0WOMQ7CMAxF95zCW4OEXPaobHCJqkOUmjZSSKrEGQBxd0wRrSV7%2BN%2F%2F2S7FwlA4V8c1E3TQD0ap0bLF%2BLz6QAVvKV%2Bsm7X2TPcDdGd4KZAKxCDKIqENYFZnHW0LU6RsmXb7byDivvhl4FLL%2FDtg1FtaOfksBcKQJr3l%2B9NwhGb0mRyn%2FNjBjUQ%2BfdZqccwAAAA%3D&config=H4sIAAAAAAAAA42VzW7bMAyA732KwOcetsOAYg%2FQ1xAUiXKUyaIg0m6Mou8%2B2k7SZKaNXRybH38k%2FuXz5XBozuSa34dPeZWPYitBvX%2BLhMbM9iKSBlxnydVYuHm90TNNKNhEMIu%2BFtKwrS3wbEW%2FrupNQiS4qV9lXcwxjI8BO5vbBA%2BSyR2WBAOkZ%2BMZ%2FQEoxiVLlG0HtKURdmmpcbAM8otFU4rwpkjJBlvjzx9PGbjnQBQcdqUC0fNlJDV9B5m1QLZW%2FJgA1%2F5RfkRMYPMOMZZMzAwtVM2xw5RsITCDrYqX6aRyF0ItxAR7Bn9Pz4pnHzlilphr6sF649CDgmIFx3EAzUxiiVkmTKDcZ8Yejn3bzv36jzUMNvVSUYVc5pLIaRWvJ4zEJvRZS%2BECN3KwwGtyV%2B0TTAXua17bnTHmjZr8b2dLP21Z73d9zEGmj0eFy6hqt8zQTmMSY1AyO2UGKketmhV872DKrNOOc8Ub6aPowUAI0iuKa%2FqI7E5aUB4LYFCA1NcGrasWYO5TuMGngdjB73JL1hvsqtFZPm1TGrsjpp0AHfAJ%2FY6ClIJxG1fZEpeyzfvsQVoDvKrS0wzWS0AGgNGkee%2BvekPGQzyaNuHxe03cNubL7Tnvzu8%2FhWWtfv0F3%2BR4c6gGAAA%3D)

### What does the proposed API of configuration look like?

none

**Comment by JSerFeng** [comment]
I believe we already updated, try version 0.7.0-canary-4bcc530-20240528063409
