### ISSUE TITLE
[Bug]: Lazy compilation does not recognize require statements with expression

### ISSUE THREAD

**Issue by zackBRAVE** [web-infra-dev/rspack#6652]
### System Info

  System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.0.1/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.77
    Edge: 111.0.1661.44
    Safari: 17.0
  npmPackages:
    @rspack/cli: ^0.7.0 => 0.7.0 
    @rspack/core: ^0.7.0 => 0.7.0 
    @rspack/plugin-react-refresh: ^0.7.0 => 0.7.0 

### Details

When there are variables inside require statements as "img" element's source, rspack would not be able to resolve it correctly as the images shown (src="[object Promise]").

<img width="778" alt="image" src="https://github.com/web-infra-dev/rspack/assets/47842054/ac95700a-b0a0-42b3-88f0-dd2c1c333d63">

<img width="1297" alt="image" src="https://github.com/web-infra-dev/rspack/assets/47842054/110f7ec1-3b4a-45e3-aa41-63bd163a3433">

### Reproduce link

https://github.com/zackBRAVE/rspack-repro-repo

### Reproduce Steps

1. pnpm run dev:rspack
2. there are no errors in the console
<img width="863" alt="image" src="https://github.com/web-infra-dev/rspack/assets/47842054/556fa2d0-ffd6-4227-a9d7-811e0cd03285">

**Comment by zackBRAVE** [comment]
A simpler reproduction code, so this happens whenever there's variable inside require statements.
```javascript
export function render() {
  const el = document.createElement("div");
  el.classList.add("text");
  document.getElementsByTagName("body")[0].appendChild(el);
  el.innerHTML = "hello, world";

  const path = "test.png";
  const imgEl = document.createElement("img");
  imgEl.setAttribute("src", require(`./assets/${path}`));
  document.getElementsByTagName("body")[0].appendChild(imgEl);
}
```
<img width="750" alt="image" src="https://github.com/web-infra-dev/rspack/assets/47842054/e0b35798-5290-48e8-8773-f9bfe7703476">

**Comment by JSerFeng** [comment]
I checked your repro, but didn't find anywhere that you enable lazyCompilation

**Comment by zackBRAVE** [comment]
> I checked your repro, but didn't find anywhere that you enable lazyCompilation

Sorry, forgot to commit the code earlier, just pushed it, now it's valid
<img width="534" alt="image" src="https://github.com/web-infra-dev/rspack/assets/47842054/845e92db-1864-4a9f-887c-3400bd3d7df7">
