### ISSUE TITLE
[Bug]: "??=" operator does not work properly in the mobile application

### ISSUE THREAD

**Issue by KyrieChen** [web-infra-dev/rspack#6666]
### System Info

rspack 0.7.0
device：OPPO Find X
ColorOS：v7.1
Android version：10
Webview: Mozilla/5.0 (Linux; Android 10; PAFM00 Build/QKQ1.191008.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36

### Details

In our project, we found that errors occur in the webview due to the use of the ??= operator without proper compatibility handling. The error is shown in the image below.

![image](https://github.com/web-infra-dev/rspack/assets/13793973/09f63505-88bb-42fd-9370-602d8d859bfa)

During the troubleshooting process, we found that the code is located here.

https://github.com/web-infra-dev/rspack/blob/c2488a66c239b88f68c696933fa7d3109028e371/packages/rspack/src/container/default.runtime.js#L19

This issue only appeared after we upgraded to rspack version v0.7.0.

### Reproduce Steps

The issue can be reproduced immediately using the code from the official website with mf.

**Comment by ckken** [comment]
+1

**Comment by LingyuCoder** [comment]
cc @ahabhgk , this a `.js` script in @rspack/core, should it transform by tsc?

**Comment by ckken** [comment]
Is it possible to provide an implementation option?

**Comment by ahabhgk** [comment]
https://github.com/web-infra-dev/rspack/pull/6672 The fix will be released in v0.7.1, in v0.7.1 if you have swc-loader/babel-loader to transform your js syntax, then the module federation runtime will also be transformed by your swc-loader/babel-loader

**Comment by ahabhgk** [comment]
For example: https://github.com/web-infra-dev/rspack/pull/6672/files#diff-23b4fa030250efc8c22bb3097281f4a66811a42c7d8dc2048a17fb3bbd6480bf
