### ISSUE TITLE
[Bug]: Build is complete without exiting the terminal[exigency!!!]

### ISSUE THREAD

**Issue by zaohuayudie** [web-infra-dev/rspack#6675]
### System Info

System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 398.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 9.0.4 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.4.1

### Details

```
    "@rspack/cli": "^0.7.0",
    "@rspack/core": "^0.7.0",
    "@rspack/plugin-react-refresh": "^0.7.0",
```

<img width="1041" alt="image" src="https://github.com/web-infra-dev/rspack/assets/32356693/678471a9-40c6-4fb6-82f8-4c5ffc53d2a2">

Build is complete without exiting the terminal。

### Reproduce link
https://www.rspack.dev/zh/blog/announcing-0-7
_No response_

### Reproduce Steps

Expectation: Automatically exit terminal after build

**Comment by zaohuayudie** [comment]
It is found that this configuration effect causes the command line to not exit automatically.
Could be a bug

```
{
        test: /\.s[ac]ss$/i,
        use: [
          {
            loader: 'sass-loader',
            options: {
              outputStyle: 'expanded',
              api: 'modern-compiler',
              implementation: require.resolve('sass-embedded'),
            },
          },
        ],
        type: 'css/module',
      },
```

**Comment by LingyuCoder** [comment]
cc @chenjiahan

**Comment by chenjiahan** [comment]
please provide a reproduction

**Comment by chenjiahan** [comment]
It is a bug of `@rspack/cli` and should be fixed in https://github.com/web-infra-dev/rspack/pull/6835.

You can also remove `api: 'modern-compiler'` from sass-loader to fix this before Rspack releasing a new version.
