### ISSUE TITLE
[Bug]: `lazyCompilation` Error: HookWebpackError: Cannot read properties of undefined (reading 'build time')

### ISSUE THREAD

**Issue by Clarkkkk** [web-infra-dev/rspack#6683]
### System Info

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800 8-Core Processor
    Memory: 12.94 GB / 31.87 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97), ChromiumDev (126.0.2592.11)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rspack/cli: ^0.7.0 => 0.7.0
    @rspack/core: ^0.7.0 => 0.7.0

### Details

When turn on `lazyCompilation` in Rsbuild, the error below occurs:
Error: HookWebpackError: Cannot read properties of undefined (reading 'build time')
        │     at tryRunOrWebpackError
         ...

### Reproduce link

https://github.com/Clarkkkk/rspack-sourcemap-issue/tree/lazy-compilation-issue

### Reproduce Steps

```
pnpm i
npm run dev:rsbuild
```

**Comment by JSerFeng** [comment]
![image](https://github.com/web-infra-dev/rspack/assets/57202839/5d5f2f92-c8da-465d-9288-75cc51e51342)
![image](https://github.com/web-infra-dev/rspack/assets/57202839/3b130c31-4de6-4e75-873e-af0dd2e6050e)
Seems okay

**Comment by JSerFeng** [comment]
If you are using css as entry, the error may occur, it will be fixed by #6747

**Comment by Clarkkkk** [comment]
I double check the reproduction with the latest version of Rspack and Rsbuild, and the error remains.

Can you confirm that you are checking the `lazy-compilation-issue` branch? I create different branches for issues in this repo for convenience.

**Comment by JSerFeng** [comment]
It's solved in latest Rspack, however rsbuild is not using the latest version yet (the latest version should be published this week), you can try with pnpm overrides

![image](https://github.com/web-infra-dev/rspack/assets/57202839/288c852f-e3ec-4095-9e5e-57535c417892)
