### ISSUE TITLE
[Bug]: Rspack Dev Tools Slow

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6690]
### What subject does this issue tracking?

# [Subject]

Hi some of my team members have reported the below issue when serving an app and debugging , so wanted to check if others are experiencing the same issue:

1) I noticed that the devtools within Edge's sources tab seem really slow to load with Rspack building. I think it was working fine without rspack, so I think the critical difference is using it.
 It seemed like everything was using these giant relative paths last time I tried to use it, so everything loads in some sources folder in Edge. Initially I thought it might just be me but a few other members of my team also seem to be running into the slowness.
 2) I frequently have my whole tab freeze / crash while I try to do anything (ex: nav through the stack trace) in the sources tab when a breakpoint is hit.
3) my devtool window responses slowly, hitting a break point will just cause the devtool window crashes.
4) Debugging is becoming extremely difficult with rspack. Most of the times, the dev tools just freezes and there is nothing I can do except restarting the browser again. Even after restart, the very next time, it hits a breakpoint and immediately freezes up again.

Any pointers as what might be wrong here?
```

**Comment by SyMind** [comment]
@pushkargupta9807 Can you provide a minimal reproducible example, and also check if the issue exists in Chrome browser?

**Comment by SyMind** [comment]
This issue duplicates https://github.com/web-infra-dev/rspack/issues/6714
