### ISSUE TITLE
[Bug]: Tree shaking not working

### ISSUE THREAD

**Issue by nguyenbatranvan** [web-infra-dev/rspack#6702]
### System Info

MAC OS - M1

### Details

I have files:
``` 
// test1.ts
export const Test1=()=>{
    console.log('sdh')
}

````

```
// test2.ts
import dayjs from "dayjs";

export const Test2=()=>{
    console.log(dayjs())
}

```

```
// index.ts
export {Test1} from "./test1";
export {Test2} from "./test2";
```

In `App.tsx` i used:
```
import {Test1} from "./utils";
import {useEffect} from "react";


const App = () => {
    useEffect(() => {
        Test1();
    }, []);
    return (
        <div className="content">
            <h1>Rsbuild with React</h1>
        </div>
    );
};

export default App;
```
- obviously I'm not using `Test2` with `dayjs`, but when building, it still appears and is not tree-shaking
-  I'm currently using `rsbuild`, but I don't see any documentation about treeshaking. While going through rspack I found [this](https://www.rspack.dev/guide/optimization/tree-shaking), despite following it, it still doesn't work.

In `rsbuild.config.ts`
```
tools: {
                rspack: {
                    module:{
                        rules:[{
                            test: [/\/index.ts/i], // or /index\.ts/ => all not working
                            sideEffects: false
                        }]
                    },
                   ...
            }
```

What configuration am I missing? Thanks for help

### Reproduce Steps

1. No

**Comment by mrakobes27** [comment]
Hi! add the following settings to the config:
`{
  optimization: {
    usedExports: true,
    providedExports: true,
  }
}`
for enable tree-shaking

**Comment by nguyenbatranvan** [comment]
any solutions for this?

**Comment by JSerFeng** [comment]
I suppose the ./utils is your ./index.ts right ?

Here is my demo for you: https://github.com/JSerFeng/rspack-repro-treeshaking

If you have any questions, feel free to ask, it would be better if you can upload your reproduce demo

**Comment by nguyenbatranvan** [comment]
> I suppose the ./utils is your ./index.ts right ?
> 
> Here is my demo for you: https://github.com/JSerFeng/rspack-repro-treeshaking
> 
> If you have any questions, feel free to ask, it would be better if you can upload your reproduce demo

why comment `console.log(dayjs())`, The problem I encountered was running that command line
<img width="262" alt="image" src="https://github.com/web-infra-dev/rspack/assets/19392455/04c59f9d-fa83-46f4-97a5-c2e0711718ec">

**Comment by JSerFeng** [comment]
You can uncomment this, the result is the same

**Comment by ljianc** [comment]
[官方文档](https://www.rspack.dev/zh/guide/optimization/tree-shaking )的例子也不生效！设置成 minimize: true才生效。官网还特意设置成 minimize: false来演示，严重误导啊。更新一下文档吧。

**Comment by JSerFeng** [comment]
> [官方文档](https://www.rspack.dev/zh/guide/optimization/tree-shaking)的例子也不生效！设置成 minimize: true才生效。官网还特意设置成 minimize: false来演示，严重误导啊。应该改成minimize: true也生效吧？方便调试。@JSerFeng

官网例子可能有误导。你说的不生效可能是发现函数仍然存在于产物中，但其实那些未使用函数的引用已经没有了，这是符合预期的，webpack 去除掉的是未使用函数的导出，依赖 minimizer 去掉死代码。

**Comment by ljianc** [comment]
> > [官方文档](https://www.rspack.dev/zh/guide/optimization/tree-shaking)的例子也不生效！设置成 minimize: true才生效。官网还特意设置成 minimize: false来演示，严重误导啊。应该改成minimize: true也生效吧？方便调试。@JSerFeng
> 
> 官网例子可能有误导。你说的不生效可能是发现函数仍然存在于产物中，但其实那些未使用函数的引用已经没有了，这是符合预期的，webpack 去除掉的是未使用函数的导出，依赖 minimizer 去掉死代码。

对，官网确实误导。应该改一下文档，不能特意拿minimize: false来演示
