### ISSUE TITLE
[Bug]: ConcatenateModules optimization affect on sourcemaps

### ISSUE THREAD

**Issue by mrakobes27** [web-infra-dev/rspack#6709]
### System Info

System:                                                       
    OS: Windows 10 10.0.19044                                   
    CPU: (8) x64 AMD Ryzen 7 5700G with Radeon Graphics         
    Memory: 8.30 GB / 19.52 GB                                  
  Binaries:                                                     
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE            
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD              
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD               
  Browsers:                                                     
    Edge: Spartan (44.19041.1266.0), Chromium (123.0.2420.97)   
    Internet Explorer: 11.0.19041.1566                          
  npmPackages:                                                  
    @rspack/cli: 0.6.5 => 0.6.5                                 
    @rspack/core: 0.6.5 => 0.6.5                                
    @rspack/plugin-minify: 0.6.5 => 0.6.5
    @rspack/plugin-react-refresh: 0.6.5 => 0.6.5

### Details

When enabled "concatenateModules" optimization "sourcemaps" are broken
(offsets of original sourcemaps of concatenated js-modules are not recalculated).

When disabling this optimization, the sourcemaps are generated correctly (I checked it through the sourcemaps visualizer - https://sokra.github.io/source-map-visualization/#custom)

### Reproduce Steps

![sourcemapsBug](https://github.com/web-infra-dev/rspack/assets/42668880/5934c98d-43bf-4770-91c7-44e97646fc28)
In the source code where you can check the operation of the "concatenateModules" optimization, try to enable/disable this option, and make sure that in one case the "sourcemaps" are formed correctly, and in the other they are not (including the impossibility of setting a breakpoint)

**Comment by mrakobes27** [comment]
Moreover, even if the "concatenation" is performed on one module (out of many existing ones), the source maps are broken for all subsequent code in the bundle.

**Comment by JSerFeng** [comment]
Can you give me a reproduce repo ? I tried a easy demo seems fine here:
![image](https://github.com/web-infra-dev/rspack/assets/57202839/7fcd339a-2bff-4c6d-9530-1657acaeb3f5)

**Comment by SyMind** [comment]
@mrakobes27 @JSerFeng Maybe fixed in https://github.com/web-infra-dev/rspack/issues/6793
