### ISSUE TITLE
[Bug]: Unable to load styled-components plugin

### ISSUE THREAD

**Issue by brendonco** [web-infra-dev/rspack#6715]
### System Info

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 2.29 GB / 15.73 GB
  Binaries:
    Node: 20.11.0 - ~\SoftwaresInstalled\node-v20.11.0-win-x64\node.EXE
    npm: 10.2.4 - ~\SoftwaresInstalled\node-v20.11.0-win-x64\npm.CMD
    pnpm: 9.0.1 - ~\SoftwaresInstalled\node-v20.11.0-win-x64\pnpm.CMD
  Browsers:
    Chrome: 117.0.5938.132
    Edge: Chromium (122.0.2365.59)
    Internet Explorer: 11.0.19041.3636

### Details

npm start

> cross-env NODE_ENV=development rspack serve

TypeError: plugin.apply is not a function
    at createCompiler (ui-sample\node_modules\@rspack\core\src\rspack.ts:68:12)
    at create (ui-sample\node_modules\@rspack\core\src\rspack.ts:116:20)
    at rspack (ui-sample\node_modules\@rspack\core\src\rspack.ts:140:31)
    at RspackCLI.createCompiler (ui-sample\node_modules\@rspack\cli\dist\rspack-cli.js:67:34)
    at Object.handler (ui-sample\node_modules\@rspack\cli\dist\commands\serve.js:18:30)

rspack.config.js

const { pluginStyledComponents } = require('@rsbuild/plugin-styled-components');
const rspack = require('@rspack/core');
const refreshPlugin = require('@rspack/plugin-react-refresh');

const isDev = process.env.NODE_ENV === 'development';
/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  context: __dirname,
  entry: {
    main: './src/index.ts',
  },
  devServer: {
    historyApiFallback: true,
    port: 8000,
  },
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: ['svg-react-loader'],
        type: 'javascript/auto',
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: {
                  tailwindcss: {},
                  autoprefixer: {},
                },
              },
            },
          },
        ],
        type: 'css',
      },
      {
        test: /\.(jsx?|tsx?)$/,
        use: [
          {
            loader: 'builtin:swc-loader',
            options: {
              sourceMap: true,
              jsc: {
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                },
                transform: {
                  react: {
                    runtime: 'automatic',
                    development: isDev,
                    refresh: isDev,
                  },
                },
              },
              env: {
                targets: [
                  'chrome >= 87',
                  'edge >= 88',
                  'firefox >= 78',
                  'safari >= 14',
                ],
              },
              rspackExperiments: {
                styledComponents: {
                  displayName: true,
                  ssr: true,
                  fileName: true,
                  meaninglessFileNames: ['index', 'styles'],
                  namespace: 'rspack-test',
                  topLevelImportPaths: [
                    '@xstyled/styled-components',
                    '@xstyled/styled-components/*',
                  ],
                  transpileTemplateLiterals: true,
                  minify: true,
                  pure: true,
                  cssProps: true,
                },
              },
            },
          },
        ],
      },
    ],
  },
  plugins: [
    pluginStyledComponents(),
    new rspack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    }),
    new rspack.ProgressPlugin({}),
    new rspack.HtmlRspackPlugin({
      template: './src/index.html',
    }),
    isDev ? new refreshPlugin() : null,
  ].filter(Boolean),
};

### Reproduce Steps

run the app using rspack config defined above.

**Comment by chenjiahan** [comment]
Hi, `@rsbuild/plugin-styled-components` is an Rsbuild plugin, it can not be used in the `rspack.config.js`.

For Rspack projects, you can use the [@swc/plugin-styled-components](https://www.npmjs.com/package/@swc/plugin-styled-components).

- Install:

```bash
npm i @swc/plugin-styled-components -D
```

- Configure in `rspack.config.js`:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.jsx$/,
        loader: "builtin:swc-loader",
        options: {
          jsc: {
            experimental: {
              plugins: [["@swc/plugin-styled-components", {}]],
            },
          },
        },
      },
    ],
  },
};
```

**Comment by brendonco** [comment]
@chenjiahan Thanks for the updates. After I applied the plugins above, I got this errors:

```
WARNING in ./node_modules/@rspack/plugin-react-refresh/client/reactRefreshEntry.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/@rspack/plugin-react-refresh/client/refreshUtils.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/@scb/crs-auth/src/services/auth-services.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/@scb/crs-auth/src/services/authentication.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/@scb/crs-auth/src/services/http-service.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/@scb/crs-auth/src/services/index.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/events/events.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/html-entities/lib/index.js
  ⚠ Experimental plugins are not currently supported.


WARNING in ./node_modules/html-entities/lib/named-references.js
  ⚠ Experimental plugins are not currently supported.
```

**Comment by chenjiahan** [comment]
What's your `@rspack/core` version?

**Comment by brendonco** [comment]
@chenjiahan After upgrade to @rspack/core 0.7.1. I got this error:

```
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing dependencies
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have module graph module
Location: crates\rspack_core\src\module_graph\mod.rs:563

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: napi_register_module_v1
    at <unknown source file>
 6: wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: napi_register_module_v1
    at <unknown source file>
 9: napi_register_module_v1
    at <unknown source file>
10: napi_register_module_v1
    at <unknown source file>
11: napi_register_module_v1
    at <unknown source file>
12: napi_register_module_v1
    at <unknown source file>
13: napi_register_module_v1
    at <unknown source file>
14: napi_register_module_v1
    at <unknown source file>
15: napi_register_module_v1
    at <unknown source file>
16: napi_register_module_v1
    at <unknown source file>
17: napi_register_module_v1
    at <unknown source file>
18: napi_register_module_v1
    at <unknown source file>
19: napi_register_module_v1
    at <unknown source file>
20: napi_register_module_v1
    at <unknown source file>
21: BaseThreadInitThunk
    at <unknown source file>
22: RtlUserThreadStart
    at <unknown source file>
```

If include the plugin will get the above error. removing plugin, build success:

```
                // experimental: {
                //   plugins: [['@swc/plugin-styled-components', {}]],
                // },
```

**Comment by chenjiahan** [comment]
Can you check this part?

https://www.rspack.dev/guide/features/builtin-swc-loader#jscexperimentalplugins

![image](https://github.com/web-infra-dev/rspack/assets/7237365/7165ab7e-d202-4a77-8447-0fbacfc1d68d)

**Comment by brendonco** [comment]
@chenjiahan sorry how do I configured this? how do I make styled-components theme work? I can render styled-components without the plugin. but when I load my UI library from a remote Module Federation (MF), I'm not getting the themes. My themes reside in a remote MF.

**Comment by chenjiahan** [comment]
The styled-components SWC plugin is built for SSR and debugging, maybe it is not the plugin you need.

For this problem, I suggest looking for a solution in the MF or styled-components repo.
