### ISSUE TITLE
[Feature]: support ListenOptions in lazyCompilaton

### ISSUE THREAD

**Issue by tatchi** [web-infra-dev/rspack#6717]
### What problem does this feature solve?

Webpack allows specifying [ListenOptions](https://webpack.js.org/configuration/experiments/#experimentslazycompilation)

```ts
interface ListenOptions extends Abortable {
    port?: number | undefined;
    host?: string | undefined;
    backlog?: number | undefined;
    path?: string | undefined;
    exclusive?: boolean | undefined;
    readableAll?: boolean | undefined;
    writableAll?: boolean | undefined;
    /**
     * @default false
     */
    ipv6Only?: boolean | undefined;
}
```

### What does the proposed API of configuration look like?

Same as webpack

**Comment by LingyuCoder** [comment]
This had been supported, the ListenOptions will be merged when the server starts, just like webpack. https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/builtin-plugin/lazy-compilation/backend.ts#L90

**Comment by tatchi** [comment]
I still think the types need to be updated

https://github.com/web-infra-dev/rspack/blob/a19ca91a4fda7198de826565cc5f900f155d8973/packages/rspack/src/config/zod.ts#L1290-L1297

**Comment by tatchi** [comment]
More precisely, it doesn't support the `backend` property as in webpack: https://webpack.js.org/configuration/experiments/#experimentslazycompilation

For instance, the following doesn't type check:

```js
    experiments: {
      lazyCompilation: { backend: { listen: { port: 7654 } } },
    },
```
