### ISSUE TITLE
[Bug]: failed to receive tsfn value: RecvError

### ISSUE THREAD

**Issue by limbowang** [web-infra-dev/rspack#6720]
### System Info

System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 34.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.15.8 - ~/.nvm/versions/node/v16.20.0/bin/pnpm
  Browsers:
    Safari: 17.0

### Details

Weird issue when using @vanilla-extract/css. 

See reproduce project in  https://codesandbox.io/p/devbox/rsbuild-issue-mz4xzy

rsbuild.config.ts
```
import { defineConfig } from '@rsbuild/core';
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
export default defineConfig({
  source: {
  },
  plugins: [
  ],
  tools: {
    rspack: {
      plugins: [new VanillaExtractPlugin()],
    },
    swc: {},
  },
});

```

### Reproduce link

https://codesandbox.io/p/devbox/rsbuild-issue-mz4xzy

### Reproduce Steps

1. Run 'pnpm run dev'
2. Got error:
```
[Error: nul byte found in provided data at position: 453] {
  code: 'GenericFailure'
}
```

**Comment by h-a-n-a** [comment]
fixed in https://github.com/web-infra-dev/rspack/issues/6643

**Comment by h-a-n-a** [comment]
Can you try `0.7.1-canary-b5b9217-20240603133655`?

**Comment by limbowang** [comment]
works well with canary version. thx~
