### ISSUE TITLE
[Bug]: rspack compiling mdx files

### ISSUE THREAD

**Issue by leimonio** [web-infra-dev/rspack#6725]
### System Info

System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 282.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.2.0 - ~/Library/pnpm/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.114
    Safari: 17.5
  npmPackages:
    @rspack/cli: 0.7.0 => 0.7.0 
    @rspack/core: 0.7.0 => 0.7.0 
    @rspack/plugin-react-refresh: 0.7.0 => 0.7.0 

### Details

When trying to process `.mdx` file by adding a rule, `.mdx` files are not processed.

I'm adding this rule under `module.rules` array:
```
// rspack.config.js
{
  test: /\.mdx$/,
  use: [
    {
      loader: require.resolve('./test-loader.js'),
    }
  ]
}
```

And in the same folder with your `rspack.config.js`, add the file `test-loader.js`.
```
// test-loader.js
module.exports = function(content) {
    console.log("🚀 ~ file: test-loader.js:2 ~ content:", content);
    return content;
}
```

No console log occurs when running `npm run dev`.

### Reproduce Steps

1. Create a new rspack project
2. Apply `.mdx` rule in the rspack configuration (description above)
3. Add `test-loader.js` file (description above)
4. Create a `.mdx` file in the `src/` folder e.g. `documentation.mdx` with some MDX content
4. Run `npm run dev`
5. Observe no console log in the terminal

Let me know if a reproduction is needed.

**Comment by chenjiahan** [comment]
I can not reproduce this issue, can you provide a reproduction?

![image](https://github.com/web-infra-dev/rspack/assets/7237365/c67471d3-9d1a-4632-9db5-80335caba2bc)

**Comment by leimonio** [comment]
After re-creating a rspack repo, the issue went away, I can also see the compilation going through. 
I'm closing the issue now, thank you for having a look either way and being responsive! 🙏
