### ISSUE TITLE
[Feature]: Provide detailed progress information

### ISSUE THREAD

**Issue by robertyclin** [web-infra-dev/rspack#6734]
### What problem does this feature solve?

打包过程的信息能不能打印更加详细的？项目打包过程一直卡在64%，哪怕是用了调试模式也没用，还是看不到任何错误信息，dev.progressBar进度条的右侧building信息又展示不完全。

打包过程一直卡在64%，没有任何错误信息。具体在building那个文件也看不清。

### What does the proposed API look like?

期望能看到错误外的信息，或者能看到当前在building那个文件，或者长时间处于building中报一个错误出来

**Comment by chenjiahan** [comment]
Can you provide a screenshot of your terminal?
