### ISSUE TITLE
[Bug]: Panic occurred if require.context can not resolve the dir

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#6735]
### System Info

  System:
    OS: macOS 13.6.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 386.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 1.22.19 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/yarn
    npm: 10.2.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/npm
    pnpm: 9.1.3 - ~/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/pnpm
    bun: 1.1.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.7.0 => 0.7.1
    @rspack/core: ^0.7.0 => 0.7.1

### Details

Panic occurred if require.context can not resolve the dir, it is expected to throw an resolve error like webpack:

- webpack

<img width="739" alt="Screenshot 2024-06-05 at 19 09 15" src="https://github.com/web-infra-dev/rspack/assets/7237365/c269a449-e31e-433b-9d92-a2f68a180d87">

- Rspack

<img width="737" alt="Screenshot 2024-06-05 at 19 08 52" src="https://github.com/web-infra-dev/rspack/assets/7237365/edf971b9-b733-4091-a6f2-389bbb3a5ea7">

### Reproduce link

https://github.com/chenjiahan/rspack-repro-require-context-panic

### Reproduce Steps

1. pnpm i
2. pnpm dev:rspack

**Comment by LingyuCoder** [comment]
relate to https://github.com/web-infra-dev/rspack/issues/6474

**Comment by chenjiahan** [comment]
Yeah these two issues are the same, maybe we can close one
