### ISSUE TITLE
[Bug]: Panic occurred at recompile in serve and watch mode with rspack 0.7.1

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6742]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (32) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 109.50 GB / 125.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/share/nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.23.19 - /usr/bin/yarn
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.0/bin/npm
    Watchman: 20240317.093234.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 125.0.6422.76

### Details

[Bug]: Panic occurred at recompile in serve and watch mode with rspack 0.7.1

Started the app in serve mode using rspack 0.7.1 and while saving a GUI change in one of the files ran into the below panic:

  ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing chunk ids                                                                                                                            Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  index out of bounds: the len is 279 but the index is 281
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing asset processing                                                                                                                     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
    at <unknown source file>
 2: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
    at <unknown source file>
 3: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
    at <unknown source file>
 4: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
    at <unknown source file>
 5: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
    at <unknown source file>
Done in 157.00s. Peak memory usage 30.66MB.

### Reproduce Steps

Please refer to the details section.

**Comment by pushkargupta9807** [comment]
I think the below error panic message is pretty informative, not sure if needs a repro. 

Message: index out of bounds: the len is 279 but the index is 281
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45

Can we at least have someone triage this bug ? Thanks.

**Comment by pushkargupta9807** [comment]
Got another instance of the above Panic with recompile:

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  index out of bounds: the len is 272 but the index is 280
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing asset processing                                                                                                                                            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
    at <unknown source file>
 2: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
    at <unknown source file>
 3: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
    at <unknown source file>
 4: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
    at <unknown source file>
 5: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
    at <unknown source file>

**Comment by pushkargupta9807** [comment]
@h-a-n-a I am trying for the past few days to create a repro repo to share but i cannot so far. Looking at the file and error message below, does it give any sort of hint ?

Message: index out of bounds: the len is 272 but the index is 280
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45. 


Here is another instance of the same panic,:
![image](https://github.com/web-infra-dev/rspack/assets/93791633/a76a60ac-d741-4269-90a0-34183f92db6c)

**Comment by h-a-n-a** [comment]
> @h-a-n-a I am trying for the past few days to create a repro repo to share but i cannot so far. Looking at the file and error message below, does it give any sort of hint ?
> 
> Message: index out of bounds: the len is 272 but the index is 280 Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45.
> 
> Here is another instance of the same panic,: ![image](https://private-user-images.githubusercontent.com/93791633/339596243-a76a60ac-d741-4269-90a0-34183f92db6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTAyNzUsIm5iZiI6MTcxODcwOTk3NSwicGF0aCI6Ii85Mzc5MTYzMy8zMzk1OTYyNDMtYTc2YTYwYWMtZDc0MS00MjY5LTkwYTAtMzQxODNmOTJkYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDExMjYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYzgwOTk1NDE3NTBlMTg4NDBhMmM5YmQ0NzliODVmOTM3NDAwMTU4MjI0MTYyYmMxZjdlMGMzMjVjZGJiZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qWk9gjOHqQUOZ1iMs7ozVX3YsgLHm6Anrh3CwkNoIZ0)

It would be more helpful if you could provide the reproduction. Otherwise it's too much hard for us to get into the real issue.

**Comment by MuTsunTsai** [comment]
I believe that I encountered essentially the same panic error as @pushkargupta9807.

![image](https://github.com/web-infra-dev/rspack/assets/39870664/5961977e-1910-480f-abeb-431292f8beff)

Can't really reproduce it though as it happens only once.

**Comment by pushkargupta9807** [comment]
@h-a-n-a @jerrykingxyz 
I am trying to create a repro repo , but not getting success there. In the meanwhile many developers in my org are running into this issue and reporting the same.  The size of our repo/ app is huge so it is not straightforward to replicate everything in a smaller repro repo. 

As such I was wondering, from the error code, file and the line number - can we derive some insights as what can lead to this index out of bounds panic?  

@MuTsunTsai do you see a pattern with your dev flow when you run into this panic?

**Comment by MuTsunTsai** [comment]
@pushkargupta9807 I have only seen the error once more since my last comment, so I can't really say I noticed any pattern. I can only make a reasonable guess that, since it happens so rarely and unpredictably, chances are that it has something to do with threading, where execution ordering of threads occasionally mess things up. But it's just a guess. Since the stacktrace didn't really print out anything meaningful, it could be hard to get further insights.
