### ISSUE TITLE
[Bug]: Regression with rebuild/ recompile times with the latest rspack 0.7.1

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#6743]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (32) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 109.55 GB / 125.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/share/nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.23.19 - /usr/bin/yarn
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.0/bin/npm
    Watchman: 20240317.093234.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 125.0.6422.76

### Details

So the release notes for the latest RSPACK 0.7.1 say "10%-15% performance improvement for JavaScript parsing"

I do see performance improvement when booting or cold start for the application in serve mode. However after booting the app , I see a regression with the recompile / reload times when making a simple GUI change. 

Before with 0.7.0 : recompile time : 5.8s
Now with 0.7.1: recompile time: 8.8s. 

Moreover with 0.7.1 after sometime in serve mode I hit the panic which I reported in https://github.com/web-infra-dev/rspack/issues/6742

### Reproduce Steps

1) start an application in serve mode with rspack 0.7.1
2) make a GUI change and observe the regression in recompile times when compared with previous rspack versions.

**Comment by pushkargupta9807** [comment]
Please try with any application you may have to check the recompile times. Are there any performance dashboards? 
Can we please have someone atleast triage this issue, maybe it is already known issue. Thanks

**Comment by pushkargupta9807** [comment]
This is a serious perf degradation issue , and it should affect all the teams who track their inner-loop dev productivity OKRs .

**Comment by h-a-n-a** [comment]
You can check out the latest benchmark here https://web-infra-dev.github.io/rspack-ecosystem-benchmark/ . A reproduction would be helpful to tackle down your issue.

**Comment by markmssd** [comment]
I've also noticed the slow down in HMR. It's not apparent in a small repo which updates in a few milliseconds, but in a larger one, it was taking ~800ms with 0.7.0, and ~1.5s with 0.7.1. @pushkargupta9807 do you think you can put together a repro for this?

**Comment by pushkargupta9807** [comment]
@h-a-n-a @markmssd I have been trying with the repro repo I have, but it is very small and the regression is not quite apparent there. 
Having said that, will it help if I collect and share cpu profile for it ? 

Also the panic reported in  https://github.com/web-infra-dev/rspack/issues/6742 is becoming more frequent :

Message: index out of bounds: the len is 272 but the index is 280
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45

Is the above index pout of bounds reported by others as well?

**Comment by pushkargupta9807** [comment]
@h-a-n-a in benchmark dashboard how do I see and interpret recompile performance?

**Comment by markmssd** [comment]
We can try forking their benchmark repo: https://github.com/web-infra-dev/rspack-ecosystem-benchmark, and then in one branch we install v0.7.0, and in another v0.7.1, and compare the HMR times. I hope that'll work.

**Comment by markmssd** [comment]
@h-a-n-a I was able to reproduce using the [10000](https://github.com/web-infra-dev/rspack-ecosystem-benchmark/tree/main/cases/10000) benchmark case, which I've extracted on its own.

Here is the repro link: https://github.com/markmssd/rspack-hmr-performance-regression.

To run it:

```
git clone https://github.com/markmssd/rspack-hmr-performance-regression
cd https://github.com/markmssd/rspack-hmr-performance-regression && npm install

// now you have v0.7.1 installed

npm start

// edit any file multiple times
// on my Macbook M1, I see HMR times of ~250ms

// now edit `package.json` to install RSPack 0.7.0 and re-run npm install, and repeat
// with 0.7.0, I see refresh times of ~180ms
```

Results using RSPack 0.7.0:
<img width="999" alt="0 7 0" src="https://github.com/web-infra-dev/rspack/assets/5899024/8444ddf0-eef8-49d4-9af1-f0a6c7d68b61">

Results using RSPack 0.7.1:
<img width="999" alt="0 7 1" src="https://github.com/web-infra-dev/rspack/assets/5899024/b9829f67-e6cb-4a78-b801-315db08f5873">

The difference in time is not as big as in our big monorepo, but it still demonstrates the regression consistently. Let me know if you need anything more!

**Comment by pushkargupta9807** [comment]
Thank you @markmssd for the repo. I am also seeing the same factor of regression in my repo which is huge. 
Before with 0.7.0 : recompile time : 5.8s
Now with 0.7.1: recompile time: 8.8s.

Also in your main repo , when you are editing and saving a file multiple times - do you occasionally run into panics like below with 0.7.1?

Message: index out of bounds: the len is 272 but the index is 280
Location: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.2.6/src/map/core.rs:45

**Comment by markmssd** [comment]
I just tried and I couldn't reproduce your error no, sorry. I am using RSPack `0.7.2-canary-fdfff21-20240606140946` which fixes https://github.com/web-infra-dev/rspack/issues/6740, so maybe give that one a try?

**Comment by h-a-n-a** [comment]
Turned out it's more likely related to caching.

In v0.7.0:
<img width="655" alt="image" src="https://github.com/web-infra-dev/rspack/assets/10465670/2d438eb8-c10a-4c4d-9441-8c5d6d4957f1">

In v0.7.1:
<img width="705" alt="image" src="https://github.com/web-infra-dev/rspack/assets/10465670/3d12f239-7fb2-4a8c-83a9-4ff13c144b26">

Would you please confirm @jerrykingxyz ?

**Comment by markmssd** [comment]
Thanks @jerrykingxyz @h-a-n-a! 🚀

**Comment by pushkargupta9807** [comment]
Thank you @markmssd , @jerrykingxyz, @h-a-n-a ! 

1) Can you please let me know how can I pick up above changes - I can test it out in our large repo and provide feedback. 
2) @h-a-n-a can you please lay the exact steps you did to collect and profile the recompile flow as above? I use the a different tool - but your profile looks pretty informative and easy to understand.

**Comment by markmssd** [comment]
I feel like it has slowed down a bit lately, I will re-open a reproduction branch, and try to find at which version the slow down is happening again, then open another issue!
