### ISSUE TITLE
[Bug]: vue 2.6+ vue-loader will parse the template  of the.vue file with JS rule

### ISSUE THREAD

**Issue by Camusama** [web-infra-dev/rspack#6768]
### System Info

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 7.26.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5

### Details

vue 2.6+ vue-loader will parse the template  of the.vue file with JS rule

related to https://github.com/web-infra-dev/rspack/issues/5372

![image](https://github.com/web-infra-dev/rspack/assets/36040009/5a3310d7-3603-4068-84c7-395f88e460a1)

Errors in real projects look like this：

 help: File was processed with this loader: 
 'xxx/node_modules/vue-loader/lib/loaders/templateLoader.js??
vue-loader-options$builtin:swc-loader??
clonedRuleSet-157.use[0]$/xxx/node_modules/vue-loader/lib/index.js??
vue-loader-options

### Reproduce link

https://github.com/Camusama/rspack-vue1.6-loader-issue

### Reproduce Steps

git clone 

https://github.com/Camusama/rspack-vue1.6-loader-issue

remove this 'resourceQuery' config , then you can reproduce it

https://github.com/Camusama/rspack-vue1.6-loader-issue/blob/main/rsbuild.config.ts#L17

**Comment by LingyuCoder** [comment]
Rsbuild does not support vue 2.6, after I installed with pnpm and upgrade to vue 2.7, it works well. cc @chenjiahan

**Comment by chenjiahan** [comment]
The Rsbuild Vue 2 plugin only supports Vue >= 2.7.0:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/d4a1256a-ce76-409e-b495-36500fa30ee9)

https://rsbuild.dev/plugins/list/plugin-vue2

Please upgrade to Vue 2.7 and try again.

**Comment by jeromehan** [comment]
> The Rsbuild Vue 2 plugin only supports Vue >= 2.7.0:
> 
> ![image](https://github.com/web-infra-dev/rspack/assets/7237365/d4a1256a-ce76-409e-b495-36500fa30ee9)
> 
> https://rsbuild.dev/plugins/list/plugin-vue2
> 
> Please upgrade to Vue 2.7 and try again.

`chain.module.rule(CHAIN_ID.RULE.JS).set('resourceQuery', (a) => {
          return !a || !/type=template/.test(a)
        })`
事实上这个配置可以让vue 2.6 工作的很好。vue2.6不支持的原因还是因为rspack最新处理 `if (query.type === `template`) {
    const path = require('path')
    const cacheLoader =
      cacheDirectory && cacheIdentifier
        ? [
            `${require.resolve('cache-loader')}?${JSON.stringify({
              // For some reason, webpack fails to generate consistent hash if we
              // use absolute paths here, even though the path is only used in a
              // comment. For now we have to ensure cacheDirectory is a relative path.
              cacheDirectory: (path.isAbsolute(cacheDirectory)
                ? path.relative(process.cwd(), cacheDirectory)
                : cacheDirectory
              ).replace(/\\/g, '/'),
              cacheIdentifier: hash(cacheIdentifier) + '-vue-loader-template'
            })}`
          ]
        : []

    const preLoaders = loaders.filter(isPreLoader)
    const postLoaders = loaders.filter(isPostLoader)
    const { is27 } = resolveCompiler(this.rootContext, this)

    const request = genRequest([
      ...cacheLoader,
      ...postLoaders,
      ...(is27 ? [] : [templateLoaderPath + `??vue-loader-options`]),
      ...preLoaders
    ])

    // the template compiler uses esm exports
    return `export * from ${request}`
  }` request 组装为

**Comment by chenjiahan** [comment]
We do not plan to make Vue 2.6 compatible in `@rsbuild/plugin-vue` as Vue 2 is EOL. I would recommend creating another community Rsbuild plugin like `rsbuild-plugin-vue-legacy` to support Vue 2.6.
