### ISSUE TITLE
[Bug]: debugger is not source code

### ISSUE THREAD

**Issue by dxhsmwqcwelllee** [web-infra-dev/rspack#6786]
### System Info

System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 43.57 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 7.9.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.4.1
  npmPackages:
    @rspack/cli: 0.6.0 => 0.6.0
    @rspack/core: 0.6.0 => 0.6.0

### Details

mode: 'development',

    cache: true,

    snapshot: {
        resolve: {
            hash: true,
            timestamp: false,
        },

        module: {
            hash: true,
            timestamp: false,
        },
    },

    watch: true,

    devtool: 'source-map', 

    watchOptions: { 
        ignored: [
            '**/node_modules',
            path.posix.resolve(__dirname, '../tool'),
            path.posix.resolve(__dirname, '../cypress'),
            path.posix.resolve(__dirname, '../config'),
            path.posix.resolve(__dirname, '../library'),
            path.posix.resolve(__dirname, '../src/modules'),
        ],
        poll: false,
        aggregateTimeout: 1500,
    },

    optimization: {
        removeAvailableModules: false,
        removeEmptyChunks: false,
        splitChunks: false, 
        minimize: false, 
        concatenateModules: false, 
        usedExports: false, 
    },

    module: {
        rules: utils.styleLoaders({
            sourceMap: false,
            usePostCSS: true,
            data: '@import "~@/styles/theme.scss";',
            additionalData: '@import "~@/styles/theme.scss";',
        }),
    },

    experiments: {
        css: false,
    },

<img width="925" alt="image" src="https://github.com/web-infra-dev/rspack/assets/145088780/a2007fec-fe92-4c79-bf9a-afb63fdd846c">
<img width="956" alt="image" src="https://github.com/web-infra-dev/rspack/assets/145088780/45b93047-cc89-42e5-b28b-04844d9ab344">

### Reproduce Steps

npm run dev

**Comment by hardfist** [comment]
i dont get what the problem is，can you explain more
