### ISSUE TITLE
[Bug]: Custom SWC loader crashes on ^0.7.3

### ISSUE THREAD

**Issue by markmssd** [web-infra-dev/rspack#6802]
### System Info

RSPack v0.7.4-canary-8ea6579-20240613100825

### Details

Unfortunately I couldn't reproduce this issue in `rspack-repro`, but I'm hoping the stacktrace would be enough in this case 🤞🏼

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/webinfra/ec2-macos-ci-0/_work/rspack/rspack/crates/rspack_napi/src/external_takable.rs:45

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: _napi_register_module_v1
    at <unknown source file>
21: _napi_register_module_v1
    at <unknown source file>
22: __pthread_joiner_wake
    at <unknown source file>
```

This is using `v0.7.4-canary-8ea6579-20240613100825`. (with `0.7.3`, ~there is no error, but the build hangs. I will try to see if that is somehow related and update this issue~ the same error happens intermittently too, otherwise it just hangs).

### Reproduce Steps

-

**Comment by h-a-n-a** [comment]
In the release artifact, which you've been using, symbols are stripped. This results in the backtrace or the stack telling nothing useful for debugging. Would you please try to reproduce it so we can proceed?

**Comment by markmssd** [comment]
Ah ok. I'll keep trying. So far I noticed that by using the builtin swc, it's working, and it crashes or hangs only when using our own (by using require.resolve). Not sure if that's related, but I did see an upgrade of swc_core in Rspack, so maybe? I'll re-update once I have a repro.

**Comment by markmssd** [comment]
Alright so using a custom loader, I was indeed able to reproduce it: https://github.com/markmssd/rspack-hmr-performance-regression/tree/swc-custom-loader!

- This repro uses Rspack `0.7.3`, but it's the same with `0.7.4-canary`
- Downgrading to Rspack `0.7.2` works without problem
- On 0.7.3, if you use the builtin loader (uncomment [here](https://github.com/markmssd/rspack-hmr-performance-regression/blob/swc-custom-loader/rspack.config.js#L21-L45) and comment the one below it), it also works
- In this repro, I haven't used the latest SWC/SWC Helpers version, but it's the same with it
- In this repro, I get a different error than in my personal project, possibly because it's different code and crashes at a different place, but it's crashing as expected.

Steps to reproduce:

```
git clone https://github.com/markmssd/rspack-hmr-performance-regression/tree/swc-custom-loader
cd rspack-hmr-performance-regression
npm install --force
npm start
```

<img width="1578" alt="Screenshot 2024-06-14 at 9 12 07 AM" src="https://github.com/web-infra-dev/rspack/assets/5899024/b3eabe31-12bd-4902-88e7-0d5ad05c4ea7">

Let me know if I can provide anything more to help!

**Comment by h-a-n-a** [comment]
Great repro! I was able to reproduce it locally. A fix is coming right over.

**Comment by markmssd** [comment]
Thanks @h-a-n-a ! 🚀 I'll wait for the next release to re-test it (issue is still happening with `0.7.4-canary-bdc2037-20240617004808`, so I guess it doesn't include this fix yet)
