### ISSUE TITLE
[Bug]: The result of bundling with rspack build produces nothing.

### ISSUE THREAD

**Issue by SeonJun-Hwang** [web-infra-dev/rspack#6804]
### System Info

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 223.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    pnpm: 9.1.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.61
    Edge: 126.0.2592.56
    Safari: 17.5
  npmPackages:
    @rspack/cli: 0.7.3 => 0.7.3 
    @rspack/core: 0.7.3 => 0.7.3 

### Details

An issue has occurred in an environment where rspack and codemirror are used together. Without any significant changes, the dev build and the production build are vastly different. Could there be something I've missed in the configuration?

### Reproduce link

https://github.com/SeonJun-Hwang/rspack-codemirror

### Reproduce Steps

1. pnpm -F external build

**Comment by h-a-n-a** [comment]
Thanks for reaching out to us. However, the wording "vastly different" is too vague and the reproduction is not working. Here's what I need:
1. The expected/actual behavior
2. Package `@test/external` is missing. Please fix the demo

**Comment by SeonJun-Hwang** [comment]
@h-a-n-a 
oh, sorry 🫠

**expected/actual behavior**
1. The bundled output should be in `libs/external/dist/index.js`

and I have updated the demo.

**Comment by xc2** [comment]
@SeonJun-Hwang as you're meant to build a library, please set `output.library.type` to the library format you want it be, e.g.,

```
output: {
  library: {
    type: "commonjs"
  }
}
```

Refer to https://webpack.js.org/configuration/output/#outputlibrarytype for available types.

**Comment by xc2** [comment]
I'm closing this issue as it is as expected. Please feel free to ask if you need any further help.
