### ISSUE TITLE
[Bug]: DefinePlugin in webpack will throw a warning for the same key, and rspack will choose to override it.

### ISSUE THREAD

**Issue by nanianlisao** [web-infra-dev/rspack#6821]
### System Info

 System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 92.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.0 
    npm: 9.6.7
    pnpm: 8.9.0 
    bun: 1.0.0
  Browsers:
    Chrome: 126.0.6478.61
    Safari: 16.3

### Details

https://github.com/webpack/webpack/blob/34e2561addb0f65a7a6fb0ce7ae1aea4cd1d599f/lib/DefinePlugin.js#L659-L674

### Reproduce Steps

empty

**Comment by h-a-n-a** [comment]
This is a known issue, as we haven't fully aligned with webpack. Will be fixed, just stay tuned ;-)

**Comment by nanianlisao** [comment]
@h-a-n-a 
Thanks for the reply. I hope this priority can be raised slightly, because this is a relatively hidden but serious bug, especially in rspack and webpack, `process.env.NODE_ENV` will be injected after `optimization.nodeEnv` is turned on.

In addition, if it is convenient, can you provide us with which issue is it duplicated? I will close this issue and subscribe to related content
