### ISSUE TITLE
[Bug]: Build stuck for no reason

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#6833]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 22.46 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.141
  npmPackages:
    @rspack/cli: ^0.7.3 => 0.7.3 
    @rspack/core: ^0.7.3 => 0.7.3 

### Details

Repo:
https://github.com/sima-land/ui-nucleons/tree/storybook-replacement

Branch:
`storybook-replacement`

Subject:
`NODE_ENV=production npm run build` stuck after log "Rspack compiled with 2 warnings in 1.27 s"

### Reproduce link

https://github.com/sima-land/ui-nucleons/tree/storybook-replacement

### Reproduce Steps

1. `npm install`
2. `cd docs`
3. `npm install`
4. `NODE_ENV=production npm run build`
5. see that process stuck

**Comment by h-a-n-a** [comment]
Related to https://github.com/web-infra-dev/rspack/issues/6675
cc @chenjiahan
