### ISSUE TITLE
[Bug]: Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by libt-web** [web-infra-dev/rspack#6849]
### System Info

System:
OS: macOS 13.0
CPU: m1
Memory: 13.28 GB / 16.00 GB
Shell: 3.7.0 - /usr/local/bin/fish
Binaries:
Node: 18.18.0 - /usr/bin/node
Yarn: 1.22.10 - /usr/bin/yarn
npm: 8.9.4 - /home/linuxbrew/.linuxbrew/bin/npm
npmPackages:
@rspack/cli: 0.7.3
@rspack/core: 0.7.3

### Details

I'm getting the following error
`Uncaught ReferenceError: exports is not defined`
Which points to this piece of code
![image](https://github.com/web-infra-dev/rspack/assets/19164750/128e2574-7df2-48d0-989b-823aea209cdc)
It seems like the function argument is called __webpack_exports__ while exports is used in the body. but in other file, it is exports argument 
![image](https://github.com/web-infra-dev/rspack/assets/19164750/447cca9b-8834-40a6-baf7-707e89fade1a)

### Reproduce Steps

I'm not sure yet how to create a small reproduction. Let me know if necessary and I'll try

**Comment by markmssd** [comment]
I'm also running into this issue, with `v0.7.4`. @libt-web can you share your `rspack.config.js` perhaps?

**Comment by libt-web** [comment]
ok,Here's the configuration. 
{
    "mode": "development",
    "entry": {
        "index": "./src/demo/index.tsx"
    },
    "output": {
        "filename": "demo/assets/[name].js",
        "publicPath": "//localhost:80/",
        "assetModuleFilename": "demo/assets/[name].[contenthash:8][ext]"
    },
    "resolve": {
        "modules": [
            "/home/work/demo/node_modules",
            "./node_modules"
        ],
        "extensions": [
            ".js",
            ".jsx",
            ".ts",
            ".tsx",
            ".json"
        ],
        "alias": {}
    },
    "devtool": false,
    "cache": true,
    "stats": "errors-warnings",
    "module": {
        "rules": [
            {
                "resourceQuery": "?raw",
                "oneOf": [
                    {
                        "test":  /.gz$/,
                        "use": "raw-loader"
                    },
                    {
                        "type": "asset/source"
                    }
                ]
            },
            {
                "test": /\.(mjs|js|ts)$/,
                "include": [
                    "/home/work/demo/src",
                    "/home/work/demo/node_modules/swiper",
                    "/home/work/demo/node_modules/proxy-compare",
                ],
                "use": {
                    "loader": "builtin:swc-loader",
                    "options": {
                        "env": {
                            "targets": [
                                "ie >= 11",
                                "chrome >= 49",
                                "safari >= 10"
                            ],
                            "coreJs": "3.21"
                        },
                        "module": {
                            "type": "commonjs"
                        },
                        "sourceMaps": true,
                        "jsc": {
                            "parser": {
                                "syntax": "typescript",
                                "tsx": false
                            },
                            "externalHelpers": true,
                            "transform": {
                                "react": {
                                    "runtime": "automatic",
                                    "development": true
                                }
                            }
                        }
                    }
                }
            },
            {
                "test": /\.(jsx|tsx)$/,
                "include": [
                    "/home/work/demo/src",
                    "/home/work/demo/node_modules/swiper",
                    "/home/work/demo/node_modules/proxy-compare",
                ],
                "use": {
                    "loader": "builtin:swc-loader",
                    "options": {
                        "env": {
                            "targets": [
                                "ie >= 11",
                                "chrome >= 49",
                                "safari >= 10"
                            ],
                            "coreJs": "3.21"
                        },
                        "module": {
                            "type": "commonjs"
                        },
                       
                        "sourceMaps": true,
                        "jsc": {
                            "parser": {
                                "syntax": "typescript",
                                "tsx": true
                            },
                            "externalHelpers": true,
                            "transform": {
                                "react": {
                                    "runtime": "automatic",
                                    "development": true
                                }
                            }
                        }
                    }
                }
            },
            {
                "test": /\.less$/,
                "oneOf": [
                    {
                        "include": [
                            "/home/work/demo/src"
                        ],
                        "use": [
                            {
                                "loader": "postcss-loader",
                                "options": {
                                    "postcssOptions": {
                                        "plugins": [
                                            null,
                                            {
                                                "postcssPlugin": "postcss-px-to-viewport"
                                            }
                                        ]
                                    }
                                }
                            },
                            {
                                "loader": "less-loader",
                                "options": {
                                    "lessOptions": {
                                        "javascriptEnabled": true,
                                        "math": "always"
                                    }
                                }
                            }
                        ],
                        "type": "css/module"
                    },
        ],
        "parser": {
            "css/auto": {
                "namedExports": false
            },
            "css/module": {
                "namedExports": false
            },
            "css": {
                "namedExports": false
            }
        },
        "generator": {
            "css/auto": {
                "esModule": false
            },
            "css/module": {
                "esModule": false
            },
            "css": {
                "esModule": false
            }
        }
    },
    "plugins": [ IgnorePlugin,DefinePlugin,HtmlRspackPlugin]
}
The plugin field here I only wrote roughly, as it involves some personal information.

**Comment by markmssd** [comment]
I wonder if https://github.com/web-infra-dev/rspack/issues/5638 is related 🤔

**Comment by libt-web** [comment]
I also feel that way, but one of the two files here is normal, while the other is abnormal.
However, when I modify the configuration of the swc-loader setting the type of module to es6, the output code matches correctly.
![image](https://github.com/web-infra-dev/rspack/assets/19164750/2e4caf0b-8691-4908-863d-2bd04b838579)
Therefore, I think that modifying the exports variable name to be passed in during the swc-loader conversion to CommonJS could resolve the issue.

**Comment by ahabhgk** [comment]
Seems duplicate with https://github.com/web-infra-dev/rspack/issues/3939

**Comment by libt-web** [comment]
> Seems duplicate with #3939

Unlike that issue, this package have exports.

**Comment by markmssd** [comment]
@ahabhgk would you know what changed between 0.7.3 and 0.7.4 to make this error resurface? I'm thinking some default values maybe? Just can't put my finger on it.

**Comment by ahabhgk** [comment]
It would be great if you can provide a reproduce here, there may be multiple potential issues here with the same error, so it's best if you can provide a reproduce for us to investigate this further.

**Comment by libt-web** [comment]
ok,here is [Demo](https://github.com/libt-web/rspack-demo)
When I was creating a demo, I found that adding module type"javascript/auto" in script rule would prevent errors from occurring.
Is this module type mandatory to set?

**Comment by ahabhgk** [comment]
This is actually expected, "./node_modules/swiper/swiper-react.mjs" notice the ".mjs", if you don't specific the moduleType to "javascript/auto", Rspack will treat its moduleType as "javascript/esm", which you can understand it as strict ESM, in strict ESM you can't use anything related to CommonJS, like `exports`.

And the `exports` in your code is actually introduced by `builtin:swc-loader`, `module: { type: "commonjs" }` will transform you code into CommonJS module system and the `exports` appears ([here is an example](https://play.swc.rs/?version=1.6.3&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIVLBVMAQAZVmF6hIAAAA%3D&config=H4sIAAAAAAAAA12RTY7DIAyF9zlF5HUXoyznDnMIhjopEQaEnWoyVe5eQ5s0idiY75nnHx5N28LIFr7bh4Z6SSYz5u2uhOcg5k8JoCXDNrskcFnVkYvUG89Y0fJSQEweUOor7r66DlaeTeA%2BZtqXyGis7EBFfUa%2BFbhcPviKd%2FQxEYaSL3nCnZinII6wFDWTRDLi7Nbp5gIxaZb7P0xZ5nSUvOvndZyd8eDjr6JDvuK77urEyoROfO3hZvTATlyac7QcduZjZDyWB3Lh1dO2LBsp6Wr43CeQCYPH4280b3egeJ2q%2BP5nmVNtUt0ohpHhk7lW3NzB8c%2F6vKy8WZ5o3E%2BvOAIAAA%3D%3D), you can also change the Module to ES Modules and see the result), so there are two solution here:

1. Add "javascript/auto"
2. A better solution compare to 1: just remove `module: { type: "commonjs" }`, let the `builtin:swc-loader` keep the original ESM module system

**Comment by markmssd** [comment]
Interesting, in my case I already use `javascript/auto` (and don't use `module: { type: "commonjs" }`), but I'm still getting the error. I'll keep trying to make a repro.

**Comment by ahabhgk** [comment]
@markmssd Can you try 0.7.5-canary-c7fe67a-20240621075559, maybe it is caused by `typeof exports === "object" && exports.xxx` which is fixed by https://github.com/web-infra-dev/rspack/pull/6883

**Comment by markmssd** [comment]
> @markmssd Can you try 0.7.5-canary-c7fe67a-20240621075559, maybe it is caused by `typeof exports === "object" && exports.xxx` which is fixed by https://github.com/web-infra-dev/rspack/pull/6883

@ahabhgk it worked! 🎉 Thank you so much, I was going crazy trying to reproduce it.
