### ISSUE TITLE
[Bug]: panic during build phase

### ISSUE THREAD

**Issue by gluhovroma** [web-infra-dev/rspack#6868]
### System Info

System Info
System:
OS: macOS 14.0
CPU: (10) arm64 Apple M1 Max
Shell: 5.9 - /bin/zsh
Binaries:
Node: 16.14.2 
npm: 8.5.0

### Details

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should print diagnostics:   × an error occurred when formatting an argument

Location: crates/rspack_core/src/stats.rs:391

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
    
    
This happens when I connect css like this:

`import 'semantic-ui-css/semantic.min.css';`
And use CssExtractRspackPlugin as described in the instructions
```
module: {
   rules: [ 
      {
          test: /\.css$/i,
          use: [rspack.CssExtractRspackPlugin.loader, 'css-loader'],
          type: 'css',
       }
   ]
}
```

### Reproduce Steps

run rspack

**Comment by LingyuCoder** [comment]
Try to create a [minimal repro](https://github.com/LingyuCoder/bundler-playground/tree/main/rspack/css-extract-stats-error) but fail, can you provide one?

**Comment by h-a-n-a** [comment]
```diff
module: {
   rules: [ 
      {
          test: /\.css$/i,
          use: [rspack.CssExtractRspackPlugin.loader, 'css-loader'],
-          type: 'css',
       }
   ]
}
```
