### ISSUE TITLE
[Bug]: Failed to resolve tsconfig paths when using extends（version：0.7.1） 

### ISSUE THREAD

**Issue by Zavieer** [web-infra-dev/rspack#6870]
### System Info

OS: Win10
CPU: Intel(R)_Core(TM)_i7-10700

### Details

https://github.com/web-infra-dev/rspack/issues/5671

  The problem appears to manifest similarly to this issue. From what I saw in the original issue, it seems that upgrading the version of `oxc_resolver` resolved the problem. However, I can still reproduce the issue with the latest version of rspack (`"@rspack/core": "0.7.1"`).

### Reproduce link

https://github.com/chenjiahan/rsbuild-repro-extend-tsconfig-base-url

### Reproduce Steps

From the example provided in the original issue, pull down the code and update the dependency to version 0.7.1

git clone [git@github.com](mailto:git@github.com):chenjiahan/rsbuild-repro-extend-tsconfig-base-url.git
pnpm i
pnpm build (to run rspack build, failed)
pnpm build:webpack (to run webpack build, succeed)
npx tsc (to run tsc, succeed)

**Comment by CPunisher** [comment]
I tested it on `rspack@alpha` without problems. rsbuild may encapsulate some configurations that need to be configured manually if using rspack directly. Here is an example:

```js
const path = require("node:path");

/**
 * @type {import('webpack').Configuration | import('@rspack/cli').Configuration}
 */
module.exports = {
  mode: "development",
  entry: "./src/index.tsx",
  resolve: {
    extensions: [".ts"],
    tsConfig: path.resolve(__dirname, "tsconfig.json"),
  },
  module: {
    rules: [
      {
        test: /\.(j|t)sx?$/,
        exclude: [/[\\/]node_modules[\\/]/],
        loader: "builtin:swc-loader",
        options: {
          sourceMap: false,
          jsc: {
            parser: {
              syntax: "typescript",
            },
            externalHelpers: true,
            transform: {
              react: {
                runtime: "automatic",
                development: true,
              },
            },
          },
        },
      },
    ],
  },
};

```

**Comment by xc2** [comment]
For rspack before 1.0.0:

```js
resolve: {
  tsConfig: {
    configFile: path.resolve(__dirname, "tsconfig.json")
  },
}
```
