### ISSUE TITLE
[Doc]: Missing sentence in optimization.mergeDuplicateChunks part of docs

### ISSUE THREAD

**Issue by Verthon** [web-infra-dev/rspack#6890]
### System Info

**System:**
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 187.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

  **Binaries:**
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.1.0 - /opt/homebrew/bin/pnpm

  **Browsers:**
    Chrome: 126.0.6478.63
    Safari: 17.4

### Details

Hi

While reading the documentation, I noticed an incomplete sentence in the `mergeduplicatechunk` section. Specifically, this part:
`If you are encountering performance issues, and you are using`

<img width="990" alt="Screenshot 2024-06-23 at 11 06 49" src="https://github.com/web-infra-dev/rspack/assets/25480861/d275e69a-d55c-488a-a880-8127553d87d0">

### Reproduce link

https://www.rspack.dev/config/optimization#optimizationmergeduplicatechunks

### Reproduce Steps

1. Visit https://www.rspack.dev/config/optimization#optimizationmergeduplicatechunks
2. Check last sentence in the `INFO` green box

**Comment by wxiaoyun** [comment]
Seems to be an issue with Rspress instead of documentation

**Comment by Timeless0911** [comment]
> Seems to be an issue with Rspress instead of documentation

Thanks, see https://github.com/web-infra-dev/rspress/issues/1208#issuecomment-2190588906 for workaround way to fix this.
