### ISSUE TITLE
Dev Server errors on code changes: StringExpected, Failed to convert JavaScript value `Undefined` into rust type `String`

### ISSUE THREAD

**Issue by SharmaTushar** [web-infra-dev/rspack#6943]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (10) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.11 GB / 40.00 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rspack/cli: ^0.7.5 => 0.7.5 
    @rspack/core: ^0.7.5 => 0.7.5 
    @rspack/plugin-react-refresh: ^0.7.5 => 0.7.5

### Details

Making any changes to code results in error:
```
<e> [webpack-dev-middleware] [Error:   × StringExpected, Failed to convert JavaScript value `Undefined` into rust type `String`
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

### Reproduce link

https://github.com/SharmaTushar/rspack-generic-failure

### Reproduce Steps

Run the server
change code

**Comment by h-a-n-a** [comment]
The filename returned in `options.filename` function should not be an `undefined`
