### ISSUE TITLE
[Bug]: incorrect LICENSE.txt

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#6971]
### System Info

None

### Details

I was testing this https://github.com/umijs/benchmark/tree/master/projects/three10x

`pnpm run bundler rsbuild build`

In the `three10x` benchmark, it produced a license file

`dist/static/js/async/213.bf016bb8.js.LICENSE.txt`

with the content

```
// !\ DECLARE ALIAS AFTER assign prototype !

// !\ DECLARE ALIAS AFTER assign prototype !
```

### Reproduce Steps

See above

**Comment by CPunisher** [comment]
I think there are two reasons.
1. The project is using a webpack configuration with `extractComments` turned off. ([Code](https://github.com/umijs/umi/blob/c0da93f15874cda70081458dbc6c4a2e3c28a2a4/packages/bundler-webpack/src/config/compressPlugin.ts#L83))
3. The SwcJsMinimizerRspackPlugin does not remove duplicate comments, but the TerserWebpackPlugin does. ([Code](https://github.com/webpack-contrib/terser-webpack-plugin/blob/d09ed4f8df2fd854354f45016b00d8a3542a470b/src/utils.js#L449))
