### ISSUE TITLE
[Bug]: Global polyfill no longer seems to work

### ISSUE THREAD

**Issue by isuro** [web-infra-dev/rspack#6984]
### System Info

  System:
    OS: Linux 6.9 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) arm64 unknown
    Memory: 4.82 GB / 23.43 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chromium: 115.0.5790.75
  npmPackages:
    @rspack/core: ^0.7.5 => 0.7.5
    @rspack/dev-server: ^0.7.5 => 0.7.5

### Details

After upgrading from rspack 0.7.0 to 0.7.5, global is no longer polyfilled for browser environments. This is true when left at the default behavior or when explicitly passing `node: {global: true}`.

### Reproduce Steps

1. Run rspack over code that uses global
	In our case, the specific line that fails is `const g: any = global;`
2. Global is undefined

**Comment by xc2** [comment]
tried to reproduce with no luck, would you please help creating a repo with reproductable setup.

**Comment by isuro** [comment]
I think the specific issue may have been code like this:

```js
const g = window || global

g.foo = BAR
...
```
