### ISSUE TITLE
[Bug]: ProgressPlugin: time is NaN

### ISSUE THREAD

**Issue by renzp94** [web-infra-dev/rspack#7007]
### System Info

 System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.03 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 1.1.16 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5

### Details

`@rspack/core`: 0.7.5
`@rspack/dev-server`: 0.7.5

run dev-server done:   
![image](https://github.com/web-infra-dev/rspack/assets/20986285/68f3d1e5-bc01-4b85-8fdf-f17c74364bda)

time is NaN

### Reproduce link

https://github.com/renzp94/rzpack

### Reproduce Steps

1. `pnpm install`
2. `pnpm run playground:dev`

**Comment by xc2** [comment]
## Related

https://github.com/sodatea/friendly-errors-webpack-plugin but not ProgressPlugin

## Why does it happen

The `friendly-errors-webpack-plugin` produces compilation time with `stats.{endTime,startTime}` which are private and not included by rspack.

## Will rspack implement these private apis

Sorry but I'm not sure. IMO if a private api is not widely used, rspack would not implement it.

## How to break out

As this plugin seems to be inactive, there's a workaround to help you breaking out:

```js
class _FriendlyErrorsWebpackPlugin extends FriendlyErrorsWebpackPlugin {
  getStatsCompileTime(stats, statsIndex) {
    // use `stats.compilation.startTime` and `stats.compilation.endTime` instead.
    // alternatively, this will help as well: `stats.toJson({ all: false, builtAt: true, timings: true })`
    const {endTime, startTime} = stats.compilation;
    if (statsIndex !== undefined) {
      if (this.previousEndTimes[statsIndex] === endTime) {
        return 0;
      }

      this.previousEndTimes[statsIndex] = endTime;
    }

    return endTime - startTime;
  }
```
