### ISSUE TITLE
[Bug]: (1.0.0-alpha)Js API rspack build out info no have gzip info

### ISSUE THREAD

**Issue by renzp94** [web-infra-dev/rspack#7013]
### System Info

System:
OS: macOS 14.5
CPU: (8) arm64 Apple M1 Pro
Memory: 1.03 GB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
Yarn: 1.22.17 - /usr/local/bin/yarn
npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
bun: 1.1.16 - ~/.bun/bin/bun
Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
Browsers:
Chrome: 126.0.6478.127
Safari: 17.5
@rspack/core: 1.0.0-alpha
@rspack/dev-server: 1.0.0-alpha

### Details

use `compression-webpack-plugin`

In Rspack

```ts
{
  type: 'asset',
  name: 'assets/js/main.077a04b94619b60740b7.js',
  size: 4491,
  emitted: true,
  info: {
    minimized: false,
    development: false,
    hotModuleReplacement: false,
    immutable: false,
    chunkHash: [],
    contentHash: [],
    related: {}
  },
  chunkNames: [ 'main' ],
  chunks: [ '909' ]
}
assets/js/main.077a04b94619b60740b7.js.gz  2.353KB  [immutable]
{
  type: 'asset',
  name: 'assets/js/runtime~main.32b00dbd6e2a82c572b7.js.gz',
  size: 1290,
  emitted: true,
  info: {
    minimized: false,
    development: false,
    hotModuleReplacement: false,
    immutable: true,
    chunkHash: [],
    contentHash: [],
    related: {}
  },
  chunkNames: [],
  chunks: []
}
```
When using JS API packaging, there is no gzip information in the output information.

In Webpack

```ts
{
  type: 'asset',
  name: 'assets/js/main.3707b15860c4a7f9c9fa.js',
  size: 3284,
  emitted: true,
  comparedForEmit: false,
  cached: false,
  info: {
    immutable: true,
    contenthash: '3707b15860c4a7f9c9fa',
    javascriptModule: false,
    minimized: true,
    related: { gzipped: 'assets/js/main.3707b15860c4a7f9c9fa.js.gz' },
    size: 3284
  },
  chunkNames: [ 'main' ],
  chunkIdHints: [],
  auxiliaryChunkNames: [],
  auxiliaryChunkIdHints: [],
  filteredRelated: 0,
  related: [
    {
      type: 'gzipped',
      name: 'assets/js/main.3707b15860c4a7f9c9fa.js.gz',
      size: 1640,
      emitted: true,
      comparedForEmit: false,
      cached: false,
      info: [Object],
      chunkNames: [],
      chunkIdHints: [],
      auxiliaryChunkNames: [],
      auxiliaryChunkIdHints: [],
      filteredRelated: undefined,
      related: {},
      chunks: [],
      auxiliaryChunks: [],
      isOverSizeLimit: false
    }
  ],
  chunks: [ 792 ],
  auxiliaryChunks: [],
  isOverSizeLimit: false
}
```

There is a related attribute in the webpack, which contains information related to gzip.

### Reproduce link

https://github.com/renzp94/rzpack

### Reproduce Steps

1. `pnpm install`
2. run Rspack
    1. change `playground/rzpack.config.ts`：`builder: BUILDER.WEBPACK` -> `builder: BUILDER.RSPACK`
    2. `pnpm playground:build`
3. run Webpack
    1. change `playground/rzpack.config.ts`：`builder: BUILDER.RSPACK` -> `builder: BUILDER.WEBPACK`
    2. `pnpm playground:build`

**Comment by h-a-n-a** [comment]
This is not related with Rspack. `gzipped` information does not come naturally with rspack. Please refer to https://github.com/webpack-contrib/compression-webpack-plugin
