### ISSUE TITLE
[Bug]: moduleIds: deterministic is not stable during rebuild

### ISSUE THREAD

**Issue by mrceperka** [web-infra-dev/rspack#7031]
### System Info

```
  System:
    OS: Linux 6.5 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 9.16 GB / 23.13 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @rspack/cli: ^1.0.0-alpha.0 => 1.0.0-alpha.0 
    @rspack/core: ^1.0.0-alpha.0 => 1.0.0-alpha.0 
    @rspack/plugin-react-refresh: ^1.0.0-alpha.0 => 1.0.0-alpha.0
```

### Details

When running in dev mode (`rspack dev`) `optimization.moduleIds="deterministic"` causes errors like `undefined factory 19218`  
I have had hmr and hot mode also enabled.

When changed to `moduleIds: isDev ? "named" : "deterministic"` it works.

### Reproduce Steps

1. set `optimization.moduleIds="deterministic`
2. `rspack dev` with hmr

**Comment by JSerFeng** [comment]
Can you try to create a minimum repro repo

**Comment by mrceperka** [comment]
@JSerFeng I am not at the moment. I've tried with the repro repo but it was working as expected. But I haven't installed all the plugins and dependencies my original repo has.

Is there some command that could help you debug? I think I could run that in private repo and give you output.

**Comment by colinaaa** [comment]
Same issue here. I can provide an internal repro. It works when using Rspack `1.0.0-alpha.0` but does not work when using Rspack `1.0.0-alpha.1`.

**Comment by JSerFeng** [comment]
try 1.0.0-alpha.2

**Comment by mrceperka** [comment]
@JSerFeng it won't even start now :(

```
NODE_ENV=development HMR=1 rspack dev -c webpack/rspack.app.config.js
/var/docker/frontend_v2/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/docker/frontend_v2/node_modules/string-width/index.js from /var/docker/frontend_v2/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /var/docker/frontend_v2/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/yargs/build/index.cjs:1:60039)
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/@rspack/cli/dist/cli.js:35:33)
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/@rspack/cli/dist/bootstrap.js:4:15)
    at Object.<anonymous> (/var/docker/frontend_v2/node_modules/@rspack/cli/bin/rspack:2:16) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by JSerFeng** [comment]
> Error [ERR_REQUIRE_ESM]: require() of ES Module

This is not issue with rspack, can you solve it and then continue trying 1.0.0-alpha.2

**Comment by mrceperka** [comment]
@JSerFeng maybe it's not directly, but why 1.0.0-alpha.0 works and 1.0.0-aplha.2 not? It looks like some rspack dependencies were updated and not the build is broken. When I downgrade to alpha.0 its able to run.

**Comment by JSerFeng** [comment]
I think it's because some dependencies are unexpectedly hoist, can you try using pnpm

**Comment by mrceperka** [comment]
@JSerFeng thanks for the tip. Will try. I am using yarn v1 and it was working so far (I mean with alpha.0)

**Comment by Herz3h** [comment]
I had to change to "named" too, just testing to use rspack instead of webpack, and faced among many other issues(no amd support, etc..) this one

I have v1.0.14, and the issue still present

**Comment by JSerFeng** [comment]
> I have v1.0.14, and the issue still present

Can you provide more info, like which module factory is missing ?

**Comment by JSerFeng** [comment]
If you could give me a repro, I can fix that soon

**Comment by JSerFeng** [comment]
FYI: I've found a repro repo, will fix this

**Comment by ScriptedAlchemy** [comment]
Experiencing this internally as well on Ark

**Comment by ScriptedAlchemy** [comment]
There is also an issue with contenthash in development mode in ark, i have to use chunkhash otherwise the js file and stats do not match what import from is rundering in the chunk. stats and files match but the chunks are referencing hashed ids that do not match whats on disk
