### ISSUE TITLE
refactor: migrate codebase to pure esm

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7089]
we migrate lots of webpack's internal code which is commonjs format, which may cause some interop issue with rspack's esm code  and is not good for treeshaking if we bundle rspack's code.
we should migrate all existing commonjs code to esm
**notice that we do migrate to esm module other than strict esm module during this refactor which means we still compiles all code to commonjs**

strict esm maybe supported in 2.0

**Comment by SoonIter** [comment]
this task has been done in https://github.com/web-infra-dev/rspack/issues/7225
