### ISSUE TITLE
[Bug]: Panic occurred at runtime.

### ISSUE THREAD

**Issue by bczak** [web-infra-dev/rspack#7125]
### System Info

Macbook pro m3 pro 18gb

### Details

Message:  assertion failed: self.max_target_is_set
Location: crates/rspack_core/src/exports_info.rs:1722

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: _napi_register_module_v1
    at <unknown source file>
21: _napi_register_module_v1
    at <unknown source file>
22: _napi_register_module_v1
    at <unknown source file>
23: _napi_register_module_v1
    at <unknown source file>
24: _napi_register_module_v1
    at <unknown source file>
25: _napi_register_module_v1
    at <unknown source file>
26: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
27: _napi_register_module_v1
    at <unknown source file>
28: _napi_register_module_v1
    at <unknown source file>
29: _napi_register_module_v1
    at <unknown source file>
30: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
31: _napi_register_module_v1
    at <unknown source file>
32: _napi_register_module_v1
    at <unknown source file>
33: _napi_register_module_v1
    at <unknown source file>
34: _napi_register_module_v1
    at <unknown source file>
35: __pthread_joiner_wake
    at <unknown source file>
error: script "build" was terminated by signal SIGABRT (Abort)
[1]    16439 abort      bun run build

### Reproduce Steps

bun run dev

**Comment by h-a-n-a** [comment]
It was fixed in 1.0.0-alpha.3. Please upgrade and try again :-)
https://github.com/web-infra-dev/rspack/pull/7082
