### ISSUE TITLE
[Bug]: config `optimization` option `nodeEnv: 'production'` does not work with rspack 0.7.5 `development` mode

### ISSUE THREAD

**Issue by pauliusg** [web-infra-dev/rspack#7128]
### System Info

```
{
  "name": "rspack-project",
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "dev": "cross-env NODE_ENV=development rspack serve",
    "build": "cross-env NODE_ENV=production rspack build"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@rspack/cli": "^0.7.5",
    "@rspack/core": "^0.7.5",
    "@rspack/plugin-react-refresh": "^0.7.5",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "cross-env": "^7.0.3",
    "react-refresh": "^0.14.2",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.3"
  }
}

```

### Details

In Webpack this works without issue, however with Rspack I see an error in the browser: 
```
Uncaught Error: React Refresh runtime should not be included in the production bundle.
    at ./node_modules/react-refresh/cjs/react-refresh-runtime.production.min.js (react-refresh-runtime.production.min.js:10:1)
    at __webpack_require__ (stripAnsi.js:18:1)
    at fn (stripAnsi.js:18:1)
    at ./node_modules/react-refresh/runtime.js (runtime.js:4:1)
    at __webpack_require__ (stripAnsi.js:18:1)
    at fn (stripAnsi.js:18:1)
    at ./node_modules/@rspack/plugin-react-refresh/client/reactRefreshEntry.js (reactRefreshEntry.js:9:1)
    at __webpack_require__ (stripAnsi.js:18:1)
    at stripAnsi.js:18:1
    at stripAnsi.js:18:1
``` 

Looks like React code is compiled in `development` mode. We need this for test engineers who are writing E2E tests. We need to have dev server and React in `production` mode not to show React warnings when they are working with tests.

### Reproduce Steps

- run: `npm create rspack@latest`
- enter project name
- choose: `react-ts`
- in generated `rspack.config.ts` add ```optimization: { nodeEnv: 'production' }```
- run `npm run dev`
- Check bwoser console in `http://localhost:8080/`

Whole  `rspack.config.ts` file content:
```
import { defineConfig } from "@rspack/cli";
import { rspack } from "@rspack/core";
import * as RefreshPlugin from "@rspack/plugin-react-refresh";

const isDev = process.env.NODE_ENV === "development";

export default defineConfig({
	context: __dirname,
	entry: {
		main: "./src/main.tsx"
	},
	resolve: {
		extensions: ["...", ".ts", ".tsx", ".jsx"]
	},
	module: {
		rules: [
			{
				test: /\.svg$/,
				type: "asset"
			},
			{
				test: /\.(jsx?|tsx?)$/,
				use: [
					{
						loader: "builtin:swc-loader",
						options: {
							jsc: {
								parser: {
									syntax: "typescript",
									tsx: true
								},
								transform: {
									react: {
										runtime: "automatic",
										development: isDev,
										refresh: isDev
									}
								}
							},
							env: {
								targets: [
									"chrome >= 87",
									"edge >= 88",
									"firefox >= 78",
									"safari >= 14"
								]
							}
						}
					}
				]
			}
		]
	},
	plugins: [
		new rspack.DefinePlugin({
			"process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV)
		}),
		new rspack.ProgressPlugin({}),
		new rspack.HtmlRspackPlugin({
			template: "./index.html"
		}),
		isDev ? new RefreshPlugin() : null
	].filter(Boolean),
	experiments: {
		css: true
	},
	optimization: { nodeEnv: 'production' }
});

```

As I have mentioned, this configuratoin works with Webpack without issues, React code is compiled in `production` mode.

**Comment by h-a-n-a** [comment]
Would you please try out the latest `1.0.0-alpha.3`? This might be fixed.

**Comment by pauliusg** [comment]
@h-a-n-a, I am using `npm` v10.5.0 and `node` v18.20.2 in windows WSL and when I try steps:
- run: npm create rspack@latest
- choose: `react-ts`
- enter project name: `test`
- run: `cd test`
- run `npm install`

I see error with `1.0.0-alpha.3`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: new-pr@1.0.0
npm ERR! Found: @rspack/core@1.0.0-alpha.3
npm ERR! node_modules/@rspack/core
npm ERR!   dev @rspack/core@"1.0.0-alpha.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @rspack/core@">=0.4.0" from @rspack/cli@1.0.0-alpha.3
npm ERR! node_modules/@rspack/cli
npm ERR!   dev @rspack/cli@"1.0.0-alpha.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2024-07-12T06_51_08_576Z-eresolve-report.txt
```
Something is not right with `1.0.0-alpha.3` dependencies.

**Comment by h-a-n-a** [comment]
> @h-a-n-a, I am using `npm` v10.5.0 and `node` v18.20.2 in windows WSL and when I try steps:
> 
> * run: npm create rspack@latest
> * choose: `react-ts`
> * enter project name: `test`
> * run: `cd test`
> * run: `npm install`
> 
> I see error with `1.0.0-alpha.3`:
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: new-pr@1.0.0
> npm ERR! Found: @rspack/core@1.0.0-alpha.3
> npm ERR! node_modules/@rspack/core
> npm ERR!   dev @rspack/core@"1.0.0-alpha.3" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @rspack/core@">=0.4.0" from @rspack/cli@1.0.0-alpha.3
> npm ERR! node_modules/@rspack/cli
> npm ERR!   dev @rspack/cli@"1.0.0-alpha.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! /root/.npm/_logs/2024-07-12T06_51_08_576Z-eresolve-report.txt
> ```
> 
> Something is not right with `1.0.0-alpha.3` dependencies. But that`s another issue.
> 
> **Update:** If I run `npm i --legacy-peer-deps` then I need more changes in config not to show warning:
> 
> ```
> WARNING in ⚠ DefinePlugin:
>   │ Conflicting values for 'process.env.NODE_ENV' ("\"development\"" !== "\"production\"")
> ```
> 
> So, with config:
> 
> ```
> ...
> 		new rspack.DefinePlugin({
> 			"process.env.NODE_ENV": JSON.stringify('production')
> 		}),
> ...
>   optimization: { nodeEnv: 'production' }
> ...
> ```
> 
> Running `npm run dev` and going to http://localhost:8080/ shows **another** error in the console:
> 
> ```
> Uncaught Error: React Refresh runtime should not be included in the production bundle.
>     at ./node_modules/react-refresh/cjs/react-refresh-runtime.production.min.js (react-refresh-runtime.production.min.js:10:1)
>     at __webpack_require__ (stripAnsi.js:18:1)
>     at fn (stripAnsi.js:18:1)
>     at ./node_modules/react-refresh/runtime.js (runtime.js:4:1)
>     at __webpack_require__ (stripAnsi.js:18:1)
>     at fn (stripAnsi.js:18:1)
>     at ./node_modules/@rspack/plugin-react-refresh/client/reactRefreshEntry.js (reactRefreshEntry.js:9:1)
>     at __webpack_require__ (stripAnsi.js:18:1)
>     at stripAnsi.js:18:1
>     at stripAnsi.js:18:1
> ```

Rspack's template use `NODE_ENV=development` by default. With this setting, react-refresh is injected. Change the script to for example `"cross-env NODE_ENV=production rspack serve"` should fix this.
