### ISSUE TITLE
[Bug]: Output contains a __webpack_require__(null) call which causes a crash

### ISSUE THREAD

**Issue by LinusCenterstrom** [web-infra-dev/rspack#7133]
### System Info

  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 10.50 GB / 63.58 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527

### Details

The output code contains a call to webpack_require with null as a parameter.
This causes a crash at runtime.
I'm not quite sure what in causes it exactly, but the linked repo is a minimal repro that does have the bug.

### Reproduce link

https://github.com/LinusCenterstrom/rspack-repro-buildfail/tree/ca99fd0119fa67ba3165d5b868707390ea1fbff8

### Reproduce Steps

yarn install
yarn build
check outputfile index.js in the dist folder

**Comment by ahabhgk** [comment]
Fixed by https://github.com/web-infra-dev/rspack/pull/7212, could you checkout if it still exists in nightly version [1.0.0-canary-b3bac1b-20240719023634](https://www.npmjs.com/package/@rspack/core-canary/v/1.0.0-canary-b3bac1b-20240719023634)

**Comment by LinusCenterstrom** [comment]
That seems to have fixed it
