### ISSUE TITLE
[Feature]: support for exclude option by LightningCssMinimizerRspackPlugin

### ISSUE THREAD

**Issue by dartess** [web-infra-dev/rspack#7135]
### What problem does this feature solve?

Already described for `SwcCssMinimizerRspackPlugin`: https://github.com/web-infra-dev/rspack/issues/6898

I need to disable minification of third-party library files that are simply copied to build.

I managed to prevent minification of the JS using the exclude option, but it seems that the option for the CSS minifier has not yet been implemented.

### What does the proposed API of configuration look like?

```js
  optimization: {
    minimizer: [
      new SwcJsMinimizerRspackPlugin({ exclude: /^assets\// }), // <-- this is works
      new LightningCssMinimizerRspackPlugin({ exclude: /^assets\// }), // <-- this doesn't exist
    ],
  }
```

**Comment by shulaoda** [comment]
Try it. 🙌
