### ISSUE TITLE
[Feature]: `ChunkGraph.setModuleId`

### ISSUE THREAD

**Issue by jacob-ebey** [web-infra-dev/rspack#7148]
### What problem does this feature solve?

Allows for custom naming of modules and brings RSPack's API closer to Webpack's.

### What does the proposed API of configuration look like?

Just the webpack API: https://github.com/webpack/webpack/blob/277460b33bcc49c51acbbcd688672aa4ec685732/types.d.ts#L1221

```js
compilation.chunkGraph.setModuleId(mod, stringOrNumber)
```

**Comment by h-a-n-a** [comment]
We are not planning to expose **mutable** internal data structures like `ChunkGraph` to JS. In the future, we may provide Rust plugins to support this.
