### ISSUE TITLE
[Bug]: Seems that require.context always include subdirs even though set as false

### ISSUE THREAD

**Issue by hanstf** [web-infra-dev/rspack#7153]
### System Info

System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 91.17 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.6.7 - ~/Documents/node_modules/.bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @rspack/cli: ^0.7.5 => 0.7.5 
    @rspack/core: ^0.7.2 => 0.7.5 
    @rspack/dev-server: ^0.7.2 => 0.7.5 
    @rspack/plugin-minify: ^0.6.1 => 0.6.5 
    @rspack/plugin-react-refresh: ^0.6.1 => 0.6.5 

### Details

We are currently migrating from webpack to rspack.

We are trying to do ```require.context('../database/seeds', false, /^\.\/.*\.ts$/)```
where our structure is as follow:

```
subscription/
├── database/
│   ├── seeds/
│   │   ├── data/
│   │   │   └── data.ts
│   └── seedfiles.ts
├── src/
│   └── main.ts (file that calling the require.context)
```

previously when using webpack, it only includes the seedfiles.ts which is correct but it seems now even I set the includeSubdirs to false, it also includes the data/data.ts

The generated code is as follow:
```__webpack_require__(/*! ../database/seeds */ "./apps/subscription/database/seeds sync recursive ^\\.\\/.*\\.ts$")```

### Reproduce Steps

1. run require.context with includeSubdirs as false
2. subdirs is also included

**Comment by LingyuCoder** [comment]
Tried to reproduce the issue with [test repo](https://github.com/LingyuCoder/bundler-playground/blob/main/rspack/require-context/src/index.js) and `@rspack/core@0.7.5` but failed.

The require.context will be compiled to this:

```js
const r = __webpack_require__("./database/seeds sync ^\\.\\/.*\\.js$")
```

Can you provide a repro?
