### ISSUE TITLE
[Bug]: Removing CSS File while runnning `npm run dev` results in compile error

### ISSUE THREAD

**Issue by ALEXWARELLC** [web-infra-dev/rspack#7172]
### System Info

System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 16.52 GB / 31.84 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527

### Details

Hello!

When running 'npm run dev' and removing a CSS link in the main TypeScript file, it fails to compile instead of recompiling the TypeScript file, which is what I assumed would occur.

If this is intended behavior, you can ignore this :)

### Reproduce Steps

1. Create a template project using `npm create rsbuild@latest`. I selected Svelte & TypeScript with no additional tools.
2. Start a dev server using `npm run dev`.
3. Remove the CSS styling import in `index.ts` and wait for the rebuild.
4. Compile Error

**Comment by LingyuCoder** [comment]
I have tried the latest version which is `rsbuild@1.0.1-beta.3` and it works well. Seems this issue had been solved.
