### ISSUE TITLE
[Bug]: 也更新后报错

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rspack#7202]
### System Info

System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^1.0.1-beta.2",
    "@rsbuild/plugin-babel": "^1.0.1-beta.2",
    "@rsbuild/plugin-less": "^1.0.1-beta.2",
    "@rsbuild/plugin-vue2": "^1.0.1-beta.2",
    "@rsbuild/plugin-vue2-jsx": "^1.0.1-beta.2"

### Details

<img width="948" alt="1111" src="https://github.com/user-attachments/assets/709e5f27-4aa5-40d9-bbd7-39da3bcaccb3">
修改代码后直接报错

### Reproduce Steps

npm run dev

**Comment by LingyuCoder** [comment]
fixed by #7197, please upgrade to v1.0.0-alpha.5
