### ISSUE TITLE
[Bug]: should have dependency id

### ISSUE THREAD

**Issue by TryChai** [web-infra-dev/rspack#7207]
### Version

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 1.94 GB / 15.66 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (126.0.2592.102)
    Internet Explorer: 11.0.19041.1202
```

### Details

 Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have dependency id
Location: crates\rspack_plugin_javascript\src\dependency\context\import_meta_context_dependency.rs:104

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
![image](https://github.com/user-attachments/assets/39821ac2-7ca5-4981-838b-60da28af3bba)

### Reproduce link

no link

### Reproduce Steps

i change the project from vite to rsbuild,follow the doc ,set the config 
import { defineConfig } from '@rsbuild/core';
import { pluginVue } from '@rsbuild/plugin-vue';
import { pluginSass } from '@rsbuild/plugin-sass';
import { resolve } from 'path';
const pathResolve = (dir: string) => {
	return resolve(__dirname, '.', dir);
};

export default defineConfig({
  plugins: [
	pluginVue(),
	pluginSass()
  ],
  html: {
    template: './index.html',
  },
  source: {
    entry: {
      index: './src/main.ts',
    },
	alias: {
      '/@': pathResolve('./src/'),
	  'vue-i18n': 'vue-i18n/dist/vue-i18n.cjs.js',
	  __VUE_I18N_LEGACY_API__: JSON.stringify(false),
	__VUE_I18N_FULL_INSTALL__: JSON.stringify(false),
	__INTLIFY_PROD_DEVTOOLS__: JSON.stringify(false),
	__VERSION__: JSON.stringify(process.env.npm_package_version),
	__NEXT_NAME__: JSON.stringify(process.env.npm_package_name),
    },
  },
});
and run build ,it was failed

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/526da66f-343f-46a3-9335-853c60fe3cc0)
i only change the name,but i don`t konw the webpackContext how to use

**Comment by LingyuCoder** [comment]
You can try this nightly version:  `1.0.0-canary-b3bac1b-20240719023634 `

**Comment by TryChai** [comment]
update the lastest version?

**Comment by LingyuCoder** [comment]
> update the lastest version?

no, just override the `@rspack/core` to `1.0.0-canary-b3bac1b-20240719023634`, you can use the [`overrides`] field(https://pnpm.io/package_json#pnpmoverrides) in `package.json`

**Comment by TryChai** [comment]
ok,let me try

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/1345e550-a6a8-4705-bc6e-e51f8fe3e05b)
![image](https://github.com/user-attachments/assets/94966318-0f09-48e1-bdf0-daec6a7476be)
i get the same result

**Comment by LingyuCoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/30064871/350305733-1345e550-a6a8-4705-bc6e-e51f8fe3e05b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzU0NjksIm5iZiI6MTcyMTM3NTE2OSwicGF0aCI6Ii8zMDA2NDg3MS8zNTAzMDU3MzMtMTM0NWU1NTAtYTZhOC00NzA1LWJjNmUtZTUxZjhmZTNlMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzJlMjNhMTk4YjNkYWRiYzY3YTZiYmRmYjdlMjNhYzZmNDdhOTdhNzI1Y2JhNGIxODBmZTQ3YWMzM2IyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3St0K45Hdlkcn7jfn01D5Qx5PeepUUZuB9jKNAl_5nU) ![image](https://private-user-images.githubusercontent.com/30064871/350305804-94966318-0f09-48e1-bdf0-daec6a7476be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzU0NjksIm5iZiI6MTcyMTM3NTE2OSwicGF0aCI6Ii8zMDA2NDg3MS8zNTAzMDU4MDQtOTQ5NjYzMTgtMGYwOS00OGUxLWJkZjAtZGFlYzZhNzQ3NmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTA4YTc1N2I1ZmE0MGE4ODllNGY1YmZkZGRjMjJiNjFjZDhmZjQwZDQ2Nzk4YTc0MmQ5NTMzNzM0NTM5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0z94qLI4umrdKDpV0Eh2FW2lhEvlq1cZclSxTUElGzM) i get the same result

please check the version of @rspack/core in your pnpm node_modules, seems to use the old version

**Comment by TryChai** [comment]
ok,i forget to install again

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/479391f1-3842-467d-8f7e-b6ab66ea9836)

i delete the node_module and yarn again, but it also wrong

**Comment by LingyuCoder** [comment]
the overrides is a pnpm feature, try to use pnpm install

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/100dcd23-ceec-4aeb-9f92-f6e18c8561c6)
![image](https://github.com/user-attachments/assets/a63b1e05-b711-408c-8d9d-13f74de60f48)
i has use the pnpm,but it also

**Comment by LingyuCoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/30064871/350335250-100dcd23-ceec-4aeb-9f92-f6e18c8561c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODAzNTEsIm5iZiI6MTcyMTM4MDA1MSwicGF0aCI6Ii8zMDA2NDg3MS8zNTAzMzUyNTAtMTAwZGNkMjMtY2VlYy00YWViLTlmOTItZjZlMThjODU2MWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA5MDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDYxMTE3ZWQ0OTMwNDcxMjYyOTc4ZmIyODc4OTcxZGU5YjFhNmNhOWEzMTJmZDlhZDk3NjRlNThiZWM3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5R58OOtn8BZSP4jdTflTYMczomO6N0PnbxtmI5upL3g) ![image](https://private-user-images.githubusercontent.com/30064871/350335367-a63b1e05-b711-408c-8d9d-13f74de60f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODAzNTEsIm5iZiI6MTcyMTM4MDA1MSwicGF0aCI6Ii8zMDA2NDg3MS8zNTAzMzUzNjctYTYzYjFlMDUtYjcxMS00MDhjLThkOWQtMTNmNzRkZTYwZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA5MDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NmI5MTA2NDE5MWU2YWE3MGZhZDhjNmFkZjE4YmIyZjIxNTc2ZTQ0OGJjMGUzNTk1OGM2MzY0ZDg5MTM1NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ng0p_u1Urxq34LB0pB47gQGtaMu9d1ggj_mYQOJNqLM) i has use the pnpm,but it also

see the version in `node_modules/.pnpm/@rspack-core-{some-path}/@rspack/core/package.json`

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/df963b90-73c6-4304-b5f8-89096000e146)
this?

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/df963b90-73c6-4304-b5f8-89096000e146)
this?

**Comment by LingyuCoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/30064871/350338696-df963b90-73c6-4304-b5f8-89096000e146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODEwMTQsIm5iZiI6MTcyMTM4MDcxNCwicGF0aCI6Ii8zMDA2NDg3MS8zNTAzMzg2OTYtZGY5NjNiOTAtNzNjNi00MzA0LWI1ZjgtODkwOTYwMDBlMTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA5MTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYjQyNTI4YjFiODUzZWRmZjk4MjRlNGQ5YTk0MzIwMzI2MzIzNzRkNzU5YmM3MzAyMDI1Njg5NDVlYjRmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jURxVRn2lsyxSPT_wWsKuarfy50R0KikwGlAKbdvXK4) this?

Yes, this is not the latest canary version, please try to upgrade to `1.0.0-canary-b3bac1b-20240719023634 `

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/2f0ebe65-0e9b-4ed2-8f07-cf2e7732d41c)

**Comment by TryChai** [comment]
![image](https://github.com/user-attachments/assets/8c8c96b5-479e-448b-9892-456fa9feb68f)

**Comment by SoonIter** [comment]
@TryChai 
could you try `npx install-rspack --version 1.0.0-canary-b3bac1b-20240719023634` ?

**Comment by TryChai** [comment]
> @TryChai could you try `npx install-rspack --version 1.0.0-canary-b3bac1b-20240719023634` ?

![image](https://github.com/user-attachments/assets/1d1d6ff3-8558-4b3b-936d-3dc050a12996)
i try,but found new progrem,how to change the code

**Comment by LingyuCoder** [comment]
This is a glob match, please check you source files and try to match it.
