### ISSUE TITLE
[Bug]: plugin compiles fine in webpack, but does not work in rspack

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rspack#7218]
### System Info

System:
OS: macOS 13.3.1
CPU: 2.5 GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
Browsers:
Chrome: 120.0.6099.109
npmPackages:
"@rsbuild/core": "^0.7.10",
"@rsbuild/plugin-vue2": "^0.7.10",

### Details

使用skin-utils的插件替换源码中的颜色变量进行换色
在webpack中
<img width="461" alt="image" src="https://github.com/user-attachments/assets/57036a1b-77ab-435c-9a7f-80e7dd703143">
点击
<img width="346" alt="image" src="https://github.com/user-attachments/assets/ae8c8598-17a0-4a34-9f06-15578bcce97a">
可以换色，在rspack里不可以

### Reproduce link

https://github.com/wengjiacheng/rspack-repro

### Reproduce Steps

npm run dev:rspack || dev:webpack
浏览器localhost:8080
点击按钮

**Comment by chenjiahan** [comment]
I can't find the code in the provided repo, can you check it?

![image](https://github.com/user-attachments/assets/b06c9811-d319-4843-b275-8f325e30db36)

**Comment by wengjiacheng** [comment]
![image](https://github.com/user-attachments/assets/18d128ff-acb9-48ba-8162-fc5ad21ee350)
![image](https://github.com/user-attachments/assets/edc0d3ed-28f8-43af-aa3a-a99df449eea4)

**Comment by wengjiacheng** [comment]
@chenjiahan 你好请问还需要提供哪些信息吗？

**Comment by wengjiacheng** [comment]
@chenjiahan 这个demo是之前打包报错做demo,当时只是解决了打包问题， 没有注意打包效果，是之后发现打包后不生效，所以就直接用了这个demo,所以现实提交是几个月前的

**Comment by wengjiacheng** [comment]
@chenjiahan 你好这个问题有进展吗？还需要提供哪些信息吗？

**Comment by chenjiahan** [comment]
我在这个 demo 里安装了最新版的 Rspack，没有复现你说的问题，建议你升级试一下

**Comment by wengjiacheng** [comment]
@chenjiahan 好的，我在项目里升级试一下

**Comment by xc2** [comment]
@wengjiacheng any further questions?
