### ISSUE TITLE
[Feature]: Add chunks raised for imports in third-party npm packages, which need to be captured in ouput.chunkFilename

### ISSUE THREAD

**Issue by dingjiang-gao** [web-infra-dev/rspack#7223]
### What problem does this feature solve?

背景：项目引入了monaco-editor，用于sql编辑器功能，rspack设置了output. asyncChunks: true
现象：构建产物会把对于语言包构建成chunk，但是我想自定义，所以定义了output.chunkFilename
问题：chunkFilename函数并没有捕捉到对于monaco-editor的import的部分
![image](https://github.com/user-attachments/assets/4f7ba0bf-b4ae-4ed4-a471-06f3ffd28fda)

### What does the proposed API of configuration look like?

out.chunkFilename

**Comment by dingjiang-gao** [comment]
更新：能捕捉到，但是并没有name，

**Comment by dingjiang-gao** [comment]
![image](https://github.com/user-attachments/assets/008eb923-1c4e-4f1f-bcff-06b8eb8608bd)

**Comment by CPunisher** [comment]
动态导入的 chunk 没有 name，这点和 webpack 一样
要加 name 可以用: https://webpack.js.org/api/module-methods/#webpackchunkname

**Comment by hardfist** [comment]
close as it's by design and same with webpack
