### ISSUE TITLE
[Bug]: Some `output.copy` glob patterns fail

### ISSUE THREAD

**Issue by matteom-synth** [web-infra-dev/rspack#7226]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 239.06 MB / 36.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @rsbuild/core: 1.0.1-beta.3 => 1.0.1-beta.3
    @rsbuild/plugin-react: 1.0.1-beta.3 => 1.0.1-beta.3
```

### Details

Hello hello!
I've been waiting for https://github.com/web-infra-dev/rspack/pull/6668 for some time hoping for it to solve this issue, but looks like it didn't.
When using `!` within a glob pattern in `output.copy`, the build fails to compile. 
I'm attaching a minimal repo (boostrapped by running `npm create rsbuild@latest`, adding a `public` dir with a couple of random files, and setting the `output.copy` glob to `{ from: "*.!(html)", context: "public", to: "." }`).  

### Reproduce link

https://github.com/matteom-synth/rsbuild-issue-repro-2

### Reproduce Steps

Clone the repo, run `pnpm install`, and then run `pnpm dev`, which will fail with:

```
» pnpm dev

> rsbuild-repro@1.0.0 dev /Users/matteo.mazzarolo/workspace/rsbuild-repro
> rsbuild dev

  Rsbuild v1.0.1-beta.3

  > Local:    http://localhost:3000/
  > Network:  http://192.168.1.86:3000/
  > Network:  http://192.168.1.165:3000/
  > Network:  http://10.100.64.35:3000/

start   Compiling...
error   Compile error:
Failed to compile, check the errors for troubleshooting.
× unable to locate '/Users/matteo.mazzarolo/workspace/rsbuild-repro/public/*.!(html)' glob

× unable to locate '/Users/matteo.mazzarolo/workspace/rsbuild-repro/public/*.!(html)' glob
```

**Comment by SyMind** [comment]
@matteom-synth The `output.copy` capability is powered by the `CopyRspackPlugin`, which uses Rust's `glob` crate for implementation. However, the `glob` crate does not support the pattern `*.!(html)`. Instead, you might try using `!*.html`.

**Comment by matteom-synth** [comment]
@SyMind how about negations capturing multiple elements `!(*.html|frame.js|frame.wasm)`?

**Comment by SyMind** [comment]
```
[
  '**/*',
  '!**/*.html',
  '!**/*.frame.js',
  '!**/*.frame.wasm'
]
```
