### ISSUE TITLE
[Bug Report]: css-loader errors occurred while using tailwindcss.

### ISSUE THREAD

**Issue by kurorinto** [web-infra-dev/rspack#7242]
### System Info

System:
- OS: macOS Sonoma 14.5
- CPU: Apple M1

Binaries:
- Node: 21.7.3
- npm: 10.5.0

Browsers:
- Chrome: 126.0.6478.183

- npmPackages:
- @rspack/cli: 1.0.0-alpha.3
- @rspack/core: 1.0.0-alpha.3

### Details

When using tailwindcss, writing the following code anywhere in the compiled code file (including comments) will cause a compilation error:
```javascript
import './render.css'

export function render() {
    // Reproduce the bug

    // 1:
    // bg-[url(something)]

    // 2:
    const unusedVar = `bg-[url(something)]`

    // 3:
    const unusedFunc = (something) => `bg-[url(${something})]`

    const el = document.createElement('div')
    el.classList.add('text')
    document.getElementsByTagName('body')[0].appendChild(el)
    el.innerHTML = 'hello, world'
}
```
The error message
```bash
start   Compiling...
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
File: /Users/_/Desktop/github/rspack-repro-MRE/src/render.css:1:1
  × Module build failed:
  ╰─▶   × Error: HookWebpackError: Cannot find module '${something}'
        │     at tryRunOrWebpackError (/Users/_/Desktop/github/rspack-repro-MRE/node_modules/@rspack/core/dist/lib/HookWebpackError.js:80:15)
        │     at __webpack_require__ (/Users/_/Desktop/github/rspack-repro-MRE/node_modules/@rspack/core/dist/Compiler.js:640:61)
        │     at /Users/_/Desktop/github/rspack-repro-MRE/node_modules/@rspack/core/dist/Compiler.js:652:35
        │     at last.function (/Users/_/Desktop/github/rspack-repro-MRE/node_modules/@rspack/core/dist/Compiler.js:810:28)
        │

File: /Users/_/Desktop/github/rspack-repro-MRE/src/render.css:1:1
  × Module not found: Can't resolve '${something}' in '/Users/_/Desktop/github/rspack-repro-MRE/src'
   ╭─[3:1]
 3 │ import ___CSS_LOADER_API_IMPORT___ from "../node_modules/@rsbuild/core/compiled/css-loader/api.js";
 4 │ import ___CSS_LOADER_GET_URL_IMPORT___ from "../node_modules/@rsbuild/core/compiled/css-loader/getUrl.js";
 5 │ var ___CSS_LOADER_URL_IMPORT_0___ = new URL("${something}", import.meta.url);
   ·                                     ────────────────────────────────────────
 6 │ var ___CSS_LOADER_URL_IMPORT_1___ = new URL("something", import.meta.url);
 7 │ var ___CSS_LOADER_EXPORT___ = ___CSS_LOADER_API_IMPORT___(___CSS_LOADER_API_NO_SOURCEMAP_IMPORT___);
   ╰────

File: /Users/_/Desktop/github/rspack-repro-MRE/src/render.css:1:1
  × Module not found: Can't resolve 'something' in '/Users/_/Desktop/github/rspack-repro-MRE/src'
   ╭─[4:1]
 4 │ import ___CSS_LOADER_GET_URL_IMPORT___ from "../node_modules/@rsbuild/core/compiled/css-loader/getUrl.js";
 5 │ var ___CSS_LOADER_URL_IMPORT_0___ = new URL("${something}", import.meta.url);
 6 │ var ___CSS_LOADER_URL_IMPORT_1___ = new URL("something", import.meta.url);
   ·                                     ─────────────────────────────────────
 7 │ var ___CSS_LOADER_EXPORT___ = ___CSS_LOADER_API_IMPORT___(___CSS_LOADER_API_NO_SOURCEMAP_IMPORT___);
 8 │ var ___CSS_LOADER_URL_REPLACEMENT_0___ = ___CSS_LOADER_GET_URL_IMPORT___(___CSS_LOADER_URL_IMPORT_0___);
```

### Reproduce link

https://github.com/kurorinto/rspack-repro

### Reproduce Steps

1. Run `npm create rsbuild@latest` and `npm install`.
2. Add tailwindcss and configure it in rsbuild.config.ts, then use it.
```npm i -D tailwindcss```
```npx tailwindcss init```
```javascript
// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}

// rsbuild.config.ts
import { defineConfig } from "@rsbuild/core";

export default defineConfig({
  tools: {
    postcss: {
      postcssOptions: {
        plugins: [require("tailwindcss")],
      }
    }
  }
});
```
```css
/* App.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```
3. Write these in js/jsx/ts/tsx file.
```
import './App.css';

const App = () => {
  // bg-[url(something)]
  const unusedVar = `bg-[url(something)]`
  const unusedFunc = (something) => `bg-[url(${something})]`

  return (
    <div className="content">
      <h1>Rsbuild with React</h1>
      <p>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;
```
4. Try to compile: `npm run dev` or `npm run build`

**Comment by xc2** [comment]
## Is it as expected?

Yes

## Why

The TailwindCSS does text match regardless of language syntax to find classes and produce css.

So when tw see text `bg[url(someting)]`, it produces `.bg-\[url\(something\)\] { background-image: url(something); }`.

When tw see see text `bg-[url(${something})]`, it produces `.bg-\[url\(\$\{something\}\)\] { background-image: url(${something}); }`

Then the rspack see `url(xyz)` in the css "module", it starting to resolve the module `xyz`.

## Way out?

To stop rspack/rsbuild resolving the module `xyz`, set `output.externals = [/xyz/]` to `rsbuild.config.ts`

### Will things work now?

After stopping the resolving, `.bg-\[url\(something\)\] { background-image: url(something); }` will work but .bg-\[url\(\$\{something\}\)\] { background-image: url(${something}); }` won't as the latter is of invalid css syntax.

You should never write dynamic class names in tw: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by kurorinto** [comment]
But in the webpack project and vite project there is no such error. Is it because css "module" and tree-shaking are not in the same order in rspack.

**Comment by kurorinto** [comment]
> ## Is it as expected?
> Yes
> 
> ## Why
> The TailwindCSS does text match regardless of language syntax to find classes and produce css.
> 
> So when tw see text `bg[url(someting)]`, it produces `.bg-\[url\(something\)\] { background-image: url(something); }`.
> 
> When tw see see text `bg-[url(${something})]`, it produces `.bg-\[url\(\$\{something\}\)\] { background-image: url(${something}); }`
> 
> Then the rspack see `url(xyz)` in the css "module", it starting to resolve the module `xyz`.
> 
> ## Way out?
> To stop rspack/rsbuild resolving the module `xyz`, set `output.externals = [/xyz/]` to `rsbuild.config.ts`
> 
> ### Will things work now?
> After stopping the resolving, `.bg-\[url\(something\)\] { background-image: url(something); }` will work but .bg-[url(${something})] { background-image: url(${something}); }` won't as the latter is of invalid css syntax.
> 
> You should never write dynamic class names in tw: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

But in the webpack project and vite project there is no such error. Is it because css "module" and tree-shaking are not in the same order in rspack.

**Comment by Morning-Shine** [comment]
Hi! I created file rsbuild.config.ts in project root with:
`module.exports = {
    output: {
      externals: [/${posterUrl}/],
    },
  };`
  but it doesn't work for me. I made somthing wrong?

**Comment by Jervx** [comment]
Me too, I am using tw v4, added the url in style={{ }} instead of using tailwind arbitrary bg-[url()]. And still having the error

<img width="680" height="154" alt="Image" src="https://github.com/user-attachments/assets/7f000131-0a18-4a2d-9459-478cd23753b7" />

```
File: /home/x/Documents/x1/project/src/index.css:1:1
  × Module not found: Can't resolve '/auth-bg.webp' in '/home/x/Documents/x1/project/src'
   ╭─[5:36]
 3 │ import ___CSS_LOADER_API_IMPORT___ from "../node_modules/@rsbuild/core/compiled/css-loader/api.js";
 4 │ import ___CSS_LOADER_GET_URL_IMPORT___ from "../node_modules/@rsbuild/core/compiled/css-loader/getUrl.js";
 5 │ var ___CSS_LOADER_URL_IMPORT_0___ = new URL("/auth-bg.webp", import.meta.url);
   ·                                     ─────────────────────────────────────────
 6 │ var ___CSS_LOADER_URL_IMPORT_1___ = new URL("./assets/fonts/Inter/Inter-VariableFont.ttf", import.meta.url);
 7 │ var ___CSS_LOADER_EXPORT___ = ___CSS_LOADER_API_IMPORT___(___CSS_LOADER_API_NO_SOURCEMAP_IMPORT___);
   ╰────
```
