### ISSUE TITLE
[Bug]: Random error with CopyRspackPlugin

### ISSUE THREAD

**Issue by cjnoname** [web-infra-dev/rspack#7278]
### System Info

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.91 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5

### Details

Hi,

I randomly encountered this error, which occurs 50% of the time. I'm not sure why.

/home/circleci/project/node_modules/@rspack/core/dist/util/fs.js:83
        throw new Error(`${absPath} is neither a posix nor a windows path, and there is no 'dirname' method defined in the file system`);
        ^

Error: dist/emailTemplates is neither a posix nor a windows path, and there is no 'dirname' method defined in the file system
    at dirname (/home/circleci/project/node_modules/@rspack/core/dist/util/fs.js:83:15)
    at /home/circleci/project/node_modules/@rspack/core/dist/util/fs.js:90:29
    at FSReqCallback.oncomplete (node:fs:187:23)

Thanks

### Reproduce Steps

The config I use:

            new rspack.CopyRspackPlugin({
              patterns: [
                {
                  from: "./emailTemplates",
                  to: "emailTemplates"
                }
              ]
            })

Expected the "emailTemplates" to be copied to dist/emailTemplates.

Thanks

**Comment by karlis-vagalis** [comment]
Have encountered the same issue, it relates to the fact, that the destination (ie, "to") folder does not exist yet.

A solution is to make sure, that the destination folder "emailTemplates" exists in the "dist" before building.

**Comment by cjnoname** [comment]
> Have encountered the same issue, it relates to the fact, that the destination (ie, "to") folder does not exist yet.
> 
> A solution is to make sure, that the destination folder "emailTemplates" exists in the "dist" before building.

I have fixed it by adding import.meta.dirname. I think it just doesn't support relative paths.
