### ISSUE TITLE
support compile  import.meta.url

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#729]
webpack will transpile import.metal to object, see https://github.com/webpack/webpack/blob/main/test/cases/esm/import-meta/index.js

**Comment by marco2216** [comment]
I think maybe this error is caused by support for import.meta lacking?
From the jotai package.
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/4561482/224376847-fd51392c-2363-49b5-9971-1a69897c0b8e.png">

**Comment by h-a-n-a** [comment]
> I think maybe this error is caused by support for import.meta lacking? From the jotai package. <img alt="image" width="1342" src="https://user-images.githubusercontent.com/4561482/224376847-fd51392c-2363-49b5-9971-1a69897c0b8e.png">

I guess it is. You may switch to the CommonJS version and I think that will be the fix currently.

**Comment by marco2216** [comment]
Currently I worked around it by adding       `'import.meta.env': undefined` to the define object in the builtin config.

**Comment by AndreinNguyen** [comment]
> 

Can you explain more details?
Currently, I have same problem...

**Comment by AndreinNguyen** [comment]
> Currently I worked around it by adding `'import.meta.env': undefined` to the define object in the builtin config.

Can you explain more details?
Currently, I have same problem...

**Comment by marco2216** [comment]
Sure, jotai has checks for import.meta.env being undefined, so I just set it to undefined.
To [builtins.define](https://www.rspack.dev/config/builtins.html#builtinsdefine) add:
```
define: {
      'import.meta.env': undefined,
}
```
You could also use some other value than undefined, e.g. `process.env.NODE_ENV` or something.
