### ISSUE TITLE
[Bug]: rspack.CopyRspackPlugin modifies file content

### ISSUE THREAD

**Issue by SaniMusic** [web-infra-dev/rspack#7298]
### System Info
Mac OS
   "@rspack/cli": "0.7.5",
  "@rspack/core": "0.7.5",

### Details

Using rspack.CopyRspackPlugin javascript files content gets modified, 

should this ever be the case?

Can an option be added to the API to avoid modifying content?

The file in question is a compiled javascript file, 

Out of all files (~50) only one fails in this way..

File starts like this: 
`
(self,(()=>(()=>{var __webpack_modules__={831:function(__unused_webpack_module,exports,__webpack_require__){var t;t=function(exports){"use strict";function appendForwardSlash(e){return 0!==e.length&&"/"===e[e.length-1]||(e=`${e}/`),e}function defined(e){return null!=e}
`

Modified file `
(self,()=>(()=>{var __webpack_modules__={831:function(__unused_webpack_module,exports,__webpack_require__){t=function(exports){"use strict";let a$2,supportsImageBitmapOptionsPromise,a$1,baseResource,implementation$2,_supportsFullscreen,theNavigator,isChromeResult,chromeVersionResult,isSafariResult,safariVersionResult,isWebkitResult,webkitVersionResult,isInternetExplorerResult,internetExplorerVersionResult,isEdgeResult,edgeVersionResult,isFirefoxResult,firefoxVersionResult,isWindowsResult,isIPadOrIOSResult,hasPointerEvents,imageRenderingValueResult,supportsImageRenderingPixelatedResult,bootstrapperUrlResult,unitBoxGeometry,implementation$1,getTimestamp,scratchArrayBuffer,scratchUint32Array,scratchUint8Array,defaultTokenCredit,unitCylinderGeometry,unitEllipsoidGeometry,dbrootParser,dbrootParserPromise,defaultKeyCredit,supportedTranscoderFormats,imageSmoothingEnabledName,implementation,randomNumberGenerator$1,randomValues$1,attributeLocations$6,getIndexBuffer$2,scratchPositionsArray,scratchVariable,randomNumberGenerator,randomValues,currentId,parser$1,scratchDiv$1,parser,scratchDiv,renderStateScratch,scratchBackBufferArray,emptyImage,viewRectangle3DEllipsoidGeodesic,attributeLocations$1,getIndexBuffer,defaultCredit$2,getDebugOrientedBoundingBox,getDebugBoundingSphere,debugDestroyPrimitive,comparisonPoint,scratchOccluder,widgetForDrag,staticTextCommitQueueTimeout;function appendForwardSlash(e){return 0!==e.length&&"/"===e[e.length-1]||(e=`${e}/`),e}function defined(e)
`

### Reproduce Steps
rspack.CopyRspackPlugin with or without a loader involved..
`
new rspack.CopyRspackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, './file'),
            to: path.resolve(__dirname, './file')
          },
        ]
      }),
`

**Comment by LingyuCoder** [comment]
You can try to add `info: { minimized: true }` to the pattern, this can tell the minimizer that the asset had been minimized, just the same as [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin#info).

```js
new rspack.CopyRspackPlugin({
  patterns: [{
    from: path.resolve(__dirname, './file'),
    to: path.resolve(__dirname, './file'),
    info: { minimized: true },
  }]
}),
```

**Comment by SaniMusic** [comment]
Thx, this is Awesome!! 

It works and since the minimization is skipped it's even faster!!
