### ISSUE TITLE
[Bug]:CopyRspackPlugin 插件报错 

### ISSUE THREAD

**Issue by bosens-China** [web-infra-dev/rspack#7312]
### System Info

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 76.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5

### Details

 [{ from: './public', noErrorOnMissing: true }],

我的文件结构
![image](https://github.com/user-attachments/assets/b17b9a14-041c-41fa-966d-f5bce4b900cd)

报错信息
``` sh
error   Failed to build.
error   Rspack build failed!
    at file:///Users/yliu/Desktop/job/jcnl-admin/node_modules/@rsbuild/core/dist/index.js:4835:39
    at finalCallback (/Users/yliu/Desktop/job/jcnl-admin/node_modules/@rspack/core/dist/Compiler.js:302:21)
    at /Users/yliu/Desktop/job/jcnl-admin/node_modules/@rspack/core/dist/Compiler.js:326:40
    at done (/Users/yliu/Desktop/job/jcnl-admin/node_modules/@rspack/lite-tapable/dist/index.js:478:13)
    at promise.then.index (/Users/yliu/Desktop/job/jcnl-admin/node_modules/@rspack/lite-tapable/dist/index.js:500:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduce Steps

none

**Comment by bosens-China** [comment]
猜测是index.html冲突导致的，所以希望可以有一个忽略项

**Comment by bosens-China** [comment]
> Emit file conflicts may cause error. If you do not need to copy `index.html`, you can try the `globOptions.ignore` configuration. https://www.rspack.dev/plugins/rspack/copy-rspack-plugin#copyrspackplugin

配置了同样报相同的错误。

**Comment by cjnoname** [comment]
This plugin is somewhat immature and buggy, so it would be better to review it as a whole.

**Comment by bosens-China** [comment]
> This plugin is somewhat immature and buggy, so it would be better to review it as a whole.

是的，我还发现现在插件跟webpack的插件有的没办法兼容，比如webpack-zip这个插件。

**Comment by 9aoy** [comment]
Need to provide a reproduction demo.

**Comment by cjnoname** [comment]
> Need to provide a reproduction demo.

Believe it or not, this issue occurs randomly and cannot be reproduced on demand. I have encountered it both on my MacBook (arm64) and on our CI/CD tool (CircleCI) running on ARM. This is something I have never experienced before.
