### ISSUE TITLE
[Bug]: Rspack errors seem to not support the correct location

### ISSUE THREAD

**Issue by shulaoda** [web-infra-dev/rspack#7327]
### Details
Related to #6051

<img width="794" alt="image" src="https://github.com/user-attachments/assets/62676402-820a-4c88-8c62-631739273694">

### Reproduce Steps

1. Config rspack.config.js
2. Import non-existent module

**Comment by h-a-n-a** [comment]
This is a limitation from miette. See snapshots from the old oxc lint: https://github.com/oxc-project/oxc/blob/6e5aad26393c363e64cd3040547f3184538fa9b7/crates/oxc_linter/src/snapshots/adjacent_overload_signatures.snap. We can take later fix as an reference to fix this issue: https://github.com/oxc-project/oxc/pull/2241
