### ISSUE TITLE
[Bug]: memory iterator issue

### ISSUE THREAD

**Issue by ii64** [web-infra-dev/rspack#7393]
### System Info

```
  System:
    OS: Linux 6.8 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 17.69 GB / 62.22 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.5.2 - /usr/bin/npm
    pnpm: 9.3.0 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 123.1.64.116
    Chrome: 126.0.6478.114
  npmPackages:
    @rspack/cli: workspace:* => 1.0.0-beta.1 

```

### Details

rspack/rsbuild crashed with iterator/memory issue, empty backtrace

![image](https://github.com/user-attachments/assets/653f36ed-0f94-48f6-9691-9233db82d583)
![image](https://github.com/user-attachments/assets/e77b7a0e-9abf-4ff6-a8ee-3f43ea2a62de)

### Reproduce link

https://github.com/ii64/rspack-repro-import-meta-url

### Reproduce Steps

1. Run `pnpm build:webpack`, it'll show you errors, and generated files persisted
Run `pnpm build:rsbuild` or `pnpm build:rspack`, got run-time abort/segfault/napi stuff/iterator capacity overflow

**Comment by LingyuCoder** [comment]
After replacing the `ts-loader` to `builtin:swc-loader`, do not meet the same issue. Just build like webpack and report lots of errors:

![image](https://github.com/user-attachments/assets/bdc74cb3-a735-4105-9d33-9f428f18f1fc)

**Comment by h-a-n-a** [comment]
Cannot reproduce this issue on arch. The only error it shows is related to ts-loader.
<img width="958" alt="image" src="https://github.com/user-attachments/assets/1bc4ce57-2786-4ae6-ad8d-006a0b11a927">

**Comment by ii64** [comment]
I have updated the repro config, got rsbuild panic on `crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs:95`
![image](https://github.com/user-attachments/assets/ca64cc9f-c821-4ebf-a8e4-1656af1538bc)

**Comment by h-a-n-a** [comment]
> I have updated the repro config, got rsbuild panic on `crates/rspack_plugin_javascript/src/parser_plugin/import_meta_plugin.rs:95` ![image](https://private-user-images.githubusercontent.com/26342994/355549352-ca64cc9f-c821-4ebf-a8e4-1656af1538bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTc3ODgsIm5iZiI6MTcyNDY1NzQ4OCwicGF0aCI6Ii8yNjM0Mjk5NC8zNTU1NDkzNTItY2E2NGNjOWYtYzgyMS00ZWJmLWE4ZTQtMTY1NmFmMTUzOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3MzEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTI5NjAzNjhiMGMwODcwMDk1ODRmNDFhOThkODk4YjMzNGRjMDA1YjM3ODlkODBmZjg3MzY5NjY0MGRkODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gh6B7ofS4Ka_cxW_IoV5ZB92vK248QORmPxvMIANcbw)

Sorry for the late reply. The `context` you provided is not an absolute path, this breaks the invariant of bundler internals. We are going to improve that.
