### ISSUE TITLE
[Bug]: Panic Module should be added before using (Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:74)

### ISSUE THREAD

**Issue by hverlin** [web-infra-dev/rspack#7419]
### System Info

`@rsbuild/core: 1.0.1-beta.9` (but happens on earlier version as well)

### Details

When I start `rsbuild`, it needs to run the `compiling...` step twice (I am not sure exactly why)

I have noticed that rspack will crash if I try to access the page before the second `compiling...` step is done. If I wait, the page will load fine.

```
start   Compiling...
● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit                                                                                                                ready   Compiled in 13.2 s (web)
start   Compiling...
● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing dependencies                                                                                                                Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Module(builtin:react-refresh-loader!builtin:swc-loader??ruleSet[1].rules[3].use[0]!/<..>./some-file.js) should be added before using
Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:74

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
    at <unknown source file>
 2: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
    at <unknown source file>
 3: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
    at <unknown source file>
 4: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
    at <unknown source file>
 5: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
    at <unknown source file>
Aborted (core dumped)
```

Given what's mentioned in the error message, I am filing this bug report.

### Reproduce Steps

I have seen it failing with two different files.

One file has some code that does this:
```js
async function getModule(code) {
  function encode(code) {
    return Buffer.from(code).toString('base64');
  }

  const importStatement = `data:text/javascript;base64,${encode(code)}`;
  return import(importStatement);
}
```

If I remove the `import(importStatement)` line, I get the same error but this time because of
```
mocha@10.7.0/node_modules/mocha/lib/mocha.js
```

which is imported like this (using `require` or `import` causes the same error)
```js
const mocha = require('mocha');
```

**Comment by JSerFeng** [comment]
Are you using lazyCompilation ?

**Comment by hverlin** [comment]
`lazyCompilation` is not enabled. As I understand, it's [disabled](https://rsbuild.dev/config/dev/lazy-compilation#devlazycompilation) by default.

This is my `dev` config
```ts
  dev: {
    progressBar: true,
    client: { host: '127.0.0.1', protocol: 'ws' },
    writeToDisk: true,
  },
  ```

**Comment by JSerFeng** [comment]
Might be caused by accessing stats before chunk graph is built, can you try disable some of the javascript plugins ?

**Comment by JSerFeng** [comment]
bump

**Comment by hverlin** [comment]
Thanks, I am still facing the issue even after upgrading to the latest rspack version.

 I am using the following plugins:
`pluginNodePolyfill`, `pluginReact`, `pluginLess`, `rspack.ProvidePlugin` and `rspack.IgnorePlugin`.
I have tried to disable them, but I can still reproduce this issue

**Comment by hverlin** [comment]
@JSerFeng Is there a way to let rspack know that they should ignore a given `import`?

```ts
async function getModule(code) {
  function encode(code) {
    return Buffer.from(code).toString('base64');
  }

  const importStatement = `data:text/javascript;base64,${encode(code)}`;
  return import(importStatement);
}
```
For example, here I would like rspack to keep this code as is, and not try to understand what it's trying to import.

A workaroud would be this: 
```
  const importStatement = `data:text/javascript;base64,${btoa(code)}`;
  const res = await eval(`import('${importStatement}')`);
```

checking the documentation here https://rspack.dev/api/runtime-api/module-methods#dynamic-expressions-in-import I see that it's not supported. It would be nice if `rspack` would just ignore any dynamic imports which starts with `data:text/javascript;...` since they cannot refer to files on the filesystem

**Comment by hverlin** [comment]
Is it possible to keep it open, or should I create a new issue?

**Comment by hverlin** [comment]
Adding a few more details here. I did not manage to reproduce it yet.

If I try to use mocha standalone, it works. I only get a few warnings like 
```
/test/node_modules/.pnpm/mocha@10.7.3/node_modules/mocha/lib/mocha.js:1:1
  ⚠ Module parse warning:
  ╰─▶   ⚠ Critical dependency: the request of a dependency is an expression
           ╭─[339:27]
       337 │       try {
       338 │         foundReporter = require.resolve(reporterName);
       339 │         reporter = require(foundReporter);
           ·                            ──────────────
       340 │       } catch (err) {
       341 │         if (foundReporter) {
           ╰────
```
However, it does not show the "compiling" message twice every time.

---

Here is how it's used to give you an idea.
---
rsbuild configuration
```ts
import { defineConfig } from "@rsbuild/core";
import { pluginNodePolyfill } from "@rsbuild/plugin-node-polyfill";

export default defineConfig({
  plugins: [pluginNodePolyfill()],
});
```

```ts
const mocha = require("mocha");
require("mocha/mocha.css");

document.body.innerHTML = '<div id="mocha"></div>';

const testContext = require.context("./tests", true, /.*-test(\.js)$/);

mocha.setup("bdd");
mocha.run();

testContext.keys()
  .forEach((testFile: string) => testContext(testFile)());
```

In a directory `tests`, I have files like these:
```js
const { assert } = require("chai");
module.exports = () => {
    describe("Test", () => {
        it("should return true", () => {
            assert.ok(true);
        });
    });
};
```

**Comment by JSerFeng** [comment]
Can you try using this config, see if it is something incorrect in incremental build

```rspack.config.js
module.exports = {
  cache: false
}
```

**Comment by JSerFeng** [comment]
And please give this version a try 1.0.1-canary-d6c74be-20240902095124

**Comment by hverlin** [comment]
Thanks for your answers. The bug is still happening with the latest version (rsbuild 1.0.1). 

It seems to be an incremental build issue indeed. After disabling the cache with `rsbuildConfig.tools.rspack.cache = false` as you suggested, the bug does not happen anymore (however, it's much slower as we get two full builds)
```
start   Compiling...
● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit                                                                                                     
ready   Compiled in 11.7 s (web)
start   Compiling...
● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit                                                                                                      
ready   Compiled in 12.6 s (web)
```

I am moving the tests pages to a separate [environment](https://rsbuild.dev/guide/advanced/environments) as a workaround for now.

I think, ideally, there should be a way to tell rspack to ignore some `import` or have rspack keep `import` or `require` which have a complex expression passed to them

**Comment by JSerFeng** [comment]
> I think, ideally, there should be a way to tell rspack to ignore some import or have rspack keep import or require which have a complex expression passed to them

You can use `__non_webpack_require__`, it will be preserved as `require` in the output

**Comment by hardfist** [comment]
does this bug still exists in latest rspack version @hverlin ?

**Comment by hverlin** [comment]
I can still reproduce it with the latest version (`rsbuild 1.0.7`). Here is the error message I get if I reload before the second compilation completes:

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Module(javascript/dynamic|/<...>/node_modules/.pnpm/mocha@9.2.2/node_modules/mocha/lib/mocha.js) should be added before using
Location: crates/rspack_core/src/chunk_graph/chunk_graph_module.rs:71

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
    at <unknown source file>
 2: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
    at <unknown source file>
 3: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
    at <unknown source file>
 4: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
    at <unknown source file>
 5: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
    at <unknown source file>
Aborted (core dumped)
```

Is there a way for rspack/rsbuild to indicate why it would need to re-compile?
```
start   Compiling...
● tests ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit     ready   Compiled in 10.3 s (tests)
start   Compiling...
● tests ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit     ready   Compiled in 0.59 s (tests)
```
