### ISSUE TITLE
[Bug]: JsStatsModule type is incorrect

### ISSUE THREAD

**Issue by ska-kialo** [web-infra-dev/rspack#7449]
### System Info

```
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 1.84 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
  Yarn: 4.3.1 - ~/.nvm/versions/node/v21.5.0/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
Browsers:
  Chrome: 126.0.6478.57
  Edge: 113.0.1774.35
  Safari: 17.5
npmPackages:
  @rspack/cli: ^1.0.0-beta.2 => 1.0.0-beta.2
  @rspack/core: ^1.0.0-beta.2 => 1.0.0-beta.2
  @rspack/plugin-react-refresh: ^1.0.0-beta.2 => 1.0.0-beta.2
  ```

### Details

Since `1.0.0-beta.2` the TypeScript type of `JsStatsModule` defines a lot of its attributes under a property `commonAttributes: JsStatsModuleCommonAttributes`. This is incorrect as this property does not exist and the properties defined in `JsStatsModuleCommonAttributes` are (from what I can see) still present on the `JsStatsModule` object during runtime.

### Reproduce Steps

Use the `StatsWriterPlugin` and in the `transform` callback, try to access e.g. `name` on `stats.chunks[0].modules[0]`.

**Comment by SyMind** [comment]
@ska-kialo `JsStatsModule` is an internal data structure. It gets converted to `StatsModule`, similar to how webpack handles it in `DefaultStatsFactoryPlugin`.

I tried using the `StatsWriterPlugin`, and in the `transform` callback, everything worked as expected.

Could you please provide a reproducible demo so we can better understand the issue?

**Comment by ska-kialo** [comment]
Ah okay, that would make sense as to how it works during runtime. Just to clarify, it's just the TypeScript types that seem incorrect. During runtime the elements of `StatsChunk.modules` seem to follow the `StatsModule` type.

Then I would assume the issue the issue is that the `modules` property on `KnownStatsChunk` (which is defined on [JsStatsChunk](https://github.com/web-infra-dev/rspack/blob/e33ba68005c0968d608df97360fedca163cc16b6/crates/node_binding/binding.d.ts#L676)) is an array of `JsStatsModule` and not `StatsModule`.

I can look into creating an example later.

**Comment by SyMind** [comment]
@ska-kialo Ho no, the ts type is wrong. I will fix it.
