### ISSUE TITLE
[Feature]: support contextReplacementPlugin

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7474]
### What problem does this feature solve?

docusaurus  use https://webpack.js.org/plugins/context-replacement-plugin/#root  to optimize primjs bundling

### What does the proposed API of configuration look like?

same as webpack

**Comment by shulaoda** [comment]
This part of the content is currently difficult to proceed with, as there are many missing features in `ContextModulaFactory` and it seems that there are also some implementation issues.

**Comment by hardfist** [comment]
currently blocks https://github.com/getsentry/sentry/pull/77077 and docusaurs integration, consider prioritize it

**Comment by hardfist** [comment]
@shulaoda  this is high prioritize issue, so @SyMind will continue work on it

**Comment by shulaoda** [comment]
> @shulaoda this is high prioritize issue, so @SyMind will continue work on it

👍
