### ISSUE TITLE
is it possible to replace the optional chain in hmr/hotModuleReplacement.ts with a writeup that is compatible with lower versions?

### ISSUE THREAD

**Issue by wChenonly** [web-infra-dev/rspack#7495]
### System Info

/

### Details

https://github.com/web-infra-dev/rspack/blob/main/packages/rspack/src/builtin-plugin/css-extract/hmr/hotModuleReplacement.ts#L59

In hotModuleReplacement, this will cause an error to be reported if you are developing with a browser that does not support the Optional Chaining syntax.

Because some of the container versions for hybrid development are still relatively low

The current solution is to configure include in souce: [/[/\\]node_modules[/\\]@rspack\/core[/\\]/]

### Reproduce Steps

/

**Comment by JSerFeng** [comment]
Yes, I can do it when I got time, and It would be very great if you are willing to contribute

**Comment by wChenonly** [comment]
> Yes, I can do it when I got time, and It would be very great if you are willing to contribute

Then I'll do it.
