### ISSUE TITLE
[Bug]: Slow hot reload

### ISSUE THREAD

**Issue by escaton** [web-infra-dev/rspack#7503]
### System Info

```
  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 4.18 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.90
    Safari: 17.5
  npmPackages:
    @rspack/cli: 1.0.0-alpha.0 => 1.0.0-alpha.0
    @rspack/core: 1.0.0-alpha.0 => 1.0.0-alpha.0
    @rspack/plugin-react-refresh: 1.0.0-alpha.0 => 1.0.0-alpha.0
```

### Details

I have an app with 45193 modules and when I'm changing any leaf sometimes the delta between `compiler.hooks.done` and the successful `ok` send from websocket server is 2s.
The CPU profile shows that right after the `done` hook the process is busy and around 1s is spent in the `Watchpack::watch()`.
The same happens with webpack, but this is unnoticeable compared to the overall webpack's slowness.
In case of Rspack, that one second is more than the rebuild itself, so would be nice to investigate it :)

Here is the cpuprofile: 
[CPU-20240807T155610.cpuprofile](https://github.com/user-attachments/files/16542339/CPU-20240807T155610.cpuprofile)

Most of the time is spent here: https://github.com/webpack/watchpack/blob/main/lib/watchpack.js#L35

And here is my watch config:
```
watchOptions: {
	ignored: [
		'**/node_modules/**',
		'**/.storybook/**',
		'**/.storybook-canvas/**',
		'**/application/target/**',
		'**/application/native/**',
		'**/application/typings/**',
		'**/bamboo-specs/**',
		'**/cli/**',
		'**/docs/**',
		'**/e2e-tests/**',
		'**/platform/**',
		'**/scripts/**',
		'**/stat-config-generator/**',
	],
	aggregateTimeout: 50,
},
```

I wonder if it is necessary to re-initialize the watcher on any change even if there are no new modules in the build?

### Reproduce Steps

-

**Comment by hardfist** [comment]
thank you for your detailed report similar issue with https://github.com/web-infra-dev/rspack/issues/7490,  it seems a performance bug of watchpack, can you help provide the input of the slow Function(the `x` and `regex` value) and help us find whether it's slow in `x.replace(/\\/g, "/")` or `regexp.test`

**Comment by escaton** [comment]
The `regex` is [compiled](https://github.com/webpack/watchpack/blob/main/lib/watchpack.js#L34) **once** from the `watchOptions.ignored` that I provided, and `x` is each of the watched files (45k in my case).

The problem is not the performance of `x => regex.test(x)`, but the fact that it is called _at least_ 45k times (see `filter()` calls in [`watch`](https://github.com/webpack/watchpack/blob/main/lib/watchpack.js#L166) method).

**Comment by hardfist** [comment]
thanks that's really helpful, and we will consider reuse watch across different compilation

**Comment by hardfist** [comment]
> Maybe I can help with it? I thought about some early bailout in `packages/rspack/src/Watching.ts`

https://github.com/web-infra-dev/rspack/issues/7503#issuecomment-2275876966 you can try whether this works for you?

**Comment by escaton** [comment]
Oh, this issue is actually a duplicate of https://github.com/web-infra-dev/rspack/issues/7490. That one was posted by my colleague :) Let's proceed in that issue.
