### ISSUE TITLE
[Bug]: ReferenceError: cacheGroup is not defined

### ISSUE THREAD

**Issue by hyper-dot** [web-infra-dev/rspack#7505]
### System Info
- **Operating System:** macOS (M1)
- **Browser:** Google Chrome
- **Page URL:** https://rspack.dev/guide/optimization/code-splitting

### Details

**Description:**  
While reviewing the Rspack documentation for code splitting, I encountered a `ReferenceError: cacheGroup is not defined` in the English version of the documentation.

**Steps to Reproduce:**  
1. Open the Rspack documentation at the following URL: https://rspack.dev/guide/optimization/code-splitting
2. Review the English version of the documentation.
3. Observe the error: `ReferenceError: cacheGroup is not defined`.

**Expected Behavior:**  
The documentation should correctly define or describe `cacheGroup` without any reference errors.

**Actual Behavior:**  
A `ReferenceError: cacheGroup is not defined` is encountered, which indicates that there may be an undefined or incorrectly referenced variable in the documentation.

**Additional Information:**  
- This issue was encountered on a Mac with an M1 chip.
- The error appears to be specific to the English version of the documentation.

### Reproduce link

http://localhost:3000/guide/optimization/code-splitting

### Reproduce Steps

Just visit the given link and see on the console.

**Comment by hardfist** [comment]
thanks for detailed report, will fix it ASAP in #7506
