### ISSUE TITLE
[Bug]: Imported modules disappear in built files

### ISSUE THREAD

**Issue by MaxtuneLee** [web-infra-dev/rspack#7508]
### System Info

  System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.99
    Edge: 127.0.2651.86
    Safari: 17.1
  npmPackages:
    @rspack/cli: 1.0.0-beta.3 => 1.0.0-beta.3 
    @rspack/core: 1.0.0-beta.3 => 1.0.0-beta.3 
    @rspack/plugin-react-refresh: 1.0.0-beta.3 => 1.0.0-beta.3 

### Details

I would like to export some modules in the entry files so that I can use them in another project, so I wrote a simple demo to test if it is possible.
```ts
// src/main.ts
import App from "./App";

export { App };
```
but `App.tsx` as well as `main.tsx` is not included in the built file `main.js`.
![image](https://github.com/user-attachments/assets/2ff7c1a5-2a51-49b3-ae37-70d4530ef8df)
so I checked the rspack tree shaking docs, and try sideEffects configurations, but still not work.
However, when disabled minimize in rspack config, 
```ts
// rspack.config.ts
optimization: {
		minimize: false,
	},
```
files built correctly
![image](https://github.com/user-attachments/assets/9d970b98-adbf-4e0b-af8f-30edf0d8ea5f)
so I'm wondering if it is something wrong with the minimizer, or if I missed some configs.

### Reproduce link

https://github.com/MaxtuneLee/rspack-export-demo

### Reproduce Steps

pnpm build

**Comment by xc2** [comment]
The default output is used to be "executed" so any code that will not be executed would be stripped.

If you want to "export" something, please specify a library type as your need with `output.library.type` 

- https://webpack.js.org/configuration/output/#outputlibrarytype
- https://rspack.dev/config/output#outputlibrarytype
