### ISSUE TITLE
[Feature]: complex values support for `HtmlRspackPlugin#templateParameters`

### ISSUE THREAD

**Issue by JounQin** [web-infra-dev/rspack#7509]
### What problem does this feature solve?

I'm migrating `webpack` to `rspack` in https://github.com/backstage/backstage/pull/25953, and find `HtmlRspackPlugin#templateParameters` only support simple `Record<string, string>`, is that possible to support `Record<string, unknown>`?

Of course it's fine to use `HtmlWebpackPlugin` instead.

### What does the proposed API of configuration look like?

As about

**Comment by JounQin** [comment]
Besides, I found `Unrecognized key(s) in object: 'maxAsyncRequests', 'maxInitialRequests' at "optimization.splitChunks.cacheGroups.packages"` which is support by webpack.

In rspack, `maxAsyncRequests/maxInitialRequests` are only available at `optimization.splitChunks` level.

**Comment by JSerFeng** [comment]
> HtmlRspackPlugin#templateParameters only support simple Record<string, string>, is that possible to support Record<string, unknown>

In the future maybe, it is not high priority thing at present, as there is HtmlWebpackPlugin available.

> In rspack, maxAsyncRequests/maxInitialRequests are only available at optimization.splitChunks level.

Thanks for reporting I will support this soon
