### ISSUE TITLE
[Bug]: 使用assest/source 导出的文件内容不全

### ISSUE THREAD

**Issue by congxiaobai** [web-infra-dev/rspack#7540]
### System Info

![image](https://github.com/user-attachments/assets/2f902102-9c58-4f8f-afe9-cc3d4b7af74b)

### Details

1.   使用    {
          resourceQuery: /\?raw/,
          type: 'asset/source'
        }解析文本
2. 被解析的文本是一个ts文件
 
![image](https://github.com/user-attachments/assets/66bac8e4-0d11-4cce-9270-4bdd0d1fd155)
3. 运行之后发现导出的内容与源文件不符
4. 源文件：
![image](https://github.com/user-attachments/assets/f334ee0e-cb58-4750-a31c-41c774cf9faa)
5. 解析结果：
![image](https://github.com/user-attachments/assets/dfc9ecfa-989a-4d2a-b31e-ba8b4b3dde68)

### Reproduce link

https://github.com/congxiaobai/rspack-error

### Reproduce Steps

1. run  'pnpm run dev'
2. 在浏览器控制台查看

**Comment by xc2** [comment]
Please add option `resourceQuery: {not: [/raw/]},` to rule for `/\.ts$/`

**Comment by h-a-n-a** [comment]
Feel free to reopen this if you have anything else to report.
