### ISSUE TITLE
[Bug]: Externals config object does not work in librarytarget "umd"

### ISSUE THREAD

**Issue by MarcoLeko** [web-infra-dev/rspack#7542]
### System Info

  System:
    OS: macOS 14.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 204.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
    bun: 1.1.12 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.6
  npmPackages:
    @rspack/cli: ^0.7.5 => 0.7.5 
    @rspack/core: ^0.7.5 => 0.7.5 

### Details

It seems that how externals are handled in rspack are not working as expected like the webpack API. Especially when trying to set the externals via object and using `libraryTarget: 'umd'`, like:

```
  externals: {
    react: {
      root: ["React"],
      commonjs: "react",
      commonjs2: "react",
      amd: "react",
    },
    "react-dom": {
      root: ["ReactDom"],
      commonjs: "react-dom",
      commonjs2: "react-dom",
      amd: "react-dom",
    },
  },
```
We tried to follow this documentation: https://rspack.dev/config/externals#object. We tested the following setups with externalizing the dependencies like above:
* webpack + babel-loader (works) ✅ 
* webpack + swc-loader (works) ✅ 
* rspack + buildin swc (fails) 🔴 

### Reproduce link

https://github.com/MarcoLeko/rspack-can-not-read-property-of-undefined

### Steps to reproduce

I've provided a minimal reproducible env, to test it out:
* Clone: [Reproducible error project](https://github.com/MarcoLeko/rspack-can-not-read-property-of-undefined)
* Execute `npm ci`

* Run: `npm run webpack:swc:dev:server` 
* Hit route: http://localhost:3001 => works  ✅

* Run: `npm run webpack:babel:dev:server`
* Hit route: http://localhost:3001 => works  ✅

* *Run: `npm run rspack:dev:server`
* Hit route: http://localhost:3001 => will fail with `Cannot read properties of null (reading 'useState')` 🔴

**Comment by xc2** [comment]
It is due to react being packed into the server bundle.

Just add `externals: [nodeExternals()],` to `rspack.config.server.js` as you do in `webpack.config.server.js`

**Comment by MarcoLeko** [comment]
That worked, thanks!
