### ISSUE TITLE
[Feature]: support more command-line flags

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7573]
### What problem does this feature solve?

Rspack currently missing some cli flags which cause some migration pain for users, see https://birtles.blog/2024/08/14/lessons-learned-switching-to-rspack/#command-line-flags

> Rspack CLI includes a built-in dev server but unfortunately, the command-line flags differ from webpack-dev-server in a few places, notably missing options like --port and --hot/--no-hot.
To handle such cases I ended up using various --env values and checking them in rspack.config.js’s [configuration function](https://rspack.dev/config/index#exporting-a-configuration-function). This seems like a potentially unnecessary point of friction that could be eased in a future release.

we can align more flags  to make migration easier

### What does the proposed API of configuration look like?

seems no need to support all flags(some flags are rarely used and hard to understand), but we can support some common flags like
```
--port
--hot | --no-hot
--host
```

**Comment by shulaoda** [comment]
Can you answer my question? I see these two variables below, but it doesn't seem to have been actually used?
https://github.com/web-infra-dev/rspack/blob/fd631fa1193dd95437fe0d50f8cc5dd4d8a033fb/packages/rspack-cli/src/commands/serve.ts#L46-L47

**Comment by hardfist** [comment]
> Can you answer my question? I see these two variables below, but it doesn't seem to have been actually used?
> 
> https://github.com/web-infra-dev/rspack/blob/fd631fa1193dd95437fe0d50f8cc5dd4d8a033fb/packages/rspack-cli/src/commands/serve.ts#L46-L47
it's used here, if multi compiler specify same port, it will throw error

**Comment by shulaoda** [comment]
> it's used here, if multi compiler specify same port, it will throw error

https://github.com/web-infra-dev/rspack/blob/fd631fa1193dd95437fe0d50f8cc5dd4d8a033fb/packages/rspack-cli/src/commands/serve.ts#L101-L107

But it doesn't seem to be used anywhere else except here. `usedPorts` seems to be absolutely empty.

**Comment by hardfist** [comment]
> > it's used here, if multi compiler specify same port, it will throw error
> 
> https://github.com/web-infra-dev/rspack/blob/fd631fa1193dd95437fe0d50f8cc5dd4d8a033fb/packages/rspack-cli/src/commands/serve.ts#L101-L107
> 
> But it doesn't seem to be used anywhere else except here. `usedPorts` seems to be absolutely empty.

why the push will update usedports

**Comment by shulaoda** [comment]
> why the push will update usedports

This is where I am confused, this code seems meaningless.

**Comment by hardfist** [comment]
if you have two compiler and both use same port，during loop the usedports is updated so it can be used to detect conflict in next iteration
