### ISSUE TITLE
refactor: enable more lints clippy rules

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7589]
currently we only enable a very small sets of lint rules and clippy actually provides lots of rules that's not only useful for style but also for performance, we should adopt more clippy rule.
a good start is  to learn from biome's rules https://github.com/biomejs/biome/blob/main/Cargo.toml#L15

**Comment by shulaoda** [comment]
Clippy lints: https://rust-lang.github.io/rust-clippy/rust-1.80.0/index.html

**Comment by h-a-n-a** [comment]
closed as finished
