### ISSUE TITLE
[Feature]: provide better comment annotation 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#7591]
### What problem does this feature solve?

currently rspack | webpack will generate the following result for `modern-module`, the comment is not nicely(`Concate module` seems hard to understand for normal users) to read, even minifier can remove these comments, but normally library code shouldn't be minified for better debug experience
```js
;// CONCATENATED MODULE: ./src/answer.js
const answer = 42;

;// CONCATENATED MODULE: ./src/secret.js
const secret = 'rspack';

;// CONCATENATED MODULE: ./src/index.js



export { answer, secret };

//# sourceMappingURL=index.mjs.map
```

### What does the proposed API of configuration look like?
there're some solutions, i'm not sure which is better
* provide a option to remove comments (like rollup don't have this annotation)
```js
{
  output: {
      keepDebugComments: boolean // true means keep, false means remove
   }
}
```
* provide better comment annotation(like esbuild provide the simplest annotation)
```js
 ./src/answer.js
const answer = 42;

 ./src/secret.js
const secret = 'rspack';

 ./src/index.js
```

**Comment by hardfist** [comment]
@alexander-akait is this option acceptable for webpack or any better suggestions for this problem? also cc @fi3ework

**Comment by chenjiahan** [comment]
The original module path (./src/answer.js) is useful for debugging, maybe we can replace `CONCATENATED MODULE` with another words, or only remove `CONCATENATED MODULE`.

**Comment by chenjiahan** [comment]
We can consider adding an `rspackFuture.friendlyComments` option to generate more user friendly comments, and it can be enabled in Rspack v2 by default.

**Comment by hardfist** [comment]
> We can consider adding an `rspackFuture.friendlyComments` option to generate more user friendly comments, and it can be enabled in Rspack v2 by default.

comments content shouldn't be public api, so change comment content seems not a breaking change

**Comment by chenjiahan** [comment]
Yes, if Rspack doesn't strive for consistency with webpack's outputs and comments, then changing the comments content directly is a better idea.

**Comment by alexander-akait** [comment]
I am fine to improve comment, maybe we can do it without any new options for output, it is just a debug infromation, so we can just impove it

**Comment by alexander-akait** [comment]
How do you want to see them?

**Comment by alexander-akait** [comment]
So you just want to remove `CONCATENATED MODULE` words?

**Comment by fi3ework** [comment]
> So you just want to remove `CONCATENATED MODULE` words?

Yes, that will sufficient. 

And it will be nicer to adding the leading `;` introduced in https://github.com/webpack/webpack/pull/11920 only when necessary, if possible.

**Comment by alexander-akait** [comment]
@fi3ework @hardfist Feel free to send a Pull requests

> And it will be nicer to adding the leading ; introduced in https://github.com/webpack/webpack/pull/11920 only when necessary, if possible.

I think we already insert it only when needed, if not, consider it as a bug fix

**Comment by fi3ework** [comment]
bump, already landed in webpack.
