### ISSUE TITLE
[Bug]: 使用defineConfig中的plugins注册VueLoaderPlugin()编译报错缺少 'webpack/lib/rules/BasicEffectRulePlugin'

### ISSUE THREAD

**Issue by lintu1** [web-infra-dev/rspack#7598]
### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.09 GB / 7.83 GB
  Binaries:
    Node: 16.20.2 - E:\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - E:\nvm\nodejs\yarn.CMD
    npm: 8.19.4 - E:\nvm\nodejs\npm.CMD
    pnpm: 8.10.2 - E:\nvm\nodejs\pnpm.CMD
  Browsers:
    Chrome: 127.0.6533.119
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rspack/cli: ^1.0.0-beta.1 => 1.0.0-beta.1
    @rspack/core: ^1.0.0-beta.1 => 1.0.0-beta.1

### Details

npm run serve 出现缺少模块问题
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'
Require stack:
- D:\tyy\web-portal-rsbuild\node_modules\vue-loader\lib\plugin-webpack5.js
- D:\tyy\web-portal-rsbuild\node_modules\vue-loader\lib\plugin.js
- D:\tyy\web-portal-rsbuild\node_modules\vue-loader\lib\index.js
- D:\tyy\web-portal-rsbuild\rspack.config.js
- D:\tyy\web-portal-rsbuild\node_modules\@rspack\cli\dist\utils\crossImport.js
- D:\tyy\web-portal-rsbuild\node_modules\@rspack\cli\dist\utils\loadConfig.js
- D:\tyy\web-portal-rsbuild\node_modules\@rspack\cli\dist\cli.js
- D:\tyy\web-portal-rsbuild\node_modules\@rspack\cli\dist\bootstrap.js
- D:\tyy\web-portal-rsbuild\node_modules\@rspack\cli\bin\rspack
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\tyy\web-portal-rsbuild\node_modules\vue-loader\lib\plugin-webpack5.js:6:31)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\vue-loader\\lib\\plugin-webpack5.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\vue-loader\\lib\\plugin.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\vue-loader\\lib\\index.js',
    'D:\\tyy\\web-portal-rsbuild\\rspack.config.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\@rspack\\cli\\dist\\utils\\crossImport.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\@rspack\\cli\\dist\\utils\\loadConfig.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\@rspack\\cli\\dist\\cli.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\@rspack\\cli\\dist\\bootstrap.js',
    'D:\\tyy\\web-portal-rsbuild\\node_modules\\@rspack\\cli\\bin\\rspack'
  ]
}

### Reproduce Steps

配置rspack.config.js后
const path = require('path')
const rspack = require("@rspack/core");
const {VueLoaderPlugin} = require('vue-loader')
const { defineConfig } = require("@rspack/cli");

let plugins = [
  new VueLoaderPlugin(),
]

/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = defineConfig({
  context: __dirname,
  entry: {
    main: "./src/main.js"
  },
//   output: {
//     clean: true,
//     filename: 'js/[name].js',
//     cssFilename: 'css/[name].css',
//     assetModuleFilename: 'assets/[hash][ext]'
//   },

  devServer: {
    historyApiFallback: true,
  },

  plugins: [
    new VueLoaderPlugin(),
    new rspack.HtmlRspackPlugin({
      template: './index.html',
    }),
  ],
//   plugins,

  resolve: {
    alias: {
      "@": path.resolve(__dirname, 'src')
    },

    // extensions: [".js", ".json", ".wasm", '.vue', '.jsx', '.tsx']
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: "vue-loader",
            options: {
              experimentalInlineMatchResource: true
            }
          }
        ]
      },
      {
        test: /\.less$/,
        loader: "less-loader",
        type: "css",

      },
      {
        test: /\.scss$/,
        loader: "sass-loader",
        type: "css",
        exclude: /node_modules/,

      },
      {
        test: /\.(png|svg|jpg|jpeg|gif|webp)$/i,
        type: 'asset/resource',
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: 'asset',
      }
    ]
  }, 
  experiments: {
    css: false,
  },
})
使用npm run serve 报错
Error: Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'

**Comment by Fitz6** [comment]
It looks like your webpack version is outdated. You should upgrade to webpack 5.
```shell
npm install webpack@^5
```

**Comment by lintu1** [comment]
> 您的 webpack 版本似乎已过时。您应该升级到 webpack 5。
> 
> ```shell
> npm install webpack@^5
> ```

文档中不是说要移除webpack依赖吗 

现在你可以移除项目中 webpack 相关的依赖了：
npm remove webpack webpack-cli webpack-dev-server

**Comment by chenjiahan** [comment]
Some plugins / loaders are still depend on webpack internal modules, so you will need to install webpack in this case.
