### ISSUE TITLE
[Feature]: support for vue-class-component

### ISSUE THREAD

**Issue by zxfd** [web-infra-dev/rspack#7605]
### What problem does this feature solve?

there is so many old project build by vue-property-decorator(vue-class-component)，we want the speed and compatible of rspack, but now it seems that rspack is not support for vue-class-component yet

### What does the proposed API of configuration look like?

hope support for vue-class-componen

**Comment by hardfist** [comment]
https://class-component.vuejs.org/ it seems vue-class-component and it use legacy decorator feature, and have you tried https://swc.rs/docs/configuration/compilation#jsctransformlegacydecorator, if you met any problem please provide reproduce repo

**Comment by Yee1014** [comment]
我有类似的问题。复现Demo [查看](https://github.com/Yee1014/vue2-class-style-rspack-repo)

**Comment by Yee1014** [comment]
> https://class-component.vuejs.org/ it seems vue-class-component and it use legacy decorator feature, and have you tried https://swc.rs/docs/configuration/compilation#jsctransformlegacydecorator, if you met any problem please provide reproduce repo

我有类似的问题。复现Demo [查看](https://github.com/Yee1014/vue2-class-style-rspack-repo)

**Comment by Yee1014** [comment]
在我这个[复现 Demo](https://github.com/Yee1014/vue2-class-style-rspack-repo) 中！

测试下来貌似是 Rsbuild 的配置问题。

`https://rsbuild.dev/zh/config/tools/swc`，这个默认配置貌似没有完全生效，但是如果通过 `https://rsbuild.dev/zh/config/tools/rspack` 来设置 `swc`，如下：

```js
export default defineConfig({
  plugins: [pluginVue2()],
  tools: {
    rspack: {
      module: {
        rules: [
          {
            test: /\.(js|ts)$/,
            use: [
              {
                loader: "builtin:swc-loader",
                options: {
                  sourceMap: true,
                  jsc: {
                    parser: {
                      syntax: "typescript",
                      decorators: true,
                    },
                  },
                },
              },
            ],
          },
        ],
      },
    },
  },
});
```
就可以解决这个错误！
@hardfist

**Comment by Yee1014** [comment]
修改 swc 的 decoratorVersion 即可解决问题。

在 `rsbuild.config.ts` 中

```js
export default defineConfig({
// ...
tools: {
        swc: {
            jsc: {
                transform: {
                    decoratorVersion: '2021-12',
                },
            },
        },
    },
// ...
})
```

Rsbuild中默认使用了 `2022-03` 。

**Comment by hardfist** [comment]
这并不算是rsbuild的配置问题，这是因为 vue-class-component依赖了很老版本的decorator实现，rsbuild 不应该因为这个库来修改其默认的decorator实现，我们可以在文档上加上 vue-class-components的使用说明，但是不会去修改默认的decorator的版本，cc @chenjiahan

**Comment by chenjiahan** [comment]
Rsbuild already provides a config to change the decorator version: https://rsbuild.dev/config/source/decorators

**Comment by idudu008** [comment]
我也遇到了这个问题，不过我使用的是 rspack。项目技术栈：vue@2.6 vue-class-component@7 vue-property-decorator@9 ，编译提示错误：
`Module build failed: SyntaxError: App.vue Support for the experimental syntax 'decorators' isn't currently enabled (7:1):`

请问这个怎么解决
