### ISSUE TITLE
[Feature]: export types related to builtin:lightningcss-loader

### ISSUE THREAD

**Issue by zavierkolten** [web-infra-dev/rspack#7610]
### What problem does this feature solve?

Make it easier for developers to get the type definitions for the `builtin:lightningcss-loader` configuration.

### What does the proposed API of configuration look like?

N/A

**Comment by JSerFeng** [comment]
You can use

```js
import('@rspack/core').LightningcssLoaderOptions
```

**Comment by zavierkolten** [comment]
@JSerFeng Can I just import this type from '@rspack/core' ? I want to extend it🙂

**Comment by h-a-n-a** [comment]
Closed as already implemented

**Comment by JSerFeng** [comment]
> @JSerFeng Can I just import this type from '@rspack/core' ? I want to extend it🙂

```ts
import { type LightningcssLoaderOptions } from "@rspack/core";
```

**Comment by zavierkolten** [comment]
@JSerFeng OK， I've found it after upgrading @rspack/core from '1.0.0-beta.5' to '1.0.0-rc.1'
