### ISSUE TITLE
Is there a plan supporting resolve plugins ?

### ISSUE THREAD

**Issue by hikerpig** [web-infra-dev/rspack#7620]
Our project in webpack relies on several enhanced-resolve plugin for dynamic path replacement or so.

So it would be nice if there is similar mechanism in rspack, otherwise we would need some extra efforts transforming the build process to rspack.

**Comment by SyMind** [comment]
@hikerpig  I wonder which resolve plugins you are using. Are they open source?

**Comment by hikerpig** [comment]
@SyMind It's one of our company's project, not open-source. We have some custom resolve plugins for our specific needs.

So far I find `normalModuleFactory.hooks.resolve` suffices for what I am looking for. Just need some rewriting for those resolve plugins.
