### ISSUE TITLE
[Bug]: Module Federation typeError: Cannot set properties of undefined (setting 'constructor')    

### ISSUE THREAD

**Issue by skearney414** [web-infra-dev/rspack#7632]
### System Info

mathjs with pnpm,rspack beta 5 with module federation 1.5

### Details

When using mathjs with rspack module federation it leads to the following error on launching the micrfrontend. 
This occurs when calling factory().

Promise.resolve(remote.get(`./AppShell`))
            .then((moduleFactory) => moduleFactory())
            .then((microfrontend) =>
                microfrontend.mount(configuration.Shell, {
                    ...appVars,
                    getWfFormsData,
                    openWorkflowForm: FormToolbarClickedEvent,
                    events,
                    setVariable,
                    isLightning: true,
                })
            )
            .catch((error) => {
                diag.error({
                    category: "Microfrontend Helper",
                    message: `Failed to load microfrontend. Error: ${JSON.stringify(error)}`,
                });
<img width="407" alt="image" src="https://github.com/user-attachments/assets/dd72a857-8242-4736-b570-454600897355">

When using webpack federation instead of rspack the issue does not occur. 

### Reproduce Steps

Create a simple project that imports mathjs, 
Use that in the module federation setup. 

Importing the module results in the error.

**Comment by CPunisher** [comment]
Can you provide a reproduction? I import mathjs based on https://github.com/rspack-contrib/rspack-examples/tree/main/rsbuild/module-federation, but get no error.
