### ISSUE TITLE
[Bug]: css module has HMR but tsx file not update css name

### ISSUE THREAD

**Issue by xyhxx** [web-infra-dev/rspack#7709]
### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 6.88 GB / 15.89 GB
  Binaries:
    Node: 21.7.3 - D:\nvm\node\node.EXE
    Yarn: 1.22.22 - D:\nvm\node\yarn.CMD
    npm: 10.5.0 - D:\nvm\node\npm.CMD
    pnpm: 9.4.0 - D:\nvm\node\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: 1.0.0-rc.1 => 1.0.0-rc.1
    @rspack/core: 1.0.0-rc.1 => 1.0.0-rc.1
    @rspack/plugin-react-refresh: 1.0.0 => 1.0.0

### Details

After I updated the classname in the index.module.css file or added a new class,  css file was HMR, but the tsx file did not update the classaname in the export css object, resulting in style loss.

### Reproduce link

https://github.com/xyhxx/rspack-css-module-hmr/tree/main

### Reproduce Steps

1. run `pnpm run dev`
2. change demo-title2 to demo-title in `index.module.css`
3. change css.demoTitle2 to css.demoTitle in `App.jsx`
4. modified css name does not take effect

**Comment by JSerFeng** [comment]
bump

**Comment by JSerFeng** [comment]
closed as it's fixed in the latest commit after #8587
