### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by calidan-x** [web-infra-dev/rspack#7718]
### System Info

mac os 

### Details

创建项目后 启动项目 直接报错

Error: dlopen(/Users/xxx/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node, 0x0001): tried: '/Users/xxx/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' (code signature invalid in <157AF2F1-7438-3058-9DB6-CF5179FAA924> '/Users/xxx/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' (errno=85) sliceOffset=0x00000000, codeBlobOffset=0x02BD7E20, codeBlobSize=0x00057B88), '/System/Volumes/Preboot/Cryptexes/OS/Users/calidan/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' (no such file), '/Users/xxx/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' (code signature invalid in <157AF2F1-7438-3058-9DB6-CF5179FAA924> '/Users/xxxx/Desktop/project/node_modules/@rspack/binding-darwin-arm64/rspack.darwin-arm64.node' (errno=85) sliceOffset=0x00000000, codeBlobOffset=0x02BD7E20, codeBlobSize=0x00057B88)

### Reproduce Steps

│  cd project   │
│  npm i        │
│  npm run dev |

**Comment by h-a-n-a** [comment]
Please follow the template
