### ISSUE TITLE
[Feature]: SwcJsMinimizerRspackPlugin support charset option

### ISSUE THREAD

**Issue by ahaoboy** [web-infra-dev/rspack#7734]
### What problem does this feature solve?

For nerd fonts characters, convert them to Unicode by default. It is expected that there will be an option similar to esbuild charset

rspack

```
const a = "󰋚";
console.log("a", a);
```
```
  console.log("a", "\uDB80\uDEDA");
```
esbuild 
```
esbuild ./a.js --bundle  --charset=utf8 
```

```
var a = "󰋚";
console.log("a", a);
```

### What does the proposed API of configuration look like?

```
  optimization: {
    minimizer: [
      new rspack.SwcJsMinimizerRspackPlugin({
        charset: 'utf8'
      }),
    ]
  },
```

**Comment by chenjiahan** [comment]
Try this:

```js
new rspack.SwcJsMinimizerRspackPlugin({
  minimizerOptions: {
    format: {
      asciiOnly: true,
    },
  },
})
```

Ref: https://swc.rs/docs/configuration/minification#jscminifyformat

**Comment by ahaoboy** [comment]
> Try this:
> ```js
>       asciiOnly: true,

Doesn't work

```
export default defineConfig({
  target: 'es3',
  entry: {
    "a": "./src/a.tsx"
  },
  resolve: {
    extensions: ["...", ".ts", ".tsx", ".jsx"]
  },
  output: {
    chunkFormat: "commonjs"
  },
  optimization: {
    minimizer: [
      new rspack.SwcJsMinimizerRspackPlugin({
        minimizerOptions: {
          format: {
            asciiOnly: true,
          },
        },
      })
    ]
  },
});
```

**Comment by ahaoboy** [comment]
https://github.com/ahaoboy/rspack-repro-charset.git
```
pnpm run build
```

**Comment by chenjiahan** [comment]
This should be a bug of SWC, can you submit an issue to the SWC repo?

- https://play.swc.rs/?version=1.7.21&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP11BKVNJRUPq8oXsWiH62tfvF%2BqlKmtYA2egJaCMAAAA%3D&config=H4sIAAAAAAAAA42VzW7bMAyA732KwOcetsOAYg%2FQ1xAUiXKUyaIg0m6Mou8%2B2nHSZKaNXRybH38k%2FuXz5XBozuSa34dPeZWPYitBvX%2BLhMbM9iKSBlxnydVYuHm90TNNKNhEMIu%2BrqRhW1vg2Yp%2BLepNQiS4qS%2ByLuYYxseAnc1tggfJ5A5LggHSs%2FGM%2FgAU45IlyrYD2tIIu7TUOFgG%2BcWiKUV4U6Rkg63x54%2BnDNxzIAoOu1KB6Pkykpq%2Bg8xaIFsrfkyAa%2F8oPyImsHmHGEsmZoYWqubYYUq2EJjBVsXLdFK5C6EWYoI9g7%2BnZ8WzjxwxS8w19WC9cehBQbGC4ziAZiaxxCwTJlDuM2MPx75t5379xxoGm3qpqEIuc0nktIrXE0ZiE%2FqspfAKN3JwhUtyV%2B0TTAXua17bnTHmjZr8b2dLP21Z73d9zEGmj0eFy6hqt8zQTmMSY1AyO2UGKketmhV872DKrNOOs%2BCN9FH0YCAE6RXFNX1EdictKI8FMChA6muD1lVXYO5TuMGngdjB73JL1hts0egsn7Ypjd0R006ADviEfkdBSsG4jatsiUvZ5n32IK0BXlXpaQbrJSADwGjSvPdXvSHjIR5Nm%2FD4vSZuG%2FPl9px35%2Fefwqzz9Rc%2BNnjbpwYAAA%3D%3D

**Comment by chenjiahan** [comment]
This issue will be closed as it is an upstream issue.
