### ISSUE TITLE
[Bug]: writeToDisk feature (devMiddleware) does not work when starting devServer

### ISSUE THREAD

**Issue by gitrequests** [web-infra-dev/rspack#7740]
### System Info

System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz
    Memory: 22.63 GB / 31.13 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash

### Details

The writeToDisk feature does not work when starting devServer, files do not appear in the output folder.
rsbuild configuration:
```js
import { defineConfig } from '@rsbuild/core';

export default defineConfig({
    devServer: {
        devMiddleware: {
            writeToDisk: true,
        },
    },
});
```
Exactly the same configuration works in webpack 5, files are created in the output folder when the devServer starts.

### Reproduce Steps

1. Add config to rsbuild.config.mjs
```js
import { defineConfig } from '@rsbuild/core';

export default defineConfig({
    devServer: {
        devMiddleware: {
            writeToDisk: true,
        },
    },
});
```
2. Run `npm run dev`
3. Check that files are not created in the dist folder

**Comment by colinaaa** [comment]
The [`devServer.devMiddleware`](https://rspack.dev/config/dev-server#devserverdevmiddleware) configuration you provided is a Rspack configuration. It does not work with Rsbuild.

You should use `dev.writeToDisk: true` in your `rsbuild.config.mjs`.

See: https://rsbuild.dev/config/dev/write-to-disk

You may also add `//@ts-check` at the front of the `rsbuild.config.mjs`, which would make TypeScript show type errors on invalid configurtaion.
