### ISSUE TITLE
[Bug]: Compilation does not export the chunkGroups variable, and using getStats().toJson({ chunkGroups: true }) does not return data with the origins variable included. 

### ISSUE THREAD

**Issue by EzioW** [web-infra-dev/rspack#7766]
### System Info

node version 18 
relative package @ecom/pb-route-chunks-preload-plugin

### Details

I encountered an API conversion issue while upgrading Rspack and adapting a webpack plugin. After using the recommended approach to retrieve chunkGroups data, I found that some fields were missing.

### Reproduce Steps

install @ecom/pb-route-chunks-preload-plugin for test

**Comment by LingyuCoder** [comment]
Seems that [chunk groups](https://github.com/webpack/webpack/blob/main/lib/stats/DefaultStatsFactoryPlugin.js#L126-L140) in webpack stats don't has `origins` too. The `origins` is only in chunk group objects. So need to add an API on JavaScript chunk group API.

**Comment by EzioW** [comment]
> Seems that [chunk groups](https://github.com/webpack/webpack/blob/main/lib/stats/DefaultStatsFactoryPlugin.js#L126-L140) in webpack stats don't has `origins` too. The `origins` is only in chunk group objects. So need to add an API on JavaScript chunk group API.

So when will I be able to access this variable, and will its data structure be the same as in webpack? Is there any plan to support this?

**Comment by LingyuCoder** [comment]
> > Seems that [chunk groups](https://github.com/webpack/webpack/blob/main/lib/stats/DefaultStatsFactoryPlugin.js?rgh-link-date=2024-09-03T07%3A39%3A29Z#L126-L140) in webpack stats don't has `origins` too. The `origins` is only in chunk group objects. So need to add an API on JavaScript chunk group API.
> 
> So when will I be able to access this variable, and will its data structure be the same as in webpack? Is there any plan to support this?

should be released in `1.0.3` next tuesday
