### ISSUE TITLE
[Bug]: `exclude: {}` is required to enable transpilation with lightningcss

### ISSUE THREAD

**Issue by SabrinaJewson** [web-infra-dev/rspack#7768]
### System Info

Using rspack 1.0.0.

### Details

If one writes

```ts
export default defineConfig({
	optimization: {
		minimizer: [
			new rspack.LightningCssMinimizerRspackPlugin({
				minimizerOptions: { targets }
			}),
		],
	},
});
```

then no transpilation is performed. However, it works if one writes `{ targets, exclude: {} }`.

### Reproduce Steps

1. `pnpm create rspack@latest`, cd in the directory, `pnpm install`
2. Edit `index.css` to say something like `main{color:blue;body{color:red}}`
3. Run `pnpm build --mode=production`; observe that `dist/main.css` contains nesting (in contradiction to the browserslist in the config file)
4. Edit line 40 of `rspack.config.mjs` to say `minimizerOptions: { targets, exclude: {} }`, rebuild, and observe that `dist/main.css` now does not include nesting

**Comment by ahabhgk** [comment]
This is expected, see https://arc.net/l/quote/pwktziks, you need `builtin:lightningcss-loader` to downgrade syntax, or override the default `exclude`

**Comment by SabrinaJewson** [comment]
Then would it at least make sense to avoid passing in `targets` to `rspack.LightningCssMinimizerRspackPlugin` when a user runs `pnpm create rspack@latest`?
