### ISSUE TITLE
[Bug]: runtime's `source.source()` does not return a string

### ISSUE THREAD

**Issue by theninthsky** [web-infra-dev/rspack#7781]
### System Info

System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 8.69 GB / 15.79 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rspack/cli: ^1.0.0 => 1.0.0
    @rspack/core: ^1.0.0 => 1.0.0
    @rspack/plugin-react-refresh: ^1.0.0 => 1.0.0

### Details

When extracting the chunk sources in the build using `source.source()`, all sources are extracted as strings except for the `runtime` chunk, which returns the following object: `{"type":"Buffer","data":[...]`

Relevant code snippet:
```
new HtmlPlugin({
        scriptLoading: 'module',
        templateContent: ({ compilation }) => {
          const assets = compilation.getAssets()
          const pages = pagesManifest.map(({ chunk, path, title, data }) => {
            const scripts = assets
              .map(({ name }) => name)
              .filter(name => new RegExp(`[/.]${chunk}\\.(.+)\\.js$`).test(name))

            return { path, title, scripts, data }
          })

          if (production) {
            const assetsWithSource = assets
              .filter(({ name }) => /^scripts\/.+\.js$/.test(name))
              .map(({ name, source }) => ({
                url: `/${name}`,
  ----------->  source: source.source(),
                parentPaths: pages.filter(({ scripts }) => scripts.includes(name)).map(({ path }) => path)
              }))

            writeFileSync(join(__dirname, 'public', 'assets.js'), JSON.stringify(assetsWithSource))
          }

          return htmlTemplate(pages)
        }
      }),
```

### Reproduce link

https://github.com/theninthsky/client-side-rendering/tree/rspack

### Reproduce Steps

1. Clone https://github.com/theninthsky/client-side-rendering.git
2. Switch to the `rspack` branch.
3. `npm i`
4. In the `scripts/inject-worker-html.js` file, comment line 29 which removes the helper file `public/assets.js`.
5. `npm run build`
6. Open `public/assets.js` and look for `runtime`.

You'll see that only this chunk was extracted as an object.

**Comment by SyMind** [comment]
@theninthsky I cannot reproduce this issue on a Mac. It might be a Windows-specific bug. I will try it on Windows later.

**Comment by theninthsky** [comment]
@SyMind
Thanks.
It also happens in Cloudflare Pages CI build (Linux).

**Comment by kitiho** [comment]
Same error happened. I wrote a custom plugin .
My plugin is 
```ts
import { Compiler, Compilation, sources } from '@rspack/core';

class DynamicPublicPathPlugin {
    constructor() {}
    apply(compiler: Compiler) {
        compiler.hooks.emit.tapAsync(
            'DynamicPublicPathPlugin',
            (compilation: Compilation, callback: () => void) => {
                // 修改__webpack_require__.p的值为CDN地址
                const assets = compilation.assets;
                Object.keys(assets).forEach((key) => {
                    if (key.endsWith('.js')) {
                        const asset = assets[key];
                        // Bug： https://github.com/web-infra-dev/rspack/issues/7781
                        let source = asset.source() as string;
                        const pattern = /([a-zA-Z0-9_.]+)="\<\$\= locals\.cdnDomainUrl \$\>"/g;
                        const replacement =
                            '$1=window.__SPOTTER_APP_BOOT_DATA__.cdnDomainUrl + "/"';
                        source = source.replace(pattern, replacement);

                        // 创建新source
                        const newSource = new sources.RawSource(source);

                        // 覆盖source
                        compilation.assets[key] = newSource;
                    }
                });

                callback();
            }
        );
    }
}

export = DynamicPublicPathPlugin;
```
<img width="488" alt="image" src="https://github.com/user-attachments/assets/66c3390b-f9cc-4198-9673-3ed4bd73d9ee">

**Comment by SyMind** [comment]
@theninthsky  I wonder if the problem is related to your regex filtering the name field. Even if `source.source()` returns a buffer, there should still be content present, rather than nothing as mentioned in your issue.

**Comment by kitiho** [comment]
> ```ts
> et source = asset.source() as string;
> ```

All api is same as Webpack

**Comment by SyMind** [comment]
@kitiho Not the same bug. Rspack transforms the source from the Rust side to the JavaScript side. Now, it will be converted to `RawSource`. If you want to call replace on the source, you should use `const replaceSource = new ReplaceSource(source);`.

**Comment by theninthsky** [comment]
@SyMind 
You mean the `"data": [...]` part I wrote?
Sorry, I just wanted to it make it short. There is indeed binary data inside `data`.

I don't think this is related to the `assetsWithSource` name filtering, but I'll try removing it and just keep all assets to see if it fixes the issue (might take a few days since I'm not home).

**Comment by SyMind** [comment]
@theninthsky I reproduce this issue. I'm trying to fix it.

**Comment by theninthsky** [comment]
@SyMind 
Works like a charm, thanks!
