### ISSUE TITLE
[Bug]: Rspack cannot be used with unplugin-vue-router

### ISSUE THREAD

**Issue by tmg0** [web-infra-dev/rspack#7787]
### System Info

System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M2
    Memory: 65.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.volta/tools/image/node/18.20.4/bin/node
    npm: 10.7.0 - ~/.volta/tools/image/node/18.20.4/bin/npm
    pnpm: 9.9.0 - ~/.volta/tools/image/pnpm/9.9.0/bin/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
  npmPackages:
    @rspack/cli: ^1.0.1 => 1.0.1
    @rspack/core: ^1.0.1 => 1.0.1

### Details

[unplugin-vue-router](https://github.com/posva/unplugin-vue-router) does not work with rspack, It seems to be a vfs error? 

I'm not quite sure abount this issue should belongs to rspack or unplugin, unplugin has support all of the life cycle hooks of rspack, so it should not be a problem?

I would be very grateful if anyone could answer this question.

```bash
ERROR in ./node_modules/.pnpm/unplugin@1.12.3/node_modules/unplugin/dist/rspack/virtual.js?unplugin_rspack_virtual=%2F__vue-router%2Fauto-routes
  × Module parse failed:
  ╰─▶   × JavaScript parsing error: 'import', and 'export' cannot be used outside of module code
         ╭─[1:0]
       1 │ export const routes = [
         · ──────
       2 │   {
       3 │     path: '/',
         ╰────

  help:
        File was processed with these loaders:
         * commonjs|/nuxlite/node_modules/.pnpm/unplugin@1.12.3/node_modules/unplugin/dist/rspack/loaders/load.js??ruleSet[1].rules[2].use[0]
        You may need an additional loader to handle the result of these loaders.
```

### Reproduce link

https://github.com/tmg0/nuxlite/tree/rspack/unplugin-vue-router

### Reproduce Steps

1. `pnpm i`
2. `pnpm dev`

**Comment by ahabhgk** [comment]
https://github.com/unjs/unplugin/pull/411 should fix this

**Comment by tmg0** [comment]
Wow！Thanks for the quick fix！ 🚀

**Comment by webszy** [comment]
so,how to use this plugin correctly?

**Comment by tmg0** [comment]
This should be fixed in the latest version of `unplugin-vue-router`, please upgrade and try again.

If there are still issues after the upgrade, could you provide the error logs?

**Comment by yuantongkang** [comment]
> This should be fixed in the latest version of `unplugin-vue-router`, please upgrade and try again.
> 
> If there are still issues after the upgrade, could you provide the error logs?
```ts
import VueRouterPlugin  from 'unplugin-vue-router/webpack' 
 plugins: [
    pluginBabel({
      include: /\.(?:jsx|tsx)$/,
    }),
    pluginVue(),
    pluginVueJsx(),
    {
      name: 'vue-router-plugin',
      setup(api) {
        api.modifyWebpackChain((chain) => {
          chain.plugin('vue-router').use(VueRouterPlugin, [{
            path: 'src/pages',
            dts: 'src/typed-router.d.ts',
          }])
        })
      }
    }
  ],

print error `ESModulesLinkingError: export 'routes' (imported as 'routes') was not found in 'vue-router/auto-routes' (possible exports: NavigationFailureType, RouterLink, RouterView, START_LOCATION, createMemoryHistory, createRouter, createRouterMatcher, createWebHashHistory, createWebHistory, isNavigationFailure, loadRouteLocation, matchedRouteKey, onBeforeRouteLeave, onBeforeRouteUpdate, parseQuery, routeLocationKey, routerKey, routerViewLocationKey, stringifyQuery, useLink, useRoute, useRouter, viewDepthKey)`
```

**Comment by tmg0** [comment]
The error message seems to indicate that the `resolveId` did not match `vue-router/auto-routes`. I suspect this might be caused by the backslash \ in the path on Windows.

I noticed that the import part is using the webpack version. Could you try using rspack? unplugin should already have support for rspack.

However, the configuration file you provided seems incomplete. If further investigation is needed, please provide the environment information and a reproduce repository.

**Comment by yuantongkang** [comment]
> The error message seems to indicate that the `resolveId` did not match `vue-router/auto-routes`. I suspect this might be caused by the backslash \ in the path on Windows.
> 
> I noticed that the import part is using the webpack version. Could you try using rspack? unplugin should already have support for rspack.
> 
> However, the configuration file you provided seems incomplete. If further investigation is needed, please provide the environment information and a reproduce repository.

I encountered the same issue as described in https://github.com/posva/unplugin-vue-router/issues/531 when exporting with rspack.

**Comment by yuantongkang** [comment]
> > The error message seems to indicate that the `resolveId` did not match `vue-router/auto-routes`. I suspect this might be caused by the backslash \ in the path on Windows.
> > I noticed that the import part is using the webpack version. Could you try using rspack? unplugin should already have support for rspack.
> > However, the configuration file you provided seems incomplete. If further investigation is needed, please provide the environment information and a reproduce repository.
> 
> I encountered the same issue as described in [posva/unplugin-vue-router#531](https://github.com/posva/unplugin-vue-router/issues/531) when exporting with rspack.


```ts
import { defineConfig } from '@rsbuild/core'
import { pluginBabel } from '@rsbuild/plugin-babel'
import { pluginVue } from '@rsbuild/plugin-vue'
import { pluginVueJsx } from '@rsbuild/plugin-vue-jsx'


import rspackPluginVueRouter, { VueRouterAutoImports } from 'unplugin-vue-router'
import path from 'node:path'
import { execSync } from 'node:child_process'
import AutoImport from 'unplugin-auto-import/rspack'


export default defineConfig({
  source: {
    entry: {
      index: './src/main.ts',
    },
    alias: {
      '@/': path.join(__dirname, 'src/'),
    },
    define: {
      BUILD_DATE: JSON.stringify(new Date().toLocaleString()),
      COMMIT_SHA: gitSha,
      RELEASE_ID: JSON.stringify(releaseId),
    },
  },

  plugins: [
    pluginBabel({
      include: /\.(?:jsx|tsx)$/,
    }),
    pluginVue(),
    pluginVueJsx(),
  ],

  tools: {
    async rspack (config) {
      config.plugins?.push(
        rspackPluginVueRouter.rspack(),
        AutoImport({
          imports: [
            VueRouterAutoImports,
            {
              'unplugin-vue-router/runtime': ['definePage'],
            },
          ],
          eslintrc: {
            enabled: true,
            filepath: './.eslintrc-auto-import.json',
            globalsPropValue: true,
          },
        }),
      )
    },
  },


  html: {
    template: './index.html',
    mountId: 'app',
  },

  output: {
    sourceMap: true,
    minify: false,
    distPath: {
      root: 'dist',
      js: 'assets/js',
      css: 'assets/css',
    },
  },
})

```

**Comment by tmg0** [comment]
So, does this issue only occur when the `definePage` keyword is used in the project?

I have reproduced this issue locally, and it seems to be caused by the `definePage` keyword.

`unplugin-vue-router` seems generate a sfc file with tsx lang like:

```vue
// src/pages/about.vue?definePage&vue&lang.tsx

export default {
  meta: {
    title: 'Home',
  },
}
```

And the conent is invalidate caused this error (I guess).

Maybe we could open another issue to describe this problem.
