### ISSUE TITLE
[Bug]: resolve.alias.set('core-js','path')  in rspack 1.0 throw error

### ISSUE THREAD

**Issue by ckken** [web-infra-dev/rspack#7795]
### System Info

  System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 434.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.1.17 - ~/.bun/bin/bun
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6

### Details

The error occurs when setting chain.resolve.alias.set('core-js', this.coreJs.alias) in rspack 1.0, while versions after 0.7 do not have this issue.

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/7ac8fc7d-86b7-4582-b8f2-8c33c37a5998">

I suspect that different versions of core-js are causing the issue, but it runs normally after downgrading rspack.

### Reproduce Steps

pnpm dev

**Comment by ckken** [comment]
the problem is https://github.com/ant-design/ant-design/issues/16852 and work in rspack@0.7.0

**Comment by ckken** [comment]
https://github.com/empjs/rspack-q-and-A/blob/e1f2e069f1ec16147def5bdd83427d6fecb0e137/packages/multi-corejs-version-error/package.json#L11 fixed it and update coreJS

**Comment by chenjiahan** [comment]
I think the behavior of Rspack 1.0 is the same as webpack. When you need to use both core-js v2 and v3, you should not configure a global alias for core-js, which will break the module resolution of core-js v2.

Configuring `alias` in the `rule.resolve.alias` can avoid this issue: https://rspack.dev/config/module#ruleresolve
