### ISSUE TITLE
[Feature]: Standardize the type of the `request` property in the dependencies

### ISSUE THREAD

**Issue by shulaoda** [web-infra-dev/rspack#7797]
### Description
I noticed that in some Dependencies, the types of requests are not consistent, some use `String` while others use `Atom`. What is the best choice? @h-a-n-a cc

https://github.com/web-infra-dev/rspack/blob/b7026816e11e781bbe92ad65fef2ed0e5a200163/crates/rspack_plugin_javascript/src/dependency/esm/import_eager_dependency.rs#L13-L21

https://github.com/web-infra-dev/rspack/blob/b7026816e11e781bbe92ad65fef2ed0e5a200163/crates/rspack_core/src/dependency/entry.rs#L7-L14

**Comment by h-a-n-a** [comment]
This is probably related to the whole repo. I cannot make a quick conclusion at the moment. Let's make sure we are on the same page and provide as much information as possible before discussing this.

Some resources:
- https://github.com/rolldown/rolldown/issues/427
- https://kdy1.dev/2023-10-14-a-journey-towards-a-proper-string-type
- https://fasterthanli.me/articles/small-strings-in-rust

**Comment by shulaoda** [comment]
> Will get back to you soon as soon as I have some idea.

Thanks for your clarification！

**Comment by hardfist** [comment]
I think we should at least use `Request` new type to unify request usage first
```
Struct Request(Atom);
```

**Comment by hardfist** [comment]
seems resolved in other mr
