### ISSUE TITLE
[Bug]: css syntax lowering functionality fails when builtin:lightningcss-loader + css-loader + postcss-loader are used together

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#7798]
### System Info

  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 216.27 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.15.8 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.5

### Details

启用 postcss-loader 后 css 降级功能不生效 （css degradation does not work when postcss-loader is enabled）
**启用 (enabled)**
![image](https://github.com/user-attachments/assets/eb8d4d89-aba0-4253-b777-325fedcfd6fb)
**关闭 (disable)**
![image](https://github.com/user-attachments/assets/5e848202-d5d7-4dd9-b3b3-072efa773973)
配置 (rspack config)
<img width="643" alt="image" src="https://github.com/user-attachments/assets/a9fdd897-c691-4cdc-9bd6-a083d7350d9f">

### Reproduce Steps

[rspack-project.zip](https://github.com/user-attachments/files/16869458/rspack-project.zip) 最小复现

pnpm install
pnpm build

**Comment by h-a-n-a** [comment]
Related https://github.com/web-infra-dev/rspack/issues/7819
