### ISSUE TITLE
[Bug]: esm default import loss ts type

### ISSUE THREAD

**Issue by nuintun** [web-infra-dev/rspack#7806]
### System Info

System: Win11
Version: 1.0.3
Node: 22.8.0

### Details

 esm default import loss ts type

![image](https://github.com/user-attachments/assets/2a362e66-cef5-4374-ab7f-c4c8a9a0bc7c)
![image](https://github.com/user-attachments/assets/2d221e63-012a-4ef5-896f-720d8c87edff)

### Reproduce Steps

Use default import in ts

**Comment by h-a-n-a** [comment]
This is not related to rspack.

Turn on `esModuleInterop` or `allowSyntheticDefaultImports` in tsconfig and try again.

**Comment by nuintun** [comment]
> This is not related to rspack.[ 重试    错误原因 ](javascript:void(0))
> 
> Turn on `esModuleInterop` or `allowSyntheticDefaultImports` in tsconfig and try again.

Not working !
