### ISSUE TITLE
[Bug]: about lightningcss minimizer, which could cause the difference about dev & prod env

### ISSUE THREAD

**Issue by ja-plus** [web-infra-dev/rspack#7813]
### System Info

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
    Memory: 1.07 GB / 7.99 GB
  Binaries:
    Node: 18.16.0 - D:\ThsSoftware\nodejs1816_ths\ths\node.EXE
    Yarn: 1.22.22 - D:\ThsSoftware\nodejs1816_ths\ths\yarn.CMD
    npm: 8.19.4 - D:\ThsSoftware\nodejs1816_ths\ths\npm.CMD
    pnpm: 8.11.0 - D:\ThsSoftware\nodejs1816_ths\ths\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (128.0.2739.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rspack/cli: ^1.0.3 => 1.0.3
    @rspack/core: ^1.0.3 => 1.0.3

### Details

The lightingcss will minimize the code, and the targets config not take effetc.

### Example 
```
.test {
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```
to
```
.test {
  inset: 0;
}
```

The `inset` can not be used in chrome < 87

I've tried the `targets` config but not worked

```
new rspack.LightningCssMinimizerRspackPlugin({
   minimizerOptions: {
     targets: 'chrome 49',
    },
}),
```

### Reproduce Steps

prepare a css

### style.css
```
.test-css-minimize{
  top: 0;
  left:0;
  right:0;
  bottom:0;
}
```

### main.js
```
import './style.css';
```

### rspack.config.js
```
optimization: {
    minimizer: [
      new rspack.LightningCssMinimizerRspackPlugin({
        minimizerOptions: {
          targets: 'chrome 84',
        },
      }),
    ],
  },
```

npm run build

### result:
![图片](https://github.com/user-attachments/assets/a75c87dc-4271-44e2-94d4-815b51b95288)

please take back `rspack.SwcCssMinimizerRspackPlugin`

**Comment by ja-plus** [comment]
the lightning css worked correct
```
"lightningcss": "^1.26.0"
```
main.js:
```
import { transform } from 'lightningcss';
import fs from 'fs';

let { code, map } = transform({
  filename: 'style.css',
  code: fs.readFileSync('style.css'),
  minify: true,
  sourceMap: true,
  targets: {
    chrome: 84, // the target config take effect
  },
});
console.log(code.toString());
```

**Comment by SoonIter** [comment]
https://github.com/web-infra-dev/rspack/pull/7811

**Comment by noshower** [comment]
You can temporarily use this configuration to resolve the issue.
```
 minimizerOptions: {
         targets: 'chrome 84',
         // empty object
         exclude: {}
 },
```

**Comment by chenjiahan** [comment]
Fixed by https://github.com/web-infra-dev/rspack/pull/7811
