### ISSUE TITLE
[Bug]: CSS Module Scripts not working

### ISSUE THREAD

**Issue by faga295** [web-infra-dev/rspack#7827]
### System Info

System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 66.33 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.local/state/fnm_multishells/1512_1725602435429/bin/node
    Yarn: 1.22.22 - ~/.local/state/fnm_multishells/1512_1725602435429/bin/yarn
    npm: 10.8.2 - ~/.local/state/fnm_multishells/1512_1725602435429/bin/npm
    pnpm: 9.3.0 - ~/.local/state/fnm_multishells/1512_1725602435429/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.4
  npmPackages:
    @rspack/cli: workspace:* => 1.0.0

### Details

I found that [CSS module scripts](https://web.dev/articles/css-module-scripts) is supported in the announcement of Rspack 1.0, but it seems they are not working as expected

<img width="949" alt="image" src="https://github.com/user-attachments/assets/b5cf5248-1659-486d-9396-bcbf5d0006c0">
<img width="845" alt="image" src="https://github.com/user-attachments/assets/05713996-2463-4151-b0d6-c6bb36c444a1">

### Reproduce link

https://github.com/faga295/rspack-reproduce/tree/css-module-scripts

### Reproduce Steps

npm run build

**Comment by SoonIter** [comment]
Cannot resolve **styles.css**, because your filename is "style.css" 😂

**Comment by faga295** [comment]
> Cannot resolve **styles.css**, because your filename is "style.css" 😂

updated

**Comment by SoonIter** [comment]
>  ```
>       // Parser options for CSS modules
>       css: {
>         namedExports: true,
>       },
>       // Parser options for css/auto modules
>       'css/auto': {
>         namedExports: true,
>       },
>       // Parser options for css/module modules
>       'css/module': {
>         namedExports: true,
>       },
> ```

https://rspack.dev/config/module#moduleparser

> css/auto: Automatically determines whether a file is a normal CSS file or CSS Modules based on the file extension. Files ending with *.module.css are treated as CSS Modules.

https://rspack.dev/guide/tech/css#native-css-support


you can rename **styles.css** to **styles.module.css**, and turn "namedExports" to false

**Comment by faga295** [comment]
Maybe some misunderstanding about [css-module-scripts](https://web.dev/articles/css-module-scripts)

**Comment by hardfist** [comment]
@faga295  https://github.com/webpack-contrib/css-loader#exporttype css module script can only be used by css-loader

**Comment by faga295** [comment]
Okay, just curious whether Rspack supports this feature

**Comment by SoonIter** [comment]
So should we close this issue? @faga295

**Comment by faga295** [comment]
Okay, any related questions please see #5340
