### ISSUE TITLE
[Bug]: "Message: should have dependency id"

### ISSUE THREAD

**Issue by ipseonet** [web-infra-dev/rspack#7831]
### System Info

 System:
    OS: Linux Debian Bookworm
    CPU: x64 13th Gen Intel(R) Core(TM)
    Container: Yes
    Shell: 5.2.15 
  Binaries:
    Node: 21.7.0 
    Yarn: 1.22.22 
    npm: 10.8.2 
    pnpm: 9.9.0 
  Browsers:
    Chromium

### Details

Tried to run an app with NodeJS and got this error.

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have dependency id
Location: crates/rspack_plugin_javascript/src/dependency/context/require_context_dependency.rs:108

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<empty backtrace>

### Reproduce Steps

npm start

**Comment by GiveMe-A-Name** [comment]
Can you give us a demo repository to reproduce it?

**Comment by ipseonet** [comment]
> Can you give us a demo repository to reproduce it?

I am unsure of what is was but i am not experiencing this error anymore

**Comment by GiveMe-A-Name** [comment]
> > Can you give us a demo repository to reproduce it?
> 
> I am unsure of what is was but i am not experiencing this error anymore

Got it, I closed this issues firstly. 
You can open other issues,  If you meet it again.
