### ISSUE TITLE
[Feature]: DefinePlugin support `__webpack_layer__`

### ISSUE THREAD

**Issue by luhc228** [web-infra-dev/rspack#7848]
### What problem does this feature solve?

Webpack supports [`__webpack_layer__`](https://github.com/webpack/webpack/blob/277460b33bcc49c51acbbcd688672aa4ec685732/lib/APIPlugin.js#L243) and it will be replaced with the value of `entry.layer`. But now Rspack doesn't support it.

### What does the proposed API of configuration look like?

```js
// webpack.config.js
module.exports = {
  entry: {
    catalog: {
      import: './catalog.js',
      layer: 'main'
    }
  },
  plugins: [
     new rspack.DefinePlugin({
      __RUNTIME_TYPE__: '__webpack_layer__'
    }) 
  ]
}
```

**Comment by chenjiahan** [comment]
@h-a-n-a Can you evaluate whether this feature can be supported?

**Comment by LingyuCoder** [comment]
Rspack has supported layer it in https://github.com/web-infra-dev/rspack/pull/7330.

However, if a variable is transformed into __webpack_layer__ through `DefinePlugin`, it will not be further transformed. This behavior is consistent with webpack. 

This means that the code below:

```js
console.log(__RUNTIME_TYPE__);
console.log(__webpack_layer__);
```

will be transform to 

```js
console.log(__webpack_layer__);
console.log("main");
```

I will close this issue as completed. If you meet any question, just reopen it.

**Comment by luhc228** [comment]
It seems that it doesn't work as expected. 

I have created a [demo](https://github.com/luhc228/webpack-layer-repo). You can run `npm run build:webpack` and `npm run build:rspack` to see the output.

**Comment by h-a-n-a** [comment]
@LingyuCoder Would you please to check this?

**Comment by LingyuCoder** [comment]
> It seems that it doesn't work as expected.
> 
> I have created a [demo](https://github.com/luhc228/webpack-layer-repo). You can run `npm run build:webpack` and `npm run build:rspack` to see the output.

Found where the trick is, webpack will only compute the compile time evaluation result of `__webpack_layer__` which is generated from `DefinePlugin`. So if the code like

```js
const condexp = (
  __RUNTIME_TYPE__ === 'main' ? 'onLifecycleEvent' : 'onLifecycleEvent2');

const cond = __RUNTIME_TYPE__ === 'main';

console.log(__RUNTIME_TYPE__);
```

will be converted to

```js
const condexp = (
   false ? 0 : 'onLifecycleEvent2');

const cond = __webpack_layer__ === 'main';

console.log(__webpack_layer__);
```

**Comment by inottn** [comment]
It doesn't seem related to the implementation of DefinePlugin, can I try to fix it? 🤔

**Comment by luhc228** [comment]
> It doesn't seem related to the implementation of DefinePlugin, can I try to fix it? 🤔

LGTM～Thanks! @inottn
