### ISSUE TITLE
[Bug]: build uses latest branch code instead of specified commit in ci/cd

### ISSUE THREAD

**Issue by shulaoda** [web-infra-dev/rspack#7850]
### Details

Related to #7757

In fact, the actual modification of trait `Dependency` is made in the latest main branch, not the branch where the build is located.

```bash
   Compiling rspack_plugin_javascript v0.1.0 (/build/crates/rspack_plugin_javascript)
error[E0407]: method `span` is not a member of trait `Dependency`
  --> crates/rspack_plugin_javascript/src/dependency/context/require_resolve_context_dependency.rs:45:3
   |
45 | /   fn span(&self) -> Option<ErrorSpan> {
46 | |     Some(ErrorSpan::new(self.range.start, self.range.end))
47 | |   }
   | |___^ not a member of trait `Dependency`
```

**Comment by shulaoda** [comment]
You can create a new branch based on the commit history prior to commit `f19562` to reproduce the issue.

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/87b9ff9d-3396-40aa-a3ce-e3080a969cae">

**Comment by SoonIter** [comment]
I used to be troubled by this problem too... 😂
Can I see the specific wrong github action link?

**Comment by shulaoda** [comment]
> I used to be troubled by this problem too... 😂 Can I see the specific wrong github action link?

At present, only `Action` records are available, and the `PR` has been updated.

https://github.com/web-infra-dev/rspack/actions/runs/10786518541/job/29913523550

**Comment by SoonIter** [comment]
It is relatively difficult to locate the problem, which may be due to the following reasons

1. checkout action bug (I checked the commit hash, it is fine)
2. ci status is dirty (only in self-hosted machine)
3. cargo cache

Wait for the next time repro.
