### ISSUE TITLE
[Bug]: Vue style loss since Rspack v1.0.4

### ISSUE THREAD

**Issue by ritilyn1991** [web-infra-dev/rspack#7869]
### Version

```sh
System:
OS: macOS sonoma 14.6.1
Binaries:
Node: 18.20.4 - /usr/local/bin/node
npm: 10.7.0 - /usr/local/bin/npm
Browsers:
Chrome: 128.0.6613.120
npmPackages:
@rspack/core: 1.0.2
```

### Details

When I used @rspack/core@1.0.2, the page style of vue3 was lost (each page was loaded asynchronously). When I rolled back the version to 1.0.1-beta.13, everything was normal

### Reproduce link

No response

### Reproduce Steps

rsbuild dev

**Comment by chenjiahan** [comment]
Related to https://github.com/web-infra-dev/rspack/pull/7846

We will release a new version to fix this issue soon.

**Comment by beliefgp** [comment]
When will it be released?

**Comment by chenjiahan** [comment]
Today

**Comment by chenjiahan** [comment]
Fixed in:

- https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.3
- https://github.com/web-infra-dev/rspack/releases/tag/v1.0.5
