### ISSUE TITLE
[Bug]: 我在 vue-cli迁移到 rsbuild的时候    The export "MiniMap" in "./node_modules/@ant-design/icons-vue/es/utils.js" has no internal name (existing names: )

### ISSUE THREAD

**Issue by ZhangHaiyangYang** [web-infra-dev/rspack#7873]
### System Info

 window11  node 16.15.0

### Details

![image](https://github.com/user-attachments/assets/ac991018-d524-4054-ba26-ca1be35c671e)

### Reproduce Steps

暂无

**Comment by ZhangHaiyangYang** [comment]
你好 能看出来是哪里出问题了吗  用的是"ant-design-vue": "1.7.3",

**Comment by h-a-n-a** [comment]
Please provide a reproducible demo and reopen this issue.
