### ISSUE TITLE
[Bug]: @rspack/cli does not support node v16

### ISSUE THREAD

**Issue by deanveloper** [web-infra-dev/rspack#7884]
### System Info

  System:
    OS: macOS 14.6.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 7.08 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.local/state/fnm_multishells/3886_1724698272462/bin/node
    npm: 8.11.0 - ~/.local/state/fnm_multishells/3886_1724698272462/bin/npm
  Browsers:
    Chrome: 128.0.6613.85
    Safari: 17.6
  npmPackages:
    @rspack/core: ^1.0.4 => 1.0.4

### Details

When I was experimenting with upgrading from webpack to rspack, I was expecting things to be seamless, however the node installation that we currently use for our development environment is 16.15.1. I was expecting this to be fine since the [Rspack Quickstart](https://rspack.dev/guide/start/quick-start) details that the minimum required version for node is `>= 16`. While this seems to be true for `@rspack/core`, but minimum required version for `@rspack/cli` is `>= 18.12.0`.

I do see this documented at [Migrating from rspack 0.x](https://rspack.dev/guide/migration/rspack_0.x#important-rspackcli), however this article isn't relevant to what I'm currently doing since I'm not migrating from rspack 0.x, I'm migrating from webpack 5.x.

It might be good to both change the versions specified in the [Quick Start](https://rspack.dev/guide/start/quick-start), and possibly specifying the `webpack-cli` and `webpack-dev-server` versions in the [Migrate from Webpack](https://rspack.dev/guide/migration/webpack) guide.

(Note that I was migrating from the following webpack dependencies)
- "webpack": "5.78.0"
- "webpack-cli": "4.10.0"
- "webpack-dev-server": "4.9.0"

### Reproduce Steps

1. Install node `v16.15.1` and npm `8.11.0`
2. `npm add @rspack/cli@1.0.0 -D`

Expected: successful install
Actual: EBADENGINE, required node version `>= 18.12.0` because of a dependency on `webpack-dev-middleware@7.4.2`

**Comment by SoonIter** [comment]
The best way is to upgrade node to version 18. node version 16 is no longer maintained.

As for `@rspack/dev-server`, a workaround is to use `npm.overrides` to pin the version of `webpack-dev-server@4` and `webpack-dev-middleware@7`

The relevant documents like `QuickStart` need to be updated. Maybe we need to change the recommended version to node18 @chenjiahan cc

**Comment by chenjiahan** [comment]
Given that more and more third-party dependencies are deprecating Node 16,  I recommend upgrading to Node 18 rather than trying to find a workaround.

@SoonIter  we can update Rspack's quickstart documentation to clarify the Node version requirement.

**Comment by chenjiahan** [comment]
Note that Rsbuild still supports Node 16 as it does not depend on webpack-dev-server.

https://github.com/web-infra-dev/rsbuild

**Comment by deanveloper** [comment]
> The best way is to upgrade node to version 18. node version 16 is no longer maintained... :D

Yup! We're taking steps to upgrade node atm, wasn't asking for any workarounds or anything! Unfortunately its just a long process to do that. Just wanted to point out that the documentation probably needs to be updated :)

**Comment by deanveloper** [comment]
> Note that Rsbuild still supports Node 16 as it does not depend on webpack-dev-server.
> 
> https://github.com/web-infra-dev/rsbuild

Unfortunately (if I understand the ecosystem correctly) this won't work for us. We don't have the time for anything that is much more than a drop-in replacement, and we rely on webpack's CLI devtools.

**Comment by SoonIter** [comment]
document has been updated：）
