### ISSUE TITLE
[Bug]: experiments.css=true  css loader repeated execute

### ISSUE THREAD

**Issue by beliefgp** [web-infra-dev/rspack#7889]
### System Info

 System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 94.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
    pnpm: 8.15.9 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.5

### Details

use rsbuild  @rsbuild/plugin-vue  @rsbuild/plugin-less

when experiments.css=false is  ok

when experiments.css=true throw error

File: /src/views/test/index.vue?vue&type=style&index=0&id=f10f9558&lang=less&scoped=true:1:1
  × Module parse failed:
  ╰─▶   × JavaScript parsing error: Expression expected
         ╭────
       1 │ /* unplugin-vue-components disabled */@import "./index.vue.less?vue&type=style&index=0&id=f10f9558&lang=less&scoped=true!=!-!../../../../../node_modules/vue-loader/dist/stylePostLoader.js!../../../../../node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!../../../../../node_modules/@rspack/core/dist/builtin-plugin/css-extract/loader.js!../../../../../node_modules/@rsbuild/core/compiled/css-loader/index.js??clonedRuleSet-25.use[1]!builtin:lightningcss-loader??clonedRuleSet-25.use[2]!../../../../../node_modules/@rsbuild/plugin-less/compiled/less-loader/index.js??clonedRuleSet-25.use[3]!../../../../../node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./index.vue?vue&type=style&index=0&id=f10f9558&lang=less&scoped=true";
         ·                                       ─
         ╰────
      
  help: 
        File was processed with these loaders:
         * commonjs|test/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components
         * commonjs|test/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components
         * test/node_modules/vue-loader/dist/pitcher.js??ruleSet[1].rules[0].use[0]
         * 
         * test/node_modules/@rspack/core/dist/builtin-plugin/css-extract/loader.js
         * commonjs|test/node_modules/@rsbuild/core/compiled/css-loader/index.js??clonedRuleSet-25.use[1]
         * builtin:lightningcss-loader??clonedRuleSet-25.use[2]
         * commonjs|test/node_modules/@rsbuild/plugin-less/compiled/less-loader/index.js??clonedRuleSet-25.use[3]
         * 
         * test/node_modules/@rspack/core/dist/builtin-plugin/css-extract/loader.js
         * commonjs|test/node_modules/@rsbuild/core/compiled/css-loader/index.js??clonedRuleSet-25.use[1]
         * builtin:lightningcss-loader??clonedRuleSet-25.use[2]
         * commonjs|test/node_modules/@rsbuild/plugin-less/compiled/less-loader/index.js??clonedRuleSet-25.use[3]
         * 
         * test/node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]
        You may need an additional loader to handle the result of these loaders.

### Reproduce Steps

rsbuild build

**Comment by JSerFeng** [comment]
if you want to use `experiments.css` and css-loader together, make sure mark the module correct moduleType.

If you want to use `experiments.css` for certain module, mark it moduleType as 'css/auto'

```
module.exports = {
  module: { rules: [{ test: /foo\.css/, type: 'css/auto' }] }
}
```

otherwise you should set type to 'javascript' **explicitly**

**Comment by beliefgp** [comment]
this is  rsbuild config error ?

**Comment by beliefgp** [comment]
I tested it and it seems to be related to vue-loader
