### ISSUE TITLE
[Bug]: rsbuild fails to compile with compression-webpack-plugin

### ISSUE THREAD

**Issue by madiyetov** [web-infra-dev/rspack#7891]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 97.76 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
```

### Details

The `rsbuild dev` command run fails with `[webpack-dev-middleware] [Error:   × HookWebpackError: A Source-like object with a 'map' method must also provide an 'updateHash' method` error if I add `compression-webpack-plugin` plugin.

### Reproduce link

https://github.com/madiyetov/rspack-issue-repro

### Reproduce Steps

added in the README file

**Comment by 9aoy** [comment]
@SyMind Looks like we need to implement updateHash method for rspack `source.compatSource`.
![ff7e2a19-9331-47e6-8f1d-8df4b8ba2207](https://github.com/user-attachments/assets/7eec6079-0c9e-4263-aedf-94b29c2065fb)

<img width="775" alt="image" src="https://github.com/user-attachments/assets/842b4447-ed78-48ba-8350-9f1d37dfe556">
