### ISSUE TITLE
[Bug]:  rsbuld build failed  “Cannot find module '@rspack/binding-linux-x64-gnu' ”

### ISSUE THREAD

**Issue by daisy908** [web-infra-dev/rspack#7893]
### System Info

node v16.20.2
npm 8.19.4
systemOs: linux-x64 macOs

### Details

![20240913-162249](https://github.com/user-attachments/assets/0336222d-a24a-4dee-88af-0c5618699dfd)

lock  文件中的依赖没有自动安装，造成打包时缺少依赖
optionalDependencies:
    "@rspack/binding-darwin-arm64" "1.0.0"
    "@rspack/binding-darwin-x64" "1.0.0"
    "@rspack/binding-linux-arm64-gnu" "1.0.0"
    "@rspack/binding-linux-arm64-musl" "1.0.0"
    "@rspack/binding-linux-x64-gnu" "1.0.0"
    "@rspack/binding-linux-x64-musl" "1.0.0"
    "@rspack/binding-win32-arm64-msvc" "1.0.0"
    "@rspack/binding-win32-ia32-msvc" "1.0.0"
    "@rspack/binding-win32-x64-msvc" "1.0.0"

### Reproduce Steps

1、npm i
2、rsbuild build 或者 sbuild dev 报错

**Comment by zhangmingyuan666** [comment]
Same question.

I had removed these code in package-lock.json. then we met same question
```json
"@rspack/binding-darwin-arm64": "0.7.5",
        "@rspack/binding-darwin-x64": "0.7.5",
        "@rspack/binding-linux-arm64-gnu": "0.7.5",
        "@rspack/binding-linux-arm64-musl": "0.7.5",
        "@rspack/binding-linux-x64-gnu": "0.7.5",
        "@rspack/binding-linux-x64-musl": "0.7.5",
        "@rspack/binding-win32-arm64-msvc": "0.7.5",
        "@rspack/binding-win32-ia32-msvc": "0.7.5",
        "@rspack/binding-win32-x64-msvc": "0.7.5"
```

**Comment by chenjiahan** [comment]
This is usually a problem with the package manager, you can try to fix it by deleting the node_modules and reinstalling the dependencies.

If that doesn't work, try clearing your package manager cache, or using pnpm.

**Comment by Zhakkz** [comment]
Same error (deleting the node_modules and reinstalling the dependencies didn't help)

**Comment by juilletVent** [comment]
I had the same problem.

1. I deleted and reinstalled all dependencies
2. I deleted the pnpm cache
3. I deleted the lock file

Then I tried to reinstall, but the problem persisted. This problem seems to have started with version 1.1.4. After rolling back the version of @rspack/core to 1.1.3, the problem was solved

I checked the description of @rspack/binding in the Lock file. In version 1.1.3, it is as follows:

```
'@rspack/binding@1.1.3':
    optionalDependencies:
      '@rspack/binding-darwin-arm64': 1.1.3
      '@rspack/binding-darwin-x64': 1.1.3
      '@rspack/binding-linux-arm64-gnu': 1.1.3
      '@rspack/binding-linux-arm64-musl': 1.1.3
      '@rspack/binding-linux-x64-gnu': 1.1.3
      '@rspack/binding-linux-x64-musl': 1.1.3
      '@rspack/binding-win32-arm64-msvc': 1.1.3
      '@rspack/binding-win32-ia32-msvc': 1.1.3 '@rspack/binding-win32-x64-msvc': 1.1.3
```
But in 1.1.4 it is like this:
```
  '@rspack/binding@1.1.4': {}

  '@rspack/core@1.1.4':
    dependencies:
      '@module-federation/runtime-tools': 0.5.1
      '@rspack/binding': 1.1.4
      '@rspack/lite-tapable': 1.0.1
      caniuse-lite: 1.0.30001684
```
My attempts were all carried out in a clean environment, this may be a BUG

**Comment by emma-sg** [comment]
I encountered the same issue in Docker with yarn, the underlying issue is that I was running `yarn install` with the `--ignore-optional` flag, which was preventing the platform-specific packages from being installed. Removing this flag fixed the issue.

**Comment by JonBlauvelt** [comment]
In my case, building locally on a different architecture removed all the package-lock.json entries with the optional bindings that were not needed for my local setup which broke the linux build.  I was able to mitigate this by adding back the missing linux binding to the package-lock.json:
```
    "node_modules/@rspack/binding-linux-x64-gnu": {
      "version": "1.3.12",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ]
   },
```
