### ISSUE TITLE
[Bug]: BannerPlugin not working with the default stage PROCESS_ASSETS_STAGE_ADDITIONS 

### ISSUE THREAD

**Issue by DiegoSerra** [web-infra-dev/rspack#7898]
### System Info

System:
    OS: Windows 10 10.0.19045
Binaries:
    Node: 18.17.1
    npm: 6.14.4

### Details

BannerPlugin only work for stage from PROCESS_ASSETS_STAGE_DEV_TOOLING (500 and onwards) instead of the default stage PROCESS_ASSETS_STAGE_ADDITIONS which is when you ‘Add additional sections to existing assets, like a banner or initialization code‘

![image](https://github.com/user-attachments/assets/ece93f0e-5d46-46a2-bd43-7d83d4fc2a31)

**Default stage _rspack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONS_** 
![image](https://github.com/user-attachments/assets/07cc2614-a7c2-4b41-bf22-0410a0a663cb)

**Stage _rspack.Compilation.PROCESS_ASSETS_STAGE_DEV_TOOLING_**
![image](https://github.com/user-attachments/assets/54faf4e3-c0d2-46d0-b54a-af1bc69ce5e1)

### Reproduce link

https://codesandbox.io/p/github/DiegoSerra/rspack-project/master?import=true

### Reproduce Steps

1 - `npm create rspack@latest`

2 - modifying the `rspack.config.mjs` file and adding to the list of plugins:
```
new rspack.BannerPlugin({
   banner: 'hello world',
   footer: true,
   // stage: rspack.Compilation.PROCESS_ASSETS_STAGE_DEV_TOOLING
})
```

3 - `npm run build`

**Comment by hardfist** [comment]
the default stage not working is caused by the minifier remove the added banner, if you disable the minimize you can see the added banner.
```js
optimization: {
  minimize:false
}
```
and since it's same as webpack, I don't think it's a bug
