### ISSUE TITLE
[Bug]: Some links on the built with rspack sections dont work on mobile

### ISSUE THREAD

**Issue by yharaskrik** [web-infra-dev/rspack#7905]
### System Info

Chrome - mobile (both on a Pixel 7 + Chrome on desktop in mobile mode)

### Details

In the Built with rspack section on rspack.dev only some links open on mobile (although they all work in desktop size)

For example:

Trellis and Sequoia do not open on mobile but do on desktop
Microsoft opens on both.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/bed9e6fb-6c51-48e9-8a87-921712c9dfea">

### Reproduce link

rspack.dev

### Reproduce Steps

1. Go to rspack dev on a mobile phone or chrome in mobile mode on desktop
2. Try and link the trellis logo

**Comment by nilptr** [comment]
It's blocked by the pseudo-element used to implement the border effect.
