### ISSUE TITLE
[Bug]: When using a web worker with lazyCompilation enabled, a compilation error occurs.

### ISSUE THREAD

**Issue by wendy0512** [web-infra-dev/rspack#7962]
### Version

```sh
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
    Memory: 12.17 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)  
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rsbuild/core: ^1.0.4 => 1.0.4 
    @rsbuild/plugin-less: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-react: ^1.0.2 => 1.0.2 
    @rsbuild/plugin-styled-components: ^1.0.1 => 1.0.1
```

### Details

1.Create a worker example, as shown in the reproduction repository.
2.Enable dev: { lazyCompilation: true }, and open the page link. The following error appears in the compiler console:
![image](https://github.com/user-attachments/assets/a557788d-b560-4935-bf6f-28066f5ad48a)
3.If dev: { lazyCompilation: true } is disabled, the page runs normally, as shown below:
![image](https://github.com/user-attachments/assets/58632e8c-5d39-4fd0-bd17-4d55864dca3c)

### Reproduce link

https://github.com/wendy0512/rsbuild-worker-repro

### Reproduce Steps

1. npm i
2. npm start

**Comment by wendy0512** [comment]
"As of version 1.014, I'm still encountering errors during runtime. Could you please help me look into this bug?" @JSerFeng

**Comment by JSerFeng** [comment]
Sorry for the delay, I checked the repro, turned out it was a HMR bug for both Rspack and webpack, I'm fixing it but it was tricky, I'm working on it

**Comment by JSerFeng** [comment]
For the temporary solution is to disable splitChunks, you can achieve that by config like this

```javascript
defineConfig({
  tools: { rspack(config) {config.optimization.splitChunks = 'false'} }
})
```

**Comment by JSerFeng** [comment]
You can try this version @rspack/core-canary@1.1.0-canary-20200056-20241101043803, should be fine
