### ISSUE TITLE
[Bug]: Missing typings for `externals` function (zod types not inferred correctly)

### ISSUE THREAD

**Issue by ecraig12345** [web-infra-dev/rspack#7979]
### System Info

`@rspack/core` version: 1.0.7
TypeScript version: 5.5.4

(other system info is irrelevant because this is a typescript problem)

### Details

I was trying to use an `externals` function in a configuration, and TS can't infer the proper argument types or return type based on the generated zod types for `Externals`.

I ended up manually writing the type `(ctx: ExternalItemFunctionData) => Promise<ExternalItemValue | undefined>` based on looking at the [source code](https://github.com/web-infra-dev/rspack/blob/5fd46efd67b7ebc8fdadeafc6a6b19c3eec92878/packages/rspack/src/config/zod.ts#L942). But it would be better if the typings would work properly without any extra work. 

(The `undefined` return is also missing from the zod types, and that seems to be the way to indicate that an item shouldn't be externalized?)

### Reproduce Steps

Make a TS file with the following contents and observe the errors.

```ts
import type { Configuration, ExternalItem } from '@rspack/core';

const config: Configuration = {
  externals:
    // `ctx` type and return type are any
    async (ctx) => {
      // `ctx` type is any, so `ctx.request` type is missing
      if (ctx.request?.includes('foo')) {
        return ctx.request;
      }
    },
};

type ExternalsFunction1 = Extract<ExternalItem, (ctx: Object) => Promise<unknown>>;
// `ctx` has a type, but there's an error that undefined is not a valid return value
const externals1: ExternalsFunction1 = async (ctx) => {
  if (ctx.request?.includes('foo')) {
    return ctx.request;
  }
  return;
};

// I couldn't get the types for the callback version to be inferred at all.
// `ctx` arg type is correct, other args get typed as `...arg1: unknown[]`
type ExternalsFunction2 = Extract<ExternalItem, (ctx: Object, callback: Function) => void>;
// also there's the error again that undefined is not a valid return value
const externals2: ExternalsFunction2 = (ctx, callback) => {
  if (ctx.request?.includes('foo')) {
    // unknown type
    callback(ctx.request);
  }
  callback();
};
```

**Comment by GiveMe-A-Name** [comment]
> ```ts
> const config: Configuration = {
>   externals:
>      // `ctx` type and return type are any
>     async (ctx) => {
>       // `ctx` type is any, so `ctx.request` type is missing
>       if (ctx.request?.includes('foo')) {
>         return ctx.request;
>       }
>     },
> };
> 
> // I couldn't get the types for the callback version to be inferred at all.
> // `ctx` arg type is correct, other args get typed as `...arg1: unknown[]`
> type ExternalsFunction2 = Extract<ExternalItem, (ctx: Object, callback: Function) => void>;
> // also there's the error again that undefined is not a valid return value
> const externals2: ExternalsFunction2 = (ctx, callback) => {
>   if (ctx.request?.includes('foo')) {
>     // unknown type
>    callback(ctx.request);
>   }
>   callback();
> };
> 
> ```

Zod will add ...args: unknown[] to function type by default, like the code bellow

```ts
import { z } from "zod";

const myFunction = z.function().returns(z.string());

// MyFunction1 type is (...args: unknown[]) => string;
type MyFunction1 = z.infer<typeof myFunction>;

const f1: MyFunction1 = (x1: string) => "";

// Expect type is () => string;
type MyFunction2 = () => string;

const f2: MyFunction2 = () => "";
```

In typescript, types infer is restricted, so `ctx` would be as `any` by ts.

Reference to: https://github.com/colinhacks/zod/issues/3773 

----

> ```ts
> type ExternalsFunction1 = Extract<ExternalItem, (ctx: Object) => Promise<unknown>>;
> // `ctx` has a type, but there's an error that undefined is not a valid return value
> const externals1: ExternalsFunction1 = async (ctx) => {
>   if (ctx.request?.includes('foo')) {
>     return ctx.request;
>   }
>   return;
> };
> ```

According the type define, you should return some instead of `undefined`.
It's same as webpack.

**Comment by GiveMe-A-Name** [comment]
We should need a better way provide the Configuration type.

**Comment by GiveMe-A-Name** [comment]
Yes, you can use callback continue without externalizing the import after we provide better types.
But if you use the type interface `((data: ExternalItemFunctionData) => Promise<ExternalItemValue>)`, you need return a value.
It is same with webpack.

```ts
import type { Externals } from "webpack";

type ExternalsFunction1 = Extract<
  Externals,
  (ctx: Record<string, any>) => Promise<unknown>
>;

// there's an error that undefined is not a valid return value
const externals: ExternalsFunction1 = async (ctx) => {
  if (ctx.request?.includes("foo")) {
    return ctx.request;
  }
  return;
};
```

**Comment by GiveMe-A-Name** [comment]
Fix by https://github.com/web-infra-dev/rspack/pull/8013
