### ISSUE TITLE
[Bug]: [content-hash] changes when building same image twice

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspack#7992]
### System Info

rspack 1.0.7

### Details

same image but different filename

**input**

```
├── assets
│   ├── cover-12.bed026dc.webp       <----- "bed026dc" is the content-hash of this file
│   └── cover-12.webp
```

**output**
```
└── static
    ├── image
    │   ├── cover-12.8960ba75.8960ba75.webp
    │   └── cover-12.8960ba75.webp
```

**expected output**

aligned with webpack

```
└── static
    ├── image
    │   ├── cover-12.bed026dc.bed026dc.webp
    │   └── cover-12.bed026dc.webp
```

<img width="500" alt="image" src="https://github.com/user-attachments/assets/2e7bfff5-58c8-4c9d-b1dc-19ee33231f16">

### Reproduce link

https://github.com/SoonIter/rsbuild-image-compress/tree/chore/new-bug

### Reproduce Steps

1. pnpm install
2. npm run build

**Comment by SoonIter** [comment]
maybe related to https://github.com/web-infra-dev/rspack/pull/7464

**Comment by SoonIter** [comment]
@ahabhgk cc, coulld you take a look 😭

**Comment by inottn** [comment]
It seems unrelated to https://github.com/web-infra-dev/rspack/pull/7464, I'll try to fix it.
