### ISSUE TITLE
[Bug]: The bundles built with rspack has a module in __webpack_require__ that does not exist in __webpack_modules__, causing a code error

### ISSUE THREAD

**Issue by CoderQuixote** [web-infra-dev/rspack#8027]
### System Info

     "vue": "^3.2.13",   
    "@babel/preset-env": "^7.25.3",
    "@rsbuild/core": "^1.0.1-rc.2",
    "@rsbuild/plugin-babel": "^1.0.1-rc.2",
    "@rsbuild/plugin-less": "^1.0.1-rc.2",
    "@rsbuild/plugin-vue": "^1.0.1-rc.2",
    "@rsbuild/plugin-vue-jsx": "^1.0.1-rc.2",
    "@rsdoctor/rspack-plugin": "^0.4.0",
    "@rspack/cli": "^1.0.0"

### Details

利用rspack获批构建的打包产物，存在 __webpack_require__中加载了在 __webpack_modules__不存在的模块导致代码报错

报错信息
buildQuickly.all.min.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (buildQuickly.all.min.js:52:700772)
    at 3580 (buildQuickly.all.min.js:52:59513)
    at __webpack_require__ (buildQuickly.all.min.js:52:700772)
    at buildQuickly.all.min.js:52:743628
    at buildQuickly.all.min.js:56:128664
    at buildQuickly.all.min.js:56:128687
    at buildQuickly.all.min.js:1:201
    at buildQuickly.all.min.js:1:205

---------
 return __webpack_modules__[t].call(n.exports, n, n.exports, __webpack_require__),

### Reproduce Steps

1，npm run build
产物在其他系统中试用

**Comment by CoderQuixote** [comment]
配置如下

const path = require('path');
const rspack = require('@rspack/core');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const {VueLoaderPlugin} = require('vue-loader');
const {RsdoctorRspackPlugin} = require('@rsdoctor/rspack-plugin');

function resolve(moduleName) {
    return require.resolve(moduleName);
}

function assertResolve(dir) {
    return path.join(__dirname, dir);
}

const config = {
    context: __dirname,
    mode: 'production',
    devtool: false,
    target: ['web', 'es5'],
    entry: {
        'buildQuickly.all.umd.min': ['./src/entry.js'],
        'buildQuickly.all.umd': ['./src/entry.js'],
        'buildQuickly.renderEngine.umd.min': ['./src/engineEntry.js'],
        'buildQuickly.renderEngine.umd': ['./src/engineEntry.js']
    },
    output: {
        clean: true,
        filename: '[name].js',
        library: {
            name: 'buildQuickly',
            type: 'umd'
        },
        path: path.resolve(__dirname, 'dist')
    },
    optimization: {
        minimize: true,
        minimizer: [
            new rspack.SwcJsMinimizerRspackPlugin({
                test: /min/,
                minimizerOptions: {
                    format: {
                        comments: false,
                    },
                },
            }),
            new rspack.LightningCssMinimizerRspackPlugin({
                include: /min/,
                minimizerOptions: {
                    errorRecovery: false,
                },
            }),
        ]
    },
    externals: [],
    resolve: {
        modules: ['node_modules', path.join(__dirname, '../node_modules')],
        extensions: [
            '.web.tsx',
            '.web.ts',
            '.web.jsx',
            '.web.js',
            '.ts',
            '.tsx',
            '.js',
            '.jsx',
            '.vue',
            '.md',
            '.json'
        ],
        alias: {
            '@': assertResolve('src'),
            public: assertResolve('public')
        },
        fallback: ['child_process', 'cluster', 'dgram', 'dns', 'fs', 'module', 'net', 'readline', 'repl', 'tls'].reduce(
            (acc, name) => Object.assign({}, acc, {[name]: 'empty'}),
            {}
        )
    },
    plugins: [
        ...(process.env.RSDOCTOR ? [
            new RsdoctorRspackPlugin({
                features: {
                    resolver: true
                },
                supports: {
                    generateTileGraph: true
                },
                port: 120
            })
        ] : []),
        new VueLoaderPlugin(),
        // new rspack.CssExtractRspackPlugin(),
        new CaseSensitivePathsPlugin()],
    experiments: {
        css: true
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'vue-loader',
                        options: {
                            // 注意，为了绝大多数功能的可用性，请确保该选项为 `true`
                            experimentalInlineMatchResource: true
                        }
                    }
                ]
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            // 插件先执行 再执行预设
                            plugins: ['@vue/babel-plugin-jsx'],
                            presets: ['@babel/preset-env']
                        }
                    }
                ]
            },
            // {
            //     test: /\.css$/i,
            //     use: [
            //         rspack.CssExtractRspackPlugin.loader,
            //         'css-loader',
            //         {
            //             loader: 'postcss-loader',
            //             options: {
            //                 postcssOptions: {
            //                     plugins: ['autoprefixer']
            //                 },
            //                 sourceMap: true
            //             }
            //         }
            //     ],
            //     type: 'javascript/auto'
            // },

            {
                test: /\.less$/,
                loader: 'less-loader',
                type: 'css'
            },
            {
                test: /\.svg$/,
                use: ['vue-loader', resolve('./build/loaders/vue-svg-loader.js')]
            }
        ]
    }
};

function externalDep(config) {
    config.externals.push({
        vue: {
            root: 'Vue',
            commonjs2: 'vue',
            commonjs: 'vue',
            amd: 'vue',
            module: 'vue'
        }
    });

    config.externals.push({
        dayjs: {
            root: 'dayjs',
            commonjs2: 'dayjs',
            commonjs: 'dayjs',
            amd: 'dayjs',
            module: 'dayjs'
        }
    });


    config.externals.push(function ({_context, request}, callback) {
        if (/^dayjs\/plugin\//.test(request)) {
            const name = request.replace(/\//g, '_');
            return callback(null, {
                root: name,
                commonjs2: name,
                commonjs: name,
                amd: name,
                module: name
            });
        }
        callback();
    });

    config.externals.push({
        '@xa-web/hua-design-vue3': {
            root: 'huad', // root global variable
            commonjs2: '@xa-web/hua-design-vue3', // module.exports = xxx
            commonjs: '@xa-web/hua-design-vue3', // exports[“Library”] = xxx
            amd: '@xa-web/hua-design-vue3', // define(["xxx"], factory)
            module: '@xa-web/hua-design-vue3'
        }
    });
}

externalDep(config);

module.exports = config;

**Comment by CoderQuixote** [comment]
配置如下
`const path = require('path');
const rspack = require('@rspack/core');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const {VueLoaderPlugin} = require('vue-loader');
const {RsdoctorRspackPlugin} = require('@rsdoctor/rspack-plugin');

function resolve(moduleName) {
    return require.resolve(moduleName);
}

function assertResolve(dir) {
    return path.join(__dirname, dir);
}

const config = {
    context: __dirname,
    mode: 'production',
    devtool: false,
    target: ['web', 'es5'],
    entry: {
        'buildQuickly.all.umd.min': ['./src/entry.js'],
        'buildQuickly.all.umd': ['./src/entry.js'],
        'buildQuickly.renderEngine.umd.min': ['./src/engineEntry.js'],
        'buildQuickly.renderEngine.umd': ['./src/engineEntry.js']
    },
    output: {
        clean: true,
        filename: '[name].js',
        library: {
            name: 'buildQuickly',
            type: 'umd'
        },
        path: path.resolve(__dirname, 'dist')
    },
    optimization: {
        minimize: true,
        minimizer: [
            new rspack.SwcJsMinimizerRspackPlugin({
                test: /min/,
                minimizerOptions: {
                    format: {
                        comments: false,
                    },
                },
            }),
            new rspack.LightningCssMinimizerRspackPlugin({
                include: /min/,
                minimizerOptions: {
                    errorRecovery: false,
                },
            }),
        ]
    },
    externals: [],
    resolve: {
        modules: ['node_modules', path.join(__dirname, '../node_modules')],
        extensions: [
            '.web.tsx',
            '.web.ts',
            '.web.jsx',
            '.web.js',
            '.ts',
            '.tsx',
            '.js',
            '.jsx',
            '.vue',
            '.md',
            '.json'
        ],
        alias: {
            '@': assertResolve('src'),
            public: assertResolve('public')
        },
        fallback: ['child_process', 'cluster', 'dgram', 'dns', 'fs', 'module', 'net', 'readline', 'repl', 'tls'].reduce(
            (acc, name) => Object.assign({}, acc, {[name]: 'empty'}),
            {}
        )
    },
    plugins: [
        ...(process.env.RSDOCTOR ? [
            new RsdoctorRspackPlugin({
                features: {
                    resolver: true
                },
                supports: {
                    generateTileGraph: true
                },
                port: 120
            })
        ] : []),
        new VueLoaderPlugin(),
        // new rspack.CssExtractRspackPlugin(),
        new CaseSensitivePathsPlugin()],
    experiments: {
        css: true
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'vue-loader',
                        options: {
                            // 注意，为了绝大多数功能的可用性，请确保该选项为 `true`
                            experimentalInlineMatchResource: true
                        }
                    }
                ]
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            // 插件先执行 再执行预设
                            plugins: ['@vue/babel-plugin-jsx'],
                            presets: ['@babel/preset-env']
                        }
                    }
                ]
            },
            // {
            //     test: /\.css$/i,
            //     use: [
            //         rspack.CssExtractRspackPlugin.loader,
            //         'css-loader',
            //         {
            //             loader: 'postcss-loader',
            //             options: {
            //                 postcssOptions: {
            //                     plugins: ['autoprefixer']
            //                 },
            //                 sourceMap: true
            //             }
            //         }
            //     ],
            //     type: 'javascript/auto'
            // },

            {
                test: /\.less$/,
                loader: 'less-loader',
                type: 'css'
            },
            {
                test: /\.svg$/,
                use: ['vue-loader', resolve('./build/loaders/vue-svg-loader.js')]
            }
        ]
    }
};

function externalDep(config) {
    config.externals.push({
        vue: {
            root: 'Vue',
            commonjs2: 'vue',
            commonjs: 'vue',
            amd: 'vue',
            module: 'vue'
        }
    });

    config.externals.push({
        dayjs: {
            root: 'dayjs',
            commonjs2: 'dayjs',
            commonjs: 'dayjs',
            amd: 'dayjs',
            module: 'dayjs'
        }
    });


    config.externals.push(function ({_context, request}, callback) {
        if (/^dayjs\/plugin\//.test(request)) {
            const name = request.replace(/\//g, '_');
            return callback(null, {
                root: name,
                commonjs2: name,
                commonjs: name,
                amd: name,
                module: name
            });
        }
        callback();
    });

    config.externals.push({
        '@xa-web/hua-design-vue3': {
            root: 'huad', // root global variable
            commonjs2: '@xa-web/hua-design-vue3', // module.exports = xxx
            commonjs: '@xa-web/hua-design-vue3', // exports[“Library”] = xxx
            amd: '@xa-web/hua-design-vue3', // define(["xxx"], factory)
            module: '@xa-web/hua-design-vue3'
        }
    });
}

externalDep(config);

module.exports = config;
`

**Comment by CoderQuixote** [comment]
rspack配置如下
`
const path = require('path');
const rspack = require('@rspack/core');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const {VueLoaderPlugin} = require('vue-loader');
const {RsdoctorRspackPlugin} = require('@rsdoctor/rspack-plugin');

function resolve(moduleName) {
    return require.resolve(moduleName);
}

function assertResolve(dir) {
    return path.join(__dirname, dir);
}

const config = {
    context: __dirname,
    mode: 'production',
    devtool: false,
    target: ['web', 'es5'],
    entry: {
        'buildQuickly.all.umd.min': ['./src/entry.js'],
        'buildQuickly.all.umd': ['./src/entry.js'],
        'buildQuickly.renderEngine.umd.min': ['./src/engineEntry.js'],
        'buildQuickly.renderEngine.umd': ['./src/engineEntry.js']
    },
    output: {
        clean: true,
        filename: '[name].js',
        library: {
            name: 'buildQuickly',
            type: 'umd'
        },
        path: path.resolve(__dirname, 'dist')
    },
    optimization: {
        minimize: true,
        minimizer: [
            new rspack.SwcJsMinimizerRspackPlugin({
                test: /min/,
                minimizerOptions: {
                    format: {
                        comments: false,
                    },
                },
            }),
            new rspack.LightningCssMinimizerRspackPlugin({
                include: /min/,
                minimizerOptions: {
                    errorRecovery: false,
                },
            }),
        ]
    },
    externals: [],
    resolve: {
        modules: ['node_modules', path.join(__dirname, '../node_modules')],
        extensions: [
            '.web.tsx',
            '.web.ts',
            '.web.jsx',
            '.web.js',
            '.ts',
            '.tsx',
            '.js',
            '.jsx',
            '.vue',
            '.md',
            '.json'
        ],
        alias: {
            '@': assertResolve('src'),
            public: assertResolve('public')
        },
        fallback: ['child_process', 'cluster', 'dgram', 'dns', 'fs', 'module', 'net', 'readline', 'repl', 'tls'].reduce(
            (acc, name) => Object.assign({}, acc, {[name]: 'empty'}),
            {}
        )
    },
    plugins: [
        ...(process.env.RSDOCTOR ? [
            new RsdoctorRspackPlugin({
                features: {
                    resolver: true
                },
                supports: {
                    generateTileGraph: true
                },
                port: 120
            })
        ] : []),
        new VueLoaderPlugin(),
        // new rspack.CssExtractRspackPlugin(),
        new CaseSensitivePathsPlugin()],
    experiments: {
        css: true
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'vue-loader',
                        options: {
                            // 注意，为了绝大多数功能的可用性，请确保该选项为 `true`
                            experimentalInlineMatchResource: true
                        }
                    }
                ]
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            // 插件先执行 再执行预设
                            plugins: ['@vue/babel-plugin-jsx'],
                            presets: ['@babel/preset-env']
                        }
                    }
                ]
            },
            // {
            //     test: /\.css$/i,
            //     use: [
            //         rspack.CssExtractRspackPlugin.loader,
            //         'css-loader',
            //         {
            //             loader: 'postcss-loader',
            //             options: {
            //                 postcssOptions: {
            //                     plugins: ['autoprefixer']
            //                 },
            //                 sourceMap: true
            //             }
            //         }
            //     ],
            //     type: 'javascript/auto'
            // },

            {
                test: /\.less$/,
                loader: 'less-loader',
                type: 'css'
            },
            {
                test: /\.svg$/,
                use: ['vue-loader', resolve('./build/loaders/vue-svg-loader.js')]
            }
        ]
    }
};

function externalDep(config) {
    config.externals.push({
        vue: {
            root: 'Vue',
            commonjs2: 'vue',
            commonjs: 'vue',
            amd: 'vue',
            module: 'vue'
        }
    });

    config.externals.push({
        dayjs: {
            root: 'dayjs',
            commonjs2: 'dayjs',
            commonjs: 'dayjs',
            amd: 'dayjs',
            module: 'dayjs'
        }
    });


    config.externals.push(function ({_context, request}, callback) {
        if (/^dayjs\/plugin\//.test(request)) {
            const name = request.replace(/\//g, '_');
            return callback(null, {
                root: name,
                commonjs2: name,
                commonjs: name,
                amd: name,
                module: name
            });
        }
        callback();
    });

    config.externals.push({
        '@xa-web/hua-design-vue3': {
            root: 'huad', // root global variable
            commonjs2: '@xa-web/hua-design-vue3', // module.exports = xxx
            commonjs: '@xa-web/hua-design-vue3', // exports[“Library”] = xxx
            amd: '@xa-web/hua-design-vue3', // define(["xxx"], factory)
            module: '@xa-web/hua-design-vue3'
        }
    });
}

externalDep(config);

module.exports = config;
`

**Comment by stulip** [comment]
<img width="844" alt="image" src="https://github.com/user-attachments/assets/5b451807-6880-4e0f-b6a7-fc59749e7d7a">
css 打包出来存在一堆乱码的东西，导致模块丢失无法加载，排查了很久才发现是 css 打包出问题了，换回 1.0.0-alpha.5 就没问题，已经几个月了这个问题还没解决

scss 配置如下
<img width="680" alt="image" src="https://github.com/user-attachments/assets/6c92da9d-139c-4ef7-8255-4500e6e93710">

**Comment by LingyuCoder** [comment]
> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/5770971/371920614-5b451807-6880-4e0f-b6a7-fc59749e7d7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjU0ODEsIm5iZiI6MTcyNzY2NTE4MSwicGF0aCI6Ii81NzcwOTcxLzM3MTkyMDYxNC01YjQ1MTgwNy02ODgwLTRlMGYtYjZhNy1mYzU5NzQ5ZTdkN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDI1OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJkNjcxNmQ0MmQxYmIyZjY4YzIxYjcwZDg5NWU2N2EzZWRjZDdmMGIzNzgwMzlkYWViZGU2MzM2M2Y2NmJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JWysq6HRTZURrqLAay4CAJiFVKZYdE4ot77cU3iB6rk"> css 打包出来存在一堆乱码的东西，导致模块丢失无法加载，排查了很久才发现是 css 打包出问题了，换回 1.0.0-alpha.5 就没问题，已经几个月了这个问题还没解决
> scss 配置如下 <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/5770971/371921301-6c92da9d-139c-4ef7-8255-4500e6e93710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjU0ODEsIm5iZiI6MTcyNzY2NTE4MSwicGF0aCI6Ii81NzcwOTcxLzM3MTkyMTMwMS02YzkyZGE5ZC0xMzljLTRlZjctODI1NS00NTAwZTZlOTM3MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDI1OTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE0ZmQ1ZmZjZmRhNWJlY2YyYTM1MzIyMWM0OWM5NmU4ODViNzMwZjZlZGM2MjJmZTM4YjFhYjYyZjQ1MjU3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BxkZfCGoPFZcuSUFZrP4Cf6mVaJWM54toE97k50OHBQ">

乱码问题看起来是一个独立的问题，可以单开一个新的 issue，并提供最小复现以协助排查

**Comment by JSerFeng** [comment]
issue 中加载了不存在的，尝试一下升级到最新的 rspack

@stulip 提到的问题，看起来像乱码的是 css 的 (meta 信息压缩)[https://rspack.dev/config/output#outputcssheaddatacompression]，不会影响css 加载

**Comment by stulip** [comment]
更新最新版本之后报错问题没有了

**Comment by stulip** [comment]
> issue 中加载了不存在的，尝试一下升级到最新的 rspack
> 
> [@stulip](https://github.com/stulip) 提到的问题，看起来像乱码的是 css 的 [meta 信息压缩](https://rspack.dev/config/output#outputcssheaddatacompression)，不会影响css 加载

非常感谢，但是编译控制台会输出对应 warning 

![Image](https://github.com/user-attachments/assets/ede50192-b1bd-4ae1-9359-175dc4e95b28)

**Comment by LingyuCoder** [comment]
> > issue 中加载了不存在的，尝试一下升级到最新的 rspack
> > [@stulip](https://github.com/stulip) 提到的问题，看起来像乱码的是 css 的 [meta 信息压缩](https://rspack.dev/config/output#outputcssheaddatacompression)，不会影响css 加载
> 
> 遇到相同的问题，因为 scss 文件路径被乱码导致对应的文件加载失败。（如下图，p[e].call 失败，因为 p[e] === undefined）
> 
> 当前： rspack 版本1.0.9. 切换 0.7.4 时不再出现此问题。
> 
> js输出格式: systemjs
> 
> ![Image](https://github.com/user-attachments/assets/435578d8-9ebd-4e5c-ac93-79367876409d)

能否提供一个最小复现项目协助排查？

**Comment by ckken** [comment]
+1

**Comment by ckken** [comment]
> > issue 中加载了不存在的，尝试一下升级到最新的 rspack
> > [@stulip](https://github.com/stulip) 提到的问题，看起来像乱码的是 css 的 [meta 信息压缩](https://rspack.dev/config/output#outputcssheaddatacompression)，不会影响css 加载
> 
> 遇到相同的问题，因为 scss 文件路径被乱码导致对应的文件加载失败。（如下图，p[e].call 失败，因为 p[e] === undefined）
> 
> 当前： rspack 版本1.0.9. 切换 0.7.4 时不再出现此问题。
> 
> js输出格式: systemjs
> 
> ![Image](https://github.com/user-attachments/assets/435578d8-9ebd-4e5c-ac93-79367876409d)

0.7 的版本不会有这个问题 最近升级后才出现

**Comment by ckken** [comment]
把压缩关闭了 应该可以正常访问

**Comment by JSerFeng** [comment]
来个复现demo可以迅速修复

**Comment by ckken** [comment]
![Image](https://github.com/user-attachments/assets/f37aba47-f762-49c3-b40c-399d59bbd069)
![Image](https://github.com/user-attachments/assets/06120cbb-4650-480e-8ad1-283e236c41a8)
chrome 109一下才会报错 业务代码太多~无法正常呈现

**Comment by ckken** [comment]
> ![Image](https://github.com/user-attachments/assets/f37aba47-f762-49c3-b40c-399d59bbd069) ![Image](https://github.com/user-attachments/assets/06120cbb-4650-480e-8ad1-283e236c41a8) chrome 109一下才会报错 业务代码太多~无法正常呈现

只有启动 build 压缩 才会报错 其他情况都不会

**Comment by SoonIter** [comment]
@ckken 可能和 lightningcss 的压缩有关，你可以把压缩前的 css 和压缩后的 css 贴一下
可以利用 lightningcss playground https://lightningcss.dev/playground/index.html 辅助调试

**Comment by ckken** [comment]
定位到 确定是 lightningcss 的压缩问题

**Comment by ckken** [comment]
@SoonIter 确认了 是 lightning css 的问题！谢谢

**Comment by SoonIter** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/79413249?s=64&amp;u=eae9353263ddfad46817ef38190a455bf06d5cd9&amp;v=4">@SoonIter](https://github.com/SoonIter) 确认了 是 lightning css 的问题！谢谢

😂好的，能定位问题就好，解决了可以把问题代码和具体问题也贴一下，辅助我们修复上游 lightningcss 的问题
@GiveMe-A-Name cc ⚡️

**Comment by ckken** [comment]
@SoonIter 业务代码 10+w行 而且是 兼容性问题 短时间比较难定位 只能排除法 慢慢搞

**Comment by ckken** [comment]
还是建议把 `rspack.SwcJsMinimizerRspackPlugin` 加回来 保证项目的稳定性推进 0.7 测试没问题

**Comment by SoonIter** [comment]
@ckken 
这个问题看上下文猜测是 webpack-runtime 会用 css 变量来定位 module，这些变量是用的 “乱码” 的形式来压缩体积的

这个 “乱码” 过 lightningcss 再压缩一遍出现了问题

所以你只要把开 minimize 前的 css 和关 minimize 后的 css 贴出来就行

**Comment by ckken** [comment]
`output. cssHeadDataCompression:false` 目测解决问题

**Comment by GiveMe-A-Name** [comment]
如果能把出现问题的 css 范围定位的小一点，可以提另外的 issuer 我们来处理。

**Comment by ckken** [comment]
文件确实有点多 或者你们能否提示下 乱码特征 我检索下

**Comment by JSerFeng** [comment]
试试能不能找到报错的那个css文件，然后尝试只引用那个css看看能不能复现，如果可以 把class名字脱敏后可以发给我们排查一下

**Comment by ckken** [comment]
其实除了压缩之外 还有 sass 解析的问题 项目代码量过大 没细查 压缩这个问题比较明显！项目上线后再回归下

**Comment by SoonIter** [comment]
> 这个问题解决了么, 现在遇到了 @SoonIter 

解决方法上面有哈，麻烦提供最小复现

**Comment by flowke** [comment]
> > 这个问题解决了么, 现在遇到了 [@SoonIter](https://github.com/SoonIter)
> 
> 解决方法上面有哈，麻烦提供最小复现

我们的情况比较复杂. 在chrome浏览器里直接没有这种情况.   我们的的页面在webview 里运行.  稳定的复现路径是: 如果webview 的devtool的网络里勾选了停用缓存, 那么勾选后的第一次访问, 必定出现这种情况. 

所以并不是必现.

**Comment by flowke** [comment]
> > 这个问题解决了么, 现在遇到了 [@SoonIter](https://github.com/SoonIter)
> 
> 解决方法上面有哈，麻烦提供最小复现

同时, output. cssHeadDataCompression:false 也无法解决问题, 目前只能回退到 0.7能解决

**Comment by hardfist** [comment]
> > > 这个问题解决了么, 现在遇到了 [@SoonIter](https://github.com/SoonIter)
> > 
> > 
> > 解决方法上面有哈，麻烦提供最小复现
> 
> 我们的情况比较复杂. 在chrome浏览器里直接没有这种情况. 我们的的页面在webview 里运行. 稳定的复现路径是: 如果webview 的devtool的网络里勾选了停用缓存, 那么勾选后的第一次访问, 必定出现这种情况.
> 
> 所以并不是必现.

你用了experiments.css吗？

**Comment by hardfist** [comment]
如果有用户在`experiments.css = true` 的情况下碰到了这个问题，有很大的概率是触发了 https://github.com/webpack/webpack/issues/17611 中的bug，这个是 webpack 目前 experiments.css 的设计和实现问题，我们在跟进解决，这个问题在0.7版本中没出现是因为我们在0.7之前的版本的experiments.css 实现没对齐webpack而在1.0版本中和webpack进行了对齐从而触发了这个bug，如果确认是这个bug建议通过切换到 [rspack.CssExtractRspackPlugin](https://rspack.dev/plugins/rspack/css-extract-rspack-plugin), 这个 bug 我们在高优和webpack team讨论如何解决

**Comment by flowke** [comment]
> 如果有用户在`experiments.css = true` 的情况下碰到了这个问题，有很大的概率是触发了 [webpack/webpack#17611](https://github.com/webpack/webpack/issues/17611) 中的bug，这个是 webpack 目前 experiments.css 的设计和实现问题，我们在跟进解决，这个问题在0.7版本中没出现是因为我们在0.7之前的版本的experiments.css 实现没对齐webpack而在1.0版本中和webpack进行了对齐从而触发了这个bug，如果确认是这个bug建议通过切换到 [rspack.CssExtractRspackPlugin](https://rspack.dev/plugins/rspack/css-extract-rspack-plugin), 这个 bug 我们在高优和webpack team讨论如何解决

用了experiments.css = true,  切回到 [rspack.CssExtractRspackPlugin](https://rspack.dev/plugins/rspack/css-extract-rspack-plugin) 的方案后, 问题解决上. thx

**Comment by rotate-life** [comment]
> 如果有用户在`experiments.css = true` 的情况下碰到了这个问题，有很大的概率是触发了 [webpack/webpack#17611](https://github.com/webpack/webpack/issues/17611) 中的bug，这个是 webpack 目前 experiments.css 的设计和实现问题，我们在跟进解决，这个问题在0.7版本中没出现是因为我们在0.7之前的版本的experiments.css 实现没对齐webpack而在1.0版本中和webpack进行了对齐从而触发了这个bug，如果确认是这个bug建议通过切换到 [rspack.CssExtractRspackPlugin](https://rspack.dev/plugins/rspack/css-extract-rspack-plugin), 这个 bug 我们在高优和webpack team讨论如何解决

有详细的配置吗，我修改后没有生效
