### ISSUE TITLE
[Bug]: runtime bundle throws exception in Safari.  TypeError: undefined is not an object (evaluating e[n].call). 

### ISSUE THREAD

**Issue by fredrik-lindqvist** [web-infra-dev/rspack#8031]
### System Info

System:
OS: macOS 14.2.1,
CPU: Apple M2 pro
Memory: 16gb
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0
npm: 10.8.2
Browsers:
Chrome 121.0.6167.160
Safari 18.0 
npmPackages:
@rspack/cli: 1.0.8
@rspack/core: 1,0.8
@swc/core: 1.7.26

### Details

When running production build in safari 18.0 our app crashes and shows only white screen and in the console an error shows "TypeError: undefined is not an object (evaluating e[n].call)" thrown from our rspack run-time bundle. If we downgrade to 0.7.5 our production build works just fine in safari. 

### Reproduce Steps

1. run production build.
2. Open app in safari 18 and runtime bundle should throw an TypeError.

**Comment by acnebs** [comment]
I've seen this as well, but it is almost impossible to debug. Sometimes the built bundle does this, sometimes it doesn't, and it is very hard to nail down when.

What I can say is that we've had to pin rspack packages to `1.0.0-beta.1` which works consistently. Anything after that breaks, but not consistently.

**Comment by anazaritc** [comment]
I'm having exact this issue. Any fix?

**Comment by anazaritc** [comment]
The fix was simple. Changed the following lines in `rspack.config.ts`:


<img width="750" height="282" alt="Image" src="https://github.com/user-attachments/assets/08b52775-7086-4573-8aa0-48d158272523" />
