### ISSUE TITLE
[Bug]: 如何移除rspack的内置vue-loader，配置用户指定的vue-loader版本？

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rspack#8042]
### System Info

rspack最新版本、rspack-cli

最新的rspack内置vue-loader版本过高，请问如何移除内置vue-loader，配置用户指定的vue-loader？

### Details

最新的rspack内置vue-loader版本过高，请问如何移除内置vue-loader，配置用户指定的vue-loader？

以下bundlerChain里配置没有生效
bundlerChain: (chain, { env, isProd, target, CHAIN_ID }) => {
    chain.module
        .rule("vue")
        .test(/\.vue$/)
        .use("vue-loader")
        .loader("vue-loader");
}

### Reproduce Steps

请问如何移除内置vue-loader，配置用户指定的vue-loader？

**Comment by hardfist** [comment]
rspack没有内置vue-loader

**Comment by Dengpei1688** [comment]
嗯嗯，谢谢回复，应该是我的提问没正确描述好。

描述应该是： rspack提供的Vue 插件如何移除内置的vue-loader v17版本,采用用户指定的vue-loader版本？


Vue 插件提供了对 Vue 3 SFC（单文件组件）的支持，插件内部集成了 [vue-loader](https://vue-loader.vuejs.org/) v17 版本。


下面是引用示例：
import { pluginVue2 } from '@rsbuild/plugin-vue';

export default {
  plugins: [pluginVue2()],
};


请问rspack提供的Vue 插件如何移除内置的vue-loader v17版本,采用用户指定的vue-loader版本？
