### ISSUE TITLE
[Bug]: CopyRspackPlugin.pattern.from not support to specify a file path not regexp

### ISSUE THREAD

**Issue by moonlitusun** [web-infra-dev/rspack#8056]
### System Info

Mac os

### Details

There appears to be a bug in Rspack's CopyPlugin where it does not properly handle patterns that specify a single file. This functionality is supported in webpack's CopyWebpackPlugin, but it seems to be missing or not working as expected in Rspack.

### Reproduce Steps

1. Configure CopyPlugin in Rspack config
2. Attempt to copy a specific file using a pattern

```ts
{
  from: '/xx/xx.ts'
}
```

But `/xx/xx.ts*` is working

Expected Behavior:
The plugin should be able to copy a single, specific file when the pattern points to that file.

Actual Behavior:
The plugin fails to copy the file or throws an error (please specify the exact behavior you're seeing).

**Comment by inottn** [comment]
need reproduction

**Comment by moonlitusun** [comment]
I discovered the reason for the error. My path includes a ] character, but when I use other bundlers or use glob patterns myself, I can match it. Is it possible to support this?
![Image](https://github.com/user-attachments/assets/c4dd7568-b110-4a0e-b889-be3741047806)

**Comment by moonlitusun** [comment]
> I discovered the reason for the error. My path includes a ] character, but when I use other bundlers or use glob patterns myself, I can match it. Is it possible to support this? ![Image](https://github.com/user-attachments/assets/c4dd7568-b110-4a0e-b889-be3741047806)

![Image](https://github.com/user-attachments/assets/8959e9d4-bfa8-4396-8911-944ecd28c129)

**Comment by moonlitusun** [comment]
https://codesandbox.io/p/devbox/5j83p2?file=%2Frspack.config.mjs%3A45%2C13
