### ISSUE TITLE
[Bug]: Barrel file export with TypeScript type breaks import

### ISSUE THREAD

**Issue by andreme** [web-infra-dev/rspack#8078]
### System Info

rs build 1.0.8

### Details

When a barrel file exports both a TS type and a function, the build fails with an error about the type. Commenting out the export for the type makes the build succeed.

```ts
export {DummyType, testFunc} from './dummy' // fails
// export {/*DummyType,*/ testFunc} from './dummy' // works
```

```ts
// dummy.ts
export interface DummyType {
    a: boolean
}

export function testFunc() {
    console.log('test')
}
```

### Reproduce link

https://github.com/andreme/rsbuild-barrel-file-error

### Reproduce Steps

Run `pnpm build`

Error:
```
File: /workspaces/rspack-repro/src/dummy_export.ts:1:1
  × HarmonyLinkingError: export 'DummyType' (reexported as 'DummyType') was not found in './dummy' (possible exports: testFunc)
   ╭─[1:0]
 1 │ export { DummyType, testFunc } from './dummy'; // fails
   · ──────────────────────────────────────────────
 2 │  // export {/*DummyType,*/ testFunc} from './dummy' // works
   ╰────
```

**Comment by markmssd** [comment]
In case that helps you get unblocked, as a workaround we import the type first, then re-export it:

```
import { DummyType } from './dummy'

export { testFunc } from './dummy'
export { DummyType }
```

**Comment by JSerFeng** [comment]
Because we can only see single typescript file at present, there is no information that can let Rspack know that DummyType is a type.

Here are solutions that can help you:

1. ```export {type DummyType } from "./dummy"``` this way Rspack can know that DummyType is type
2. Use this [config](https://rspack.dev/zh/config/module#moduleparserjavascriptexportspresence) to ignore the error
