### ISSUE TITLE
[Bug]: crash when using watching.invalidate in middleware which is apply in setupMiddlewares

### ISSUE THREAD

**Issue by Godsleeper** [web-infra-dev/rspack#8082]
### System Info

  System:
    OS: macOS 15.0
    CPU: (14) x64 Apple M3 Max
    Memory: 773.21 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 18.0
  npmPackages:
    @rspack/cli: ^1.0.8 => 1.0.8
    @rspack/core: ^1.0.8 => 1.0.8
    @rspack/dev-server: ^1.0.7 => 1.0.7

### Details

ERROR MESSAGE
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have event sender
Location: ./crates/rspack_core/src/compiler/module_executor/mod.rs:179

Backtrace omitted.

devServer will crash when using watching.invalidate.
works ok in my original webpack code for five years，how can I transform to rspack？

### Reproduce Steps

DEMO Example
add this code
```js
new RspackDevServer({
 setupMiddlewares(middlewares, devServer) {
     const clientWatcher = devServer.middleware.context.watching;
     middlewares.push((req, res, next) => {
          clientWatcher.invalidate(() => {
          next();
       })
    })
    return middlewares;
   }, clientWater);
}
```

**Comment by LingyuCoder** [comment]
Tried to reproduce the problem but failed. Could you provide a complete repro?
