### ISSUE TITLE
[Bug]: Default export from `@rspack/core` does not have TypeScript types

### ISSUE THREAD

**Issue by mxmason** [web-infra-dev/rspack#8095]
### System Info

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 71.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.1.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.5
  npmPackages:
    @rspack/cli: ^1.0.10 => 1.0.10 
    @rspack/core: ^1.0.10 => 1.0.10 
    @rspack/dev-server: ^1.0.8 => 1.0.8 

### Details

While the following code runs as expected, the types for Compiler#run only show up if one imports `rspack` as a **named** import. Note: this is true in both ESM and CommonJS.

```js
const rspack = require('@rspack/core')

const compiler = rspack(config)

compiler.run(...)
```

![Image](https://github.com/user-attachments/assets/7264f430-10eb-458a-8ace-d040e7f2678f)
![Image](https://github.com/user-attachments/assets/8c0a7781-6e66-422a-a876-3cd6d25dfe97)

### Reproduce Steps

In an rspack project, try the following import scenarios

**ESM, has types:**
```js
import { rspack } from '@rspack/core'

const configs = require('./path/to/config.js')

const compiler = rspack(configs)
```

**ESM, no types:**
```js
import rspack from '@rspack/core'

const configs = require('./path/to/config.js')

const compiler = rspack(configs)
```

**CommonJS, has types:**
```js
const { rspack } = require('@rspack/core')

const configs = require('./path/to/config.js')

const compiler = rspack(configs)
```

**CommonJS, no types:**
```js
const rspack = require('@rspack/core')

const configs = require('./path/to/config.js')

const compiler = rspack(configs)
```

**Comment by SoonIter** [comment]
In fact, rspack does not have default export in esm. It can work normally because it is converted to cjs. At present, there is only cjs dist in `@rspack/core`

The default export is too complicated, I strongly recommend that users use named export in my opinion, which will make this problem much easier.

```ts
import { rspack } from '@rspack/core';
```

js api declares named export in the document. https://rspack.dev/api/javascript-api/index
