### ISSUE TITLE
[Bug]: `swc-loader` unable to properly set and use breakpoints

### ISSUE THREAD

**Issue by MBearo** [web-infra-dev/rspack#8108]
### System Info

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.36 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.100
    Edge: 112.0.1722.68
    Safari: 18.0
  npmPackages:
    @rspack/cli: ^1.0.10 => 1.0.10 
    @rspack/core: ^1.0.10 => 1.0.10 

### Details

https://github.com/MBearo/issue-rspack-sourcemap-error

![Image](https://github.com/user-attachments/assets/f558c2a9-e8b2-4e18-92c5-2f0d9caee3dc)

This is a demo. After running `npm i && npm run bundle:rs`, the sourcemap in the bundled output is missing some mappings. However, the same configuration works correctly when using webpack and ts-loader.

### Reproduce Steps

npm i
npm run bundle:rs

**Comment by SyMind** [comment]
@MBearo Try 1.0.13
