### ISSUE TITLE
Svg as inline component not working in vue 3 with rspack

### ISSUE THREAD

**Issue by hammadahamed** [web-infra-dev/rspack#8117]
Is the any loader that can be used to load svg's as inline components in rspack
vite has ` vite-svg-loader`

tried different ways nothing is working in rspack

**Comment by LingyuCoder** [comment]
cc @9aoy

**Comment by 9aoy** [comment]
try https://github.com/damianstasik/vue-svg-loader

**Comment by hammadahamed** [comment]
> cc [@9aoy](https://github.com/9aoy)

This isn't working either.
`vue-svg-loader` keeps throwing the template-compiler-sfc version error (which it uses internally)., which is basically intended to be for `vue2`
