### ISSUE TITLE
[Feature]: Expose nested modules in `compilation.chunkGraph.getChunkModules`

### ISSUE THREAD

**Issue by abettadapur** [web-infra-dev/rspack#8130]
### What problem does this feature solve?

When using `moduleConcatenation:true`, the call to `compilation.chunkGraph.getChunkModules(chunk)` only returns the top level concatenated modules, and there is no way to access the nested modules.

In Webpack, you can access the nested modules with
```
type ConcatenatedModule {
    ...
    modules: Module[]
}
```

I saw #6784 exposes this information to the stats plugin. Can we also expose this information to the JS API?

### What does the proposed API of configuration look like?

Expose `modules` property on concatenated modules, which would be a list of the modules that are contained in the ConcatenatedModule

**Comment by SyMind** [comment]
@abettadapur Would you like to give me a use case.

**Comment by abettadapur** [comment]
@SyMind I have plugins in my application that want to inspect the source files that are included in an entry point, even if multiple entry points were built. The particular use case is to flag that certain sensitive files were included in the compilation that were not supposed to be
