### ISSUE TITLE
[Bug]: Bug in initializing worker script : Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#8134]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (32) x64 AMD EPYC 7763 64-Core Processor
    Memory: 115.62 GB / 125.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/share/nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.23.19 - /usr/bin/yarn
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.0/bin/npm
    Watchman: 20240317.093234.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 126.0.6478.126

### Details

I started running into the below error when initializing the worker script with v 1.0.5 and with latest 1.0.11

![Image](https://github.com/user-attachments/assets/cb8e9811-2a63-411b-9b2b-6666889215dc)

it is a simple worker init code as below which was working fine in v1.0.4. 

![Image](https://github.com/user-attachments/assets/c31550e9-b118-4d60-8116-7b66a12a365e)

I reported the same bug in this thread , however the fix which landed in v 1.0.11 still has this issue. 
https://github.com/web-infra-dev/rspack/pull/7866#issuecomment-2406623108

### Reproduce Steps

The original issue was repro by the author here :
https://github.com/web-infra-dev/rspack/pull/7866#issuecomment-2406623108

**Comment by LingyuCoder** [comment]
Seems I have found where the error is. I will try to fix it

**Comment by LingyuCoder** [comment]
Please try this canary version `@rspack/core@1.0.12-canary-5152cd23-20241016102625`

**Comment by pushkargupta9807** [comment]
@LingyuCoder is the above canary version published? I could not find that in the npm store.

**Comment by LingyuCoder** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/2663351?s=64&amp;u=b901361c940b41dc06e9b3d373e2d081d09c35e5&amp;v=4">@LingyuCoder](https://github.com/LingyuCoder) is the above canary version published? I could not find that in the npm store.

My fault, we have migrated canary versions to another package. Please use `@rspack/core-canary@1.0.12-canary-5152cd23-20241016102625`.

You can follow this [guide](https://rspack.dev/contribute/development/releasing#using-nightlycanary-version) to override your `@rspack/core` with  `@rspack/core-canary`
