### ISSUE TITLE
[Bug]: Uncaught (in promise) ReferenceError: $RefreshReg$ is not defined

### ISSUE THREAD

**Issue by F-happy** [web-infra-dev/rspack#8153]
### System Info

  System:
    OS: macOS 14.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 23.69 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 17.6
  npmPackages:
    @rspack/cli: 1.0.13 => 1.0.13 
    @rspack/core: 1.0.13 => 1.0.13 
    @rspack/dev-server: 1.0.9 => 1.0.9 
    @rspack/plugin-react-refresh: 1.0.0 => 1.0.0

### Details

When I configure Web Workers and fast-refresh at the same time, the following error occurs.
![Image](https://github.com/user-attachments/assets/7427ebb6-3147-475e-86d3-fac2e45ad80f)

### Reproduce Steps

npm run dev

**Comment by baiwusanyu-c** [comment]
I am the same problem as it is, did you solve it?

**Comment by LingyuCoder** [comment]
> I am the same problem as it is, did you solve it?

Please check if you have added the `[@rspack/plugin-react-refresh](https://www.npmjs.com/package/@rspack/plugin-react-refresh)` plugin.

**Comment by dominic-allica** [comment]
I ran into this from a newly generated react app. rspack.config.js was missing `ReactRefreshPlugin` as the above link indicates.

**Comment by jackiealex** [comment]
the same case, emo
