### ISSUE TITLE
[Bug]: Infinite Rebuild Loop with CopyRspackPlugin in Watch Mode when Using "*.txt" Pattern

### ISSUE THREAD

**Issue by bankmonitor-mihaly-szalai** [web-infra-dev/rspack#8163]
### System Info

**System:**
- OS: macOS 15.0.1
- CPU: (8) arm64 Apple M1
- Memory: 101.53 MB / 16.00 GB
- Shell: 5.9 - /bin/zsh

**Binaries:**
- Node: 22.9.0 - /opt/homebrew/bin/node
- Yarn: 1.22.19 - /opt/homebrew/bin/yarn
- npm: 10.8.3 - /opt/homebrew/bin/npm
- pnpm: 9.12.2 - /opt/homebrew/bin/pnpm

**Browsers:**
- Chrome: 129.0.6668.101
- Safari: 18.0.1

**npmPackages:**
- @rspack/cli: 1.0.13 => 1.0.13 
- @rspack/core: 1.0.13 => 1.0.13 

### Details

I'm experiencing an issue with the CopyRspackPlugin in rspack when using a pattern like `"*.txt"`. When running the compiler in watch mode and making changes to a `.ts` or `.js` file, the compiler enters an infinite loop, continuously creating new builds without stopping.

I attempted to reproduce the issue in a GitHub Codespace, but the problem did not occur there. However, on my Mac, the issue consistently manifests. I've created a sample repository that demonstrates this behavior.

### Reproduce link

https://github.com/bankmonitor-mihaly-szalai/rspack-repro

### Reproduce Steps

1. Run `npm run dev`
2. Make a change in `src/index.js`file
3. Observe the compiler's behavior.

**Comment by inottn** [comment]
Is it similar to this [issue](https://github.com/webpack-contrib/copy-webpack-plugin/issues/602 )?

**Comment by bankmonitor-mihaly-szalai** [comment]
Yes
