### ISSUE TITLE
[Bug]: Set external extension, compilation error during dependent export

### ISSUE THREAD

**Issue by lzxb** [web-infra-dev/rspack#8206]
### System Info

  System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1
    Memory: 106.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.15.8 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.0.1
  npmPackages:
    @rspack/cli: 1.0.14 => 1.0.14 
    @rspack/core: 1.0.14 => 1.0.14 

### Details

Named export is normal, but all exports are incorrect
```js
// Compilation failed
export * from 'test2';
// Compilation successful
export { test2 } from 'test2'

export function test1 () {}
```
![Image](https://github.com/user-attachments/assets/1c4d9350-7117-4c13-99b7-53db9beb38e4)

### Reproduce link

https://github.com/lzxb/rspack-externals-error

### Reproduce Steps

1. rspack.config.js
```js
{
    externals: ['test2']
}
```
2. packages/test1/index.js
```js
export * from 'test2';
```
3. Run command
```bash
pnpm build
```

**Comment by chenjiahan** [comment]
Hi, can you try the `modern-module` type? It should work:

![Image](https://github.com/user-attachments/assets/9eb5cc43-bf5d-493d-ac0f-faa4d2c12890)

@fi3ework When will we add documentation for `modern-module`?

**Comment by lzxb** [comment]
![Image](https://github.com/user-attachments/assets/946a330c-a218-4181-bc55-833a4d8b16d1)
The exported result is missing

**Comment by fi3ework** [comment]
> Hi, can you try the modern-module type? It should work:

Currently, it does not work with `modern-module` either. `export *` is still under track https://github.com/web-infra-dev/rslib/issues/45. I used to try to implement it in `modern-module` only, but seems it should be fixed as long as `output.module = true` and `module` external type used together.

> When will we add documentation for modern-module?

Not in a hurry, many edge cases need to be addressed. We might add it to documentation after Rslib becoming more stable.

**Comment by lzxb** [comment]
![Image](https://github.com/user-attachments/assets/36330f5a-a2f0-4e30-9c70-e5d427fb2204)

**Comment by fi3ework** [comment]
I will continue working on preserving `export *` this week. I found a way to use webpack before, but Rspack is not suitable.
