### ISSUE TITLE
[Bug]: Website crashed https://rspack.dev/zh/config/module

### ISSUE THREAD

**Issue by cangSDARM** [web-infra-dev/rspack#8218]
### System Info

none

### Details

![Image](https://github.com/user-attachments/assets/e755fb57-2f44-4d4d-8650-738a832b142a)

### Reproduce Steps

https://rspack.dev/zh/config/module
https://rspack.dev/config/module

**Comment by inottn** [comment]
Thank you for the feedback, I will fix it later.
