### ISSUE TITLE
[Feature]: Does it support different values ​​for the same environment variable (process.env.XXXX) in different entries of a multi-entry project?

### ISSUE THREAD

**Issue by moonsky-all** [web-infra-dev/rspack#8234]
如:
```js
module.exports = {
  entry: {
    foo: './foo.js',
    bar: './bar.js',
  },
}
```
```js
// foo.js & bar.js
import {VALUE} from './const';
```
```js
// const.js
// 期望：
// 当从 foo.js import 拿到的是 ‘foo’, 
// 从 bar.js import 拿到的是 'bar'
export const VALUE = process.env.DIFF_ENTRY_VAR;
```

期望`foo.js`和`bar.js`两个（或更多）入口从同一个资源`const.js`，拿到的环境变量是属于自身这个入口的值

不知道是否支持这种配置？

**Comment by chenjiahan** [comment]
Rspack's `define` does not support this, because `define` can only replace an identifier with a fixed expression. For this requirement, you can consider dynamically setting a value through runtime code.

Rspack 的 define 不支持这种用法，因为 define 只能将标识符替换为一个固定的表达式。对于这个需求，你可以考虑在通过运行时代码来动态设置一个值。
