### ISSUE TITLE
[Feature]: Support Parser Hooks

### ISSUE THREAD

**Issue by Geylnu** [web-infra-dev/rspack#8247]
### What problem does this feature solve?

我正在将 https://github.com/privatenumber/webpack-json-access-optimizer 这个插件迁移到rspack，其中使用了“JavascriptParser Hooks” 来查找对应的函数，但是rspack缺少这个hooks，我发现此前已有相关的PR：https://github.com/web-infra-dev/rspack/pull/3690 ，但是最终没有被合并，rspack最终打算支持这个hooks吗？如果不支持，我是否应该用SWC插件来实现该逻辑？
———
I'm migrating the plugin https://github.com/privatenumber/webpack-json-access-optimizer to rspack, which uses “JavascriptParser Hooks “ to find the corresponding functions, but rspack lacks this hooks, I found that there was a PR for it: https://github.com/web-infra-dev/rspack/pull/3690 but it was not merged in the end. Is rspack finally going to support this hook? If not, should I use the SWC plugin to implement the logic?

Translated with DeepL.com (free version)

### What does the proposed API of configuration look like?

https://webpack.js.org/api/parser/

**Comment by hardfist** [comment]
不打算支持这个hooks，建议用swc的wasm plugin

**Comment by Geylnu** [comment]
@hardfist 我想问一下swc的插件如何与rs-pack通信呢？这里我需要收集js中使用的多语言key，并对多语言JSON做tree shaking，并且再更新多语言key

**Comment by hardfist** [comment]
不太能直接通信，但是loader可以返回额外的metadata或者你写入到临时文件给plugin消费
