### ISSUE TITLE
[Bug]: Cannot find module with id = {xxx} It might have been removed on the Rust side.

### ISSUE THREAD

**Issue by RainedX** [web-infra-dev/rspack#8280]
### System Info

System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.76 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
  npmPackages:
    @rspack/cli: ^1.0.14 => 1.0.14 
    @rspack/core: ^1.0.14 => 1.0.14 
    @rspack/dev-server: ^1.0.9 => 1.0.9 

### Details

`{
      test: /\.scss$/,
      use: [
        rspack.CssExtractRspackPlugin.loader,
        `{`
          loader: 'css-loader',
          options: { modules: false }
        },
        {
          loader: 'builtin:lightningcss-loader',
          options: {
            targets: ['last 2 versions', 'not ie < 11', '> 1%']
          }
        },
        {
          loader: 'sass-loader',
          options: {
            api: 'modern-compiler',
            implementation: require.resolve('sass-embedded')
       }
      }
}`![Image](https://github.com/user-attachments/assets/b0eebf0c-60ee-4f3f-8698-b1b960bd3c1b)
![Image](https://github.com/user-attachments/assets/234c7a15-a162-41f0-aad6-72a8163a3b1f)

for Plugins:
new rspack.CssExtractRspackPlugin({ ignoreOrder: true })

 I dont konw why, it make me confuse

### Reproduce Steps

There was no problem with the first compilation, but when I modified the code, the console directly reported an error

**Comment by RainedX** [comment]
I used style-loader to replace  rspack.CssExtractRspackPlugin.loader, it works well

**Comment by SyMind** [comment]
It's possible that you are calling some methods on a Module on the JavaScript side. The panic occurs when you call methods on a Module that has been removed from the Compilation in Rust.

**Comment by RainedX** [comment]
its my errors, thanks
