### ISSUE TITLE
[Bug]:  experiments.incremental panic in HMR + fast refresh

### ISSUE THREAD

**Issue by kwonoj** [web-infra-dev/rspack#8304]
### System Info

npx envinfo --system --npmPackages '@rspack/*' --binaries --browsers

  System:
    OS: macOS 14.7
    CPU: (12) arm64 Apple M3 Pro
    Memory: 12.04 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.local/state/fnm_multishells/1067_1730394966182/bin/node
    Yarn: 4.5.0 - ~/.local/state/fnm_multishells/1067_1730394966182/bin/yarn
    npm: 10.7.0 - ~/.local/state/fnm_multishells/1067_1730394966182/bin/npm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
  npmPackages:
    @rspack/cli: ^1.1.0-beta.0 => 1.1.0-beta.0
    @rspack/core: ^1.1.0-beta.0 => 1.1.0-beta.0
    @rspack/plugin-react-refresh: 1.0.0-beta.5 => 1.0.0-beta.5

### Details

Unfortunately, stacks are not very helpful.

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  should have best match
Location: crates/rspack_plugin_extract_css/src/plugin.rs:247

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _wasmer_vm_f64_nearest
    at <unknown source file>
 6: _wasmer_vm_f64_nearest
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: __pthread_joiner_wake
    at <unknown source file>
```

### Reproduce link

private code :/

### Reproduce Steps

- Run devserver
- Trigger HMR + fast refresh for the react component

**Comment by JSerFeng** [comment]
Can you try using specific experiments.incremental config, like

```javascript
module.exports = {
  experiments: {
    incremental: {
      make: true,
      buildChunkGraph: true,
    }
  }
}
```

To help us find which part of incremental config causes it

**Comment by kwonoj** [comment]
@JSerFeng Thanks for the detail, didn't aware there's an object.

This config made HMR works:

```
incremental: {
      make: true,
      emitAssets: true,
      inferAsyncModules: true,
      providedExports: true,
      dependenciesDiagnostics: true,
      modulesHashes: true,
      modulesCodegen: true,
      modulesRuntimeRequirements: true,
      buildChunkGraph: false,
    }
```

Only `buildChunkGraph` is `false` and no longer panics.

**Comment by JSerFeng** [comment]
bump

**Comment by JSerFeng** [comment]
can you try @nightly version？Should have fixed now

**Comment by kwonoj** [comment]
Mind confirm which version is correctly nightly? Tried to install nightly via tag, gives 5month old version instead

![Image](https://github.com/user-attachments/assets/a3945632-1596-4b07-b3e6-d09d2d3f426c)

**Comment by JSerFeng** [comment]
Oh, we have separate npm package for canary and nightly version, @rspack/core-canary [here](https://www.npmjs.com/package/@rspack/core-canary?activeTab=versions)

**Comment by kwonoj** [comment]
Maybe I configured something wrong, different pkg name (`-canary`) is not correctly changed in the relevant packages like `@rspack/cli-canary`, there are some amounts of references to `@rspack/core`

like
```
ERROR in ./node_modules/@rspack/dev-server/client/index.js?protocol=wss%3A&hostname=0.0.0.0&port=8082&pathname=%2Fws&logging=info&overlay=false&reconnect=10&hot=true&live-reload=false 62:0-52
    × Module not found: Can't resolve '@rspack/core/hot/log.js'
```

When trying

```
"@rspack/cli-canary": "^1.1.6-canary-837a2e01-20241203084806",
"@rspack/core-canary": "^1.1.6-canary-837a2e01-20241203084806",
```

**Comment by JSerFeng** [comment]
you can use

"@rspack/core": "@rspack/core-canary@^1.1.6-canary-837a2e01-20241203084806"

**Comment by kwonoj** [comment]
Ok thanks. Just tried the latest and seems it no longer panics with buildchunkgraph.
