### ISSUE TITLE
[Bug]: split chunk not respect minSize and maxSize

### ISSUE THREAD

**Issue by bigbossx** [web-infra-dev/rspack#8310]
### System Info

System: mac os
rsbuild: 1.0.18

The split chunk results are very different from those of webpack.

### Details

webpack
![Image](https://github.com/user-attachments/assets/67f7a486-7706-4633-b417-3c25fbf5cd33)

rsbuild

![Image](https://github.com/user-attachments/assets/73dc53ed-dee0-4ce5-8a02-4e5cbd1a79c6)

1. If minSize is set small, for example, I set 100*1024
There will be many small initial blocks less than 100kb, and some of their contents are even just a component
2. maxSize seems unable to limit the size of the initial chunk, they will actually exceed

the summary is that minSize + maxSize cannot produce a product with a suitable size range.

### Reproduce Steps

webpack.config.js
![Image](https://github.com/user-attachments/assets/dab1e8da-f785-43fb-9066-595326f6ac58)

rsbuild.config.ts
![Image](https://github.com/user-attachments/assets/fa927e0c-b874-4eb8-9f58-731ec67ecb71)

**Comment by JSerFeng** [comment]
rsbuild 有一些默认的 cacheGroups，即使用了 override chunkSplit，可以试一下在 tools.rspack 里面直接配置 rspack 的 splitChunks，保持和 webpack 一致，试一下结果是不是还有问题

**Comment by bigbossx** [comment]
https://github.com/bigbossx/split-chunk-bug

@JSerFeng @chenjiahan 我创建了一个最小复现demo，我认为应该足够说明问题了，麻烦看看

**Comment by bigbossx** [comment]
Anything update？

btw，another issue about chunk(split & hash) unstable can also reproduce in https://github.com/bigbossx/split-chunk-bug

## reproduce  step1
```sh
npm run rsbuild > snapshots/1.txt
npm run rsbuild > snapshots/2.txt
npm run rsbuild > snapshots/3.txt

npm run webpack > snapshots/4.txt
npm run webpack > snapshots/5.txt
npm run webpack > snapshots/6.txt
```

## reproduce step2
comparing the chunk hash name and file size of the txt file, it is obvious that rsbuild is different every time, but webpack is the same every time

There will be 2 flaws here
1. not good for caching
2. css was cover by different chunk order。（we can avoid this on the user side through the selector of CSS, but for the build tool, I think the stability of the chunk output is very important.


ps：If you think I should open a new issue, please let me know

**Comment by JSerFeng** [comment]
I'm fixing this, thank you for repro

**Comment by JSerFeng** [comment]
> maxSize seems unable to limit the size of the initial chunk, they will actually exceed

I run the repro [above](https://github.com/bigbossx/split-chunk-bug), turns out the result is similar to webpack when minSize set to 100 * 1024 which has one big file larger than 200 * 1024

webpack:
![Image](https://github.com/user-attachments/assets/bd6f3f11-fb02-4ad1-943a-dbfa3461bcc2)

That's because this chunk contains modules like this: A, B, C. combines the size of any 2 of them will exceed the max size limit

**Comment by bigbossx** [comment]
@JSerFeng 

yes！this chunk 408k is as expected. for this chunk is generate from a 400k js (a super large single file cannot be limited by maxSize, this is expected). webpack is same with it. not bug.

what rspack need to fixed is other main chunks

**Comment by JSerFeng** [comment]
https://github.com/web-infra-dev/rspack/pull/8425 fix the inconsistency during rebuild

> what rspack need to fixed is other main chunks, you may notice that webpack also has 3 small than 200k main chunks. But rspack is not

let me try this

**Comment by bigbossx** [comment]
Awesome～Thank you guy！

**Comment by bigbossx** [comment]
@JSerFeng Thanks again!

just want to know when next rspack and rsbuild version will release.  we really hope that the production chunk is stable

**Comment by JSerFeng** [comment]
should be tomorrow

**Comment by bigbossx** [comment]
<img width="1083" alt="Image" src="https://github.com/user-attachments/assets/1adc8330-e91c-4f00-baec-c1bf1551f6a6" />

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/289b206d-5ca6-4950-a317-75f1bc4a7594" />


@JSerFeng it seem main chunk still not respect maxSize. it over maxSize limit
