### ISSUE TITLE
[Feature]: output.clean does not support keep configuration

### ISSUE THREAD

**Issue by shyim** [web-infra-dev/rspack#8333]
### System Info

```
  System:
    OS: macOS 15.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 34.44 GB / 128.00 GB
    Shell: 3.7.1 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 23.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /etc/profiles/per-user/shyim/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
    pnpm: 9.12.3 - /etc/profiles/per-user/shyim/bin/pnpm
    bun: 1.1.32 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.1
    Safari Technology Preview: 18.0
  npmPackages:
    @rspack/cli: ^1.0.14 => 1.0.14 
    @rspack/core: ^1.0.14 => 1.0.14
```

### Details

I would like to clean keep a specific part that's possible with regular webpack:
https://webpack.js.org/configuration/output/#outputclean

https://github.com/shopware/shopware/blob/trunk/src/Storefront/Resources/app/storefront/webpack.config.js#L250-L252

**Comment by shulaoda** [comment]
This may be because that `output.clean` only support `boolean` and not support below.
```js
{
    keep: /assets\//,
}
```

**Comment by shulaoda** [comment]
Do you have more detailed error information?

**Comment by shyim** [comment]
Whoopsie you are right, we had two times clean 🙈 . I adjusted the Issue to referer to support the clean settings 👍

**Comment by shulaoda** [comment]
Related to #7822
