### ISSUE TITLE
[Bug]: async/await syntax present in build output despite setting externalsType: 'script'

### ISSUE THREAD

**Issue by lichenabson** [web-infra-dev/rspack#8351]
### Version

System: macos
Browser: Chrome126
npmPackages: @rsbuild/core@1.0.18

### Details

I've noticed that when using externalsType: 'script' for asynchronously loading CDN files, the final build output always includes async/await syntax for the asynchronous CDN loading, regardless of the browser range specified in .browserslistrc. This causes compatibility issues in older browsers.

Specifically:

Setting externalsType: 'script' is intended to load CDN files asynchronously.
The .browserslistrc file is configured to target specific browser versions.
However, the build output consistently uses async/await syntax for CDN loading, ignoring the .browserslistrc settings.
This results in compatibility problems with older browsers that don't support async/await.

### Reproduce link

https://www.marscode.cn/ide/7oqyxje9lq9nee

### Reproduce Steps

![Image](https://github.com/user-attachments/assets/4ee7d721-0b3b-4d49-8ef8-6cb0f1edd9d3)
1. edit  .browserslistrc
2. run build
3. Observe the output after processing the resources

**Comment by inottn** [comment]
The behavior seems consistent with webpack, but webpack provides corresponding warnings.

**Comment by lichenabson** [comment]
So, do rspack or rsbuild have plans to fix this issue?
Or are there other ways I can solve this problem? This is very important to me.

**Comment by lichenabson** [comment]
ok, i will try this
