### ISSUE TITLE
[Feature]: Module Federation: Recursive share version search/resolve

### ISSUE THREAD

**Issue by ScriptedAlchemy** [web-infra-dev/rspack#8375]
### What problem does this feature solve?

Federation fails to find the share version for some repo and package structures. 

- the package is dual esm/cjs and uses a empty {type: module} package.json in a directory 
- the user has a monorepo and the deps are installed above the bundlers context

### What does the proposed API of configuration look like?

The work as been done in `/enhanced`, but needs sync back to rust side of rspack: reference MR https://github.com/module-federation/core/pull/3078

**Comment by inottn** [comment]
I think I can give it a try.
