### ISSUE TITLE
[Bug]: hitting a panic when saving file changes while running with --watch enabled

### ISSUE THREAD

**Issue by klinakerdisy** [web-infra-dev/rspack#8383]
### System Info

  System:
    OS: macOS 14.7.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 15.02 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.volta/tools/image/node/16.20.1/bin/node
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.1/bin/npm
    pnpm: 8.15.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 18.1
  npmPackages:
    @rspack/cli: 1.1.0 => 1.1.0 
    @rspack/core: 1.1.0 => 1.1.0 

### Details

Hi, I started hitting a panic when saving file changes under normal development conditions while running with `--watch` enabled.
The issues started after updating @rspack/cli and @rspack/core from 1.0.14 -> 1.1.0.

```console
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Chunk should be added before
Location: crates/rspack_core/src/chunk_graph/chunk_graph_chunk.rs:185

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _wasmer_vm_f64_nearest
    at <unknown source file>
 6: _wasmer_vm_f64_nearest
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: __pthread_joiner_wake
    at <unknown source file>
 ELIFECYCLE  Command failed with exit code 129.
```

### Reproduce Steps

1. Run `pnpm run rspack --watch`.
2. Make a change to a file and hit save.

Unfortunately it doesn't always happen and there is no obvious pattern to when it does.
A colleague of mine could reproduce it on his x86 Linux system so it's not macOS specific.

**Comment by GiveMe-A-Name** [comment]
Can you provide a produce repo?

**Comment by birtles** [comment]
I think I am seeing this in my [10ten-ja-reader](https://github.com/birchill/10ten-ja-reader/) project.

STR:

1. `git clone https://github.com/birchill/10ten-ja-reader.git`
2. `cd 10ten-ja-reader`
3. `pnpm install`
4. `pnpm start:firefox`
5. Wait for a few minutes for the dictionaries to download and _something_ causing a file to be touched (I think)

I get the following output:

![Image](https://github.com/user-attachments/assets/e0237e92-db7a-445b-9a77-98a454d9ea9c)

I've bisected this to [this changeset](https://github.com/birchill/10ten-ja-reader/commit/5ab9c7f8a89862467ccd62bc02911261a4421589) that updates rspack from 1.0.14 to 1.1.0.

I'm actually not quite sure what triggers the panic so if there's extra logging I can try please let me know.
