### ISSUE TITLE
[Bug]: asset processing broken in production with unicode private area codes

### ISSUE THREAD

**Issue by Narretz** [web-infra-dev/rspack#8384]
### System Info

System: Windows
rspack 1.1.0

It's a doozy.

Here's a repro: https://github.com/Narretz/rspack-sass-asset-bug

run `npm run build:rspack`.

Go to `localhost:8085`

You can see that in the scss div, there are not background images, because
the url is still `url(../assets/leading.svg)` (the asset was not processed).

In the css div, it works.

If you run `npm run build:webpack`, it works in both.

### Details

the problem is this css:

```
body {
  content: var(--some-var, "\f101");
}
```

The private use area unicode breaks the asset processing.

- if you set the unicode as value of content, it works (bug is in variabel parsing somewhere?)
- If you move the block after the asset, it works
- if you use other unicode values, like emojis, it also works
- if the rspack mode is "development" it also works
- works in webpack

These private unicode areas are widely used in ag-grid:

https://github.com/ag-grid/ag-grid/blob/3930d31b4e0f7db83a9a427b151ecb0a52da210d/packages/ag-grid-community/styles/_icon-font-codes.scss#L5

### Reproduce link

https://github.com/Narretz/rspack-sass-asset-bug

### Reproduce Steps

run `npm run build:rspack`.

Go to `localhost:8085`

You can see that in the scss div, there are not background images, because
the url is still `url(../assets/leading.svg)` (the asset was not processed).

In the css div, it works.

**Comment by inottn** [comment]
Thank you for the detailed description of the issue. After looking into it, I found that the problem is not related to Sass; it can be reproduced with this line of CSS: `body{content: "\f101";background-image:url(./img.png)}`. This might be related to the lexer.

**Comment by Narretz** [comment]
Thanks for the quick response!

> it can be reproduced with this line of CSS: `body{content: "\f101";background-image:url(./img.png)}`. 

Interesting!

**Comment by kentets4** [comment]
Founded something like that issue with `@atomaro/icons` package.
In Windows only. Correctly works in MacOS

```
  × Module not found: Can't resolve './Сookie' in
     ╭─[552:15]
 550 │   }
 551 │ });
 552 │ var _ookie_1 = require("./\u0421ookie");
     ·                ────────────────────────
 553 │ Object.defineProperty(exports, "\u0421ookie", {
 554 │   enumerable: true,
     ╰────
```

script route is not normalized, but something normalizes that

**Comment by ahabhgk** [comment]
Not related, @kentets4 please submit a new issue and provide reproduction
