### ISSUE TITLE
[Bug]: css/module崩溃

### ISSUE THREAD

**Issue by fangkyi03** [web-infra-dev/rspack#8387]
### System Info

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 3.42 GB / 31.73 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.93)  
    Internet Explorer: 11.0.19041.1566

### Details

     {
        test: /\.less$/,
        use: [
          {
            loader: 'less-loader',
          },
        ],
        type: 'css/module',
      },
这个type css/module语法有问题 在这个window系统上面 web编译以后会页面会崩溃

main.js:258 undefined factory E:\project\xxx\src\pages\demo\index.module.less
__webpack_require__ @ main.js:258
fn @ main.js:425
eval @ E:\project\xxx\src\pages\demo\demo.js?b251:9
E:\project\biz-operation-web-pc\src\pages\demo\demo.js @ main.js:5
__webpack_require__ @ main.js:260
fn @ main.js:425
eval @ E:\project\xxx\test.js?3efd:5
E:\project\xxxx\test.js @ main.js:20
__webpack_require__ @ main.js:260
(anonymous) @ main.js:1661
(anonymous) @ main.js:1662
main.js:260 Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### Reproduce Steps

import style from './index.less';

在页面的任何一个地方 直接引入一个less文件就崩溃了

**Comment by inottn** [comment]
need reproduction demo

**Comment by fangkyi03** [comment]
提供demo没有用 需要这个系统的才会出这个问题 因为demo里面的内容就是很简单的引入一个less文件 其他没了 只要引入就崩溃

**Comment by fangkyi03** [comment]
如果使用type:'css'这种模式的话 程序不会崩溃 可以正常编译出来 
但是如果使用import style from './index.less' 语法 
或者文件名换成module.less
类型改成type:'css/auto' 就会出现上面一样的崩溃

**Comment by fangkyi03** [comment]
公司3台window 一台window没有出现这个问题 唯一的问题就是antd编译的样式丢了
剩下的两台window都是上面同样的现象

**Comment by fangkyi03** [comment]
类型type:'css'
import  './index.less';
这个不崩溃
import style from './index.less';
崩溃

换成css/module
import style from './index.less';
崩溃
换成css/auto
import style from './index.module.less';
崩溃

**Comment by inottn** [comment]
> 提供demo没有用 需要这个系统的才会出这个问题 因为demo里面的内容就是很简单的引入一个less文件 其他没了 只要引入就崩溃

I was unable to reproduce the issue on Windows 10.

**Comment by fangkyi03** [comment]
是否安装的是跟我同一个版本的系统呢？

**Comment by hardfist** [comment]
@fangkyi03  你要不先提供个复现仓库吧

**Comment by wuyuchang** [comment]
Got the same issue on MacOS
