### ISSUE TITLE
[Bug]: code splitting of dynamic import does not work in Vue2

### ISSUE THREAD

**Issue by ape-casear** [web-infra-dev/rspack#8395]
### System Info

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.5
  npmPackages:
    @rspack/cli: ^1.1.0 => 1.1.0 
    @rspack/core: ^1.1.0 => 1.1.0

### Details

when using dynamic import to split code
```
<script>
export default {
    name: 'app',
    components: {
        Child: () => import('./child.vue'),
    },
}
</script>
```
the output of rspack.build results in a single file main.js

### Reproduce link

https://github.com/ape-casear/rspack-demo

### Reproduce Steps

npm install
node build.js
see dist directory

**Comment by JSerFeng** [comment]
![Image](https://github.com/user-attachments/assets/3c0fa37b-ec2d-49b7-a1e5-b3c3ebb6458b)

You are using swc to transform your code, and set module type to `commonjs`

so code like `import()` becomes `Promise.resolve().then(() => require())`, final output does not contain dynamic import at all
