### ISSUE TITLE
[Bug]: “Failed to resolve loader: ./builtin:swc-loader” when chaining builtin:swc-loader into expose-loader

### ISSUE THREAD

**Issue by andersk** [web-infra-dev/rspack#8430]
### System Info

```
  System:
    OS: Linux 6.11 cpe:/o:nixos:nixos:24.11 24.11 (Vicuna)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 8.45 GB / 15.26 GB
    Container: Yes
    Shell: 5.2.37 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 20.18.0 - ~/.nix-profile/bin/node
    Yarn: 1.22.19 - ~/.nix-profile/bin/yarn
    npm: 10.8.2 - ~/.nix-profile/bin/npm
    pnpm: 9.12.3 - ~/.nix-profile/bin/pnpm
    bun: 1.1.31 - ~/.nix-profile/bin/bun
  Browsers:
    Chromium: 130.0.6723.91
  npmPackages:
    @rspack/cli: ^1.1.1 => 1.1.1 
```

### Details

When trying to chain `builtin:swc-loader` into `expose-loader`, Rspack tries and fails to resolve `./builtin:swc-loader` rather than `builtin:swc-loader`, resulting in an error like `Failed to resolve loader: ./builtin:swc-loader in /tmp/test, error: RspackResolver(NotFound("./builtin:swc-loader"))`.

```js
module.exports = {
  entry: "./foo.js",
  module: {
    rules: [
      {
        test: require.resolve("./foo.js"),
        loader: "expose-loader",
        options: { exposes: "foo" },
      },
      {
        test: /\.js$/,
        exclude: [/node_modules/],
        loader: "builtin:swc-loader",
      },
    ],
  },
};
```

### Reproduce link

https://gist.github.com/andersk/cc79db11483b345f52c13203d2515496

### Reproduce Steps

```console
$ npm i
$ npx rspack
ERROR in ./foo-exposed.js 1:41-75
  × Failed to resolve loader: ./builtin:swc-loader in /tmp/test, error: RspackResolver(NotFound("./builtin:swc-loader"))


Rspack compiled with 1 error in 27 ms
```

**Comment by h-a-n-a** [comment]
The issue is inside expose-loader. 

`contextify` used in expose-loader does not convert the request correctly. As you can see, the value produced by `loaderContext.utils.contextify` is not returned. https://github.com/webpack-contrib/expose-loader/blob/fcd04070854892a394395bac18d74d39ece6cda4/src/utils.js#L102
