### ISSUE TITLE
[Bug]: __webpack_public_path__ runtime does not function correctly when using Webpack Module Federation.

### ISSUE THREAD

**Issue by cairon666** [web-infra-dev/rspack#8436]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 172.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.5
  npmPackages:
    @rsbuild/core: ^1.1.1 => 1.1.1 
    @rsbuild/plugin-react: ^1.0.7 => 1.0.7
```

### Details

When my remote app uses Webpack, __webpack_public_path__ is set to the path of the remoteEntry.js import.
When my remote app uses RSBuild, __webpack_public_path__ is set to window.location.origin.

As a result, when the remote app is loaded with RSBuild, the component is not loaded from the correct path.

The main application is located at http://localhost:1000/, where the host MWF is running. I need to load BugRsbuild, which is located at http://localhost:1000/static/bug-rsbuild/remoteEntry.js. After loading the remoteEntry.js, I expect that the remaining components will be loaded from the path http://localhost:1000/static/bug-rsbuild/..., but it loads everything from http://localhost:1000/..., resulting in an error.

But when use Webpack, work great:
![Image](https://github.com/user-attachments/assets/1db2aa28-cb00-42d1-9e4f-6dc0e0b0b300)
![Image](https://github.com/user-attachments/assets/f0e13445-9666-4de2-83a9-43b9f333049c)
 
When use rspack:
![Image](https://github.com/user-attachments/assets/2c000ca9-36f8-43cd-bf36-3cf0cb2db196)
![Image](https://github.com/user-attachments/assets/f58e0d01-f245-483d-a561-2716fb62a4ca)

### Reproduce link

https://github.com/cairon666/rsbuild-webpack-public-path-bug

### Reproduce Steps

1. donwload nginx
2. load nginx.conf config
3. start nginx
4. npm i
5. npm run dev
6. go to localhost:1000
7. click the buttons

**Comment by inottn** [comment]
This might be related to the default value of `output.publicPath` being `auto` in webpack. You can try setting `output.publicPath` to the same value and then see if the results are consistent.

**Comment by cairon666** [comment]
It seems that the issue was resolved by adding `output.publicPath: "auto"`. Thank you!
