### ISSUE TITLE
[Bug]:using docusaurus edit mdx or md file, process crash.

### ISSUE THREAD

**Issue by zycgit** [web-infra-dev/rspack#8480]
### System Info

  System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 30.03 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Chrome: 130.0.6723.119
    Safari: 17.5

### Details

package.json

  "dependencies": {
    "@docusaurus/core": "^3.6.2",
    "@docusaurus/faster": "^3.6.2",
    "@docusaurus/plugin-content-docs": "^3.6.2",
    "@docusaurus/preset-classic": "^3.6.2",
    "@docusaurus/theme-live-codeblock": "^3.6.2",
    "@easyops-cn/docusaurus-search-local": "^0.40.1",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^1.2.1",
    "prism-react-renderer": "^2.3.1",
    "prismjs": "^1.25.0",
    "punycode": "^2.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@docusaurus/module-type-aliases": "^3.6.2",
    "@docusaurus/types": "^3.6.2"
  },

when using docusaurus edit mdx or md file reprot this info and Process crash.

### Reproduce Steps

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Chunk(ChunkUkey(Ukey(240), PhantomData<rspack_core::chunk::Chunk>)) not found in ChunkByUkey
Location: crates/rspack_core/src/lib.rs:328

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _wasmer_vm_f64_nearest
    at <unknown source file>
 6: _napi_register_module_v1
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: __pthread_start
    at <unknown source file>
zsh: abort      npm run start

**Comment by lebalz** [comment]
Same here, running on WSL 2, docusaurus@3.6.2 with @rspack/core@1.1.2

```bash
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Chunk(ChunkUkey(Ukey(197), PhantomData<rspack_core::chunk::Chunk>)) not found in ChunkByUkey
Location: crates/rspack_core/src/lib.rs:328

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
<empty backtrace>
```

### Workaround
With
```json
// package.json
"resolutions": {
    "@rspack/core": "1.1.1"
},
```
the problem does not occur.

**Comment by chenjiahan** [comment]
Hi, can you provide an reproduction?

**Comment by darrenjon** [comment]
Same problem while editing .mdx or .md file.  docusaurus@3.6.2 with experimental_faster 

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Chunk(ChunkUkey(Ukey(118), PhantomData<rspack_core::chunk::Chunk>)) not found in ChunkByUkey
Location: crates/rspack_core/src/lib.rs:328

Backtrace omitted.

Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
 ELIFECYCLE  Command failed.
Abort trap: 6

**Comment by slorber** [comment]
@ahabhgk I just tried using Rspack 1.1.8 with incremental and it still crashes for me.

Editing a file works fine (it hot reloads) but creating a new MDX file leads to a crash.


```bash
● Client ██████████████████████████████████████████████████ (77%) sealing chunk modules optimization                                                                                                               Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Entrypoint should set_runtime_chunk at build_chunk_graph before get_runtime_chunk
Location: crates/rspack_core/src/chunk_group.rs:136

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _wasmer_vm_f64_nearest
    at <unknown source file>
 6: _napi_register_module_v1
    at <unknown source file>
 7: _napi_register_module_v1
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: __pthread_deallocate
    at <unknown source file>
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/sebastienlorber/Library/Application Support/fnm/node-versions/v22.3.0/installation/bin/node
Arguments: /Users/sebastienlorber/Library/Application Support/fnm/node-versions/v22.3.0/installation/lib/node_modules/yarn/lib/cli.js start
Directory: /Users/sebastienlorber/Desktop/projects/docusaurus/website
Output:
```

See also https://github.com/facebook/docusaurus/pull/10800


To reproduce, go to that Docusaurus branch and run:

```bash
yarn install
yarn start:website
```

```bash
touch website/docs/test.mdx
```

**Comment by ahabhgk** [comment]
@slorber Before we didn't handle `runtimeChunk: true` correctly in incremental, #8866 should fix this, I'm have released a canary version for you to continue on your side: [@rspack-canary/core@1.1.7-canary-d137f4c7-20241227094933](https://www.npmjs.com/package/@rspack-canary/core/v/1.1.7-canary-d137f4c7-20241227094933).

I'm very appreciate that docusaurus are trying incremental. Although I've already spent a lot of time on incremental, it's still lacking large-scale usage at present, it will still take some time to go through the feedback loop of shipping while fixing bugs. I'm happy to help fix any problems that docusaurus encounters when using incremental.

**Comment by slorber** [comment]
Thanks for your support @ahabhgk 

Since Rspack support is opt-in in Docusaurus, and we also have a flag to disable incremental rebuilds, we can try to support it by default, be early adopters, and give feedback.


Isn't 1.1.7 a version to avoid? wondering why the canary isn't using 1.1.8 instead. I'll probably wait for 1.1.9 if you plan to release it soon.

**Comment by chenjiahan** [comment]
Agreed, we should avoid releasing `1.1.7-canary`, I will update the version number in package.json to avoid this.

Rspack 1.2.0 alpha will be released next week, so we probably won't release 1.1.9.
