### ISSUE TITLE
[Bug]: CSS `@layer` order is messed up

### ISSUE THREAD

**Issue by ModyQyW** [web-infra-dev/rspack#8489]
### Version

```sh
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 91.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.70
    Safari: 18.1
  npmPackages:
    @rsbuild/core: ^1.1.4 => 1.1.4 
    @rsbuild/plugin-react: ^1.0.7 => 1.0.7
```

### Details

I have developed a small project using Rsbuild and PrimeReact. I've noticed that both dev and build are generating the CSS `@layer` in the wrong order, resulting in incorrect CSS styles.

![Image](https://github.com/user-attachments/assets/a4fdc800-51ac-4bff-bf4b-c93526bd7093)

As a comparison, PrimeReact officially provides a [Vite Demo](https://github.com/primefaces/primereact-examples/tree/main/vite-styled-tailwind) and when I run it, the CSS `@layer` order is correct and the CSS styles are correct.

![Image](https://github.com/user-attachments/assets/9928eb50-c725-4759-82f8-15400edec97d)

I am not sure if this is a problem with Rspack, Rsbuild, other tools, or other settings. Feel free to let me know. Thanks! 🙏

### Reproduce link

https://github.com/ModyQyW/trimmean-now

### Reproduce Steps

1. `git clone git@github.com:ModyQyW/trimmean-now.git`
2. `pnpm install`
3. `pnpm dev`
4. Check index. The button is not styled accordingly, it is expected to be styled accordingly.

**Comment by JSerFeng** [comment]
There are 2 issues for this:

Webpack and Rspack uses `css-loader` to transform css, which hoists `@import` to the top, that is:

```css
@layer a, b;

@import "./foo"
```

becomes 👇

```css
@import "./foo"
@layer a, b;
```

In your repro, @import point to a module that declare a layer primereact first, so the primereact is the first layer.

If you change the js import order of these 2, like:

```javascript
import "primereact/resources/themes/lara-light-blue/theme.css"
import "./global.css";
```

It's fine, **but** the splitChunks cannot determine the order for some reason, bundlers cannot keep the exec order after manual chunk splitting, see [here](https://github.com/orgs/web-infra-dev/discussions/12)

The solution for you:



```javascript
defineConfig({
  tools: {
    rspack(config) {
      // add a new cache group for global.css
      config.optimization!.splitChunks!.cacheGroups['decl-layers'] = {
        test: /src\/global\.css/,
        chunks: 'all',
        minSize: 0, // you can use enforce as well
        name: 'decl-layers', // make sure index.css has only 1 chunk
        priority: 10000 // make sure index.css gets split first, this way it loads first
      }
    },
  },
})
```

**Comment by ModyQyW** [comment]
Thanks for your kind response! ♥️

I also find that [the next14 example](https://github.com/primefaces/primereact-examples/tree/main/nextjs-styled-tailwind) works fine. It may help more people later come here.
