### ISSUE TITLE
[Feature]: Can I close cssHeadDataCompression to skip css file load?

### ISSUE THREAD

**Issue by Fov6363** [web-infra-dev/rspack#8524]
### What problem does this feature solve?

【Chinese】
现在在构建的产物 css 文件结尾会有一个 head {--xxx} 的逻辑，我理解它是用于检查 css 完整性的一个步骤，经过查看文档，我发现是和cssHeadDataCompression 有关。

我有一个神奇的场景是一个 entry 的产物 js+css，在某些情况下，只需要加载 js 而不需要加载 css，在加载时我会将 css 给它 block 掉，我这样做会导致 js 本身也会报错

这个非常 hack 的操作是一个历史问题，我去修改它的成本比较高，想问一下有没有不检查 css 完整性的办法？

【English】
Now at the end of the built product css file, there will be a head {--xxx} logic. I understand that it is a step to check the integrity of css. After checking the document, I found that it is related to cssHeadDataCompression.

I have a magical scenario where the product of an entry is js+css. In some cases, only js needs to be loaded without loading css. When loading, I will block css. Doing so will cause js itself to report an error.

This very hack operation is a historical issue. I think the cost of modifying it is relatively high. I would like to ask if there is a way to not check the integrity of css?

### What does the proposed API of configuration look like?

output.cssHeadDataCompression = false ?

**Comment by hardfist** [comment]
this is a design issue in experiments.css will be fixed soon，you can try rspackExtractPlugin to avoid this issue

**Comment by Fov6363** [comment]
@hardfist thanks，Expect experiment.css to become production.css
