### ISSUE TITLE
[Bug]: Rspack can not import some packages (This package not support ESM) correctly but webpack working well

### ISSUE THREAD

**Issue by kvsur** [web-infra-dev/rspack#8547]
### System Info

We use `webpack + systemjs(with AMD extral) + single-spa` before,  we can not import the package `eventemitter2` correctly when migrate to `rspack`.

### Details

This is reproduce demo in github repo：https://github.com/kvsur/rspack-demo-amd

### Reproduce link

https://github.com/kvsur/rspack-demo-amd

### Reproduce Steps

https://github.com/kvsur/rspack-demo-amd

**Comment by inottn** [comment]
Rspack does not fully support AMD format yet.

**Comment by kvsur** [comment]
> Rspack does not fully support AMD format yet.

Any version plans here?

**Comment by inottn** [comment]
> Any version plans here?

See https://github.com/web-infra-dev/rspack/issues/4313
