### ISSUE TITLE
[Feature]: Rspack output.clean support CleanOptions.

### ISSUE THREAD

**Issue by GiveMe-A-Name** [web-infra-dev/rspack#8549]
### What problem does this feature solve?

align with webpack, output.clean config support CleanOptions.

### What does the proposed API of configuration look like?

```js
module.exporst = {
  output: { 
    clean: { dry: true, keep: /ignored\/dir\//,  }
  }
}
```

**Comment by chenjiahan** [comment]
Duplicated: https://github.com/web-infra-dev/rspack/issues/7822
