### ISSUE TITLE
Rspack serve error

### ISSUE THREAD

**Issue by fandywen** [web-infra-dev/rspack#8571]
![Image](https://github.com/user-attachments/assets/24e2addd-030d-448e-94d8-70cd5ad5fd8a)
1.@rspack/cli": "^1.1.4"，@rspack/core": "^1.1.4  node:v16.15.0
Rspack serve error

Is there an rspack communication group？(WeChat, QQ)

**Comment by inottn** [comment]
Please create an issue using the corresponding template and include a link to the reproduction. This will help us resolve your issue more quickly.

For this issue, I suspect it might be due to an outdated version of Node.js. The Rspack CLI requires Node.js version >= 18.12.0.

**Comment by fandywen** [comment]
> Please create an issue using the corresponding template and include a link to the reproduction. This will help us resolve your issue more quickly.
> 
> For this issue, I suspect it might be due to an outdated version of Node.js. The Rspack CLI requires Node.js version >= 18.12.0.
@inottn @chenjiahan 
The issue mentioned above is indeed a problem with the node version, and now there is a new problem. Can you help investigate what caused it?
The error message is as follows：
<img width="1049" alt="Image" src="https://github.com/user-attachments/assets/c3273919-bdd0-4261-b49b-82f890cdf971" />

**Comment by chenjiahan** [comment]
Need a reproduction repo

**Comment by inottn** [comment]
> The issue mentioned above is indeed a problem with the node version, and now there is a new problem. Can you help investigate what caused it?

These are two separate issues. You can open a new issue and include a reproduction demo.
