### ISSUE TITLE
[Bug]: build failed on Windows system.

### ISSUE THREAD

**Issue by ZYanan0129** [web-infra-dev/rspack#8601]
### System Info

System: 
Windows 10 
CPU  Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
Binaries:
node 16.18.1
npm 8.19.2
Browsers:
chrome  131.0.6778.70
npmPackages:
@rspack/cli: 1.1.2
@rspack/core: 1.1.2

### Details

Hello, the same configuration in the project can be built successfully and started on macOS, but it fails to build and start on Windows. The error message located can be referenced as follows:
![Image](https://github.com/user-attachments/assets/8575e35d-b126-4453-810e-1c727af03a28)
![Image](https://github.com/user-attachments/assets/ced127fc-f984-4716-ae15-08b174bb423f)
This application used to be built using webpack，could start normally on both macOS and windows systems.
Thanks ~~

### Reproduce Steps

The output configuration information is as follows:
`output: {
    filename: path.join('./', 'js/[name].[chunkhash:8].js'),
    chunkFilename: path.join('./', 'js/[name].[chunkhash:8].chunk.js'),
}`
Thanks ~~

**Comment by LingyuCoder** [comment]
Can you provide the complete code in your picture so that we can determine exactly which character generation error caused it? A repro will be better

**Comment by ZYanan0129** [comment]
The first picture is source code from @rspack/cli，and the code marked in red blocks the application build. 
`return "js\" + chunkId + ".chunk.js";`
 Our output configuration code is `output: { filename: path.join('./', 'js/[name].[chunkhash:8].js'), chunkFilename: path.join('./', 'js/[name].[chunkhash:8].chunk.js'), }`
We guess whether it is related to the Windows system path translation.
Thanks ~~

**Comment by LingyuCoder** [comment]
Actually there is a bug here. The win32 path should not lead to generate wrong runtime code of chunk filename runtime module. I will fix it.
