### ISSUE TITLE
[Bug]: SwcJsMinimizerRspackPlugin The code of the internal infrastructure third-party package, after being compressed by SwcJsMinimizerRspackPlugin, removed the code that needs to be executed, causing execution exceptions.

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#8638]
### System Info

System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 110.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 8.7.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.5

### Details

The code of the internal infrastructure third-party package, after being compressed by SwcJsMinimizerRspackPlugin, removed the code that needs to be executed, causing execution exceptions. (内部基建三方包 的代码经过 SwcJsMinimizerRspackPlugin 压缩后移除了需要执行的代码、导致执行异常)

source code 源代码
```js
function dist_index_es_P(e: string) {
  var t = '';
  if ('string' == typeof e) t = e;
  else
    try {
      t = JSON.stringify(e);
    } catch (r) {
      t = String(e);
    }
  for (var r = 0, o = 0; o < t.length; o++) {
    var n = t.charCodeAt(o);
    r +=
      n < 128
        ? 1
        : n < 2048
        ? 2
        : n < 65536
        ? 3
        : n < 1 << 21
        ? 4
        : n < 1 << 26
        ? 5
        : n < 1 << 31
        ? 6
        : Number.NaN;
  }
  return r;
}
```
after compression 压缩后

```js
function(n) {
    var t = "";
    if ("string" == typeof n) t = n;
    else try {
        t = JSON.stringify(n)
    } catch(e) {
        t = String(n)
    }
    for (var e = 0,
    i = 0; i < t.length; i++) var o = t.charCodeAt(i);
    return r
}
```
The ternary operator chain was removed. 三元运算符链 被移除了

### Reproduce Steps

[rspack-minimizer-bug.zip](https://github.com/user-attachments/files/18037650/rspack-minimizer-bug.zip)

```sh
pnpm install
pnpm build
```
查看压缩后的代码

**Comment by xierenyuan** [comment]
The internal third-party package affects many projects. Please expedite the fix. Thank you very much 😂😂

**Comment by CPunisher** [comment]
This is a bug of swc minifier. I will fix it.

**Comment by chenjiahan** [comment]
Fixed by https://github.com/swc-project/swc/issues/9785.

Rspack will bump SWC to the latest version in v1.2.0 (this month).
