### ISSUE TITLE
[Bug]: cannot compatible the `~` in less-loader

### ISSUE THREAD

**Issue by priority3** [web-infra-dev/rspack#8653]
### Version

```sh
System:
    OS: macOS 12.7.2
    CPU: (8) arm64 Apple M1
    Memory: 135.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 15.6.1
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-less: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-react: ^1.0.1 => 1.0.1
```

### Details

* this is an error when compiler the less file 
![image](https://github.com/user-attachments/assets/8f9f9260-c88f-4115-9ae5-446433a4fb79)
[less-loader](https://github.com/webpack-contrib/less-loader#webpack-resolver),although the `~` has been deprecated, But when migrating some old projects to Rsbuild, I don't want to change a lot of existing CSS file.
* it's working in  `rsbuildv0.5.9` 
![image](https://github.com/user-attachments/assets/11734ea7-e5f9-4408-a794-dbc2a00395ed)

### Reproduce link

https://github.com/priority3/rebuild-less-loader/blob/main/src/App.less#L1

### Reproduce Steps

change `@import '~@animate'` to `@import '@animate'` everything is working.

**Comment by SyMind** [comment]
I will work on it this weak.
