### ISSUE TITLE
[Bug]: `RawSource` from `webpack-sources` is not assignable to rspack's Source

### ISSUE THREAD

**Issue by Areo-Joe** [web-infra-dev/rspack#8664]
### System Info

System: Mac

### Details

When i use `RawSource`, ts says it cannot be assigned to rspack's `Source`.
Seems like the return type of `sourceAndMap()`'s definition is not compatible with webpack-sources:
webpack-sources:
```ts
sourceAndMap(options?: MapOptions): SourceAndMapResult;

export interface SourceAndMapResult {
    source: string | Buffer;
    map: RawSourceMap | null;
}
```
rspack:
```ts 
sourceAndMap(options?: MapOptions): {
    source: string | Buffer;
    map: Object;
};
```

![Image](https://github.com/user-attachments/assets/736c6875-b20e-4cc5-89a2-0b1283927153)

### Reproduce Steps

Copy this to editor and see what ts says:
```ts
import { RawSource } from "webpack-sources";
import type { Compilation } from "@rspack/core";

function addFile(compilation: Compilation, filename: string, content: string) {
  compilation.emitAsset(filename, new RawSource(content));
}
```

**Comment by SyMind** [comment]
Replace `RawSource` that is imported from `webpack-sources` with `compiler.webpack.sources.RawSource`.
