### ISSUE TITLE
[Bug]: Crash since minor version update

### ISSUE THREAD

**Issue by KevinGruber** [web-infra-dev/rspack#8747]
### System Info

  System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.11 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v22.1.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
    Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1.1

### Details

Since upgrading from rspack:~1.0.13 to rspack:~1.1.6 we have the following error:

Nothing further is shown sadly.

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Chunk(ChunkUkey(Ukey(19), PhantomData<rspack_core::chunk::Chunk>)) not found in ChunkByUkey
Location: crates/rspack_core/src/lib.rs:325

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>

### Reproduce Steps

We are using rspack inside of a custom framework/cli so no public repro possible

**Comment by LingyuCoder** [comment]
Too little information makes it difficult to locate the problem. It's better to provide a repro.

**Comment by KevinGruber** [comment]
Hi @LingyuCoder 

thanks for answering my ticket.
I can't do a reproduction as it is a closed source framework which uses rspack under the hood.

What I found out through experimentation is that it only happens since 1.1.0 and when experiments.incremental is turned on.

I turned it off now so not a big deal, but something seemed to have changed from 1.0.x to 1.1.0 regarding this experimental flag.

**Comment by LingyuCoder** [comment]
To those who access this issue, experiments.incremental is not stable at present. If there are any problems, you can turn off it first. Since no repro can be provided, we are unable to locate the problem. Therefore, this issue is closed for now. Wait until a similar problem is encountered later or there is a way to reproduce it, and then we will reopen it.

**Comment by ahabhgk** [comment]
Probably already fixed in v1.1.8, if it's still exists in v1.1.8, then I need a reproduction to find the cause
