### ISSUE TITLE
[Bug]: Rspack cannot correctly recognize @ unobservable @ computed @ action and other decorative symbols in the mobx library

### ISSUE THREAD

**Issue by fandywen** [web-infra-dev/rspack#8768]
### System Info

System Info
System:
MacBook Pro (13-inch, M1, 2020)
Memory:16 GB
Binaries:
Node: 18.15.0
npm: 9.5.0
Browsers:
  Chrome:  131.0.6778.140

npmPackages:
@rspack/cli: ^1.1.6 => 1.1.6
@rspack/core: ^1.1.6 => 1.1.6
mobx:^5.15.7 => 5.15.7
mobx-react:^6.3.1 => 6.3.1
react:^17.0.1 => 17.0.1
react-dom:^17.0.1 => 17.0.1

### Details
React  +Mobx

The loader configuration is as follows 
swc-loader Set decorators: true，Compile without any errors，But The menu bar is blank because the @unobservable @computed @action decoration symbol is not correctly recognized

Remove the @ unobservable @ computed @ action decoration from the code, and the page will display normally

```js
{
  test: /\.(j|t)s(x)?$/,
  exclude: /node_modules/,
  loader: 'builtin:swc-loader',
  options: {
    // js/ts编译配置
    jsc: {
      parser: {
        // 开启ts编译
        syntax:'typescript',
        // 开启tsx编译
        tsx: true,
        // 开启@装饰器编译
        decorators: true,
        // 动态import
        dynamicImport: true,
      },
      transform: {
        // react运行环境配置
        react: {
          // dev模式打开development启动react的开发模式
          development: isDevelopment,
          refresh: isDevelopment,
        },
        // stage 1 的旧版本class decorators
        legacyDecorator: true,
        // 支持 ts emitDecoratorMetadata
        // decoratorMetadata: true,
      },
  },
},
```

### Reproduce Steps

Compile without any errors
<img width="920" alt="Image" src="https://github.com/user-attachments/assets/df1c88c6-c928-4e04-8c50-0cb44548d513" />

But The menu bar is blank
<img width="277" alt="Image" src="https://github.com/user-attachments/assets/c7fd23fe-f0e8-47ad-82e0-b0a917d25cc5" />

Remove the @ unobservable @ computed @ action decoration from the code, and the page will display normally
<img width="257" alt="Image" src="https://github.com/user-attachments/assets/760ba1c7-eb44-4675-9c69-460be83808bb" />

**Comment by SyMind** [comment]
@fandywen which version mobx you used

**Comment by fandywen** [comment]
> [@fandywen](https://github.com/fandywen) which version mobx you used
@SyMind  mobx:5.15.7,mobx-react:6.3.1

**Comment by fandywen** [comment]
@chenjiahan @inottn   Boss, Can you help me investigate the reason?

**Comment by inottn** [comment]
Need a reproduction repo.

**Comment by yee94** [comment]
SAME ISSUE!

**Comment by fandywen** [comment]
> Hello [@fandywen](https://github.com/fandywen), sorry we can't investigate the problem further without reproduction demo, please provide a repro demo by forking [rspack-repro](https://github.com/web-infra-dev/rspack-repro), or provide a minimal GitHub repository by yourself. Issues labeled by `need reproduction` will be closed if no activities in 14 days.

I have found the reason and added loose in the jsx configuration: true

**Comment by fandywen** [comment]
> SAME ISSUE!

I have found the reason and added {loose:true, decorators:true }in the jsx configuration

 jsc: {
            loose: true,
            parser: {
              // 开启ts编译
              syntax:'typescript',
              // 开启tsx编译
              tsx: true,
              // 开启@装饰器编译
              decorators: true,
              // decoratorsBeforeExport: true,
              // 动态import
              dynamicImport: true,
            },

          },

**Comment by yee94** [comment]
Great ! it also works for me!Thanks very much!
